import assert from 'node:assert/strict';
import test from 'node:test';
import {readFile,mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes} from 'node:crypto';
import {createLifestreamServer} from '../../server/src/index.ts';
import {loadProfile} from '../../server/src/config/loader.ts';
import {savedVoiceFixture} from '../../server/test/saved-voice-fixture.ts';
import {FixtureInferenceProvider} from '../../../packages/runtime/dist/inference/fixture.js';

test('rendered acknowledgment cache uses paired audio clock, skips cold/stale work and yields to answer audio',{skip:!process.env.PLAYWRIGHT_MODULE},async t=>{
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage();
 await page.route('http://127.0.0.1:9/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);if(!name)return route.fulfill({contentType:'text/html',body:'<main><h1>Synthetic acknowledgment playback</h1><div id="mouth">Ready</div></main>'});if(!['acknowledgments.js','conversation-output.js'].includes(name))return route.abort();return route.fulfill({contentType:'text/javascript',body:await readFile(new URL('../'+name,import.meta.url))});});await page.goto('http://127.0.0.1:9/');
 const result=await page.evaluate(async()=>{
  const {AcknowledgmentCache}=await import('/acknowledgments.js'),{ConversationOutput}=await import('/conversation-output.js'),audio=new AudioContext();await audio.resume();const hash=async b=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('');
  const bytes=new Uint8Array(96000);for(let i=0;i<48000;i++)new DataView(bytes.buffer).setInt16(i*2,1200,true);const sha=await hash(bytes),track={schemaVersion:'1.0.0',cueSet:'fixture-open-rest',analysisRevision:'fixture-1',timeUnit:'ms',timeOrigin:'audio-start',audioSha256:sha,durationMs:1000,cues:[{startMs:0,endMs:300,cue:'open'},{startMs:300,endMs:1000,cue:'rest'}]},trackBytes=new TextEncoder().encode(JSON.stringify(track)),trackSha=await hash(trackBytes);
  let downloads=0,current=true,requiresSync=true;const clips=['one','two'].map(id=>({id,text:'Synthetic cue.',audio:{format:'pcm_s16le',sampleRateHz:48000,channels:1,bytes:bytes.length,durationMs:1000,sha256:sha},synchronized:true,visemes:{sha256:trackSha,bytes:trackBytes.length,cueSet:track.cueSet,analysisRevision:track.analysisRevision}}));let manifest={schemaVersion:'1.0.0',assistantId:'synthetic',revision:1,binding:'saved-voice-revision',enabled:true,clips};const measurements=[];
  const output=new ConversationOutput({onStopped(){},onComplete(){},onState(){},onReplyAudio:e=>measurements.push(e)});output.socket={readyState:WebSocket.OPEN,send(){},close(){}};output.audio=audio;
  const cache=new AcknowledgmentCache({audio:()=>audio,current:()=>current,manifest:async()=>manifest,artifact:async kind=>{downloads++;return (kind==='audio'?bytes:trackBytes).buffer.slice(0);},mode:()=>({requiresSync,accepts:t=>t.cueSet===track.cueSet}),onMeasure:e=>measurements.push(e)});output.acknowledgments=cache;
  const token=()=>({revision:manifest.revision,binding:manifest.binding,clipIds:manifest.clips.map(c=>c.id)});
  const cold=cache.play('cold',token());await cache.refresh();const before=downloads;output.beginReply('spoken-one');output.receive({type:'acknowledgment',interactionTraceId:'spoken-one',catalog:token()});const first=cache.playing.entry.clip.id;const once=cache.play('spoken-one',token());cache.stop();
  output.beginReply('spoken-two');cache.play('spoken-two',token(),{bufferOffset:.2});const second=cache.playing.entry.clip.id,beforeStart=cache.sample();const playbackDeadline=performance.now()+3000;let during=cache.sample();while((!during.playing||during.sampleOffset===0)&&performance.now()<playbackDeadline){await new Promise(r=>setTimeout(r,10));during=cache.sample();}document.querySelector('#mouth').textContent=during.viseme;const savedEnded=cache.playing.source.onended,segment=cache.playing.segmentId;
  const pcm=new Uint8Array(9600);output.receive({type:'audio',interactionTraceId:'spoken-two',chunk:{segmentId:'answer-segment',frame:{format:{encoding:'pcm_s16le',sampleRateHz:48000,channels:1},sequence:0,sampleOffset:0,sampleCount:4800,dataBase64:btoa(String.fromCharCode(...pcm))}}});const preempted=cache.playing===null,replySources=output.sources.size;savedEnded();const lateCannotRevive=cache.playing===null;
  output.stop();const silent=!cache.sample().playing,noDownloadsOnTurn=downloads===before;
  output.beginReply('ready-race');const readySkipped=cache.play('ready-race',token(),{responseReady:true});const old=token();manifest={...manifest,revision:2,clips:[]};await cache.refresh();const retiredSkipped=cache.play('retired',old);
  manifest={...manifest,revision:3,clips:clips.map(c=>({...c,synchronized:false,visemes:null}))};await cache.refresh();const degradedSkipped=cache.play('degraded',token());requiresSync=false;const explicitFallback=cache.play('fallback',token());cache.clear();current=false;const afterLogout=cache.play('logout',token());output.close();
  return {cold,once,first,second,beforeStart,during,preempted,replySources,lateCannotRevive,silent,noDownloadsOnTurn,readySkipped,retiredSkipped,degradedSkipped,explicitFallback,afterLogout,measurements,segment};
 });
 assert.equal(result.cold,false);assert.equal(result.once,false);assert.notEqual(result.first,result.second);assert.equal(result.beforeStart.playing,false);assert.equal(result.during.clock,'AudioContext.currentTime');assert.equal(result.during.viseme,result.during.sampleOffset/48<300?'open':'rest');assert.ok(result.during.sampleOffset>0);assert.equal(result.preempted,true);assert.equal(result.replySources,1);assert.equal(result.lateCannotRevive,true);assert.equal(result.silent,true);assert.equal(result.noDownloadsOnTurn,true);for(const key of ['readySkipped','retiredSkipped','degradedSkipped','afterLogout'])assert.equal(result[key],false);assert.equal(result.explicitFallback,true);assert.equal(result.measurements.filter(e=>e.kind==='acknowledgment-start').length,3);assert.equal(result.measurements.filter(e=>e.kind==='actual-response-audio').length,1);
});

test('acknowledgment administration covers enablement, preview, stop, pin, finite expiry, removal and restart',{skip:!process.env.PLAYWRIGHT_MODULE},async t=>{
 const root=await mkdtemp(join(tmpdir(),'ack-ui-'));t.after(()=>rm(root,{recursive:true,force:true}));const fixture=await savedVoiceFixture();t.after(fixture.close);const original=FixtureInferenceProvider.prototype.generate;FixtureInferenceProvider.prototype.generate=async function*(){yield {kind:'text',text:JSON.stringify(['I am listening.','Let me think.','One moment.','I hear you.','Let me consider that.','Hmm.','I see.','All right.','Let me take a look.','Okay.'])};yield {kind:'done'};};t.after(()=>{FixtureInferenceProvider.prototype.generate=original;});
 const config=loadProfile('test');config.providers.tts='voxcpm';config.ttsProfile=fixture.profile;config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex'),localAuth={stateDirectory:join(root,'safety'),installerToken};let app=createLifestreamServer({config,localAuth});await app.start();t.after(()=>app.shutdown());
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));t.after(()=>{if(errors.length)console.log('Browser errors:',errors);});page.setDefaultTimeout(12000);await page.goto(`http://127.0.0.1:${app.address().port}/control/#voice`);await page.waitForFunction(()=>window.lifestreamUI);await page.evaluate(()=>window.lifestreamAuth.ready);await page.locator('#auth-username').fill('synthetic-owner');await page.locator('#auth-password').fill('Synthetic-acknowledgment-password-1');await page.locator('#auth-installer-token').fill(installerToken);await page.locator('#auth-setup').click();await page.waitForFunction(()=>window.lifestreamAuth.session);
 await page.evaluate(async()=>{const r=(p,b)=>window.lifestreamAuth.request(p,b,b!==undefined),a=await r('/api/admin/v1/assistants',{displayName:'Synthetic catalog review'});await r(`/api/admin/v1/assistants/${a.assistantId}/activate`,{profileId:a.profile.profileId,expectedActiveRevision:null});});await page.reload();await page.waitForFunction(()=>window.lifestreamUI);await page.locator('[data-destination=voice]').click();const panel=page.locator('.acknowledgment-admin');await panel.getByRole('button',{name:'Refresh acknowledgments',exact:true}).click();await panel.locator('[role=status]').filter({hasText:'0/5'}).waitFor();await panel.getByRole('checkbox').check();await panel.locator('[name=days]').fill('7');await panel.getByRole('button',{name:'Save acknowledgment settings'}).click();
 for(let i=0;i<50;i++){await panel.getByRole('button',{name:'Refresh acknowledgments',exact:true}).click();if(await panel.locator('[data-clips] article').count()===5)break;await page.waitForTimeout(60);}assert.equal(await panel.locator('[data-clips] article').count(),5);const first=panel.locator('[data-clips] article').first();await first.getByRole('button',{name:'Preview acknowledgment',exact:true}).click();await panel.locator('[role=status]').filter({hasText:'Playing audio-only'}).waitFor();await panel.getByRole('button',{name:'Stop acknowledgment preview'}).click();await first.getByRole('button',{name:'Keep indefinitely'}).click();await first.locator('p').filter({hasText:'Kept indefinitely'}).waitFor();await first.getByRole('button',{name:'Restore finite expiry'}).click();await page.waitForFunction(()=>!document.querySelector('.acknowledgment-admin [data-clips] article p').textContent.includes('Kept indefinitely'));await first.getByRole('button',{name:'Extend by default lifetime'}).click();await page.waitForTimeout(100);await first.getByRole('button',{name:'Keep indefinitely'}).click();await first.locator('p').filter({hasText:'Kept indefinitely'}).waitFor();
 if(process.env.ACK_SCREENSHOT){await panel.scrollIntoViewIfNeeded();await page.screenshot({path:process.env.ACK_SCREENSHOT,fullPage:true});await page.setViewportSize({width:390,height:844});await panel.scrollIntoViewIfNeeded();await page.screenshot({path:process.env.ACK_SCREENSHOT.replace('.png','-mobile.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.setViewportSize({width:1440,height:1000});}
 await page.reload();await page.waitForFunction(()=>window.lifestreamUI);await panel.getByRole('button',{name:'Refresh acknowledgments',exact:true}).click();await first.locator('p').filter({hasText:'Kept indefinitely'}).waitFor();assert.equal(await panel.locator('[name=days]').inputValue(),'7');await first.getByRole('button',{name:'Remove acknowledgment'}).click();await panel.getByRole('checkbox').uncheck();await panel.getByRole('button',{name:'Save acknowledgment settings'}).click();await page.reload();await page.waitForFunction(()=>window.lifestreamUI);await panel.getByRole('button',{name:'Refresh acknowledgments',exact:true}).click();assert.equal(await panel.getByRole('checkbox').isChecked(),false);assert.deepEqual(errors,[]);
});
