import assert from 'node:assert/strict';
import test from 'node:test';
import {readFile,mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes} from 'node:crypto';
import {createLifestreamServer} from '../../server/src/index.ts';
import {loadProfile} from '../../server/src/config/loader.ts';
import {savedVoiceFixture} from '../../server/test/saved-voice-fixture.ts';
import {presentationVendor} from '../../server/src/runtime/presentation-vendor.ts';
import {FixtureInferenceProvider} from '../../../packages/runtime/dist/inference/fixture.js';

test('expired acknowledgment polling skips optional cues without expiring the conversation or renewing administration',{skip:!process.env.PLAYWRIGHT_MODULE,timeout:45000},async t=>{
 const root=await mkdtemp(join(tmpdir(),'ack-idle-'));t.after(()=>rm(root,{recursive:true,force:true}));let now=Date.now();
 const config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};
 const installerToken=randomBytes(32).toString('hex'),password=randomBytes(32).toString('hex');
 const app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'safety'),installerToken,now:()=>now},audiencePrivacy:{sourceIds:[]}});await app.start();t.after(()=>app.shutdown());
 // Silence is injected at the device seam; no physical capture or provider call.
 app.providers.stt={async *transcribe(){throw Error('Silent capture must not invoke recognition');}};app.providers.tts={};
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(12000);
 await page.addInitScript(()=>{window.audienceMessages=0;const NativeEventSource=EventSource;window.EventSource=class extends NativeEventSource{constructor(...args){super(...args);this.addEventListener('message',()=>window.audienceMessages++);}};navigator.mediaDevices.getUserMedia=async()=>{const audio=new AudioContext();await audio.resume();const source=audio.createMediaStreamDestination();window.syntheticCapture=source.stream;return source.stream;};});
 const base=`http://127.0.0.1:${app.address().port}`;await page.goto(base+'/control/');await page.waitForFunction(()=>window.lifestreamUI);await page.locator('#auth-username').fill('synthetic-owner');await page.locator('#auth-password').fill(password);await page.locator('#auth-installer-token').fill(installerToken);await page.locator('#auth-setup').click();await page.waitForFunction(()=>window.lifestreamAuth.session);
 const assistantId=await page.evaluate(async()=>{const r=(p,b)=>window.lifestreamAuth.request(p,b,b!==undefined),a=await r('/api/admin/v1/assistants',{displayName:'Synthetic idle conversation'});await r(`/api/admin/v1/assistants/${a.assistantId}/activate`,{profileId:a.profile.profileId,expectedActiveRevision:null});await r('/api/runtime/v1/session-context',{expectedRevision:0,mode:'audio',audienceScope:'authenticatedSession'});return a.assistantId;});
 await page.reload();await page.waitForFunction(()=>window.lifestreamUI);await page.locator('[data-audience-solo]').click();await page.waitForFunction(()=>document.documentElement.dataset.audienceProtected==='false');await page.locator('[data-destination=conversation]').click();await page.locator('#room-mic-start').click();await page.waitForFunction(()=>document.querySelector('#room-mic-status').textContent.startsWith('Microphone on'));
 const sessionId=await page.evaluate(()=>window.lifestreamAuth.session.sessionId),activity=()=>app.database.connection.prepare('SELECT admin_last_activity FROM local_sessions WHERE session_id=?').get(sessionId).admin_last_activity,originalActivity=activity();
 const audienceMessages=await page.evaluate(()=>window.audienceMessages);now+=1_800_000;
 const denied=page.waitForResponse(r=>r.url()===base+`/api/admin/v1/assistants/${assistantId}/acknowledgments`&&r.status()===401);
 await page.locator('#room-ack-audio-only').check();await denied;await page.locator('#room-ack-status').filter({hasText:'Acknowledgments unavailable; ordinary replies continue.'}).waitFor();
 await page.waitForFunction(before=>window.audienceMessages>=before+2,audienceMessages);assert.equal(await page.locator('html').getAttribute('data-audience-protected'),'false');
 assert.equal(await page.evaluate(()=>window.lifestreamAuth.session?.sessionId),sessionId,'Optional catalog expiry must not sign out the conversation');
 assert.equal(await page.locator('#room-mic-stop').isEnabled(),true);assert.equal(await page.evaluate(()=>window.syntheticCapture.getAudioTracks()[0].readyState),'live');assert.equal(activity(),originalActivity);
 const protectedEdit=await page.evaluate(async id=>{const r=await fetch(`/api/admin/v1/assistants/${id}/revisions`,{method:'POST',headers:{'content-type':'application/json','x-lifestream-csrf':window.lifestreamAuth.session.csrfToken},body:JSON.stringify({expectedRevision:1,displayName:'Expired edit must fail'})});return r.status;},assistantId);assert.equal(protectedEdit,401);assert.equal(activity(),originalActivity);
 await page.locator('#room-message').fill('Continue this synthetic conversation after administration expiry.');await page.locator('#room-send').click();await page.locator('#room-status').filter({hasText:'Reply completed'}).waitFor();assert.match(await page.locator('.room-turn.assistant').textContent(),/Fixture response/);assert.equal(activity(),originalActivity);
 await page.locator('[data-audience-shared]').click();await page.waitForFunction(()=>document.documentElement.dataset.audienceProtected==='true');assert.equal(await page.evaluate(()=>window.syntheticCapture.getAudioTracks()[0].readyState),'ended');
 await page.locator('[data-audience-solo]').click();await page.waitForFunction(()=>document.documentElement.dataset.audienceProtected==='false');await page.locator('#room-mic-start').click();await page.waitForFunction(()=>document.querySelector('#room-mic-status').textContent.startsWith('Microphone on'));assert.equal(activity(),originalActivity);assert.equal(await page.evaluate(()=>window.lifestreamAuth.session?.sessionId),sessionId);
 await page.locator('[data-destination=account]').click();await page.locator('#auth-sign-out').click();await page.waitForFunction(()=>!window.lifestreamAuth.session);assert.equal(await page.evaluate(()=>window.syntheticCapture.getAudioTracks()[0].readyState),'ended');assert.deepEqual(errors,[]);
});

test('rendered acknowledgment cache uses paired audio clock, skips cold/stale work and yields to answer audio',{skip:!process.env.PLAYWRIGHT_MODULE},async t=>{
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage();
 await page.route('http://127.0.0.1:9/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);if(!name)return route.fulfill({contentType:'text/html',body:'<main><h1>Synthetic acknowledgment playback</h1><div id="mouth">Ready</div></main>'});if(!['acknowledgments.js','acknowledgment-presentation.js','conversation-output.js'].includes(name))return route.abort();return route.fulfill({contentType:'text/javascript',body:await readFile(new URL('../'+name,import.meta.url))});});await page.goto('http://127.0.0.1:9/');
 const result=await page.evaluate(async()=>{
  const {AcknowledgmentCache}=await import('/acknowledgments.js'),{ConversationOutput}=await import('/conversation-output.js'),audio=new AudioContext();await audio.resume();const hash=async b=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('');
  const bytes=new Uint8Array(96000);for(let i=0;i<48000;i++)new DataView(bytes.buffer).setInt16(i*2,1200,true);const sha=await hash(bytes),track={schemaVersion:'1.0.0',cueSet:'fixture-open-rest',analysisRevision:'fixture-1',timeUnit:'ms',timeOrigin:'audio-start',audioSha256:sha,durationMs:1000,cues:[{startMs:0,endMs:300,cue:'open'},{startMs:300,endMs:1000,cue:'rest'}]},trackBytes=new TextEncoder().encode(JSON.stringify(track)),trackSha=await hash(trackBytes);
  let downloads=0,current=true,requiresSync=true;const clips=['one','two'].map(id=>({id,text:'Synthetic cue.',audio:{format:'pcm_s16le',sampleRateHz:48000,channels:1,bytes:bytes.length,durationMs:1000,sha256:sha},synchronized:true,visemes:{sha256:trackSha,bytes:trackBytes.length,cueSet:track.cueSet,analysisRevision:track.analysisRevision}}));let manifest={schemaVersion:'1.0.0',assistantId:'synthetic',revision:1,binding:'saved-voice-revision',enabled:true,clips};const measurements=[];
  const output=new ConversationOutput({onStopped(){},onComplete(){},onState(){},onReplyAudio:e=>measurements.push(e)});output.socket={readyState:WebSocket.OPEN,send(){},close(){}};output.audio=audio;
  const cache=new AcknowledgmentCache({audio:()=>audio,current:()=>current,manifest:async()=>manifest,artifact:async kind=>{downloads++;return (kind==='audio'?bytes:trackBytes).buffer.slice(0);},mode:()=>({requiresSync,accepts:t=>t.cueSet===track.cueSet}),onMeasure:e=>measurements.push(e)});output.acknowledgments=cache;
  const token=()=>({revision:manifest.revision,binding:manifest.binding,clipIds:manifest.clips.map(c=>c.id)});
  const cold=cache.play('cold',token());await cache.refresh();const before=downloads;output.beginReply('spoken-one');output.receive({type:'acknowledgment',interactionTraceId:'spoken-one',catalog:token()});const first=cache.playing.entry.clip.id;const once=cache.play('spoken-one',token());cache.stop();
  output.beginReply('spoken-two');cache.play('spoken-two',token(),{bufferOffset:.2});const second=cache.playing.entry.clip.id,beforeStart=cache.sample();const playbackDeadline=performance.now()+3000;let during=cache.sample();while((!during.playing||during.sampleOffset===0)&&performance.now()<playbackDeadline){await new Promise(r=>setTimeout(r,10));during=cache.sample();}document.querySelector('#mouth').textContent=during.viseme;const savedEnded=cache.playing.source.onended,segment=cache.playing.segmentId;
  const pcm=new Uint8Array(9600);output.receive({type:'audio',interactionTraceId:'spoken-two',chunk:{segmentId:'answer-segment',frame:{format:{encoding:'pcm_s16le',sampleRateHz:48000,channels:1},sequence:0,sampleOffset:0,sampleCount:4800,dataBase64:btoa(String.fromCharCode(...pcm))}}});const preempted=cache.playing===null,replySources=output.sources.size;savedEnded();const lateCannotRevive=cache.playing===null;
  output.stop();const silent=!cache.sample().playing,noDownloadsOnTurn=downloads===before;
  output.beginReply('ready-race');const readySkipped=cache.play('ready-race',token(),{responseReady:true});const old=token();manifest={...manifest,revision:2,clips:[]};await cache.refresh();const retiredSkipped=cache.play('retired',old);
  manifest={...manifest,revision:3,clips:clips.map(c=>({...c,synchronized:false,visemes:null}))};await cache.refresh();const degradedSkipped=cache.play('degraded',token());requiresSync=false;const explicitFallback=cache.play('fallback',token());cache.clear();current=false;const afterLogout=cache.play('logout',token());output.close();
  return {cold,once,first,second,beforeStart,during,preempted,replySources,lateCannotRevive,silent,noDownloadsOnTurn,readySkipped,retiredSkipped,degradedSkipped,explicitFallback,afterLogout,measurements,segment};
 });
 assert.equal(result.cold,false);assert.equal(result.once,false);assert.notEqual(result.first,result.second);assert.equal(result.beforeStart.playing,false);assert.equal(result.during.clock,'AudioContext.currentTime');assert.equal(result.during.viseme,result.during.sampleOffset/48<300?'open':'rest');assert.ok(result.during.sampleOffset>0);assert.equal(result.preempted,true);assert.equal(result.replySources,1);assert.equal(result.lateCannotRevive,true);assert.equal(result.silent,true);assert.equal(result.noDownloadsOnTurn,true);for(const key of ['readySkipped','retiredSkipped','degradedSkipped','afterLogout'])assert.equal(result[key],false);assert.equal(result.explicitFallback,true);assert.equal(result.measurements.filter(e=>e.kind==='acknowledgment-start').length,3);assert.equal(result.measurements.filter(e=>e.kind==='actual-response-audio').length,1);
});

test('acknowledgment administration covers enablement, preview, stop, pin, finite expiry, removal and restart',{skip:!process.env.PLAYWRIGHT_MODULE},async t=>{
 const root=await mkdtemp(join(tmpdir(),'ack-ui-'));t.after(()=>rm(root,{recursive:true,force:true}));const fixture=await savedVoiceFixture();t.after(fixture.close);const original=FixtureInferenceProvider.prototype.generate;FixtureInferenceProvider.prototype.generate=async function*(){yield {kind:'text',text:JSON.stringify(['I am listening.','Let me think.','One moment.','I hear you.','Let me consider that.','Hmm.','I see.','All right.','Let me take a look.','Okay.'])};yield {kind:'done'};};t.after(()=>{FixtureInferenceProvider.prototype.generate=original;});
 const config=loadProfile('test');config.providers.tts='voxcpm';config.ttsProfile=fixture.profile;config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex'),localAuth={stateDirectory:join(root,'safety'),installerToken};let app=createLifestreamServer({config,localAuth});await app.start();t.after(()=>app.shutdown());
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));t.after(()=>{if(errors.length)console.log('Browser errors:',errors);});page.setDefaultTimeout(12000);await page.goto(`http://127.0.0.1:${app.address().port}/control/#voice`);await page.waitForFunction(()=>window.lifestreamUI);await page.evaluate(()=>window.lifestreamAuth.ready);await page.locator('#auth-username').fill('synthetic-owner');await page.locator('#auth-password').fill('Synthetic-acknowledgment-password-1');await page.locator('#auth-installer-token').fill(installerToken);await page.locator('#auth-setup').click();await page.waitForFunction(()=>window.lifestreamAuth.session);
 await page.evaluate(async()=>{const r=(p,b)=>window.lifestreamAuth.request(p,b,b!==undefined),a=await r('/api/admin/v1/assistants',{displayName:'Synthetic catalog review'});await r(`/api/admin/v1/assistants/${a.assistantId}/activate`,{profileId:a.profile.profileId,expectedActiveRevision:null});});await page.reload();await page.waitForFunction(()=>window.lifestreamUI);await page.locator('[data-destination=voice]').click();const panel=page.locator('.acknowledgment-admin');await panel.getByRole('button',{name:'Refresh acknowledgments',exact:true}).click();await panel.locator('[role=status]').filter({hasText:'0/5'}).waitFor();await panel.getByRole('checkbox').check();await panel.locator('[name=days]').fill('7');await panel.getByRole('button',{name:'Save acknowledgment settings'}).click();
 for(let i=0;i<50;i++){await panel.getByRole('button',{name:'Refresh acknowledgments',exact:true}).click();if(await panel.locator('[data-clips] article').count()===5)break;await page.waitForTimeout(60);}assert.equal(await panel.locator('[data-clips] article').count(),5);const first=panel.locator('[data-clips] article').first();await first.getByRole('button',{name:'Preview acknowledgment',exact:true}).click();await panel.locator('[role=status]').filter({hasText:'Playing audio-only'}).waitFor();await panel.getByRole('button',{name:'Stop acknowledgment preview'}).click();await first.getByRole('button',{name:'Keep indefinitely'}).click();await first.locator('p').filter({hasText:'Kept indefinitely'}).waitFor();await first.getByRole('button',{name:'Restore finite expiry'}).click();await page.waitForFunction(()=>!document.querySelector('.acknowledgment-admin [data-clips] article p').textContent.includes('Kept indefinitely'));await first.getByRole('button',{name:'Extend by default lifetime'}).click();await page.waitForTimeout(100);await first.getByRole('button',{name:'Keep indefinitely'}).click();await first.locator('p').filter({hasText:'Kept indefinitely'}).waitFor();
 if(process.env.ACK_SCREENSHOT){await panel.scrollIntoViewIfNeeded();await page.screenshot({path:process.env.ACK_SCREENSHOT,fullPage:true});await page.setViewportSize({width:390,height:844});await panel.scrollIntoViewIfNeeded();await page.screenshot({path:process.env.ACK_SCREENSHOT.replace('.png','-mobile.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.setViewportSize({width:1440,height:1000});}
 await page.reload();await page.waitForFunction(()=>window.lifestreamUI);await panel.getByRole('button',{name:'Refresh acknowledgments',exact:true}).click();await first.locator('p').filter({hasText:'Kept indefinitely'}).waitFor();assert.equal(await panel.locator('[name=days]').inputValue(),'7');const committed=async(action)=>{await page.evaluate(()=>{window.ackMutationComplete=false;window.addEventListener('lifestream-acknowledgments',()=>{window.ackMutationComplete=true;},{once:true});});await action();await page.waitForFunction(()=>window.ackMutationComplete);};await committed(()=>first.getByRole('button',{name:'Remove acknowledgment'}).click());await panel.getByRole('checkbox').uncheck();await committed(()=>panel.getByRole('button',{name:'Save acknowledgment settings'}).click());await page.reload();await page.waitForFunction(()=>window.lifestreamUI);await panel.getByRole('button',{name:'Refresh acknowledgments',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.acknowledgment-admin [name=days]').value==='7'&&!document.querySelector('.acknowledgment-admin [name=enabled]').checked);assert.equal(await panel.getByRole('checkbox').isChecked(),false);assert.deepEqual(errors,[]);
});

test('Saved Voice preview uses the selected renderer and fences stop, fallback, navigation and late preparation',{skip:!process.env.PLAYWRIGHT_MODULE,timeout:45000},async t=>{
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true,args:['--mute-audio','--autoplay-policy=no-user-gesture-required']});t.after(()=>browser.close());const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('http://127.0.0.1:9/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);if(!name)return route.fulfill({contentType:'text/html',body:'<script type="importmap">{"imports":{"three":"/three.module.js"}}</script><style>canvas{width:400px;height:310px}[hidden]{display:none}</style><main></main>'});if(!/^[a-zA-Z0-9_.-]+$/.test(name))return route.abort();return route.fulfill({contentType:'text/javascript',body:await presentationVendor(name)??await readFile(new URL('../'+name,import.meta.url))});});await page.goto('http://127.0.0.1:9/#voice');
 await page.evaluate(async()=>{
  const {installAcknowledgmentAdministration}=await import('/acknowledgments.js'),{PresentationRuntime}=await import('/presentation-runtime.js');window.lifestreamAuth={session:{}};
  const hash=async b=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('');
  const binary=new Float32Array([-.2,0,0,.2,0,0,0,.1,0,0,1,1,1,1,1,6,1,1,1,1,1,1,1]);
  const model={asset:{version:'2.0'},scene:0,scenes:[{nodes:[0]}],nodes:[{name:'Mouth',mesh:0}],meshes:[{primitives:[{attributes:{POSITION:0}}]}],buffers:[{uri:'poses.bin',byteLength:binary.byteLength}],bufferViews:[{buffer:0,byteOffset:0,byteLength:36},{buffer:0,byteOffset:36,byteLength:8},{buffer:0,byteOffset:44,byteLength:24},{buffer:0,byteOffset:68,byteLength:24}],accessors:[{bufferView:0,componentType:5126,count:3,type:'VEC3',min:[-.2,0,0],max:[.2,.1,0]},{bufferView:1,componentType:5126,count:2,type:'SCALAR',min:[0],max:[1]},{bufferView:2,componentType:5126,count:2,type:'VEC3'},{bufferView:3,componentType:5126,count:2,type:'VEC3'}],animations:['open','rest'].map((name,i)=>({name,channels:[{sampler:0,target:{node:0,path:'scale'}}],samplers:[{input:1,output:2+i,interpolation:'LINEAR'}]}))};
  const files=new Map([['model.gltf',new TextEncoder().encode(JSON.stringify(model))],['poses.bin',new Uint8Array(binary.buffer)]]),pcm=new Uint8Array(192000);for(let i=0;i<pcm.length/2;i++)new DataView(pcm.buffer).setInt16(i*2,1200,true);
  const audioSha=await hash(pcm),track={schemaVersion:'1.0.0',cueSet:'synthetic-preview',analysisRevision:'test-1',audioSha256:audioSha,timeUnit:'ms',timeOrigin:'audio-start',durationMs:2000,cues:[{startMs:0,endMs:1000,cue:'A'},{startMs:1000,endMs:2000,cue:'X'}]},trackBytes=new TextEncoder().encode(JSON.stringify(track)),trackSha=await hash(trackBytes);
  const item={id:'synthetic',digest:'synthetic-digest',label:'Synthetic cue appearance',manifest:{model:'model.gltf',animations:{mouthAmplitude:'open'},framing:{distance:1.2,targetHeight:.5},capabilities:{lipSync:'amplitude'},speech:{cueSet:'synthetic-preview',poses:{A:'open',X:'rest'},transitionSeconds:0},resources:await Promise.all([...files].map(async([path,bytes])=>({path,bytes:bytes.byteLength,sha256:await hash(bytes),mime:'application/octet-stream'})))}};
  const clip={id:'one',revision:1,text:'I am listening.',expiresAt:null,audio:{sha256:audioSha,bytes:pcm.length,durationMs:2000,format:'pcm_s16le',sampleRateHz:48000,channels:1},synchronized:true,visemes:{sha256:trackSha,bytes:trackBytes.length,cueSet:track.cueSet,analysisRevision:track.analysisRevision}};
  window.previewFixture={starts:0,stops:0,frames:[],runtimes:[],pending:false,release:null,incompatible:false,requests:[]};const f=window.previewFixture,fetchOriginal=fetch,sourceOriginal=AudioContext.prototype.createBufferSource,animate=PresentationRuntime.prototype.animate,prepare=PresentationRuntime.prototype.prepare;
  AudioContext.prototype.createBufferSource=function(){const node=sourceOriginal.call(this),start=node.start.bind(node),stop=node.stop.bind(node);node.start=(...args)=>{f.starts++;return start(...args);};node.stop=(...args)=>{f.stops++;return stop(...args);};return node;};
  PresentationRuntime.prototype.animate=function(){if(!f.runtimes.includes(this))f.runtimes.push(this);animate.call(this);if(this.current?.speechMotion)f.frames.push({sample:this.playback(),scale:this.current.root.getObjectByName('Mouth').scale.y});};
  PresentationRuntime.prototype.prepare=async function(...args){const result=await prepare.apply(this,args);if(f.pending)await new Promise(resolve=>{f.release=resolve;});return result;};
  window.fetch=(url,options)=>{const name=String(url).split('/').pop();if(String(url).includes('/presentation/resources/'))return Promise.resolve(new Response(files.get(name)));if(name===audioSha)return Promise.resolve(new Response(pcm));if(name===trackSha)return Promise.resolve(new Response(trackBytes));return fetchOriginal(url,options);};
  const api=async(path,options)=>{f.requests.push({path,method:options?.method??'GET'});if(path==='/api/runtime/v1/presentation')return {endpointId:'synthetic-endpoint',selection:{override:{id:item.id,digest:item.digest}},neutral:{id:'neutral'},packages:[item]};return {schemaVersion:'1.0.0',revision:1,binding:'synthetic',enabled:true,defaultTtlDays:5,readyCount:1,synchronizedReadyCount:1,maintenance:'publishedCurrentRevision',clips:[f.incompatible?{...clip,synchronized:false,visemes:null}:clip]};};
  window.admin=installAcknowledgmentAdministration({anchor:document.querySelector('main'),api,context:()=>({assistantId:'synthetic-assistant'})});window.admin.refresh();
 });
 const panel=page.locator('.acknowledgment-admin'),play=panel.getByRole('button',{name:'Preview acknowledgment',exact:true}),audioOnly=panel.getByRole('button',{name:'Preview audio only',exact:true}),stop=panel.getByRole('button',{name:'Stop acknowledgment preview',exact:true});
 await play.click();await page.waitForFunction(()=>previewFixture.frames.some(f=>f.sample.viseme==='A'&&f.scale===6));assert.match(await panel.locator('[role=status]').textContent(),/Playing paired/);await stop.click();await page.waitForFunction(()=>previewFixture.frames.at(-1).sample.playing===false&&previewFixture.frames.at(-1).scale===1);assert.equal(await page.evaluate(()=>previewFixture.starts),1);
 await audioOnly.click();await panel.locator('[role=status]').filter({hasText:'Playing audio-only'}).waitFor();assert.equal(await page.locator('.acknowledgment-preview').isVisible(),false);assert.equal(await page.evaluate(()=>previewFixture.runtimes.every(r=>r.disposed)),true);await stop.click();
 await page.evaluate(()=>{previewFixture.incompatible=true;admin.clear();admin.refresh();});await play.click();await panel.locator('[role=status]').filter({hasText:'compatible audio and mouth-cue pair is unavailable'}).waitFor();assert.equal(await page.evaluate(()=>previewFixture.starts),2);await audioOnly.click();await panel.locator('[role=status]').filter({hasText:'Playing audio-only'}).waitFor();await stop.click();
 await page.evaluate(()=>{previewFixture.incompatible=false;previewFixture.pending=true;admin.clear();admin.refresh();});await play.click();await page.waitForFunction(()=>typeof previewFixture.release==='function');await stop.click();await page.evaluate(()=>{previewFixture.release();previewFixture.release=null;});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>previewFixture.starts),3);assert.equal(await page.evaluate(()=>previewFixture.runtimes.at(-1).current.label==='Neutral reference'),true);
 await page.evaluate(()=>{previewFixture.pending=false;admin.clear();admin.refresh();});await play.click();await panel.locator('[role=status]').filter({hasText:'Playing paired'}).waitFor();await page.evaluate(()=>{location.hash='#account';});await page.waitForFunction(()=>previewFixture.runtimes.every(r=>r.disposed));assert.equal(await page.locator('.acknowledgment-preview').isVisible(),false);
 await page.evaluate(()=>{location.hash='#voice';previewFixture.pending=true;admin.clear();admin.refresh();});await play.click();await page.waitForFunction(()=>typeof previewFixture.release==='function');await page.evaluate(()=>{window.dispatchEvent(new CustomEvent('lifestream-audience',{detail:{privateAllowed:false}}));previewFixture.release();});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>previewFixture.starts),4);assert.equal(await page.evaluate(()=>previewFixture.runtimes.every(r=>r.disposed)),true);assert.equal(await page.locator('.acknowledgment-preview').isVisible(),false);assert.equal(await page.evaluate(()=>previewFixture.requests.some(r=>r.method!=='GET')),false);assert.deepEqual(errors,[]);
});
