import assert from 'node:assert/strict';
import {test} from 'node:test';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {presentationVendor} from '../../server/src/runtime/presentation-vendor.ts';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes} from 'node:crypto';
import {createLifestreamServer} from '../../server/src/index.ts';
import {loadProfile} from '../../server/src/config/loader.ts';
test('audience renewal restores the saved display after immediate privacy disposal without reopening capture',{skip:!process.env.PLAYWRIGHT_MODULE},async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-audience-display-'));t.after(()=>rm(root,{recursive:true,force:true}));
 const config=loadProfile('test');config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};config.authority.authentication='local-password';
 const token=randomBytes(32).toString('hex'),app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'auth'),installerToken:token},audiencePrivacy:{sourceIds:[]}});await app.start();t.after(()=>app.shutdown());
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[];page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{window.captureCalls=0;navigator.mediaDevices.getUserMedia=async()=>{window.captureCalls++;throw Error('Capture is not part of this test.');};});
 await page.goto(`http://127.0.0.1:${app.address().port}/control/#account`);await page.evaluate(()=>window.lifestreamAuth.ready);await page.waitForFunction(()=>!!window.lifestreamUI);
 await page.locator('#auth-username').fill('synthetic-owner');await page.locator('#auth-password').fill('Synthetic-display-password-1');await page.locator('#auth-installer-token').fill(token);await page.locator('#auth-setup').click();await page.waitForFunction(()=>!!window.lifestreamAuth.session);
 await page.evaluate(async()=>{const r=(p,b)=>window.lifestreamAuth.request(p,b,b!==undefined),a=await r('/api/admin/v1/assistants',{displayName:'Neutral display check'});await r(`/api/admin/v1/assistants/${a.assistantId}/activate`,{profileId:a.profile.profileId,expectedActiveRevision:null});const s=await r('/api/runtime/v1/session-context');await r('/api/runtime/v1/session-context',{expectedRevision:s.revision,mode:'text',audienceScope:'authenticatedSession',bindingKey:crypto.randomUUID()});});
 await page.reload();await page.waitForFunction(()=>!!window.lifestreamUI);await page.locator('[data-audience-solo]').click();await page.waitForFunction(()=>document.documentElement.dataset.audienceProtected==='false');
 await page.evaluate(async()=>{const {PresentationRuntime}=await import('/control/presentation-runtime.js'),commit=PresentationRuntime.prototype.commit;window.displayInstances=[];PresentationRuntime.prototype.commit=function(...args){if(!window.displayInstances.includes(this))window.displayInstances.push(this);return commit.apply(this,args);};});
 await page.locator('[data-destination=conversation]').click();await page.locator('.presentation-stage canvas').scrollIntoViewIfNeeded();await page.waitForFunction(()=>window.displayInstances.at(-1)?.renderedAt>0);
 await page.getByLabel('Appearance',{exact:true}).selectOption('neutral');await page.getByLabel('Appearance scope',{exact:true}).selectOption('session');await page.getByRole('button',{name:'Apply appearance',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.presentation-controls [role=status]').textContent.includes('Amplitude-driven'));
 const selection=await page.evaluate(async()=>{window.previousDisplay=window.displayInstances.at(-1);return (await window.lifestreamAuth.request('/api/runtime/v1/presentation')).selection;});
 await page.locator('[data-audience-solo]').click();
 await page.waitForFunction(()=>window.previousDisplay.disposed===true);
 await page.waitForFunction(()=>{const current=window.displayInstances.at(-1);return current!==window.previousDisplay&&!current.disposed&&current.renderedAt>0;});
 assert.deepEqual(await page.evaluate(async()=>(await window.lifestreamAuth.request('/api/runtime/v1/presentation')).selection),selection,'renewal must restore the existing selection without rewriting it');
 await page.locator('#room-message').fill('Synthetic reply after audience renewal.');await page.locator('#room-send').click();await page.locator('#room-status').filter({hasText:'Reply completed'}).waitFor();
 await page.locator('[data-audience-shared]').click();await page.waitForFunction(()=>document.documentElement.dataset.audienceProtected==='true');await page.waitForFunction(()=>window.displayInstances.every(r=>r.disposed));assert.equal(await page.locator('.presentation-panel').isVisible(),false);assert.equal(await page.locator('.room-turn').count(),0);
 await page.locator('[data-audience-solo]').click();await page.waitForFunction(()=>document.documentElement.dataset.audienceProtected==='false');await page.waitForFunction(()=>!window.displayInstances.at(-1).disposed&&window.displayInstances.at(-1).renderedAt>0);
 await page.evaluate(async()=>{window.previousDisplay=window.displayInstances.at(-1);const r=window.lifestreamAuth.request,s=await r('/api/runtime/v1/session-context');const value=await r('/api/runtime/v1/session-context',{expectedRevision:s.revision,mode:'text',audienceScope:'authenticatedSession'},true);dispatchEvent(new CustomEvent('lifestream-session-context',{detail:value}));});
 await page.waitForFunction(()=>window.previousDisplay.disposed===true);await page.waitForFunction(()=>{const current=window.displayInstances.at(-1);return current!==window.previousDisplay&&!current.disposed&&current.renderedAt>0;});
 await page.locator('[data-audience-clear]').click();await page.waitForFunction(()=>document.documentElement.dataset.audienceProtected==='true');await page.waitForFunction(()=>window.displayInstances.every(r=>r.disposed));
 assert.equal(await page.evaluate(()=>window.captureCalls),0);assert.deepEqual(errors,[]);
});
test('automatic audience transition protects private screens and transcript; unknown still permits generic conversation',{skip:!process.env.PLAYWRIGHT_MODULE},async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-audience-ui-'));t.after(()=>rm(root,{recursive:true,force:true}));let occupants=0,ownerPresent=true;
 const config=loadProfile('test');config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};config.authority.authentication='local-password';
 const token=randomBytes(32).toString('hex'),app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'auth'),installerToken:token},audiencePrivacy:{sourceIds:['synthetic-enrolled'],poll:async identity=>({sourceId:'synthetic-enrolled',evidenceRef:'synthetic:presence',...identity,observedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+3000).toISOString(),coverageKnown:true,ownerPresent:occupants>0&&ownerPresent,occupants})}});await app.start();t.after(()=>app.shutdown());
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage();page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`http://127.0.0.1:${app.address().port}/control/`);await page.evaluate(()=>window.lifestreamAuth.ready);await page.waitForFunction(()=>window.lifestreamUI);await page.locator('#auth-username').fill('synthetic-owner');await page.locator('#auth-password').fill('Synthetic-long-password-1');await page.locator('#auth-installer-token').fill(token);assert.equal(await page.locator('#auth-username').inputValue(),'synthetic-owner');await page.locator('#auth-setup').click();await page.waitForFunction(()=>!!window.lifestreamAuth.session).catch(async e=>{console.log({phase:'setup',errors,status:await page.locator('#auth-status').textContent(),state:await page.evaluate(()=>({mode:window.lifestreamAuth.mode,setupRequired:window.lifestreamAuth.setupRequired,hasSession:!!window.lifestreamAuth.session}))});throw e;});
 assert.equal(await page.locator('html').getAttribute('data-audience-protected'),'true');
 await page.evaluate(async()=>{const r=(p,b)=>window.lifestreamAuth.request(p,b,b!==undefined),a=await r('/api/admin/v1/assistants',{displayName:'Private synthetic name'});await r(`/api/admin/v1/assistants/${a.assistantId}/activate`,{profileId:a.profile.profileId,expectedActiveRevision:null});const session=await r('/api/runtime/v1/session-context');await r('/api/runtime/v1/session-context',{expectedRevision:session.revision,mode:'text',audienceScope:'authenticatedSession',bindingKey:crypto.randomUUID()});});
 await page.reload();await page.waitForFunction(()=>window.lifestreamUI);occupants=1;await page.waitForFunction(()=>document.documentElement.dataset.audienceProtected==='false').catch(async e=>{console.log({errors,status:await page.locator('[data-audience-status]').textContent(),server:await page.evaluate(()=>window.lifestreamAuth.request('/api/runtime/v1/audience')),session:await page.evaluate(()=>window.lifestreamAuth.request('/api/runtime/v1/session-context'))});throw e;});assert.match(await page.locator('[data-audience-status]').textContent(),/automatic/);
 await page.locator('[data-destination="conversation"]').click();await page.locator('#room-message').fill('Please remember this synthetic private sentence during this conversation.');await page.locator('#room-send').click();await page.locator('#room-status').filter({hasText:'Reply completed'}).waitFor();assert.ok(await page.locator('.room-turn').count()>0);
 occupants=2;await page.waitForFunction(()=>document.documentElement.dataset.audienceProtected==='true');await page.waitForFunction(()=>document.querySelectorAll('.room-turn').length===0);assert.equal(await page.locator('#assistant-list').isVisible(),false);assert.match(await page.locator('[data-audience-status]').textContent(),/shared/);
 assert.equal(await page.locator('.presentation-panel').isVisible(),false,'selected private appearance is protected immediately');
 assert.equal(await page.locator('[aria-label="Appearance"] option').count(),1,'private appearance choices are cleared');
 await page.locator('[data-audience-solo]').click();await page.waitForFunction(()=>document.querySelector('[data-audience-status]').textContent.includes('shared'));assert.equal(await page.locator('html').getAttribute('data-audience-protected'),'true');
 occupants=1;await page.waitForFunction(()=>document.documentElement.dataset.audienceProtected==='false');
 await page.locator('#room-message').fill('Private conversation before the owner leaves.');await page.locator('#room-send').click();await page.locator('#room-status').filter({hasText:'Reply completed'}).waitFor();assert.ok(await page.locator('.room-turn').count()>0);
 ownerPresent=false;await page.waitForFunction(()=>document.querySelector('[data-audience-status]').textContent.startsWith('unknown · automatic'));
 assert.equal(await page.locator('html').getAttribute('data-audience-protected'),'true','one unknown occupant must override the existing manual solo declaration');
 await page.waitForFunction(()=>document.querySelectorAll('.room-turn').length===0);assert.equal(await page.locator('.presentation-panel').isVisible(),false);
 await page.locator('[data-audience-solo]').click();await page.waitForFunction(()=>document.querySelector('[data-audience-status]').textContent.startsWith('unknown · automatic'));assert.equal(await page.locator('html').getAttribute('data-audience-protected'),'true','renewing the manual declaration cannot override fresh owner-absent evidence');
 await page.locator('#room-message').fill('Explain a rainbow.');await page.locator('#room-send').click();await page.locator('#room-status').filter({hasText:'Reply completed'}).waitFor();assert.equal(await page.locator('.room-turn.user').count(),1);
 const self=await page.evaluate(()=>window.lifestreamAuth.request('/api/runtime/v1/session-context'));assert.equal(self.runtimeSelfContext.audienceScope,'unknown');assert.deepEqual(errors,[]);
});

test('a fresh protected sign-in can configure disclosure and declare audience entirely through visible controls',{skip:!process.env.PLAYWRIGHT_MODULE},async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-audience-entry-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};config.authority.authentication='local-password';const token=randomBytes(32).toString('hex'),app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'auth'),installerToken:token},audiencePrivacy:{sourceIds:[]}});await app.start();t.after(()=>app.shutdown());
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1280,height:1000}});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`http://127.0.0.1:${app.address().port}/control/#account`);await page.evaluate(()=>window.lifestreamAuth.ready);await page.waitForFunction(()=>!!window.lifestreamUI);await page.locator('#auth-username').fill('synthetic-owner');await page.locator('#auth-password').fill('Synthetic-entry-password-1');await page.locator('#auth-installer-token').fill(token);const enrollment=page.waitForResponse(r=>r.url().endsWith('/api/auth/v1/setup'));await page.locator('#auth-setup').click();const enrolled=await enrollment;assert.equal(enrolled.status(),201,'local enrollment must succeed');await page.waitForFunction(()=>!!window.lifestreamAuth.session&&document.querySelector('#session-context-status').textContent.includes('revision 0'));
 assert.equal(await page.locator('html').getAttribute('data-audience-protected'),'true');await page.locator('[data-destination=session]').click();await page.waitForFunction(()=>location.hash==='#session'&&!document.querySelector('[data-view=session]').hidden);assert.equal(await page.locator('#session-context-apply').isVisible(),true,'unknown audience must leave safe disclosure setup accessible');
 assert.equal(await page.locator('#session-audience').inputValue(),'unknown');await page.locator('#session-context-apply').click();await page.waitForFunction(()=>document.querySelector('#session-context-status').textContent.includes('revision 1'));assert.equal(await page.locator('html').getAttribute('data-audience-protected'),'true');
 await page.locator('[data-audience-solo]').click();await page.waitForFunction(()=>document.documentElement.dataset.audienceProtected==='false');assert.equal((await page.evaluate(()=>window.lifestreamAuth.request('/api/runtime/v1/session-context'))).runtimeSelfContext.audienceScope,'unknown','a solo declaration alone is not private disclosure');
 await page.locator('#session-audience').selectOption('authenticatedSession');await page.locator('#session-context-apply').click();await page.waitForFunction(()=>document.querySelector('#session-context-status').textContent.includes('revision 2'));await page.waitForFunction(()=>document.documentElement.dataset.audienceProtected==='false');
 await page.locator('#session-context-panel summary').click();assert.equal(await page.locator('#session-context-details').isVisible(),true);await page.locator('[data-audience-shared]').click();await page.waitForFunction(()=>document.documentElement.dataset.audienceProtected==='true');assert.equal(await page.locator('#session-context-details').isVisible(),false);assert.equal(await page.locator('#session-context-apply').isVisible(),true);assert.equal(await page.locator('#assistant-list').isVisible(),false);assert.equal(await page.locator('.presentation-panel').isVisible(),false);
 await page.locator('[data-destination=account]').click();await page.locator('#auth-sign-out').click();await page.waitForFunction(()=>!window.lifestreamAuth.session);await page.locator('#auth-username').fill('synthetic-owner');await page.locator('#auth-password').fill('Synthetic-entry-password-1');await page.locator('#auth-sign-in').click();await page.waitForFunction(()=>!!window.lifestreamAuth.session);await page.waitForFunction(()=>location.hash==='#session');assert.equal(await page.locator('#session-context-apply').isVisible(),true);assert.equal(await page.locator('#session-audience').inputValue(),'unknown');assert.deepEqual(errors,[]);
});


test('saved display restoration waits for an idle boundary and is cancelled by privacy, navigation or invalid assets',{skip:!process.env.PLAYWRIGHT_MODULE},async t=>{
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage();page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('http://127.0.0.1:9/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);if(!name)return route.fulfill({contentType:'text/html',body:'<script type="importmap">{"imports":{"three":"/three.module.js"}}</script><main><div class="room-layout"></div></main>'});const body=name.startsWith('presentation-')||name==='presentation.js'?await readFile(new URL('../'+name,import.meta.url)):await presentationVendor(name);if(!body)return route.abort();return route.fulfill({contentType:'text/javascript',body});});
 await page.goto('http://127.0.0.1:9/#conversation');
 await page.evaluate(async()=>{
  window.lifestreamAuth={session:{principalId:'synthetic'}};window.displayBusy=true;window.displayAttempts=0;window.displayCommits=[];window.displayReleases=[];window.displayWrites=0;
  const {PresentationRuntime}=await import('/presentation-runtime.js'),commit=PresentationRuntime.prototype.commit,release=PresentationRuntime.prototype.release;
  // Real renderer and neutral geometry; only package preparation is gated to
  // deterministically reproduce loading overlapping microphone/turn setup.
  PresentationRuntime.prototype.prepare=async function(item,signal){window.displayAttempts++;await new Promise(resolve=>window.finishDisplayPrepare=resolve);if(window.rejectDisplayPrepare)throw Error('Synthetic invalid package');signal.throwIfAborted();const candidate=this.neutral();candidate.label=item.label;return candidate;};
  PresentationRuntime.prototype.commit=function(candidate){window.displayCommits.push(candidate.label);return commit.call(this,candidate);};
  PresentationRuntime.prototype.release=function(candidate){window.displayReleases.push(candidate.label);return release.call(this,candidate);};
  const {installPresentation}=await import('/presentation.js');window.fixtureDisplay={endpointId:'synthetic-endpoint',neutral:{id:'neutral',label:'Neutral reference',digest:'neutral-v1'},packages:[{id:'saved-fixture',label:'Saved fixture',digest:'synthetic-digest',manifest:{capabilities:{lipSync:'amplitude'}}}],selection:{default:{id:'saved-fixture',digest:'synthetic-digest',revision:1}}};
  window.presentation=installPresentation({anchor:document.querySelector('main'),busy:()=>window.displayBusy,identity:()=>({assistantId:'synthetic'}),playback:()=>({playing:false,amplitude:0}),api:async(_path,options)=>{if(options)window.displayWrites++;return window.fixtureDisplay;}});window.presentation.refresh();
 });
 await page.waitForFunction(()=>document.querySelector('[aria-label="Appearance"]').value==='saved-fixture');
 assert.equal(await page.evaluate(()=>window.displayAttempts),0,'busy refresh must defer package preparation');
 await page.evaluate(()=>{window.displayBusy=false;window.presentation.settle?.();});
 await page.waitForFunction(()=>window.displayAttempts===1);await page.evaluate(()=>window.finishDisplayPrepare());await page.waitForFunction(()=>window.displayCommits.includes('Saved fixture'));
 await page.evaluate(()=>{dispatchEvent(new CustomEvent('lifestream-audience',{detail:{privateAllowed:true}}));});
 await page.waitForFunction(()=>window.displayAttempts===2);const before=await page.evaluate(()=>window.displayCommits.filter(x=>x==='Saved fixture').length);
 await page.evaluate(()=>{window.displayBusy=true;window.finishDisplayPrepare();});await page.waitForFunction(()=>!window.presentation.pending);
 assert.equal(await page.evaluate(()=>window.displayCommits.filter(x=>x==='Saved fixture').length),before,'saved display cannot commit during speech or microphone setup');assert.ok(await page.evaluate(()=>window.displayReleases.includes('Saved fixture')),'interrupted prepared geometry must be released');
 await page.evaluate(()=>{window.displayBusy=false;window.presentation.settle?.();window.presentation.settle?.();});await page.waitForFunction(()=>window.displayAttempts===3);await page.evaluate(()=>window.finishDisplayPrepare());await page.waitForFunction(n=>window.displayCommits.filter(x=>x==='Saved fixture').length===n,before+1);
 for(const event of ['privacy','navigation','signout']){
  await page.evaluate(()=>{window.displayBusy=true;dispatchEvent(new CustomEvent('lifestream-audience',{detail:{privateAllowed:true}}));});await page.waitForFunction(()=>!window.presentation.pending);
  const attempts=await page.evaluate(()=>window.displayAttempts);
  await page.evaluate(event=>{if(event==='privacy')dispatchEvent(new CustomEvent('lifestream-audience',{detail:{privateAllowed:false}}));if(event==='navigation')location.hash='#account';if(event==='signout'){window.lifestreamAuth.session=null;dispatchEvent(new Event('lifestream-auth'));}},event);
  await page.evaluate(async()=>{await new Promise(r=>setTimeout(r,0));window.displayBusy=false;window.presentation.settle?.();await new Promise(r=>setTimeout(r,0));});assert.equal(await page.evaluate(()=>window.displayAttempts),attempts,`${event} must discard the deferred appearance`);
  await page.evaluate(()=>{window.displayBusy=true;window.lifestreamAuth.session={principalId:'synthetic'};location.hash='#conversation';dispatchEvent(new CustomEvent('lifestream-audience',{detail:{privateAllowed:true}}));});
  await page.waitForFunction(()=>document.querySelector('[aria-label="Appearance"]').value==='saved-fixture');
 }
 await page.evaluate(()=>{window.displayBusy=false;window.rejectDisplayPrepare=true;window.presentation.settle?.();});const next=await page.evaluate(()=>window.displayAttempts);await page.waitForFunction(()=>window.presentation.pending);await page.evaluate(()=>window.finishDisplayPrepare());await page.waitForFunction(()=>!window.presentation.pending);
 await page.evaluate(async()=>{window.presentation.settle?.();window.presentation.settle?.();await new Promise(r=>setTimeout(r,0));});assert.equal(await page.evaluate(()=>window.displayAttempts),next,'invalid packages must not retry automatically');assert.match(await page.locator('.presentation-controls > [role=status]').textContent(),/Synthetic invalid package/);
 assert.equal(await page.evaluate(()=>window.displayWrites),0,'restoration must not rewrite the saved selection');assert.deepEqual(errors,[]);
});
