import assert from 'node:assert/strict';
import test from 'node:test';
import {readFile} from 'node:fs/promises';
test('memory mode reflects durable policy and preserves an unsaved choice across an unchanged refresh',{skip:!process.env.PLAYWRIGHT_MODULE},async t=>{
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage();
 const source=await readFile(new URL('../automatic-memory.js',import.meta.url),'utf8');
 await page.route('http://127.0.0.1:9/**',route=>route.fulfill({contentType:route.request().url().endsWith('.js')?'text/javascript':'text/html',body:route.request().url().endsWith('.js')?source:'<main></main>'}));await page.goto('http://127.0.0.1:9/');
 await page.evaluate(async()=>{window.lifestreamAuth={session:{sessionId:'synthetic'}};window.policy={enabled:false,revision:1};const {installAutomaticMemory}=await import('/automatic-memory.js');installAutomaticMemory({anchor:document.querySelector('main'),context:()=>({assistantId:'synthetic',relationship:{relationshipId:'synthetic'}}),api:async(_path,options)=>{if(options){const body=JSON.parse(options.body);if(body.expectedRevision!==window.policy.revision)throw Error('conflict');window.policy={enabled:body.enabled,revision:window.policy.revision+1};}return {policy:{...window.policy},jobs:window.jobs??[]};}});});
 await page.evaluate(()=>{window.jobs=[{state:'saved',result:JSON.stringify({rejectedItemCount:1})}];});
 const checkbox=page.locator('[data-memory-enabled]'),refresh=page.getByRole('button',{name:'Refresh memory status'});
 await refresh.click();await page.waitForFunction(()=>document.querySelector('.room-memory > [role="status"]').textContent.includes('Automatic memory off'));assert.equal(await checkbox.isChecked(),false);assert.match(await page.locator('.room-memory > [role="status"]').textContent(),/1 unsafe or malformed extracted item rejected; valid items were handled separately/);
 await checkbox.check();await refresh.click();assert.equal(await checkbox.isChecked(),true,'an unchanged background read must not erase an unsaved edit');
 await page.getByRole('button',{name:'Apply memory mode'}).click();await page.waitForFunction(()=>document.querySelector('.room-memory > [role="status"]').textContent.includes('Automatic memory enabled'));await refresh.click();assert.equal(await checkbox.isChecked(),true);
 await page.evaluate(()=>{window.policy={enabled:false,revision:3};});await refresh.click();await page.waitForFunction(()=>!document.querySelector('[data-memory-enabled]').checked);assert.match(await page.locator('.room-memory > [role="status"]').textContent(),/Automatic memory off/);
});

test('visual policy requires explicit retention, preserves edits, safely renders observation and forgets it',{skip:!process.env.PLAYWRIGHT_MODULE},async t=>{
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:960,height:1000}}),source=await readFile(new URL('../automatic-memory.js',import.meta.url),'utf8');
 await page.route('http://127.0.0.1:9/**',route=>route.fulfill({contentType:route.request().url().endsWith('.js')?'text/javascript':'text/html',body:route.request().url().endsWith('.js')?source:'<style>body{background:#101c28;color:#eef3f7;font:17px system-ui;padding:24px}main{max-width:820px;margin:auto}label{display:block;margin:14px 0}button{padding:10px;margin:8px 8px 8px 0}input[type=number]{padding:8px}a{color:#91e1d4}.visual-memory{border:1px solid #587484;padding:20px;margin-top:24px}article{border-top:1px solid #587484}</style><main></main>'}));await page.goto('http://127.0.0.1:9/');
 await page.evaluate(async()=>{window.lifestreamAuth={session:{sessionId:'synthetic'}};window.posts=[];window.data={policy:{enabled:true,revision:1},jobs:[],visual:{policy:{enabled:false,revision:0,retentionMs:null},episodes:[],complete:true}};const {installAutomaticMemory}=await import('/automatic-memory.js');installAutomaticMemory({anchor:document.querySelector('main'),context:()=>({assistantId:'synthetic-assistant',relationship:{relationshipId:'synthetic-relationship'}}),api:async(_url,options)=>{if(options){const body=JSON.parse(options.body);window.posts.push(body);if(body.operation==='configureVisual'){if(window.fail)throw Error('Synthetic visual policy conflict; refresh required.');window.data.visual.policy={enabled:body.enabled,revision:window.data.visual.policy.revision+1,retentionMs:body.retentionMs};}if(body.operation==='forgetVisual')window.data.visual.episodes=[{episodeId:body.id,revision:body.expectedRevision+1,state:'forgotten',episode:null}];}return structuredClone(window.data);}});});
 await page.getByRole('button',{name:'Refresh memory status'}).click();const enabled=page.locator('[data-visual-memory-enabled]'),days=page.getByLabel('Visual memory retention in days'),apply=page.getByRole('button',{name:'Apply visual memory policy'});assert.equal(await enabled.isChecked(),false);assert.equal(await days.inputValue(),'');await enabled.check();await apply.click();await page.waitForFunction(()=>document.querySelector('[data-visual-memory-status]').textContent.includes('explicit positive'));assert.equal(await page.evaluate(()=>window.posts.length),0);await days.fill('3');await apply.click();await page.waitForFunction(()=>document.querySelector('[data-visual-memory-status]').textContent.includes('Visual memory enabled'));assert.equal(await page.evaluate(()=>window.posts[0].retentionMs),259200000);
 await enabled.uncheck();await page.getByRole('button',{name:'Refresh memory status'}).click();assert.equal(await enabled.isChecked(),false,'unchanged policy reads preserve pending edits');
 await page.evaluate(()=>{window.data.visual.episodes=[{episodeId:'synthetic-episode',revision:1,state:'retained',expiresAt:'2026-10-02T12:00:00Z',episode:{summary:'<img src=x onerror="window.sceneInjected=true"> synthetic uncertain blue hat',occurredAt:'2026-09-29T12:00:00Z'}}];window.data.visual.complete=false;});await page.getByRole('button',{name:'Refresh memory status'}).click();assert.match(await page.locator('[data-visual-memory-status]').textContent(),/missing coverage/);assert.equal(await page.locator('[data-visual-memory-episodes] img').count(),0);assert.equal(await page.evaluate(()=>window.sceneInjected),undefined);
 if(process.env.VISUAL_MEMORY_SCREENSHOT)await page.screenshot({path:process.env.VISUAL_MEMORY_SCREENSHOT,fullPage:true});
 await page.getByRole('button',{name:'Forget visual observation'}).click();await page.waitForFunction(()=>document.querySelector('[data-visual-memory-episodes]').textContent.includes('payload removed'));assert.equal(await page.getByRole('button',{name:'Forget visual observation'}).count(),0);assert.equal(await page.evaluate(()=>window.posts.at(-1).expectedRevision),1);
 await page.evaluate(()=>{window.fail=true;});await apply.click();await page.waitForFunction(()=>document.querySelector('[data-visual-memory-status]').textContent.includes('Synthetic visual policy conflict'));assert.equal(await apply.isEnabled(),true);
 await page.evaluate(()=>window.dispatchEvent(new Event('lifestream-relationship')));await page.waitForFunction(()=>document.querySelector('[data-visual-memory-enabled]').checked===true);assert.equal(await days.inputValue(),'3');
});
