import assert from 'node:assert/strict';
import test from 'node:test';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {join} from 'node:path';
const enabled=!!process.env.PLAYWRIGHT_MODULE;
async function fixture(t,owner=false){
 const requests=[],permission={revision:1,ownerAllowed:true,consented:false},memory={id:'memory',content:'User stated: My bicycle code word is amber maple.',provenance:{source:'turn:synthetic'},lifecycle:{revision:1,status:'active',confidence:1}},personal={assistantId:'assistant',permission,eligible:true,relationshipId:null,relationshipRevision:1,memory:null,memories:[]};
 const subscription={id:'destination',assistantId:'assistant',principalId:'person',label:'Personal chat',channel:'telegram',status:'unpaired',revision:1,requestedConversations:true,requestedAlerts:false,personalContext:permission};let hold;
 const server=createServer(async(req,res)=>{if(req.url.startsWith('/api/')){let text='';for await(const chunk of req)text+=chunk;const body=text?JSON.parse(text):null;if(body)requests.push(body);let data;
  if(req.url.startsWith('/api/runtime/v1/my-personal-context')){data=personal;if(body?.operation==='consent'){permission.consented=body.enabled;permission.revision++;personal.relationshipId='own-relationship';personal.memory={policy:{revision:0,enabled:false},jobs:[]};}else if(body?.operation==='collection'){personal.memory.policy={enabled:body.enabled,revision:body.expectedRevision+1};if(body.enabled)personal.memories=[memory];}else if(body?.operation==='correct'){data={event:{revision:2,payload:{proposedContent:body.content}}};}else if(body?.operation==='applyCorrection'){memory.content='User stated: My bicycle code word is blue cedar.';memory.lifecycle.revision++;data={applied:true};}else if(body?.operation==='retryPrivacy'){personal.privacyReceipts=[];data={receipt:{status:'completed'}};}else if(body?.operation==='forgetPreview'){data={preview:{}};}else if(body?.operation==='forget'){memory.content='';memory.lifecycle={...memory.lifecycle,status:'invalidated',contentRemoved:true};if(personal.partial){personal.privacyReceipts=[{operationId:'operation',retryRequired:true}];data={receipt:{status:'partial',retryRequired:true}};}else data={receipt:{status:'completed'}};}}
  else if(req.url.startsWith('/api/runtime/v1/channel-subscriptions')){if(body?.operation==='personalContext'){permission.ownerAllowed=body.allowed;permission.consented=false;permission.revision++;}data={subscriptions:[subscription],accounts:[{principalId:'person',username:'Subscriber'}]};}
  else data={personalContextAvailable:true,subscriptions:[subscription]};
  const content=JSON.stringify(data),send=()=>{res.setHeader('content-type','application/json');res.end(content);};if(hold){hold(send);hold=null;}else send();return;
 }
 if(['/my-channels.js','/channel-subscriptions.js','/styles.css'].includes(req.url)){res.setHeader('content-type',req.url.endsWith('.js')?'text/javascript':'text/css');res.end(await readFile(new URL('..'+req.url,import.meta.url)));return;}res.end('<!doctype html><html lang="en" data-audience-protected="false"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/styles.css"><main class="shell card"></main></html>');});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>{server.closeAllConnections();server.close();});const base='http://127.0.0.1:'+server.address().port,{chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));t.after(()=>assert.deepEqual(errors,[]));await page.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());await page.goto(base+(owner?'/#conversation':'/#account'));
 await page.evaluate(async owner=>{window.identity='synthetic';const api=async(path,options)=>(await fetch(path,options)).json(),anchor=document.querySelector('main');if(owner){const {installChannelSubscriptions}=await import('/channel-subscriptions.js');installChannelSubscriptions({anchor,api,scope:()=>({assistantId:'assistant'})});}else{const {installMyChannels}=await import('/my-channels.js');installMyChannels({anchor,api,identity:()=>window.identity});}},owner);
 const click=async name=>{await page.getByRole('button',{name,exact:true}).click();await page.waitForFunction(()=>!document.querySelector('[data-mine-refresh],[data-channel-refresh]').disabled);};return {page,requests,permission,personal,click,hold:fn=>hold=fn};
}
test('subscriber consent, collection, correction review/cancel/apply, forgetting review/cancel/apply and withdrawal are reachable',{skip:!enabled},async t=>{
 const f=await fixture(t),{page,click}=f;await click('Refresh my connections');await click('Review my personal context');await click('Consent to my personal context');await click('Enable automatic memory');assert.equal(f.permission.consented,true);await click('Refresh my memory');
 await page.getByLabel('Correct this memory',{exact:true}).fill('User stated: My bicycle code word is blue cedar.');await click('Review correction');await click('Cancel correction review');await click('Review correction');await click('Apply my correction');await page.getByText('User stated: My bicycle code word is blue cedar.',{exact:true}).waitFor();
 if(process.env.SUBSCRIBER_QA_DIRECTORY){await mkdir(process.env.SUBSCRIBER_QA_DIRECTORY,{recursive:true});await page.screenshot({path:join(process.env.SUBSCRIBER_QA_DIRECTORY,'personal-context-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:join(process.env.SUBSCRIBER_QA_DIRECTORY,'personal-context-mobile.png'),fullPage:true});}
 await click('Review forgetting');await click('Cancel forgetting');await click('Review forgetting');await click('Confirm forget my memory');assert.equal(await page.getByRole('button',{name:'Review forgetting'}).count(),0);await click('Stop automatic memory');await click('Withdraw my context consent');assert.equal(f.permission.consented,false);assert.deepEqual(f.requests.map(r=>r.operation),['consent','collection','correct','correct','applyCorrection','forgetPreview','forgetPreview','forget','collection','consent']);assert.equal(f.requests.filter(r=>r.operation==='forgetPreview').at(-1).idempotencyKey,f.requests.find(r=>r.operation==='forget').idempotencyKey);
});
test('private memory and late replies clear when audience or account changes',{skip:!enabled},async t=>{const f=await fixture(t);await f.click('Refresh my connections');let release;f.hold(fn=>release=fn);await f.page.getByRole('button',{name:'Review my personal context'}).click();for(let n=0;n<100&&!release;n++)await new Promise(r=>setTimeout(r,10));assert.ok(release);await f.page.evaluate(()=>{document.documentElement.dataset.audienceProtected='true';dispatchEvent(new Event('lifestream-audience'));});release();await f.page.waitForTimeout(50);assert.equal(await f.page.locator('[data-mine-list]').innerText(),'');await f.click('Refresh my connections');await f.click('Review my personal context');await f.page.getByText('Select a personal session and declare a private audience before reviewing memory.').waitFor();assert.equal(await f.page.getByRole('button',{name:'Consent to my personal context'}).count(),0);});
test('owner permission applies to one person and revocation clears separate consent without granting administrator access',{skip:!enabled},async t=>{const f=await fixture(t,true);await f.click('Refresh subscribers');await f.click('Revoke personal context');assert.equal(f.permission.ownerAllowed,false);await f.click('Permit personal context');assert.equal(f.permission.ownerAllowed,true);assert.equal(f.permission.consented,false);assert.deepEqual(f.requests.map(r=>({principalId:r.principalId,allowed:r.allowed})),[{principalId:'person',allowed:false},{principalId:'person',allowed:true}]);});

test('interrupted privacy cleanup remains retryable after memory disappears and panel refreshes',{skip:!enabled},async t=>{const f=await fixture(t);await f.click('Refresh my connections');await f.click('Review my personal context');await f.click('Consent to my personal context');await f.click('Enable automatic memory');f.personal.partial=true;await f.click('Review forgetting');await f.click('Confirm forget my memory');await f.click('Refresh my memory');await f.click('Retry privacy cleanup');assert.equal(await f.page.getByRole('button',{name:'Retry privacy cleanup'}).count(),0);assert.equal(f.requests.at(-1).operation,'retryPrivacy');});
