import assert from 'node:assert/strict';
import test from 'node:test';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {join} from 'node:path';
const enabled=!!process.env.PLAYWRIGHT_MODULE;
async function fixture(t){
 const data={accounts:[{principalId:'person.one',username:'Owner'},{principalId:'person.two',username:'Second person'}],subscriptions:[],transportReady:false,pairingAvailable:false},requests=[];let held;
 const server=createServer(async(req,res)=>{
  if(req.url.startsWith('/api/')){let body='';for await(const chunk of req)body+=chunk;const input=body?JSON.parse(body):null;if(input){requests.push(input);if(input.operation==='create')data.subscriptions.push({...input,id:'destination.'+requests.length,revision:1,status:'unpaired',connection:{pairingState:'unpaired',conversationsEnabled:false,alertsEnabled:false,transportReady:false}});else{const item=data.subscriptions.find(x=>x.id===input.id);assert.equal(input.expectedRevision,item.revision);if(input.operation==='update')Object.assign(item,input);else Object.assign(item,{requestedConversations:false,requestedAlerts:false,status:input.operation==='remove'?'removed':'disabled'});item.revision++;}}
   const result=JSON.stringify(data),send=()=>{res.writeHead(200,{'content-type':'application/json'});res.end(result);};if(held){held(send);held=null;}else send();return;
  }
  if(['/channel-subscriptions.js','/styles.css'].includes(req.url)){res.writeHead(200,{'content-type':req.url.endsWith('.js')?'text/javascript':'text/css'});res.end(await readFile(new URL('..'+req.url,import.meta.url)));return;}
  res.end('<!doctype html><html lang="en" data-audience-protected="false"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/styles.css"><main class="shell card"></main></html>');
 });await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>{server.closeAllConnections();server.close();});const base='http://127.0.0.1:'+server.address().port;
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-background-networking','--disable-component-update','--disable-sync']});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1280,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));t.after(()=>assert.deepEqual(errors,[]));await page.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());
 await page.goto(base+'/#conversation');await page.evaluate(async()=>{window.scope={assistantId:'assistant.one'};const {installChannelSubscriptions}=await import('/channel-subscriptions.js');installChannelSubscriptions({anchor:document.querySelector('main'),scope:()=>window.scope,api:async(path,options)=>(await fetch(path,options)).json()});});
 const refresh=async()=>{await page.getByRole('button',{name:'Refresh subscribers'}).click();await page.waitForFunction(()=>!document.querySelector('[data-channel-refresh]').disabled);};
 const save=async()=>{await page.getByRole('button',{name:'Save destination'}).click();await page.waitForFunction(()=>document.querySelector('[data-channel-status]').textContent.startsWith('Destination saved.')&&!document.querySelector('[data-channel-save]').disabled);};
 return {page,data,requests,refresh,save,hold:fn=>{held=fn;}};
}
test('rendered subscribers plane supports both people and multiple destinations, edits, disable and historical remove',{skip:!enabled},async t=>{
 const f=await fixture(t),p=f.page;assert.equal(await p.getByRole('button',{name:'Save destination'}).isDisabled(),true);await f.refresh();
 for(const [person,label] of [['person.one','Owner personal Telegram'],['person.one','Owner second Telegram'],['person.two','Second person Telegram']]){await p.getByLabel('Subscriber',{exact:true}).selectOption(person);await p.getByLabel('Destination name').fill(label);await p.getByLabel('Request two-way Assistant conversations').check();await p.getByLabel('Request while-away alerts').check();await f.save();}
 assert.equal(f.data.subscriptions.length,3);assert.equal(f.requests.filter(r=>r.operation==='create'&&r.principalId==='person.one').length,2);assert.equal(await p.getByText('Pairing: unpaired',{exact:true}).count(),3);
 await p.getByRole('button',{name:'Edit destination',exact:true}).first().click();assert.equal(await p.getByLabel('Subscriber',{exact:true}).isDisabled(),true);await p.getByLabel('Destination name').fill('Discard this edit');await p.getByRole('button',{name:'Cancel edit'}).click();assert.equal(f.data.subscriptions[0].label,'Owner personal Telegram');
 await p.getByRole('button',{name:'Edit destination',exact:true}).first().click();await p.getByLabel('Destination name').fill('Owner preferred chat');await p.getByLabel('Request while-away alerts').uncheck();await f.save();assert.equal(f.data.subscriptions[0].label,'Owner preferred chat');assert.equal(f.data.subscriptions[0].requestedAlerts,false);
 await p.getByRole('button',{name:'Disable destination',exact:true}).first().click();await p.getByText('Disabled · no requested permissions',{exact:true}).waitFor();assert.equal(f.data.subscriptions[0].requestedConversations,false);
 await p.getByRole('button',{name:'Remove destination',exact:true}).first().click();await p.getByText('Removed · history retained',{exact:true}).waitFor();assert.equal(f.data.subscriptions.length,3);assert.equal(await p.getByRole('button',{name:'Edit destination',exact:true}).count(),2);
 await p.getByLabel('Subscriber',{exact:true}).selectOption('person.two');await p.getByLabel('Channel',{exact:true}).selectOption('ios-push');assert.equal(await p.getByLabel('Request two-way Assistant conversations').isDisabled(),true);await p.getByLabel('Destination name').fill('Future phone');await p.getByLabel('Request while-away alerts').check();await f.save();await p.getByText('Deferred · mobile endpoint required',{exact:true}).waitFor();assert.equal(f.data.subscriptions[3].requestedConversations,false);
 if(process.env.SUBSCRIBER_QA_DIRECTORY){await mkdir(process.env.SUBSCRIBER_QA_DIRECTORY,{recursive:true});await p.screenshot({path:join(process.env.SUBSCRIBER_QA_DIRECTORY,'subscribers-desktop.png'),fullPage:true});await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.screenshot({path:join(process.env.SUBSCRIBER_QA_DIRECTORY,'subscribers-mobile.png'),fullPage:true});}
});
test('subscriber names render as text and late refresh is discarded on audience or Assistant change',{skip:!enabled},async t=>{
 const f=await fixture(t);f.data.accounts[0].username='<img src=x onerror=alert(1)>';f.data.subscriptions.push({id:'destination.one',principalId:'person.one',channel:'telegram',label:'<script>unsafe()</script>',status:'unpaired',revision:1,requestedConversations:false,requestedAlerts:false});await f.refresh();assert.equal(await f.page.locator('script').count(),0);assert.match(await f.page.locator('[data-channel-list]').innerText(),/<script>unsafe/);
 let release;f.hold(fn=>{release=fn;});await f.page.getByRole('button',{name:'Refresh subscribers'}).click();for(let i=0;i<100&&!release;i++)await new Promise(r=>setTimeout(r,10));assert.ok(release);await f.page.evaluate(()=>{document.documentElement.dataset.audienceProtected='true';dispatchEvent(new Event('lifestream-audience'));});release();await f.page.waitForTimeout(50);assert.equal(await f.page.locator('[data-channel-list]').innerText(),'');assert.equal(await f.page.getByRole('button',{name:'Save destination'}).isDisabled(),true);assert.equal(f.requests.length,0);
});

test('owner subscriber cards distinguish paired consent and host readiness without implying delivery',{skip:!enabled},async t=>{
 const f=await fixture(t);Object.assign(f.data,{transportConfigured:true,transportReady:true,alertCompositionConfigured:false});f.data.subscriptions=[{id:'paired',principalId:'person.two',channel:'telegram',label:'Paired destination',revision:1,status:'unpaired',requestedConversations:true,requestedAlerts:true,connection:{pairingState:'paired',conversationsEnabled:true,alertsEnabled:false,transportReady:true}}];await f.refresh();assert.match(await f.page.locator('[data-channel-list]').innerText(),/Paired · host connected/);assert.match(await f.page.locator('[data-channel-list]').innerText(),/conversations enabled; alerts disabled/);assert.doesNotMatch(await f.page.locator('[data-channel-list]').innerText(),/No live delivery|Not connected/);
 if(process.env.SUBSCRIBER_QA_DIRECTORY){await mkdir(process.env.SUBSCRIBER_QA_DIRECTORY,{recursive:true});await f.page.screenshot({path:join(process.env.SUBSCRIBER_QA_DIRECTORY,'owner-paired-desktop.png'),fullPage:true});await f.page.setViewportSize({width:390,height:844});assert.equal(await f.page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await f.page.screenshot({path:join(process.env.SUBSCRIBER_QA_DIRECTORY,'owner-paired-mobile.png'),fullPage:true});}
 f.data.transportReady=false;f.data.subscriptions[0].connection.transportReady=false;await f.refresh();assert.match(await f.page.locator('[data-channel-status]').innerText(),/configured but unavailable or disabled/);assert.match(await f.page.locator('[data-channel-list]').innerText(),/Paired · host unavailable/);
});
