import assert from 'node:assert/strict';
import {test} from 'node:test';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';

// Component presentation/request test. Protected API and rollback behavior are tested separately.
test('hypothesis review shows competing evidence, confirms exact revision and preserves rejection retries',{skip:!process.env.PLAYWRIGHT_MODULE,timeout:60000},async t=>{
 const server=createServer(async(req,res)=>{
  if(['/discovery-workflows.js','/discovery-lab.js','/styles.css'].includes(req.url)){res.setHeader('content-type',req.url.endsWith('.js')?'text/javascript':'text/css');res.end(await readFile(new URL('..'+req.url,import.meta.url),'utf8'));return;}
  res.setHeader('content-type','text/html');res.end(`<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="/styles.css"><title>Hypothesis review fixture</title></head><body><main><section id="host" class="panel"><section aria-label="Current configuration">Synthetic configuration</section><div class="workflow-step">Settings fixture</div></section><p id="status" role="status"></p></main><script type="module">
  import {installDiscoveryWorkflows} from '/discovery-workflows.js';
  const data={recordType:'hypothesis',hypothesisId:'152e4453-4a82-4a9a-b8a1-c9bb05267853',revision:1,status:'candidate',topicRefs:['topic:synthetic-story'],sourceCoverage:'partial',epistemicStatus:'tentative',explanations:[{summary:'Exploration may matter.',traitRefs:['trait:exploration'],supportEvidenceRefs:['relationship-record:source-a:2'],counterEvidenceRefs:['relationship-record:source-b:1'],boundary:'This synthetic story only.'},{summary:'Novelty may matter.',traitRefs:['trait:novelty'],supportEvidenceRefs:['relationship-record:source-b:1'],counterEvidenceRefs:[],boundary:'No general motive established.'}],unknownAlternative:'Other motives remain unknown.',uncertainty:'Partial evidence cannot establish a personal motive.',configurationRef:'configuration:synthetic:1',dependencyRefs:['evidence:source-a:2']};
  window.requests=[];let rejectionFailed=false,ui;const status=text=>document.querySelector('#status').textContent=text;
  const guard=fn=>async event=>{event?.preventDefault?.();try{await fn({});}catch(error){status(error.message);}};
  const refresh=async()=>ui.render([data],{enabled:true,policyRefs:[]});
  ui=installDiscoveryWorkflows({anchor:document.querySelector('#host'),guard,refresh,status,call:async request=>{window.requests.push(structuredClone(request));if(request.decision==='rejectHypothesis'&&!rejectionFailed){rejectionFailed=true;throw new Error('Synthetic storage failure. Retry this exact rejection.');}data.status=request.decision==='rejectHypothesis'?'rejected':'reviewed';data.revision++;return {explanations:[{summary:data.status==='rejected'?'Hypothesis rejected; supporting evidence unchanged.':'Reviewed for usefulness; still tentative.'}]};}});await refresh();window.ready=true;window.clearScope=ui.invalidate;
  </script></body></html>`);
 });await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>server.close());
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1280,height:950}}),errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>window.ready);await page.getByRole('button',{name:'Hypotheses',exact:true}).click();await page.getByRole('button',{name:'Inspect hypothesis',exact:true}).click();const detail=page.locator('[data-hypothesis-detail]');
 assert.match(await detail.textContent(),/Possible explanation 1/);assert.match(await detail.textContent(),/Possible explanation 2/);assert.match(await detail.textContent(),/Other motives remain unknown/);
 await detail.locator('summary').filter({hasText:'Supporting evidence and counterevidence'}).first().click();assert.equal(await detail.getByText('relationship-record:source-a:2',{exact:true}).isVisible(),true);
 await detail.getByLabel('Reason',{exact:true}).fill('Useful to consider, not a declaration.');await detail.getByRole('button',{name:'Review decision',exact:true}).click();assert.equal((await page.evaluate(()=>window.requests)).length,0);assert.match(await detail.locator('[data-hypothesis-consequence]').textContent(),/revision 1/);await detail.getByRole('button',{name:'Confirm hypothesis decision',exact:true}).click();await page.getByRole('status').filter({hasText:'Reviewed for usefulness'}).waitFor();assert.match(await detail.textContent(),/reviewed · revision 2/);assert.equal(await detail.getByLabel('Decision',{exact:true}).inputValue(),'rejectHypothesis');
 await detail.getByLabel('Reason',{exact:true}).fill('Not useful; retain the observations.');await detail.getByRole('button',{name:'Review decision',exact:true}).click();await detail.getByRole('button',{name:'Confirm hypothesis decision',exact:true}).click();await page.getByRole('status').filter({hasText:'Synthetic storage failure'}).waitFor();await detail.getByRole('button',{name:'Confirm hypothesis decision',exact:true}).click();await page.getByRole('status').filter({hasText:'Hypothesis rejected'}).waitFor();
 const requests=await page.evaluate(()=>window.requests);assert.deepEqual(requests[1],requests[2]);assert.equal(requests[1].expectedRevision,2);assert.equal(await detail.locator('form').count(),0);assert.match(await detail.textContent(),/rejected · revision 3/);
 await page.screenshot({path:'/private/tmp/lifestream-hypothesis-review-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.match(await page.locator('[data-hypothesis-list] td').first().evaluate(node=>getComputedStyle(node,'::before').content),/Hypothesis ID/);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/private/tmp/lifestream-hypothesis-review-mobile.png',fullPage:true});
 await page.evaluate(()=>window.clearScope());assert.equal(await detail.isVisible(),false);assert.doesNotMatch(await page.locator('#host').textContent(),/Exploration may matter/);assert.deepEqual(errors,[]);
});
