import assert from 'node:assert/strict';
import {test} from 'node:test';
import {randomBytes} from 'node:crypto';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createLifestreamServer} from '../../server/src/index.ts';
import {loadProfile} from '../../server/src/config/loader.ts';

test('Discovery Lab compares a draft through protected API with readable failed input checks and no activation',{skip:!process.env.PLAYWRIGHT_MODULE,timeout:90000},async t=>{
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),root=await mkdtemp(join(tmpdir(),'ls-discovery-lab-browser-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex');const app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'safety'),installerToken}});await app.start();t.after(()=>app.shutdown());
 const browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1450,height:1000}}),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(`http://127.0.0.1:${app.address().port}/control/`);await page.waitForFunction(()=>!!window.lifestreamUI);
 await page.locator('#auth-username').fill('owner');await page.locator('#auth-password').fill(randomBytes(32).toString('hex'));await page.locator('#auth-installer-token').fill(installerToken);await page.locator('#auth-setup').click();await page.waitForFunction(()=>!!window.lifestreamAuth.session);await page.locator('#new-assistant').click();await page.waitForFunction(()=>document.querySelector('#result').textContent.includes('Assistant created'));
 await page.locator('[data-destination=relationship]').click();await page.locator('#relationship-create').click();await page.waitForFunction(()=>document.querySelector('#relationship-results').textContent.includes('revision 1'));await page.locator('[data-destination=discovery]').click();const panel=page.locator('.relationship-understanding'),status=panel.locator('[data-role=status]');await panel.locator('[data-action=refresh]').click();await status.filter({hasText:'Settings loaded'}).waitFor();
 await panel.locator('[data-path=enabled]').check();await panel.getByText('Sources, exclusions & preparation limits',{exact:true}).click();await panel.locator('[data-path=policyRefs]').fill('policy:discovery-lab-v1');await panel.getByRole('button',{name:'Save review draft',exact:true}).click();await status.filter({hasText:'Draft saved'}).waitFor();
 await panel.getByRole('button',{name:'Input Lab',exact:true}).click();const lab=panel.locator('[data-discovery-panel=lab]');assert.match(await lab.getByLabel('Configuration to compare',{exact:true}).textContent(),/draft/);await lab.getByRole('button',{name:'Run input comparison',exact:true}).click();await lab.getByRole('button',{name:'Refresh comparison',exact:true}).waitFor();
 for(let n=0;n<30&&!await lab.locator('[data-discovery-lab-result]').isVisible();n++){await page.waitForTimeout(150);await lab.getByRole('button',{name:'Refresh comparison',exact:true}).click();}
 const result=lab.locator('[data-discovery-lab-result]');assert.equal(await result.isVisible(),true);assert.match(await result.locator('[data-lab-summary]').textContent(),/18 canonical requests/);assert.match(await result.locator('[data-lab-summary]').textContent(),/No model was called/);assert.equal(await result.locator('article').count(),3);assert.match(await result.locator('article').nth(1).textContent(),/Input expectation failed/);assert.match(await panel.locator('[data-role=active]').textContent(),/no activated extension/);
 await result.locator('article').nth(1).getByText('Inspect assembled input',{exact:true}).click();const input=page.getByRole('dialog');assert.match(await input.textContent(),/FOREST_DETAIL_281/);assert.match(await input.textContent(),/STELLAR_DETAIL_392/);await page.screenshot({path:'/private/tmp/lifestream-discovery-lab-input.png'});await input.getByRole('button',{name:'Close input'}).click();
 await page.screenshot({path:'/private/tmp/lifestream-discovery-lab-desktop.png',fullPage:true});await result.getByLabel('Scenario',{exact:true}).selectOption('heldout-mineral');assert.match(await result.locator('article').nth(1).textContent(),/Input checks passed/);await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/private/tmp/lifestream-discovery-lab-mobile.png',fullPage:true});
 await page.locator('.nav-toggle').click();await page.locator('[data-destination=account]').click();await page.locator('#auth-sign-out').click();await page.waitForFunction(()=>!window.lifestreamAuth.session);assert.equal(await result.isVisible(),false);assert.doesNotMatch(await lab.textContent(),/BASALT_DETAIL_573/);assert.deepEqual(errors,[]);
});
