import assert from 'node:assert/strict';
import test from 'node:test';
import {mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {randomBytes} from 'node:crypto';
import {createLifestreamServer} from '../../server/src/index.ts';
import {loadProfile} from '../../server/src/config/loader.ts';

test('effective configuration renders real revisions and clears protected or late responses without a renderer',{skip:!process.env.PLAYWRIGHT_MODULE},async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-effective-browser-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};config.authority.authentication='local-password';const installerToken=randomBytes(32).toString('hex'),app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'auth'),installerToken},audiencePrivacy:{sourceIds:[]}});await app.start();t.after(()=>app.shutdown());
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[];page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${app.address().port}/control/#account`);await page.evaluate(()=>window.lifestreamAuth.ready);await page.waitForFunction(()=>!!window.lifestreamUI);await page.locator('#auth-username').fill('owner');await page.locator('#auth-password').fill('Synthetic-config-password-1');await page.locator('#auth-installer-token').fill(installerToken);const enrollment=page.waitForResponse(r=>r.url().endsWith('/api/auth/v1/setup'));await page.locator('#auth-setup').click();const enrolled=await enrollment;assert.equal(enrolled.status(),201,'local enrollment must succeed');await page.waitForFunction(()=>!!window.lifestreamAuth.session&&document.querySelector('#session-context-status').textContent.includes('revision 0')).catch(async error=>{t.diagnostic(JSON.stringify(await page.evaluate(()=>({authenticated:!!window.lifestreamAuth.session,authStatus:document.querySelector('#auth-status').textContent,sessionStatus:document.querySelector('#session-context-status').textContent}))));throw error;});
 const navigate=async id=>{await page.locator(`[data-destination=${id}]`).click();await page.waitForFunction(id=>!document.querySelector(`[data-view=${id}]`).hidden,id);};
 await navigate('session');assert.equal(await page.locator('#endpoint-configuration-panel').isVisible(),false);await page.locator('#session-context-apply').click();await page.waitForFunction(()=>document.querySelector('#session-context-status').textContent.includes('revision 1'));await page.locator('[data-audience-solo]').click();await page.waitForFunction(()=>document.querySelector('[data-effective-status]').textContent.includes('Current read-only'));assert.match(await page.locator('[data-effective-values]').textContent(),/Select an Assistant/);
 await page.locator('[data-effective-route=profile]').click();await page.locator('#new-assistant').click();await page.waitForFunction(()=>document.querySelector('#result').textContent.includes('Assistant created'));await page.locator('#activate').click();await page.waitForFunction(()=>document.querySelector('#editor-status').textContent==='active');await navigate('session');await page.waitForFunction(()=>document.querySelector('[data-effective-values]').textContent.includes('Active profile revision 1'));const first=JSON.parse(await page.locator('[data-effective-details]').textContent());assert.equal(first.session.revision,1);assert.equal(first.disclosure.effectiveScope,'unknown');assert.equal(first.presentation.source,'neutralFallback');assert.equal(first.audioOwnership.active,false);
 await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>document.querySelector('[data-effective-values]').textContent.includes('Reduced motion: on for this display'));assert.equal(JSON.parse(await page.locator('[data-effective-details]').textContent()).session.revision,1);await page.emulateMedia({reducedMotion:'no-preference'});await page.waitForFunction(()=>document.querySelector('[data-effective-values]').textContent.includes('Reduced motion: off for this display'));
 await page.locator('[data-effective-refresh]').click();await page.waitForFunction(()=>document.querySelector('[data-effective-status]').textContent.includes('Current read-only'));assert.equal(JSON.parse(await page.locator('[data-effective-details]').textContent()).session.revision,1);
 for(const route of ['voice','conversation']){await page.locator(`[data-effective-route=${route}]`).click();await page.waitForFunction(route=>!document.querySelector(`[data-view=${route}]`).hidden,route);await navigate('session');await page.waitForFunction(()=>document.querySelector('[data-effective-status]').textContent.includes('Current read-only'));}
 await page.setViewportSize({width:390,height:844});await page.locator('#endpoint-configuration-panel').scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await page.setViewportSize({width:1280,height:1000});
 // Hold a real authorized response, then change audience before delivery.
 let release,seen;const gate=new Promise(r=>release=r),captured=new Promise(r=>seen=r);await page.route('**/api/runtime/v1/endpoint-configuration?**',async route=>{const response=await route.fetch();seen();await gate;await route.fulfill({response});});await page.locator('[data-effective-refresh]').click();await captured;await page.locator('[data-audience-shared]').click();await page.waitForFunction(()=>document.documentElement.dataset.audienceProtected==='true');const received=page.waitForResponse(response=>response.url().includes('/endpoint-configuration'));release();await received;assert.equal(await page.locator('#endpoint-configuration-panel').isVisible(),false);assert.equal(await page.locator('[data-effective-details]').textContent(),'');assert.equal(await page.locator('[data-effective-values]').textContent(),'');await page.unroute('**/api/runtime/v1/endpoint-configuration?**');
 await page.locator('[data-audience-solo]').click();await page.waitForFunction(()=>document.querySelector('[data-effective-status]').textContent.includes('Current read-only'));await navigate('account');await page.locator('#auth-sign-out').click();await page.waitForFunction(()=>!window.lifestreamAuth.session);assert.equal(await page.locator('[data-effective-details]').textContent(),'');assert.deepEqual(errors,[]);
});
