import assert from 'node:assert/strict';
import test from 'node:test';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes} from 'node:crypto';
import {createLifestreamServer} from '../../server/src/index.ts';
import {loadProfile} from '../../server/src/config/loader.ts';

test('rendered experiential controls cover policy, every topic, seeds, reversal, reset, stale scope and mobile layout',{skip:!process.env.PLAYWRIGHT_MODULE},async t=>{
 const root=await mkdtemp(join(tmpdir(),'experience-ui-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex'),app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'safety'),installerToken}});await app.start();t.after(()=>app.shutdown());
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(15000);await page.goto(`http://127.0.0.1:${app.address().port}/control/#discovery`);await page.waitForFunction(()=>window.lifestreamUI);await page.evaluate(()=>window.lifestreamAuth.ready);await page.locator('#auth-username').fill('synthetic-owner');await page.locator('#auth-password').fill('Synthetic-experience-password-1');await page.locator('#auth-installer-token').fill(installerToken);await page.locator('#auth-setup').click();await page.waitForFunction(()=>window.lifestreamAuth.session);
 await page.evaluate(async()=>{const r=(p,b)=>window.lifestreamAuth.request(p,b,b!==undefined),a=await r('/api/admin/v1/assistants',{displayName:'Synthetic shared-experience review',adaptivePersonaPolicy:{dimensions:[{key:'attentionGardening',valueType:'number',minimum:-1,maximum:1,maxDeltaPerDreamingRun:.05,sensitive:false,activation:'automatic'}]}});await r(`/api/admin/v1/assistants/${a.assistantId}/activate`,{profileId:a.profile.profileId,expectedActiveRevision:null});const {relationship}=await r(`/api/admin/v1/assistants/${a.assistantId}/relationships`,{});await r('/api/runtime/v1/memory',{assistantId:a.assistantId,relationshipId:relationship.relationshipId,expectedRevision:0,enabled:true});});await page.reload();await page.waitForFunction(()=>window.lifestreamUI);await page.locator('[data-destination=discovery]').click();const panel=page.locator('.experience-controls'),refresh=panel.getByRole('button',{name:'Refresh learning',exact:true}),status=panel.locator('[role=status]');await refresh.click();await status.filter({hasText:'Off · disabled'}).waitFor();assert.equal(await panel.locator('[data-enabled]').isChecked(),false);
 const topics=panel.locator('[data-topic]');assert.equal(await topics.count(),10);for(let n=0;n<10;n++)await topics.nth(n).selectOption(n<6?'invitationRequired':'disallowed');await panel.locator('[data-enabled]').check();await panel.getByRole('button',{name:'Apply learning settings'}).click();await status.filter({hasText:'Enabled · enabled'}).waitFor();await refresh.click();for(let n=0;n<10;n++)assert.equal(await topics.nth(n).inputValue(),n<6?'invitationRequired':'disallowed');
 await panel.locator('[data-frozen]').check();await panel.getByRole('button',{name:'Apply learning settings'}).click();await status.filter({hasText:'Frozen'}).waitFor();await panel.locator('[data-frozen]').uncheck();await topics.nth(0).selectOption('ordinary');await panel.getByRole('button',{name:'Apply learning settings'}).click();await status.filter({hasText:'Enabled'}).waitFor();
 await panel.locator('summary').click();await panel.locator('[data-dimension]').selectOption('attentionReading');await panel.locator('[data-value]').fill('0.10');await panel.getByRole('button',{name:'Set initial preference'}).click();await status.filter({hasText:'dimension_not_allowed'}).waitFor();await panel.locator('[data-dimension]').selectOption('attentionGardening');await panel.getByRole('button',{name:'Set initial preference'}).click();await panel.getByRole('button',{name:'Reverse this change'}).waitFor();assert.match(await panel.locator('tbody tr').first().textContent(),/0.10/);
 if(process.env.EXPERIENCE_SCREENSHOT){await panel.scrollIntoViewIfNeeded();await page.screenshot({path:process.env.EXPERIENCE_SCREENSHOT,fullPage:true});await page.setViewportSize({width:390,height:844});await panel.scrollIntoViewIfNeeded();await page.screenshot({path:process.env.EXPERIENCE_SCREENSHOT.replace('.png','-mobile.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.setViewportSize({width:1440,height:1000});}
 await panel.getByRole('button',{name:'Reverse this change'}).click();await page.waitForFunction(()=>!document.querySelector('.experience-controls [data-role=lineage] button'));assert.match(await panel.locator('tbody tr').first().textContent(),/0.000.000.00/);await panel.getByRole('button',{name:'Reset learning',exact:true}).click();await status.filter({hasText:'Select the reset confirmation'}).waitFor();await panel.locator('[data-reset-confirm]').check();await panel.getByRole('button',{name:'Reset learning',exact:true}).click();await status.filter({hasText:'Enabled · reset'}).waitFor();assert.equal(await panel.locator('[data-reset-confirm]').isChecked(),false);await panel.locator('[data-enabled]').uncheck();await panel.getByRole('button',{name:'Apply learning settings'}).click();await status.filter({hasText:'Off · disabled'}).waitFor();await page.reload();await page.waitForFunction(()=>window.lifestreamUI);await refresh.click();await status.filter({hasText:'Off · disabled'}).waitFor();
 await page.evaluate(()=>window.dispatchEvent(new CustomEvent('lifestream-audience',{detail:{privateAllowed:false}})));await status.filter({hasText:'Scope changed'}).waitFor();assert.equal(await panel.locator('[data-role=inspection]').textContent(),'');assert.equal(await panel.getByRole('button',{name:'Apply learning settings'}).isDisabled(),true);assert.deepEqual(errors,[]);
});
