import assert from 'node:assert/strict';
import test from 'node:test';
import {randomBytes} from 'node:crypto';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createLifestreamServer} from '../../server/src/index.ts';
import {loadProfile} from '../../server/src/config/loader.ts';

test('Initiative comparison presents labeled counts and event reasons without activating its selected draft',{skip:!process.env.PLAYWRIGHT_MODULE,timeout:60000},async t=>{
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),root=await mkdtemp(join(tmpdir(),'initiative-lab-browser-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex'),app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'safety'),installerToken}});await app.start();t.after(()=>app.shutdown());
 const browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1360,height:960}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${app.address().port}/control/`);await page.waitForFunction(()=>!!window.lifestreamUI);
 await page.locator('#auth-username').fill('owner');await page.locator('#auth-password').fill(randomBytes(32).toString('hex'));await page.locator('#auth-installer-token').fill(installerToken);await page.locator('#auth-setup').click();await page.waitForFunction(()=>!!window.lifestreamAuth.session);
 await page.locator('#new-assistant').click();await page.waitForFunction(()=>document.querySelector('#result').textContent.includes('Assistant created'));const nav=async id=>{const link=page.locator(`[data-destination="${id}"]`);if(!await link.isVisible())await page.locator('.nav-toggle').click();await link.click();};await nav('relationship');await page.locator('#relationship-create').click();await page.waitForFunction(()=>document.querySelector('#relationship-results').textContent.includes('revision 1'));
 await nav('initiative');const panel=page.locator('.relationship-initiative'),lab=panel.getByRole('region',{name:'Initiative comparison Lab',includeHidden:true});assert.equal(await lab.getByRole('button',{name:'Run comparison',exact:true}).isDisabled(),true);
 await panel.locator('[data-action=refresh]').click();await panel.locator('[data-role=status]').filter({hasText:'Settings loaded'}).waitFor();await panel.getByRole('button',{name:'Save review draft',exact:true}).click();await panel.locator('[data-role=status]').filter({hasText:'Draft saved'}).waitFor();
 await lab.getByRole('button',{name:'Run comparison',exact:true}).click();await lab.getByRole('button',{name:'Check results',exact:true}).waitFor();
 for(let n=0;n<30;n++){await page.waitForTimeout(300);await lab.getByRole('button',{name:'Check results',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('[data-lab-status]').textContent.includes('Checking'));if((await lab.locator('[data-lab-status]').textContent()).includes('completed'))break;}
 assert.match(await lab.locator('[data-lab-status]').textContent(),/completed/);const rows=lab.locator('table').first().locator('tbody tr');assert.equal(await rows.count(),4);assert.equal(await rows.nth(0).locator('td').first().textContent(),'0');assert.equal(await rows.nth(1).locator('td').first().textContent(),'2');assert.equal(await rows.nth(2).locator('td').first().textContent(),'7');assert.equal(await rows.nth(3).locator('td').first().textContent(),'0');
 await lab.locator('summary').filter({hasText:'Highly engaged · 11 · event outcomes and reasons'}).click();assert.match(await lab.textContent(),/Unanswered Initiative topic/);assert.match(await lab.textContent(),/Private audience unavailable/);assert.match(await panel.locator('[data-role=active]').textContent(),/no activated extension/);assert.equal(await panel.locator('[data-action=activate]').isEnabled(),true);
 await page.screenshot({path:'/private/tmp/lifestream-initiative-lab-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await lab.scrollIntoViewIfNeeded();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await lab.screenshot({path:'/private/tmp/lifestream-initiative-lab-mobile.png'});
 await nav('account');await page.locator('#auth-sign-out').click();await page.waitForFunction(()=>!window.lifestreamAuth.session);assert.equal(await lab.locator('[data-lab-results]').textContent(),'');assert.equal(await lab.locator('[data-lab-run]').isDisabled(),true);assert.deepEqual(errors,[]);
});
