import assert from 'node:assert/strict';
import { test } from 'node:test';
import { randomBytes, randomUUID } from 'node:crypto';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createLifestreamServer } from '../../server/src/index.ts';
import { loadProfile } from '../../server/src/config/loader.ts';
import { FixtureCapabilityProvider } from '../../../packages/providers-fixture/src/capability/provider.ts';
const capability={id:'synthetic.echo',version:'1.0.0',inputSchema:{type:'object',properties:{text:{type:'string'}}},outputSchema:{type:'object'},sideEffect:'reversible',authorization:'required',idempotency:'idempotent',latencyClass:'fast',offlineAvailable:true,simulationSupported:true,route:'synthetic-fixture'};
const artifact={reference:'synthetic:schema',sha256:'0'.repeat(64),mediaType:'application/schema+json',schemaRef:'https://json-schema.org/draft/2020-12/schema',byteLength:2};
const skillDraft=assistantId=>({schemaVersion:'1.0.0',skillId:randomUUID(),assistantId,revision:1,version:'1.0.0',status:'draft',name:'Synthetic browser Skill',description:'Synthetic isolated administration check',inputSchema:artifact,outputSchema:artifact,requiredCapabilities:[{capabilityId:capability.id,version:capability.version}],preconditions:[],maxSteps:1,steps:[{stepId:randomUUID(),capabilityId:capability.id,capabilityVersion:capability.version,inputBindings:[],onMissingInput:'reject'}],outputBindings:[],failurePolicy:'stop',compensationGuidance:'Stop for review',provenance:{sourceRefs:['synthetic-note'],transformationId:'manual',transformationVersion:'1.0.0'},createdAt:new Date().toISOString(),createdBy:'synthetic',activationRef:null});

test('rendered local setup, session, profile review and Owner provisioning use actual authentication', {skip: !process.env.PLAYWRIGHT_MODULE}, async t => {
  const { chromium }=await import(process.env.PLAYWRIGHT_MODULE);
  const root=await mkdtemp(join(tmpdir(),'ls-rendered-auth-'));t.after(()=>rm(root,{recursive:true,force:true}));
  const config=loadProfile('test');config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};config.authority.authentication='local-password';
  const installerToken=randomBytes(32).toString('hex'),password=`synthetic-${randomBytes(24).toString('hex')}`;const app=createLifestreamServer({config,capabilityProvider:new FixtureCapabilityProvider([capability]),localAuth:{stateDirectory:join(root,'safety'),installerToken}});await app.start();t.after(()=>app.shutdown());
  const browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`http://127.0.0.1:${app.address().port}/control/`);await page.locator('#auth-setup').waitFor({state:'visible'});await page.locator('#auth-username').fill('owner');await page.locator('#auth-password').fill(password);await page.locator('#auth-installer-token').fill(installerToken);await page.locator('#auth-setup').click();await page.waitForFunction(()=>document.querySelector('#auth-status').textContent.includes('Owner enrolled'));assert.equal((await page.locator('#auth-recovery-codes').textContent()).trim().split('\n').length,10);
  await page.locator('#new-assistant').click();await page.waitForFunction(()=>document.querySelector('#result').textContent.includes('Assistant created'));await page.locator('#display-name').fill('Synthetic Browser Assistant');await page.locator('#identity').fill('A neutral synthetic administration example.');await page.locator('#preview').click();await page.waitForFunction(()=>document.querySelector('#result').textContent.includes('Nothing was activated or saved'));await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#revisions').textContent.includes('Revision 2'));await page.locator('#activate').click();await page.waitForFunction(()=>document.querySelector('#editor-status').textContent==='active');
  // Recovery values are cleared before screenshots or subsequent navigation.
  await page.locator('#auth-sign-out').click();await page.waitForFunction(()=>document.querySelector('.workspace').hidden);await page.locator('#auth-username').fill('owner');await page.locator('#auth-password').fill(password);await page.locator('#auth-sign-in').click();await page.waitForFunction(()=>document.querySelector('#auth-status').textContent.startsWith('Signed in'));await page.waitForFunction(()=>document.querySelector('#editor-title').textContent==='Synthetic Browser Assistant');
  await page.goto(`http://127.0.0.1:${app.address().port}/control/security.html`);await page.waitForFunction(()=>window.lifestreamAuth.session);await page.locator('#security-username').fill('member');await page.locator('#security-password').fill(`synthetic-${randomBytes(24).toString('hex')}`);await page.locator('#security-provision').click();await page.waitForFunction(()=>document.querySelector('#security-status').textContent.includes('no Assistant permissions'));await page.locator('#security-accounts').click();await page.waitForFunction(()=>document.querySelector('#security-account-list').textContent.includes('member'));assert.ok(!(await page.locator('#security-account-list').textContent()).includes('password'));
  const selected=await page.evaluate(async()=>{const result=await window.lifestreamAuth.request('/api/admin/v1/assistants');return result.assistants[0];});
  await page.locator('#security-assistant').fill(selected.assistantId);
  await page.locator('#security-capabilities').fill('synthetic.echo');await page.locator('#security-request').click();await page.locator('#security-grants').getByRole('button',{name:'Approve grant'}).click();await page.locator('#security-grants').getByRole('button',{name:'Revoke grant'}).click();await page.waitForFunction(()=>document.querySelector('#security-grants').textContent.includes('revoked'));assert.ok((await page.locator('#security-tools').textContent()).includes('synthetic.echo'));assert.ok((await page.locator('#security-audit').textContent()).includes('revoked'));
  await page.locator('#security-skill').fill(JSON.stringify(skillDraft(selected.assistantId)));await page.locator('#security-save-skill').click();await page.locator('#security-skills').getByRole('button',{name:'Activate reviewed Skill'}).click();await page.waitForFunction(()=>document.querySelector('#security-skills').textContent.includes('revision 2 · active'));await page.locator('#security-skills').getByRole('button',{name:'Edit as new draft'}).click();await page.locator('#security-save-skill').click();await page.waitForFunction(()=>document.querySelector('#security-skills').textContent.includes('revision 3 · draft'));await page.locator('#security-skills').getByRole('button',{name:'Activate reviewed Skill'}).click();await page.waitForFunction(()=>document.querySelector('#security-skills').textContent.includes('revision 4 · active'));await page.locator('#security-skills').getByRole('button',{name:'Show revision history'}).click();await page.waitForFunction(()=>document.querySelector('#security-skills pre')?.textContent.includes('"revision": 4'));
  const proposed=await page.evaluate(async selected=>window.lifestreamAuth.request('/api/auth/v1/proposals',{operation:{method:'POST',path:`/api/admin/v1/assistants/${selected.assistantId}/revisions`,body:{expectedRevision:2,displayName:'Reviewed synthetic proposal'},expectedRevision:2}},true),selected);
  await page.locator('#security-proposal-id').fill(proposed.proposalId);await page.locator('#security-review-proposal').click();await page.waitForFunction(()=>!document.querySelector('#security-approve-proposal').disabled);assert.ok((await page.locator('#security-proposal').textContent()).includes('Reviewed synthetic proposal'));await page.locator('#security-approve-proposal').click();await page.waitForFunction(()=>document.querySelector('#security-status').textContent.includes('submitted once'));const after=await page.evaluate(async selected=>window.lifestreamAuth.request(`/api/admin/v1/assistants/${selected.assistantId}`),selected);assert.equal(after.profiles.length,3);assert.equal(after.activeProfile.displayName,'Synthetic Browser Assistant','AI proposal creates a draft, not activation');
  await page.locator('#security-review-proposal').click();await page.waitForFunction(()=>document.querySelector('#security-approve-proposal').disabled);
  await page.setViewportSize({width:390,height:844});assert.ok(await page.locator('#security-provision').isVisible());assert.deepEqual(errors,[]);
});
