import assert from 'node:assert/strict';
import test from 'node:test';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {join} from 'node:path';
const enabled=!!process.env.PLAYWRIGHT_MODULE;
async function fixture(t){
 const p={subscriptionId:'synthetic.destination',revision:0,state:'unpaired',botId:null,claimId:null,chatId:null,userId:null},data={transportReady:false,subscriptions:[{id:p.subscriptionId,revision:1,label:'My synthetic chat',channel:'telegram',requestedConversations:true,requestedAlerts:true,pairing:p}]},requests=[];let hold;
 const server=createServer(async(req,res)=>{
  if(req.url.startsWith('/api/')){let input='';for await(const c of req)input+=c;delete data.issued;if(input){const b=JSON.parse(input);requests.push(b);p.revision++;if(b.operation==='issue'){p.state='challenge';p.botId=b.botId;data.issued={subscriptionId:p.subscriptionId,challenge:'synthetic-code-for-ui-only'};}else if(b.operation==='confirm'){assert.equal(b.claimId,p.claimId);p.state='paired';}else p.state='revoked';}const content=JSON.stringify(data),send=()=>{res.setHeader('content-type','application/json');res.end(content);};if(hold){hold(send);hold=null;}else send();return;}
  if(['/my-channels.js','/styles.css'].includes(req.url)){res.setHeader('content-type',req.url.endsWith('.js')?'text/javascript':'text/css');res.end(await readFile(new URL('..'+req.url,import.meta.url)));return;}
  res.end('<!doctype html><html lang="en"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/styles.css"><main class="shell card"></main></html>');
 });await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>{server.closeAllConnections();server.close();});const base='http://127.0.0.1:'+server.address().port;
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));t.after(()=>assert.deepEqual(errors,[]));await page.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());await page.goto(base+'/#account');await page.evaluate(async()=>{window.identity='synthetic.session';const {installMyChannels}=await import('/my-channels.js');installMyChannels({anchor:document.querySelector('main'),identity:()=>window.identity,api:async(path,options)=>(await fetch(path,options)).json()});});
 const refresh=async()=>{await page.getByRole('button',{name:'Refresh my connections'}).click();await page.waitForFunction(()=>!document.querySelector('[data-mine-refresh]').disabled);};return {page,data,p,requests,refresh,hold:fn=>hold=fn};
}
test('subscriber pairing journeys cover create, replace, refresh, claim confirmation and revoke at desktop/mobile',{skip:!enabled},async t=>{
 const f=await fixture(t),page=f.page;await f.refresh();await page.getByLabel('Telegram bot numeric ID',{exact:true}).fill('9999');await page.getByRole('button',{name:'Create pairing code'}).click();await page.getByText('/start synthetic-code-for-ui-only',{exact:true}).waitFor();assert.equal(f.requests[0].botId,'9999');await page.getByRole('button',{name:'Replace pairing code'}).click();await page.waitForFunction(()=>!document.querySelector('[data-mine-refresh]').disabled);assert.equal(f.requests.length,2);
 Object.assign(f.p,{state:'claimed',revision:3,claimId:'synthetic.claim',chatId:'1234',userId:'1234'});await f.refresh();await page.getByText('Telegram user 1234, private chat 1234.',{exact:false}).waitFor();assert.equal(await page.locator('code').count(),0);
 if(process.env.SUBSCRIBER_QA_DIRECTORY){await mkdir(process.env.SUBSCRIBER_QA_DIRECTORY,{recursive:true});await page.screenshot({path:join(process.env.SUBSCRIBER_QA_DIRECTORY,'pairing-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:join(process.env.SUBSCRIBER_QA_DIRECTORY,'pairing-mobile.png'),fullPage:true});}
 await page.getByRole('button',{name:'Confirm my Telegram chat'}).click();await page.getByText('Paired. Delivery remains disabled',{exact:false}).waitFor();await page.getByRole('button',{name:'Revoke pairing'}).click();await page.getByText('telegram · revoked',{exact:true}).waitFor();assert.deepEqual(f.requests.map(r=>r.operation),['issue','issue','confirm','revoke']);
});
test('pending pairing codes and late responses clear on account change; untrusted labels are literal text',{skip:!enabled},async t=>{
 const f=await fixture(t);f.data.subscriptions[0].label='<script>unsafe()</script>';await f.refresh();assert.equal(await f.page.locator('script').count(),0);let release;f.hold(fn=>release=fn);await f.page.getByRole('button',{name:'Refresh my connections'}).click();for(let i=0;i<100&&!release;i++)await new Promise(r=>setTimeout(r,10));assert.ok(release);await f.page.evaluate(()=>{window.identity=null;dispatchEvent(new Event('lifestream-auth'));});release();await f.page.waitForTimeout(30);assert.equal(await f.page.locator('[data-mine-list]').innerText(),'');
});
