import assert from 'node:assert/strict';
import { test } from 'node:test';
import { randomBytes, randomUUID } from 'node:crypto';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createLifestreamServer } from '../../server/src/index.ts';
import { loadProfile } from '../../server/src/config/loader.ts';

test('authenticated personalization applies reviewed correction, reverses adaptation, scopes import and recalls after restart', { skip: !process.env.PLAYWRIGHT_MODULE, timeout: 90000 }, async t => {
  const { chromium } = await import(process.env.PLAYWRIGHT_MODULE);
  const root = await mkdtemp(join(tmpdir(), 'ls-personalization-')); t.after(() => rm(root, { recursive: true, force: true }));
  const config = loadProfile('test'); config.storage = { databasePath: join(root, 'state.sqlite'), artifactDirectory: join(root, 'artifacts') }; config.authority.authentication = 'local-password';
  const installerToken = randomBytes(32).toString('hex'), password = `synthetic-${randomBytes(24).toString('hex')}`;
  const options = { config, localAuth: { stateDirectory: join(root, 'safety'), installerToken } };
  let app = createLifestreamServer(options); await app.start(); t.after(() => app.shutdown());
  const browser = await chromium.launch({ channel: 'chrome', headless: true }); t.after(() => browser.close());
  const page = await browser.newPage(), errors = []; page.setDefaultTimeout(5000); page.on('pageerror', error => errors.push(error.message));
  const api = (path, body) => page.evaluate(async ({ path, body }) => {
    const response = await fetch(path, { method: body === undefined ? 'GET' : 'POST', headers: { 'content-type': 'application/json', 'x-lifestream-csrf': window.lifestreamAuth.session?.csrfToken || '' }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
    return { status: response.status, body: await response.json() };
  }, { path, body });
  await page.goto(`http://127.0.0.1:${app.address().port}/control/`);
  await page.locator('#auth-setup').waitFor({ state: 'visible' }); await page.locator('#auth-username').fill('owner'); await page.locator('#auth-password').fill(password); await page.locator('#auth-installer-token').fill(installerToken); await page.locator('#auth-setup').click();
  await page.waitForFunction(() => window.lifestreamAuth.session);
  await page.locator('#new-assistant').click(); await page.waitForFunction(() => document.querySelector('#result').textContent.includes('Assistant created'));
  t.diagnostic('Owner enrolled and first Assistant created');
  const selected = (await api('/api/admin/v1/assistants')).body.assistants[0]; const base = `/api/admin/v1/assistants/${selected.assistantId}`;
  const second = await api('/api/admin/v1/assistants', { displayName: 'Other synthetic Assistant' }); assert.equal(second.status, 201);
  const policy = { dimensions: [{ key: 'warmth', valueType: 'number', minimum: 0, maximum: 1, maxDeltaPerDreamingRun: 0.1, sensitive: false, activation: 'humanApproval' }] };
  const revision = await api(`${base}/revisions`, { expectedRevision: 1, displayName: 'Synthetic Personalization', adaptivePersonaPolicy: policy }); assert.equal(revision.status, 201);
  assert.equal((await api(`${base}/activate`, { profileId: revision.body.profile.profileId, expectedActiveRevision: null })).status, 200);
  await page.reload(); await page.locator('#assistant-list').getByRole('button', { name: 'Synthetic Personalization', exact: true }).click(); await page.waitForFunction(() => document.querySelector('#editor-title').textContent === 'Synthetic Personalization');
  t.diagnostic('Active profile selected');
  // All changes below go through rendered review controls using the real local session.
  page.once('dialog', dialog => dialog.accept('Synthetic preferred color is blue')); await page.locator('#memory-add').click();
  await page.locator('#memory-results').getByRole('button', { name: 'Approve', exact: true }).click(); await page.waitForFunction(() => document.querySelector('#memory-results').textContent.includes('active'));
  page.once('dialog', dialog => dialog.accept('Synthetic preferred color is green')); await page.locator('#memory-results').getByRole('button', { name: 'Suggest correction' }).click();
  await page.waitForFunction(() => document.querySelector('#result').textContent.includes('Correction proposed for review'));
  const historyResponse = page.waitForResponse(response => response.url().endsWith('/history')); await page.locator('#memory-results').getByRole('button', { name: 'Review history' }).click(); const historyRead = await historyResponse; assert.equal(historyRead.status(), 200); assert.equal((await historyRead.json()).history.at(-1).eventType, 'correctionProposed'); try { await page.getByRole('button', { name: 'Apply reviewed correction' }).click(); } catch(error) { t.diagnostic(await page.locator('#memory-results').innerHTML()); t.diagnostic(await page.locator('#result').textContent()); t.diagnostic(JSON.stringify(errors)); throw error; }
  await page.waitForFunction(() => document.querySelector('#memory-results').textContent.includes('Synthetic preferred color is green'));
  t.diagnostic('Reviewed correction applied');
  const memories = (await api(`${base}/memories`)).body.memories;
  const corrected = memories.find(item => item.content.endsWith('green')), original = memories.find(item => item.content.endsWith('blue'));
  assert.equal(corrected.lifecycle.status, 'active'); assert.equal(corrected.provenance.correctionOf, original.id); assert.equal(original.lifecycle.status, 'superseded');
  assert.equal((await api(`${base}/memories/${original.id}/correction`, { applyRevision: 3, expectedRevision: 2 })).status, 409);
  const otherBase = `/api/admin/v1/assistants/${second.body.assistantId}`;
  assert.equal((await api(`${otherBase}/memories/${original.id}/history`)).status, 404);
  await page.locator('#memory-search').fill('green'); await page.locator('#memory-search-button').click(); await page.waitForFunction(() => document.querySelector('#memory-results').textContent.includes('green'));
  const answers = ['warmth', '0.5', '0.55', 'synthetic-reviewed-note']; const answerDialog = dialog => dialog.accept(answers.shift()); page.on('dialog', answerDialog);
  await page.locator('#adaptation-add').click(); await page.locator('#adaptation-results').getByRole('button', { name: 'Approve', exact: true }).click(); page.off('dialog', answerDialog);
  await page.locator('#adaptation-results').getByRole('button', { name: 'Reverse adaptation' }).click(); await page.waitForFunction(() => document.querySelector('#adaptation-results').textContent.includes('reversed'));
  t.diagnostic('Adaptation reversed');
  const stale = await api(`${base}/adaptations`, { dimensionKey: 'warmth', priorValue: 0.5, proposedValue: 0.55, evidence: ['synthetic-new-note'] }); assert.equal(stale.status, 201);
  assert.equal((await api(`${otherBase}/adaptations`, { dimensionKey: 'warmth', priorValue: 0.5, proposedValue: 0.55, evidence: ['synthetic-note'] })).status, 422, 'undeclared policy is not editable');
  const changed = await api(`${base}/revisions`, { expectedRevision: 2, displayName: 'Synthetic Personalization', adaptivePersonaPolicy: { dimensions: [] } });
  await api(`${base}/activate`, { profileId: changed.body.profile.profileId, expectedActiveRevision: 2 });
  assert.equal((await api(`${base}/adaptations/${stale.body.adaptation.id}/decision`, { status: 'active', expectedStatus: 'proposed' })).status, 409);
  const exported = (await api(`${base}/memories/export`)).body; assert.equal(exported.dataScope, 'assistant-memories');
  assert.equal((await api(`${otherBase}/memories/import`, exported)).status, 422);
  const newRecord = { ...corrected, id: randomUUID(), content: 'Synthetic imported reminder', lifecycle: { status: 'active', revision: 7, changedBy: 'imported-assertion' } };
  assert.equal((await api(`${base}/memories/import`, { ...exported, memories: [newRecord] })).status, 422, 'revoked correction lineage cannot be reimported');
  newRecord.provenance = { source: 'synthetic-independent-import' };
  assert.equal((await api(`${base}/memories/import`, { ...exported, memories: [newRecord] })).status, 201);
  const importedRecord=(await api(`${base}/memories`)).body.memories.find(item=>item.id===newRecord.id); assert.equal(importedRecord.lifecycle.status,'candidate'); assert.equal(importedRecord.lifecycle.revision,1); assert.equal(importedRecord.provenance.importedLifecycle.status,'active'); assert.equal(importedRecord.provenance.source,'authenticated-file-import');
  assert.equal((await api(`${base}/memories/import`, { ...exported, memories: [{ ...newRecord, id: randomUUID(), provenance: { grant: 'attempted-import-authority' } }] })).status, 422);
  const before = (await api(base)).body;
  const preview = await api(`${base}/import`, { schemaVersion: '1.0.0', dataScope: 'assistant-profiles', assistantId: selected.assistantId, profile: { displayName: 'Inert import' }, expectedRevision: 3 }); assert.equal(preview.status, 200); assert.equal(preview.body.previewOnly, true);
  assert.deepEqual((await api(base)).body, before);
  await page.locator('#memory-refresh').click();
  await page.locator('#memory-results .revision').filter({ hasText: 'Synthetic imported reminder' }).getByRole('button', { name: 'Mark conflicted' }).click();
  await page.waitForFunction(() => document.querySelector('#result').textContent === 'Memory marked conflicted.');
  await api(`${base}/memories`, { content: 'Synthetic suppression example' }); await page.locator('#memory-refresh').click();
  await page.locator('#memory-results .revision').filter({ hasText: 'Synthetic suppression example' }).getByRole('button', { name: 'Suppress', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#result').textContent === 'Memory suppressed; history retained.');
  await page.locator('#assistant-list').getByRole('button', { name: 'Other synthetic Assistant', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#memory-results').textContent.includes('No memories yet'));
  assert.ok(!(await page.locator('#memory-results').textContent()).includes('green'));
  await app.shutdown(); app = createLifestreamServer(options); await app.start();
  await page.goto(`http://127.0.0.1:${app.address().port}/control/`); await page.locator('#auth-sign-in').waitFor({ state: 'visible' }); await page.locator('#auth-username').fill('owner'); await page.locator('#auth-password').fill(password); await page.locator('#auth-sign-in').click(); await page.waitForFunction(() => window.lifestreamAuth.session);
  const recalled = (await api(`${base}/memories/search`, { query: 'green' })).body.memories; assert.equal(recalled[0].id, corrected.id);
  assert.equal((await api(`${otherBase}/memories/search`, { query: 'green' })).body.memories.length, 0);
  assert.equal((await api(`${base}/adaptations`)).body.adaptations.find(item => item.status === 'reversed').dimensionKey, 'warmth');
  assert.deepEqual(errors, []);
});
