import assert from 'node:assert/strict';
import test from 'node:test';
import {readFile,mkdtemp,rm} from 'node:fs/promises';
import {createServer} from 'node:http';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {presentationVendor} from '../../server/src/runtime/presentation-vendor.ts';

test('rendered reduced motion pauses automatic body animation while preserving explicit previews and playback mouth',{skip:!process.env.PLAYWRIGHT_MODULE},async t=>{
 const html='<link rel="stylesheet" href="./styles.css"><script type="importmap">{"imports":{"three":"./three.module.js"}}</script><main class="shell"><section class="conversation-room"><div class="room-layout"></div></section></main>';
 const server=createServer((request,response)=>void(async()=>{const name=new URL(request.url,'http://localhost').pathname.slice('/control/'.length);if(!name){response.setHeader('content-type','text/html');return response.end(html);}if(!/^[a-zA-Z0-9_.-]+$/.test(name)){response.writeHead(404);return response.end();}response.setHeader('content-type',name.endsWith('.css')?'text/css':'text/javascript');response.end(await presentationVendor(name)??await readFile(new URL('../'+name,import.meta.url)));})().catch(()=>{response.writeHead(404);response.end();}));await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>{server.closeAllConnections();server.close(r);}));
 const url=`http://127.0.0.1:${server.address().port}/control/#conversation`,{chromium,_electron}=await import(process.env.PLAYWRIGHT_MODULE);let page;
 if(process.env.LIFESTREAM_NATIVE_EXECUTABLE){const directory=await mkdtemp(join(tmpdir(),'ls-motion-native-'));t.after(()=>rm(directory,{recursive:true,force:true}));const app=await _electron.launch({executablePath:process.env.LIFESTREAM_NATIVE_EXECUTABLE,args:['--url',url,'--user-data-dir='+directory]});t.after(()=>app.close());page=await app.firstWindow();assert.equal(await page.evaluate(()=>typeof require),'undefined');}
 else{const browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());page=await browser.newPage({viewport:{width:1280,height:1000}});}
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.emulateMedia({reducedMotion:'no-preference'});await page.goto(url);
 await page.evaluate(async()=>{
  window.lifestreamAuth={session:{principalId:'synthetic'}};window.motionSample={playing:false,amplitude:0};window.motionWrites=0;window.motionFrames=0;
  const {PresentationRuntime}=await import('/control/presentation-runtime.js'),commit=PresentationRuntime.prototype.commit;PresentationRuntime.prototype.commit=function(...args){window.motionRuntime=this;return commit.apply(this,args);};
  const {installPresentation}=await import('/control/presentation.js');window.presentation=installPresentation({anchor:document.querySelector('main'),busy:()=>false,playback:()=>window.motionSample,identity:()=>({assistantId:'synthetic'}),api:async(_path,options)=>{if(options)window.motionWrites++;return {endpointId:'synthetic-endpoint',packages:[],neutral:{id:'neutral',label:'Neutral reference',digest:'neutral-v1'},selection:{}};}});window.presentation.refresh();
 });await page.waitForFunction(()=>window.motionRuntime&&!document.querySelector('[data-apply]').disabled);
 await page.evaluate(async()=>{const T=await import('three'),r=window.motionRuntime,v=r.current;v.manifest.animations={idle:'sway',listening:'listen'};v.manifest.transitionSeconds=.15;v.mixer=new T.AnimationMixer(v.root);v.actions=new Map(['sway','listen'].map((name,i)=>[name,v.mixer.clipAction(new T.AnimationClip(name,2,[new T.NumberKeyframeTrack('.rotation[z]',[0,1,2],[0,.2+i*.1,0])]))]));const onState=r.onState;r.onState=(...args)=>{window.motionFrames++;onState(...args);};});
 await page.waitForFunction(()=>window.motionRuntime.current.mixer.time>.15);
 const frames=async n=>{const before=await page.evaluate(()=>window.motionFrames);await page.waitForFunction(target=>window.motionFrames>=target,before+n);};
 await page.evaluate(()=>{window.motionRuntime.animationEnabled=()=>false;});await frames(3);assert.equal(await page.evaluate(()=>!!window.motionRuntime.current.action),false,'disabled bundled clips must not remain active');await page.evaluate(()=>{window.motionRuntime.animationEnabled=()=>true;});await frames(3);assert.ok(await page.evaluate(()=>!!window.motionRuntime.current.action));
 await page.emulateMedia({reducedMotion:'reduce'});await frames(3);
 const frozen=await page.evaluate(()=>({time:window.motionRuntime.current.mixer.time,angle:window.motionRuntime.current.root.rotation.z}));await frames(12);
 assert.deepEqual(await page.evaluate(()=>({time:window.motionRuntime.current.mixer.time,angle:window.motionRuntime.current.root.rotation.z})),frozen,'ambient body must stop at the current pose');
 assert.match(await page.locator('[data-motion-status]').textContent(),/Reduced motion on.*paused/);
 await page.evaluate(()=>window.presentation.state('listening'));await frames(4);assert.equal(await page.locator('.presentation-state').textContent(),'listening');assert.equal(await page.evaluate(()=>window.motionRuntime.current.mixer.time),frozen.time);
 await page.evaluate(()=>window.motionSample={playing:true,amplitude:.12,trace:'synthetic-playback'});await frames(4);assert.equal(await page.evaluate(()=>window.motionRuntime.current.mixer.time),frozen.time);assert.ok(await page.evaluate(()=>window.motionRuntime.current.mouth.scale.y>1));
 await page.evaluate(()=>window.motionSample={playing:false,amplitude:0});await frames(3);assert.equal(await page.evaluate(()=>window.motionRuntime.current.mouth.scale.y),1);
 await page.getByText('Preview animations',{exact:true}).click();await page.getByLabel('Animation preview state').selectOption('listening');await page.getByRole('button',{name:'Preview animation',exact:true}).click();await frames(5);assert.ok(await page.evaluate(time=>window.motionRuntime.current.mixer.time>time,frozen.time));assert.match(await page.locator('[data-motion-status]').textContent(),/explicit five-second preview/);
 await page.getByRole('button',{name:'End preview',exact:true}).click();await frames(2);const stopped=await page.evaluate(()=>window.motionRuntime.current.mixer.time);await frames(5);assert.equal(await page.evaluate(()=>window.motionRuntime.current.mixer.time),stopped);
 await page.getByRole('button',{name:'Preview animation',exact:true}).click();await page.evaluate(()=>window.motionRuntime.previewState.until=0);await frames(2);assert.equal(await page.evaluate(()=>window.motionRuntime.previewState),null);
 await page.emulateMedia({reducedMotion:'no-preference'});await frames(5);assert.ok(await page.evaluate(time=>window.motionRuntime.current.mixer.time>time,stopped));assert.match(await page.locator('[data-motion-status]').textContent(),/Standard motion/);
 await page.getByRole('button',{name:'Preview animation',exact:true}).click();await page.emulateMedia({reducedMotion:'reduce'});await frames(3);assert.equal(await page.evaluate(()=>window.motionRuntime.previewState),null,'new reduced-motion preference cancels a prior preview');
 await page.evaluate(async()=>{const T=await import('three'),r=window.motionRuntime,v=r.neutral();v.manifest.animations={idle:'rest'};v.mixer=new T.AnimationMixer(v.root);v.actions=new Map([['rest',v.mixer.clipAction(new T.AnimationClip('rest',2,[new T.NumberKeyframeTrack('.rotation[z]',[0,2],[.12,.4])]))]]);r.commit(v);});await frames(3);assert.ok(await page.evaluate(()=>Math.abs(window.motionRuntime.current.root.rotation.z-.12)<.00001),'an appearance loaded in reduced motion must use its initial idle pose');const initialPose=await page.evaluate(()=>window.motionRuntime.current.mixer.time);await frames(4);assert.equal(await page.evaluate(()=>window.motionRuntime.current.mixer.time),initialPose);
 if(process.env.LIFESTREAM_MOTION_SCREENSHOT){await page.screenshot({path:process.env.LIFESTREAM_MOTION_SCREENSHOT+'-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:process.env.LIFESTREAM_MOTION_SCREENSHOT+'-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);}
 assert.equal(await page.evaluate(()=>window.motionWrites),0);assert.deepEqual(errors,[]);await page.evaluate(()=>dispatchEvent(new CustomEvent('lifestream-audience',{detail:{privateAllowed:false}})));assert.equal(await page.evaluate(()=>window.motionRuntime.disposed),true);
});
