import assert from 'node:assert/strict';
import test from 'node:test';
import {readFile} from 'node:fs/promises';
import {createServer} from 'node:http';
import {presentationVendor} from '../../server/src/runtime/presentation-vendor.ts';

test('rendered opt-in library preserves root motion, follows its anchor, pauses and honors enabled clips',{skip:!process.env.PLAYWRIGHT_MODULE},async t=>{
 const server=createServer((request,response)=>void(async()=>{const name=new URL(request.url,'http://localhost').pathname.slice(1);if(!name){response.setHeader('content-type','text/html');return response.end('<style>canvas{width:400px;height:400px}</style><script type="importmap">{"imports":{"three":"/three.module.js"}}</script><canvas></canvas>');}if(name==='favicon.ico'){response.writeHead(204);return response.end();}if(!/^[a-zA-Z0-9_.-]+$/.test(name)){response.writeHead(404);return response.end();}response.setHeader('content-type','text/javascript');response.end(await presentationVendor(name)??await readFile(new URL('../'+name,import.meta.url)));})().catch(()=>{response.writeHead(404);response.end();}));await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>{server.closeAllConnections();server.close(r);}));
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));await page.emulateMedia({reducedMotion:'no-preference'});await page.goto('http://127.0.0.1:'+server.address().port);
 await page.evaluate(async()=>{
  const {PresentationRuntime}=await import('/presentation-runtime.js');
  const binary=new Float32Array([-.5,0,0,.5,0,0,0,1,0,0,20,0,0,0,6,0,0]);
  const gltf={asset:{version:'2.0'},scene:0,scenes:[{nodes:[0]}],nodes:[{name:'Anchor',children:[1]},{mesh:0}],meshes:[{primitives:[{attributes:{POSITION:0}}]}],buffers:[{uri:'mesh.bin',byteLength:binary.byteLength}],bufferViews:[{buffer:0,byteOffset:0,byteLength:36},{buffer:0,byteOffset:36,byteLength:8},{buffer:0,byteOffset:44,byteLength:24}],accessors:[{bufferView:0,componentType:5126,count:3,type:'VEC3',min:[-.5,0,0],max:[.5,1,0]},{bufferView:1,componentType:5126,count:2,type:'SCALAR',min:[0],max:[20]},{bufferView:2,componentType:5126,count:2,type:'VEC3'}],animations:[{name:'travel',samplers:[{input:1,output:2}],channels:[{sampler:0,target:{node:0,path:'translation'}}]}]};
  const files=new Map([['model.gltf',new TextEncoder().encode(JSON.stringify(gltf))],['mesh.bin',binary]]),manifest={model:'model.gltf',animations:{idle:'travel'},animationLibrary:[{clip:'travel',label:'Travel'}],framing:{distance:1.35,targetHeight:.5,motionAnchor:'Anchor'},capabilities:{lipSync:'none'},resources:await Promise.all([...files].map(async([path,bytes])=>({path,bytes:bytes.byteLength,mime:'application/octet-stream',sha256:[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(v=>v.toString(16).padStart(2,'0')).join('')})))};
  window.enabled=true;window.frames=0;window.runtime=new PresentationRuntime(document.querySelector('canvas'),{randomAnimations:true,animationEnabled:()=>window.enabled,onState(){window.frames++;},retrieveResource:async route=>{const bytes=files.get(route.split('/').pop());return bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength);}});
  const value=await runtime.prepare({id:'fixture',manifest});runtime.commit(value);window.anchorOffset=runtime.camera.position.x-value.motionAnchor.position.x;
 });
 const frames=async n=>{const before=await page.evaluate(()=>window.frames);await page.waitForFunction(target=>window.frames>=target,before+n);};await frames(10);
 const moving=await page.evaluate(()=>({clip:runtime.current.playlist.current,anchor:runtime.current.motionAnchor.position.x,camera:runtime.camera.position.x,offset:anchorOffset}));assert.equal(moving.clip,'travel');assert.ok(moving.anchor>0);assert.ok(Math.abs(moving.camera-moving.anchor-moving.offset)<1e-6);
 await page.emulateMedia({reducedMotion:'reduce'});await frames(3);const frozen=await page.evaluate(()=>[runtime.current.mixer.time,runtime.current.playlist.remaining,runtime.camera.position.x]);await frames(6);assert.deepEqual(await page.evaluate(()=>[runtime.current.mixer.time,runtime.current.playlist.remaining,runtime.camera.position.x]),frozen);
 await page.evaluate(()=>{window.enabled=false;});await frames(3);assert.equal(await page.evaluate(()=>runtime.current.playlist.current),null);assert.equal(await page.evaluate(()=>runtime.current.motionAnchor.position.x),0);
 await page.emulateMedia({reducedMotion:'no-preference'});await page.evaluate(()=>{window.enabled=true;});await frames(6);assert.ok(await page.evaluate(()=>runtime.current.motionAnchor.position.x)>0);
 assert.ok(await page.evaluate(()=>{runtime.frame(runtime.current);const before=runtime.camera.position.clone();runtime.followMotionAnchor(runtime.current);return before.distanceTo(runtime.camera.position)<1e-12;}),'reframing must reset the tracked anchor without a jump');
 assert.equal(await page.evaluate(()=>runtime.preview('idle').clip),'travel');assert.equal(await page.evaluate(()=>!!runtime.current.playlist),false);await page.evaluate(()=>runtime.endPreview());await frames(3);assert.equal(await page.evaluate(()=>runtime.current.playlist.current),'travel');
 await page.evaluate(()=>runtime.dispose());assert.equal(await page.evaluate(()=>runtime.current.mixer.stats.actions.inUse),0);assert.deepEqual(errors,[]);
});
