import assert from 'node:assert/strict';
import test from 'node:test';
import * as THREE from 'three';
import {readFile} from 'node:fs/promises';
import {presentationVendor} from '../../server/src/runtime/presentation-vendor.ts';
import {SpeechMotion} from '../presentation-speech.js';
function fixture(transitionSeconds=.04){const root=new THREE.Group(),mouth=new THREE.Bone(),body=new THREE.Bone(),eye=new THREE.Bone();mouth.name='Mouth';body.name='Body';eye.name='Eye';root.add(mouth,body,eye);const clips=[new THREE.AnimationClip('open',1,[new THREE.VectorKeyframeTrack('Mouth.position',[0,1],[0,0,0,0,-1,0])]),new THREE.AnimationClip('rest',1,[new THREE.VectorKeyframeTrack('Mouth.position',[0,1],[0,0,0,0,0,0])])],configuration={cueSet:'neutral-two-poses',poses:{A:'open',X:'rest'},transitionSeconds};return {root,mouth,body,eye,clips,configuration,motion:new SpeechMotion(root,clips,configuration)};}
const sample=(offset,cue='A',extra={})=>({playing:true,clock:'AudioContext.currentTime',trace:'active',segmentId:'audio',sampleOffset:offset,cueSet:'neutral-two-poses',viseme:cue,...extra});
test('mouth transitions follow only the actual audio sample clock and restore the current body pose',()=>{const f=fixture();for(const offset of [0,480,960,1440,1920]){f.motion.beginFrame();f.body.position.x=3;f.eye.rotation.y=.2;assert.equal(f.motion.apply(sample(offset)),true);assert.ok(Math.abs(f.mouth.position.y+offset/1920)<1e-6);assert.equal(f.body.position.x,3);assert.equal(f.eye.rotation.y,.2);}f.motion.beginFrame();f.motion.apply(sample(2400,'X'));assert.equal(f.mouth.position.y,-1);f.motion.beginFrame();f.motion.apply(sample(4320,'X'));assert.equal(f.mouth.position.y,0);f.motion.reset();assert.equal(f.mouth.position.y,0);});
test('paused samples do not advance transitions with elapsed wall time or repeated render frames',()=>{const f=fixture();f.motion.apply(sample(0));for(let i=0;i<100;i++){f.motion.beginFrame();f.motion.apply(sample(960));assert.equal(f.mouth.position.y,-.5);}f.motion.reset();assert.equal(f.mouth.position.y,0);});
test('silence, mismatched cue sets, unknown cues and invalid clocks preserve amplitude fallback',()=>{const f=fixture(0);for(const value of [null,sample(0,'A',{playing:false}),sample(0,'A',{clock:'request-start'}),sample(0,'A',{cueSet:'other'}),sample(0,'bad'),sample(-1),sample(1.5),sample(0,'A',{trace:null})]){f.motion.beginFrame();f.mouth.position.y=-.3;assert.equal(f.motion.apply(value),false);assert.equal(f.mouth.position.y,-.3);}assert.equal(f.motion.accepts({cueSet:'neutral-two-poses',cues:[{cue:'A'},{cue:'X'}]}),true);assert.equal(f.motion.accepts({cueSet:'other',cues:[{cue:'A'}]}),false);assert.equal(f.motion.accepts({cueSet:'neutral-two-poses',cues:[{cue:'Z'}]}),false);});
test('new audio identity and rewound sample offsets discard prior transitions',()=>{const f=fixture();f.motion.apply(sample(0));f.motion.beginFrame();f.motion.apply(sample(1920));assert.equal(f.mouth.position.y,-1);f.motion.beginFrame();f.motion.apply(sample(0,'A',{trace:'new'}));assert.equal(f.mouth.position.y,0);f.motion.beginFrame();f.motion.apply(sample(1920,'A',{trace:'new'}));assert.equal(f.mouth.position.y,-1);f.motion.beginFrame();f.motion.apply(sample(480,'A',{trace:'new'}));assert.equal(f.mouth.position.y,0);});
test('repeated application requires frame restoration and reset clears owned transforms',()=>{const f=fixture(0);f.motion.apply(sample(0));assert.equal(f.mouth.position.y,-1);assert.throws(()=>f.motion.apply(sample(1)),/beginFrame/);f.motion.reset();assert.equal(f.mouth.position.y,0);assert.equal(f.motion.scope,null);});
test('missing clips, ambiguous targets and unsupported transform tracks fail closed',()=>{const f=fixture();assert.throws(()=>new SpeechMotion(f.root,[],f.configuration),/missing/);assert.throws(()=>new SpeechMotion(f.root,[...f.clips,f.clips[0]],f.configuration),/ambiguous/);const duplicate=f.mouth.clone();f.root.add(duplicate);assert.throws(()=>new SpeechMotion(f.root,f.clips,f.configuration),/ambiguous/);f.root.remove(duplicate);const bad=new THREE.AnimationClip('open',1,[new THREE.NumberKeyframeTrack('Mouth.visible',[0,1],[1,0])]);assert.throws(()=>new SpeechMotion(f.root,[bad,f.clips[1]],f.configuration),/track/);assert.throws(()=>new SpeechMotion(f.root,f.clips,{...f.configuration,transitionSeconds:1}),/mapping/);});

test('nonfinite, reversed and oversized pose timelines fail before rendering',()=>{for(const times of [[0,NaN],[0,Infinity],[1,0],[0,0],[-1,1],Array.from({length:2049},(_,i)=>i/2048)]){const f=fixture();f.clips[0].tracks[0].times=new Float32Array(times);assert.throws(()=>new SpeechMotion(f.root,f.clips,f.configuration),/track/);}});


test('real renderer consumes cached paired cues on the audio clock and yields mouth control to the answer',{skip:!process.env.PLAYWRIGHT_MODULE},async t=>{
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true,args:['--autoplay-policy=no-user-gesture-required']});t.after(()=>browser.close());const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('http://127.0.0.1:9/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);if(!name)return route.fulfill({contentType:'text/html',body:'<script type="importmap">{"imports":{"three":"/three.module.js"}}</script><canvas style="width:400px;height:400px"></canvas>'});if(!/^[a-zA-Z0-9_.-]+$/.test(name))return route.abort();const body=await presentationVendor(name)??await readFile(new URL('../'+name,import.meta.url));return route.fulfill({contentType:'text/javascript',body});});await page.goto('http://127.0.0.1:9/');
 const result=await page.evaluate(async()=>{
  const {PresentationRuntime}=await import('/presentation-runtime.js'),{AcknowledgmentCache}=await import('/acknowledgments.js'),{ConversationOutput}=await import('/conversation-output.js');
  const hash=async bytes=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');
  const binary=new Float32Array([-.2,0,0,.2,0,0,0,.1,0,0,1,1,1,1,1,6,1,1,1,1,1,1,1]);
  const model={asset:{version:'2.0'},scene:0,scenes:[{nodes:[0]}],nodes:[{name:'Mouth',mesh:0}],meshes:[{primitives:[{attributes:{POSITION:0}}]}],buffers:[{uri:'poses.bin',byteLength:binary.byteLength}],bufferViews:[{buffer:0,byteOffset:0,byteLength:36},{buffer:0,byteOffset:36,byteLength:8},{buffer:0,byteOffset:44,byteLength:24},{buffer:0,byteOffset:68,byteLength:24}],accessors:[{bufferView:0,componentType:5126,count:3,type:'VEC3',min:[-.2,0,0],max:[.2,.1,0]},{bufferView:1,componentType:5126,count:2,type:'SCALAR',min:[0],max:[1]},{bufferView:2,componentType:5126,count:2,type:'VEC3'},{bufferView:3,componentType:5126,count:2,type:'VEC3'}],animations:['open','rest'].map((name,i)=>({name,channels:[{sampler:0,target:{node:0,path:'scale'}}],samplers:[{input:1,output:2+i,interpolation:'LINEAR'}]}))};
  const files=new Map([['model.gltf',new TextEncoder().encode(JSON.stringify(model))],['poses.bin',new Uint8Array(binary.buffer)]]),nativeFetch=fetch;window.fetch=(url,options)=>String(url).startsWith('/api/runtime/v1/presentation/resources/')?Promise.resolve(new Response(files.get(String(url).split('/').pop()))):nativeFetch(url,options);
  const manifest={schemaVersion:'1.3.0',version:'synthetic',model:'model.gltf',framing:{distance:1.2,targetHeight:.5},animations:{mouthAmplitude:'open'},capabilities:{lipSync:'amplitude',facialAnimation:false},speech:{cueSet:'neutral-two-poses',poses:{A:'open',X:'rest'},transitionSeconds:0},resources:await Promise.all([...files].map(async([path,bytes])=>({path,bytes:bytes.byteLength,sha256:await hash(bytes),mime:'application/octet-stream'})))};
  const audio=new AudioContext();await audio.resume();const output=new ConversationOutput({onState(){},onStopped(){},onComplete(){}});output.audio=audio;output.socket={readyState:WebSocket.OPEN,send(){},close(){}};
  // Observe the exact audio-clock snapshot used for this pose. Sampling again at
  // render time can cross audio onset or a cue boundary after the pose was applied.
  let renderedSample;
  const runtime=new PresentationRuntime(document.querySelector('canvas'),{playback:()=>renderedSample=output.playbackSample()});runtime.commit(await runtime.prepare({id:'synthetic',label:'Synthetic cue geometry',manifest}));const mouth=runtime.current.root.getObjectByName('Mouth');
  const pcm=new Uint8Array(115200),view=new DataView(pcm.buffer);for(let i=0;i<pcm.length/2;i++)view.setInt16(i*2,1200,true);const sha=await hash(pcm),track={schemaVersion:'1.0.0',cueSet:'neutral-two-poses',analysisRevision:'synthetic-1',timeUnit:'ms',timeOrigin:'audio-start',audioSha256:sha,durationMs:1200,cues:[{startMs:0,endMs:600,cue:'A'},{startMs:600,endMs:1200,cue:'X'}]},trackBytes=new TextEncoder().encode(JSON.stringify(track));
  const clip={id:'synthetic',audio:{format:'pcm_s16le',sampleRateHz:48000,channels:1,bytes:pcm.length,durationMs:1200,sha256:sha},synchronized:true,visemes:{sha256:await hash(trackBytes),bytes:trackBytes.length,cueSet:track.cueSet,analysisRevision:track.analysisRevision}},catalog={schemaVersion:'1.0.0',revision:1,binding:'synthetic',enabled:true,clips:[clip]},token={revision:1,binding:'synthetic',clipIds:['synthetic']};let downloads=0;
  const cache=new AcknowledgmentCache({audio:()=>audio,current:()=>true,manifest:async()=>catalog,artifact:async kind=>{downloads++;return (kind==='audio'?pcm:trackBytes).buffer.slice(0);},mode:()=>({requiresSync:true,accepts:t=>runtime.current.speechMotion?.accepts(t)===true})});output.acknowledgments=cache;await cache.refresh();const before=downloads,frames=[],render=runtime.renderer.render.bind(runtime.renderer);runtime.renderer.render=(...args)=>{const sample=renderedSample;frames.push({sample,scale:mouth.scale.y});render(...args);};
  const wait=async condition=>{const until=performance.now()+4000;while(!condition()){if(performance.now()>until)throw Error('Renderer playback phase timed out');await new Promise(r=>setTimeout(r,10));}};
  output.beginReply('first');const played=cache.play('first',token,{bufferOffset:.2});const beforeStart=cache.sample();await wait(()=>frames.some(f=>f.sample.viseme==='A'));await wait(()=>frames.some(f=>f.sample.viseme==='X'));const openFrames=frames.filter(f=>f.sample.viseme==='A'),restFrames=frames.filter(f=>f.sample.viseme==='X');output.stop();await wait(()=>frames.at(-1).sample.playing===false&&mouth.scale.y===1);
  output.beginReply('second');cache.play('second',token);await wait(()=>frames.at(-1).sample.trace==='second'&&frames.at(-1).sample.viseme==='A');const lateEnded=cache.playing.source.onended;
  const answer=new Uint8Array(9600),answerView=new DataView(answer.buffer);for(let i=0;i<answer.length/2;i++)answerView.setInt16(i*2,2048,true);output.receive({type:'audio',interactionTraceId:'second',chunk:{segmentId:'answer',frame:{format:{encoding:'pcm_s16le',sampleRateHz:48000,channels:1},sequence:0,sampleOffset:0,sampleCount:4800,dataBase64:btoa(String.fromCharCode(...answer))}}});lateEnded();await wait(()=>frames.some(f=>f.sample.trace==='second'&&f.sample.playing&&!f.sample.acknowledgment));const answerFrames=frames.filter(f=>f.sample.trace==='second'&&f.sample.playing&&!f.sample.acknowledgment);
  output.stop();await wait(()=>mouth.scale.y===1);const noDownloadsOnTurn=downloads===before,lateCannotRevive=cache.playing===null,unknownRejected=!runtime.current.speechMotion.accepts({...track,cues:[{cue:'unknown'}]});runtime.dispose();output.close();return {played,beforeStart,openFrames,restFrames,answerFrames,noDownloadsOnTurn,lateCannotRevive,unknownRejected,errors:[]};
 });
 assert.equal(result.played,true);assert.equal(result.beforeStart.playing,false);assert.ok(result.openFrames.length&&result.restFrames.length&&result.answerFrames.length);for(const f of result.openFrames){assert.equal(f.scale,6);assert.ok(f.sample.sampleOffset<28800);assert.equal(f.sample.clock,'AudioContext.currentTime');}for(const f of result.restFrames)assert.equal(f.scale,1);for(const f of result.answerFrames)assert.ok(Math.abs(f.scale-(1+Math.min(1,f.sample.amplitude*5)*5))<.001,'same-frame amplitude pose must replace the cue without forced rest: '+JSON.stringify(f));assert.equal(result.noDownloadsOnTurn,true);assert.equal(result.lateCannotRevive,true);assert.equal(result.unknownRejected,true);assert.deepEqual(errors,[]);
});
