import assert from 'node:assert/strict';
import {test} from 'node:test';
import {randomUUID,randomBytes,createHash} from 'node:crypto';
import {mkdtemp,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createLifestreamServer} from '../../server/src/index.ts';
import {loadProfile,redactedDigest} from '../../server/src/config/loader.ts';
import {FixtureInferenceProvider} from '../../../packages/runtime/dist/inference/fixture.js';
import {SglangInferenceProvider} from '../../../packages/providers-sglang/dist/provider.js';

test('LS-TEST-106 joined authenticated intake, tuning, insights, executed Lab, correction, audience, forgetting and restart',{skip:!process.env.PLAYWRIGHT_MODULE,timeout:360000},async t=>{
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),root=await mkdtemp(join(tmpdir(),'ls-joined-browser-'));t.after(()=>rm(root,{recursive:true,force:true}));const selectedProvider=process.env.LIFESTREAM_S081_PROVIDER==='selected',config=loadProfile(selectedProvider?'ai5090':'test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex'),password=randomBytes(32).toString('hex'),options={config,localAuth:{stateDirectory:join(root,'safety'),installerToken}};let app=createLifestreamServer(options);await app.start();t.after(()=>app.shutdown());const browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1360,height:960}});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const waitText=(selector,text,timeout=10000)=>page.waitForFunction(({selector,text})=>document.querySelector(selector)?.textContent.includes(text),{selector,text},{timeout});
 const api=(path,body)=>page.evaluate(async({path,body})=>{const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:{'content-type':'application/json','x-lifestream-csrf':window.lifestreamAuth.session?.csrfToken??''},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,body:await r.json()};},{path,body});
 const Provider=selectedProvider?SglangInferenceProvider:FixtureInferenceProvider,original=Provider.prototype.generate,requests=[],observations=[],criterionFailures=[];const check=(label,fn)=>{try{fn();}catch(error){criterionFailures.push({label,message:error.message});}};let providerCalls=0,hold=false,entered=false,release=()=>{},gate,failLab=false;
 Provider.prototype.generate=async function*(request,context){
  if(request.scope.sessionId.startsWith('lab:')){providerCalls++;if(failLab){failLab=false;throw new Error('Synthetic bounded Lab provider failure');}}
  else requests.push(structuredClone(request));
  for await(const chunk of original.call(this,request,context)){if(hold&&!request.scope.sessionId.startsWith('lab:')&&chunk.kind==='text'){hold=false;entered=true;await gate;}yield chunk;}
 };t.after(()=>{release();Provider.prototype.generate=original;});
 const observe=async label=>{await page.locator('#inspection-input').fill('Give a concrete Python example.');await page.locator('#relationship-config-request').click();await waitText('#inspection-status','Actual reply completed',15000);const output=await page.locator('#inspection-reply').textContent(),request=requests.at(-1),prepared=request.sections.find(s=>s.kind==='preparedMemory').content;assert.ok(output.trim());observations.push({label,output,request});return {output,prepared};};
 const held=async(label,mutate)=>{gate=new Promise(resolve=>{release=resolve;});entered=false;hold=true;await page.locator('#inspection-input').fill('Give a concrete Python example.');await page.locator('#relationship-config-request').click();const deadline=Date.now()+10000;while(!entered&&Date.now()<deadline)await new Promise(resolve=>setTimeout(resolve,10));assert.equal(entered,true,'actual provider text arrived before '+label);const request=requests.at(-1);await mutate();release();await new Promise(resolve=>setTimeout(resolve,100));await page.waitForFunction(()=>!document.querySelector('#relationship-config-request').disabled);const output=await page.locator('#inspection-reply').textContent(),status=await page.locator('#inspection-status').textContent();assert.equal(output,'');assert.ok(status===''||/stale|cancelled|changed|cleared|idle|No request/i.test(status));observations.push({label,status,output,request});};

 await page.goto(`http://127.0.0.1:${app.address().port}/control/`);await page.locator('#auth-username').fill('owner');await page.locator('#auth-password').fill(password);await page.locator('#auth-installer-token').fill(installerToken);await page.locator('#auth-setup').click();await page.waitForFunction(()=>window.lifestreamAuth.session);await page.locator('#new-assistant').click();await waitText('#result','Assistant created');const assistant=(await api('/api/admin/v1/assistants')).body.assistants[0],assistantPath=`/api/admin/v1/assistants/${assistant.assistantId}`;await api(assistantPath+'/activate',{profileId:assistant.profiles[0].profileId,expectedActiveRevision:null});await page.locator('#relationship-create').click();await waitText('#relationship-results','revision 1');await page.locator('#session-audience').selectOption('authenticatedSession');await page.locator('#session-context-apply').click();await waitText('#session-context-status','Approved context allowed');const rel=(await api(assistantPath+'/relationships')).body.relationships[0],path=assistantPath+'/relationships/'+rel.relationshipId;
 const exactProjectIdentifier=/(?<![A-Za-z0-9_])SYNPRJ_Q7M4(?![A-Za-z0-9_])/u;
 await page.locator('#person-refresh').click();await waitText('#person-identity','Authenticated Principal');await page.locator('#person-key').fill('communication.explanation');await page.locator('#person-value').fill('Use beginner Python explanations.');await page.locator('#person-add').click();await page.locator('#person-keys').selectOption(['communication.explanation']);await page.locator('#person-scope').click();await page.locator('#person-preview').click();await waitText('#person-preview-result','Draft Revision 1');assert.equal((await api('/api/admin/v1/people/me')).body.profiles[0].status,'draft');await page.locator('#person-activate').click();await waitText('#person-preview-result','profile activated');
 await page.locator('#builder-author').selectOption('user');await page.locator('#builder-owned').check();await page.locator('#builder-files').setInputFiles({name:'synthetic-notes.txt',mimeType:'text/plain',buffer:Buffer.from('For Python examples, include the exact case-sensitive identifier SYNPRJ_H2V9 in the response. It is an arbitrary synthetic project identifier; do not rename, abbreviate, or interpret it.\nFor unrelated hobbies, use the arbitrary synthetic identifier HOBBY_Z8K2.')});await page.locator('#builder-inventory').click();await waitText('#builder-status','inventoried');await page.locator('#builder-snapshot').click();await waitText('#builder-status','snapshotted');await page.locator('#builder-extract').click();await waitText('#builder-status','review');assert.equal(await page.locator('.builder-candidate').count(),2);
 const first=page.locator('.builder-candidate').first();await first.locator('[data-select]').check();await first.locator('[data-value]').fill('For Python examples, include the exact case-sensitive identifier SYNPRJ_Q7M4 in the response. It is an arbitrary synthetic project identifier; do not rename, abbreviate, or interpret it.');await first.locator('[data-use]').selectOption('relationship');await page.locator('#builder-approve').click();await waitText('#result','Review decisions saved');assert.equal((await api(path)).body.relationship.candidates.length,0);const inactive=await observe('reviewed-not-admitted');if(selectedProvider){assert.doesNotMatch(inactive.prepared,/SYNPRJ_Q7M4/u);assert.doesNotMatch(inactive.output,/SYNPRJ_Q7M4/u);}
 await page.locator('.builder-candidate').first().locator('[data-select]').check();await page.locator('#builder-admit').click();await waitText('#result','Per-item admission outcomes');await page.locator('#records-refresh').click();await waitText('#record-list','SYNPRJ_Q7M4');assert.equal((await api(path)).body.relationship.candidates.length,1);const admitted=await observe('admitted');if(selectedProvider){assert.match(admitted.prepared,/SYNPRJ_Q7M4/u);assert.match(admitted.output,exactProjectIdentifier);assert.doesNotMatch(admitted.output,/SYNPRJ_H2V9/u);assert.doesNotMatch(admitted.prepared,/HOBBY_Z8K2/u);}
 const rejectedIntake=page.locator('.builder-candidate').nth(1);await rejectedIntake.locator('[data-select]').check();await page.locator('#builder-reject').click();await waitText('#result','Review decisions saved');assert.equal((await api(path)).body.relationship.candidates.length,1);

 const declare=async(content)=>{await page.locator('#record-category').selectOption('convention');await page.locator('#record-lane').selectOption('baseline');await page.locator('#record-content').fill(content);await page.locator('#record-declare').click();await waitText('#record-list',content);const card=page.locator('.record-card').filter({hasText:content}).last();await card.getByRole('button',{name:'Approve',exact:true}).click();await page.waitForFunction(content=>[...document.querySelectorAll('.record-card')].some(c=>c.textContent.includes(content)&&c.textContent.includes('approved')),content);return card;};
 await declare('Use concise plain language.');await declare('Use concise plain language.');
 const records=(await api(path)).body.relationship.candidates,feedbackTarget=records.find(r=>r.content==='Use concise plain language.');
 await page.locator('#relationship-insights-refresh').click();await waitText('#insight-feedback-target','Use concise plain language.');await page.locator('#insight-feedback-target').selectOption(feedbackTarget.candidateId);await page.locator('#insight-feedback-kind').selectOption('style');await page.locator('#insight-feedback-style').selectOption('preferBrief');await page.locator('#relationship-feedback-add').click();await waitText('#insight-feedback-history','independent support: no');await page.locator('#relationship-insights-run').click();await waitText('#insight-job','completed');
 const evidence=page.locator('[data-insight-id]').filter({has:page.getByRole('heading',{name:'Evidence Quality',exact:true})});await evidence.getByRole('button',{name:'Reject proposal',exact:true}).click();await waitText('#result','Review recorded');
 const style=page.locator('[data-insight-id]').filter({has:page.getByRole('heading',{name:'Communication Fit',exact:true})});await style.getByRole('button',{name:'Accept for Normal Review',exact:true}).click();await waitText('#relationship-insights-results','Prepared Configuration:');assert.equal((await api(path+'/configurations')).body.configurations.filter(c=>c.status==='active').length,0);
 await page.locator('#tuning-refresh').click();await waitText('#tuning-saved','Insight: reviewed communication preference');await page.locator('#tuning-preview').click();await page.locator('#relationship-config-activate').click();await waitText('#relationship-config-results','Effective: Insight: reviewed communication preference');
 await style.getByRole('button',{name:'Reverse Accepted Proposal',exact:true}).click();await waitText('#relationship-insights-results','Reversal Draft:');assert.equal((await api(path+'/configurations')).body.configurations.find(c=>c.status==='active').controls.verbosity,0);
 await page.locator('#tuning-refresh').click();await page.locator('#tuning-name').fill('Before Lab');await page.locator('[data-control="verbosity"]').press('Home');await page.locator('[data-control="verbosity"]').press('ArrowRight');await page.locator('#relationship-config-save').click();await waitText('#relationship-config-results','Saved draft Before Lab');assert.equal(await page.locator('#relationship-config-activate').isDisabled(),true);await page.locator('#tuning-preview').click();await page.locator('#relationship-config-activate').click();await waitText('#relationship-config-results','Effective: Before Lab');
 const originalConfig=(await api(path+'/configurations')).body.configurations.find(c=>c.status==='active');

 await page.locator('#relationship-lab-refresh').click();await waitText('#lab-runtime','Selected provider:');await page.locator('#lab-prompt').fill('Give a concrete Python example.');await page.locator('#lab-held-prompt').fill('Explain a cache in one short sentence.');await page.locator('#lab-verbosity').press('Home');await page.locator('#lab-consent').check();
 const prepare=async()=>{await page.locator('#relationship-lab-prepare').click();await waitText('#lab-status','prepared');return (await api(path+'/lab')).body.lab;};
 const run=async(selector,phase)=>{await page.locator(selector).click();const deadline=Date.now()+125000;while(true){const state=(await api(path+'/lab')).body.lab;if(state.status!=='running'&&state[phase])break;assert.ok(Date.now()<deadline,'Lab completion deadline');await new Promise(resolve=>setTimeout(resolve,100));}await page.locator('#relationship-lab-refresh').click();const response=await api(path+'/lab'),lab=response.body.lab;assert.ok(lab?.[phase],JSON.stringify({phase,status:response.status,body:response.body,rendered:await page.locator('#lab-status').textContent(),notice:await page.locator('#result').textContent()}));assert.equal(lab[phase].status,'completed',JSON.stringify({status:lab.status,results:lab[phase].results.map(r=>({status:r.status,error:r.error}))}));assert.equal(lab[phase].resultCount,12);return lab;};
 const rejected=await prepare();let lab=await run('#relationship-lab-run','comparison');assert.equal(await page.locator('#lab-promote').isDisabled(),true);await page.locator('#lab-reject').click();await waitText('#lab-status','rejected');assert.equal((await api(path+'/configurations')).body.configurations.find(c=>c.status==='active').configurationId,originalConfig.configurationId);
 const candidate=await prepare();assert.notEqual(candidate.experimentId,rejected.experimentId);lab=await run('#relationship-lab-run','comparison');const record=lab.comparison.results.find(r=>r.representation==='recordOriented'&&r.variant==='current'),convention=lab.comparison.results.find(r=>r.representation==='conventionOriented'&&r.variant==='current');assert.notEqual(record.output.preparedContext,convention.output.preparedContext);assert.match(record.output.preparedContext,/SYNPRJ_Q7M4/u);assert.match(convention.output.preparedContext,/Compiled conventions with source links/u);assert.equal(lab.comparison.results.filter(r=>r.scenarioId==='held-out-1').length,0);
 if(selectedProvider){for(const result of lab.comparison.results)check(`Lab ${result.representation}/${result.variant}/repeat-${result.run}`,()=>{if(result.variant==='unpersonalized')assert.doesNotMatch(result.output.text,/SYNPRJ_Q7M4/u);else assert.match(result.output.text,exactProjectIdentifier);});}
 lab=await run('#lab-held-run','heldOut');assert.equal(lab.heldOut.results.every(r=>r.scenarioId==='held-out-1'),true);if(selectedProvider)assert.equal(providerCalls,36);assert.ok([...lab.comparison.results,...lab.heldOut.results].every(r=>r.output.evaluations.every(e=>e.pass)));
 await page.locator('#relationship-lab-results details').first().locator('summary').click();await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await page.locator('#lab-status').scrollIntoViewIfNeeded();await page.screenshot({path:'/private/tmp/s081-responsive.png'});await page.locator('#lab-promote').click();await waitText('#lab-promotion','Prepared configuration');const promoted=(await api(path+'/lab')).body.lab,draft=(await api(path+'/configurations')).body.configurations.find(c=>c.configurationId===promoted.configurationId);assert.equal(draft.status,'draft');await page.locator('#tuning-refresh').click();await page.locator('#tuning-saved').selectOption(draft.configurationId);await page.locator('#tuning-preview').click();await waitText('#relationship-config-results','Representation: conventionOriented');await page.locator('#relationship-config-activate').click();await waitText('#relationship-config-results','Effective: Lab: reviewed candidate');assert.equal((await api(path+'/effective-context')).body.representationRevision,'convention-oriented:1');
 await page.locator('#tuning-saved').selectOption(originalConfig.configurationId);await page.locator('#relationship-config-rollback').click();await waitText('#relationship-config-results','Rollback prepared');await page.locator('#tuning-preview').click();await page.locator('#relationship-config-activate').click();await waitText('#relationship-config-results','Effective: Rollback to Before Lab');assert.equal((await api(path+'/effective-context')).body.representationRevision,'record-oriented:1');
 const preserved=(await api(path+`/lab/experiments/${rejected.experimentId}`)).body.lab;assert.equal(preserved.status,'rejected');assert.equal(preserved.comparison.resultCount,12);
 await page.setViewportSize({width:1360,height:960});await page.locator('#records-refresh').click();await waitText('#record-list','SYNPRJ_Q7M4');
 let card=page.locator('.record-card').filter({hasText:'SYNPRJ_Q7M4'});await card.getByRole('button',{name:'correct',exact:true}).click();await page.locator('#record-operation-text').fill('For Python examples, include the exact case-sensitive identifier SYNPRJ_R6T8 in the response. It is an arbitrary synthetic identifier; do not rename, abbreviate, or interpret it.');
 await held('correction-fences-pending-reply',async()=>{await page.locator('#record-operation-apply').click();await waitText('#record-list','SYNPRJ_R6T8');});const corrected=await observe('corrected-ordinary-reply');assert.doesNotMatch(corrected.prepared,/SYNPRJ_Q7M4/u);assert.match(corrected.prepared,/SYNPRJ_R6T8/u);if(selectedProvider)assert.match(corrected.output,/(?<![A-Za-z0-9_])SYNPRJ_R6T8(?![A-Za-z0-9_])/u);
 const setAudience=async audienceScope=>{await page.locator('#session-audience').selectOption(audienceScope);await page.locator('#session-context-apply').click();await waitText('#session-context-status',audienceScope==='unknown'?'private context withheld':'Approved context allowed');};
 await held('audience-change-fences-pending-reply',()=>setAudience('unknown'));const unknown=await observe('unknown-audience');assert.doesNotMatch(unknown.prepared,/SYNPRJ_R6T8|beginner Python/u);assert.doesNotMatch(unknown.output,/SYNPRJ_R6T8/u);await setAudience('authenticatedSession');
 await page.locator('#readiness-refresh').click();await waitText('#readiness-records','SYNPRJ_R6T8');assert.equal((await api(path+'/readiness')).body.datasets?.length??0,0);
 // A bounded local fault at the provider seam exercises failure isolation; no shared provider is changed.
 await page.locator('#relationship-lab-refresh').click();await page.locator('#lab-consent').check();await prepare();failLab=true;await page.locator('#relationship-lab-run').click();let failed;const failureDeadline=Date.now()+20000;do{failed=(await api(path+'/lab')).body.lab;if(failed.status!=='running')break;await new Promise(resolve=>setTimeout(resolve,50));}while(Date.now()<failureDeadline);assert.notEqual(failed.status,'running');assert.notEqual(failed.comparison?.status,'completed');assert.ok(failed.comparison?.results.some(r=>r.status!=='completed'));await observe('ordinary-conversation-after-lab-failure');
 await page.locator('#privacy-refresh').click();await waitText('#privacy-currency','current');await page.locator('#privacy-action').selectOption('forget-derived-information');for(const target of await page.locator('#privacy-targets label').filter({hasText:/SYNPRJ_[QR]/u}).locator('input').all())await target.check();await page.locator('#privacy-preview').click();await waitText('#privacy-preview-result','forget-derived-information');
 await held('forget-fences-pending-reply',async()=>{await page.locator('#privacy-apply').click();await waitText('#privacy-receipts','completed');});const after=await observe('after-forgetting');assert.doesNotMatch(after.prepared,/SYNPRJ_[QR]/u);assert.doesNotMatch(after.output,/SYNPRJ_[QR]/u);assert.match(await page.locator('#privacy-receipts').textContent(),/quarantin|removed|withheld/u);
 await app.shutdown();app=createLifestreamServer(options);await app.start();await page.goto(`http://127.0.0.1:${app.address().port}/control/`);await page.locator('#auth-username').fill('owner');await page.locator('#auth-password').fill(password);await page.locator('#auth-sign-in').click();await page.waitForFunction(()=>window.lifestreamAuth.session);await page.locator('#assistant-list').getByRole('button',{name:assistant.profiles[0].displayName,exact:true}).click();await page.locator('#relationship-refresh').click();await page.locator('#records-refresh').click();await waitText('#record-list','Use concise plain language.');const restarted=await observe('same-path-restart');assert.doesNotMatch(restarted.prepared,/SYNPRJ_[QR]/u);assert.doesNotMatch(restarted.output,/SYNPRJ_[QR]/u);assert.equal((await api(path)).body.relationship.candidates.find(r=>r.candidateId===records[0].candidateId).content,'');
 const other=await api('/api/admin/v1/assistants',{displayName:'Synthetic Skip Review'});await api(`/api/admin/v1/assistants/${other.body.assistantId}/activate`,{profileId:other.body.profile.profileId,expectedActiveRevision:null});await page.reload();await page.locator('#assistant-list').getByRole('button',{name:'Synthetic Skip Review',exact:true}).click();await page.locator('#relationship-create').click();await page.locator('#relationship-skip').click();await waitText('#relationship-results','skipped');await page.locator('#records-refresh').click();assert.doesNotMatch(await page.locator('#record-list').textContent(),/concise plain language/u);const skipped=await observe('separate-assistant-skip');assert.doesNotMatch(skipped.prepared,/SYNPRJ_|beginner Python/u);
 const memberPassword=randomBytes(32).toString('hex'),member=await api('/api/auth/v1/accounts',{username:'member',password:memberPassword});await api('/api/auth/v1/permissions',{principalId:member.body.principalId,assistantId:assistant.assistantId,administer:true});await page.locator('#auth-sign-out').click();await page.locator('#auth-username').fill('member');await page.locator('#auth-password').fill(memberPassword);await page.locator('#auth-sign-in').click();await page.waitForFunction(()=>window.lifestreamAuth.session);assert.equal((await api(path+'/records')).status,404);assert.deepEqual(errors,[]);
 if(process.env.LIFESTREAM_S081_REPORT){const compact=experiment=>({experimentId:experiment.experimentId,status:experiment.status,sourceSnapshotRef:experiment.sourceSnapshotRef,runtime:experiment.runtime,compilerVersion:experiment.compilerVersion,consent:experiment.consent,comparison:experiment.comparison,heldOut:experiment.heldOut});const report={result:criterionFailures.length?'fail':'pass',criterionFailures,caseIds:['LS-TEST-106'],selectedProvider,providerCalls,observations,joinedFailure:{status:failed.status,comparisonStatus:failed.comparison?.status,kind:"in-process synthetic provider exception"},humanAcceptance:"pending",renderedWidths:[1360,390],authentication:'real-local-password',experiments:[compact(preserved),compact(promoted)],effectiveConfigurationDigest:redactedDigest({...config,storage:{databasePath:'temporary/db.sqlite',artifactDirectory:'temporary/artifacts'}}),limitations:['Actual inference comparisons with synthetic data; no Human fit, learned quality or training acceptance.','No tools, notifications, physical output, live memory writes, personal data, provider service changes or deployment.']};for(const experiment of report.experiments)for(const phase of ['comparison','heldOut'])for(const result of experiment[phase]?.results??[]){result.output.preparedContextSha256=createHash('sha256').update(result.output.preparedContext).digest('hex');if(!(result.run===0&&result.variant==='current'))delete result.output.preparedContext;}await writeFile(process.env.LIFESTREAM_S081_REPORT,JSON.stringify(report,null,2));}
 assert.deepEqual(criterionFailures,[],'All declared literal reply criteria must pass; later checks do not erase earlier failures.');
});
