import assert from 'node:assert/strict';
import { test } from 'node:test';
import { randomBytes } from 'node:crypto';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createLifestreamServer } from '../../server/src/index.ts';
import { loadProfile } from '../../server/src/config/loader.ts';

test('rendered real-authenticated People and Relationships workflow reviews selected files and manages record lifecycle at desktop and mobile widths', { skip: !process.env.PLAYWRIGHT_MODULE, timeout: 90000 }, async t => {
 const { chromium }=await import(process.env.PLAYWRIGHT_MODULE),root=await mkdtemp(join(tmpdir(),'ls-rendered-records-'));t.after(()=>rm(root,{recursive:true,force:true}));const selectedProvider=process.env.LIFESTREAM_S075_PROVIDER==='selected',config=loadProfile(selectedProvider?'ai5090':'test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'state.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex'),password=randomBytes(32).toString('hex'),options={config,localAuth:{stateDirectory:join(root,'safety'),installerToken}};let app=createLifestreamServer(options);await app.start();t.after(()=>app.shutdown());const browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1440,height:960}});page.setDefaultTimeout(7000);const errors=[];page.on('pageerror',error=>errors.push(error.message));
 const observations=[];const {SglangInferenceProvider}=await import('../../../packages/providers-sglang/dist/provider.js');const originalGenerate=SglangInferenceProvider.prototype.generate;const requests=[];if(selectedProvider)SglangInferenceProvider.prototype.generate=async function*(request,context){requests.push(structuredClone(request));yield* originalGenerate.call(this,request,context);};t.after(()=>{SglangInferenceProvider.prototype.generate=originalGenerate;});
 const api=(path,body)=>page.evaluate(async({path,body})=>{const response=await fetch(path,{method:body===undefined?'GET':'POST',headers:{'content-type':'application/json','x-lifestream-csrf':window.lifestreamAuth.session?.csrfToken||''},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:response.status,body:await response.json()};},{path,body});
 const turn=async(assistantId,label)=>{const response=await page.evaluate(async assistantId=>{const response=await fetch('/api/runtime/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-lifestream-csrf':window.lifestreamAuth.session.csrfToken},body:JSON.stringify({assistantId,userInput:'Give a concrete Python example.'})});return {status:response.status,text:await response.text()};},assistantId);assert.equal(response.status,200);assert.match(response.text,/interaction.completed/u);const output=[...response.text.matchAll(/^data: (.+)$/gmu)].map(match=>JSON.parse(match[1])).filter(item=>typeof item.text==='string').map(item=>item.text).join('');const request=requests.at(-1);const observed={label,output,...(request?{scope:request.scope,manifest:request.manifest,preparedMemory:request.sections.find(item=>item.kind==='preparedMemory')}:{})};observations.push(observed);return observed;};
 const waitText=(selector,text)=>page.waitForFunction(({selector,text})=>document.querySelector(selector)?.textContent.includes(text),{selector,text});
 await page.goto(`http://127.0.0.1:${app.address().port}/control/`);await page.locator('#auth-username').fill('owner');await page.locator('#auth-password').fill(password);await page.locator('#auth-installer-token').fill(installerToken);await page.locator('#auth-setup').click();await page.waitForFunction(()=>window.lifestreamAuth.session);
 await page.locator('#new-assistant').click();await waitText('#result','Assistant created');const assistant=(await api('/api/admin/v1/assistants')).body.assistants[0];const assistantPath=`/api/admin/v1/assistants/${assistant.assistantId}`;const profile=assistant.profiles[0];assert.equal((await api(assistantPath+'/activate',{profileId:profile.profileId,expectedActiveRevision:null})).status,200);
 await page.locator('#relationship-create').click();await waitText('#relationship-results','revision 1');await page.locator('#records-refresh').click();await waitText('#record-scope','Revision 1');
 assert.equal((await api('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'})).status,200);
 const relationship=(await api(assistantPath+'/relationships')).body.relationships[0],path=assistantPath+'/relationships/'+relationship.relationshipId;
 await page.locator('#person-refresh').click();await waitText('#person-identity','Authenticated Principal');await page.locator('#person-key').fill('communication.explanation');await page.locator('#person-value').fill('Use beginner Python explanations.');await page.locator('#person-add').click();await page.locator('#person-keys').selectOption(['communication.explanation']);await page.locator('#person-scope').click();await page.locator('#person-preview').click();await waitText('#person-preview-result','Draft Revision 1');assert.equal((await api('/api/admin/v1/people/me')).body.profiles[0].status,'draft');await page.locator('#person-activate').click();await waitText('#person-preview-result','profile activated');
 await page.locator('#builder-author').selectOption('user');await page.locator('#builder-owned').check();await page.locator('#builder-files').setInputFiles({name:'synthetic-notes.txt',mimeType:'text/plain',buffer:Buffer.from('For Python examples, use the synthetic project Blue Finch.\nFor unrelated hobbies, use synthetic glass gardening.')});await page.locator('#builder-inventory').click();await waitText('#builder-status','inventoried');await page.locator('#builder-snapshot').click();await waitText('#builder-status','snapshotted');await page.locator('#builder-extract').click();await waitText('#builder-status','review');assert.equal(await page.locator('.builder-candidate').count(),2);
 const first=page.locator('.builder-candidate').first();await first.locator('[data-select]').check();await first.locator('[data-value]').fill('For Python examples, use the synthetic project Green Finch.');await first.locator('[data-use]').selectOption('relationship');await page.locator('#builder-approve').click();await waitText('#result','Review decisions saved');assert.equal((await api(path)).body.relationship.candidates.length,0);const inactive=await turn(assistant.assistantId,'reviewed-not-admitted');if(selectedProvider){assert.doesNotMatch(inactive.preparedMemory.content,/Green Finch/u);assert.doesNotMatch(inactive.output,/Green Finch/u);}
 await page.locator('.builder-candidate').first().locator('[data-select]').check();await page.locator('#builder-admit').click();await waitText('#result','Per-item admission outcomes');await page.locator('#records-refresh').click();await waitText('#record-list','Green Finch');assert.equal((await api(path)).body.relationship.candidates.length,1);const admitted=await turn(assistant.assistantId,'admitted');if(selectedProvider){assert.match(admitted.preparedMemory.content,/Green Finch/u);assert.match(admitted.output,/Green Finch/u);assert.doesNotMatch(admitted.preparedMemory.content,/glass gardening/u);}
 const rejected=page.locator('.builder-candidate').nth(1);await rejected.locator('[data-select]').check();await page.locator('#builder-reject').click();await waitText('#result','Review decisions saved');assert.equal((await api(path)).body.relationship.candidates.length,1);
 await page.locator('#record-category').selectOption('convention');await page.locator('#record-lane').selectOption('baseline');await page.locator('#record-content').fill('Use one concise sentence by default.');await page.locator('#record-declare').click();await waitText('#record-list','Use one concise sentence');let card=page.locator('.record-card').filter({hasText:'Use one concise sentence'});await card.getByRole('button',{name:'Approve',exact:true}).click();await page.waitForFunction(()=>[...document.querySelectorAll('.record-card')].some(item=>item.textContent.includes('Use one concise sentence')&&item.textContent.includes('approved')));
 await card.getByRole('button',{name:'correct',exact:true}).click();await page.locator('#record-operation-text').fill('Use two concise sentences by default.');await page.locator('#record-operation-apply').click();await waitText('#record-list','Use two concise sentences');card=page.locator('.record-card').filter({hasText:'Use two concise sentences'});await card.getByRole('button',{name:'annotate',exact:true}).click();await page.locator('#record-operation-text').fill('A reviewed synthetic preference.');await page.locator('#record-operation-apply').click();await waitText('#record-list','reviewed synthetic preference');await card.getByRole('button',{name:'pin',exact:true}).click();await page.locator('#record-operation-apply').click();await waitText('#record-list','Operator-Pinned Salience');
 const correctedReply=await turn(assistant.assistantId,'reviewed-correction');if(selectedProvider){assert.match(correctedReply.preparedMemory.content,/Critical corrections: Use two concise sentences/u);assert.doesNotMatch(correctedReply.preparedMemory.content,/one concise sentence/u);}
 const before=(await api(path)).body.relationship;assert.equal(before.candidates.filter(item=>item.status==='approved').length,2);assert.equal(before.candidates.find(item=>item.content.includes('two concise')).history.length,3);
 // Desktop and responsive forms are rendered and operated, not inferred from CSS text.
 await page.setViewportSize({width:390,height:844});await page.locator('#record-filter').selectOption('convention');await waitText('#record-list','Use two concise sentences');await page.screenshot({path:'/private/tmp/s075-responsive.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),true);await card.getByRole('button',{name:'restrict mention',exact:true}).click();await page.locator('#record-operation-apply').click();await waitText('#record-list','Withheld');
 const exportEvent=page.waitForEvent('download');await page.locator('#records-export').click();const download=await exportEvent;assert.equal(download.suggestedFilename(),'relationship-context.json');assert.ok(await download.path());
 // Reimport of the same pinned source cannot create independent records or undo correction/rejection.
 await page.locator('#builder-files').setInputFiles({name:'renamed-synthetic.txt',mimeType:'text/plain',buffer:Buffer.from('For Python examples, use the synthetic project Blue Finch.\nFor unrelated hobbies, use synthetic glass gardening.')});await page.locator('#builder-inventory').click();await waitText('#builder-status','review');assert.equal((await api(path)).body.relationship.candidates.length,before.candidates.length);
 await app.shutdown();app=createLifestreamServer(options);await app.start();await page.goto(`http://127.0.0.1:${app.address().port}/control/`);await page.locator('#auth-username').fill('owner');await page.locator('#auth-password').fill(password);await page.locator('#auth-sign-in').click();await page.waitForFunction(()=>window.lifestreamAuth.session);await page.locator('#assistant-list').getByRole('button',{name:profile.displayName,exact:true}).click();await page.locator('#relationship-refresh').click();await page.locator('#records-refresh').click();await waitText('#record-list','Green Finch');await page.locator('#builder-refresh').click();await page.locator('#builder-jobs').selectOption({index:1});await waitText('#builder-status','Collection Access closed');assert.equal((await api(path)).body.relationship.candidates.length,before.candidates.length);
 const other=await api('/api/admin/v1/assistants',{displayName:'Other Synthetic Relationship'});await api(`/api/admin/v1/assistants/${other.body.assistantId}/activate`,{profileId:other.body.profile.profileId,expectedActiveRevision:null});await page.reload();await page.locator('#assistant-list').getByRole('button',{name:'Other Synthetic Relationship',exact:true}).click();await page.locator('#relationship-create').click();await page.locator('#relationship-skip').click();await waitText('#relationship-results','skipped');await page.locator('#records-refresh').click();assert.doesNotMatch(await page.locator('#record-list').textContent(),/Green Finch|two concise/u);await api('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'});const skipped=await turn(other.body.assistantId,'other-assistant-skipped-bootstrap');if(selectedProvider){assert.doesNotMatch(skipped.preparedMemory?.content||'',/Green Finch|beginner Python/u);assert.doesNotMatch(skipped.output,/Green Finch/u);}
 const memberPassword=randomBytes(32).toString('hex'),member=await api('/api/auth/v1/accounts',{username:'member',password:memberPassword});await api('/api/auth/v1/permissions',{principalId:member.body.principalId,assistantId:assistant.assistantId,administer:true});await page.locator('#auth-sign-out').click();await page.locator('#auth-username').fill('member');await page.locator('#auth-password').fill(memberPassword);await page.locator('#auth-sign-in').click();await page.waitForFunction(()=>window.lifestreamAuth.session);await page.locator('#assistant-list').getByRole('button',{name:profile.displayName,exact:true}).click();await page.locator('#relationship-refresh').click();await waitText('#relationship-results','No relationship review');assert.doesNotMatch(await page.locator('#record-list').textContent(),/Green Finch/u);await page.locator('#person-refresh').click();assert.equal((await api('/api/admin/v1/people/me')).body.profiles.length,0);assert.equal((await api(path+'/records')).status,404);
 assert.deepEqual(errors,[]);
 if(process.env.LIFESTREAM_S075_REPORT)await writeFile(process.env.LIFESTREAM_S075_REPORT,JSON.stringify({result:'pass',caseIds:['LS-TEST-090','LS-TEST-091'],renderedWidths:[1440,390],authentication:'real-local-password',observations,selectedProvider,limitations:['Synthetic selected files and accounts only','No Human fit, physical output, training, deployment or production acceptance']},null,2));
});
