import assert from 'node:assert/strict';
import {test} from 'node:test';
import {randomUUID,randomBytes} from 'node:crypto';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createLifestreamServer} from '../../server/src/index.ts';
import {loadProfile} from '../../server/src/config/loader.ts';
test('rendered synthetic readiness consent, dataset export, fixture review and revocation', {skip:!process.env.PLAYWRIGHT_MODULE,timeout:60000},async t=>{
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),root=await mkdtemp(join(tmpdir(),'ls-insight-browser-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex'),app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'safety'),installerToken}});await app.start();t.after(()=>app.shutdown());const browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1360,height:960}});page.setDefaultTimeout(8000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const waitText=(selector,text)=>page.waitForFunction(({selector,text})=>document.querySelector(selector)?.textContent.includes(text),{selector,text});
 const api=(path,body)=>page.evaluate(async({path,body})=>{const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:{'content-type':'application/json','x-lifestream-csrf':window.lifestreamAuth.session?.csrfToken??''},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,body:await r.json()};},{path,body});
 await page.goto(`http://127.0.0.1:${app.address().port}/control/`);await page.locator('#auth-username').fill('owner');await page.locator('#auth-password').fill(randomBytes(32).toString('hex'));await page.locator('#auth-installer-token').fill(installerToken);await page.locator('#auth-setup').click();await page.waitForFunction(()=>window.lifestreamAuth.session);await page.locator('#new-assistant').click();await waitText('#result','Assistant created');const assistant=(await api('/api/admin/v1/assistants')).body.assistants[0];await page.locator('#relationship-create').click();await waitText('#relationship-results','revision 1');const relationship=(await api(`/api/admin/v1/assistants/${assistant.assistantId}/relationships`)).body.relationships[0],path=`/api/admin/v1/assistants/${assistant.assistantId}/relationships/${relationship.relationshipId}`;

 await api(`/api/admin/v1/assistants/${assistant.assistantId}/activate`,{profileId:assistant.profiles[0].profileId,expectedActiveRevision:null});await api('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'});
 let revision=1;for(let n=0;n<3;n++){const c=(await api(path+'/candidates',{content:`Synthetic independent source ${n}`,source:'authored-synthetic',sourceFamily:`family-${n}`,uncertainty:'low',expectedRevision:revision++,idempotencyKey:randomUUID()})).body.candidate;await api(path+`/candidates/${c.candidateId}/decision`,{decision:'approved',expectedRevision:revision++,idempotencyKey:randomUUID()});}
 await page.locator('#readiness-refresh').click();await waitText('#readiness-records','Synthetic independent source 2');await page.locator('#readiness-consent-check').check();for(const box of await page.locator('[data-source-select]').all())await box.check();await page.locator('#readiness-consent').click();await waitText('#readiness-consents','approved');for(const box of await page.locator('[data-source-select]').all())await box.check();const splits=await page.locator('[data-source-split]').all();await splits[1].selectOption('validation');await splits[2].selectOption('test');await page.locator('#readiness-build').click();await waitText('#readiness-dataset','prepared');const downloadPromise=page.waitForEvent('download');await page.locator('#readiness-export').click();const download=await downloadPromise;const {readFile}=await import('node:fs/promises');const exported=JSON.parse(await readFile(await download.path(),'utf8'));assert.equal(exported.records.length,3);assert.equal(exported.digest.length,64);
 await page.locator('#readiness-register').click();await waitText('#readiness-artifacts','candidate');await page.getByRole('button',{name:'Approve Fixture Review',exact:true}).click();await waitText('#readiness-artifacts','approved');await page.getByRole('button',{name:'Simulate Authenticated Routing',exact:true}).click();await waitText('#readiness-result','"route": "adapter"');await page.getByRole('button',{name:'Check Selected Runtime Eligibility',exact:true}).click();await waitText('#readiness-result','"route": "fallback"');await page.locator('#readiness-kind').selectOption('concreteFactHypothesis');await page.locator('#readiness-register').click();await waitText('#readiness-artifacts','concreteFactHypothesis');await page.getByRole('button',{name:'Approve Fixture Review',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('[data-artifact-action="approve-fixture"]'));await page.locator('#readiness-compare').click();await waitText('#readiness-result','"learnedQuality": "notEvaluated"');await page.getByRole('button',{name:'Revoke Dataset Consent',exact:true}).click();await waitText('#readiness-dataset','quarantined');await waitText('#readiness-artifacts','quarantined');await page.getByRole('button',{name:'Simulate Authenticated Routing',exact:true}).first().click();await waitText('#readiness-result','"route": "fallback"');
 await page.setViewportSize({width:390,height:844});await page.locator('#readiness-refresh').scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await page.screenshot({path:'/private/tmp/s079-responsive.png'});await page.locator('#new-assistant').click();await waitText('#result','Assistant created');assert.equal(await page.locator('#readiness-records').textContent(),'');assert.equal(await page.locator('#readiness-result').textContent(),'');assert.deepEqual(errors,[]);
});
