import { followWorkspace } from './workspace-navigation.mjs';
import assert from 'node:assert/strict';
import {test} from 'node:test';
import {randomUUID,randomBytes,createHash} from 'node:crypto';
import {mkdtemp,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createLifestreamServer} from '../../server/src/index.ts';
import {loadProfile,redactedDigest} from '../../server/src/config/loader.ts';
import {SglangInferenceProvider} from '../../../packages/providers-sglang/dist/provider.js';

test('rendered Lab executes both representations, rejects a candidate and reviews a separate held-out promotion with rollback',{skip:!process.env.PLAYWRIGHT_MODULE,timeout:300000},async t=>{
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),root=await mkdtemp(join(tmpdir(),'ls-lab-browser-'));t.after(()=>rm(root,{recursive:true,force:true}));const selectedProvider=process.env.LIFESTREAM_S078_PROVIDER==='selected',config=loadProfile(selectedProvider?'ai5090':'test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex'),app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'safety'),installerToken}});await app.start();t.after(()=>app.shutdown());const browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=followWorkspace(await browser.newPage({viewport:{width:1360,height:960}}));page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const waitText=(selector,text,timeout=10000)=>page.waitForFunction(({selector,text})=>document.querySelector(selector)?.textContent.includes(text),{selector,text},{timeout});
 const api=(path,body)=>page.evaluate(async({path,body})=>{const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:{'content-type':'application/json','x-lifestream-csrf':window.lifestreamAuth.session?.csrfToken??''},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,body:await r.json()};},{path,body});
 let providerCalls=0;const original=SglangInferenceProvider.prototype.generate;if(selectedProvider)SglangInferenceProvider.prototype.generate=async function*(request,context){if(request.scope.sessionId.startsWith('lab:'))providerCalls++;yield* original.call(this,request,context);};t.after(()=>{SglangInferenceProvider.prototype.generate=original;});
 await page.goto(`http://127.0.0.1:${app.address().port}/control/`);await page.locator('#auth-username').fill('owner');await page.locator('#auth-password').fill(randomBytes(32).toString('hex'));await page.locator('#auth-installer-token').fill(installerToken);await page.locator('#auth-setup').click();await page.waitForFunction(()=>window.lifestreamAuth.session);await page.locator('#new-assistant').click();await waitText('#result','Assistant created');const assistant=(await api('/api/admin/v1/assistants')).body.assistants[0],assistantPath=`/api/admin/v1/assistants/${assistant.assistantId}`;await api(assistantPath+'/activate',{profileId:assistant.profiles[0].profileId,expectedActiveRevision:null});await page.locator('#relationship-create').click();await waitText('#relationship-results','revision 1');await api('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'});const rel=(await api(assistantPath+'/relationships')).body.relationships[0],path=assistantPath+'/relationships/'+rel.relationshipId;
 const add=async(content,contextUse='baseline')=>{const current=(await api(path)).body.relationship,candidate=(await api(path+'/candidates',{content,contextUse,source:'authored',sourceFamily:'context-family',uncertainty:'high',expectedRevision:current.revision,idempotencyKey:randomUUID()})).body.candidate;await api(path+`/candidates/${candidate.candidateId}/decision`,{decision:'approved',expectedRevision:current.revision+1,idempotencyKey:randomUUID()});};await add('Use concise plain language.');await add('Use concise plain language.');await add('The synthetic project codename is Azure Birch.','correction');
 const originalConfig=(await api(path+'/configurations',{preset:'balanced',name:'Before Lab',controls:{verbosity:0.5},idempotencyKey:randomUUID()})).body.configuration;await api(path+`/configurations/${originalConfig.configurationId}/activate`,{expectedRevision:originalConfig.revision,idempotencyKey:randomUUID()});
 await page.locator('#relationship-lab-refresh').click();await waitText('#lab-runtime','Selected provider:');await page.locator('#lab-prompt').fill('What is the synthetic project codename? Answer in one short sentence.');await page.locator('#lab-held-prompt').fill('Explain a cache in one short sentence.');await page.locator('#lab-verbosity').press('Home');await page.locator('#lab-consent').check();
 const prepare=async()=>{await page.locator('#relationship-lab-prepare').click();await waitText('#lab-status','prepared');return (await api(path+'/lab')).body.lab;};
 const run=async(selector,phase)=>{await page.locator(selector).click();const deadline=Date.now()+125000;while(true){const state=(await api(path+'/lab')).body.lab;if(state.status!=='running'&&state[phase])break;assert.ok(Date.now()<deadline,'Lab completion deadline');await new Promise(resolve=>setTimeout(resolve,100));}await page.locator('#relationship-lab-refresh').click();const response=await api(path+'/lab'),lab=response.body.lab;assert.ok(lab?.[phase],JSON.stringify({phase,status:response.status,body:response.body,rendered:await page.locator('#lab-status').textContent(),notice:await page.locator('#result').textContent()}));assert.equal(lab[phase].status,'completed',JSON.stringify({status:lab.status,results:lab[phase].results.map(r=>({status:r.status,error:r.error}))}));assert.equal(lab[phase].resultCount,12);return lab;};
 const rejected=await prepare();let lab=await run('#relationship-lab-run','comparison');assert.equal(await page.locator('#lab-promote').isDisabled(),true);await page.locator('#lab-reject').click();await waitText('#lab-status','rejected');assert.equal((await api(path+'/configurations')).body.configurations.find(c=>c.status==='active').configurationId,originalConfig.configurationId);
 const candidate=await prepare();assert.notEqual(candidate.experimentId,rejected.experimentId);lab=await run('#relationship-lab-run','comparison');const record=lab.comparison.results.find(r=>r.representation==='recordOriented'&&r.variant==='current'),convention=lab.comparison.results.find(r=>r.representation==='conventionOriented'&&r.variant==='current');assert.notEqual(record.output.preparedContext,convention.output.preparedContext);assert.match(record.output.preparedContext,/Critical corrections: The synthetic project codename is Azure Birch/u);assert.match(convention.output.preparedContext,/Compiled conventions with source links/u);assert.equal(lab.comparison.results.filter(r=>r.scenarioId==='held-out-1').length,0);
 if(selectedProvider){for(const result of lab.comparison.results)if(result.variant==='unpersonalized')assert.doesNotMatch(result.output.text,/Azure Birch/u);else assert.match(result.output.text,/Azure Birch/u);}
 lab=await run('#lab-held-run','heldOut');assert.equal(lab.heldOut.results.every(r=>r.scenarioId==='held-out-1'),true);if(selectedProvider)assert.equal(providerCalls,36);assert.ok([...lab.comparison.results,...lab.heldOut.results].every(r=>r.output.evaluations.every(e=>e.pass)));
 await page.locator('#relationship-lab-results details').first().locator('summary').click();await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await page.locator('#lab-status').scrollIntoViewIfNeeded();await page.screenshot({path:'/private/tmp/s078-responsive.png'});await page.locator('#lab-promote').click();await waitText('#lab-promotion','Prepared configuration');const promoted=(await api(path+'/lab')).body.lab,draft=(await api(path+'/configurations')).body.configurations.find(c=>c.configurationId===promoted.configurationId);assert.equal(draft.status,'draft');await page.locator('#tuning-refresh').click();await page.locator('#tuning-saved').selectOption(draft.configurationId);await page.locator('#tuning-preview').click();await waitText('#relationship-config-results','Representation: conventionOriented');await page.locator('#relationship-config-activate').click();await waitText('#relationship-config-results','Effective: Lab: reviewed candidate');assert.equal((await api(path+'/effective-context')).body.representationRevision,'convention-oriented:1');
 await page.locator('#tuning-saved').selectOption(originalConfig.configurationId);await page.locator('#relationship-config-rollback').click();await waitText('#relationship-config-results','Rollback prepared');await page.locator('#tuning-preview').click();await page.locator('#relationship-config-activate').click();await waitText('#relationship-config-results','Effective: Rollback to Before Lab');assert.equal((await api(path+'/effective-context')).body.representationRevision,'record-oriented:1');
 const preserved=(await api(path+`/lab/experiments/${rejected.experimentId}`)).body.lab;assert.equal(preserved.status,'rejected');assert.equal(preserved.comparison.resultCount,12);assert.deepEqual(errors,[]);
 if(process.env.LIFESTREAM_S078_REPORT){const compact=experiment=>({experimentId:experiment.experimentId,status:experiment.status,sourceSnapshotRef:experiment.sourceSnapshotRef,runtime:experiment.runtime,compilerVersion:experiment.compilerVersion,consent:experiment.consent,comparison:experiment.comparison,heldOut:experiment.heldOut});const report={result:'pass',caseIds:['LS-TEST-099'],selectedProvider,providerCalls,renderedWidths:[1360,390],authentication:'real-local-password',experiments:[compact(preserved),compact(promoted)],effectiveConfigurationDigest:redactedDigest({...config,storage:{databasePath:'temporary/db.sqlite',artifactDirectory:'temporary/artifacts'}}),limitations:['Actual inference comparisons with synthetic data; no Human fit, learned quality or training acceptance.','No tools, notifications, physical output, live memory writes, personal data, provider service changes or deployment.']};for(const experiment of report.experiments)for(const phase of ['comparison','heldOut'])for(const result of experiment[phase]?.results??[]){result.output.preparedContextSha256=createHash('sha256').update(result.output.preparedContext).digest('hex');if(!(result.run===0&&result.variant==='current'))delete result.output.preparedContext;}await writeFile(process.env.LIFESTREAM_S078_REPORT,JSON.stringify(report,null,2));}
});
