import { followWorkspace } from './workspace-navigation.mjs';
import assert from 'node:assert/strict';
import {test} from 'node:test';
import {randomUUID,randomBytes} from 'node:crypto';
import {mkdtemp,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createLifestreamServer} from '../../server/src/index.ts';
import {loadProfile} from '../../server/src/config/loader.ts';
import {SglangInferenceProvider} from '../../../packages/providers-sglang/dist/provider.js';
import {FixtureInferenceProvider} from '../../../packages/runtime/dist/inference/fixture.js';
test('S081 independent skipped-Assistant conversation and cross-account isolation after joined run interruption',{skip:!process.env.PLAYWRIGHT_MODULE,timeout:90000},async t=>{
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),root=await mkdtemp(join(tmpdir(),'ls-recovery-browser-'));t.after(()=>rm(root,{recursive:true,force:true}));const selectedProvider=process.env.LIFESTREAM_S081_CONTINUATION_PROVIDER==='selected',config=loadProfile(selectedProvider?'ai5090':'test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex'),password=randomBytes(32).toString('hex'),options={config,localAuth:{stateDirectory:join(root,'safety'),installerToken}};let app=createLifestreamServer(options);await app.start();t.after(()=>app.shutdown());const browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=followWorkspace(await browser.newPage({viewport:{width:1360,height:960}}));page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const waitText=(selector,text)=>page.waitForFunction(({selector,text})=>document.querySelector(selector)?.textContent.includes(text),{selector,text});
 const api=(path,body)=>page.evaluate(async({path,body})=>{const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:{'content-type':'application/json','x-lifestream-csrf':window.lifestreamAuth.session?.csrfToken??''},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,body:await r.json()};},{path,body});
 const Provider=selectedProvider?SglangInferenceProvider:FixtureInferenceProvider,original=Provider.prototype.generate,requests=[];Provider.prototype.generate=async function*(request,context){requests.push(structuredClone(request));yield* original.call(this,request,context);};t.after(()=>{Provider.prototype.generate=original;});
 await page.goto(`http://127.0.0.1:${app.address().port}/control/`);await page.locator('#auth-username').fill('owner');await page.locator('#auth-password').fill(password);await page.locator('#auth-installer-token').fill(installerToken);await page.locator('#auth-setup').click();await page.waitForFunction(()=>window.lifestreamAuth.session);await page.locator('#new-assistant').click();await waitText('#result','Assistant created');const assistant=(await api('/api/admin/v1/assistants')).body.assistants[0],assistantPath=`/api/admin/v1/assistants/${assistant.assistantId}`;await api(assistantPath+'/activate',{profileId:assistant.profiles[0].profileId,expectedActiveRevision:null});await page.locator('#relationship-create').click();await waitText('#relationship-results','revision 1');await api('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'});const rel=(await api(assistantPath+'/relationships')).body.relationships[0],path=assistantPath+'/relationships/'+rel.relationshipId;

 const candidate=(await api(path+'/candidates',{content:'For Python examples include the exact identifier SYNPRJ_Q7M4.',contextUse:'baseline',source:'authored-synthetic',sourceFamily:'one-source',uncertainty:'low',expectedRevision:1,idempotencyKey:randomUUID()})).body.candidate;await api(path+`/candidates/${candidate.candidateId}/decision`,{decision:'approved',expectedRevision:2,idempotencyKey:randomUUID()});
 const other=await api('/api/admin/v1/assistants',{displayName:'Independent Synthetic Skip'});await api(`/api/admin/v1/assistants/${other.body.assistantId}/activate`,{profileId:other.body.profile.profileId,expectedActiveRevision:null});await page.reload();await page.locator('#assistant-list').getByRole('button',{name:'Independent Synthetic Skip',exact:true}).click();await page.locator('#relationship-create').click();await page.locator('#relationship-skip').click();await waitText('#relationship-results','skipped');await page.locator('#records-refresh').click();assert.doesNotMatch(await page.locator('#record-list').textContent(),/SYNPRJ_Q7M4/u);
 await page.locator('#inspection-input').fill('Give a concrete Python example.');await page.locator('#relationship-config-request').click();await page.waitForFunction(()=>{const s=document.querySelector('#inspection-status')?.textContent;return s&&!s.startsWith('Executing');},undefined,{timeout:15000});const status=await page.locator('#inspection-status').textContent(),reply=await page.locator('#inspection-reply').textContent();
 const memberPassword=randomBytes(32).toString('hex'),member=await api('/api/auth/v1/accounts',{username:'member',password:memberPassword});await api('/api/auth/v1/permissions',{principalId:member.body.principalId,assistantId:assistant.assistantId,administer:true});await page.locator('#auth-sign-out').click();await page.locator('#auth-username').fill('member');await page.locator('#auth-password').fill(memberPassword);await page.locator('#auth-sign-in').click();await page.waitForFunction(()=>window.lifestreamAuth.session);const denied=await api(path+'/records');assert.equal(denied.status,404);assert.equal((await api('/api/admin/v1/people/me')).body.profiles.length,0);assert.deepEqual(errors,[]);
 const prepared=requests.at(-1)?.sections.find(s=>s.kind==='preparedMemory').content??'';const result=status.startsWith('Actual reply completed')&&!/SYNPRJ_Q7M4/u.test(prepared+reply)?'pass':'fail';if(process.env.LIFESTREAM_S081_CONTINUATION_REPORT)await writeFile(process.env.LIFESTREAM_S081_CONTINUATION_REPORT,JSON.stringify({result,selectedProvider,caseIds:['LS-TEST-106'],claimClass:'independent-component-continuation',observations:{status,reply,request:requests.at(-1),otherAccountRecordsStatus:denied.status,otherAccountUserProfiles:0},humanAcceptance:'pending',limitations:['Separate fresh synthetic app; does not replace the failed joined journey. No physical output, personal data, training, deployment or provider configuration change.']},null,2));assert.equal(result,'pass',JSON.stringify({status,reply}));
});
