import { followWorkspace } from './workspace-navigation.mjs';
import assert from 'node:assert/strict';
import { test } from 'node:test';
import { randomBytes,randomUUID } from 'node:crypto';
import { mkdtemp,rm,writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createLifestreamServer } from '../../server/src/index.ts';
import { loadProfile,redactedDigest } from '../../server/src/config/loader.ts';
import { SglangInferenceProvider } from '../../../packages/providers-sglang/dist/provider.js';

test('rendered tuning previews named versions, inspects actual replies and rolls back without widening scope', {skip:!process.env.PLAYWRIGHT_MODULE,timeout:90000},async t=>{
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),root=await mkdtemp(join(tmpdir(),'ls-tuning-browser-'));t.after(()=>rm(root,{recursive:true,force:true}));const selectedProvider=process.env.LIFESTREAM_S076_PROVIDER==='selected',config=loadProfile(selectedProvider?'ai5090':'test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex');const app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'safety'),installerToken}});await app.start();t.after(()=>app.shutdown());const browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=followWorkspace(await browser.newPage({viewport:{width:1360,height:960}}));page.setDefaultTimeout(15000);await page.clock.install();const errors=[];page.on('pageerror',error=>errors.push(error.message));const requests=[],observations=[],original=SglangInferenceProvider.prototype.generate;if(selectedProvider)SglangInferenceProvider.prototype.generate=async function*(request,context){requests.push(structuredClone(request));yield* original.call(this,request,context);};t.after(()=>{SglangInferenceProvider.prototype.generate=original;});
 const api=(path,body)=>page.evaluate(async({path,body})=>{const response=await fetch(path,{method:body===undefined?'GET':'POST',headers:{'content-type':'application/json','x-lifestream-csrf':window.lifestreamAuth.session?.csrfToken||''},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:response.status,body:await response.json()};},{path,body});const waitText=(selector,text)=>page.waitForFunction(({selector,text})=>document.querySelector(selector)?.textContent.includes(text),{selector,text});
 await page.goto(`http://127.0.0.1:${app.address().port}/control/`);await page.locator('#auth-username').fill('owner');await page.locator('#auth-password').fill(randomBytes(32).toString('hex'));await page.locator('#auth-installer-token').fill(installerToken);await page.locator('#auth-setup').click();await page.waitForFunction(()=>window.lifestreamAuth.session);await page.locator('#new-assistant').click();await waitText('#result','Assistant created');const assistant=(await api('/api/admin/v1/assistants')).body.assistants[0];await api(`/api/admin/v1/assistants/${assistant.assistantId}/activate`,{profileId:assistant.profiles[0].profileId,expectedActiveRevision:null});await page.locator('#relationship-create').click();await waitText('#relationship-results','revision 1');await page.locator('#tuning-refresh').click();await page.waitForFunction(()=>document.querySelectorAll('[data-control]').length===12);assert.equal(await page.locator('#tuning-unsupported input:enabled').count(),0);
 const relationship=(await api(`/api/admin/v1/assistants/${assistant.assistantId}/relationships`)).body.relationships[0],path=`/api/admin/v1/assistants/${assistant.assistantId}/relationships/${relationship.relationshipId}`;await api('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'});const candidate=(await api(path+'/candidates',{content:'For cache examples, use the synthetic project Silver Meadow.',source:'authored',sourceFamily:'one',uncertainty:'high',expectedRevision:1,idempotencyKey:randomUUID()})).body.candidate;await api(path+`/candidates/${candidate.candidateId}/decision`,{decision:'approved',expectedRevision:2,idempotencyKey:randomUUID()});
 const save=async(name,high)=>{await page.locator('#tuning-name').fill(name);await page.locator('[data-control="verbosity"]').press(high?'End':'Home');await page.locator('#relationship-config-save').click();await waitText('#relationship-config-results',`Saved draft ${name}`);assert.equal(await page.locator('#relationship-config-activate').isDisabled(),true);await page.locator('#tuning-preview').click();await waitText('#relationship-config-results','Current basis');};
 await save('Brief',false);assert.equal((await api(path+'/configurations')).body.configurations.filter(item=>item.status==='active').length,0);await page.locator('#relationship-config-activate').click();await waitText('#relationship-config-results','Effective: Brief');const briefConfig=(await api(path+'/configurations')).body.configurations.find(item=>item.status==='active');
 const observe=async label=>{await page.locator('#inspection-input').fill('Explain cache invalidation to a beginner.');await page.locator('#relationship-config-request').click();try{await waitText('#inspection-status','Actual reply completed');}catch(error){t.diagnostic(JSON.stringify({label,status:await page.locator('#inspection-status').textContent(),partialReplyCharacters:(await page.locator('#inspection-reply').textContent()).length,metadata:await page.locator('#inspection-metadata').textContent()}));throw error;}const output=await page.locator('#inspection-reply').textContent(),metadata=await page.locator('#inspection-metadata').textContent();assert.ok(output.trim());assert.match(metadata,/relationship-context:6/u);assert.match(metadata,/causal proof/u);const request=requests.at(-1);const result={label,output,metadata,...(request?{scope:request.scope,manifest:request.manifest,preparedMemory:request.sections.find(item=>item.kind==='preparedMemory')}:{})};observations.push(result);return result;};
 await page.locator('#inspection-full').check();const brief=await observe('brief-active');assert.equal(await page.locator('#inspection-prompt-panel').isVisible(),true);assert.match(await page.locator('#inspection-prompt').textContent(),/\[preparedMemory; untrusted content\]/u);if(selectedProvider)assert.match(brief.preparedMemory.content,/Keep optional explanation brief/u);await page.clock.fastForward(31000);assert.equal(await page.locator('#inspection-prompt-panel').isVisible(),false);assert.equal(await page.locator('#inspection-prompt').textContent(),'');await page.locator('#inspection-full').uncheck();
 await save('Detailed',true);await page.locator('#relationship-config-activate').click();await waitText('#relationship-config-results','Effective: Detailed');const detailed=await observe('detailed-active');if(selectedProvider){assert.match(detailed.preparedMemory.content,/greater length/u);assert.ok(detailed.output.length>brief.output.length,JSON.stringify({brief:brief.output,detailed:detailed.output}));assert.notEqual(detailed.preparedMemory.contentDigest,brief.preparedMemory.contentDigest);}
 await page.setViewportSize({width:390,height:844});await page.locator('#relationship-config-reset').click();await waitText('#relationship-config-results','reset prepared as a draft');const reset=(await api(path+'/configurations')).body.configurations.at(-1);assert.equal(reset.status,'draft');assert.equal((await api(path+'/configurations')).body.configurations.find(item=>item.status==='active').name,'Detailed');await page.locator('#tuning-saved').selectOption(briefConfig.configurationId);await page.locator('#relationship-config-rollback').click();await waitText('#relationship-config-results','Rollback prepared');await page.locator('#tuning-preview').click();await page.locator('#relationship-config-activate').click();await waitText('#relationship-config-results','Effective: Rollback to Brief');await page.locator('#tuning-saved').selectOption(reset.configurationId);await page.locator('#tuning-preview').click();await waitText('#relationship-config-results','Stale basis');assert.equal(await page.locator('#relationship-config-activate').isDisabled(),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await page.screenshot({path:'/private/tmp/s076-responsive.png'});
 const other=await api('/api/admin/v1/assistants',{displayName:'Other Tuning Assistant'});const otherRel=(await api(`/api/admin/v1/assistants/${other.body.assistantId}/relationships`,{})).body.relationship;const otherPath=`/api/admin/v1/assistants/${other.body.assistantId}/relationships/${otherRel.relationshipId}`;assert.equal((await api(otherPath+`/configurations/${briefConfig.configurationId}/activate`,{expectedRevision:briefConfig.revision,idempotencyKey:randomUUID()})).status,404);assert.deepEqual((await api(otherPath+'/configurations')).body.configurations,[]);assert.deepEqual(errors,[]);
 if(process.env.LIFESTREAM_S076_REPORT)await writeFile(process.env.LIFESTREAM_S076_REPORT,JSON.stringify({result:'pass',caseIds:['LS-TEST-095','LS-TEST-105'],renderedWidths:[1360,390],authentication:'real-local-password',selectedProvider,observations,effectiveConfigurationDigest:redactedDigest({...config,storage:{databasePath:'temporary/db.sqlite',artifactDirectory:'temporary/artifacts'}}),providers:(await api('/health')).body.providers,limitations:['Observed input and reply differences are not causal attribution or general quality guarantees','No hidden reasoning, personal input, physical output, training, production or Human acceptance']},null,2));
});
