import assert from 'node:assert/strict';
import test from 'node:test';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes} from 'node:crypto';
import {createLifestreamServer} from '../../server/src/index.ts';
import {loadProfile} from '../../server/src/config/loader.ts';
import {savedVoiceFixture} from '../../server/test/saved-voice-fixture.ts';
test('saved voice UI compares candidates, cancels previews and activates only a reviewed revision',{skip:!process.env.PLAYWRIGHT_MODULE},async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-saved-voice-ui-'));t.after(()=>rm(root,{recursive:true,force:true}));const fixture=await savedVoiceFixture();t.after(fixture.close);const config=loadProfile('test');config.providers.tts='voxcpm';config.ttsProfile=fixture.profile;config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};config.authority.authentication='local-password';const installerToken=randomBytes(32).toString('hex'),app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'safety'),installerToken}});await app.start();t.after(()=>app.shutdown());
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(12000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${app.address().port}/control/#voice`);await page.waitForFunction(()=>window.lifestreamUI);await page.evaluate(()=>window.lifestreamAuth.ready);
 await page.locator('#auth-username').fill('synthetic-owner');await page.locator('#auth-password').fill('Synthetic-voice-password-1');await page.locator('#auth-installer-token').fill(installerToken);await page.locator('#auth-setup').click();await page.waitForFunction(()=>!!window.lifestreamAuth.session);
 await page.evaluate(async()=>{const r=(p,b)=>window.lifestreamAuth.request(p,b,b!==undefined),a=await r('/api/admin/v1/assistants',{displayName:'Synthetic voice comparison'});await r(`/api/admin/v1/assistants/${a.assistantId}/activate`,{profileId:a.profile.profileId,expectedActiveRevision:null});});await page.reload();await page.waitForFunction(()=>window.lifestreamUI);await page.locator('[data-destination=voice]').click();const panel=page.locator('.saved-voices');await panel.getByRole('button',{name:'Refresh saved voices'}).click();await page.waitForFunction(()=>!document.querySelector('[data-voice-save]').disabled);
 const create=async(label,description)=>{await panel.locator('[name=label]').fill(label);await panel.locator('[name=description]').fill(description);await panel.getByRole('button',{name:'Save voice candidate'}).click();await panel.getByRole('heading',{name:label,exact:true}).waitFor();};
 await create('Calm candidate','Calm clear delivery');await create('Bright candidate','Bright clear delivery');const calm=panel.locator('.saved-voice-candidate').filter({has:page.getByRole('heading',{name:'Calm candidate',exact:true})}),bright=panel.locator('.saved-voice-candidate').filter({has:page.getByRole('heading',{name:'Bright candidate',exact:true})});assert.equal(await calm.getByRole('button',{name:'Activate Calm candidate'}).isEnabled(),false);assert.equal(await calm.getByRole('checkbox').isEnabled(),false);
 await calm.getByRole('button',{name:'Preview Calm candidate'}).click();await panel.locator('[data-voice-status]').filter({hasText:'Preview finished: Calm candidate'}).waitFor();assert.equal(await calm.getByRole('checkbox').isEnabled(),true);assert.equal(await calm.getByRole('button',{name:'Activate Calm candidate'}).isEnabled(),false);
 fixture.state.delayMs=1500;await bright.getByRole('button',{name:'Preview Bright candidate'}).click();await panel.getByRole('button',{name:'Stop voice preview'}).click();assert.equal(await bright.getByRole('checkbox').isEnabled(),false);await page.waitForTimeout(1600);assert.equal(await bright.getByRole('button',{name:'Activate Bright candidate'}).isEnabled(),false);fixture.state.delayMs=0;
 await bright.getByRole('button',{name:'Preview Bright candidate'}).click();await panel.locator('[data-voice-status]').filter({hasText:'Preview finished: Bright candidate'}).waitFor();assert.equal(await bright.getByRole('checkbox').isEnabled(),true);
 await calm.getByRole('checkbox').check();await calm.getByRole('button',{name:'Activate Calm candidate'}).click();await panel.locator('[data-voice-active]').filter({hasText:'Saved voice Calm candidate'}).waitFor();assert.equal(await panel.locator('.saved-voice-candidate').count(),2);assert.equal(await calm.getByRole('checkbox').isEnabled(),false,'activation clears prior review state');
 if(process.env.SAVED_VOICE_SCREENSHOT){await page.screenshot({path:process.env.SAVED_VOICE_SCREENSHOT,fullPage:true});await page.setViewportSize({width:390,height:844});await panel.scrollIntoViewIfNeeded();await page.screenshot({path:process.env.SAVED_VOICE_SCREENSHOT.replace('.png','-mobile.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.setViewportSize({width:1440,height:1000});}
 await page.reload();await page.waitForFunction(()=>window.lifestreamUI);await panel.getByRole('button',{name:'Refresh saved voices'}).click();await panel.locator('[data-voice-active]').filter({hasText:'Saved voice Calm candidate'}).waitFor();assert.equal(await calm.getByRole('checkbox').isEnabled(),false);assert.equal(await calm.getByRole('button',{name:'Remove Calm candidate'}).isEnabled(),false);await bright.getByRole('button',{name:'Remove Bright candidate'}).click();await page.waitForFunction(()=>document.querySelectorAll('.saved-voice-candidate').length===1);assert.match(await panel.locator('[data-voice-active]').textContent(),/Calm candidate/);assert.deepEqual(errors,[]);
});
