import assert from 'node:assert/strict';
import test from 'node:test';
import {mkdtemp,rm,mkdir} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {randomUUID,randomBytes} from 'node:crypto';
import {createLifestreamServer} from '../../server/src/index.ts';
import {loadProfile} from '../../server/src/config/loader.ts';

test('two rendered endpoints cover readiness, cancellation, review, move, receipt and privacy races',{skip:!process.env.PLAYWRIGHT_MODULE,timeout:60000},async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-handoff-browser-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};config.authority.authentication='local-password';const installerToken=randomBytes(32).toString('hex'),password='Synthetic-handoff-password-1',app=createLifestreamServer({config,sessionEnvironmentId:randomUUID(),localAuth:{stateDirectory:join(root,'auth'),installerToken},audiencePrivacy:{sourceIds:[]}});await app.start();t.after(()=>app.shutdown());const base=`http://127.0.0.1:${app.address().port}`;
 const login=async setup=>{const response=await fetch(base+'/api/auth/v1/'+(setup?'setup':'sign-in'),{method:'POST',headers:{origin:base,'content-type':'application/json'},body:JSON.stringify({username:'owner',password,...(setup?{installerToken}:{})})});assert.equal(response.status,setup?201:200);return {cookie:response.headers.get('set-cookie').split(';')[0],...(await response.json()).session};};
 const owner=await login(true),destination=await login(false),headers={origin:base,'content-type':'application/json',cookie:owner.cookie,'x-lifestream-csrf':owner.csrfToken};
 const created=await(await fetch(base+'/api/admin/v1/assistants',{method:'POST',headers,body:JSON.stringify({displayName:'Synthetic handoff Assistant'})})).json();assert.equal((await fetch(base+`/api/admin/v1/assistants/${created.assistantId}/activate`,{method:'POST',headers,body:JSON.stringify({profileId:created.profile.profileId,expectedActiveRevision:null})})).status,200);
 const {chromium,_electron}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const sourceContext=await browser.newContext({viewport:{width:1280,height:1000}}),source=await sourceContext.newPage();const desktop=process.env.PLAYBACK_ELECTRON?await _electron.launch({executablePath:process.env.PLAYBACK_ELECTRON,args:['--user-data-dir='+join(root,'native'),'--url',base+'/control/#account']}):null;if(desktop)t.after(async()=>{const process=desktop.process();await Promise.race([desktop.close().catch(()=>{}),new Promise(r=>setTimeout(r,2000))]);if(process.exitCode===null&&!process.killed)process.kill('SIGKILL');});const targetContext=desktop?desktop.context():await browser.newContext({viewport:{width:1280,height:1000}}),target=desktop?await desktop.firstWindow():await targetContext.newPage();const errors=[];
 const navigate=async(page,id)=>{await page.locator(`[data-destination=${id}]`).click();await page.waitForFunction(id=>!document.querySelector(`[data-view=${id}]`).hidden,id);};
 const setup=async(page,context,session)=>{page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));if(!desktop||page!==target){const split=session.cookie.indexOf('=');await context.addCookies([{name:session.cookie.slice(0,split),value:session.cookie.slice(split+1),url:base,httpOnly:true,sameSite:'Strict'}]);}await page.goto(base+'/control/#session');await page.evaluate(()=>window.lifestreamAuth.ready);if(desktop&&page===target){await page.locator('#auth-username').fill('owner');await page.locator('#auth-password').fill(password);await page.locator('#auth-sign-in').click();await page.waitForFunction(()=>!!window.lifestreamAuth.session);}await page.waitForFunction(()=>!!window.lifestreamUI&&document.querySelector('#session-context-status').textContent.includes('revision 0'));await navigate(page,'session');assert.equal(await page.locator('#session-handoff-panel').isVisible(),false);await page.locator('#session-audience').selectOption('authenticatedSession');await page.locator('#session-context-apply').click();await page.waitForFunction(()=>document.querySelector('#session-context-status').textContent.includes('revision 1'));await page.locator('[data-audience-solo]').click();await page.waitForFunction(()=>document.documentElement.dataset.audienceProtected==='false');await page.locator('#assistant-list button').filter({hasText:'Synthetic handoff Assistant'}).click();await page.locator('[data-handoff-refresh]').click();await page.waitForFunction(()=>!document.querySelector('[data-handoff-ready]').disabled);};
 await setup(source,sourceContext,owner);await setup(target,targetContext,destination).catch(async error=>{t.diagnostic(JSON.stringify(await target.evaluate(()=>({url:location.href,hidden:document.hidden,auth:!!window.lifestreamAuth?.session,session:document.querySelector('#session-context-status')?.textContent,audience:document.querySelector('[data-audience-status]')?.textContent,handoff:document.querySelector('[data-handoff-status]')?.textContent,assistants:document.querySelector('#assistant-list')?.textContent})).catch(e=>({error:e.message}))));throw error;});
 await navigate(source,'conversation');await source.locator('#room-message').fill('SYNTHETIC_BROWSER_HANDOFF_ORCHID');await source.locator('#room-send').click();await source.waitForFunction(()=>document.querySelector('.room-turn.assistant .room-turn-state')?.textContent==='Completed');await navigate(source,'session');
 await target.locator('[data-handoff-ready]').click();await target.waitForFunction(()=>!document.querySelector('[data-handoff-cancel]').disabled);await target.locator('[data-handoff-cancel]').click();await target.waitForFunction(()=>document.querySelector('[data-handoff-cancel]').disabled&&!document.querySelector('[data-handoff-ready]').disabled);await target.locator('[data-handoff-ready]').click();await target.waitForFunction(()=>!document.querySelector('[data-handoff-cancel]').disabled);
 const review=async()=>{await source.locator('[data-handoff-refresh]').click();await source.waitForFunction(()=>document.querySelector('#handoff-destination').options.length===2);await source.locator('#handoff-destination').selectOption({index:1});await source.locator('[data-handoff-prepare]').click();await source.waitForFunction(()=>!document.querySelector('[data-handoff-commit]').disabled);};
 await review();assert.match(await source.locator('[data-handoff-review]').textContent(),/No grants or capture consent transfer/);await source.locator('[data-handoff-discard]').click();assert.equal(await source.locator('[data-handoff-commit]').isEnabled(),false);
 // A reviewed response received after audience protection must never restore controls.
 let release,seen;const gate=new Promise(r=>release=r),captured=new Promise(r=>seen=r);t.after(()=>release?.());await source.route('**/api/runtime/v1/handoff',async route=>{if(route.request().postDataJSON()?.operation!=='prepare')return route.continue();const response=await route.fetch();seen();await gate;await route.fulfill({response});});await source.locator('[data-handoff-prepare]').click();await captured;await source.locator('[data-audience-shared]').click();await source.waitForFunction(()=>document.documentElement.dataset.audienceProtected==='true');const delivered=source.waitForResponse(r=>r.url().endsWith('/api/runtime/v1/handoff')&&r.request().postDataJSON()?.operation==='prepare');release();await delivered;await source.unroute('**/api/runtime/v1/handoff');assert.equal(await source.locator('#session-handoff-panel').isVisible(),false);assert.equal(await source.locator('[data-handoff-review]').textContent(),'');assert.equal(await source.locator('[data-handoff-commit]').isEnabled(),false);await source.locator('[data-audience-solo]').click();await source.waitForFunction(()=>document.documentElement.dataset.audienceProtected==='false');
 // The audience change intentionally forgets prior dialogue. Admit a fresh source turn.
 await navigate(source,'conversation');await source.locator('#room-message').fill('SYNTHETIC_CURRENT_HANDOFF_ORCHID');await source.locator('#room-send').click();await source.waitForFunction(()=>document.querySelectorAll('.room-turn.assistant .room-turn-state').length>0&&[...document.querySelectorAll('.room-turn.assistant .room-turn-state')].every(e=>e.textContent==='Completed'));await navigate(source,'session');await review();
 if(process.env.HANDOFF_SCREENSHOT_DIRECTORY){await mkdir(process.env.HANDOFF_SCREENSHOT_DIRECTORY,{recursive:true,mode:0o700});await source.locator('#session-handoff-panel').screenshot({path:join(process.env.HANDOFF_SCREENSHOT_DIRECTORY,'handoff-review-desktop.png')});}
 await source.setViewportSize({width:390,height:844});await source.locator('#session-handoff-panel').scrollIntoViewIfNeeded();assert.equal(await source.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);if(process.env.HANDOFF_SCREENSHOT_DIRECTORY)await source.screenshot({path:join(process.env.HANDOFF_SCREENSHOT_DIRECTORY,'handoff-review-mobile.png')});await source.setViewportSize({width:1280,height:1000});
 await source.locator('[data-handoff-commit]').click();await source.waitForFunction(()=>document.querySelector('[data-handoff-status]').textContent.includes('This conversation has moved'));await source.locator('#session-handoff-panel summary').click();assert.match(await source.locator('[data-handoff-receipts]').textContent(),/"outcome": "completed"/);assert.equal(await source.locator('[data-handoff-ready]').isEnabled(),false);assert.equal(await source.locator('#session-context-apply').isEnabled(),false);await navigate(source,'conversation');await source.waitForFunction(()=>document.querySelector('#room-send').disabled&&document.querySelector('#room-mic-start').disabled);await navigate(source,'session');
 await target.locator('[data-handoff-refresh]').click();await target.waitForFunction(()=>document.querySelector('[data-handoff-status]').textContent.includes('Conversation received'));assert.equal(await target.locator('[data-handoff-ready]').isEnabled(),false);await target.locator('#session-handoff-panel summary').click();assert.match(await target.locator('[data-handoff-receipts]').textContent(),/"outcome": "completed"/);
 let input='';t.mock.method(app.providers.inference,'generate',async function*(request){input=JSON.stringify(request.sections);yield {kind:'text',text:'Synthetic continuation at the destination.'};yield {kind:'done'};});await navigate(target,'conversation');await target.locator('#room-message').fill('Continue on this endpoint.');await target.locator('#room-send').click();await target.waitForFunction(()=>document.querySelector('.room-turn.assistant .room-turn-state')?.textContent==='Completed');assert.match(input,/SYNTHETIC_CURRENT_HANDOFF_ORCHID/);assert.doesNotMatch(input,/SYNTHETIC_BROWSER_HANDOFF_ORCHID/);
 await navigate(target,'session');await target.locator('[data-audience-shared]').click();await target.waitForFunction(()=>document.documentElement.dataset.audienceProtected==='true');assert.equal(await target.locator('[data-handoff-receipts]').textContent(),'');await navigate(target,'account');await target.locator('#auth-sign-out').click();await target.waitForFunction(()=>!window.lifestreamAuth.session);assert.deepEqual(errors,[]);
});
