import assert from 'node:assert/strict';
import test from 'node:test';
import {mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {randomBytes} from 'node:crypto';
import {createLifestreamServer} from '../../server/src/index.ts';
import {loadProfile} from '../../server/src/config/loader.ts';

test('structured session settings cover load, preview, explicit apply, download and privacy races',{skip:!process.env.PLAYWRIGHT_MODULE},async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-session-definition-browser-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};config.authority.authentication='local-password';const installerToken=randomBytes(32).toString('hex'),app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'auth'),installerToken},audiencePrivacy:{sourceIds:[]}});await app.start();t.after(()=>app.shutdown());
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[];page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${app.address().port}/control/#account`);await page.evaluate(()=>window.lifestreamAuth.ready);await page.waitForFunction(()=>!!window.lifestreamUI);await page.locator('#auth-username').fill('owner');await page.locator('#auth-password').fill('Synthetic-config-password-1');await page.locator('#auth-installer-token').fill(installerToken);const enrollment=page.waitForResponse(r=>r.url().endsWith('/api/auth/v1/setup'));await page.locator('#auth-setup').click();const enrolled=await enrollment;assert.equal(enrolled.status(),201,'local enrollment must succeed');await page.waitForFunction(()=>!!window.lifestreamAuth.session&&document.querySelector('#session-context-status').textContent.includes('revision 0')).catch(async error=>{t.diagnostic(JSON.stringify(await page.evaluate(()=>({authenticated:!!window.lifestreamAuth.session,authStatus:document.querySelector('#auth-status').textContent,sessionStatus:document.querySelector('#session-context-status').textContent}))));throw error;});
 const navigate=async id=>{await page.locator(`[data-destination=${id}]`).click();await page.waitForFunction(id=>!document.querySelector(`[data-view=${id}]`).hidden,id);};
 await navigate('session');assert.equal(await page.locator('#session-definition-panel').isVisible(),false);await page.locator('#session-context-apply').click();await page.waitForFunction(()=>document.querySelector('#session-context-status').textContent.includes('revision 1'));await page.locator('[data-audience-solo]').click();await page.waitForFunction(()=>document.querySelector('[data-definition-status]').textContent.includes('Session revision 1'));
 const editor=page.locator('#session-definition-json'),apply=page.locator('[data-definition-apply]');assert.equal(await apply.isEnabled(),false);const initial=JSON.parse(await editor.inputValue());assert.equal(initial.audienceScope,'unknown');await editor.fill(JSON.stringify({...initial,audienceScope:'authenticatedSession'}));await page.locator('[data-definition-preview]').click();await page.waitForFunction(()=>document.querySelector('[data-definition-review]').textContent.includes('unknown → authenticatedSession'));assert.equal((await page.evaluate(()=>window.lifestreamAuth.request('/api/runtime/v1/session-context'))).revision,1);await apply.click();await page.waitForFunction(()=>document.querySelector('[data-definition-status]').textContent.includes('Applied to this sign-in at session revision 2'));assert.equal(await apply.isEnabled(),false);assert.equal((await page.evaluate(()=>window.lifestreamAuth.request('/api/runtime/v1/session-context'))).endpoint.privacyClass,'personal');
 const downloaded=page.waitForEvent('download');await page.locator('[data-definition-download]').click();const download=await downloaded;assert.equal(download.suggestedFilename(),'lifestream-session-settings.json');const {readFile}=await import('node:fs/promises');assert.deepEqual(JSON.parse(await readFile(await download.path(),'utf8')),{schemaVersion:'1.0.0',mode:'text',audienceScope:'authenticatedSession'});
 await editor.fill('{invalid');await page.locator('[data-definition-preview]').click();await page.waitForFunction(()=>document.querySelector('[data-definition-status]').textContent.startsWith('Preview unavailable'));assert.equal(await apply.isEnabled(),false);await page.locator('[data-definition-load]').click();await page.waitForFunction(()=>document.querySelector('[data-definition-status]').textContent.includes('Session revision 2'));assert.equal(JSON.parse(await editor.inputValue()).audienceScope,'authenticatedSession');
 await editor.fill(JSON.stringify({...initial,mode:'audio'}));await page.locator('[data-definition-preview]').click();await page.waitForFunction(()=>document.querySelector('[data-definition-status]').textContent.includes('Audio transport is not configured'));assert.equal(await apply.isEnabled(),false);
 await editor.fill(JSON.stringify(initial));await page.locator('[data-definition-preview]').click();await page.waitForFunction(()=>!document.querySelector('[data-definition-apply]').disabled);await editor.fill(JSON.stringify({...initial,provider:'UNTRUSTED'}));assert.equal(await apply.isEnabled(),false);await page.locator('[data-definition-preview]').click();await page.waitForFunction(()=>document.querySelector('[data-definition-status]').textContent.startsWith('Preview unavailable'));assert.equal(await apply.isEnabled(),false);
 await page.setViewportSize({width:390,height:844});await page.locator('#session-definition-panel').scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await page.setViewportSize({width:1280,height:1000});
 // A delayed authorized preview cannot repopulate fields after shared audience protection.
 let release,seen;const gate=new Promise(r=>release=r),captured=new Promise(r=>seen=r);await page.route('**/api/runtime/v1/session-definition',async route=>{if(route.request().method()!=='POST')return route.continue();const response=await route.fetch();seen();await gate;await route.fulfill({response});});await editor.fill(JSON.stringify(initial));await page.locator('[data-definition-preview]').click();await captured;await page.locator('[data-audience-shared]').click();await page.waitForFunction(()=>document.documentElement.dataset.audienceProtected==='true');const received=page.waitForResponse(r=>r.url().endsWith('/session-definition')&&r.request().method()==='POST');release();await received;assert.equal(await page.locator('#session-definition-panel').isVisible(),false);assert.equal(await editor.inputValue(),'');assert.equal(await page.locator('[data-definition-review]').textContent(),'');assert.equal(await apply.isEnabled(),false);await page.unroute('**/api/runtime/v1/session-definition');
 await page.locator('[data-audience-solo]').click();await page.waitForFunction(()=>document.querySelector('[data-definition-status]').textContent.includes('Session revision 2'));await navigate('account');await page.locator('#auth-sign-out').click();await page.waitForFunction(()=>!window.lifestreamAuth.session);assert.equal(await editor.inputValue(),'');assert.deepEqual(errors,[]);
});
