import assert from 'node:assert/strict';
import test from 'node:test';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {join} from 'node:path';
const enabled=!!process.env.PLAYWRIGHT_MODULE;
async function fixture(t){
 const state={configured:true,destinations:[{destinationRef:'fixture.private-route',destinationRevision:1,settings:{revision:0,rules:[{sourceRef:'fixture.source',eventClass:'criticalDevice',enabled:false,bypassQuietHours:false}],modality:'text',quietHours:null,snoozedUntil:null},bindings:[{sourceRef:'fixture.source',eventClass:'criticalDevice',label:'Synthetic device condition'}],worker:{running:true,destinations:[{destinationRef:'fixture.private-route',connected:true,reason:null}],deliveries:[]}}]},requests=[];let hold=null;
 const server=createServer(async(req,res)=>{
  if(req.url.startsWith('/api/')){let body='';for await(const chunk of req)body+=chunk;const input=body?JSON.parse(body):null;requests.push(input);const d=state.destinations[0];
   if(input){if(input.operation==='configure'){d.settings={...input,revision:d.settings.revision+1};}else if(input.operation==='acknowledge'){d.worker.deliveries[0].acknowledgedAt=new Date().toISOString();d.worker.deliveries[0].revision++;}else if(input.action==='disable'){d.settings.rules.forEach(r=>{r.enabled=false;r.bypassQuietHours=false;});d.settings.revision++;}else if(input.action==='snooze'){d.settings.snoozedUntil=input.until;d.settings.revision++;}}
   const value=JSON.stringify(state),send=()=>{res.writeHead(200,{'content-type':'application/json'});res.end(value);};if(hold){hold(send);hold=null;}else send();return;
  }
  if(req.url==='/urgent-away.js'||req.url==='/styles.css'){res.writeHead(200,{'content-type':req.url.endsWith('.js')?'text/javascript':'text/css'});res.end(await readFile(new URL('..'+req.url,import.meta.url),'utf8'));return;}
  res.end('<!doctype html><html lang="en" data-audience-protected="false"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/styles.css"><main class="shell card"></main></html>');
 });await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>{server.closeAllConnections();server.close();});const base=`http://127.0.0.1:${server.address().port}`;
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-background-networking','--disable-component-update','--disable-sync']});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));t.after(()=>assert.deepEqual(errors,[]));await page.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());
 await page.goto(base+'/#conversation');await page.evaluate(async()=>{window.scope={principalId:'fixture.owner',assistantId:'fixture.assistant'};const {installUrgentAway}=await import('/urgent-away.js');installUrgentAway({anchor:document.querySelector('main'),scope:()=>window.scope,api:async(path,options)=>{const r=await fetch(path,options);return r.json();}});});
 const refresh=async()=>{await page.locator('[data-away-refresh]').click();await page.waitForFunction(()=>!document.querySelector('[data-away-refresh]').disabled);};
 return {state,requests,page,refresh,hold:fn=>{hold=fn;}};
}
test('rendered away controls cover explicit class and quiet opt-in, save, snooze, disable and separate Human acknowledgment',{skip:!enabled},async t=>{
 const f=await fixture(t),{page}=f;assert.equal(await page.locator('[data-away-save]').isDisabled(),true);await f.refresh();await page.locator('[data-away-destination]').selectOption('fixture.private-route');assert.equal(await page.locator('[data-away-enabled]').isChecked(),false);assert.equal(await page.locator('[data-away-bypass]').isChecked(),false);
 await page.locator('[data-away-enabled]').check();await page.locator('[data-away-bypass]').check();await page.locator('[data-away-quiet]').check();await page.locator('[data-away-start]').fill('22:15');await page.locator('[data-away-end]').fill('07:30');await page.locator('[data-away-zone]').fill('America/Chicago');await page.locator('[data-away-save]').click();await page.waitForFunction(()=>document.querySelector('[data-away-status]').textContent.includes('settings saved'));
 const saved=f.requests.find(r=>r?.operation==='configure');assert.equal(saved.destinationRef,'fixture.private-route');assert.deepEqual(saved.rules,[{sourceRef:'fixture.source',eventClass:'criticalDevice',enabled:true,bypassQuietHours:true}]);assert.deepEqual(saved.quietHours,{startMinute:1335,endMinute:450,timeZone:'America/Chicago'});assert.equal(saved.modality,'text');
 await page.locator('[data-away-minutes]').selectOption('60');await page.locator('[data-away-snooze]').click();await page.waitForFunction(()=>document.querySelector('[data-away-status]').textContent.includes('snoozed'));assert.ok(f.requests.find(r=>r?.action==='snooze'));
 f.state.destinations[0].worker.deliveries=[{id:'fixture.delivery',revision:2,state:'accepted',conditionRef:'fixture.condition',reason:'provider_accepted',attemptedAt:new Date().toISOString(),acceptedAt:new Date().toISOString(),acknowledgedAt:null}];await f.refresh();await page.locator('summary').click();assert.match(await page.locator('[data-away-history]').innerText(),/Human acknowledgment not recorded/);await page.locator('[data-away-ack]').click();await page.waitForFunction(()=>document.querySelector('[data-away-history]').textContent.includes('Human acknowledged:'));assert.equal(f.requests.find(r=>r?.operation==='acknowledge').expectedRevision,2);
 f.state.destinations[0].conditions=[{condition:{conditionRef:'fixture.withheld',eventClass:'criticalDevice'},reasons:['output_unavailable']}];f.state.destinations[0].worker.deliveries.push({id:'fixture.unknown',revision:2,state:'unknown',conditionRef:'fixture.other',reason:'provider_unknown',attemptedAt:new Date().toISOString(),acceptedAt:null,acknowledgedAt:null});await f.refresh();assert.match(await page.locator('[data-away-history]').innerText(),/Condition withheld[\s\S]*output_unavailable/);assert.match(await page.locator('[data-away-history]').innerText(),/Delivery outcome unknown/);assert.equal(await page.locator('[data-away-ack]').count(),0);
 await page.locator('[data-away-disable]').click();await page.waitForFunction(()=>document.querySelector('[data-away-status]').textContent.includes('disabled'));assert.equal(await page.locator('[data-away-enabled]').isChecked(),false);assert.equal(await page.locator('[data-away-bypass]').isChecked(),false);
 if(process.env.URGENT_AWAY_QA_DIRECTORY){await mkdir(process.env.URGENT_AWAY_QA_DIRECTORY,{recursive:true});await page.screenshot({path:join(process.env.URGENT_AWAY_QA_DIRECTORY,'away-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:join(process.env.URGENT_AWAY_QA_DIRECTORY,'away-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
});
test('away UI clears late private data on scope loss without sending implicit disable or replay',{skip:!enabled},async t=>{
 const f=await fixture(t);await f.refresh();await f.page.locator('[data-away-destination]').selectOption('fixture.private-route');const count=f.requests.filter(Boolean).length;let release;f.hold(fn=>{release=fn;});await f.page.locator('[data-away-refresh]').click();for(let i=0;i<100&&!release;i++)await new Promise(r=>setTimeout(r,10));assert.ok(release);await f.page.evaluate(()=>{window.scope.assistantId='other';window.dispatchEvent(new Event('lifestream-assistant'));});release();await f.page.waitForTimeout(80);assert.equal(await f.page.locator('[data-away-save]').isDisabled(),true);assert.doesNotMatch(await f.page.locator('[data-away-history]').innerText(),/fixture/);assert.equal(f.requests.filter(Boolean).length,count);
});
test('unconfigured destination and invalid quiet schedule remain visibly unavailable without mutation',{skip:!enabled},async t=>{
 const f=await fixture(t);await f.refresh();await f.page.locator('[data-away-destination]').selectOption('fixture.private-route');await f.page.locator('[data-away-quiet]').check();await f.page.locator('[data-away-start]').fill('07:00');await f.page.locator('[data-away-end]').fill('07:00');await f.page.locator('[data-away-save]').click();await f.page.waitForFunction(()=>document.querySelector('[data-away-status]').textContent.includes('different'));assert.equal(f.requests.filter(Boolean).length,0);f.state.destinations=[];await f.refresh();assert.equal(await f.page.locator('[data-away-destination]').isDisabled(),true);assert.match(await f.page.locator('[data-away-status]').innerText(),/No authorized/);
});
