import assert from 'node:assert/strict';
import test from 'node:test';
import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {join} from 'node:path';

const enabled=!!process.env.PLAYWRIGHT_MODULE;
const until=()=>new Date(Date.now()+60000).toISOString();
const wait=async check=>{for(let i=0;i<150;i++){if(check())return;await new Promise(r=>setTimeout(r,20));}throw Error('Synthetic fixture observation timed out');};
async function fixture(t,{room=false}={}){
 const bindings=[{sourceRef:'fixture:source-a',eventClass:'criticalDevice',label:'Synthetic device condition',worldRef:'fixture:world',siteRef:'fixture:site',zoneRef:'fixture:zone'},{sourceRef:'fixture:source-b',eventClass:'criticalEnvironment',label:'Synthetic environment condition',worldRef:'fixture:world',siteRef:'fixture:site',zoneRef:'fixture:zone'}];
 const state={settings:{revision:0,rules:bindings.map(b=>({sourceRef:b.sourceRef,eventClass:b.eventClass,enabled:false,bypassQuietHours:false})),modality:'text',quietHours:null,snoozedUntil:null},bindings,conditions:[],deliveries:[],configured:true,connected:false,remoteDelivery:'notConfigured'},streams=new Set(),requests=[],errors=[];let opens=0,delayRead=null;
 const snapshot=()=>({...structuredClone(state),connected:streams.size>0});
 const emit=(event,value)=>{for(const stream of streams)stream.write(`event: ${event}\ndata: ${JSON.stringify(value)}\n\n`);};
 const server=createServer(async(req,res)=>{try{
  const url=new URL(req.url,'http://localhost');const json=(body,status=200)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(body));};
  if(url.pathname==='/api/runtime/v1/urgent/events'){opens++;streams.add(res);res.writeHead(200,{'content-type':'text/event-stream','cache-control':'no-store'});res.write('event: urgent.status\ndata: {"state":"connected","replay":true}\n\n');res.on('close',()=>streams.delete(res));return;}
  if(url.pathname==='/api/runtime/v1/urgent'){
   if(req.method==='GET'){const value=snapshot();if(delayRead){delayRead(()=>json(value));delayRead=null;return;}json(value);return;}
   let raw='';for await(const part of req)raw+=part;const body=JSON.parse(raw);requests.push(body);
   if(body.operation==='receipt'){const d=state.deliveries.find(d=>d.id===body.deliveryId);if(d&&body.stage==='endpointAccepted'){d.stage=d.modality==='text'?'completed':'delivered';d.endpointAcceptedAt=new Date().toISOString();d.revision++;}json({accepted:true,humanAcknowledged:false});return;}
   const ack=body.action==='acknowledge',d=ack?state.deliveries.find(d=>d.id===body.deliveryId):null;
   if(body.expectedRevision!==(ack?d?.revision:state.settings.revision)){json({message:'Settings or delivery changed. Refresh and retry.'},409);return;}
   if(body.operation==='configure'){const {operation,expectedRevision,...settings}=body;state.settings={...settings,revision:expectedRevision+1};}
   if(body.action==='disable'){state.settings.rules.forEach(r=>{r.enabled=false;r.bypassQuietHours=false;});state.settings.snoozedUntil=null;state.settings.revision++;}
   if(body.action==='snooze'){state.settings.snoozedUntil=body.until;state.settings.revision++;}
   if(ack){d.acknowledgedAt=new Date().toISOString();d.revision++;}else for(const d of state.deliveries)emit('urgent.cancel',{id:d.id,reason:'settings_changed'});
   json(snapshot());return;
  }
  if(url.pathname==='/api/runtime/v1/session-context'){json({revision:1,endpoint:{endpointId:'fixture:endpoint',privacyClass:'personal',inputModalities:['text','audio'],outputModalities:['text','audio']},runtimeSelfContext:{audienceScope:'authenticatedSession'}});return;}
  if(url.pathname==='/api/runtime/v1/messages'){res.writeHead(200,{'content-type':'text/event-stream'});res.write('event: message.delta\ndata: {"text":"Synthetic pending reply"}\n\n');return;}
  if(url.pathname.endsWith('/initiative/v1')){json({records:[],explanations:[]});return;}
  if(url.pathname.endsWith('/acknowledgments')){json({entries:[]});return;}
  const stubs=room?{'automatic-memory.js':'export const installAutomaticMemory=()=>({refresh(){}});','incidents.js':'export const installIncidentReview=()=>{};','presentation.js':'export const installPresentation=()=>({state(){},settle(){},clear(){},refresh(){},acceptsSpeech(){return false;}});','acknowledgments.js':'export class AcknowledgmentCache {clear(){} stop(){} async refresh(){} }'}:{};
  const name=url.pathname.slice(1);if(['urgent-attention.js','urgent-away.js','conversation-output.js','conversation-room.js','conversation-capture.js','speech-gate.js','styles.css',...Object.keys(stubs)].includes(name)){res.writeHead(200,{'content-type':name.endsWith('.css')?'text/css':'text/javascript'});res.end(stubs[name]??await readFile(new URL('../'+name,import.meta.url),'utf8'));return;}
  res.writeHead(200,{'content-type':'text/html'});res.end('<!doctype html><html lang="en" data-audience-protected="false"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/styles.css"><title>Synthetic urgent attention check</title><main class="shell card"></main></html>');
 }catch(error){errors.push(error.message);res.writeHead(500);res.end();}});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;
 t.after(async()=>{for(const stream of streams)stream.end();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));assert.deepEqual(errors,[]);});
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-background-networking','--disable-component-update','--disable-sync']});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1440,height:1100}}),pageErrors=[];page.setDefaultTimeout(7000);page.on('pageerror',e=>pageErrors.push(e.message));
 await page.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort());
 await page.addInitScript(()=>{
  window.log=[];window.sources=[];window.sockets=[];window.captureCalls=0;window.prepareGate=null;window.scopeValue={assistantId:'fixture:assistant',principalId:'fixture:owner',sessionId:'fixture:session',relationshipId:null};window.lifestreamAuth={mode:'local-password',session:{sessionId:'fixture:session',principalId:'fixture:owner',csrfToken:'synthetic-csrf'},ready:Promise.resolve()};
  navigator.mediaDevices.getUserMedia=async()=>{window.captureCalls++;throw Error('No microphone use in urgent attention');};
  window.AudioContext=class extends EventTarget{constructor(){super();this.state='suspended';this.currentTime=0;this.destination={};}async resume(){window.log.push(['resume',navigator.userActivation.isActive]);this.state='running';}async close(){this.state='closed';}createBuffer(_n,length,rate){return {duration:length/rate,getChannelData:()=>new Float32Array(length)};}createBufferSource(){const source=new EventTarget();source.connect=()=>{};source.disconnect=()=>{};source.start=()=>window.log.push(['audio-start']);source.stop=()=>window.log.push(['audio-stop']);window.sources.push(source);return source;}};
  window.WebSocket=class extends EventTarget{static OPEN=1;constructor(){super();window.sockets.push(this);this.readyState=0;queueMicrotask(()=>{this.readyState=1;this.dispatchEvent(new Event('open'));});}send(value){window.log.push(['ws-send',JSON.parse(value)]);}close(){this.readyState=3;this.dispatchEvent(new Event('close'));}};
 });
 await page.goto(base+'/#conversation');
 await page.evaluate(async room=>{
  const api=async(path,options)=>{const response=await fetch(path,options);const value=await response.json();if(!response.ok)throw Error(value.message||'Synthetic request rejected');return value;};
  if(room){const {installConversationRoom}=await import('/conversation-room.js');installConversationRoom({anchor:document.querySelector('main'),api,context:()=>({assistantId:window.scopeValue.assistantId,displayName:'Synthetic Assistant',relationship:null})});return;}
  const {ConversationOutput}=await import('/conversation-output.js'),{installUrgentAttention}=await import('/urgent-attention.js');let urgent;
  const output=window.output=new ConversationOutput({onState:()=>{},onStopped:trace=>urgent?.stopped(trace),onComplete:trace=>urgent?.completed(trace),onClosed:()=>urgent?.audioClosed()});
  window.urgent=urgent=installUrgentAttention({anchor:document.querySelector('main'),api,scope:()=>window.scopeValue,output,prepareOutput:async mode=>{if(mode==='speech'&&!output.connected)await output.connect();await api('/api/runtime/v1/session-context');},stopCurrent:async()=>{window.log.push(['stop-current']);output.stop();if(window.prepareGate)await new Promise(resolve=>{window.finishPrepare=resolve;});}});
 },room);
 t.after(()=>assert.deepEqual(pageErrors,[]));
 const prepare=(id='fixture:alert',modality=state.settings.modality)=>{const value={id,receiptToken:'synthetic-receipt-'+id,modality,expiresAt:until()};emit('urgent.prepare',value);return value;};
 const deliver=value=>{const d={...value,interactionId:value.id,text:'Simulation. Critical alert: synthetic device condition.',sourceRef:bindings[0].sourceRef,eventClass:bindings[0].eventClass,conditionRef:'fixture:condition',urgency:'critical'};state.deliveries.unshift({...d,revision:1,stage:'started',endpointAcceptedAt:null,playbackCompletedAt:null,speechDisposition:d.modality==='speech'?'speaking':'notRequested',expressionDisposition:'degraded',degradedDimensions:['renderer'],acknowledgedAt:null});emit('urgent.delivery',d);return d;};
 const start=async(mode='text')=>{await page.locator('[data-urgent-refresh]').click();await page.locator('[data-urgent-enabled]').first().check();await page.locator('[data-urgent-modality]').selectOption(mode);await page.locator('[data-urgent-save]').click();await page.locator('[data-urgent-listen]').click();await wait(()=>streams.size===1);};
 return {page,state,requests,emit,prepare,deliver,start,streams,opens:()=>opens,delayRead:fn=>{delayRead=fn;}};
}

test('urgent controls default off, preserve edits, save per-class bypass, quiet hours, snooze and disable',{skip:!enabled},async t=>{
 const f=await fixture(t),{page,state}=f;assert.equal(await page.locator('[data-urgent-listen]').isEnabled(),false);await page.locator('[data-urgent-refresh]').click();assert.equal(await page.locator('[data-urgent-enabled]:checked').count(),0);assert.equal(f.opens(),0);
 await page.locator('[data-urgent-enabled]').first().check();await page.locator('[data-urgent-bypass]').first().check();await page.locator('[data-urgent-refresh]').click();assert.equal(await page.locator('[data-urgent-enabled]').first().isChecked(),true);assert.equal(await page.locator('[data-urgent-listen]').isEnabled(),false);
 await page.locator('[data-urgent-quiet]').check();await page.locator('[data-urgent-start-time]').fill('23:30');await page.locator('[data-urgent-end-time]').fill('06:15');await page.locator('[data-urgent-zone]').fill('America/Chicago');await page.locator('[data-urgent-save]').click();await wait(()=>state.settings.revision===1);assert.deepEqual(state.settings.quietHours,{timeZone:'America/Chicago',startMinute:1410,endMinute:375});assert.equal(state.settings.rules[0].bypassQuietHours,true);assert.equal(state.settings.rules[1].enabled,false);assert.equal(f.opens(),0);
 await page.locator('[data-urgent-listen]').click();await wait(()=>f.streams.size===1);await page.locator('[data-urgent-enabled]').nth(1).check();f.emit('urgent.status',{state:'connected',replay:true});assert.equal(await page.locator('[data-urgent-enabled]').nth(1).isChecked(),true);await page.locator('[data-urgent-stop]').click();await wait(()=>f.streams.size===0);
 await page.locator('[data-urgent-minutes]').selectOption('60');await page.locator('[data-urgent-snooze]').click();await wait(()=>state.settings.revision===2);assert.ok(Date.parse(state.settings.snoozedUntil)>Date.now()+3500000);await page.locator('[data-urgent-disable]').click();await wait(()=>state.settings.revision===3);assert.ok(state.settings.rules.every(r=>!r.enabled&&!r.bypassQuietHours));assert.equal(await page.locator('[data-urgent-listen]').isEnabled(),false);assert.equal(await page.evaluate(()=>captureCalls),0);
});

test('urgent text prepares before delivery, uses fresh Human acknowledgment revision, never replays metadata and clears cancellation',{skip:!enabled},async t=>{
 const f=await fixture(t),{page}=f;await f.start();const value=f.prepare();await wait(()=>f.requests.some(r=>r.stage==='ready'));assert.deepEqual(await page.evaluate(()=>log.filter(x=>x[0]==='stop-current')),[['stop-current']]);f.deliver(value);await page.locator('[data-urgent-ack]').waitFor();assert.match(await page.locator('[data-urgent-current]').textContent(),/Simulation/);assert.equal(f.requests.some(r=>r.action==='acknowledge'),false);
 await page.locator('[data-urgent-enabled]').nth(1).check();f.state.deliveries[0].revision=9;await page.locator('[data-urgent-ack]').click();await wait(()=>f.requests.some(r=>r.action==='acknowledge'));assert.equal(f.requests.find(r=>r.action==='acknowledge').expectedRevision,9);assert.equal(await page.locator('[data-urgent-enabled]').nth(1).isChecked(),true,'Human acknowledgment must preserve unsaved policy edits');await page.locator('[data-urgent-refresh]').click();assert.equal(await page.locator('[data-urgent-current] article').count(),1);f.emit('urgent.cancel',{id:value.id,reason:'condition_resolved'});await page.waitForFunction(()=>document.querySelector('[data-urgent-current]').children.length===0);await page.locator('[data-urgent-refresh]').click();assert.equal(await page.locator('[data-urgent-current] article').count(),0);
});

test('urgent speech uses the existing output, resumes under a click, accepts exact audio metadata and stops on privacy',{skip:!enabled},async t=>{
 const f=await fixture(t),{page}=f;await f.start('speech');assert.deepEqual(await page.evaluate(()=>log.find(x=>x[0]==='resume')),['resume',true]);const value=f.prepare();await wait(()=>f.requests.some(r=>r.stage==='ready'));assert.equal(await page.evaluate(()=>output.waiting),true);const delivery=f.deliver(value);
 await page.evaluate(d=>{output.receive({type:'response',interactionTraceId:d.id,event:{payload:{type:'textDelta',text:d.text}}});output.receive({type:'audio',interactionTraceId:d.id,chunk:{frame:{format:{encoding:'pcm_s16le',sampleRateHz:48000,channels:1},sequence:0,sampleOffset:0,sampleCount:480,dataBase64:btoa('\0'.repeat(960))}}});},delivery);
 await wait(()=>f.requests.some(r=>r.stage==='endpointAccepted'));assert.equal(await page.evaluate(()=>sources.length),1);await page.evaluate(()=>{document.documentElement.dataset.audienceProtected='true';dispatchEvent(new CustomEvent('lifestream-audience',{detail:{privateAllowed:false}}));});await wait(()=>f.streams.size===0);assert.equal(await page.locator('[data-urgent-current]').textContent(),'');assert.equal(await page.locator('[data-urgent-recent]').textContent(),'');assert.ok(await page.evaluate(()=>log.some(x=>x[0]==='audio-stop')));assert.equal(await page.evaluate(()=>captureCalls),0);await page.evaluate(()=>{document.documentElement.dataset.audienceProtected='false';dispatchEvent(new CustomEvent('lifestream-audience',{detail:{privateAllowed:true}}));});assert.equal(f.opens(),1);
});

test('urgent stream loss, navigation, session, identity, visibility and late reads all require explicit restart',{skip:!enabled},async t=>{
 const f=await fixture(t),{page}=f;await f.start();for(const stream of f.streams)stream.end();await page.waitForFunction(()=>document.querySelector('[data-urgent-status]').textContent.includes('Listening stopped:'));await wait(()=>f.streams.size===0);assert.equal(f.opens(),1);
 for(const action of ['session','assistant','relationship','auth','navigation','visibility']){
  await page.locator('[data-urgent-listen]').click();await wait(()=>f.streams.size===1);await page.evaluate(action=>{if(action==='navigation')location.hash='#account';else if(action==='visibility'){Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));}else dispatchEvent(new Event('lifestream-'+(action==='session'?'session-context':action)));},action);await wait(()=>f.streams.size===0);assert.equal(await page.locator('[data-urgent-recent]').textContent(),'');await page.evaluate(()=>{location.hash='#conversation';Object.defineProperty(document,'hidden',{configurable:true,value:false});});await page.locator('[data-urgent-refresh]').click();
 }
 await page.waitForFunction(()=>!document.querySelector('[data-urgent-refresh]').disabled);let release;f.delayRead(resolve=>{release=resolve;});await page.locator('[data-urgent-refresh]').click();await wait(()=>!!release);await page.evaluate(()=>dispatchEvent(new Event('lifestream-auth')));release();await page.waitForFunction(()=>!document.querySelector('[data-urgent-refresh]').disabled);assert.equal(await page.locator('[data-urgent-summary]').textContent(),'No local settings loaded. Remote delivery has separate settings above.');
});

test('urgent cancellation during preparation and forged delivery cannot play or survive reconnect',{skip:!enabled},async t=>{
 const f=await fixture(t),{page}=f;await f.start('speech');await page.evaluate(()=>{prepareGate=true;});const value=f.prepare();await page.waitForFunction(()=>!!window.finishPrepare);f.emit('urgent.cancel',{id:value.id,reason:'resolved'});await page.waitForFunction(()=>document.querySelector('[data-urgent-status]').textContent.includes('cancelled'));await page.evaluate(()=>finishPrepare());assert.equal(f.requests.some(r=>r.stage==='ready'),false);assert.equal(await page.evaluate(()=>output.waiting),false);
 f.emit('urgent.delivery',{...value,interactionId:value.id,text:'Unexpected content'});await page.waitForFunction(()=>document.querySelector('[data-urgent-status]').textContent.includes('Listening stopped:'));assert.equal(await page.locator('[data-urgent-current]').textContent(),'');assert.equal(await page.evaluate(()=>sources.length),0);
});

test('source cancellation during speech metadata matching clears the alert without disconnecting or playing',{skip:!enabled},async t=>{
 const f=await fixture(t),{page}=f;await f.start('speech');const value=f.prepare();await wait(()=>f.requests.some(r=>r.stage==='ready'));f.deliver(value);await page.waitForFunction(()=>!!output.binding);f.emit('urgent.cancel',{id:value.id,reason:'source_resolved'});await page.waitForFunction(()=>!output.binding&&!output.waiting&&document.querySelector('[data-urgent-current]').children.length===0);assert.equal(f.streams.size,1);assert.equal(await page.evaluate(()=>sources.length),0);const next=f.prepare('fixture:next');await wait(()=>f.requests.some(r=>r.deliveryId===next.id&&r.stage==='ready'));assert.equal(await page.evaluate(()=>output.waiting),true);
});

test('urgent settings conflicts refresh without retry; invalid quiet times and unavailable hosts cannot enable listening',{skip:!enabled},async t=>{
 const f=await fixture(t),{page}=f;await page.locator('[data-urgent-refresh]').click();await page.locator('[data-urgent-enabled]').first().check();f.state.settings.revision=4;await page.locator('[data-urgent-save]').click();await page.waitForFunction(()=>document.querySelector('[data-urgent-status]').textContent.includes('Refresh and retry'));assert.equal(f.requests.filter(r=>r.operation==='configure').length,1);assert.equal(await page.locator('[data-urgent-enabled]').first().isChecked(),false);
 await page.locator('[data-urgent-enabled]').first().check();await page.locator('[data-urgent-quiet]').check();await page.locator('[data-urgent-zone]').fill('Not/AZone');await page.locator('[data-urgent-save]').click();await page.waitForFunction(()=>document.querySelector('[data-urgent-status]').textContent.includes('valid quiet-hours time zone'));assert.equal(f.requests.filter(r=>r.operation==='configure').length,1);await page.locator('[data-urgent-zone]').fill('UTC');await page.locator('[data-urgent-end-time]').fill('22:00');await page.locator('[data-urgent-save]').click();await page.waitForFunction(()=>document.querySelector('[data-urgent-status]').textContent.includes('different start and end'));assert.equal(f.requests.filter(r=>r.operation==='configure').length,1);
 f.state.configured=false;await page.locator('[data-urgent-refresh]').click();await page.waitForFunction(()=>document.querySelector('[data-urgent-status]').textContent.includes('not configured'));assert.equal(await page.locator('[data-urgent-listen]').isEnabled(),false);assert.equal(f.opens(),0);
});

test('urgent playback completion and expiry remain distinct from Human acknowledgment',{skip:!enabled},async t=>{
 const f=await fixture(t),{page}=f;await f.start('speech');const value=f.prepare();await wait(()=>f.requests.some(r=>r.stage==='ready'));const d=f.deliver(value);await page.evaluate(d=>{output.receive({type:'response',interactionTraceId:d.id,event:{payload:{type:'textDelta',text:d.text}}});output.receive({type:'audio',interactionTraceId:d.id,chunk:{frame:{format:{encoding:'pcm_s16le',sampleRateHz:48000,channels:1},sequence:0,sampleOffset:0,sampleCount:480,dataBase64:btoa('\0'.repeat(960))}}});output.receive({type:'response',interactionTraceId:d.id,event:{payload:{type:'terminal',state:'completed'}}});},d);await wait(()=>f.requests.some(r=>r.stage==='endpointAccepted'));await page.evaluate(()=>sources[0].dispatchEvent(new Event('ended')));await page.waitForFunction(()=>document.querySelector('[data-urgent-current]').textContent.includes('Playback finished locally'));assert.equal(f.requests.some(r=>r.action==='acknowledge'),false);f.emit('urgent.completed',{id:d.id,playbackCompleted:true,humanAcknowledged:false});await page.waitForFunction(()=>document.querySelector('[data-urgent-current]').textContent.includes('Playback completion reported'));await page.locator('[data-urgent-stop]').click();
 await page.locator('[data-urgent-modality]').selectOption('text');await page.locator('[data-urgent-save]').click();await page.locator('[data-urgent-listen]').click();await wait(()=>f.streams.size===1);const expiring={id:'fixture:expiring',receiptToken:'expiry-receipt',modality:'text',expiresAt:new Date(Date.now()+1000).toISOString()};f.emit('urgent.prepare',expiring);await wait(()=>f.requests.some(r=>r.deliveryId===expiring.id&&r.stage==='ready'));f.deliver(expiring);await page.locator('[data-urgent-current] article').waitFor();await page.waitForFunction(()=>document.querySelector('[data-urgent-current]').children.length===0);await wait(()=>f.requests.some(r=>r.deliveryId===expiring.id&&r.stage==='stopped'));assert.equal(f.requests.some(r=>r.action==='acknowledge'),false);
});

test('room Stop response and urgent preparation abort the existing typed response and clear urgent output',{skip:!enabled},async t=>{
 const f=await fixture(t,{room:true}),{page}=f;await page.locator('#room-message').fill('Synthetic interrupted reply');await page.locator('#room-send').click();await page.waitForFunction(()=>document.querySelector('.room-turn.assistant')?.textContent.includes('Synthetic pending reply'));await f.start();const value=f.prepare();await wait(()=>f.requests.some(r=>r.stage==='ready'));await page.waitForFunction(()=>document.querySelector('.room-turn.assistant')?.textContent.includes('Stopped'));f.deliver(value);await page.locator('#room-turns [data-urgent-alert]').waitFor();await page.locator('#room-stop').click();await wait(()=>f.streams.size===0);assert.equal(await page.locator('#room-turns [data-urgent-alert]').count(),0);assert.equal(await page.evaluate(()=>captureCalls),0);
});

test('real room capture shutdown preserves the shared urgent speech connection until the user stops',{skip:!enabled},async t=>{
 const f=await fixture(t,{room:true}),{page}=f;await f.start('speech');const value=f.prepare();await wait(()=>f.requests.some(r=>r.stage==='ready'));assert.equal(f.streams.size,1);const d=f.deliver(value);await page.evaluate(d=>{const send=message=>sockets[0].dispatchEvent(new MessageEvent('message',{data:JSON.stringify(message)}));send({type:'response',interactionTraceId:d.id,event:{payload:{type:'textDelta',text:d.text}}});send({type:'audio',interactionTraceId:d.id,chunk:{frame:{format:{encoding:'pcm_s16le',sampleRateHz:48000,channels:1},sequence:0,sampleOffset:0,sampleCount:480,dataBase64:btoa('\0'.repeat(960))}}});},d);await wait(()=>f.requests.some(r=>r.stage==='endpointAccepted'));assert.equal(await page.evaluate(()=>sockets.length),1);assert.equal(await page.evaluate(()=>sources.length),1);await page.locator('#room-turns [data-urgent-alert]').waitFor();await page.locator('#room-stop').click();await wait(()=>f.streams.size===0);assert.equal(await page.locator('#room-turns [data-urgent-alert]').count(),0);assert.equal(await page.evaluate(()=>captureCalls),0);
});

test('urgent controls and metadata remain readable on desktop and mobile',{skip:!enabled},async t=>{
 const f=await fixture(t),{page}=f;f.state.conditions.push({condition:{eventClass:'criticalDevice',status:'open',basis:'synthetic',severity:'critical',qualification:'qualified',freshness:'fresh',conditionRef:'fixture:condition',revision:2,sourceRef:'fixture:source-a',freshUntil:until(),confidence:.98,evidenceRefs:['fixture:incident-01','<untrusted-reference>']},reasons:[]});await f.start();const value=f.prepare();await wait(()=>f.requests.some(r=>r.stage==='ready'));f.deliver(value);await page.locator('[data-urgent-ack]').waitFor();await page.getByText('Evidence references',{exact:true}).click();assert.equal(await page.locator('[data-urgent-recent] ul li').last().textContent(),'<untrusted-reference>');assert.equal(await page.locator('[data-urgent-recent] a,[data-urgent-recent] untrusted-reference').count(),0);await page.locator('[data-urgent-quiet]').check();await page.locator('[data-urgent-zone]').fill('America/Chicago');
 for(const [name,width,height] of [['desktop',1440,1100],['mobile',390,844]]){await page.setViewportSize({width,height});await page.evaluate(()=>window.scrollTo(0,0));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${name} horizontal overflow`);for(const selector of ['save','refresh','listen','stop','snooze','disable','minutes','modality','quiet','zone','start-time','end-time','ack'])assert.equal(await page.locator(`[data-urgent-${selector}]`).first().isVisible(),true,`${name} ${selector}`);
  if(process.env.URGENT_SCREENSHOT_DIR){await mkdir(process.env.URGENT_SCREENSHOT_DIR,{recursive:true});const path=join(process.env.URGENT_SCREENSHOT_DIR,`urgent-${name}.png`);await writeFile(path,await page.screenshot({fullPage:true}),{flag:'wx'});}
 }
});
