import test from 'node:test';
import assert from 'node:assert/strict';
import {benchmarkGameConversation,type GamePerformanceEnvironment,type GamePerformanceTrial} from '../src/benchmark.ts';
const environment:GamePerformanceEnvironment={hardware:'fixture-hardware',os:'fixture-os',platform:'linux',powerMode:'fixture',network:'fixture-offline',sourceRevision:'fixture-source',speechProviderRevision:'fixture-speech',gameProviderRevision:'fixture-game',configurationDigest:'a'.repeat(64),gamePinsDigest:'b'.repeat(64),clockMappingRevision:'fixture-monotonic',evidence:'fixture',seed:94,nominalFramesPerSecond:60,declaredConditions:['disabled','enabled','contended','hung']};
function trial(i:number):GamePerformanceTrial{return {pairId:'p'+i,temperature:'warm',status:'completed',turnCommittedAt:10000,preparedStartedAt:10001,preparedCompletedAt:10010,firstAudioAt:10600,firstAudioKind:'requestedSpeech',bargeInDetectedAt:11000,audibleStoppedAt:11100,underruns:0,duplicateAudioOwners:0,optionalWork:[],resources:{residentMemoryMiB:1000,availableMemoryMiB:2000,gpuUsedMiB:1000,gpuCapacityMiB:4000,providerQueueDepth:0,oomEvents:0,memoryPressure:'normal'},presentation:{displayAvailable:true,viewerConnected:false,normalSpeedConfigured:true,emulatorOnlyBaselineRef:'fixture:emulator-only',emulatedFrames:600,elapsedMs:10000,displayFrameIntervalP95Ms:20,controllerResponseMs:30,decisionsCompleted:2,idleMs:4000,deliberatePauseMs:0}};}
const runs=(n=200)=>Object.fromEntries(environment.declaredConditions.map(c=>[c,Array.from({length:n},(_,i)=>trial(i))]));
const gate=(r:ReturnType<typeof benchmarkGameConversation>,condition:string,metric:string)=>r.gates.find(g=>g.condition===condition&&g.metric===metric)!;
test('200 supplied paired speech trials score absolute objectives independently of scripted game smoothness/native competence',()=>{const input=runs(),before=JSON.stringify(input),r=benchmarkGameConversation(environment,input);assert.equal(r.status,'passedMeasuredSpeechObjectives');assert.equal(r.qualification,'fixtureOnly');assert.equal(r.claimsRuntimeAcceptance,false);assert.equal(r.claimsNativePerformance,false);assert.equal(r.claimsGameCompetence,false);assert.equal(r.comparisons.length,3);assert.ok(r.comparisons.every(c=>c.completedSpeechPairs===200&&c.p95Delta===0&&c.uncertainty?.resamples===500));assert.equal(JSON.stringify(input),before);input.enabled![0]!.status='failed';assert.equal(r.raw.enabled![0]!.status,'completed');});
test('missing/mismatched pairs and cold successes cannot fill 200 warm completed requested-speech observations',()=>{const input=runs(199);for(const c of environment.declaredConditions)input[c]!.push({...trial(999),temperature:'cold'});let r=benchmarkGameConversation(environment,input);assert.equal(r.status,'incompleteEvidence');assert.equal(gate(r,'enabled','pairedSpeechCoverage').status,'unverified');const full=runs();full.enabled![0]!.pairId='other';r=benchmarkGameConversation(environment,full);assert.equal(r.comparisons[0]!.completedSpeechPairs,199);assert.equal(r.comparisons[0]!.uncertainty,null);});
test('200 successful pairs never hide failed/timeout/cancelled attempts or cold continuity failures',()=>{const input=runs(203);input.enabled![0]!.status='failed';input.enabled![1]!.status='timedOut';input.enabled![2]!.status='cancelled';input.enabled!.push({...trial(999),temperature:'cold',duplicateAudioOwners:1,underruns:2});const r=benchmarkGameConversation(environment,input),report=r.reports.enabled as any;assert.equal(r.status,'failedObjectives');assert.equal(report.completed,200);assert.equal(report.failed,1);assert.equal(report.timedOut,1);assert.equal(report.cancelled,1);assert.equal(report.cold.attempts,1);assert.equal(r.comparisons[0]!.completedSpeechPairs,200);assert.equal(gate(r,'enabled','pairedSpeechCoverage').status,'unverified');assert.equal(gate(r,'enabled','audioContinuity').status,'fail');assert.equal(r.raw.enabled!.length,204);});
test('acknowledgments and absent audio cannot become requested first spoken word or complete pairs',()=>{const input=runs();input.hung![0]!.firstAudioKind='acknowledgment';input.hung![0]!.bargeInDetectedAt=null;input.hung![0]!.audibleStoppedAt=null;input.hung![1]!.firstAudioKind='none';input.hung![1]!.firstAudioAt=null;input.hung![1]!.bargeInDetectedAt=null;input.hung![1]!.audibleStoppedAt=null;const r=benchmarkGameConversation(environment,input);assert.equal(gate(r,'hung','firstSpokenWord').status,'unverified');assert.equal(r.comparisons[2]!.completedSpeechPairs,198);});
test('absolute onset/prepared/stop failure is independent of equal paired latency',()=>{const input=runs();for(const rows of Object.values(input))for(const t of rows){t.preparedCompletedAt=10050;t.firstAudioAt=11600;t.bargeInDetectedAt=12000;t.audibleStoppedAt=12300;}const r=benchmarkGameConversation(environment,input);assert.equal(gate(r,'enabled','pairedSpeechCoverage').status,'pass');for(const metric of ['preparedRead','firstSpokenWord','audibleStop'])assert.equal(gate(r,'enabled',metric).status,'fail');assert.equal(r.status,'failedObjectives');});
test('presentation, viewer disconnect, unsmooth speed and decision progress stay separate from fast speech',()=>{const input=runs();input.enabled![0]!.presentation.displayAvailable=false;input.enabled![1]!.presentation.normalSpeedConfigured=false;input.enabled![2]!.presentation.emulatorOnlyBaselineRef=null;input.enabled![3]!.presentation.emulatedFrames=60;input.enabled![4]!.presentation.decisionsCompleted=0;const r=benchmarkGameConversation(environment,input),p=(r.reports.enabled as any).presentation;assert.equal(r.status,'passedMeasuredSpeechObjectives');assert.equal(p.speedRatio.minimum,.1);assert.equal(p.displayUnavailable,1);assert.equal(p.normalSpeedNotConfigured,1);assert.equal(p.baselineMissing,1);assert.equal(p.viewerDisconnectedWithDisplay,199);assert.equal(p.decisionsCompleted,398);assert.equal(r.claimsNativePerformance,false);});
test('resource headroom/pressure/OOM/queue data are retained without an invented capacity acceptance claim',()=>{const input=runs();input.contended![0]!.resources.availableMemoryMiB=null;input.contended![1]!.resources.gpuUsedMiB=5000;input.contended![2]!.resources.oomEvents=1;input.contended![2]!.resources.memoryPressure='critical';input.contended![3]!.resources.providerQueueDepth=10;const r=benchmarkGameConversation(environment,input),res=(r.reports.contended as any).resources;assert.equal(res.availableMemoryMiB.count,199);assert.equal(res.gpuHeadroomMiB.minimum,-1000);assert.equal(res.oomEvents,1);assert.equal(res.memoryPressure.critical,1);assert.equal(res.providerQueueDepth.maximum,10);assert.equal(r.claimsNativePerformance,false);});
test('declared exact conditions, identity/artifact pins and closed bounded trials are mandatory',()=>{for(const mutate of [(v:any)=>v.enabled[0].pairId='p1',(v:any)=>v.enabled[0].firstAudioAt=NaN,(v:any)=>v.enabled[0].preparedCompletedAt=1,(v:any)=>v.enabled[0].resources.providerQueueDepth=.5,(v:any)=>v.enabled[0].presentation.emulatedFrames=.5,(v:any)=>v.enabled[0].presentation.elapsedMs=0,(v:any)=>v.enabled[0].presentation.idleMs=10001,(v:any)=>v.enabled[0].rawSave='PRIVATE_SAVE']){const input=runs();mutate(input);assert.throws(()=>benchmarkGameConversation(environment,input));}assert.throws(()=>benchmarkGameConversation({...environment,gamePinsDigest:'not-pinned'},runs()));assert.throws(()=>benchmarkGameConversation({...environment,declaredConditions:['enabled','disabled']},runs()));assert.throws(()=>benchmarkGameConversation(environment,{...runs(),undeclared:[]}));});
test('empty/cancelled-only and missing optional measurements remain explicit and cannot qualify speech',()=>{assert.equal(benchmarkGameConversation(environment,runs(0)).status,'incompleteEvidence');const input=runs();for(const t of input.hung!){t.status='cancelled';t.presentation.emulatedFrames=null;t.presentation.elapsedMs=null;t.resources.gpuUsedMiB=null;t.resources.gpuCapacityMiB=null;}const r=benchmarkGameConversation(environment,input);assert.equal(gate(r,'hung','foregroundCompletion').status,'unverified');assert.equal((r.reports.hung as any).metrics.firstSpokenWord,null);assert.equal((r.reports.hung as any).presentation.speedRatio,null);});
test('hostile getters/proxies/cycles and raw bytes cannot execute while scoring',()=>{let calls=0;const input=runs(),getter={...input};Object.defineProperty(getter,'enabled',{enumerable:true,get(){calls++;return input.enabled;}});assert.throws(()=>benchmarkGameConversation(environment,getter));assert.equal(calls,0);const cyclic:any={...input};cyclic.self=cyclic;for(const value of [new Proxy(input,{}),cyclic,{...input,raw:Buffer.from('PRIVATE')},{...input,enabled:Array(5001).fill(trial(0))}])assert.throws(()=>benchmarkGameConversation(environment,value));});

test('prototype-like pressure identities and nonfinite derived native speed cannot create misleading reports',()=>{
 for(const name of ['__proto__','constructor','prototype'])assert.throws(()=>benchmarkGameConversation({...environment,declaredConditions:['disabled',name]},Object.fromEntries([['disabled',[]],[name,[]]])));
 const input=runs();input.enabled![0]!.presentation.elapsedMs=Number.MIN_VALUE;assert.throws(()=>benchmarkGameConversation(environment,input));
});

test('optional game planning/perception/checkpoint/reflection drops and failures stay separate from successful foreground speech',()=>{const input=runs();input.hung!.forEach((t,i)=>{t.optionalWork=[{workId:'work'+i,kind:i%2?'perception':'planning',status:i%2?'timedOut':'deferred',admitted:i%2===1,startedAt:i%2?9000:null,completedAt:null}];});input.hung!.push({...trial(999),temperature:'cold',optionalWork:[{workId:'cold-work',kind:'checkpoint',status:'failed',admitted:true,startedAt:9000,completedAt:null}]});const r=benchmarkGameConversation(environment,input),report=r.reports.hung as any;assert.equal(r.status,'passedMeasuredSpeechObjectives');assert.equal(report.optionalWork.attempts,200);assert.equal(report.optionalWork.outcomes.timedOut,100);assert.equal(report.optionalWork.outcomes.deferred,100);assert.equal(report.optionalWork.completedLatencyMs,null);assert.equal(report.cold.optionalWork.outcomes.failed,1);const invalid=runs();invalid.enabled![0]!.optionalWork=[{workId:'denied',kind:'reflection',status:'completed',admitted:false,startedAt:1,completedAt:2}];assert.throws(()=>benchmarkGameConversation(environment,invalid));});
