import test from 'node:test';
import assert from 'node:assert/strict';
import {benchmarkVisualConversation,visualPerformanceConditions,type VisualPerformanceCondition,type VisualPerformanceEnvironment,type VisualPerformanceTrial} from '../src/benchmark.ts';

const environment:VisualPerformanceEnvironment={hardware:'fixture',os:'fixture',powerMode:'fixture',network:'fixture',sourceRevision:'source:1',speechProviderRevision:'speech:1',perceptionProviderRevision:'vision:1',configurationDigest:'a'.repeat(64),clockMappingRevision:'clock:1',evidence:'fixture',seed:42};
function trial(id:number,condition:VisualPerformanceCondition):VisualPerformanceTrial {return {pairId:`p${id}`,temperature:'warm',status:'completed',turnCommittedAt:10000,preparedStartedAt:10001,preparedCompletedAt:10010,firstAudioAt:condition==='disabled'?10600:10620,firstAudioKind:'requestedSpeech',bargeInDetectedAt:11000,audibleStoppedAt:11100,underruns:0,duplicateAudioOwners:0,visualBatches:condition==='disabled'?[]:[{batchId:`b${id}`,admitted:true,capturedAt:9000,usableAt:10000,outcome:'usable'}]};}
function runs(count=200){return Object.fromEntries(visualPerformanceConditions.map(condition=>[condition,Array.from({length:count},(_,i)=>trial(i,condition))])) as Record<VisualPerformanceCondition,VisualPerformanceTrial[]>;}
const gate=(r:ReturnType<typeof benchmarkVisualConversation>,condition:string,metric:string)=>r.gates.find(g=>g.condition===condition&&g.metric===metric)!;

test('unrestricted content cannot be smuggled into retained raw measurement metadata',()=>{for(const location of ['environment','runs','trial','batch']){const experiment=structuredClone(environment),input=runs(),target=location==='environment'?experiment:location==='runs'?input:location==='trial'?input.warm[0]!:input.warm[0]!.visualBatches[0]!;(target as any).unrestrictedText='must not persist';assert.throws(()=>benchmarkVisualConversation(experiment,input),/closed/);}});
test('admitted visual timeouts cannot be pooled out of capture latency qualification',()=>{const input=runs();input.warm[0]!.visualBatches=[{batchId:'timeout',admitted:true,capturedAt:9000,usableAt:null,outcome:'timedOut'}];const r=benchmarkVisualConversation(environment,input);assert.equal(r.reports.warm.visual.captureToUsable!.count,199);assert.equal(gate(r,'warm','captureToUsable').status,'unverified');assert.equal(r.reports.warm.visual.outcomes.timedOut,1);});
test('partial preparation and audible-stop telemetry remain incomplete rather than disappearing on validation',()=>{const input=runs();input.warm[0]!.status='timedOut';input.warm[0]!.preparedCompletedAt=null;input.warm[1]!.audibleStoppedAt=null;input.warm[2]!.preparedStartedAt=null;input.warm[3]!.bargeInDetectedAt=null;const r=benchmarkVisualConversation(environment,input);assert.equal(r.reports.warm.timedOut,1);assert.equal(r.reports.warm.metrics.preparedRead!.count,198);assert.equal(r.reports.warm.metrics.audibleStop!.count,197);assert.equal(gate(r,'warm','preparedRead').status,'unverified');assert.equal(gate(r,'warm','audibleStop').status,'unverified');assert.equal(r.raw.warm[1]!.audibleStoppedAt,null);});
test('cold ownership, underrun and foreground failures cannot hide behind passing warm latencies',()=>{const input=runs(),cold={...trial(999,'warm'),temperature:'cold' as const,duplicateAudioOwners:1,underruns:2,status:'failed' as const};input.warm.push(cold);const r=benchmarkVisualConversation(environment,input);assert.equal(r.reports.warm.duplicateAudioOwners,0);assert.equal(r.reports.warm.cold.duplicateAudioOwners,1);assert.equal(r.reports.warm.cold.underruns,2);assert.equal(r.reports.warm.cold.failed,1);assert.equal(gate(r,'warm','audioContinuity').status,'fail');assert.equal(gate(r,'warm','foregroundCompletion').status,'fail');assert.equal(gate(r,'warm','firstSpokenWord').status,'pass');assert.equal(r.status,'failedObjectives');});

test('paired visual scorer reports objectives but keeps fixture qualification separate',()=>{const input=runs(),r=benchmarkVisualConversation(environment,input);assert.equal(r.status,'passedMeasuredObjectives');assert.equal(r.qualification,'fixtureOnly');assert.equal(r.comparisons.length,5);assert.ok(r.comparisons.every(c=>c.completedSpeechPairs===200&&c.p95Delta===20));input.warm[0]!.pairId='changed';assert.equal(r.raw.warm[0]!.pairId,'p0');});
test('missing and mismatched pairs never qualify even when each condition has 200 fast samples',()=>{const a=benchmarkVisualConversation(environment,runs(199));assert.equal(a.status,'incompleteEvidence');const input=runs();input.warm[0]!.pairId='another';const b=benchmarkVisualConversation(environment,input);assert.equal(gate(b,'warm','pairedSpeechOverhead').status,'unverified');assert.equal(b.comparisons[0]!.completedSpeechPairs,199);assert.equal(b.comparisons[0]!.uncertainty,null);});
test('cold attempts cannot fill warm counts or dilute failed warm foreground turns',()=>{const input=runs(199);for(const c of visualPerformanceConditions)input[c].push({...trial(999,c),temperature:'cold'});const r=benchmarkVisualConversation(environment,input);assert.equal(r.status,'incompleteEvidence');assert.equal(r.reports.warm.cold.attempts,1);assert.equal(r.reports.warm.attempts,199);input.warm[0]!.status='timedOut';const failed=benchmarkVisualConversation(environment,input);assert.equal(failed.reports.warm.timedOut,1);assert.equal(gate(failed,'warm','foregroundCompletion').status,'fail');assert.equal(failed.raw.warm.length,200);});
test('all failed, cancelled and timeout attempts remain explicit with incomplete paired coverage',()=>{const input=runs(203);input.warm[0]!.status='failed';input.warm[1]!.status='timedOut';input.warm[2]!.status='cancelled';const r=benchmarkVisualConversation(environment,input);assert.equal(r.reports.warm.completed,200);assert.equal(r.reports.warm.failed,1);assert.equal(r.reports.warm.timedOut,1);assert.equal(r.reports.warm.cancelled,1);assert.equal(r.comparisons[0]!.completedSpeechPairs,200);assert.equal(gate(r,'warm','pairedSpeechOverhead').status,'unverified','200 successful pairs cannot erase 3 other attempts');});
test('acknowledgments and missing playback cannot satisfy first requested spoken word',()=>{const input=runs();input.warm[0]!.firstAudioKind='acknowledgment';input.warm[0]!.bargeInDetectedAt=null;input.warm[0]!.audibleStoppedAt=null;input.warm[1]!.firstAudioKind='none';input.warm[1]!.firstAudioAt=null;input.warm[1]!.bargeInDetectedAt=null;input.warm[1]!.audibleStoppedAt=null;const r=benchmarkVisualConversation(environment,input);assert.equal(r.reports.warm.metrics.firstSpokenWord!.count,198);assert.equal(gate(r,'warm','firstSpokenWord').status,'unverified');assert.equal(gate(r,'warm','pairedSpeechOverhead').status,'unverified');});
test('absolute speech, prepared-read, stop and continuity limits remain independent of incremental overhead',()=>{const input=runs();for(const c of visualPerformanceConditions)for(const t of input[c]){t.firstAudioAt=11600;t.bargeInDetectedAt=12000;t.audibleStoppedAt=12300;t.preparedCompletedAt=10050;}input.hung[0]!.underruns=1;input.hung[1]!.duplicateAudioOwners=1;const r=benchmarkVisualConversation(environment,input);assert.equal(gate(r,'warm','pairedSpeechOverhead').status,'pass');for(const metric of ['firstSpokenWord','preparedRead','audibleStop'])assert.equal(gate(r,'warm',metric).status,'fail');assert.equal(gate(r,'hung','audioContinuity').status,'fail');});
test('increased p95 overhead fails even below absolute response limits',()=>{const input=runs();for(const t of input.warm)t.firstAudioAt=10651;const r=benchmarkVisualConversation(environment,input);assert.equal(gate(r,'warm','firstSpokenWord').status,'pass');assert.equal(gate(r,'warm','pairedSpeechOverhead').status,'fail');});
test('optional visual deferral and failure counts stay distinct from successful foreground speech',()=>{const input=runs();const outcomes=['deferred','dropped','failed','timedOut','expired'] as const;input.hung.forEach((t,i)=>{t.visualBatches=[{batchId:`h${i}`,admitted:i%2===0,capturedAt:9000,usableAt:null,outcome:outcomes[i%5]!}];});const r=benchmarkVisualConversation(environment,input);assert.equal(gate(r,'hung','firstSpokenWord').status,'pass');assert.equal(gate(r,'hung','captureToUsable').status,'unverified');assert.equal(r.reports.hung.visual.attempts,200);assert.equal(r.reports.hung.visual.admitted,100);for(const outcome of outcomes)assert.equal(r.reports.hung.visual.outcomes[outcome],40);});
test('a single context past its six-second bound fails even when the p95 is fast',()=>{const input=runs();input.warm[0]!.visualBatches[0]!.usableAt=15000;const r=benchmarkVisualConversation(environment,input);assert.equal(gate(r,'warm','captureToUsable').status,'pass');assert.equal(gate(r,'warm','captureFreshness').status,'fail');assert.equal(r.reports.warm.visual.lateUsable,1);});
test('slower usable vision fails capture objective and cold latency stays separate',()=>{const input=runs();for(const t of input.sceneChanging)t.visualBatches[0]!.usableAt=12500;input.warm.push({...trial(999,'warm'),temperature:'cold',firstAudioAt:15000,bargeInDetectedAt:15500,audibleStoppedAt:15600});const r=benchmarkVisualConversation(environment,input);assert.equal(gate(r,'sceneChanging','captureToUsable').status,'fail');assert.equal(r.reports.warm.metrics.firstSpokenWord!.p95,620);assert.equal(r.reports.warm.cold.metrics.firstSpokenWord!.p95,5000);});
test('invalid identities, times, duplicate observations and disabled work are rejected',()=>{for(const mutate of [(r:ReturnType<typeof runs>)=>{r.warm[1]!.pairId='p0';},(r:ReturnType<typeof runs>)=>{r.warm[0]!.firstAudioAt=NaN;},(r:ReturnType<typeof runs>)=>{r.warm[0]!.preparedCompletedAt=9999;},(r:ReturnType<typeof runs>)=>{r.warm[1]!.visualBatches[0]!.batchId='b0';},(r:ReturnType<typeof runs>)=>{r.disabled[0]!.visualBatches=trial(0,'warm').visualBatches;},(r:ReturnType<typeof runs>)=>{r.warm[0]!.visualBatches[0]!.admitted=false;}]){const input=runs();mutate(input);assert.throws(()=>benchmarkVisualConversation(environment,input));}assert.throws(()=>benchmarkVisualConversation({...environment,configurationDigest:'not-pinned'},runs()));});
test('empty and cancelled-only experiments never qualify',()=>{assert.equal(benchmarkVisualConversation(environment,runs(0)).status,'incompleteEvidence');const input=runs();input.warm.forEach(t=>t.status='cancelled');const r=benchmarkVisualConversation(environment,input);assert.equal(gate(r,'warm','foregroundCompletion').status,'unverified');assert.equal(r.reports.warm.metrics.firstSpokenWord,null);});
test('cold visual failures and stale usable context remain reported separately without weakening freshness',()=>{const input=runs();const cold={...trial(1000,'warm'),temperature:'cold' as const};cold.visualBatches[0]!.usableAt=15001;input.warm.push(cold);const failed={...trial(1001,'warm'),temperature:'cold' as const};failed.visualBatches=[{batchId:'cold-timeout',admitted:true,capturedAt:9000,usableAt:null,outcome:'timedOut'}];input.warm.push(failed);const r=benchmarkVisualConversation(environment,input);assert.equal(r.reports.warm.visual.lateUsable,0);assert.equal(r.reports.warm.cold.visual.lateUsable,1);assert.equal(r.reports.warm.cold.visual.outcomes.timedOut,1);assert.equal(gate(r,'warm','captureFreshness').status,'fail');});
