import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,existsSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {randomUUID,createHash} from 'node:crypto';
import {crc32,deflateSync} from 'node:zlib';
import {GameFrameCustody,GameFrameCustodyError,inspectGamePng} from '../src/frame-custody.ts';
import type * as G from '@lifestream/contracts/game-activity';
function chunk(type:string,data:Buffer){const h=Buffer.alloc(8),tail=Buffer.alloc(4);h.writeUInt32BE(data.length);h.write(type,4);tail.writeUInt32BE(crc32(Buffer.concat([h.subarray(4),data])));return Buffer.concat([h,data,tail]);}
export function png(){const h=Buffer.alloc(13);h.writeUInt32BE(1,0);h.writeUInt32BE(1,4);h[8]=8;h[9]=2;return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',h),chunk('IDAT',deflateSync(Buffer.from([0,255,0,0]))),chunk('IEND',Buffer.alloc(0))]);}
function fixture(){const directory=mkdtempSync(join(tmpdir(),'game-custody-')),bytes=png(),id=randomUUID(),now=Date.now(),scope={assistantId:randomUUID(),principalId:randomUUID(),relationshipId:randomUUID(),environmentId:randomUUID(),activityId:randomUUID(),runId:randomUUID(),activityEpoch:1,timelineId:randomUUID(),timelineRevision:1,campaignId:randomUUID(),observationDomain:'simulatedGame',contextBinding:{conversationId:randomUUID(),sessionId:randomUUID(),endpointId:randomUUID(),participationKind:'logicalActivity',humanSpeakerRef:null,audioOwnerEndpointId:null,ownerPermissionRef:'fixture'}} as G.ActivityScope;
 const shot={screenshotId:id,mediaRef:id,sha256:createHash('sha256').update(bytes).digest('hex'),byteLength:bytes.length,mediaType:'image/png',width:1,height:1,capturedAt:new Date(now).toISOString(),frameNumber:1,expiresAt:new Date(now+10000).toISOString()} as G.GameScreenshot;
 const observation={scope,screenshots:[shot],frameNumber:1,capturedAt:shot.capturedAt} as G.GameObservation;writeFileSync(join(directory,id+'.png'),bytes);return {directory,bytes,id,scope,shot,observation};}
test('PNG custody verifies structure, CRC, bounded decompression and dimensions',()=>{assert.deepEqual(inspectGamePng(png(),1),{width:1,height:1});for(const data of [png().subarray(0,20),Buffer.concat([png(),Buffer.from([0])]),Buffer.from(png())]){if(data.length===png().length)data[data.length-1]^=1;assert.throws(()=>inspectGamePng(data,1),GameFrameCustodyError);}});
test('custody binds exact source/frame/digest and refuses foreign scope, tampering and stale capture',()=>{const f=fixture();let current=true;const c=new GameFrameCustody(f.directory,{maxBytes:1024,maxQueueBytes:10000,maxLongEdge:256,maxFrames:2,maxTtlMs:10000,current:()=>current});try{assert.equal(c.ingest(f.observation),true);assert.deepEqual(c.read(f.id,f.scope).bytes,f.bytes);assert.throws(()=>c.read(f.id,{...f.scope,runId:randomUUID()}));assert.equal(c.ingest(f.observation),false);current=false;assert.throws(()=>c.read(f.id,f.scope));c.dispose();assert.equal(existsSync(join(f.directory,f.id+'.png')),false);}finally{c.dispose();rmSync(f.directory,{recursive:true,force:true});}
 for(const mutate of [(f:any)=>f.shot.sha256='a'.repeat(64),(f:any)=>f.shot.frameNumber++,(f:any)=>f.shot.mediaRef='../escape',(f:any)=>f.shot.expiresAt=new Date(0).toISOString(),(f:any)=>f.shot.width=2]){const f=fixture(),c=new GameFrameCustody(f.directory,{maxBytes:1024,maxQueueBytes:10000,maxLongEdge:256,maxFrames:2,maxTtlMs:10000,current:()=>true});try{mutate(f);assert.equal(c.ingest(f.observation),false);}finally{c.dispose();rmSync(f.directory,{recursive:true,force:true});}}});
test('cleanup leaves unrelated or replaced files intact and zeroes retained memory',()=>{const f=fixture(),c=new GameFrameCustody(f.directory,{maxBytes:1024,maxQueueBytes:10000,maxLongEdge:256,maxFrames:1,maxTtlMs:10000,current:()=>true});try{assert.equal(c.ingest(f.observation),true);const path=join(f.directory,f.id+'.png');writeFileSync(path,'replacement');c.dispose();assert.equal(existsSync(path),true);assert.throws(()=>c.read(f.id,f.scope));}finally{c.dispose();rmSync(f.directory,{recursive:true,force:true});}});
test('custody rejects queue overflow before admitting image bytes',()=>{const f=fixture(),c=new GameFrameCustody(f.directory,{maxBytes:1024,maxQueueBytes:f.bytes.length-1,maxLongEdge:256,maxFrames:1,maxTtlMs:10000,current:()=>true});try{assert.equal(c.ingest(f.observation),false);assert.throws(()=>c.read(f.id,f.scope));assert.equal(existsSync(join(f.directory,f.id+'.png')),true);}finally{c.dispose();rmSync(f.directory,{recursive:true,force:true});}});
test('custody expires an idle frame without needing a subsequent read',{timeout:5000},async()=>{const f=fixture();f.shot.expiresAt=new Date(Date.now()+100).toISOString();const c=new GameFrameCustody(f.directory,{maxBytes:1024,maxQueueBytes:10000,maxLongEdge:256,maxFrames:1,maxTtlMs:10000,current:()=>true});try{assert.equal(c.ingest(f.observation),true);await new Promise(resolve=>setTimeout(resolve,200));assert.equal(existsSync(join(f.directory,f.id+'.png')),false);assert.throws(()=>c.read(f.id,f.scope));}finally{c.dispose();rmSync(f.directory,{recursive:true,force:true});}});
