// Synthetic fixtures extracted from provider boundary tests; no native/game evidence.
import {randomUUID} from 'node:crypto';
import type * as G from '@lifestream/contracts/game-activity';
const stamp=()=>new Date().toISOString(),digest='a'.repeat(64);
const scope=():G.ActivityScope=>({assistantId:randomUUID(),principalId:randomUUID(),relationshipId:randomUUID(),environmentId:randomUUID(),activityId:randomUUID(),runId:randomUUID(),activityEpoch:1,timelineId:randomUUID(),timelineRevision:1,campaignId:randomUUID(),observationDomain:'simulatedGame',contextBinding:{conversationId:randomUUID(),sessionId:randomUUID(),endpointId:randomUUID(),participationKind:'logicalActivity',humanSpeakerRef:null,audioOwnerEndpointId:null,ownerPermissionRef:'synthetic-owner-permission'}});
export function observe():G.GameObserveRequest{return {schemaVersion:'1.0.0',operation:'GameActivityAdapter.observe',requestId:randomUUID(),correlationId:randomUUID(),deadlineAt:new Date(Date.now()+10000).toISOString(),cancellationId:randomUUID(),executionMode:'normal',scope:scope(),idempotencyKey:randomUUID(),payload:{expectedPinsDigest:digest,afterActionId:null,maxScreenshots:1}};}
const neutral={up:false,down:false,left:false,right:false,a:false,b:false,x:false,y:false,l:false,r:false,start:false,select:false} as const;
export function action():G.GameActionRequest{const r=observe(),observationId=randomUUID(),predicateId=randomUUID();return {...r,operation:'GameActivityAdapter.applyController',payload:{actionId:randomUUID(),proposal:{schemaVersion:'1.0.0',recordType:'gameActionProposal',scope:r.scope,proposalId:randomUUID(),observationId,observationRevision:1,preparedViewId:randomUUID(),preparedViewRevision:1,invalidationKey:randomUUID(),buttons:['a'],durationFrames:2,maxWallMs:100,expectedVisibleOutcome:'A synthetic menu may change.',uncertainty:'No real game was run.',adviceRefs:[],reason:'Scripted boundary test.',preconditions:[{predicateId,fieldId:'synthetic-visible-menu',expectedValue:'open',sourceObservationId:observationId}]},admission:{admissionId:randomUUID(),capabilityInvocationId:randomUUID(),authorityContextRef:{providerRef:'synthetic-authority',contextId:randomUUID(),revision:1},dispatchReceipt:{reference:'synthetic-receipt',sha256:digest,mediaType:'application/json',schemaRef:'https://lifestream.dev/contracts/human-authority-decision/2.0.0',byteLength:100},scopeDigest:digest,inputDigest:digest,policyRevision:1,issuedAt:stamp(),expiresAt:new Date(Date.now()+10000).toISOString()},inputOwnerLeaseId:randomUUID(),buttonVector:{...neutral,a:true},protectedMenuOperation:'none',expectedFrameNumber:10,expectedPinsDigest:digest,dispatchValidation:{planningObservationId:observationId,dispatchObservationId:observationId,dispatchObservationRevision:1,checkedFrameNumber:10,checkedAt:stamp(),validatorRef:'synthetic-validator',predicateChecks:[{predicateId,fieldId:'synthetic-visible-menu',observedValue:'open',matched:true,sourceObservationId:observationId}],planningCapturedAt:stamp(),planningFrameNumber:10,preparedContextFreshUntil:new Date(Date.now()+10000).toISOString()}}};}
export function observed(r:G.GameObserveRequest):G.GameObserveResult{const time=stamp();return {schemaVersion:'1.0.0',operation:r.operation,requestId:r.requestId,correlationId:r.correlationId,providerRef:'synthetic-bridge',completedAt:time,outcome:{status:'succeeded',error:null,payload:{observation:{schemaVersion:'1.0.0',recordType:'gameObservation',scope:structuredClone(r.scope),observationId:randomUUID(),revision:1,pinsDigest:digest,frameNumber:10,capturedAt:time,receivedAt:time,interpretedAt:null,providerConfigurationRef:null,screenshots:[{screenshotId:randomUUID(),mediaRef:randomUUID(),sha256:digest,byteLength:100,mediaType:'image/png',width:256,height:224,capturedAt:time,frameNumber:10,expiresAt:new Date(Date.now()+10000).toISOString()}],facts:[],visibleState:[],previousActionId:null,untrusted:true},reconciledAction:null}}};}
export function applied(r:G.GameActionRequest):G.GameActionResult{const time=stamp();return {schemaVersion:'1.0.0',operation:r.operation,requestId:r.requestId,correlationId:r.correlationId,providerRef:'synthetic-bridge',completedAt:time,outcome:{status:'succeeded',error:null,payload:{schemaVersion:'1.0.0',recordType:'gameActionReceipt',scope:structuredClone(r.scope),actionId:r.payload.actionId,proposalId:r.payload.proposal.proposalId,idempotencyKey:r.idempotencyKey,inputDigest:r.payload.admission.inputDigest,admissionId:r.payload.admission.admissionId,disposition:'completed',beforeFrame:10,afterFrame:12,framesApplied:2,buttonsNeutralized:true,startedAt:time,completedAt:time,resultingObservationIds:[],recordedAt:time,reason:null}}};}
