import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createServer,connect} from 'node:net';
import {once} from 'node:events';
import {randomUUID,createHmac} from 'node:crypto';
import {listenForNativeBizHawk,nativeBridgeEnvironment} from '../src/native-host.ts';
import {GameFrameCustody} from '../src/frame-custody.ts';
import {GameControlFrameDecoder,encodeGameControlFrame} from '../src/transport.ts';
import {scriptedGameBounds} from '../../runtime/test/fixtures/game-policy.ts';
export function scope(){return {assistantId:randomUUID(),principalId:randomUUID(),relationshipId:randomUUID(),environmentId:randomUUID(),activityId:randomUUID(),runId:randomUUID(),activityEpoch:1,timelineId:randomUUID(),timelineRevision:1,campaignId:randomUUID(),observationDomain:'simulatedGame' as const,contextBinding:{conversationId:randomUUID(),sessionId:randomUUID(),endpointId:randomUUID(),participationKind:'logicalActivity' as const,humanSpeakerRef:null,audioOwnerEndpointId:null,ownerPermissionRef:'fixture'}};}
test('native host admits one loopback peer, mutually authenticates and closes without reconnect',{timeout:10000},async()=>{const directory=mkdtempSync(join(tmpdir(),'native-host-')),frames=new GameFrameCustody(directory,{maxBytes:1024,maxQueueBytes:10000,maxLongEdge:256,maxFrames:2,maxTtlMs:10000,current:()=>true});let host:any,client:any;try{const temp=createServer();temp.listen(0,'127.0.0.1');await once(temp,'listening');const port=(temp.address() as any).port;await new Promise<void>(r=>temp.close(()=>r()));const secret=Buffer.alloc(32,23),options={port,connectionTimeoutMs:2000,pairingSecret:secret,scope:scope(),pinsDigest:'a'.repeat(64),authenticationTimeoutMs:1000,sessionDurationMs:5000,boundary:{providerRef:'native-fixture',maxDurationMs:2000,sourceAvailable:()=>false,acceptObservation:()=>false},onDisconnect:()=>{},frameCustody:frames,bounds:scriptedGameBounds,romSha1:'b'.repeat(40)};host=await listenForNativeBizHawk(options);const configuration=JSON.parse(nativeBridgeEnvironment(options).LIFESTREAM_BIZHAWK_OPTIONS);assert.equal(configuration.port,port);assert.equal(configuration.scope.observationDomain,'simulatedGame');client=connect(port,'127.0.0.1');client.on('error',()=>{});let challenge:any,confirmation:any;const decoded=new Promise<void>((resolve,reject)=>{const decoder=new GameControlFrameDecoder(text=>{const m=JSON.parse(text);if(m.type==='challenge'){challenge=m;client.write(encodeGameControlFrame(JSON.stringify({type:'authenticate',proof:createHmac('sha256',secret).update(text).digest('hex')})));}else{confirmation=m;resolve();}});client.on('data',chunk=>{try{decoder.push(chunk);}catch(e){reject(e);}});});const transport=await host.connected;await transport.ready;await decoded;assert.equal(confirmation.proof,createHmac('sha256',secret).update('lifestream-game-control/1 host '+JSON.stringify(challenge)).digest('hex'));assert.deepEqual(secret,Buffer.alloc(32,23));const disconnected=once(client,'close');await host.close();await disconnected;assert.equal(client.destroyed,true);}finally{client?.destroy();await host?.close();frames.dispose();rmSync(directory,{recursive:true,force:true});}});
