import assert from 'node:assert/strict';
import test from 'node:test';
import {randomUUID} from 'node:crypto';
import {guardGameActivityAdapter,GameAdapterBoundaryError} from '../src/provider.ts';
import type {GameActivityAdapter,GameCallContext} from '../src/port.ts';
import type * as G from '@lifestream/contracts/game-activity';
const stamp=()=>new Date().toISOString(),digest='a'.repeat(64);
const scope=():G.ActivityScope=>({assistantId:randomUUID(),principalId:randomUUID(),relationshipId:randomUUID(),environmentId:randomUUID(),activityId:randomUUID(),runId:randomUUID(),activityEpoch:1,timelineId:randomUUID(),timelineRevision:1,campaignId:randomUUID(),observationDomain:'simulatedGame',contextBinding:{conversationId:randomUUID(),sessionId:randomUUID(),endpointId:randomUUID(),participationKind:'logicalActivity',humanSpeakerRef:null,audioOwnerEndpointId:null,ownerPermissionRef:'synthetic-owner-permission'}});
function observe():G.GameObserveRequest{return {schemaVersion:'1.0.0',operation:'GameActivityAdapter.observe',requestId:randomUUID(),correlationId:randomUUID(),deadlineAt:new Date(Date.now()+10000).toISOString(),cancellationId:randomUUID(),executionMode:'simulation',scope:scope(),idempotencyKey:randomUUID(),payload:{expectedPinsDigest:digest,afterActionId:null,maxScreenshots:1}};}
const neutral={up:false,down:false,left:false,right:false,a:false,b:false,x:false,y:false,l:false,r:false,start:false,select:false} as const;
function action():G.GameActionRequest{const r=observe(),observationId=randomUUID(),predicateId=randomUUID();return {...r,operation:'GameActivityAdapter.applyController',payload:{actionId:randomUUID(),proposal:{schemaVersion:'1.0.0',recordType:'gameActionProposal',scope:r.scope,proposalId:randomUUID(),observationId,observationRevision:1,preparedViewId:randomUUID(),preparedViewRevision:1,invalidationKey:randomUUID(),buttons:['a'],durationFrames:2,maxWallMs:100,expectedVisibleOutcome:'A synthetic menu may change.',uncertainty:'No real game was run.',adviceRefs:[],reason:'Scripted boundary test.',preconditions:[{predicateId,fieldId:'synthetic-visible-menu',expectedValue:'open',sourceObservationId:observationId}]},admission:{admissionId:randomUUID(),capabilityInvocationId:randomUUID(),authorityContextRef:{providerRef:'synthetic-authority',contextId:randomUUID(),revision:1},dispatchReceipt:{reference:'synthetic-receipt',sha256:digest,mediaType:'application/json',schemaRef:'https://lifestream.dev/contracts/human-authority-decision/2.0.0',byteLength:100},scopeDigest:digest,inputDigest:digest,policyRevision:1,issuedAt:stamp(),expiresAt:new Date(Date.now()+10000).toISOString()},inputOwnerLeaseId:randomUUID(),buttonVector:{...neutral,a:true},protectedMenuOperation:'none',expectedFrameNumber:10,expectedPinsDigest:digest,dispatchValidation:{planningObservationId:observationId,dispatchObservationId:observationId,dispatchObservationRevision:1,checkedFrameNumber:10,checkedAt:stamp(),validatorRef:'synthetic-validator',predicateChecks:[{predicateId,fieldId:'synthetic-visible-menu',observedValue:'open',matched:true,sourceObservationId:observationId}],planningCapturedAt:stamp(),planningFrameNumber:10,preparedContextFreshUntil:new Date(Date.now()+10000).toISOString()}}};}
function observed(r:G.GameObserveRequest):G.GameObserveResult{const time=stamp();return {schemaVersion:'1.0.0',operation:r.operation,requestId:r.requestId,correlationId:r.correlationId,providerRef:'synthetic-bridge',completedAt:time,outcome:{status:'succeeded',error:null,payload:{observation:{schemaVersion:'1.0.0',recordType:'gameObservation',scope:structuredClone(r.scope),observationId:randomUUID(),revision:1,pinsDigest:digest,frameNumber:10,capturedAt:time,receivedAt:time,interpretedAt:null,providerConfigurationRef:null,screenshots:[{screenshotId:randomUUID(),mediaRef:randomUUID(),sha256:digest,byteLength:100,mediaType:'image/png',width:256,height:224,capturedAt:time,frameNumber:10,expiresAt:new Date(Date.now()+10000).toISOString()}],facts:[],visibleState:[],previousActionId:null,untrusted:true},reconciledAction:null}}};}
function applied(r:G.GameActionRequest):G.GameActionResult{const time=stamp();return {schemaVersion:'1.0.0',operation:r.operation,requestId:r.requestId,correlationId:r.correlationId,providerRef:'synthetic-bridge',completedAt:time,outcome:{status:'succeeded',error:null,payload:{schemaVersion:'1.0.0',recordType:'gameActionReceipt',scope:structuredClone(r.scope),actionId:r.payload.actionId,proposalId:r.payload.proposal.proposalId,idempotencyKey:r.idempotencyKey,inputDigest:r.payload.admission.inputDigest,admissionId:r.payload.admission.admissionId,disposition:'completed',beforeFrame:10,afterFrame:12,framesApplied:2,buttonsNeutralized:true,startedAt:time,completedAt:time,resultingObservationIds:[],recordedAt:time,reason:null}}};}
const context:GameCallContext={signal:new AbortController().signal,isCurrent:()=>true};
const unavailable=async()=>{throw Error('Never dispatch an unimplemented operation');};
const adapter=(overrides:Partial<GameActivityAdapter>={}):GameActivityAdapter=>({observe:async r=>observed(r),applyController:async r=>applied(r),releaseControls:unavailable,controlSave:unavailable,...overrides});
const options={providerRef:'synthetic-bridge',maxDurationMs:10000,sourceAvailable:()=>true,acceptObservation:()=>true,acceptAction:()=>true};
const error=(code:GameAdapterBoundaryError['code'],may=false)=>(e:unknown)=>e instanceof GameAdapterBoundaryError&&e.code===code&&e.effectMayHaveStarted===may;
test('closed game observations retain fictional scope and immutable source without activating any emulator',async()=>{const r=observe();let sent!:G.GameObserveRequest;const guarded=guardGameActivityAdapter(adapter({observe:async value=>{sent=value;assert.ok(Object.isFrozen(value.scope));return observed(value);}}),options);const reply=await guarded.observe(r,context);assert.equal(reply.outcome.payload!.observation.scope.observationDomain,'simulatedGame');assert.ok(Object.isFrozen(reply.outcome.payload));assert.notEqual(sent,r);assert.equal(r.scope.contextBinding.humanSpeakerRef,null);});
test('unknown fields, raw paths, camera domain, getters and proxies are rejected before provider entry',async t=>{for(const mode of ['extra','rawPath','camera','getter','proxy'])await t.test(mode,async()=>{let calls=0;const r:any=observe();if(mode==='extra')r.payload.lua='arbitrary-code';if(mode==='rawPath')r.payload.mediaPath='/synthetic/raw';if(mode==='camera')r.scope.observationDomain='physicalCamera';if(mode==='getter')Object.defineProperty(r.payload,'expectedPinsDigest',{enumerable:true,get(){calls++;return digest;}});const guarded=guardGameActivityAdapter(adapter({observe:async value=>{calls++;return observed(value);}}),options);await assert.rejects(guarded.observe(mode==='proxy'?new Proxy(r,{}):r,context),error('invalidRequest'));assert.equal(calls,0);});});
test('missing setup or reviewed observation admission remains unavailable and cannot masquerade as seeing',async()=>{let calls=0;const wire=adapter({observe:async r=>{calls++;return observed(r);}});await assert.rejects(guardGameActivityAdapter(wire,{...options,sourceAvailable:()=>false}).observe(observe(),context),error('unavailable'));assert.equal(calls,0);await assert.rejects(guardGameActivityAdapter(wire,{...options,acceptObservation:()=>false}).observe(observe(),context),error('invalidResponse'));});
test('response identity, scope and pins are checked independently of schema shape',async t=>{for(const mode of ['request','provider','scope','pins'])await t.test(mode,async()=>{const guarded=guardGameActivityAdapter(adapter({observe:async r=>{const result=observed(r);if(mode==='request')result.requestId=randomUUID();if(mode==='provider')result.providerRef='other-bridge';if(mode==='scope')result.outcome.payload!.observation.scope.timelineId=randomUUID();if(mode==='pins')result.outcome.payload!.observation.pinsDigest='b'.repeat(64);return result;}}),options);await assert.rejects(guarded.observe(observe(),context),error('invalidResponse'));});});
test('controller proposal requires a trusted durable claim and exact scope/button/current-observation binding',async t=>{for(const mode of ['missingClaim','deniedClaim','expired','uncertainMenu','predicate','staleContext','scope','button','frame'])await t.test(mode,async()=>{const r=action();if(mode==='expired')r.payload.admission.expiresAt=new Date(0).toISOString();if(mode==='uncertainMenu')r.payload.protectedMenuOperation='uncertain';if(mode==='predicate')r.payload.dispatchValidation.predicateChecks[0]!.observedValue='closed';if(mode==='staleContext')r.payload.dispatchValidation.preparedContextFreshUntil=new Date(0).toISOString();if(mode==='scope')r.payload.proposal.scope={...r.scope,timelineId:randomUUID()};if(mode==='button')r.payload.buttonVector.b=true;if(mode==='frame')r.payload.expectedFrameNumber=11;let calls=0;const guarded=guardGameActivityAdapter(adapter({applyController:async r=>{calls++;return applied(r);}}),{...options,...(mode==='missingClaim'?{}:{claimEffect:async()=>mode!=='deniedClaim'})});await assert.rejects(guarded.applyController(r,context),error(['missingClaim','deniedClaim','expired','uncertainMenu'].includes(mode)?'admissionRequired':'invalidRequest'));assert.equal(calls,0);});const r=action();const result=await guardGameActivityAdapter(adapter(),{...options,claimEffect:async()=>true}).applyController(r,context);assert.equal(result.outcome.payload!.framesApplied,2);});
test('current scope is rechecked after admission and an uncooperative late effect remains potentially started',async()=>{let current=true,release!:()=>void,entered!:()=>void;const held=new Promise<void>(r=>release=r),started=new Promise<void>(r=>entered=r),r=action(),guarded=guardGameActivityAdapter(adapter({applyController:async r=>{entered();await held;return applied(r);}}),{...options,claimEffect:async()=>true});const c={...context,isCurrent:()=>current};const pending=guarded.applyController(r,c);await started;const other=structuredClone(r);other.requestId=randomUUID();other.payload.actionId=randomUUID();await assert.rejects(guarded.applyController(other,c),error('concurrentEffect'));current=false;release();await assert.rejects(pending,error('scopeChanged',true));let calls=0;current=true;const denied=guardGameActivityAdapter(adapter({applyController:async value=>{calls++;return applied(value);}}),{...options,claimEffect:async()=>{current=false;return true;}});await assert.rejects(denied.applyController(action(),c),error('scopeChanged'));assert.equal(calls,0);});
test('deadline/cancellation abandons hung observation without accepting late output',async()=>{const r=observe();r.deadlineAt=new Date(Date.now()+100).toISOString();const guarded=guardGameActivityAdapter(adapter({observe:async()=>new Promise(()=>{})}),options);await assert.rejects(guarded.observe(r,context),error('timedOut'));const controller=new AbortController();controller.abort();await assert.rejects(guarded.observe(observe(),{...context,signal:controller.signal}),error('cancelled'));});
function releaseRequest():G.GameReleaseRequest{const r=observe();return {...r,operation:'GameActivityAdapter.releaseControls',payload:{targetInputOwnerLeaseId:randomUUID(),reason:'policyChanged',neutralButtons:{...neutral}}};}
function released(r:G.GameReleaseRequest):G.GameReleaseResult{return {schemaVersion:'1.0.0',operation:r.operation,requestId:r.requestId,correlationId:r.correlationId,providerRef:'synthetic-bridge',completedAt:stamp(),outcome:{status:'succeeded',error:null,payload:{targetInputOwnerLeaseId:r.payload.targetInputOwnerLeaseId,disposition:'neutralizedAndPaused',confirmedAt:stamp(),emulatorPaused:true,buttonsNeutralized:true,pauseFrameNumber:10,verifiedFrameNumber:10,pauseConfirmedMonotonicMs:100,verifiedMonotonicMs:110,activityEpochAfterFence:2,confirmationSource:'adapterObserved',resumeRequiresFreshObservation:true}}};}
test('exact old-lease safety release requires independent host intent and stationary-frame acknowledgment',async t=>{for(const mode of ['missing','denied','successor','moving','notFenced','verified'])await t.test(mode,async()=>{let calls=0;const request=releaseRequest(),guarded=guardGameActivityAdapter(adapter({releaseControls:async r=>{calls++;const value=released(r);if(mode==='successor')value.outcome.payload!.targetInputOwnerLeaseId=randomUUID();if(mode==='moving')value.outcome.payload!.verifiedFrameNumber=11;if(mode==='notFenced')value.outcome.payload!.activityEpochAfterFence=1;return value;}}),{...options,sourceAvailable:()=>false,...(mode==='missing'?{}:{admitRelease:async r=>mode!=='denied'&&r.payload.targetInputOwnerLeaseId===request.payload.targetInputOwnerLeaseId})});if(mode==='verified'){const response=await guarded.releaseControls(request,context);assert.equal(response.outcome.payload!.resumeRequiresFreshObservation,true);assert.equal(calls,1);}else{await assert.rejects(guarded.releaseControls(request,context),error(mode==='missing'||mode==='denied'?'admissionRequired':'invalidResponse',!['missing','denied'].includes(mode)));assert.equal(calls,['missing','denied'].includes(mode)?0:1);}});});
test('save controls reject savestates and missing admissions; transport failure preserves effect uncertainty',async()=>{const a=action(),save:G.GameSaveRequest={...observe(),operation:'GameActivityAdapter.controlSave',scope:a.scope,payload:{action:'flushSaveRam',purpose:'ordinaryInGame',expectedPinsDigest:digest,saveArtifact:null,admission:a.payload.admission}};let calls=0;const wire=adapter({controlSave:async()=>{calls++;throw Error('synthetic sensitive provider error');}});await assert.rejects(guardGameActivityAdapter(wire,options).controlSave(save,context),error('admissionRequired'));await assert.rejects(guardGameActivityAdapter(wire,{...options,claimEffect:async()=>true}).controlSave({...save,payload:{...save.payload,action:'savestate' as any}},context),error('invalidRequest'));assert.equal(calls,0);await assert.rejects(guardGameActivityAdapter(wire,{...options,claimEffect:async()=>true,acceptSave:()=>true}).controlSave(save,context),error('invalidResponse',true));assert.equal(calls,1);});
test('oversized and non-JSON inputs fail before dispatch and no response can add physical audience evidence',async()=>{let calls=0;const wire=adapter({observe:async r=>{calls++;const result:any=observed(r);result.outcome.payload.observation.visibleHumanCount='one';return result;}}),guarded=guardGameActivityAdapter(wire,options);const r:any=observe();r.payload.extra='x'.repeat(131073);await assert.rejects(guarded.observe(r,context),error('invalidRequest'));assert.equal(calls,0);await assert.rejects(guarded.observe(observe(),context),error('invalidResponse'));assert.equal(calls,1);});
test('admission expiration while awaiting a durable claim cannot enter the effect provider',async()=>{const r=action();r.payload.admission.expiresAt=new Date(Date.now()+100).toISOString();let calls=0;const guarded=guardGameActivityAdapter(adapter({applyController:async r=>{calls++;return applied(r);}}),{...options,claimEffect:async()=>{await new Promise(resolve=>setTimeout(resolve,150));return true;}});await assert.rejects(guarded.applyController(r,context),error('admissionRequired'));assert.equal(calls,0);});
test('potentially executed work stays quarantined until trusted reconciliation, with no blind second effect',async()=>{const r=action();let calls=0,reconciled=false;const wire=adapter({applyController:async request=>{calls++;if(calls===1)throw Error('Scripted unknown outcome');return applied(request);}}),guarded=guardGameActivityAdapter(wire,{...options,claimEffect:async()=>true,reconcileEffect:async original=>{assert.equal(original.payload.admission.admissionId,r.payload.admission.admissionId);return reconciled;}});await assert.rejects(guarded.applyController(r,context),error('invalidResponse',true));const successor=structuredClone(r);successor.requestId=randomUUID();successor.idempotencyKey=randomUUID();successor.payload.actionId=randomUUID();await assert.rejects(guarded.applyController(successor,context),error('concurrentEffect'));assert.equal(calls,1);reconciled=true;assert.equal((await guarded.applyController(successor,context)).outcome.payload!.disposition,'completed');assert.equal(calls,2);});

function saveRequest():G.GameSaveRequest{const a=action();return {...observe(),scope:a.scope,operation:'GameActivityAdapter.controlSave',payload:{action:'flushSaveRam',purpose:'ordinaryInGame',expectedPinsDigest:digest,saveArtifact:null,admission:a.payload.admission}};}
function saved(r:G.GameSaveRequest):G.GameSaveResult{const time=stamp();return {schemaVersion:'1.0.0',operation:r.operation,requestId:r.requestId,correlationId:r.correlationId,providerRef:'synthetic-bridge',completedAt:time,outcome:{status:'succeeded',error:null,payload:{action:r.payload.action,timelineId:r.scope.timelineId,confirmedAt:time,saveArtifact:{artifact:{reference:'synthetic:opaque-save',sha256:digest,mediaType:'application/octet-stream',schemaRef:'synthetic:qualified-save-format',byteLength:32},contentClass:'opaqueGameSaveRam',modelReadable:false,pinsDigest:digest,sourceTimelineId:r.scope.timelineId,sourceFrameNumber:12,createdAt:time,verifiedAt:time,readbackQualificationRef:'synthetic:unproved-native-readback'}}}};}

test('ordinary save cannot enter without independent native readback qualification support',async()=>{
 let calls=0,claims=0;const wire=adapter({controlSave:async r=>{calls++;return saved(r);}});
 await assert.rejects(guardGameActivityAdapter(wire,{...options,claimEffect:async()=>{claims++;return true;}}).controlSave(saveRequest(),context),error('unavailable'));assert.equal(calls,0);assert.equal(claims,0);
});

for(const mode of ['denied','promise','throws','withdraw','verified']as const)test('shaped native save acknowledgment requires strict independently qualified '+mode,async()=>{
 let current=true,calls=0,qualificationCalls=0;const r=saveRequest(),guarded=guardGameActivityAdapter(adapter({controlSave:async request=>{calls++;return saved(request);}}),{...options,claimEffect:async()=>true,acceptSave:(request,result)=>{qualificationCalls++;assert.ok(Object.isFrozen(request.payload));assert.ok(Object.isFrozen(result.outcome.payload));if(mode==='throws')throw Error('Synthetic private qualifier failure');if(mode==='withdraw')current=false;return (mode==='promise'?Promise.resolve(true):mode!=='denied')as boolean;}}),c={...context,isCurrent:()=>current};
 if(mode==='verified')assert.equal((await guarded.controlSave(r,c)).outcome.status,'succeeded');else{await assert.rejects(guarded.controlSave(r,c),error(mode==='withdraw'?'scopeChanged':'invalidResponse',true));current=true;const next=structuredClone(r);next.requestId=randomUUID();await assert.rejects(guarded.controlSave(next,c),error('concurrentEffect'));assert.equal(calls,1);}
 assert.equal(qualificationCalls,1);
});

for(const mode of ['futureConfirmation','staleReadback','wrongSourceTimeline','emptyBytes','createdAfterReadback','futureReadback']as const)test('ordinary save '+mode+' fails before host qualification',async()=>{
 let qualified=0;const r=saveRequest(),guarded=guardGameActivityAdapter(adapter({controlSave:async request=>{const result=saved(request),p=result.outcome.payload!;if(mode==='futureConfirmation')p.confirmedAt=new Date(Date.now()+1000).toISOString();if(mode==='staleReadback')p.saveArtifact.verifiedAt=new Date(0).toISOString();if(mode==='wrongSourceTimeline')p.saveArtifact.sourceTimelineId=randomUUID();if(mode==='emptyBytes')p.saveArtifact.artifact.byteLength=0;if(mode==='createdAfterReadback')p.saveArtifact.createdAt=new Date(Date.now()+1000).toISOString();if(mode==='futureReadback')p.saveArtifact.verifiedAt=new Date(Date.now()+1000).toISOString();return result;}}),{...options,claimEffect:async()=>true,acceptSave:()=>{qualified++;return true;}});
 await assert.rejects(guarded.controlSave(r,context),error('invalidResponse',true));assert.equal(qualified,0);
});


test('controller cannot claim or enter without a captured independent native-result qualifier',async()=>{
 let calls=0,claims=0;const config={...options,acceptAction:undefined,claimEffect:async()=>{claims++;return true;}},guarded=guardGameActivityAdapter(adapter({applyController:async r=>{calls++;return applied(r);}}),config);
 config.acceptAction=(()=>true)as any;await assert.rejects(guarded.applyController(action(),context),error('unavailable'));assert.equal(calls,0);assert.equal(claims,0);
});
for(const mode of ['denied','promise','throws','withdraw','verified']as const)test('controller terminal requires independent strict native qualification '+mode,async()=>{
 let current=true,calls=0,qualified=0;const r=action(),guarded=guardGameActivityAdapter(adapter({applyController:async r=>{calls++;return applied(r);}}),{...options,claimEffect:async()=>true,acceptAction:(request,result)=>{qualified++;assert.ok(Object.isFrozen(request.payload));assert.ok(Object.isFrozen(result.outcome.payload));if(mode==='throws')throw Error('Private synthetic source error');if(mode==='withdraw')current=false;return(mode==='promise'?Promise.resolve(true):mode!=='denied')as boolean;}}),c={...context,isCurrent:()=>current};
 if(mode==='verified')assert.equal((await guarded.applyController(r,c)).outcome.payload!.disposition,'completed');else{await assert.rejects(guarded.applyController(r,c),error(mode==='withdraw'?'scopeChanged':'invalidResponse',true));current=true;const next=structuredClone(r);next.requestId=randomUUID();next.payload.actionId=randomUUID();await assert.rejects(guarded.applyController(next,c),error('concurrentEffect'));assert.equal(calls,1);}assert.equal(qualified,1);
});
for(const mode of ['beforeAdmission','futureRecord','reversed','completionWithoutStart','cancelledWithoutFrames','failedWithoutClocks','afterResult']as const)test('controller terminal '+mode+' is refused before native qualification',async()=>{
 let qualified=0;const r=action(),guarded=guardGameActivityAdapter(adapter({applyController:async request=>{const result=applied(request),p=result.outcome.payload!;if(mode==='beforeAdmission')p.startedAt=new Date(0).toISOString();if(mode==='futureRecord')p.recordedAt=new Date(Date.now()+1000).toISOString();if(mode==='reversed')p.completedAt=new Date(0).toISOString();if(mode==='completionWithoutStart')p.startedAt=null;if(mode==='cancelledWithoutFrames'){p.disposition='cancelled';p.framesApplied=null;}if(mode==='failedWithoutClocks'){p.disposition='failed';p.startedAt=null;p.completedAt=null;}if(mode==='afterResult')result.completedAt=new Date(0).toISOString();return result;}}),{...options,claimEffect:async()=>true,acceptAction:()=>{qualified++;return true;}});
 await assert.rejects(guarded.applyController(r,context),error('invalidResponse',true));assert.equal(qualified,0);
});
test('an unqualified rejected action cannot clear unknown native ownership for a successor',async()=>{
 let calls=0,qualified=0;const r=action(),guarded=guardGameActivityAdapter(adapter({applyController:async request=>{calls++;return {...applied(request),outcome:{status:'rejected',payload:null,error:{code:'unavailable',message:'Scripted rejected native response',retryable:false,correlationId:request.correlationId,details:[]}}}as G.GameActionResult;}}),{...options,claimEffect:async()=>true,acceptAction:()=>{qualified++;return false;}});
 await assert.rejects(guarded.applyController(r,context),error('invalidResponse',true));await assert.rejects(guarded.applyController({...r,requestId:randomUUID()},context),error('concurrentEffect'));assert.equal(calls,1);assert.equal(qualified,1);
});
test('native-qualified unknown receipt is honest output and still fences successor control',async()=>{
 let calls=0;const r=action(),guarded=guardGameActivityAdapter(adapter({applyController:async request=>{calls++;const result=applied(request);Object.assign(result.outcome.payload!,{disposition:'outcomeUnknown',framesApplied:null,beforeFrame:null,afterFrame:null,startedAt:null,completedAt:null,buttonsNeutralized:false});return result;}}),{...options,claimEffect:async()=>true});
 assert.equal((await guarded.applyController(r,context)).outcome.payload!.disposition,'outcomeUnknown');await assert.rejects(guarded.applyController({...r,requestId:randomUUID()},context),error('concurrentEffect'));assert.equal(calls,1);
});

test('replacing the configuration callback cannot bypass its captured native qualifier',async()=>{
 let qualified=0;const config={...options,claimEffect:async()=>true,acceptAction:()=>{qualified++;return false;}},guarded=guardGameActivityAdapter(adapter(),config);config.acceptAction=()=>true;await assert.rejects(guarded.applyController(action(),context),error('invalidResponse',true));assert.equal(qualified,1);
});
for(const disposition of ['cancelled','failed']as const)test('qualified neutralized '+disposition+' with zero native usage can release the run fence',async()=>{
 let calls=0;const r=action(),guarded=guardGameActivityAdapter(adapter({applyController:async request=>{calls++;const result=applied(request);Object.assign(result.outcome.payload!,{disposition,framesApplied:0,afterFrame:10});return result;}}),{...options,claimEffect:async()=>true});assert.equal((await guarded.applyController(r,context)).outcome.payload!.disposition,disposition);assert.equal((await guarded.applyController({...r,requestId:randomUUID()},context)).outcome.payload!.framesApplied,0);assert.equal(calls,2);
});
test('independently qualified rejected control may release the run fence without claiming an action occurred',async()=>{
 let calls=0,qualified=0;const r=action(),guarded=guardGameActivityAdapter(adapter({applyController:async request=>{calls++;return {...applied(request),outcome:{status:'rejected',payload:null,error:{code:'unavailable',message:'Scripted native no-input rejection',retryable:false,correlationId:request.correlationId,details:[]}}}as G.GameActionResult;}}),{...options,claimEffect:async()=>true,acceptAction:(_request,result)=>{qualified++;assert.equal(result.outcome.status,'rejected');return true;}});assert.equal((await guarded.applyController(r,context)).outcome.status,'rejected');assert.equal((await guarded.applyController({...r,requestId:randomUUID()},context)).outcome.payload,null);assert.equal(calls,2);assert.equal(qualified,2);
});

for(const first of ['admission','request']as const)test('owned '+first+' expiry remains truthful when wall clock has not reached its boundary',async t=>{
 const now=Date.now(),r=action();r.payload.admission.issuedAt=new Date(now-10).toISOString();r.payload.admission.expiresAt=new Date(now+(first==='admission'?20:100)).toISOString();r.deadlineAt=new Date(now+(first==='request'?20:100)).toISOString();t.mock.method(Date,'now',()=>now);let entered=0;const guarded=guardGameActivityAdapter(adapter({applyController:async()=>{entered++;return new Promise(()=>{});}}),{...options,claimEffect:async()=>true});await assert.rejects(guarded.applyController(r,context),error(first==='admission'?'admissionRequired':'timedOut',true));assert.equal(entered,1);
});
