import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
import {crc32,deflateSync} from 'node:zlib';
import {ReviewedFrameDecoder} from '../src/reviewed-frame-decoder.ts';
import type {ActivityScope,GameObservation} from '@lifestream/contracts/game-activity';
const time=Date.parse('2026-10-02T08:00:00Z');
function png(){const chunk=(name:string,body:Buffer)=>{const bytes=Buffer.alloc(body.length+12);bytes.writeUInt32BE(body.length);bytes.write(name,4);body.copy(bytes,8);bytes.writeUInt32BE(crc32(bytes.subarray(4,body.length+8)),body.length+8);return bytes;};const header=Buffer.alloc(13);header.writeUInt32BE(2);header.writeUInt32BE(2,4);header[8]=8;header[9]=2;return Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',header),chunk('IDAT',deflateSync(Buffer.alloc(14))),chunk('IEND',Buffer.alloc(0))]);}
function fixture(){const id=()=>randomUUID(),bytes=png(),sha256=createHash('sha256').update(bytes).digest('hex');const scope:ActivityScope={assistantId:id(),principalId:id(),relationshipId:id(),environmentId:id(),activityId:id(),runId:id(),activityEpoch:1,timelineId:id(),timelineRevision:1,campaignId:id(),observationDomain:'simulatedGame',contextBinding:{conversationId:id(),sessionId:id(),endpointId:id(),participationKind:'logicalActivity',humanSpeakerRef:null,audioOwnerEndpointId:null,ownerPermissionRef:'decoder-fixture'}};const observation:GameObservation={schemaVersion:'1.0.0',recordType:'gameObservation',scope,observationId:id(),revision:1,pinsDigest:'a'.repeat(64),frameNumber:2,capturedAt:new Date(time).toISOString(),receivedAt:new Date(time).toISOString(),interpretedAt:null,providerConfigurationRef:null,screenshots:[{screenshotId:id(),mediaRef:id(),sha256,byteLength:bytes.length,mediaType:'image/png',width:2,height:2,capturedAt:new Date(time).toISOString(),frameNumber:2,expiresAt:new Date(time+1000).toISOString()}],facts:[],visibleState:[],previousActionId:null,untrusted:true};return {bytes,scope,observation,manifest:{revision:'1.0.0',entries:[{sha256,width:2,height:2,fields:[{fieldId:'synthetic.screen.kind',value:'reviewed'}]}]}};}
test('decoder retains exact visible provenance and snapshots the reviewed manifest',()=>{const f=fixture(),decoder=new ReviewedFrameDecoder(f.manifest);f.manifest.entries[0].fields[0].value='mutated';const fields=decoder.decode({...f,now:time+1});assert.equal(fields.length,1);assert.equal(fields[0].value,'reviewed');assert.equal(fields[0].timelineId,f.scope.timelineId);assert.equal(fields[0].firstObservedRef,f.observation.observationId);assert.equal(fields[0].lastObservedRef,f.observation.observationId);assert.equal(fields[0].manifestDigest,decoder.manifestDigest);assert.equal(fields[0].visibility,'visibleNow');});
test('unknown, stale, wrong timeline, mismatched frame/dimension and corrupt pixels fail closed',()=>{const f=fixture(),decoder=new ReviewedFrameDecoder(f.manifest);assert.deepEqual(decoder.decode({...f,now:time+1000}),[]);assert.deepEqual(decoder.decode({...f,scope:{...f.scope,timelineId:randomUUID()},now:time}),[]);for(const change of ['sha256','frameNumber','width','capturedAt']){const copy=structuredClone(f.observation);(copy.screenshots[0] as any)[change]=change==='sha256'?'b'.repeat(64):change==='capturedAt'?new Date(time-1).toISOString():3;assert.deepEqual(decoder.decode({...f,observation:copy,now:time}),[]);}const changed=Buffer.from(f.bytes);changed[40]^=1;assert.deepEqual(decoder.decode({...f,bytes:changed,now:time}),[]);});
test('manifest refuses duplicate images and fields, nonfinite values and oversize meanings',()=>{const f=fixture();assert.throws(()=>new ReviewedFrameDecoder({...f.manifest,entries:[...f.manifest.entries,...f.manifest.entries]}));for(const fields of [[{fieldId:'a',value:Infinity}],[{fieldId:'a',value:'x'.repeat(501)}],[{fieldId:'a',value:1},{fieldId:'a',value:2}]])assert.throws(()=>new ReviewedFrameDecoder({...f.manifest,entries:[{...f.manifest.entries[0],fields}]}));});
