import assert from 'node:assert/strict';
import test,{type TestContext} from 'node:test';
import {createHmac,randomUUID} from 'node:crypto';
import {Duplex,PassThrough} from 'node:stream';
import {createServer,connect} from 'node:net';
import {once} from 'node:events';
import type * as G from '@lifestream/contracts/game-activity';
import {createAuthenticatedGameTransport,GameControlFrameDecoder,encodeGameControlFrame,GameTransportError} from '../src/transport.ts';
import {GameAdapterBoundaryError} from '../src/provider.ts';
const secret=Buffer.alloc(32,23),digest='a'.repeat(64),stamp=()=>new Date().toISOString();
function scope():G.ActivityScope{return {assistantId:randomUUID(),principalId:randomUUID(),relationshipId:randomUUID(),environmentId:randomUUID(),activityId:randomUUID(),runId:randomUUID(),activityEpoch:1,timelineId:randomUUID(),timelineRevision:1,campaignId:randomUUID(),observationDomain:'simulatedGame',contextBinding:{conversationId:randomUUID(),sessionId:randomUUID(),endpointId:randomUUID(),participationKind:'logicalActivity',humanSpeakerRef:null,audioOwnerEndpointId:null,ownerPermissionRef:'synthetic-permission'}};}
function observe(s=scope()):G.GameObserveRequest{return {schemaVersion:'1.0.0',operation:'GameActivityAdapter.observe',requestId:randomUUID(),correlationId:randomUUID(),deadlineAt:new Date(Date.now()+4000).toISOString(),cancellationId:randomUUID(),executionMode:'simulation',scope:s,idempotencyKey:randomUUID(),payload:{expectedPinsDigest:digest,afterActionId:null,maxScreenshots:1}};}
function observed(r:G.GameObserveRequest):G.GameObserveResult{const time=stamp();return {schemaVersion:'1.0.0',operation:r.operation,requestId:r.requestId,correlationId:r.correlationId,providerRef:'scripted-peer',completedAt:time,outcome:{status:'succeeded',error:null,payload:{observation:{schemaVersion:'1.0.0',recordType:'gameObservation',scope:r.scope,observationId:randomUUID(),revision:1,pinsDigest:digest,frameNumber:10,capturedAt:time,receivedAt:time,interpretedAt:null,providerConfigurationRef:null,screenshots:[{screenshotId:randomUUID(),mediaRef:randomUUID(),sha256:digest,byteLength:100,mediaType:'image/png',width:256,height:224,capturedAt:time,frameNumber:10,expiresAt:new Date(Date.now()+10000).toISOString()}],facts:[],visibleState:[],previousActionId:null,untrusted:true},reconciledAction:null}}};}
const neutral={up:false,down:false,left:false,right:false,a:false,b:false,x:false,y:false,l:false,r:false,start:false,select:false} as const;
function action(s=scope()):G.GameActionRequest{const r=observe(s),observationId=randomUUID(),predicateId=randomUUID();return {...r,operation:'GameActivityAdapter.applyController',payload:{actionId:randomUUID(),proposal:{schemaVersion:'1.0.0',recordType:'gameActionProposal',scope:r.scope,proposalId:randomUUID(),observationId,observationRevision:1,preparedViewId:randomUUID(),preparedViewRevision:1,invalidationKey:randomUUID(),buttons:['a'],durationFrames:2,maxWallMs:100,expectedVisibleOutcome:'A synthetic menu may change.',uncertainty:'No real game was run.',adviceRefs:[],reason:'Scripted boundary test.',preconditions:[{predicateId,fieldId:'synthetic-visible-menu',expectedValue:'open',sourceObservationId:observationId}]},admission:{admissionId:randomUUID(),capabilityInvocationId:randomUUID(),authorityContextRef:{providerRef:'synthetic-authority',contextId:randomUUID(),revision:1},dispatchReceipt:{reference:'synthetic-receipt',sha256:digest,mediaType:'application/json',schemaRef:'https://lifestream.dev/contracts/human-authority-decision/2.0.0',byteLength:100},scopeDigest:digest,inputDigest:digest,policyRevision:1,issuedAt:stamp(),expiresAt:new Date(Date.now()+10000).toISOString()},inputOwnerLeaseId:randomUUID(),buttonVector:{...neutral,a:true},protectedMenuOperation:'none',expectedFrameNumber:10,expectedPinsDigest:digest,dispatchValidation:{planningObservationId:observationId,dispatchObservationId:observationId,dispatchObservationRevision:1,checkedFrameNumber:10,checkedAt:stamp(),validatorRef:'synthetic-validator',predicateChecks:[{predicateId,fieldId:'synthetic-visible-menu',observedValue:'open',matched:true,sourceObservationId:observationId}],planningCapturedAt:stamp(),planningFrameNumber:10,preparedContextFreshUntil:new Date(Date.now()+10000).toISOString()}}};}

const context={signal:new AbortController().signal,isCurrent:()=>true};
class Peer{
 readonly stream:Duplex;readonly messages:any[]=[];private waiters:Array<(message:any)=>void>=[];private decoder:GameControlFrameDecoder;
 constructor(stream:Duplex){this.stream=stream;this.decoder=new GameControlFrameDecoder(text=>{const message=JSON.parse(text),waiter=this.waiters.shift();if(waiter)waiter(message);else this.messages.push(message);});stream.on('data',chunk=>this.decoder.push(chunk));stream.on('error',()=>{});}
 next():Promise<any>{if(this.messages.length)return Promise.resolve(this.messages.shift());return new Promise((resolve,reject)=>{const waiter=(message:any)=>{clearTimeout(timer);resolve(message);};const timer=setTimeout(()=>{this.waiters=this.waiters.filter(w=>w!==waiter);reject(Error('No scripted peer message'));},1000);this.waiters.push(waiter);});}
 send(message:unknown):void{this.stream.write(encodeGameControlFrame(JSON.stringify(message)));}
 async authenticate(key=secret,change:(c:any)=>void=()=>{}):Promise<any>{const challenge=await this.next();assert.equal(challenge.type,'challenge');change(challenge);this.send({type:'authenticate',proof:createHmac('sha256',key).update(JSON.stringify(challenge)).digest('hex')});return challenge;}
}
function pair(t:TestContext){const a=new PassThrough(),b=new PassThrough(),host=Duplex.from({readable:a,writable:b}),client=Duplex.from({readable:b,writable:a});t.after(()=>{host.destroy();client.destroy();});return {host,peer:new Peer(client)};}
function setup(t:TestContext,changes:any={}){const {host,peer}=pair(t),s=scope(),failures:string[]=[];
 const transport=createAuthenticatedGameTransport(host,{pairingSecret:secret,scope:s,pinsDigest:digest,authenticationTimeoutMs:500,sessionDurationMs:10000,boundary:{providerRef:'scripted-peer',maxDurationMs:5000,sourceAvailable:()=>true,acceptObservation:()=>true,acceptAction:()=>true,claimEffect:async()=>true,...changes.boundary},onDisconnect:code=>failures.push(code),...changes.options});t.after(()=>transport.close());return {peer,s,failures,transport};}
const boundaryError=(code:string,may=false)=>(e:unknown)=>e instanceof GameAdapterBoundaryError&&e.code===code&&e.effectMayHaveStarted===may;
test('byte framing handles every split of multibyte text and multiple coalesced control messages',()=>{
 const text='{"text":"é 🐈"}',frame=encodeGameControlFrame(text);assert.equal(Number(frame.subarray(0,frame.indexOf(32)).toString()),Buffer.byteLength(text));assert.notEqual(Buffer.byteLength(text),text.length);
 for(let split=0;split<=frame.length;split++){const result:string[]=[],decoder=new GameControlFrameDecoder(value=>result.push(value));decoder.push(frame.subarray(0,split));decoder.push(frame.subarray(split));decoder.finish();assert.deepEqual(result,[text]);}
 const result:string[]=[],decoder=new GameControlFrameDecoder(value=>result.push(value));decoder.push(Buffer.concat([frame,frame,frame]));decoder.finish();assert.deepEqual(result,[text,text,text]);
});
test('framing refuses unbounded/ambiguous lengths, invalid UTF-8, truncated input and raw empty text',async t=>{
 for(const bytes of [Buffer.from('0 '),Buffer.from('01 a'),Buffer.from('-1 '),Buffer.from('131073 '),Buffer.from('9999999'),Buffer.from([49,32,255]),Buffer.alloc(262145)])await t.test(String(bytes.length)+'-'+bytes.subarray(0,8).toString('hex'),()=>{const decoder=new GameControlFrameDecoder(()=>assert.fail('Must not deliver malformed text'));assert.throws(()=>decoder.push(bytes),GameTransportError);assert.throws(()=>decoder.push(Buffer.from('1 a')),GameTransportError);});
 for(const bytes of [Buffer.from('1'),Buffer.from('2 a')]){const decoder=new GameControlFrameDecoder(()=>assert.fail());decoder.push(bytes);assert.throws(()=>decoder.finish(),GameTransportError);}
 assert.throws(()=>encodeGameControlFrame(''),GameTransportError);assert.throws(()=>encodeGameControlFrame('x'.repeat(131073)),GameTransportError);assert.throws(()=>encodeGameControlFrame('\ud800'),GameTransportError);
});
test('an authenticated immutable scope delivers closed typed results; the caller credential remains unchanged',async t=>{
 const {transport,peer,s}=setup(t);await peer.authenticate();await transport.ready;assert.equal((await peer.next()).type,'authenticated');assert.deepEqual(secret,Buffer.alloc(32,23));
 const request=observe(s),pending=transport.adapter.observe(request,context),sent=await peer.next();assert.equal(sent.requestId,request.requestId);peer.send(observed(sent));assert.equal((await pending).outcome.payload!.observation.frameNumber,10);
});
test('requests cannot leave the channel before explicit pairing and authentication never grants source admission',async t=>{
 const {transport,peer,s}=setup(t);const pending=transport.adapter.observe(observe(s),context);assert.equal((await peer.next()).type,'challenge');await new Promise(resolve=>setTimeout(resolve,10));assert.equal(peer.messages.length,0);transport.close();await assert.rejects(pending,boundaryError('invalidResponse'));
 const unavailable=setup(t,{boundary:{sourceAvailable:()=>false}});await assert.rejects(unavailable.transport.adapter.observe(observe(unavailable.s),context),boundaryError('unavailable'));assert.equal((await unavailable.peer.next()).type,'challenge');assert.equal(unavailable.peer.messages.length,0);
});
test('wrong secret, altered challenge scope, stale handshake and noncanonical authentication close without leaking credentials',async t=>{
 for(const mode of ['secret','scope','stale','duplicate'])await t.test(mode,async t=>{const {transport,peer,failures}=setup(t,mode==='stale'?{options:{authenticationTimeoutMs:30}}:{});if(mode==='duplicate'){const c=await peer.next(),proof=createHmac('sha256',secret).update(JSON.stringify(c)).digest('hex');peer.stream.write(encodeGameControlFrame('{"type":"authenticate","type":"authenticate","proof":"'+proof+'"}'));}else if(mode==='stale'){await peer.next();await new Promise(resolve=>setTimeout(resolve,50));}else await peer.authenticate(mode==='secret'?Buffer.alloc(32,24):secret,c=>{if(mode==='scope')c.scopeDigest='b'.repeat(64);});await assert.rejects(transport.ready,e=>e instanceof GameTransportError&&e.code==='authenticationFailed'&&!e.message.includes(secret.toString('hex')));assert.deepEqual(failures,['authenticationFailed']);});
});
test('scope, source and admission are rechecked after the authentication await before any command write',async t=>{
 let available=true,current=true;const {transport,peer,s}=setup(t,{boundary:{sourceAvailable:()=>available}}),pending=transport.adapter.observe(observe(s),{...context,isCurrent:()=>current});const c=await peer.next();available=false;peer.send({type:'authenticate',proof:createHmac('sha256',secret).update(JSON.stringify(c)).digest('hex')});await assert.rejects(pending,boundaryError('invalidResponse'));assert.equal((await peer.next()).type,'authenticated');assert.equal(peer.messages.length,0);current=false;
 await assert.rejects(transport.adapter.observe(observe(s),{...context,isCurrent:()=>current}),boundaryError('scopeChanged'));
 const other=observe({...s,timelineId:randomUUID()});available=true;await assert.rejects(transport.adapter.observe(other,context),boundaryError('invalidResponse'));
});
test('response correlation/provider identity and replay failures close the connection and notify the host once',async t=>{
 for(const mode of ['correlation','provider','unknown','replay'])await t.test(mode,async t=>{const {transport,peer,s,failures}=setup(t);await peer.authenticate();await transport.ready;await peer.next();const pending=transport.adapter.observe(observe(s),context),sent=await peer.next(),result=observed(sent);if(mode==='correlation')result.correlationId=randomUUID();if(mode==='provider')result.providerRef='wrong';if(mode==='unknown')result.requestId=randomUUID();peer.send(result);if(mode==='replay'){await pending;peer.send(result);await new Promise(resolve=>setTimeout(resolve,10));}else await assert.rejects(pending,boundaryError('invalidResponse'));assert.deepEqual(failures,['invalidResponse']);transport.close();assert.equal(failures.length,1);});
});
test('cancelled output is discarded once and cannot be reused or cross-correlated into a successor',async t=>{
 const {transport,peer,s}=setup(t);await peer.authenticate();await transport.ready;await peer.next();const controller=new AbortController(),request=observe(s),pending=transport.adapter.observe(request,{...context,signal:controller.signal}),sent=await peer.next();controller.abort();await assert.rejects(pending,boundaryError('cancelled'));peer.send(observed(sent));
 const next=observe(s),successor=transport.adapter.observe(next,context),sentNext=await peer.next();peer.send(observed(sentNext));assert.equal((await successor).requestId,next.requestId);await assert.rejects(transport.adapter.observe(request,context),boundaryError('invalidResponse'));
});
test('pending capacity is finite and reserves one separate safety-release slot',async t=>{
 const {transport,peer,s}=setup(t);await peer.authenticate();await transport.ready;await peer.next();const abort=new AbortController(),pending=Array.from({length:8},()=>transport.adapter.observe(observe(s),{...context,signal:abort.signal}));for(let i=0;i<8;i++)await peer.next();await assert.rejects(transport.adapter.observe(observe(s),context),boundaryError('invalidResponse'));
 // No safety admission is supplied here: reserved transport capacity cannot
 // itself authorize even a neutral button vector.
 const r=observe(s),release:G.GameReleaseRequest={...r,operation:'GameActivityAdapter.releaseControls',payload:{targetInputOwnerLeaseId:randomUUID(),reason:'policyChanged',neutralButtons:{up:false,down:false,left:false,right:false,a:false,b:false,x:false,y:false,l:false,r:false,start:false,select:false}}};
 await assert.rejects(transport.adapter.releaseControls(release,context),boundaryError('admissionRequired'));abort.abort();await Promise.all(pending.map(p=>assert.rejects(p,boundaryError('cancelled'))));
});
test('real loopback TCP carries scripted control frames, not an emulator or game execution',async t=>{
 const server=createServer();server.on('error',()=>{});t.after(()=>server.close());server.listen(0,'127.0.0.1');await once(server,'listening');const address=server.address();assert.ok(address&&typeof address!=='string');const accepted=once(server,'connection'),client=connect(address.port,'127.0.0.1');client.on('error',()=>{});await once(client,'connect');const [host]=await accepted as [Duplex];t.after(()=>{client.destroy();host.destroy();});const peer=new Peer(client),s=scope(),failures:string[]=[];
 const transport=createAuthenticatedGameTransport(host,{pairingSecret:secret,scope:s,pinsDigest:digest,authenticationTimeoutMs:500,sessionDurationMs:10000,boundary:{providerRef:'scripted-peer',maxDurationMs:5000,sourceAvailable:()=>true,acceptObservation:()=>true},onDisconnect:code=>failures.push(code)});t.after(()=>transport.close());await peer.authenticate();await transport.ready;await peer.next();const pending=transport.adapter.observe(observe(s),context),sent=await peer.next(),reply=encodeGameControlFrame(JSON.stringify(observed(sent)));for(let i=0;i<reply.length;i+=7)client.write(reply.subarray(i,i+7));assert.equal((await pending).outcome.payload!.observation.frameNumber,10);client.end();await once(host,'close');assert.deepEqual(failures,['disconnected']);
});
test('lost controller delivery remains potentially executed with no retry or successor dispatch',async t=>{
 const {transport,peer,s,failures}=setup(t);await peer.authenticate();await transport.ready;await peer.next();const request=action(s),pending=transport.adapter.applyController(request,context),sent=await peer.next();assert.equal(sent.payload.actionId,request.payload.actionId);peer.stream.destroy();await assert.rejects(pending,boundaryError('invalidResponse',true));assert.deepEqual(failures,['disconnected']);
 await assert.rejects(transport.adapter.applyController(action(s),context),boundaryError('concurrentEffect'));assert.equal(peer.messages.length,0);
});
test('an expired effect admission while pairing is held writes no game command',async t=>{
 const {transport,peer,s}=setup(t),request=action(s);request.payload.admission.expiresAt=new Date(Date.now()+50).toISOString();const pending=transport.adapter.applyController(request,context),challenge=await peer.next();await assert.rejects(pending,boundaryError('admissionRequired',true));peer.send({type:'authenticate',proof:createHmac('sha256',secret).update(JSON.stringify(challenge)).digest('hex')});await transport.ready;assert.equal((await peer.next()).type,'authenticated');assert.equal(peer.messages.length,0);
});
test('exact admitted release uses the reserved slot while eight observations await replies',async t=>{
 const {transport,peer,s}=setup(t,{boundary:{admitRelease:async()=>true}});await peer.authenticate();await transport.ready;await peer.next();const controller=new AbortController(),pending=Array.from({length:8},()=>transport.adapter.observe(observe(s),{...context,signal:controller.signal}));for(let i=0;i<8;i++)await peer.next();
 const release:G.GameReleaseRequest={...observe(s),operation:'GameActivityAdapter.releaseControls',payload:{targetInputOwnerLeaseId:randomUUID(),reason:'policyChanged',neutralButtons:{...neutral}}},shutdown=transport.adapter.releaseControls(release,context),sent=await peer.next();assert.equal(sent.operation,'GameActivityAdapter.releaseControls');const time=stamp();peer.send({schemaVersion:'1.0.0',operation:sent.operation,requestId:sent.requestId,correlationId:sent.correlationId,providerRef:'scripted-peer',completedAt:time,outcome:{status:'succeeded',error:null,payload:{targetInputOwnerLeaseId:sent.payload.targetInputOwnerLeaseId,disposition:'neutralizedAndPaused',confirmedAt:time,emulatorPaused:true,buttonsNeutralized:true,pauseFrameNumber:10,verifiedFrameNumber:10,pauseConfirmedMonotonicMs:100,verifiedMonotonicMs:110,activityEpochAfterFence:2,confirmationSource:'adapterObserved',resumeRequiresFreshObservation:true}}});assert.equal((await shutdown).outcome.payload!.disposition,'neutralizedAndPaused');controller.abort();await Promise.all(pending.map(p=>assert.rejects(p,boundaryError('cancelled'))));
});
test('closed schema validation survives authentication and malformed peer bytes trigger host shutdown notification',async t=>{
 const {transport,peer,s,failures}=setup(t);await peer.authenticate();await transport.ready;await peer.next();let pending=transport.adapter.observe(observe(s),context),sent=await peer.next(),result:any=observed(sent);result.outcome.payload.observation.physicalAudience='private';peer.send(result);await assert.rejects(pending,boundaryError('invalidResponse'));assert.equal(failures.length,0);
 pending=transport.adapter.observe(observe(s),context);await peer.next();peer.stream.write(Buffer.from('9999999'));await assert.rejects(pending,boundaryError('invalidResponse'));assert.deepEqual(failures,['invalidFrame']);
});
test('connection scope is copied at creation and a bounded session timeout cannot become reconnection',async t=>{
 const {host,peer}=pair(t),s=scope(),original=structuredClone(s),failures:string[]=[];const transport=createAuthenticatedGameTransport(host,{pairingSecret:secret,scope:s,pinsDigest:digest,authenticationTimeoutMs:50,sessionDurationMs:120,boundary:{providerRef:'scripted-peer',maxDurationMs:5000,sourceAvailable:()=>true,acceptObservation:()=>true},onDisconnect:code=>failures.push(code)});t.after(()=>transport.close());s.timelineId=randomUUID();await peer.authenticate();await transport.ready;await peer.next();const pending=transport.adapter.observe(observe(original),context),sent=await peer.next();assert.equal(sent.scope.timelineId,original.timelineId);await assert.rejects(pending,boundaryError('invalidResponse'));assert.deepEqual(failures,['timedOut']);await assert.rejects(transport.adapter.observe(observe(original),context),boundaryError('invalidResponse'));assert.equal(failures.length,1);
});

test('trusted decoded visible fields preserve the exact native observation source',async t=>{
 const {transport,peer,s}=setup(t,{options:{enrichObservation:(_request:any,o:any)=>({...o,interpretedAt:stamp(),providerConfigurationRef:'reviewed-local-pixels',visibleState:[{fieldId:'synthetic.visible.pixel',value:true,visibility:'visibleNow',firstObservedRef:o.observationId,lastObservedRef:o.observationId,timelineId:o.scope.timelineId,observedAt:o.capturedAt,freshUntil:o.screenshots[0].expiresAt,decoderRevision:'1.0.0',manifestDigest:digest,limitations:['Synthetic source-bound field fixture.']}]})}});
 await peer.authenticate();await transport.ready;await peer.next();const pending=transport.adapter.observe(observe(s),context),sent=await peer.next(),raw=observed(sent);peer.send(raw);const result=await pending;assert.deepEqual(result.outcome.payload!.observation.screenshots,raw.outcome.payload!.observation.screenshots);assert.equal(result.outcome.payload!.observation.frameNumber,raw.outcome.payload!.observation.frameNumber);assert.equal(result.outcome.payload!.observation.visibleState[0]?.lastObservedRef,raw.outcome.payload!.observation.observationId);
});
test('a decoder cannot replace native scope/frame/pins/pixels or action lineage',async t=>{
 for(const key of ['frameNumber','pinsDigest','scope','screenshots','previousActionId'])await t.test(key,async t=>{
  const {transport,peer,s}=setup(t,{options:{enrichObservation:(_request:any,o:any)=>{if(key==='frameNumber')o.frameNumber++;else if(key==='pinsDigest')o.pinsDigest='b'.repeat(64);else if(key==='scope')o.scope.timelineId=randomUUID();else if(key==='screenshots')o.screenshots[0].sha256='b'.repeat(64);else o.previousActionId=randomUUID();return o;}}});await peer.authenticate();await transport.ready;await peer.next();const pending=transport.adapter.observe(observe(s),context),sent=await peer.next();peer.send(observed(sent));await assert.rejects(pending,boundaryError('invalidResponse'));
 });
});
