import test from 'node:test';
import assert from 'node:assert/strict';
import {WindowsHostLifecycle,WindowsHostLifecycleError,inheritedHostIpcAvailable,WINDOWS_HOST_BACKEND_URL} from '../src/windows-host-lifecycle.ts';
const tick=()=>new Promise(resolve=>setTimeout(resolve,0));
function deferred<T>(){let resolve!:(value:T)=>void,reject!:(reason:Error)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no;});return {promise,resolve,reject};}
test('construction and inherited IPC presence never activate an unconfigured host',async()=>{const empty=new WindowsHostLifecycle();assert.equal(empty.snapshot.state,'unconfigured');assert.equal(empty.snapshot.attempted,false);assert.equal(inheritedHostIpcAvailable({connected:true,send(){}}),true);await assert.rejects(empty.start(),error=>error instanceof WindowsHostLifecycleError&&error.code==='unconfigured');assert.equal(empty.snapshot.attempted,false);assert.equal(empty.snapshot.pauseConfirmation,'unconfirmed');assert.equal(inheritedHostIpcAvailable({connected:false,send(){}}),false);});
test('missing contract and denied authentication make zero connection/driver attempts',async()=>{let connects=0,drives=0;const reasons:string[]=[];const base={connectAuthenticated:async()=>{connects++;return {close(){}};},isSessionCurrent:()=>false,onFence:(reason:string)=>reasons.push(reason),connectionTimeoutMs:100,sessionDurationMs:1000};const missing=new WindowsHostLifecycle(base);await assert.rejects(missing.start(),/unconfigured/);const denied=new WindowsHostLifecycle({...base,driveContract:async()=>{drives++;}});await assert.rejects(denied.start(),/denied/);assert.equal(connects,0);assert.equal(drives,0);assert.deepEqual(reasons,['denied']);await assert.rejects(denied.start(),/closed/);});
test('finite connection deadline fences immediately and disposes a late connection without driving',{timeout:3000},async()=>{const opened=deferred<{close():void}>();let closed=0,driven=0;const reasons:string[]=[];const host=new WindowsHostLifecycle({connectAuthenticated:()=>opened.promise,isSessionCurrent:()=>true,onFence:reason=>reasons.push(reason),driveContract:async()=>{driven++;},connectionTimeoutMs:25,sessionDurationMs:500});await assert.rejects(host.start(),/connectionDeadline/);assert.deepEqual(reasons,['connectionDeadline']);opened.resolve({close(){closed++;}});await tick();assert.equal(closed,1);assert.equal(driven,0);await assert.rejects(host.start(),/closed/);assert.equal(host.snapshot.pauseConfirmation,'unconfirmed');});
test('scope revocation during authentication prevents the first driver call',async()=>{let current=true,closed=0,driven=0;const opened=deferred<{close():void}>();const host=new WindowsHostLifecycle({connectAuthenticated:()=>opened.promise,isSessionCurrent:()=>current,onFence(){},driveContract:async()=>{driven++;},connectionTimeoutMs:500,sessionDurationMs:1000});const running=host.start();await tick();current=false;opened.resolve({close(){closed++;}});await assert.rejects(running,/scopeChanged/);assert.equal(closed,1);assert.equal(driven,0);});
test('parent cancellation fences before connection close and settles an uncooperative driver',{timeout:3000},async()=>{const stop=new AbortController(),events:string[]=[];const began=deferred<void>();const host=new WindowsHostLifecycle({connectAuthenticated:async context=>{assert.equal(context.backendUrl,WINDOWS_HOST_BACKEND_URL);return {close(){events.push('close');}};},isSessionCurrent:()=>true,onFence:()=>events.push('fence'),driveContract:async()=>{began.resolve();await new Promise(()=>{});},connectionTimeoutMs:500,sessionDurationMs:1000});const running=host.start(stop.signal);await began.promise;stop.abort();await assert.rejects(running,/cancelled/);assert.deepEqual(events,['fence','close']);assert.equal(host.snapshot.pauseConfirmation,'unconfirmed');await assert.rejects(host.start(),/closed/);});
test('connected dispatch recheck closes a revoked session without fabricating pause evidence',async()=>{let current=true;const began=deferred<void>(),gate=deferred<void>();let closes=0;const host=new WindowsHostLifecycle({connectAuthenticated:async()=>({close(){closes++;}}),isSessionCurrent:()=>current,onFence(){},driveContract:async(_connection,context)=>{began.resolve();await gate.promise;context.assertSessionCurrent();},connectionTimeoutMs:500,sessionDurationMs:1000});const running=host.start();await began.promise;current=false;gate.resolve();await assert.rejects(running,/scopeChanged/);assert.equal(closes,1);assert.equal(host.snapshot.pauseConfirmation,'unconfirmed');});
test('disconnect and normal session end are terminal, not reconciliation or resume authority',async()=>{for(const interrupted of [false,true]){let connects=0,closes=0;const host=new WindowsHostLifecycle({connectAuthenticated:async()=>{connects++;return {close(){closes++;}};},isSessionCurrent:()=>true,onFence(){},driveContract:async()=>{if(interrupted)throw Error('Synthetic disconnect');},connectionTimeoutMs:500,sessionDurationMs:1000});if(interrupted)await assert.rejects(host.start(),/disconnected/);else await host.start();assert.equal(host.snapshot.reason,interrupted?'disconnected':'sessionEnded');assert.equal(host.snapshot.pauseConfirmation,'unconfirmed');await assert.rejects(host.start(),/closed/);assert.equal(connects,1);assert.equal(closes,1);}});
test('finite session expiration and throwing cleanup cannot become a safe-pause claim',{timeout:3000},async()=>{let closes=0;const host=new WindowsHostLifecycle({connectAuthenticated:async()=>({close(){closes++;throw Error('Synthetic cleanup failure');}}),isSessionCurrent:()=>true,onFence(){throw Error('Synthetic fence notification failure');},driveContract:async()=>new Promise(()=>{}),connectionTimeoutMs:10,sessionDurationMs:30});await assert.rejects(host.start(),/expired/);assert.equal(closes,1);assert.equal(host.snapshot.fenceRequested,true);assert.equal(host.snapshot.pauseConfirmation,'unconfirmed');});
