import assert from 'node:assert/strict';
import test from 'node:test';
import {mkdtemp,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Database} from '@lifestream/storage-sqlite';
import {UnderstandingWorkCoordinator} from '@lifestream/runtime/understanding/coordinator';
import {AcknowledgmentCatalogService,acknowledgmentPhrases,validateAcknowledgmentTrack,type AcknowledgmentAlignment} from '../src/runtime/acknowledgments.ts';
import {defaultVoiceSettings} from '../src/runtime/voice-settings.ts';
import {createLifestreamServer} from '../src/index.ts';
import {loadProfile} from '../src/config/loader.ts';
import {FixtureInferenceProvider} from '@lifestream/runtime/inference/fixture';
import {savedVoiceFixture} from './saved-voice-fixture.ts';
import {randomBytes} from 'node:crypto';

const phrases=['I am listening.','Let me think.','One moment.','I hear you.','Let me consider that.','Hmm.','I see.','All right.','Let me take a look.','Okay.'];
async function setup(t:any,paired=false){
 const root=await mkdtemp(join(tmpdir(),'ack-catalog-'));t.after(()=>rm(root,{recursive:true,force:true}));const db=new Database({path:join(root,'state.sqlite')});db.migrate();t.after(()=>db.close());
 const state={now:Date.parse('2026-09-01T10:00:00Z'),binding:'voice-1',llm:0,tts:0,alignment:0,fail:false,failAlignment:false,beforePublish:undefined as undefined|(()=>void),analysis:'analysis-1'};
 const coordinator=new UnderstandingWorkCoordinator({now:()=>state.now,pressureAllowsWork:()=>true});
 const alignment=():AcknowledgmentAlignment=>({cueSet:'fixture-open-rest',analysisRevision:state.analysis,cues:['open','rest'],align:async(_audio,metadata)=>{state.alignment++;if(state.failAlignment)throw Error('alignment failed');return {schemaVersion:'1.0.0',cueSet:'fixture-open-rest',analysisRevision:state.analysis,timeUnit:'ms',timeOrigin:'audio-start',audioSha256:metadata.sha256,durationMs:metadata.durationMs,cues:[{startMs:0,endMs:metadata.durationMs,cue:'open'}]};}});
 const host={now:()=>state.now,voice:()=>({settings:{...defaultVoiceSettings},voiceProfile:{voiceRef:'saved-voice:fixture',revision:1},binding:state.binding,language:'en',current:()=>true}),priority:()=>({preemptionBoundMs:0,slotReleaseBoundMs:0}),run:coordinator.run.bind(coordinator),propose:async()=>{state.llm++;return phrases;},synthesize:async(text:string)=>{state.tts++;if(state.fail)throw Error('synthesis failed');state.beforePublish?.();return Buffer.alloc(9600,phrases.indexOf(text)+1);},...(paired?{alignment,requiresSync:()=>true}:{} )};
 const service=new AcknowledgmentCatalogService(db,root,host);t.after(()=>service.close());const c=service.current('assistant').catalog;service.repository.configure('assistant',c.revision,true,5);
 return {root,db,state,service,host,coordinator,alignment};
}
test('catalog generation publishes five complete pairs, survives restart and repairs only missing tracks',async t=>{
 const {db,state,service,host,root}=await setup(t,true);await service.maintain('assistant');let m=await service.manifest('assistant');assert.equal(m.readyCount,5);assert.equal(m.synchronizedReadyCount,5);assert.equal(state.llm,1);assert.equal(state.tts,5);
 const previous=m.clips.map(c=>({id:c.id,audio:c.audio,expiresAt:c.expiresAt}));service.close();const restarted=new AcknowledgmentCatalogService(db,root,host);t.after(()=>restarted.close());state.analysis='analysis-2';await restarted.maintain('assistant');m=await restarted.manifest('assistant');assert.equal(state.tts,5);assert.equal(state.llm,1);assert.equal(state.alignment,10);assert.deepEqual(m.clips.map(c=>({id:c.id,audio:c.audio,expiresAt:c.expiresAt})),previous);
});
test('overdue clips remain ready, one oldest rotates per UTC day across concurrency, restart and missed days',async t=>{
 const {db,state,service,host,root}=await setup(t,true);await service.maintain('assistant');const original=service.repository.get('assistant')!,oldest=[...original.clips].sort((a,b)=>a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id))[0]!;
 state.now+=6*86400000;assert.equal((await service.manifest('assistant')).readyCount,5);await Promise.all([service.maintain('assistant'),service.maintain('assistant')]);let c=service.repository.get('assistant')!;assert.equal(c.clips.length,5);assert.ok(!c.clips.some(x=>x.id===oldest.id));assert.equal(state.tts,6);const ids=c.clips.map(x=>x.id);
 service.close();const restarted=new AcknowledgmentCatalogService(db,root,host);t.after(()=>restarted.close());await restarted.maintain('assistant');assert.deepEqual(restarted.repository.get('assistant')!.clips.map(x=>x.id),ids);state.now+=10*86400000;await restarted.maintain('assistant');c=restarted.repository.get('assistant')!;assert.equal(c.clips.length,5);assert.equal(state.tts,7);assert.equal(c.clips.filter(x=>ids.includes(x.id)).length,4);
});
test('failed synthesis or alignment and concurrent pin retain the old usable pool',async t=>{
 const {state,service}=await setup(t,true);await service.maintain('assistant');const original=service.repository.get('assistant')!,ids=original.clips.map(x=>x.id);state.now+=6*86400000;
 state.fail=true;await service.maintain('assistant');assert.deepEqual(service.repository.get('assistant')!.clips.map(x=>x.id),ids);state.fail=false;state.failAlignment=true;await service.maintain('assistant');assert.equal((await service.manifest('assistant')).synchronizedReadyCount,5);assert.deepEqual(service.repository.get('assistant')!.clips.map(x=>x.id),ids);state.failAlignment=false;
 const oldest=[...original.clips].sort((a,b)=>a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id))[0]!;state.beforePublish=()=>{state.beforePublish=undefined;const c=service.repository.get('assistant')!;service.repository.edit('assistant',c.revision,oldest.id,oldest.revision,null,state.now);};await service.maintain('assistant');const next=service.repository.get('assistant')!;assert.deepEqual(next.clips.map(x=>x.id),ids);assert.equal(next.clips.find(x=>x.id===oldest.id)?.expiresAt,null);assert.equal(next.lastSweepDay,null);
});
test('missing audio refills only deficits; voice changes fence favorites; disabled catalogs do no work',async t=>{
 const {state,service,root}=await setup(t);await service.maintain('assistant');const old=service.repository.get('assistant')!;await writeFile(join(root,'acknowledgments',old.clips[0]!.audio.sha256),'broken');await rm(join(root,'acknowledgments',old.clips[1]!.audio.sha256));assert.equal((await service.manifest('assistant')).readyCount,3);
 await service.maintain('assistant');assert.equal((await service.manifest('assistant')).readyCount,5);assert.equal(state.tts,7);let c=service.repository.get('assistant')!;service.repository.edit('assistant',c.revision,c.clips[0]!.id,c.clips[0]!.revision,null,state.now);state.binding='voice-2';assert.equal((await service.manifest('assistant')).readyCount,0);await service.maintain('assistant');assert.equal((await service.manifest('assistant')).readyCount,5);assert.equal(state.tts,12);c=service.repository.get('assistant')!;service.repository.configure('assistant',c.revision,false,10);state.now+=20*86400000;await service.maintain('assistant');assert.equal(state.tts,12);
});
test('foreground admission suppresses maintenance and aborts work already preparing audio',async t=>{
 const {service,state,coordinator,host}=await setup(t);let release=coordinator.foregroundStarted();await service.maintain('assistant');assert.equal(state.llm,0);assert.equal(state.tts,0);release();
 let entered!:()=>void;const started=new Promise<void>(r=>{entered=r;});host.synthesize=async(_text:string,signal?:AbortSignal)=>{state.tts++;entered();await new Promise<void>(r=>signal!.addEventListener('abort',()=>r(),{once:true}));return Buffer.alloc(9600);};
 const pending=service.maintain('assistant');await started;release=coordinator.foregroundStarted();await pending;assert.equal((await service.manifest('assistant')).readyCount,0);release();
});
test('administration preserves indefinite expiry and rejects stale and invalid edits',async t=>{
 const {service,state}=await setup(t);await service.maintain('assistant');let c=service.repository.get('assistant')!,clip=c.clips[0]!;assert.throws(()=>service.repository.configure('assistant',c.revision,true,0));assert.throws(()=>service.repository.configure('assistant',c.revision,true,1.5));c=service.repository.edit('assistant',c.revision,clip.id,clip.revision,null,state.now);assert.equal(c.clips[0]!.expiresAt,null);assert.throws(()=>service.repository.edit('assistant',c.revision,clip.id,clip.revision,'remove',state.now));clip=c.clips[0]!;c=service.repository.edit('assistant',c.revision,clip.id,clip.revision,new Date(state.now+86400000).toISOString(),state.now);assert.notEqual(c.clips[0]!.expiresAt,null);c=service.repository.edit('assistant',c.revision,clip.id,c.clips[0]!.revision,'remove',state.now);assert.equal(c.clips.length,4);await service.maintain('assistant');assert.equal((await service.manifest('assistant')).readyCount,5);
});
test('proposal and viseme validation reject duplicate, action-success and malformed timing claims',()=>{
 assert.deepEqual(acknowledgmentPhrases(['I am listening.','I am listening.','Done.','I saved your file.','Everything is safe.','I will do it.','x '.repeat(9)+'.','[bad].']),['I am listening.']);
 const audio={sha256:'a'.repeat(64),bytes:9600,format:'pcm_s16le' as const,sampleRateHz:48000 as const,channels:1 as const,durationMs:100},alignment={cueSet:'set',analysisRevision:'rev',cues:['open']},track={schemaVersion:'1.0.0',cueSet:'set',analysisRevision:'rev',timeUnit:'ms',timeOrigin:'audio-start',audioSha256:audio.sha256,durationMs:100,cues:[{startMs:0,endMs:100,cue:'open'}]};assert.ok(validateAcknowledgmentTrack(track,audio,alignment));
 for(const patch of [{audioSha256:'b'.repeat(64)},{timeOrigin:'request-start'},{cueSet:'other'},{cues:[{startMs:0,endMs:101,cue:'open'}]},{cues:[{startMs:NaN,endMs:10,cue:'open'}]},{cues:[{startMs:0,endMs:80,cue:'open'},{startMs:60,endMs:90,cue:'open'}]}])assert.throws(()=>validateAcknowledgmentTrack({...track,...patch},audio,alignment));
});
test('authenticated catalog APIs prepare in the background and fence audience, revisions and foreign artifacts',async t=>{
 const root=await mkdtemp(join(tmpdir(),'ack-http-'));t.after(()=>rm(root,{recursive:true,force:true}));const fixture=await savedVoiceFixture();t.after(fixture.close);const original=FixtureInferenceProvider.prototype.generate,requests:any[]=[];
 FixtureInferenceProvider.prototype.generate=async function*(request){requests.push(request);yield {kind:'text',text:JSON.stringify(phrases)};yield {kind:'done'};};t.after(()=>{FixtureInferenceProvider.prototype.generate=original;});
 const config=loadProfile('test');config.providers.tts='voxcpm';config.ttsProfile=fixture.profile;config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex'),app=createLifestreamServer({config,audiencePrivacy:{},localAuth:{stateDirectory:join(root,'safety'),installerToken}});await app.start();t.after(()=>app.shutdown());
 const base=`http://127.0.0.1:${app.address().port}`;let cookie='',csrf='';const call=(path:string,body?:unknown,headers={})=>fetch(base+path,{method:body===undefined?'GET':'POST',headers:{origin:base,cookie,'content-type':'application/json','x-lifestream-csrf':csrf,...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});
 const setup=await call('/api/auth/v1/setup',{username:'synthetic-owner',password:randomBytes(32).toString('hex'),installerToken});cookie=setup.headers.get('set-cookie')!.split(';')[0]!;csrf=(await setup.json()).session.csrfToken;let state=await (await call('/api/runtime/v1/session-context')).json();await call('/api/runtime/v1/session-context',{expectedRevision:state.revision,mode:'text',audienceScope:'authenticatedSession'});await call('/api/runtime/v1/audience',{mode:'solo',seconds:300});
 const a=await (await call('/api/admin/v1/assistants',{displayName:'Synthetic acknowledgment Assistant'})).json();await call(`/api/admin/v1/assistants/${a.assistantId}/activate`,{profileId:a.profile.profileId,expectedActiveRevision:null});const path=`/api/admin/v1/assistants/${a.assistantId}/acknowledgments`;state=await (await call(path)).json();assert.equal(state.enabled,false);assert.equal(state.readyCount,0);assert.equal(requests.length,0);
 const enable={operation:'configure',expectedRevision:state.revision,enabled:true,defaultTtlDays:5};assert.equal((await call(path,enable,{'x-lifestream-csrf':'wrong'})).status,403);assert.equal((await call(path,enable)).status,200);
 for(let i=0;i<100;i++){state=await (await call(path)).json();if(state.readyCount===5)break;await new Promise(r=>setTimeout(r,20));}assert.equal(state.readyCount,5);assert.equal(state.synchronizedReadyCount,0);assert.equal(state.alignment,'unavailable');assert.equal(requests.length,1);assert.equal(fixture.requests.length,5);assert.doesNotMatch(JSON.stringify(state),/voiceDesign|dataBase64|transcript|Synthetic acknowledgment Assistant/);
 const request=requests[0];for(const kind of ['preparedMemory','worldContext','conversation'])assert.doesNotMatch(request.sections.find((s:any)=>s.kind===kind).content,/Synthetic acknowledgment/);assert.equal(request.scope.assistantId,'acknowledgment-catalog');
 const artifact=path+'/audio/'+state.clips[0].audio.sha256;assert.equal((await call(artifact)).status,200);assert.equal((await call(path+'/audio/'+'a'.repeat(64))).status,404);assert.equal((await call(path,enable)).status,422,'stale config cannot overwrite new catalog');
 await call('/api/runtime/v1/audience',{mode:'shared',seconds:300});assert.equal((await call(path)).status,403);assert.equal((await call(artifact)).status,403);await call('/api/auth/v1/sign-out',{});assert.equal((await call(path)).status,401);
});
