import assert from 'node:assert/strict';
import {test} from 'node:test';
import {mkdtemp,mkdir,writeFile,readFile,rm,cp,symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes,randomUUID,createHash} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {snapshotCandidate,restoreCandidate} from '../src/admin/candidate-snapshot.ts';
import {createLifestreamServer} from '../src/index.ts';
import {loadProfile} from '../src/config/loader.ts';

async function fixture(t:any){
 const root=await mkdtemp(join(tmpdir(),'candidate-recovery-'));t.after(()=>rm(root,{recursive:true,force:true}));const candidate=join(root,'candidate'),packages=join(root,'packages');await mkdir(candidate);await mkdir(join(packages,'synthetic'),{recursive:true});await writeFile(join(candidate,'candidate.json'),JSON.stringify({schemaVersion:'1.0.0',profile:'test'}));
 const model=JSON.stringify({asset:{version:'2.0'},scenes:[{nodes:[]}],scene:0});const manifest={schemaVersion:'1.0.0',id:'synthetic',version:'1',label:'Synthetic',renderer:'three-glb.v1',model:'model.gltf',resources:[{path:'model.gltf',bytes:Buffer.byteLength(model),sha256:createHash('sha256').update(model).digest('hex'),mime:'model/gltf+json'}],framing:{distance:1,targetHeight:.5},animations:{},capabilities:{lipSync:'none',facialAnimation:false},fallback:'neutral'};
 await writeFile(join(packages,'index.json'),'["synthetic"]');await writeFile(join(packages,'synthetic/manifest.json'),JSON.stringify(manifest));await writeFile(join(packages,'synthetic/model.gltf'),model);await writeFile(join(packages,'unrelated-source.txt'),'Do not include undeclared source files');
 const config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(candidate,'data.sqlite'),artifactDirectory:join(candidate,'artifacts')};const installerToken=randomBytes(32).toString('hex'),password=randomBytes(32).toString('hex');let app=createLifestreamServer({config,localAuth:{stateDirectory:join(candidate,'safety'),installerToken},presentationPackages:{directory:packages}});await app.start();t.after(()=>app.shutdown());let base=`http://127.0.0.1:${app.address().port}`;const headers:Record<string,string>={origin:base,'content-type':'application/json'};
 const request=(path:string,body?:unknown)=>fetch(base+path,{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:JSON.stringify(body)})});const api=async(path:string,body?:unknown)=>{const r=await request(path,body),data=await r.json() as any;assert.ok(r.ok,JSON.stringify(data));return data;};
 const setup=await request('/api/auth/v1/setup',{username:'owner',password,installerToken});headers.cookie=setup.headers.get('set-cookie')!.split(';')[0]!;const identity=await setup.json() as any;headers['x-lifestream-csrf']=identity.session.csrfToken;
 const assistant=await api('/api/admin/v1/assistants',{displayName:'Synthetic recovery'});await api(`/api/admin/v1/assistants/${assistant.assistantId}/activate`,{profileId:assistant.profile.profileId,expectedActiveRevision:null});await api('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'});
 const item=(await api('/api/runtime/v1/presentation')).packages[0];await api('/api/runtime/v1/presentation',{scope:'default',id:item.id,digest:item.digest,expectedRevision:0});await api('/api/runtime/v1/presentation',{scope:'session',id:'neutral',digest:'neutral-v1',expectedRevision:0});
 const relationship=(await api(`/api/admin/v1/assistants/${assistant.assistantId}/relationships`,{})).relationship,path=`/api/admin/v1/assistants/${assistant.assistantId}/relationships/${relationship.relationshipId}`;
 const record=(await api(path+'/candidates',{content:'SYNTHETIC_FORGET_AFTER_BACKUP',source:'synthetic',sourceFamily:'recovery-test',uncertainty:'low',expectedRevision:relationship.revision,idempotencyKey:randomUUID()})).candidate;
 return {root,candidate,packages,config,password,identity,headers,request,api,path,record,async startRestore(directory:string){await app.shutdown();const restored=structuredClone(config);restored.storage={databasePath:join(directory,'data.sqlite'),artifactDirectory:join(directory,'artifacts')};app=createLifestreamServer({config:restored,localAuth:{stateDirectory:join(directory,'safety')},presentationPackages:{directory:join(directory,'packages')}});await app.start();base=`http://127.0.0.1:${app.address().port}`;headers.origin=base;}};
}
test('consistent export and isolated restore replay newer forgetting and authentication safety, preserve package defaults and quarantine authority',async t=>{
 const f=await fixture(t),snapshot=join(f.root,'snapshot');const manifest=await snapshotCandidate({candidate:f.candidate,packages:f.packages,destination:snapshot});assert.equal(manifest.packageCount,1);assert.ok(!manifest.files.some(f=>f.path.includes('unrelated-source')));
 const relationship=(await f.api(f.path)).relationship;await f.api(f.path+'/privacy',{action:'forget-derived-information',expectedRevision:relationship.revision,idempotencyKey:randomUUID(),targets:[{kind:'record',id:f.record.candidateId,revision:1}]});
 const newPassword=randomBytes(32).toString('hex');await f.api('/api/auth/v1/recover',{username:'owner',recoveryCode:f.identity.recoveryCodes[0],newPassword});
 const destination=join(f.root,'restored'),receipt=await restoreCandidate({snapshot,currentSafety:join(f.candidate,'safety'),destination});assert.equal(receipt.authority,'quarantined');assert.equal(receipt.safetyEpoch,manifest.safetyEpoch+1);
 const db=new DatabaseSync(join(destination,'data.sqlite'),{readOnly:true});const restored=JSON.parse(String(db.prepare('SELECT payload_json FROM assistant_relationships').get()!.payload_json));assert.equal(restored.candidates[0].content,'');assert.equal(db.prepare('SELECT COUNT(*) AS n FROM local_sessions WHERE revoked=0').get()!.n,0);assert.equal(db.prepare("SELECT COUNT(*) AS n FROM presentation_selections WHERE scope_id<>'default'").get()!.n,0);assert.equal(db.prepare("SELECT package_id FROM presentation_selections WHERE scope_id='default'").get()!.package_id,'synthetic');db.close();
 await f.startRestore(destination);assert.equal((await f.request('/api/auth/v1/session')).status,401);assert.equal((await f.request('/api/runtime/v1/recovery')).status,401);assert.equal((await f.request('/api/auth/v1/sign-in',{username:'owner',password:f.password})).status,401);assert.equal((await f.request('/api/auth/v1/recover',{username:'owner',recoveryCode:f.identity.recoveryCodes[0],newPassword:f.password})).status,401);
 const signIn=await f.request('/api/auth/v1/sign-in',{username:'owner',password:newPassword});assert.equal(signIn.status,200);f.headers.cookie=signIn.headers.get('set-cookie')!.split(';')[0]!;f.headers['x-lifestream-csrf']=(await signIn.json() as any).session.csrfToken;
 assert.equal((await f.api('/api/runtime/v1/recovery')).quarantined,true);assert.equal((await f.request('/api/authority/v1/grants')).status,423);assert.equal((await f.api('/api/runtime/v1/audience')).privateAllowed,false);
 const dangerous=structuredClone(f.config);dangerous.storage.databasePath=join(destination,'data.sqlite');assert.throws(()=>createLifestreamServer({config:dangerous,host:'0.0.0.0'}),/quarantined/);
});
test('recovery rejects changed bytes, missing current safety, old epochs, unavailable selections, symlinks and overwrite',async t=>{
 const f=await fixture(t),snapshot=join(f.root,'snapshot');await snapshotCandidate({candidate:f.candidate,packages:f.packages,destination:snapshot});
 await assert.rejects(restoreCandidate({snapshot,currentSafety:join(f.candidate,'safety'),destination:f.candidate}),/EEXIST/);
 const stale=join(f.root,'stale');await cp(join(f.candidate,'safety'),stale,{recursive:true});await writeFile(join(stale,`epoch-${f.identity.session.principalId}`),'0');await assert.rejects(restoreCandidate({snapshot,currentSafety:stale,destination:join(f.root,'bad-epoch')}),/epoch is stale/);
 await rm(join(stale,'authentication-key'));await assert.rejects(restoreCandidate({snapshot,currentSafety:stale,destination:join(f.root,'bad-safety')}),/incomplete|epoch is stale/);
 await writeFile(join(snapshot,'packages/synthetic/model.gltf'),'tampered');await assert.rejects(restoreCandidate({snapshot,currentSafety:join(f.candidate,'safety'),destination:join(f.root,'bad-bytes')}),/differ/);
 const db=new DatabaseSync(join(f.candidate,'data.sqlite'));db.prepare("UPDATE presentation_selections SET package_digest='unavailable'").run();db.close();await snapshotCandidate({candidate:f.candidate,packages:f.packages,destination:join(f.root,'old-selection')});const restored=await restoreCandidate({snapshot:join(f.root,'old-selection'),currentSafety:join(f.candidate,'safety'),destination:join(f.root,'unavailable-selection')});assert.equal(restored.unavailableDefaultPresentations,1);
 await symlink(join(f.root,'stale'),join(f.candidate,'safety/link'));await assert.rejects(snapshotCandidate({candidate:f.candidate,packages:f.packages,destination:join(f.root,'bad-link')}),/symbolic/);
});
