import assert from 'node:assert/strict';
import {test} from 'node:test';
import {mkdtemp,mkdir,writeFile,readFile,rm,cp,symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes,randomUUID,createHash} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {Database,MemoryRepository,ExperienceRepository} from '@lifestream/storage-sqlite';
import {defaultTopics,type ExperienceScope,type ExperiencePolicy,type Source} from '@lifestream/contracts/experience';
import {snapshotCandidate,restoreCandidate} from '../src/admin/candidate-snapshot.ts';
import {createLifestreamServer} from '../src/index.ts';
import {loadProfile} from '../src/config/loader.ts';

async function fixture(t:any){
 const root=await mkdtemp(join(tmpdir(),'candidate-recovery-'));t.after(()=>rm(root,{recursive:true,force:true}));const candidate=join(root,'candidate'),packages=join(root,'packages');await mkdir(candidate);await mkdir(join(packages,'synthetic'),{recursive:true});await writeFile(join(candidate,'candidate.json'),JSON.stringify({schemaVersion:'1.0.0',profile:'test'}));
 const model=JSON.stringify({asset:{version:'2.0'},scenes:[{nodes:[]}],scene:0});const manifest={schemaVersion:'1.0.0',id:'synthetic',version:'1',label:'Synthetic',renderer:'three-glb.v1',model:'model.gltf',resources:[{path:'model.gltf',bytes:Buffer.byteLength(model),sha256:createHash('sha256').update(model).digest('hex'),mime:'model/gltf+json'}],framing:{distance:1,targetHeight:.5},animations:{},capabilities:{lipSync:'none',facialAnimation:false},fallback:'neutral'};
 await writeFile(join(packages,'index.json'),'["synthetic"]');await writeFile(join(packages,'synthetic/manifest.json'),JSON.stringify(manifest));await writeFile(join(packages,'synthetic/model.gltf'),model);await writeFile(join(packages,'unrelated-source.txt'),'Do not include undeclared source files');
 const config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(candidate,'data.sqlite'),artifactDirectory:join(candidate,'artifacts')};const installerToken=randomBytes(32).toString('hex'),password=randomBytes(32).toString('hex');let app=createLifestreamServer({config,localAuth:{stateDirectory:join(candidate,'safety'),installerToken},presentationPackages:{directory:packages}});await app.start();t.after(()=>app.shutdown());let base=`http://127.0.0.1:${app.address().port}`;const headers:Record<string,string>={origin:base,'content-type':'application/json'};
 const request=(path:string,body?:unknown)=>fetch(base+path,{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:JSON.stringify(body)})});const api=async(path:string,body?:unknown)=>{const r=await request(path,body),data=await r.json() as any;assert.ok(r.ok,JSON.stringify(data));return data;};
 const setup=await request('/api/auth/v1/setup',{username:'owner',password,installerToken});headers.cookie=setup.headers.get('set-cookie')!.split(';')[0]!;const identity=await setup.json() as any;headers['x-lifestream-csrf']=identity.session.csrfToken;
 const assistant=await api('/api/admin/v1/assistants',{displayName:'Synthetic recovery',adaptivePersonaPolicy:{dimensions:['attentionGardening','attentionReading'].map(key=>({key,valueType:'number',minimum:-1,maximum:1,maxDeltaPerDreamingRun:.05,sensitive:false,activation:'automatic'}))}});await api(`/api/admin/v1/assistants/${assistant.assistantId}/activate`,{profileId:assistant.profile.profileId,expectedActiveRevision:null});await api('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'});
 const item=(await api('/api/runtime/v1/presentation')).packages[0];await api('/api/runtime/v1/presentation',{scope:'default',id:item.id,digest:item.digest,expectedRevision:0});await api('/api/runtime/v1/presentation',{scope:'session',id:'neutral',digest:'neutral-v1',expectedRevision:0});
 const relationship=(await api(`/api/admin/v1/assistants/${assistant.assistantId}/relationships`,{})).relationship,path=`/api/admin/v1/assistants/${assistant.assistantId}/relationships/${relationship.relationshipId}`;
 const record=(await api(path+'/candidates',{content:'SYNTHETIC_FORGET_AFTER_BACKUP',source:'synthetic',sourceFamily:'recovery-test',uncertainty:'low',expectedRevision:relationship.revision,idempotencyKey:randomUUID()})).candidate;
 return {root,candidate,packages,config,password,identity,headers,request,api,path,record,assistant,relationship,async startRestore(directory:string){await app.shutdown();const restored=structuredClone(config);restored.storage={databasePath:join(directory,'data.sqlite'),artifactDirectory:join(directory,'artifacts')};app=createLifestreamServer({config:restored,localAuth:{stateDirectory:join(directory,'safety')},presentationPackages:{directory:join(directory,'packages')}});await app.start();base=`http://127.0.0.1:${app.address().port}`;headers.origin=base;}};
}
test('consistent export and isolated restore replay newer forgetting and authentication safety, preserve package defaults and quarantine authority',async t=>{
 const f=await fixture(t),snapshot=join(f.root,'snapshot');const manifest=await snapshotCandidate({candidate:f.candidate,packages:f.packages,destination:snapshot});assert.equal(manifest.packageCount,1);assert.ok(!manifest.files.some(f=>f.path.includes('unrelated-source')));
 const relationship=(await f.api(f.path)).relationship;await f.api(f.path+'/privacy',{action:'forget-derived-information',expectedRevision:relationship.revision,idempotencyKey:randomUUID(),targets:[{kind:'record',id:f.record.candidateId,revision:1}]});
 const newPassword=randomBytes(32).toString('hex');await f.api('/api/auth/v1/recover',{username:'owner',recoveryCode:f.identity.recoveryCodes[0],newPassword});
 const destination=join(f.root,'restored'),receipt=await restoreCandidate({snapshot,currentSafety:join(f.candidate,'safety'),destination});assert.equal(receipt.authority,'quarantined');assert.equal(receipt.safetyEpoch,manifest.safetyEpoch+1);
 const db=new DatabaseSync(join(destination,'data.sqlite'),{readOnly:true});const restored=JSON.parse(String(db.prepare('SELECT payload_json FROM assistant_relationships').get()!.payload_json));assert.equal(restored.candidates[0].content,'');assert.equal(db.prepare('SELECT COUNT(*) AS n FROM local_sessions WHERE revoked=0').get()!.n,0);assert.equal(db.prepare("SELECT COUNT(*) AS n FROM presentation_selections WHERE scope_id<>'default'").get()!.n,0);assert.equal(db.prepare("SELECT package_id FROM presentation_selections WHERE scope_id='default'").get()!.package_id,'synthetic');db.close();
 await f.startRestore(destination);assert.equal((await f.request('/api/auth/v1/session')).status,401);assert.equal((await f.request('/api/runtime/v1/recovery')).status,401);assert.equal((await f.request('/api/auth/v1/sign-in',{username:'owner',password:f.password})).status,401);assert.equal((await f.request('/api/auth/v1/recover',{username:'owner',recoveryCode:f.identity.recoveryCodes[0],newPassword:f.password})).status,401);
 const signIn=await f.request('/api/auth/v1/sign-in',{username:'owner',password:newPassword});assert.equal(signIn.status,200);f.headers.cookie=signIn.headers.get('set-cookie')!.split(';')[0]!;f.headers['x-lifestream-csrf']=(await signIn.json() as any).session.csrfToken;
 assert.equal((await f.api('/api/runtime/v1/recovery')).quarantined,true);assert.equal((await f.request('/api/authority/v1/grants')).status,423);assert.equal((await f.api('/api/runtime/v1/audience')).privateAllowed,false);
 const dangerous=structuredClone(f.config);dangerous.storage.databasePath=join(destination,'data.sqlite');assert.throws(()=>createLifestreamServer({config:dangerous,host:'0.0.0.0'}),/quarantined/);
});
test('recovery rejects changed bytes, missing current safety, old epochs, unavailable selections, symlinks and overwrite',async t=>{
 const f=await fixture(t),snapshot=join(f.root,'snapshot');await snapshotCandidate({candidate:f.candidate,packages:f.packages,destination:snapshot});
 await assert.rejects(restoreCandidate({snapshot,currentSafety:join(f.candidate,'safety'),destination:f.candidate}),/EEXIST/);
 const stale=join(f.root,'stale');await cp(join(f.candidate,'safety'),stale,{recursive:true});await writeFile(join(stale,`epoch-${f.identity.session.principalId}`),'0');await assert.rejects(restoreCandidate({snapshot,currentSafety:stale,destination:join(f.root,'bad-epoch')}),/epoch is stale/);
 await rm(join(stale,'authentication-key'));await assert.rejects(restoreCandidate({snapshot,currentSafety:stale,destination:join(f.root,'bad-safety')}),/incomplete|epoch is stale/);
 await writeFile(join(snapshot,'packages/synthetic/model.gltf'),'tampered');await assert.rejects(restoreCandidate({snapshot,currentSafety:join(f.candidate,'safety'),destination:join(f.root,'bad-bytes')}),/differ/);
 const db=new DatabaseSync(join(f.candidate,'data.sqlite'));db.prepare("UPDATE presentation_selections SET package_digest='unavailable'").run();db.close();await snapshotCandidate({candidate:f.candidate,packages:f.packages,destination:join(f.root,'old-selection')});const restored=await restoreCandidate({snapshot:join(f.root,'old-selection'),currentSafety:join(f.candidate,'safety'),destination:join(f.root,'unavailable-selection')});assert.equal(restored.unavailableDefaultPresentations,1);
 await symlink(join(f.root,'stale'),join(f.candidate,'safety/link'));await assert.rejects(snapshotCandidate({candidate:f.candidate,packages:f.packages,destination:join(f.root,'bad-link')}),/symbolic/);
});

// These are synthetic stored results. No real model, voice or personal learning is enabled.
async function learnedRecoveryFixture(t:any){
 const f=await fixture(t),scope:ExperienceScope={assistantId:f.assistant.assistantId,relationshipId:f.relationship.relationshipId,principalId:f.identity.session.principalId},path=f.path+'/experience/v1';
 await f.api('/api/runtime/v1/memory',{...scope,principalId:undefined,enabled:true,expectedRevision:0});
 const configured=await f.api(path,{schemaVersion:'1.0.0',operation:'configure',expectedRevision:0,enabled:true,frozen:false,retention:'sourceBound',topicPolicies:defaultTopics});
 const db=new Database({path:join(f.candidate,'data.sqlite')}),clock={now:Date.now()},repo=new ExperienceRepository(db,()=>clock.now),memories=new MemoryRepository(db);
 const policy:ExperiencePolicy={allowed:true,revision:configured.state.configuration.processingPolicyRevision,dimensions:{attentionGardening:{minimum:-1,maximum:1,delta:.05},attentionReading:{minimum:-1,maximum:1,delta:.05}}};
 const sources:Source[]=Array.from({length:6},(_,i)=>{const id=randomUUID(),content='SYNTHETIC_RESTORED_SOURCE_'+i,createdAt=new Date(clock.now).toISOString();memories.admitAutomatic([{id,assistantId:scope.assistantId,content,createdAt,provenance:{actor:scope.principalId,relationshipId:scope.relationshipId,sourceTurnRef:'turn-'+i,sourceFamily:'turn:'+i,epistemicStatus:'userStatement',automaticMemoryKey:'recovery.'+i},lifecycle:{status:'candidate',revision:1}}],scope.principalId,false);return {id,revision:2,family:'turn:'+i,digest:createHash('sha256').update(content).digest('hex'),content,occurredAt:createdAt};});
 const jobs=sources.slice(0,4).map(source=>repo.enqueue(scope,[source],'outcome',policy)!);clock.now+=61000;assert.ok(repo.admit(jobs[3]!,'fixture'));repo.called(scope);
 repo.publish(jobs[3]!,{recordType:'reflectionResult',decision:'change',conclusion:'SYNTHETIC_FORGOTTEN_DERIVED_SUMMARY',items:[{id:'retained-project',expectedRevision:0,kind:'project',topic:'gardening',statement:'SYNTHETIC_VALID_PROJECT',nextStep:'Compare two beds',uncertainty:'medium',sourceRefs:sources.slice(0,2).map(s=>s.id),disposition:'open'},{id:'forgotten-project',expectedRevision:0,kind:'project',topic:'reading',statement:'SYNTHETIC_FORGOTTEN_PROJECT',nextStep:'SYNTHETIC_FORGOTTEN_NEXT_STEP',uncertainty:'medium',sourceRefs:[sources[2]!.id],disposition:'open'}],changes:[{dimension:'attentionGardening',delta:.05,episodeRefs:jobs.slice(0,2).map(j=>j.id),confidence:.9,reason:'Independent garden outcomes'},{dimension:'attentionReading',delta:.04,episodeRefs:jobs.slice(2).map(j=>j.id),confidence:.9,reason:'Independent reading outcomes'}]},policy,sources);
 for(const job of jobs)repo.finish(job,job.id===jobs[3]!.id?'published':'noChange');repo.seed(scope,repo.read(scope).revision,'attentionReading',.1,policy);
 const pending=sources.slice(4).map(source=>repo.enqueue(scope,[source],'project',policy)!);clock.now+=61000;assert.ok(repo.admit(pending[0]!,'fixture'));repo.called(scope);const before=repo.read(scope);db.close();
 return {...f,scope,experiencePath:path,sources,pending,before};
}
test('isolated restore retains valid learning, applies newer forgetting before access and fences old jobs until fresh approvals',async t=>{
 const f=await learnedRecoveryFixture(t),snapshot=join(f.root,'learning-snapshot');await snapshotCandidate({candidate:f.candidate,packages:f.packages,destination:snapshot});
 const current=(await f.api(f.path)).relationship;await f.api(f.path+'/privacy',{action:'forget-derived-information',expectedRevision:current.revision,idempotencyKey:randomUUID(),targets:[{kind:'memory',id:f.sources[2]!.id,revision:2}]});
 const destination=join(f.root,'learning-restored');await restoreCandidate({snapshot,currentSafety:join(f.candidate,'safety'),destination});
 const db=new Database({path:join(destination,'data.sqlite')}),repo=new ExperienceRepository(db),state=repo.read(f.scope);
 assert.equal(state.items.find(i=>i.id==='forgotten-project')?.statement,'','newer forgetting must remove derived payload before the restore is exposed');
 assert.doesNotMatch(JSON.stringify(db.connection.prepare('SELECT payload_json,inverse_items_json FROM experience_lineage').all()),/SYNTHETIC_FORGOTTEN/);
 assert.equal(state.items.find(i=>i.id==='retained-project')?.statement,'SYNTHETIC_VALID_PROJECT');assert.equal(state.imprints.find(i=>i.dimension==='attentionGardening')?.learned,.05);assert.equal(state.imprints.find(i=>i.dimension==='attentionReading')?.learned,0);assert.equal(state.imprints.find(i=>i.dimension==='attentionReading')?.seed,.1);
 assert.equal(state.configuration.enabled,false);assert.equal(state.configuration.frozen,true);assert.equal(state.funnel.calls,f.before.funnel.calls);assert.equal(db.connection.prepare('SELECT count(*) AS n FROM experience_calls').get()!.n,2);
 for(const job of f.pending){assert.equal(repo.current(job),false);assert.equal(repo.jobs(f.scope).find(j=>j.id===job.id)?.state,'cancelled');assert.throws(()=>repo.publish(job,{recordType:'reflectionResult',decision:'noChange',conclusion:'Late synthetic reply',items:[],changes:[]},{allowed:true,revision:job.policyRevision,dimensions:{}},f.sources),/reflection_stale/);}db.close();
 await f.startRestore(destination);const login=await f.request('/api/auth/v1/sign-in',{username:'owner',password:f.password});assert.equal(login.status,200);f.headers.cookie=login.headers.get('set-cookie')!.split(';')[0]!;f.headers['x-lifestream-csrf']=(await login.json() as any).session.csrfToken;
 const session=await f.api('/api/runtime/v1/session-context');await f.api('/api/runtime/v1/session-context',{expectedRevision:session.revision,mode:'text',audienceScope:'authenticatedSession'});await f.api('/api/runtime/v1/audience',{mode:'solo',seconds:300});
 let view=await f.api(f.experiencePath);assert.equal(view.state.imprints[0].learned,.05,'normal runtime reconciliation must retain the quarantined valid state');
 const configure=()=>({schemaVersion:'1.0.0',operation:'configure',expectedRevision:view.state.revision,enabled:true,frozen:false,retention:'sourceBound',topicPolicies:defaultTopics});assert.equal((await f.request(f.experiencePath,configure())).status,409);
 let memory=await f.api('/api/runtime/v1/memory?'+new URLSearchParams({assistantId:f.scope.assistantId,relationshipId:f.scope.relationshipId}));await f.api('/api/runtime/v1/memory',{assistantId:f.scope.assistantId,relationshipId:f.scope.relationshipId,enabled:true,expectedRevision:memory.policy.revision});
 view=await f.api(f.experiencePath);assert.equal(view.state.configuration.enabled,false);assert.equal(view.state.imprints[0].learned,.05);view=await f.api(f.experiencePath,configure());assert.equal(view.state.configuration.enabled,true);
 memory=await f.api('/api/runtime/v1/memory?'+new URLSearchParams({assistantId:f.scope.assistantId,relationshipId:f.scope.relationshipId}));await f.api('/api/runtime/v1/memory',{assistantId:f.scope.assistantId,relationshipId:f.scope.relationshipId,enabled:false,expectedRevision:memory.policy.revision});view=await f.api(f.experiencePath);assert.equal(view.state.imprints[0].learned,0,'explicit withdrawal still removes learned state');assert.equal(view.state.imprints[2].seed,.1,'authored seed stays distinct');
});

test('nested isolated restore preserves suspension, but an explicit disabled policy expires retention permission',async t=>{
 const f=await learnedRecoveryFixture(t),snapshot=join(f.root,'first-snapshot'),first=join(f.root,'first-restore'),secondSnapshot=join(f.root,'second-snapshot'),second=join(f.root,'second-restore');
 await snapshotCandidate({candidate:f.candidate,packages:f.packages,destination:snapshot});await restoreCandidate({snapshot,currentSafety:join(f.candidate,'safety'),destination:first});
 await snapshotCandidate({candidate:first,packages:join(first,'packages'),destination:secondSnapshot});await restoreCandidate({snapshot:secondSnapshot,currentSafety:join(first,'safety'),destination:second});
 const db=new Database({path:join(second,'data.sqlite')}),repo=new ExperienceRepository(db);assert.equal(repo.read(f.scope).imprints[0]!.learned,.05);assert.equal(repo.read(f.scope).configuration.enabled,false);assert.ok(repo.jobs(f.scope).every(j=>!['queued','running'].includes(j.state)));db.close();
 await f.startRestore(second);const login=await f.request('/api/auth/v1/sign-in',{username:'owner',password:f.password});assert.equal(login.status,200);f.headers.cookie=login.headers.get('set-cookie')!.split(';')[0]!;f.headers['x-lifestream-csrf']=(await login.json() as any).session.csrfToken;
 const session=await f.api('/api/runtime/v1/session-context');await f.api('/api/runtime/v1/session-context',{expectedRevision:session.revision,mode:'text',audienceScope:'authenticatedSession'});await f.api('/api/runtime/v1/audience',{mode:'solo',seconds:300});
 assert.equal((await f.api(f.experiencePath)).state.imprints[0].learned,.05);const memory=await f.api('/api/runtime/v1/memory?'+new URLSearchParams({assistantId:f.scope.assistantId,relationshipId:f.scope.relationshipId}));assert.equal(memory.policy.enabled,false);
 await f.api('/api/runtime/v1/memory',{assistantId:f.scope.assistantId,relationshipId:f.scope.relationshipId,enabled:false,expectedRevision:memory.policy.revision});assert.equal((await f.api(f.experiencePath)).state.imprints[0].learned,0);
});
test('restore suspension cannot override newer collection withdrawal, revoked administration or an expired policy marker',async t=>{
 for(const reason of ['stop-collection','revoked-administration','expired-marker'])await t.test(reason,async t=>{
  const f=await learnedRecoveryFixture(t),snapshot=join(f.root,'snapshot'),destination=join(f.root,'restored');
  if(reason==='revoked-administration'){const db=new DatabaseSync(join(f.candidate,'data.sqlite'));db.prepare('UPDATE local_assistant_permissions SET administer=0').run();db.close();}
  if(reason==='expired-marker'){const db=new DatabaseSync(join(f.candidate,'data.sqlite'));db.prepare('UPDATE automatic_memory_policies SET enabled=0,revision=revision+1').run();db.prepare('INSERT INTO experience_restore_quarantine SELECT scope_key,revision-1 FROM automatic_memory_policies').run();db.close();}
  await snapshotCandidate({candidate:f.candidate,packages:f.packages,destination:snapshot});
  if(reason==='stop-collection'){const relationship=(await f.api(f.path)).relationship;await f.api(f.path+'/privacy',{action:'stop-collection',expectedRevision:relationship.revision,idempotencyKey:randomUUID(),targets:[]});}
  await restoreCandidate({snapshot,currentSafety:join(f.candidate,'safety'),destination});const db=new Database({path:join(destination,'data.sqlite')}),repo=new ExperienceRepository(db),state=repo.read(f.scope);assert.equal(state.imprints[0]!.learned,0);assert.equal(state.imprints[2]!.seed,.1);assert.ok(state.items.every(i=>i.statement===''));assert.equal(db.connection.prepare('SELECT count(*) AS n FROM experience_restore_quarantine').get()!.n,0);db.close();
 });
});
