import {favoriteSupport,evidenceDependency} from '../src/admin/discovery-preference.ts';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtemp,rm,copyFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import test from 'node:test';
import {compileDiscoveryCandidates} from '../src/admin/discovery-candidates.ts';
import {Database} from '../../../packages/storage-sqlite/src/database.ts';
import {UnderstandingRepository,understandingDigest,type UnderstandingRecord} from '../../../packages/storage-sqlite/src/understanding.ts';
import {extensionSettings} from '../../../tests/fixtures/extension-settings.ts';
import {createLifestreamServer} from '../src/index.ts';
import {loadProfile} from '../src/config/loader.ts';
const subject=()=>({assistantId:randomUUID(),userId:randomUUID(),relationshipId:randomUUID(),deploymentId:randomUUID()});
const source=(topic='topic:stellar-saga',text='Orin and Vale pilot ships in Stellar Saga. STELLAR_FACT_483.')=>({sourceRef:`source:${topic}`,sourceFamily:`family:${topic}`,sourceRevision:'revision:1',topicRef:topic,policyRef:'policy:synthetic',retrievedAt:new Date().toISOString(),reliability:'unknown',reliabilityBasis:'Synthetic supplied material.',content:text,claims:[{claimId:randomUUID(),text,sourceRefs:[`source:${topic}`],qualifier:'attributed',versionScope:'Synthetic edition',spoilerClass:'none',contradictionRefs:[]}],aliasClaims:[],knowledgeGaps:['No independent verification.']});

test('favorite priority requires a whole direct declaration, exact topic and current evidence dependency',()=>{
 const record={ref:'relationship-record:synthetic:1',revision:1,content:'Forest Chronicle is my favorite.',basis:'userDeclaration'},topic=['topic:forest-chronicle'];
 assert.deepEqual(favoriteSupport(topic,[record],[evidenceDependency(record)]),[record]);
 for(const content of ['I played Forest Chronicle.','I own Forest Chronicle.','Forest Chronicle is not my favorite.','If Forest Chronicle is my favorite','"Forest Chronicle is my favorite."','A friend said Forest Chronicle is my favorite.','Forest Chronicle is my favorite example of bad design.','Forest Chronicle was my favorite.','Forest Chronicle is my favorite. But only as a bad example.']){const value={...record,content};assert.deepEqual(favoriteSupport(topic,[value],[evidenceDependency(value)]),[],content);}
 for(const basis of ['observation','modelInference','unknown']){const value={...record,basis};assert.deepEqual(favoriteSupport(topic,[value],[evidenceDependency(value)]),[]);}
 assert.deepEqual(favoriteSupport(topic,[{...record,revision:2}],[evidenceDependency(record)]),[]);
 assert.deepEqual(favoriteSupport(['topic:stellar-saga'],[record],[evidenceDependency(record)]),[]);
 const alternate={...record,content:'My favourite is Forest Chronicle!'};assert.equal(favoriteSupport(topic,[alternate],[evidenceDependency(alternate)]).length,1);
});

test('candidate compiler and publication preserve source bounds, unknown scores, expiry and current parent identity',t=>{
 const db=new Database({path:':memory:'});db.migrate();t.after(()=>db.close());let now=Date.now();const repo=new UnderstandingRepository(db,()=>now),scope=subject(),boundary=understandingDigest('current');
 const s=source(),brief:UnderstandingRecord={...scope,schemaVersion:'1.0.0',recordType:'topicBrief',briefId:randomUUID(),revision:1,topicRef:s.topicRef,derived:true,status:'prepared',sources:[{sourceRef:s.sourceRef,sourceFamily:s.sourceFamily,sourceRevision:s.sourceRevision,policyRef:s.policyRef,retrievedAt:s.retrievedAt,reliability:s.reliability,reliabilityBasis:s.reliabilityBasis,kind:'providedFixture'}],claims:s.claims,aliasClaims:[],knowledgeGaps:s.knowledgeGaps,deeperMaterialRefs:[],builtAt:new Date(now).toISOString(),freshUntil:new Date(now+900000).toISOString(),compilerRef:'synthetic:1',dependencyRefs:['source:synthetic:1'],configurationRef:'configuration:1'};
 const candidate=compileDiscoveryCandidates(brief,boundary,now)[0]!;assert.equal(candidate.confersAuthority,false);assert.equal((candidate.scores as any).interestStrength,null);assert.equal((candidate.scores as any).evidenceConfidence,null);assert.equal((candidate.scores as any).researchCost,0);assert.equal(Date.parse(String(candidate.expiresAt))-now,600000);assert.equal(candidate.content,s.content);
 const work:UnderstandingRecord={...scope,schemaVersion:'1.0.0',recordType:'work',workId:randomUUID(),revision:1,topicRef:s.topicRef,purpose:'briefRebuild',state:'queued',executionMode:'normal',idempotencyKey:'candidate-once',configurationRef:'configuration:1',policyRefs:['policy:synthetic'],dependencyRefs:['source:synthetic:1'],capabilityInvocationRef:null,admissionReceiptRef:null,createdAt:new Date(now).toISOString(),deadlineAt:new Date(now+120000).toISOString(),expiresAt:new Date(now+86400000).toISOString(),budget:extensionSettings.understanding.budget,producedRefs:[],lastOutcome:'notRun',reason:'Synthetic candidate preparation'};
 repo.admit(scope,work,understandingDigest(work),understandingDigest('snapshot'),boundary,()=>true);repo.start(scope,String(work.workId));assert.throws(()=>repo.publish(scope,String(work.workId),boundary,[candidate],()=>true),/parent/);
 assert.throws(()=>repo.publish(scope,String(work.workId),boundary,[brief,{...candidate,expiresAt:new Date(now+600001).toISOString()}],()=>true),/candidate/);assert.equal(repo.list(scope,boundary).filter(r=>r.recordType!=='work').length,0,'parent and child publication roll back atomically');
 assert.equal(repo.publish(scope,String(work.workId),boundary,[brief,candidate],()=>true),true);assert.match(repo.select(scope,boundary,'Orin in Stellar Saga?')[0]!.content,/STELLAR_FACT_483/);assert.equal(repo.select(scope,boundary,'Orin in Forest Chronicle?').length,0);assert.equal(repo.select({...scope,userId:randomUUID()},boundary,'Stellar Saga').length,0);
 now+=600001;assert.equal(repo.select(scope,boundary,'Stellar Saga').length,0);assert.ok(repo.list(scope,boundary).some(record=>record.recordType==='topicBrief'),'fresh brief does not bypass expired candidate selection');repo.cleanupExpired();assert.equal(db.connection.prepare('SELECT COUNT(*) AS n FROM understanding_projection').get()!.n,0);
});

test('prepared candidates reach actual input with current-domain precedence and suppression survives restore',async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-candidates-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomUUID(),password=randomUUID()+randomUUID(),options={config,localAuth:{stateDirectory:join(root,'safety'),installerToken}};
 let app=createLifestreamServer(options);await app.start();t.after(()=>app.shutdown());let base=`http://127.0.0.1:${app.address().port}`;const headers:Record<string,string>={origin:base,'content-type':'application/json'};
 const send=(path:string,body?:unknown)=>fetch(base+path,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:JSON.stringify(body)}),api=async(path:string,body?:unknown)=>{const response=await send(path,body);return {status:response.status,body:await response.json() as any};};
 const setup=await send('/api/auth/v1/setup',{installerToken,username:'owner',password});assert.equal(setup.status,201);headers.cookie=setup.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=(await setup.json() as any).session.csrfToken;
 const assistant=(await api('/api/admin/v1/assistants',{displayName:'Synthetic Candidate Review'})).body;await api(`/api/admin/v1/assistants/${assistant.assistantId}/activate`,{profileId:assistant.profile.profileId,expectedActiveRevision:null});const relation=(await api(`/api/admin/v1/assistants/${assistant.assistantId}/relationships`,{})).body.relationship;
 const prefix=`/api/admin/v1/assistants/${assistant.assistantId}/relationships/${relation.relationshipId}`,discovery=(body:Record<string,unknown>)=>api(prefix+'/understanding/v1',{schemaVersion:'1.0.0',...body});
 const declared=await api(prefix+'/candidates',{idempotencyKey:'favorite',expectedRevision:relation.revision,content:'Forest Chronicle is my favorite.',source:'authored',sourceFamily:'user-declaration',uncertainty:'low',contextUse:'baseline'});assert.equal(declared.status,201);const approved=await api(prefix+`/candidates/${declared.body.candidate.candidateId}/decision`,{idempotencyKey:'approve-favorite',expectedRevision:declared.body.relationshipRevision,decision:'approved'});assert.equal(approved.status,200);
 const draft=await discovery({operation:'draft',idempotencyKey:'settings',expectedActiveConfigurationId:null,settings:{...extensionSettings.understanding,enabled:true,policyRefs:['policy:synthetic']}});assert.equal(draft.status,201,JSON.stringify(draft));const settings=draft.body.records[0];assert.equal((await discovery({operation:'activate',idempotencyKey:'activate',configurationId:settings.configurationId,expectedRevision:settings.revision,confirmed:true})).status,200);
 for(const item of [source('topic:forest-chronicle','Orin and Vale explore Forest Chronicle. FOREST_FACT_291.'),source()]){const admitted=await discovery({operation:'prepare',purpose:'briefRebuild',idempotencyKey:randomUUID(),topicRef:item.topicRef,evidenceRefs:[],sources:[item]});assert.equal(admitted.status,202,JSON.stringify(admitted));let published=false;for(let n=0;n<50;n++){const inspect=await discovery({operation:'inspect'});assert.equal(inspect.status,200);if(inspect.body.records.some((r:any)=>r.workId===admitted.body.records[0].workId&&r.state==='published')){published=true;break;}await new Promise(resolve=>setTimeout(resolve,10));}assert.ok(published,`Preparation did not publish for ${item.topicRef}`);}
 await api('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'});
 const prompt=async(userInput:string)=>{const response=await send('/api/runtime/v1/messages',{assistantId:assistant.assistantId,relationshipId:relation.relationshipId,userInput,inspect:true,fullPromptPreview:true});assert.equal(response.status,200);const output=await response.text();assert.match(output,/event: interaction.completed/);return output;};
 const ambiguous=await prompt('Tell me about Orin and Vale.');assert.match(ambiguous,/FOREST_FACT_291/,ambiguous.split('\n').filter(line=>line.includes('omissions')).join('\n'));assert.doesNotMatch(ambiguous,/STELLAR_FACT_483/);
 const actual=await prompt('Who are Orin and Vale in Stellar Saga?');assert.match(actual,/STELLAR_FACT_483/);assert.doesNotMatch(actual,/FOREST_FACT_291/);assert.match(actual,/discovery-candidate:/);assert.doesNotMatch(await prompt('Who are Orin and Vale in Stellar Saga?'),/STELLAR_FACT_483/,'an already submitted optional candidate is not repeated through a cached view');assert.doesNotMatch(await prompt('Actually, not Stellar Saga. Explain a different topic.'),/STELLAR_FACT_483/);
 const inspected=await discovery({operation:'inspect'}),candidate=inspected.body.records.find((r:any)=>r.recordType==='candidate'&&r.topicRefs[0]==='topic:stellar-saga');assert.ok(candidate);assert.equal(candidate.confersAuthority,false);
 const db=new Database({path:config.storage.databasePath});const backup=join(root,'before-suppression.sqlite');await db.backup(backup);db.exec("CREATE TRIGGER fail_suppression BEFORE INSERT ON understanding_candidate_suppressions BEGIN SELECT RAISE(ABORT,'synthetic failure'); END");
 const suppression={operation:'disposition',idempotencyKey:'suppress-once',recordId:candidate.candidateId,expectedRevision:1,decision:'suppressCandidate',reason:'No need for this optional detail.'};assert.equal((await discovery(suppression)).status,409);assert.equal((await discovery({operation:'inspect'})).status,503);db.exec('DROP TRIGGER fail_suppression');
 const suppressed=await discovery(suppression);assert.equal(suppressed.status,200,JSON.stringify(suppressed));assert.equal(suppressed.body.records[0].status,'suppressed');assert.equal((await discovery(suppression)).status,200);assert.equal((await discovery({...suppression,reason:'changed retry'})).status,409);assert.doesNotMatch(await prompt('Who are Orin and Vale in Stellar Saga?'),/STELLAR_FACT_483/);
 assert.equal(db.connection.prepare("SELECT COUNT(*) AS n FROM understanding_artifacts WHERE kind='topicBrief'").get()!.n,2,'suppression retains the parent briefs');await app.shutdown();db.close();await copyFile(backup,config.storage.databasePath);app=createLifestreamServer(options);await app.start();base=`http://127.0.0.1:${app.address().port}`;headers.origin=base;delete headers.cookie;delete headers['x-lifestream-csrf'];const login=await send('/api/auth/v1/sign-in',{username:'owner',password,totp:''});assert.equal(login.status,200);headers.cookie=login.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=(await login.json() as any).session.csrfToken;
 const restored=await discovery({operation:'inspect'});assert.equal(restored.status,200,JSON.stringify(restored));assert.equal(restored.body.records.find((r:any)=>r.candidateId===candidate.candidateId).status,'suppressed');assert.equal((await discovery(suppression)).status,200);assert.doesNotMatch(await prompt('Who are Orin and Vale in Stellar Saga?'),/STELLAR_FACT_483/);
 const current=(await api(prefix)).body.relationship,favorite=current.candidates.find((r:any)=>r.candidateId===approved.body.candidate.candidateId);
 const revised=await api(prefix+`/records/${favorite.candidateId}/operations`,{operation:'correct',content:'Forest Chronicle is no longer my favorite.',expectedRevision:current.revision,expectedRecordRevision:favorite.revision,idempotencyKey:'correct-favorite'});assert.equal(revised.status,200,JSON.stringify(revised));
 assert.doesNotMatch(await prompt('Tell me about Orin and Vale again.'),/FOREST_FACT_291/,'correcting the owning declaration invalidates the derived favorite and its prepared detail');
 const again=source('topic:forest-chronicle','Orin and Vale explore Forest Chronicle. FOREST_FACT_291.');const rebuilt=await discovery({operation:'prepare',purpose:'briefRebuild',idempotencyKey:'rebuild-after-correction',topicRef:again.topicRef,evidenceRefs:[],sources:[again]});assert.equal(rebuilt.status,202,JSON.stringify(rebuilt));let after:any;for(let n=0;n<50;n++){after=await discovery({operation:'inspect'});if(after.body.records.some((r:any)=>r.workId===rebuilt.body.records[0].workId&&r.state==='published'))break;await new Promise(resolve=>setTimeout(resolve,10));}assert.equal(after.body.records.find((r:any)=>r.recordType==='candidate').scores.interestStrength,null,'the corrected favorite cannot be reconstructed from its superseded statement');
});

test('hypothesis questions do not turn dislike, fatigue or uncertainty into assumed enjoyment',()=>{
 for(const summary of ['The stated topic may be disliked.','Temporary fatigue may explain the reaction.','Interest without capacity may explain the reaction.','There is insufficient evidence of interest.']){
  const scope=subject(),now=Date.now(),parent:UnderstandingRecord={...scope,schemaVersion:'1.0.0',recordType:'hypothesis',hypothesisId:randomUUID(),revision:1,epistemicStatus:'tentative',status:'candidate',topicRefs:['topic:synthetic'],explanations:[{explanationId:randomUUID(),summary,traitRefs:['trait:synthetic'],supportEvidenceRefs:['evidence:synthetic'],counterEvidenceRefs:[],boundary:'Only the stated context.'},{explanationId:randomUUID(),summary:'Timing may explain the reaction.',traitRefs:['trait:timing'],supportEvidenceRefs:['evidence:synthetic'],counterEvidenceRefs:[],boundary:'No lasting preference established.'}],unknownAlternative:'Another explanation may apply.',sourceCoverage:'unknown',uncertainty:'No established personal motive.',dependencyRefs:['evidence:synthetic:1'],createdAt:new Date(now).toISOString(),configurationRef:'configuration:synthetic'};
  const before=structuredClone(parent),candidate=compileDiscoveryCandidates(parent,understandingDigest('current'),now)[0]!;
  assert.equal(candidate.kind,'question');
  assert.doesNotMatch(String(candidate.content),/appeal|enjoy|like|favorite/iu,'the question must not assume positive interest');
  assert.match(String(candidate.content),/if anything/iu);
  assert.deepEqual(candidate.alternatives,(parent.explanations as Record<string,unknown>[]).map(e=>e.summary));
  assert.deepEqual(candidate.hypothesisRefs,[`hypothesis:${parent.hypothesisId}:1`]);
  assert.equal(candidate.confersAuthority,false);
  assert.equal((candidate.scores as any).interestStrength,null);
  assert.deepEqual(parent,before,'compiling a question cannot reinforce or alter the hypothesis');
  assert.equal(compileDiscoveryCandidates({...parent,status:'rejected'},understandingDigest('current'),now).length,0);
 }
});
