import assert from 'node:assert/strict';import test from 'node:test';import {randomBytes,createHash} from 'node:crypto';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {createLifestreamServer} from '../src/index.ts';import {loadProfile} from '../src/config/loader.ts';import {FixtureInferenceProvider} from '@lifestream/runtime/inference/fixture';import {defaultTopics} from '@lifestream/contracts/experience';
const delay=(ms:number)=>new Promise(r=>setTimeout(r,ms));
import {fixtureEpisode} from '../../../packages/runtime/test/fixtures/game-memory.ts';
import {gameEpisodeFamilyKey} from '@lifestream/contracts/game-memory';
test('normal completed typed conversations and retained memory automatically reflect, persist and change later choice',async t=>{
 const root=await mkdtemp(join(tmpdir(),'experience-http-'));t.after(()=>rm(root,{recursive:true,force:true}));const original=FixtureInferenceProvider.prototype.generate,requests:any[]=[];
 FixtureInferenceProvider.prototype.generate=async function*(request,context){requests.push(request);if(request.scope.sessionId==='automatic-memory-worker'){const source=JSON.parse(request.sections.at(-1)!.content).source;yield {kind:'text',text:JSON.stringify({items:[{key:'project.'+createHash('sha256').update(source).digest('hex').slice(0,16),kind:'experiential',quote:source,subject:'owner',epistemic:'userStatement'}]})};yield {kind:'done'};return;}
 if(request.scope.sessionId.startsWith('experience:')){const data=JSON.parse(request.sections.at(-1)!.content),refs=data.sources.map((s:any)=>s.id),items=['reading','gardening'].map((topic,i)=>{const old=data.workspace.find((s:any)=>s.id===['a-reading','z-garden'][i]);return {id:['a-reading','z-garden'][i],expectedRevision:old?.revision??0,kind:'project',topic,statement:'Continue the '+topic+' project',nextStep:topic==='reading'?'Compare two essays':'Plan a soil comparison',uncertainty:'medium',sourceRefs:refs,disposition:'open'};});yield {kind:'text',text:JSON.stringify({recordType:'reflectionResult',decision:'change',conclusion:'Independent retained outcomes support next steps.',items,changes:data.episodes.length>=2&&!data.alreadyContributed[0]?.episodes.length?[{dimension:'attentionGardening',delta:.05,episodeRefs:data.episodes.map((e:any)=>e.id),confidence:.9,reason:'Independent outcomes'}]:[]})};yield {kind:'done'};return;}
 const memory=request.sections.find(s=>s.kind==='preparedMemory')!.content;yield {kind:'text',text:memory.includes('Selected eligible continuation')?(memory.includes('Plan a soil comparison')?'Compare soil in two beds, keeping water and light equal.':'Compare the argument in two nature essays.'):'Understood.'};yield {kind:'done'};
 };t.after(()=>{FixtureInferenceProvider.prototype.generate=original;});const clock={now:Date.now()},config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex'),password=randomBytes(32).toString('hex'),options={config,experienceTestClock:()=>clock.now,localAuth:{stateDirectory:join(root,'safety'),installerToken}};let app=createLifestreamServer(options);await app.start();t.after(()=>app.shutdown());let base=`http://127.0.0.1:${app.address().port}`,cookie='',csrf='';const request=(path:string,body?:unknown)=>fetch(base+path,{method:body===undefined?'GET':'POST',headers:{origin:base,cookie,'content-type':'application/json','x-lifestream-csrf':csrf},...(body===undefined?{}:{body:JSON.stringify(body)})});
 const setup=await request('/api/auth/v1/setup',{username:'synthetic',password,installerToken});cookie=setup.headers.get('set-cookie')!.split(';')[0]!;csrf=(await setup.json()).session.csrfToken;
 const a=await (await request('/api/admin/v1/assistants',{displayName:'Synthetic learning Assistant',adaptivePersonaPolicy:{dimensions:[{key:'attentionGardening',valueType:'number',minimum:-1,maximum:1,maxDeltaPerDreamingRun:.05,sensitive:false,activation:'automatic'}]}})).json();assert.equal((await request(`/api/admin/v1/assistants/${a.assistantId}/activate`,{profileId:a.profile.profileId,expectedActiveRevision:null})).status,200);const rel=(await (await request(`/api/admin/v1/assistants/${a.assistantId}/relationships`,{})).json()).relationship,scope={assistantId:a.assistantId,relationshipId:rel.relationshipId},path=`/api/admin/v1/assistants/${a.assistantId}/relationships/${rel.relationshipId}/experience/v1`;
 let view=await (await request(path)).json();assert.equal(view.state.configuration.enabled,false);const configure=()=>({schemaVersion:'1.0.0',operation:'configure',expectedRevision:view.state.revision,enabled:true,frozen:false,retention:'sourceBound',topicPolicies:defaultTopics});assert.equal((await request(path,configure())).status,409,'missing retained processing policy fails closed');assert.equal((await request('/api/runtime/v1/memory',{...scope,enabled:true,expectedRevision:0})).status,200);view=await (await request(path)).json();assert.equal((await request(path,configure())).status,200);assert.equal((await request('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'})).status,200);
 const turn=async(userInput:string)=>{const response=await request('/api/runtime/v1/messages',{...scope,userInput});const text=await response.text();assert.match(text,/interaction.completed/,text);return text;};
 const waitFor=async(fn:()=>Promise<boolean>)=>{for(let n=0;n<100;n++){if(await fn())return;await delay(50);}assert.fail('bounded wait failed '+JSON.stringify({view,requests:requests.map(r=>r.scope.sessionId)}));};
 await turn('I enjoyed the gardening and reading projects on our first trial day.');await waitFor(async()=>{const v=await (await request('/api/runtime/v1/memory?'+new URLSearchParams(scope))).json();return v.jobs.some((j:any)=>j.state==='saved');});await delay(1100);clock.now+=61000;await waitFor(async()=>{view=await (await request(path)).json();return view.state.items.length===2;});
 await turn('I enjoyed comparing garden soil and reading essays during our second independent trial day.');await waitFor(async()=>{const v=await (await request('/api/runtime/v1/memory?'+new URLSearchParams(scope))).json();return v.jobs.filter((j:any)=>j.state==='saved').length===2;});await delay(1100);clock.now+=61000;await waitFor(async()=>{view=await (await request(path)).json();return view.state.imprints[0].value===.05;});const answer=await turn('What should we work on next?');assert.match(answer,/Compare soil in two beds/);view=await (await request(path)).json();assert.equal(view.state.funnel.eligible,2);assert.equal(view.state.funnel.calls,2);assert.equal(view.state.funnel.outputs,1);assert.ok(view.selections.some((s:any)=>s.selected==='z-garden'&&s.observedOutput));assert.equal(requests.filter(r=>r.scope.sessionId.startsWith('experience:')).length,2);
 await app.shutdown();app=createLifestreamServer(options);await app.start();base=`http://127.0.0.1:${app.address().port}`;const login=await request('/api/auth/v1/sign-in',{username:'synthetic',password});assert.equal(login.status,200);cookie=login.headers.get('set-cookie')!.split(';')[0]!;csrf=(await login.json()).session.csrfToken;view=await (await request(path)).json();assert.equal(view.state.imprints[0].value,.05);assert.equal(view.state.items.length,2);
 assert.equal((await request(path,{schemaVersion:'1.0.0',operation:'configure',expectedRevision:view.state.revision,enabled:true,frozen:true,retention:'sourceBound',topicPolicies:defaultTopics})).status,200);const frozen=await turn('What should we work on next?');assert.doesNotMatch(frozen,/Compare soil/);assert.equal((await request(path,{...configure(),authority:true})).status,422);
});

test('foreground arrival and source withdrawal fence an uncooperative reflection before publication',async t=>{
 const {Database}=await import('@lifestream/storage-sqlite'),{ExperientialLearning}=await import('../src/runtime/experience.ts'),{UnderstandingWorkCoordinator}=await import('@lifestream/runtime/understanding/coordinator');const db=new Database({path:':memory:'});db.migrate();t.after(()=>db.close());let now=Date.now(),sources:any[]=[{id:'retained-synthetic',revision:1,family:'turn:synthetic',digest:createHash('sha256').update('synthetic').digest('hex'),content:'I enjoyed a gardening project',occurredAt:new Date(now).toISOString()}];const scope={assistantId:crypto.randomUUID(),principalId:crypto.randomUUID(),relationshipId:crypto.randomUUID()},policy={allowed:true,revision:1,dimensions:{}},coordinator=new UnderstandingWorkCoordinator({now:()=>now,pressureAllowsWork:()=>true});let release!:()=>void,entered!:()=>void;const held=new Promise<void>(r=>release=r),started=new Promise<void>(r=>entered=r);const provider={tokenize:async()=>({count:40,identity:'fixture'}),async*generate(){entered();await held;yield {kind:'text' as const,text:JSON.stringify({recordType:'reflectionResult',decision:'change',conclusion:'Must never publish.',items:[{id:'late',expectedRevision:0,kind:'project',topic:'gardening',statement:'LATE_PRIVATE_ITEM',nextStep:'Must never be delivered',uncertainty:'medium',sourceRefs:['retained-synthetic'],disposition:'open'}],changes:[]})};yield {kind:'done' as const};}};
 const service=new ExperientialLearning(db,{policy:()=>policy,sources:()=>sources,provider:()=>({provider,revision:'synthetic',preemptionBoundMs:1,slotReleaseBoundMs:1}),run:work=>coordinator.run(work),idle:()=>coordinator.isIdle(),changed:()=>{},now:()=>now});t.after(()=>service.close());service.repository.configure(scope,0,{enabled:true,frozen:false,retention:'sourceBound',topicPolicies:defaultTopics},policy);service.repository.enqueue(scope,sources,'project',policy);now+=60001;const work=service.tick();await started;const finishForeground=coordinator.foregroundStarted();service.foreground();sources=[];service.reconcile(scope);release();await work;finishForeground();const view=service.inspect(scope);assert.equal(view.state.items.length,0);assert.equal(view.state.funnel.calls,1);assert.equal(view.state.funnel.published,0);assert.equal(view.jobs[0]!.state,'cancelled');assert.doesNotMatch(JSON.stringify(view),/LATE_PRIVATE_ITEM/);
});

test('idle visual reflection only collects evidence for supported workspace and fences late source withdrawal',async t=>{
 const {Database}=await import('@lifestream/storage-sqlite'),{ExperientialLearning}=await import('../src/runtime/experience.ts'),{UnderstandingWorkCoordinator}=await import('@lifestream/runtime/understanding/coordinator'),{visualEpisode}=await import('../../../packages/storage-sqlite/test/fixtures/visual-episode.ts');const db=new Database({path:':memory:'});db.migrate();t.after(()=>db.close());let now=Date.now(),idle=false;const scope={assistantId:crypto.randomUUID(),principalId:crypto.randomUUID(),relationshipId:crypto.randomUUID()},policy={allowed:true,revision:1,dimensions:{}},owner={id:'retained-garden-owner',revision:1,family:'turn:synthetic',digest:createHash('sha256').update('I am working on a gardening comparison.').digest('hex'),content:'I am working on a gardening comparison.',occurredAt:new Date(now).toISOString()};let sources:any[]=[owner];const coordinator=new UnderstandingWorkCoordinator({now:()=>now,pressureAllowsWork:()=>true});let release!:()=>void,entered!:()=>void;const held=new Promise<void>(r=>release=r),started=new Promise<void>(r=>entered=r);let captured:any;const provider={tokenize:async()=>({count:40,identity:'scripted-tokenizer'}),async*generate(request:any){captured=JSON.parse(request.sections.at(-1).content);entered();await held;yield {kind:'text' as const,text:JSON.stringify({recordType:'reflectionResult',decision:'change',conclusion:'LATE_VISUAL_REFLECTION',items:[{id:'garden',expectedRevision:1,kind:'project',topic:'gardening',statement:'LATE_VISUAL_ITEM',nextStep:'Ask whether the sampled garden was relevant',uncertainty:'high',sourceRefs:sources.map(s=>s.id),disposition:'open'}],changes:[]})};yield {kind:'done' as const};}};
 const service=new ExperientialLearning(db,{policy:()=>policy,sources:()=>sources,provider:()=>({provider,revision:'scripted',preemptionBoundMs:1,slotReleaseBoundMs:1}),run:work=>coordinator.run(work),idle:()=>idle,changed:()=>{},now:()=>now});t.after(()=>service.close());service.repository.configure(scope,0,{enabled:true,frozen:false,retention:'sourceBound',topicPolicies:defaultTopics},policy);const seed=service.repository.enqueue(scope,[owner],'project',policy)!;now+=60001;assert.ok(service.repository.admit(seed,'scripted'));service.repository.publish(seed,{recordType:'reflectionResult',decision:'change',conclusion:'Owner supports a project.',items:[{id:'garden',expectedRevision:0,kind:'project',topic:'gardening',statement:'Compare two garden beds',nextStep:'Ask about the planned comparison',uncertainty:'medium',sourceRefs:[owner.id],disposition:'open'}],changes:[]},policy,[owner]);service.repository.finish(seed,'published');
 const {episode}=visualEpisode(scope,{enabled:true,revision:1,retentionMs:86400000,retentionPolicyRef:'synthetic-retention'},now);episode.state='retained';episode.summary='Unverified sampled garden bed appearance.';episode.sourceDigest=createHash('sha256').update(JSON.stringify({scope:episode.scope,observations:episode.observations})).digest('hex');const content=JSON.stringify(episode),visual={id:'visual-episode:'+episode.episodeId,revision:1,family:'visual:'+episode.independenceKeys[0],digest:createHash('sha256').update(content).digest('hex'),content,occurredAt:episode.occurredAt};sources=[owner,visual];await service.tick();assert.equal(service.repository.read(scope).funnel.eligible,2);assert.equal(service.repository.read(scope).funnel.calls,0);const visualJob=service.repository.jobs(scope).find(j=>j.state==='queued')!;assert.equal(service.repository.episodes(scope).find(e=>e.id===visualJob.id)!.eligibleReason,'question');await service.tick();assert.equal(service.repository.read(scope).funnel.eligible,2,'same family is not admitted again');idle=true;now+=60001;const work=service.tick();await started;assert.equal(captured.sources.find((s:any)=>s.id===visual.id).family,visual.family);assert.equal(JSON.parse(captured.sources.find((s:any)=>s.id===visual.id).content).memoryRecordId,null);sources=[owner];service.reconcile(scope);release();await work;assert.equal(service.repository.current(visualJob),false);assert.equal(service.repository.read(scope).items[0]!.statement,'Compare two garden beds');assert.doesNotMatch(JSON.stringify(service.inspect(scope)),/LATE_VISUAL_ITEM|LATE_VISUAL_REFLECTION/);idle=false;service.repository.reset(scope,service.repository.read(scope).revision);sources=[owner,visual];const eligible=service.repository.read(scope).funnel.eligible;await service.tick();assert.equal(service.repository.read(scope).funnel.eligible,eligible,'a scene cannot manufacture an unsupported workspace question');
});

for(const cause of ['source','expiry','policy','foreground']as const)test('idle typed game reflection preserves origin and fences suspended '+cause,{timeout:15000},async t=>{
 const {Database}=await import('@lifestream/storage-sqlite'),{ExperientialLearning}=await import('../src/runtime/experience.ts'),{UnderstandingWorkCoordinator}=await import('@lifestream/runtime/understanding/coordinator');const db=new Database({path:':memory:'});db.migrate();t.after(()=>db.close());let now=Date.now(),idle=false;
 const e=fixtureEpisode(now);e.expiresAt=new Date(now+86400000).toISOString();const scope={principalId:e.scope.principalId,assistantId:e.scope.assistantId,relationshipId:e.scope.relationshipId},content=JSON.stringify(e),source={id:'game-episode:'+e.episodeId,revision:e.revision,family:'game:'+gameEpisodeFamilyKey(e),digest:createHash('sha256').update(content).digest('hex'),content,occurredAt:e.occurredFrom};let sources=[source],policy={allowed:true,revision:1,dimensions:{}};
 const coordinator=new UnderstandingWorkCoordinator({now:()=>now,pressureAllowsWork:()=>true});let release!:()=>void,entered!:()=>void;const held=new Promise<void>(r=>release=r),started=new Promise<void>(r=>entered=r);t.after(()=>release());let captured:any;
 const provider={tokenize:async()=>({count:40,identity:'scripted-tokenizer'}),async*generate(request:any){captured=request;entered();await held;yield {kind:'text' as const,text:JSON.stringify({recordType:'reflectionResult',decision:'change',conclusion:'LATE_GAME_REFLECTION',items:[{id:'game-gate',expectedRevision:0,kind:'question',topic:'games',statement:'LATE_GAME_ITEM',nextStep:'Ask about the past gate attempt',uncertainty:'high',sourceRefs:[source.id],disposition:'open'}],changes:[]})};yield {kind:'done' as const};}};
 const service=new ExperientialLearning(db,{policy:()=>policy,sources:()=>sources,provider:()=>({provider,revision:'scripted',preemptionBoundMs:1,slotReleaseBoundMs:1}),run:work=>coordinator.run(work),idle:()=>idle,changed:()=>{},now:()=>now});t.after(()=>service.close());service.repository.configure(scope,0,{enabled:true,frozen:false,retention:'sourceBound',topicPolicies:defaultTopics},policy);
 await service.tick();const job=service.repository.jobs(scope)[0]!;assert.equal(service.repository.read(scope).funnel.eligible,1);assert.equal(service.repository.read(scope).funnel.calls,0);assert.equal(service.repository.episodes(scope)[0]!.occurredAt,e.occurredFrom);assert.equal(db.connection.prepare('SELECT count(*) AS n FROM experience_turns').get()!.n,0);
 idle=true;now+=60001;const work=service.tick();await started;assert.equal(captured.sections.length,9);const input=JSON.parse(captured.sections.at(-1).content);assert.equal(input.sources[0].family,source.family);assert.equal(JSON.parse(input.sources[0].content).scope.timelineId,e.scope.timelineId);assert.deepEqual(input.eligibleAttentionChanges,[]);
 let finish:(()=>void)|undefined;if(cause==='source')sources=[];if(cause==='expiry')now=Date.parse(e.expiresAt);if(cause==='policy')policy={...policy,allowed:false,revision:2};if(cause==='foreground'){finish=coordinator.foregroundStarted();service.foreground();}
 service.reconcile(scope);release();await work;finish?.();const view=service.inspect(scope);assert.equal(view.state.funnel.calls,1);assert.equal(view.state.funnel.published,0);assert.equal(view.state.items.length,0);assert.doesNotMatch(JSON.stringify(view),/LATE_GAME_ITEM|LATE_GAME_REFLECTION/);
});
