import assert from 'node:assert/strict';
import test from 'node:test';
import {randomUUID} from 'node:crypto';
import {isDeepStrictEqual} from 'node:util';
import type * as G from '@lifestream/contracts/game-activity';
import {selectGameWindow} from '@lifestream/runtime/activity/policy';
import {Database} from '../../../packages/storage-sqlite/src/database.ts';
import {GameStartRepository} from '../../../packages/storage-sqlite/src/game-starts.ts';
import {gameCampaignFixture} from '../../../packages/runtime/test/fixtures/game-campaign.ts';
import {scriptedGameBounds,scriptedGamePolicy} from '../../../packages/runtime/test/fixtures/game-policy.ts';
import {DiscoveryAdministration} from '../src/admin/understanding.ts';
import {claimConfiguredGameStart} from '../src/runtime/game-activity.ts';
import {interruptGameRun,type GameInterruptionInput,type GameInterruptionPorts,type GameShutdownReport} from '../src/runtime/game-activity-lifecycle.ts';
const neutral={up:false,down:false,left:false,right:false,a:false,b:false,x:false,y:false,l:false,r:false,start:false,select:false} as const;
function fixture(){
 const scope=gameCampaignFixture().input.expectedScope,lease=randomUUID(),key='game-decision:'+randomUUID()+':1',db=new Database({path:':memory:'});db.migrate();db.exec('CREATE TABLE test_shutdown_intents(identity TEXT PRIMARY KEY,report_json TEXT)');let current=true,clockOffset=0,releases=0,fences=0;
 const admin=new DiscoveryAdministration(db,{snapshot:()=>({boundary:'scripted',configuration:undefined}),evidenceAllowed:()=>false,sourceAllowed:()=>false,forget:()=> 'missing',changed:()=>{}}),proofs=new Set<string>(),reports:GameShutdownReport[]=[],events:string[]=[];
 const now=()=>Date.now()+clockOffset,policy=scriptedGamePolicy(now()),bounds=structuredClone(scriptedGameBounds),starts=new GameStartRepository(db,{maxClaims:4,maxAssistantSlots:2,quarantined:()=>false,limitsFor:()=>({enabled:true,revision:1,rollingPeriodMs:86400000,rollingStartLimit:2,startsPerWindow:1}),admissionCurrent:()=>true,inspectionCurrent:s=>isDeepStrictEqual(s,scope),dispositionCurrent:(_s,next,_r,ref)=>proofs.has(ref)&&(ref.startsWith('scripted-qualified')||next==='recoveryRequired'),now});
 claimConfiguredGameStart(starts,{scope,policy,bounds},selectGameWindow({scope,policy,bounds,purpose:'play',nowMs:now()},{policyCurrent:()=>true,now}));
 const request:G.GameReleaseRequest={schemaVersion:'1.0.0',operation:'GameActivityAdapter.releaseControls',requestId:randomUUID(),correlationId:randomUUID(),deadlineAt:new Date(now()+3000).toISOString(),cancellationId:randomUUID(),executionMode:'simulation',scope:structuredClone(scope),idempotencyKey:randomUUID(),payload:{targetInputOwnerLeaseId:lease,reason:'pause',neutralButtons:{...neutral}}};
 const input:GameInterruptionInput={request,planningKey:key,epochAfterFence:scope.activityEpoch+1};
 const result=(r=request):G.GameReleaseResult=>{const time=new Date(now()).toISOString();return {schemaVersion:'1.0.0',operation:r.operation,requestId:r.requestId,correlationId:r.correlationId,providerRef:'scripted-bridge',completedAt:time,outcome:{status:'succeeded',error:null,payload:{targetInputOwnerLeaseId:lease,disposition:'neutralizedAndPaused',confirmedAt:time,emulatorPaused:true,buttonsNeutralized:true,pauseFrameNumber:20,verifiedFrameNumber:20,pauseConfirmedMonotonicMs:1,verifiedMonotonicMs:2,activityEpochAfterFence:input.epochAfterFence,confirmationSource:'adapterObserved',resumeRequiresFreshObservation:true}}};};
 const ports:GameInterruptionPorts={background:admin,providerRef:'scripted-bridge',maximumReleaseWaitMs:1000,fenceAndClaim:value=>{fences++;events.push('fence');if(!isDeepStrictEqual(value.request.scope,scope)||value.request.payload.targetInputOwnerLeaseId!==lease||value.epochAfterFence!==scope.activityEpoch+1||value.planningKey!==key||db.connection.prepare('SELECT identity FROM test_shutdown_intents WHERE identity=?').get(value.request.idempotencyKey))return false;db.connection.prepare('INSERT INTO test_shutdown_intents VALUES(?,NULL)').run(value.request.idempotencyKey);return true;},shutdownCurrent:()=>current,release:async(r,context)=>{releases++;events.push('release');assert.ok(Object.isFrozen(r)&&Object.isFrozen(r.payload.neutralButtons));assert.equal(context.isCurrent(r.scope),true);assert.equal(context.isCurrent({...r.scope,runId:randomUUID()}),false);return result(r);},qualifyWithdrawal:()=>{const ref='scripted-qualified-native-receipt-not-real-proof';proofs.add(ref);return ref;},persist:report=>{events.push('persist');reports.push(report);const ref=report.receiptRef??'scripted-local-unknown-event:'+report.requestId;proofs.add(ref);const next=report.status==='stopConfirmed'?'stopped':report.status==='pauseConfirmed'?'paused':'recoveryRequired';const committed=starts.noteDisposition(scope,next,1,ref);if(committed)db.connection.prepare('UPDATE test_shutdown_intents SET report_json=? WHERE identity=?').run(JSON.stringify(report),report.idempotencyKey);return committed;},now};
 return {scope,key,lease,db,admin,starts,input,ports,result,reports,events,releases:()=>releases,fences:()=>fences,withdraw:()=>{current=false;},offset:(n:number)=>{clockOffset=n;},close:()=>{admin.close();db.close();}};
}
test('synchronous durable fence precedes one exact-old-lease release and qualified stationary acknowledgment persists paused metadata without resume',async t=>{
 const f=fixture();t.after(()=>f.close());const report=await interruptGameRun(f.input,f.ports);assert.equal(report.status,'pauseConfirmed');assert.equal(report.metadataPersisted,true);assert.equal(report.observedPauseConfirmed,true);assert.equal(report.executionMode,'simulation');assert.equal(report.resumeAuthority,false);assert.equal(report.replayAllowed,false);assert.deepEqual(f.events,['fence','release','persist']);assert.equal(f.starts.inspect(f.scope)!.recordedDisposition,'paused');assert.equal(f.starts.inspect(f.scope)!.blocksReplacement,true);assert.match(report.resultDigest!,/^[a-f0-9]{64}$/);assert.ok(Object.isFrozen(report.scope));
});
test('qualified stop closes only the original slot while a duplicate shutdown claim performs no second release or metadata overwrite',async t=>{
 const f=fixture();t.after(()=>f.close());f.input.request.payload.reason='stop';assert.equal((await interruptGameRun(f.input,f.ports)).status,'stopConfirmed');assert.equal(f.starts.inspect(f.scope)!.blocksReplacement,false);const duplicate=await interruptGameRun(f.input,f.ports);assert.equal(duplicate.status,'unconfirmed');assert.equal(duplicate.reason,'fenceDenied');assert.equal(duplicate.epochAfterFence,null);assert.equal(duplicate.metadataPersisted,false);assert.equal(f.releases(),1);assert.equal(f.reports.length,1);assert.equal(f.starts.inspect(f.scope)!.recordedDisposition,'stopped');
});
test('stopping model commands or stationary shape alone cannot certify native pause without independent qualified source evidence',async t=>{
 const f=fixture();t.after(()=>f.close());f.ports.qualifyWithdrawal=()=>null;const report=await interruptGameRun(f.input,f.ports);assert.equal(report.status,'unconfirmed');assert.equal(report.reason,'unqualifiedEvidence');assert.equal(report.observedPauseConfirmed,false);assert.equal(f.starts.inspect(f.scope)!.recordedDisposition,'recoveryRequired');assert.equal(f.starts.inspect(f.scope)!.blocksReplacement,true);
});
test('foreign reply identity/provider/lease, advancing frames, bad monotonic order, stale fenced epoch or replayed time cannot confirm pause',async t=>{
 for(const mode of ['request','correlation','provider','lease','frame','monotonic','epoch','time','hidden'])await t.test(mode,async()=>{const f=fixture();try{f.ports.release=async()=>{const r:any=f.result(),p=r.outcome.payload;if(mode==='request')r.requestId=randomUUID();if(mode==='correlation')r.correlationId=randomUUID();if(mode==='provider')r.providerRef='other';if(mode==='lease')p.targetInputOwnerLeaseId=randomUUID();if(mode==='frame')p.verifiedFrameNumber++;if(mode==='monotonic')p.verifiedMonotonicMs=1;if(mode==='epoch')p.activityEpochAfterFence++;if(mode==='time')p.confirmedAt='2020-01-01T00:00:00Z';if(mode==='hidden')p.emulatorSnapshot='forbidden';return r;};const report=await interruptGameRun(f.input,f.ports);assert.equal(report.status,'unconfirmed');assert.equal(report.observedPauseConfirmed,false);assert.equal(f.starts.inspect(f.scope)!.recordedDisposition,'recoveryRequired');}finally{f.close();}});
});
test('canonical successor-preserved acknowledgment does not pause, stop or release the new owner',async t=>{
 const f=fixture();t.after(()=>f.close());f.ports.release=async()=>{const r=f.result();r.outcome.payload={...r.outcome.payload!,disposition:'successorPreserved',confirmedAt:null,emulatorPaused:null,buttonsNeutralized:null,pauseFrameNumber:null,verifiedFrameNumber:null,pauseConfirmedMonotonicMs:null,verifiedMonotonicMs:null,activityEpochAfterFence:null,confirmationSource:'notApplicable'};return r;};const report=await interruptGameRun(f.input,f.ports);assert.equal(report.status,'successorPreserved');assert.equal(report.observedPauseConfirmed,false);assert.equal(f.starts.inspect(f.scope)!.blocksReplacement,true);assert.equal(f.starts.inspect(f.scope)!.recordedDisposition,'recoveryRequired');
});
test('unknown exception and hung native port return bounded unconfirmed status, keep blocking ownership and never retry late release',async t=>{
 for(const mode of ['throw','hang'])await t.test(mode,async()=>{const f=fixture();try{let resolve!:(v:G.GameReleaseResult)=>void;let calls=0,signal:AbortSignal|undefined;f.ports.maximumReleaseWaitMs=100;f.ports.release=async(_r,context)=>{calls++;signal=context.signal;if(mode==='throw')throw Error('Opaque native error must not escape');return new Promise<G.GameReleaseResult>(r=>{resolve=r;});};const report=await interruptGameRun(f.input,f.ports);assert.equal(report.status,'unconfirmed');assert.equal(report.observedPauseConfirmed,false);assert.equal(signal?.aborted,true);assert.equal(calls,1);assert.equal(f.starts.inspect(f.scope)!.blocksReplacement,true);if(mode==='hang'){resolve(f.result());await new Promise(r=>setTimeout(r,0));assert.equal(f.reports.length,1);}assert.doesNotMatch(JSON.stringify(report),/Opaque native error/);}finally{f.close();}});
});
test('expired shutdown deadline still fences and cancels, but cannot enter a stale release or claim paused controls',async t=>{
 const f=fixture();t.after(()=>f.close());f.input.request.deadlineAt=new Date(Date.now()-1).toISOString();const report=await interruptGameRun(f.input,f.ports);assert.equal(f.fences(),1);assert.equal(f.releases(),0);assert.equal(report.status,'unconfirmed');assert.equal(report.reason,'staleBoundary');assert.equal(f.starts.inspect(f.scope)!.recordedDisposition,'recoveryRequired');
});
test('scope/provider/UTC withdrawal while release or qualification awaits fences acknowledgment before durable pause claim',async t=>{
 for(const mode of ['scope','provider','clock','qualifier'])await t.test(mode,async()=>{const f=fixture();try{f.ports.release=async()=>{const result=f.result();if(mode==='scope')f.withdraw();if(mode==='provider')f.ports.providerRef='changed';if(mode==='clock')f.offset(-10000);return result;};if(mode==='qualifier')f.ports.qualifyWithdrawal=()=>{f.withdraw();return 'scripted-qualified';};const report=await interruptGameRun(f.input,f.ports);assert.equal(report.status,'unconfirmed');assert.equal(report.observedPauseConfirmed,false);if(mode!=='clock')assert.equal(f.starts.inspect(f.scope)!.recordedDisposition,'recoveryRequired');else{f.offset(0);assert.equal(f.starts.inspect(f.scope)!.blocksReplacement,true);}}finally{f.close();}});
});
test('durable metadata failure reports unconfirmed even with independently observed pause evidence',async t=>{
 const f=fixture();t.after(()=>f.close());f.ports.persist=()=>false;const report=await interruptGameRun(f.input,f.ports);assert.equal(report.status,'unconfirmed');assert.equal(report.reason,'persistenceFailed');assert.equal(report.metadataPersisted,false);assert.equal(report.observedPauseConfirmed,true);assert.equal(f.starts.inspect(f.scope)!.recordedDisposition,'claimed');assert.equal(f.starts.inspect(f.scope)!.blocksReplacement,true);
});
test('late source withdrawal inside persistence cannot expose a current safely-paused claim',async t=>{
 const f=fixture();t.after(()=>f.close());const persist=f.ports.persist;f.ports.persist=report=>{const saved=persist(report);f.withdraw();return saved;};const report=await interruptGameRun(f.input,f.ports);assert.equal(report.status,'unconfirmed');assert.equal(report.reason,'staleBoundary');assert.equal(report.observedPauseConfirmed,true);assert.equal(report.metadataPersisted,true);
});
test('interruption cancels existing P2 immediately and releases independently of an uncooperative suspended inference slot',async t=>{
 const f=fixture();t.after(()=>f.close());let resolve!:()=>void,entered!:()=>void,published=0,signal:AbortSignal|undefined;const gate=new Promise<void>(r=>{resolve=r;}),ready=new Promise<void>(r=>{entered=r;});const planning=f.admin.runBackground({key:f.key,deadlineAt:Date.now()+3000,current:()=>true,admitOnce:()=>true,sharedInference:true,priority:'P2',providerPreemptionBoundMs:1,providerSlotReleaseBoundMs:1,steps:[async s=>{signal=s;entered();await gate;return 'inert';}],publish:()=>{published++;return true;}});await ready;const release=f.ports.release;f.ports.release=async(r,c)=>{assert.equal(signal?.aborted,true);assert.equal(f.admin.backgroundIdle(),false);return release(r,c);};assert.equal((await interruptGameRun(f.input,f.ports)).status,'pauseConfirmed');resolve();assert.equal((await planning).state,'cancelled');assert.equal(published,0);
});
test('invalid/hostile shutdown input cannot fence, cancel, release or execute getters',async t=>{
 for(const mode of ['epoch','buttons','snapshot','key','getter'])await t.test(mode,async()=>{const f=fixture();try{let reads=0;const input:any=structuredClone(f.input);if(mode==='epoch')input.epochAfterFence=input.request.scope.activityEpoch;if(mode==='buttons')input.request.payload.neutralButtons.a=true;if(mode==='snapshot')input.request.payload.saveState='forbidden';if(mode==='key')input.planningKey='unrelated-background-work';if(mode==='getter')Object.defineProperty(input,'request',{enumerable:true,get(){reads++;return f.input.request;}});await assert.rejects(interruptGameRun(input,f.ports),/unavailable/);assert.equal(reads,0);assert.equal(f.fences(),0);assert.equal(f.releases(),0);}finally{f.close();}});
});
