import assert from 'node:assert/strict';
import test from 'node:test';
import {randomUUID} from 'node:crypto';
import {isDeepStrictEqual} from 'node:util';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawnSync} from 'node:child_process';
import {loadMigrations} from '../../../packages/storage-sqlite/src/migrations/index.ts';
import {Database} from '../../../packages/storage-sqlite/src/database.ts';
import {GameStartRepository,type GameStartOptions,type GameStartLimits,type GameStartOccurrence} from '../../../packages/storage-sqlite/src/game-starts.ts';
import {selectGameWindow} from '@lifestream/runtime/activity/policy';
import type * as G from '@lifestream/contracts/game-activity';
import {scriptedGameBounds,scriptedGamePolicy} from '../../../packages/runtime/test/fixtures/game-policy.ts';
import {gameCampaignFixture} from '../../../packages/runtime/test/fixtures/game-campaign.ts';
import {claimConfiguredGameStart} from '../src/runtime/game-activity.ts';
const actor=(s:G.ActivityScope)=>[s.assistantId,s.principalId,s.relationshipId,s.environmentId,s.activityId];
function fixture(path=':memory:',caps={maxClaims:8,maxAssistantSlots:4}){
 let now=Date.parse('2026-09-30T12:00:00Z'),authorized=true,quarantined=false,inspection=true,receipt=false;
 const input={scope:gameCampaignFixture().input.expectedScope,policy:scriptedGamePolicy(now),bounds:structuredClone(scriptedGameBounds)},limits:GameStartLimits={enabled:true,revision:1,rollingPeriodMs:86400000,rollingStartLimit:4,startsPerWindow:1};
 const options:GameStartOptions={...caps,quarantined:()=>quarantined,limitsFor:()=>limits,admissionCurrent:(v,l)=>authorized&&isDeepStrictEqual(actor(v.scope),actor(input.scope))&&isDeepStrictEqual(v.policy,input.policy)&&isDeepStrictEqual(v.bounds,input.bounds)&&isDeepStrictEqual(l,limits),inspectionCurrent:s=>inspection&&isDeepStrictEqual(actor(s),actor(input.scope)),dispositionCurrent:(_s,_next,_revision,ref)=>receipt&&ref==='scripted-native-receipt-not-real-proof',now:()=>now};
 let db=new Database({path});db.migrate();let repository=new GameStartRepository(db,options);
 const window=(raw=input)=>selectGameWindow({...raw,purpose:'play',nowMs:now},{policyCurrent:(s,p,b)=>authorized&&isDeepStrictEqual(actor(s),actor(input.scope))&&isDeepStrictEqual(p,input.policy)&&isDeepStrictEqual(b,input.bounds),now:()=>now});
 return {input,limits,options,window,get db(){return db;},get repository(){return repository;},clock:(n:number)=>{now=n;},get now(){return now;},authorize:(v:boolean)=>{authorized=v;},quarantine:(v:boolean)=>{quarantined=v;},inspection:(v:boolean)=>{inspection=v;},receipt:(v:boolean)=>{receipt=v;},reopen:()=>{db.close();db=new Database({path});db.migrate();repository=new GameStartRepository(db,options);}};
}
const successor=(f:ReturnType<typeof fixture>)=>({...f.input,scope:{...f.input.scope,runId:randomUUID(),activityEpoch:f.input.scope.activityEpoch+1,timelineId:randomUUID()}});
const ack='scripted-native-receipt-not-real-proof';
test('first-party authentic calendar joins a durable opaque start claim without creating start/resume/controller authority',t=>{
 const f=fixture();t.after(()=>f.db.close());assert.equal(claimConfiguredGameStart(f.repository,f.input,f.window()),true);const saved=f.repository.inspect(f.input.scope)!;assert.equal(saved.recordedDisposition,'claimed');assert.equal(saved.blocksReplacement,true);assert.equal(saved.continuationAuthority,false);const row=f.db.connection.prepare('SELECT * FROM game_start_claims').get()!;assert.equal(Object.hasOwn(row,'policy_json'),false);assert.equal(Object.hasOwn(row,'scope_json'),false);assert.equal(claimConfiguredGameStart(f.repository,f.input,f.window()),false);
});
test('actual SQLite reopen preserves occurrence and Assistant blocking slot; neither another run nor another activity replaces it',t=>{
 const root=mkdtempSync(join(tmpdir(),'game-start-')),f=fixture(join(root,'metadata.sqlite'));t.after(()=>{f.db.close();rmSync(root,{recursive:true,force:true});});assert.equal(claimConfiguredGameStart(f.repository,f.input,f.window()),true);f.reopen();assert.equal(f.repository.inspect(f.input.scope)!.continuationAuthority,false);const next=successor(f);assert.equal(claimConfiguredGameStart(f.repository,next,f.window(next)),false);f.input.scope.activityId=randomUUID();const another=successor(f);assert.equal(claimConfiguredGameStart(f.repository,another,f.window(another)),false);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_start_claims').get()!.n,1);
});
test('pause and uncertain recovery keep the original slot even in later configured windows and after reopen',async t=>{
 for(const state of ['paused','recoveryRequired'] as const)await t.test(state,()=>{const root=mkdtempSync(join(tmpdir(),'game-paused-')),f=fixture(join(root,'metadata.sqlite'));try{claimConfiguredGameStart(f.repository,f.input,f.window());f.receipt(true);assert.equal(f.repository.noteDisposition(f.input.scope,state,1,ack),true);f.reopen();f.clock(f.now+86400000);const next=successor(f);assert.equal(claimConfiguredGameStart(f.repository,next,f.window(next)),false);assert.equal(f.repository.inspect(f.input.scope)!.recordedDisposition,state);}finally{f.db.close();rmSync(root,{recursive:true,force:true});}});
});
test('only source-qualified exact-old-run terminal releases its slot, while same-window identity remains spent',t=>{
 const f=fixture();t.after(()=>f.db.close());claimConfiguredGameStart(f.repository,f.input,f.window());assert.equal(f.repository.noteDisposition(f.input.scope,'stopped',1,ack),false);f.receipt(true);assert.equal(f.repository.noteDisposition({...f.input.scope,runId:randomUUID()},'stopped',1,ack),false);assert.equal(f.repository.noteDisposition(f.input.scope,'stopped',2,ack),false);assert.equal(f.repository.noteDisposition(f.input.scope,'stopped',1,'fake-receipt'),false);assert.equal(f.repository.noteDisposition(f.input.scope,'stopped',1,ack),true);assert.equal(f.repository.inspect(f.input.scope)!.blocksReplacement,false);const next=successor(f);assert.equal(claimConfiguredGameStart(f.repository,next,f.window(next)),false);f.clock(f.now+86400000);assert.equal(claimConfiguredGameStart(f.repository,next,f.window(next)),true);assert.equal(f.repository.noteDisposition(f.input.scope,'stopped',1,ack),false);assert.equal(f.db.connection.prepare('SELECT run_id FROM game_controller_slots').get()!.run_id,next.scope.runId);
});
test('withdrawn gameplay authority cannot release ownership by itself; separately qualified safety termination may still close the old run',t=>{
 const f=fixture();t.after(()=>f.db.close());claimConfiguredGameStart(f.repository,f.input,f.window());f.authorize(false);assert.equal(f.repository.noteDisposition(f.input.scope,'stopped',1,ack),false);assert.equal(f.repository.inspect(f.input.scope)!.blocksReplacement,true);f.receipt(true);assert.equal(f.repository.noteDisposition(f.input.scope,'stopped',1,ack),true);assert.equal(f.repository.inspect(f.input.scope)!.continuationAuthority,false);
});
test('actual DST repeated hour cannot create a replacement automatic claim after confirmed stop or policy-revision change',t=>{
 const f=fixture();t.after(()=>f.db.close());f.clock(Date.parse('2026-11-01T05:30:00Z'));f.input.policy.schedule.timeZone='America/New_York';f.input.policy.schedule.windows[0]!.startMinute=60;f.input.policy.schedule.windows[0]!.endMinute=120;assert.equal(claimConfiguredGameStart(f.repository,f.input,f.window()),true);f.receipt(true);f.repository.noteDisposition(f.input.scope,'stopped',1,ack);f.clock(Date.parse('2026-11-01T06:30:00Z'));const next=successor(f);assert.equal(claimConfiguredGameStart(f.repository,next,f.window(next)),false);f.input.policy.revision++;f.input.policy.schedule.validatedPolicyRevision++;f.limits.revision++;const changed=successor(f);assert.equal(claimConfiguredGameStart(f.repository,changed,f.window(changed)),false);
});
test('rolling start usage includes spent/unknown claims across policy/activity changes and cannot reset with a new window ID',t=>{
 const f=fixture();t.after(()=>f.db.close());f.limits.rollingStartLimit=1;claimConfiguredGameStart(f.repository,f.input,f.window());f.receipt(true);f.repository.noteDisposition(f.input.scope,'completed',1,ack);f.input.policy.schedule.windows[0]!.windowId=randomUUID();f.input.policy.revision++;f.input.policy.schedule.validatedPolicyRevision++;f.limits.revision++;assert.equal(claimConfiguredGameStart(f.repository,successor(f),f.window(successor(f))),false);f.clock(f.now+f.limits.rollingPeriodMs);const next=successor(f);assert.equal(claimConfiguredGameStart(f.repository,next,f.window(next)),true);
});
test('missing actual enrollment, authority, finite rolling limits, quarantine or current policy cannot claim a start',async t=>{
 for(const mode of ['authority','disabled','missingLimits','infinitePeriod','revision','quarantine','currentWindow'])await t.test(mode,()=>{const f=fixture();try{const view=f.window();if(mode==='authority')f.authorize(false);if(mode==='disabled')f.limits.enabled=false;if(mode==='missingLimits')f.options.limitsFor=()=>null;if(mode==='infinitePeriod')f.limits.rollingPeriodMs=Infinity;if(mode==='revision')f.limits.revision++;if(mode==='quarantine')f.quarantine(true);if(mode==='currentWindow')f.clock(f.now+86400000);if(['missingLimits','disabled','infinitePeriod','revision'].includes(mode))assert.throws(()=>claimConfiguredGameStart(f.repository,f.input,view),/unavailable/);else assert.equal(claimConfiguredGameStart(f.repository,f.input,view),false);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_start_claims').get()!.n,0);}finally{f.db.close();}});
});
test('copied selections, borrowed callbacks, same-revision altered policy/bounds, contact windows and hostile accessors do not enter the durable join',async t=>{
 for(const mode of ['copy','callback','policy','bounds','contact','accessor'])await t.test(mode,()=>{const f=fixture();try{let view:any=f.window(),input:any=f.input,reads=0;if(mode==='copy')view={...view};if(mode==='callback')view={...view,isCurrent:()=>true};if(mode==='policy'){input=structuredClone(input);input.policy.playWindowRef='foreign';}if(mode==='bounds'){input=structuredClone(input);input.bounds.startBudget++;}if(mode==='contact'){f.input.policy.contactConfiguration={...f.input.policy.schedule,channelRef:'scripted-channel',recipientRef:'scripted-recipient'};view=selectGameWindow({...f.input,purpose:'contact',nowMs:f.now},{policyCurrent:()=>true,now:()=>f.now});}if(mode==='accessor'){view={};Object.defineProperty(view,'purpose',{get(){reads++;return 'play';}});}assert.equal(claimConfiguredGameStart(f.repository,input,view),false);assert.equal(reads,0);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_start_claims').get()!.n,0);}finally{f.db.close();}});
});
test('withdrawal at final admission recheck rolls claim and slot back atomically',t=>{
 const f=fixture();t.after(()=>f.db.close());let calls=0;f.options.admissionCurrent=()=>{if(++calls===3)f.quarantine(true);return true;};assert.throws(()=>claimConfiguredGameStart(f.repository,f.input,f.window()),/unavailable/);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_start_claims').get()!.n,0);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_controller_slots').get()!.n,0);
});
test('final window-end and later clock rollback refuse claims rather than turning a missed window into catch-up',t=>{
 const f=fixture();t.after(()=>f.db.close());let calls=0;f.options.admissionCurrent=()=>{if(++calls===3)f.clock(f.now+86400000);return true;};assert.throws(()=>claimConfiguredGameStart(f.repository,f.input,f.window()),/unavailable/);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_start_claims').get()!.n,0);f.options.admissionCurrent=()=>true;f.clock(f.now-86400001);assert.throws(()=>claimConfiguredGameStart(f.repository,f.input,f.window()),/unavailable/);
});
test('final disposition-source withdrawal rolls termination back, preserving the blocking slot',t=>{
 const f=fixture();t.after(()=>f.db.close());claimConfiguredGameStart(f.repository,f.input,f.window());let calls=0;f.options.dispositionCurrent=()=>{if(++calls===3)f.inspection(false);return true;};assert.throws(()=>f.repository.noteDisposition(f.input.scope,'stopped',1,ack),/unavailable/);f.inspection(true);assert.equal(f.repository.inspect(f.input.scope)!.recordedDisposition,'claimed');assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_controller_slots').get()!.n,1);
});
test('global bounded capacities stay pinned and spent identities are not evicted to permit repeated starts',t=>{
 const f=fixture(':memory:',{maxClaims:1,maxAssistantSlots:1});t.after(()=>f.db.close());claimConfiguredGameStart(f.repository,f.input,f.window());f.receipt(true);f.repository.noteDisposition(f.input.scope,'stopped',1,ack);f.options.maxClaims=Infinity;f.clock(f.now+86400000);const next=successor(f);assert.throws(()=>claimConfiguredGameStart(f.repository,next,f.window(next)),/unavailable/);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_start_claims').get()!.n,1);
});
test('foreign owner/environment/context cannot inspect or close another claim and invalid canonical inputs never execute getters',t=>{
 const f=fixture();t.after(()=>f.db.close());claimConfiguredGameStart(f.repository,f.input,f.window());for(const key of ['assistantId','principalId','relationshipId','environmentId','activityId'] as const)assert.equal(f.repository.inspect({...f.input.scope,[key]:randomUUID()}),null);assert.equal(f.repository.inspect({...f.input.scope,contextBinding:{...f.input.scope.contextBinding,sessionId:randomUUID()}}),null);f.receipt(true);assert.equal(f.repository.noteDisposition({...f.input.scope,activityEpoch:3},'stopped',1,ack),false);let reads=0;const raw:any={scope:f.input.scope,policy:f.input.policy,bounds:f.input.bounds,windowId:f.input.policy.schedule.windows[0]!.windowId,localDate:'2026-09-30',occurrenceKey:'a'.repeat(64)};Object.defineProperty(raw,'policy',{enumerable:true,get(){reads++;return f.input.policy;}});assert.throws(()=>f.repository.claim(raw,()=>true),/unavailable/);assert.equal(reads,0);assert.throws(()=>f.repository.claim({...raw,emulatorSnapshot:'forbidden'} as GameStartOccurrence,()=>true),/unavailable/);
});
test('a separate fresh Node process retains the original opaque claim and controller slot with no continuation permission',t=>{
 const root=mkdtempSync(join(tmpdir(),'game-start-process-')),path=join(root,'metadata.sqlite'),f=fixture(path);t.after(()=>rmSync(root,{recursive:true,force:true}));claimConfiguredGameStart(f.repository,f.input,f.window());f.db.close();
 const script=`import {Database} from ${JSON.stringify(new URL('../../../packages/storage-sqlite/src/database.ts',import.meta.url).href)};import {GameStartRepository} from ${JSON.stringify(new URL('../../../packages/storage-sqlite/src/game-starts.ts',import.meta.url).href)};import {selectGameWindow} from ${JSON.stringify(import.meta.resolve('@lifestream/runtime/activity/policy'))};import {claimConfiguredGameStart} from ${JSON.stringify(new URL('../src/runtime/game-activity.ts',import.meta.url).href)};const data=JSON.parse(process.argv[1]),db=new Database({path:data.path});db.migrate();const repository=new GameStartRepository(db,{maxClaims:8,maxAssistantSlots:4,quarantined:()=>false,limitsFor:()=>data.limits,admissionCurrent:()=>true,inspectionCurrent:()=>true,dispositionCurrent:()=>false,now:()=>data.now});const view=selectGameWindow({...data.input,purpose:'play',nowMs:data.now},{policyCurrent:()=>true,now:()=>data.now});console.log(JSON.stringify({inspection:repository.inspect(data.input.scope),duplicate:claimConfiguredGameStart(repository,data.input,view),slots:db.connection.prepare('SELECT count(*) AS n FROM game_controller_slots').get().n}));db.close();`;
 const child=spawnSync(process.execPath,['--experimental-strip-types','--input-type=module','-e',script,JSON.stringify({path,input:f.input,limits:f.limits,now:f.now})],{encoding:'utf8',timeout:10000});assert.equal(child.status,0,child.stderr);const result=JSON.parse(child.stdout);assert.equal(result.inspection.recordedDisposition,'claimed');assert.equal(result.inspection.blocksReplacement,true);assert.equal(result.inspection.continuationAuthority,false);assert.equal(result.duplicate,false);assert.equal(result.slots,1);
});
test('additive migration63 preserves the exact previous migration records and existing shared durable clock floor',t=>{
 const root=mkdtempSync(join(tmpdir(),'game-start-upgrade-')),path=join(root,'metadata.sqlite');let db=new Database({path,migrations:loadMigrations().filter(m=>m.id<=62)});const previous=db.migrate();db.connection.prepare('UPDATE activity_metadata_clock SET observed_at=12345 WHERE singleton=1').run();db.close();db=new Database({path});t.after(()=>{db.close();rmSync(root,{recursive:true,force:true});});const upgraded=db.migrate();assert.deepEqual(upgraded.slice(0,previous.length),previous);assert.deepEqual(upgraded.slice(previous.length).map(m=>m.id),[63]);assert.equal(db.connection.prepare('SELECT observed_at FROM activity_metadata_clock').get()!.observed_at,12345);assert.equal(db.connection.prepare('SELECT count(*) AS n FROM game_start_claims').get()!.n,0);assert.equal(db.connection.prepare('SELECT count(*) AS n FROM game_controller_slots').get()!.n,0);
});
test('late restore quarantine or inspection withdrawal withholds persisted claim inspection',async t=>{
 for(const mode of ['quarantine','owner'])await t.test(mode,()=>{const f=fixture();try{claimConfiguredGameStart(f.repository,f.input,f.window());let calls=0;f.options.inspectionCurrent=()=>{if(++calls===2){if(mode==='quarantine')f.quarantine(true);else return false;}return true;};assert.equal(f.repository.inspect(f.input.scope),null);}finally{f.db.close();}});
});
