import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {Database,MemoryRepository,GameExperienceRepository,GameHelpRepository,type MemoryRecord} from '@lifestream/storage-sqlite';
import {fixtureEpisode,fixtureGameHelpItem,fixtureGameEpisodeSources} from '../../../packages/runtime/test/fixtures/game-memory.ts';
import {selectGameAdvice,type GameAdvicePorts,type GameAdviceReply} from '../src/runtime/game-advice.ts';
import {CampaignJournalRepository} from '@lifestream/storage-sqlite';
import {campaignJournalFixture} from '../../../packages/storage-sqlite/test/fixtures/campaign-journal.ts';
import {selectCampaignContext} from '@lifestream/runtime/activity/journal';
function fixture(t:import('node:test').TestContext){
 let now=Date.now(),revision=1,authenticated=true,current=true,relevant=true;const db=new Database({path:':memory:'});db.migrate();t.after(()=>db.close());const e=fixtureEpisode(now),owner={principalId:e.scope.principalId,assistantId:e.scope.assistantId,relationshipId:e.scope.relationshipId},sources=fixtureGameEpisodeSources(e);
 db.connection.prepare('INSERT INTO automatic_memory_policies VALUES(?,?,?,?,?,?,?)').run('test-only:owned-memory',owner.principalId,owner.assistantId,owner.relationshipId,1,1,new Date(now).toISOString());
 const episodes=new GameExperienceRepository(db,{maximumFences:4,scopeCurrent:()=>true,quarantined:()=>false,retentionFor:()=>({retentionMs:86400000,retentionPolicyRef:e.retentionPolicyRef,maximumEpisodes:4,maximumBytes:8192}),sourceRecordsFor:()=>sources,meaningfulGroundingCurrent:()=>true,publicationCurrent:()=>true,retainedSourceCurrent:()=>current,now:()=>now});assert.equal(episodes.admit(e),true);
 const item=fixtureGameHelpItem(e,now),help=new GameHelpRepository(db,{maximumFences:4,scopeCurrent:()=>true,quarantined:()=>false,retentionFor:()=>({revision:1,policyRef:'test-only:help-retention',retentionMs:30000,maximumItems:4,maximumBytes:8192}),episodeFor:(o,id)=>episodes.get(o,id),boundaryRevision:()=>String(revision),pendingCurrent:()=>current,situationKeyFor:()=> 'd'.repeat(64),now:()=>now});assert.equal(help.queue({item,episodeId:e.episodeId,expiresAt:now+30000}),true);
 const memories=new MemoryRepository(db),turn=randomUUID(),quote='Try the visible lever before crossing.',m:MemoryRecord={id:randomUUID(),assistantId:owner.assistantId,content:'User stated: '+quote,provenance:{actor:owner.principalId,relationshipId:owner.relationshipId,sourceTurnRef:turn,sourceFamily:'turn:'+turn,epistemicStatus:'userStatement',transformation:'exact-attributed-quote-v1'},lifecycle:{status:'candidate',revision:1,kind:'experiential',sensitivity:'private',confidence:1},createdAt:new Date(now).toISOString()};memories.save(m);memories.transition(m.assistantId,m.id,'active',owner.principalId,true);
 const reply:GameAdviceReply={helpId:item.helpId,helpRevision:1,...owner,channelRef:item.channelRef,recipientRef:item.recipientRef,sourceTurnRef:turn,sourceSessionRef:'test-only:authenticated-human-session',memoryId:m.id,memoryRevision:2,quotedAdvice:quote,questionDeliveryEvidenceRef:'test-only:actual-question-delivery',authenticatedReplyEvidenceRef:'test-only:authenticated-human-input',receivedAt:new Date(now).toISOString()},o=structuredClone(sources.observations[0]!);o.observationId=randomUUID();o.capturedAt=o.receivedAt=o.interpretedAt=new Date(now).toISOString();for(const s of o.screenshots){s.screenshotId=randomUUID();s.capturedAt=o.capturedAt;s.expiresAt=new Date(now+6000).toISOString();}o.facts[0]!.sourceScreenshotIds=o.screenshots.map(s=>s.screenshotId);
 const input={scope:structuredClone(e.scope),reply,observation:o,maximumBytes:8192,maximumObservationAgeMs:6000,nowMs:now,freshUntilMs:now+5000},ports:GameAdvicePorts={memories,help,boundaryRevision:()=>String(revision),scopeCurrent:()=>current&&db.connection.prepare('SELECT enabled FROM automatic_memory_policies').get()!.enabled===1,replyCurrent:()=>authenticated,observationCurrent:()=>current,adviceRelevantCurrent:()=>relevant,now:()=>now};
 return {db,e,item,m,reply,memories,help,input,ports,advance:(ms:number)=>now+=ms,withdraw:()=>{current=false;revision++;},unauthenticate:()=>authenticated=false,irrelevant:()=>relevant=false,change:()=>revision++};
}
test('retained exact Human input and qualified reply select inert attributed advice with distinct Human session',t=>{
 const f=fixture(t),v=selectGameAdvice(f.input,f.ports);assert.equal(v.state,'selected');assert.equal(v.isCurrent(),true);assert.equal(v.entry!.kind,'humanAdvice');assert.equal(v.entry!.epistemicKind,'humanAdvice');assert.equal(v.entry!.content,f.m.content);assert.equal(v.entry!.sourceSessionRef,f.reply.sourceSessionRef);assert.notEqual(v.entry!.sourceSessionRef,f.e.scope.contextBinding.sessionId);assert.equal(v.playAuthority,false);assert.equal(v.resumeAuthority,false);assert.equal(v.sendAuthority,false);
 const source=JSON.parse(v.content!);assert.equal(source.sourceType,'participantStatement');assert.equal(source.quotedAdvice,f.reply.quotedAdvice);assert.equal(source.freshObservationId,f.input.observation.observationId);assert.match(v.content!,/not an observed game outcome/);assert.ok(!v.content!.includes(f.reply.recipientRef));assert.ok(Object.isFrozen(v.entry));assert.equal(selectGameAdvice(f.input,f.ports).adviceRef,v.adviceRef,'reselection cannot invent independent advice');assert.equal(f.help.get({principalId:f.e.scope.principalId,assistantId:f.e.scope.assistantId,relationshipId:f.e.scope.relationshipId},f.item.helpId)!.item.status,'queued','source selection cannot fabricate channel status');assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_start_claims').get()!.n,0);
});
for(const port of ['scopeCurrent','replyCurrent','observationCurrent','adviceRelevantCurrent']as const)test('advice requires independent '+port,t=>{const f=fixture(t);f.ports[port]=()=>false;assert.equal(selectGameAdvice(f.input,f.ports).state,'unavailable');});
for(const [label,change]of [
 ['wrong actor',(v:any)=>v.reply.principalId=randomUUID()],['wrong relationship',(v:any)=>v.reply.relationshipId=randomUUID()],['wrong recipient',(v:any)=>v.reply.recipientRef='foreign:recipient'],['wrong channel',(v:any)=>v.reply.channelRef='foreign:channel'],['wrong question',(v:any)=>v.reply.helpId=randomUUID()],['wrong revision',(v:any)=>v.reply.helpRevision=2],['foreign timeline',(v:any)=>v.observation.scope.timelineId=randomUUID()],['wrong pins',(v:any)=>v.observation.pinsDigest='e'.repeat(64)],['pre-answer observation',(v:any)=>v.observation.capturedAt=new Date(v.nowMs-1).toISOString()],['future answer',(v:any)=>v.reply.receivedAt=new Date(v.nowMs+1).toISOString()],['invented quote',(v:any)=>v.reply.quotedAdvice='The gate opened successfully'],['foreign source turn',(v:any)=>v.reply.sourceTurnRef=randomUUID()],['unknown field',(v:any)=>v.reply.authority=true],['missing input receipt',(v:any)=>v.reply.authenticatedReplyEvidenceRef=''],['missing source session',(v:any)=>v.reply.sourceSessionRef=''],['byte ceiling',(v:any)=>v.maximumBytes=1],['invalid time type',(v:any)=>v.reply.receivedAt=2026]
]as const)test('advice source rejects '+label,t=>{const f=fixture(t);change(f.input);assert.equal(selectGameAdvice(f.input,f.ports).state,'unavailable');});

for(const cause of ['memory','help','policy','reply','timeline','expiry','rollback']as const)test('held advice source permanently retires after '+cause,t=>{
 const f=fixture(t),v=selectGameAdvice(f.input,f.ports);assert.equal(v.state,'selected');if(cause==='memory')f.memories.forget(f.m.assistantId,f.m.id,f.e.scope.principalId);if(cause==='help')f.help.forget({principalId:f.e.scope.principalId,assistantId:f.e.scope.assistantId,relationshipId:f.e.scope.relationshipId},f.item.helpId,1);if(cause==='policy')f.db.exec('UPDATE automatic_memory_policies SET enabled=0,revision=revision+1');if(cause==='reply')f.unauthenticate();if(cause==='timeline')f.change();if(cause==='expiry')f.advance(5000);if(cause==='rollback')f.advance(-1);assert.equal(v.isCurrent(),false);f.advance(1);assert.equal(v.isCurrent(),false);
});

test('late Human forgetting during relevance qualification fences preparation before disclosure',t=>{const f=fixture(t);f.ports.adviceRelevantCurrent=()=>{f.memories.forget(f.m.assistantId,f.m.id,f.e.scope.principalId);return true;};assert.equal(selectGameAdvice(f.input,f.ports).state,'unavailable');});
test('caller mutation cannot replace captured authentication or retained source content',t=>{const f=fixture(t),v=selectGameAdvice(f.input,f.ports);f.ports.replyCurrent=()=>true;f.input.reply.quotedAdvice='Invented later claim';assert.equal(v.isCurrent(),true);assert.doesNotMatch(v.content!,/Invented later/);f.unauthenticate();assert.equal(v.isCurrent(),false);});
for(const cause of ['gameOrigin','visualOrigin','summaryTransform','inactive','sourceFamily']as const)test('game dialogue or unattributed memory cannot become Human advice '+cause,t=>{const f=fixture(t),r=f.memories.get(f.m.assistantId,f.m.id)!;if(cause==='gameOrigin')r.provenance.gameEpisodeId=randomUUID();if(cause==='visualOrigin')r.provenance.visualEpisodeId=randomUUID();if(cause==='summaryTransform')r.provenance.transformation='model-summary';if(cause==='sourceFamily')r.provenance.sourceFamily='game:fiction';if(cause==='inactive')r.lifecycle.status='candidate';f.db.connection.prepare('UPDATE memories SET provenance_json=?,lifecycle_json=? WHERE id=?').run(JSON.stringify(r.provenance),JSON.stringify(r.lifecycle),r.id);assert.equal(selectGameAdvice(f.input,f.ports).state,'unavailable');});

test('qualified advice entry reuses existing bounded journal/context and Human forgetting erases dependent prose',t=>{
 const f=fixture(t),advice=selectGameAdvice(f.input,f.ports);assert.equal(advice.state,'selected');const j=campaignJournalFixture(f.input.nowMs),owner={principalId:f.e.scope.principalId,assistantId:f.e.scope.assistantId,relationshipId:f.e.scope.relationshipId};j.campaignId=f.e.scope.campaignId;j.entries=[structuredClone(advice.entry!)];j.summary='An attributed Human suggestion remains to be tested.';j.summaryEntryIds=[advice.entry!.entryId];j.goals=[];
 const repo=new CampaignJournalRepository(f.db,{maxJournals:4,maxEntryIdentities:16,maxSourceFences:32,maxJournalBytes:8192,scopeCurrent:()=>true,quarantined:()=>false,policyFor:()=>({enabled:true,revision:1,retentionMs:30000,retentionPolicyRef:j.retentionPolicyRef}),allowCreate:()=>true,sourceCurrent:(_o,entry)=>entry.entryId===advice.entry!.entryId&&advice.isCurrent(),journalCurrent:()=>advice.isCurrent(),now:()=>f.input.nowMs});repo.put(owner,j,0);const context=selectCampaignContext(repo.get(owner,j.journalId)!,8192,f.input.nowMs,()=>advice.isCurrent());assert.equal(context.status,'selected');assert.match(context.content!,/humanAdvice/);assert.match(context.content!,/Try the visible lever/);assert.match(context.content!,/not an observed game outcome/);
 f.memories.forget(f.m.assistantId,f.m.id,owner.principalId);assert.equal(context.isCurrent(),false);assert.equal(repo.get(owner,j.journalId),null);assert.equal(repo.inspect(owner,j.journalId)!.state,'needsReview');assert.equal(f.db.connection.prepare('SELECT payload_json FROM campaign_journal_entries').get()!.payload_json,null);assert.equal(f.db.connection.prepare('SELECT header_json FROM campaign_journals').get()!.header_json,null);assert.doesNotMatch(JSON.stringify(repo.inspect(owner,j.journalId)),/Try the visible lever/);
});
