import {selectGameAdviceOutcome,type GameAdviceOutcomePorts} from '../src/runtime/game-advice-outcome.ts';
import {gameCampaignFixture} from '../../../packages/runtime/test/fixtures/game-campaign.ts';
import {selectGameCampaignContext,prepareGameCampaignContext,gameDecisionInput} from '@lifestream/runtime/activity/game-journal';
import {createPreparedTurnBinding,finalizePreparedTurn,requestForFinalizedTurn} from '@lifestream/runtime/inference/prompt';
import type * as G from '@lifestream/contracts/game-activity';
import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {Database,MemoryRepository,GameExperienceRepository,GameHelpRepository,type MemoryRecord} from '@lifestream/storage-sqlite';
import {fixtureEpisode,fixtureGameHelpItem,fixtureGameEpisodeSources,projection} from '../../../packages/runtime/test/fixtures/game-memory.ts';
import {gameAdviceEpisodeSource,gameAdviceHistoricalSourceCurrent,selectGameAdvice,type GameAdvicePorts,type GameAdviceReply} from '../src/runtime/game-advice.ts';
import {CampaignJournalRepository} from '@lifestream/storage-sqlite';
import {campaignJournalFixture} from '../../../packages/storage-sqlite/test/fixtures/campaign-journal.ts';
import {selectCampaignContext} from '@lifestream/runtime/activity/journal';
function fixture(t:import('node:test').TestContext){
 let now=Date.now(),revision=1,authenticated=true,current=true,relevant=true,paused=true;const db=new Database({path:':memory:'});db.migrate();t.after(()=>db.close());const e=fixtureEpisode(now),owner={principalId:e.scope.principalId,assistantId:e.scope.assistantId,relationshipId:e.scope.relationshipId},sources=fixtureGameEpisodeSources(e);
 db.connection.prepare('INSERT INTO automatic_memory_policies VALUES(?,?,?,?,?,?,?)').run('test-only:owned-memory',owner.principalId,owner.assistantId,owner.relationshipId,1,1,new Date(now).toISOString());
 const episodes=new GameExperienceRepository(db,{maximumFences:4,scopeCurrent:()=>true,quarantined:()=>false,retentionFor:()=>({retentionMs:86400000,retentionPolicyRef:e.retentionPolicyRef,maximumEpisodes:4,maximumBytes:8192}),sourceRecordsFor:()=>sources,meaningfulGroundingCurrent:()=>true,publicationCurrent:()=>true,retainedSourceCurrent:()=>current,now:()=>now});assert.equal(episodes.admit(e),true);
 const item=fixtureGameHelpItem(e,now),help=new GameHelpRepository(db,{maximumFences:4,scopeCurrent:()=>true,quarantined:()=>false,retentionFor:()=>({revision:1,policyRef:'test-only:help-retention',retentionMs:30000,maximumItems:4,maximumBytes:8192}),episodeFor:(o,id)=>episodes.get(o,id),boundaryRevision:()=>String(revision),pendingCurrent:()=>current&&paused,situationKeyFor:()=> 'd'.repeat(64),now:()=>now});assert.equal(help.queue({item,episodeId:e.episodeId,expiresAt:now+30000}),true);
 const memories=new MemoryRepository(db),turn=randomUUID(),quote='Try the visible lever before crossing.',m:MemoryRecord={id:randomUUID(),assistantId:owner.assistantId,content:'User stated: '+quote,provenance:{actor:owner.principalId,relationshipId:owner.relationshipId,sourceTurnRef:turn,sourceFamily:'turn:'+turn,epistemicStatus:'userStatement',transformation:'exact-attributed-quote-v1'},lifecycle:{status:'candidate',revision:1,kind:'experiential',sensitivity:'private',confidence:1},createdAt:new Date(now).toISOString()};memories.save(m);memories.transition(m.assistantId,m.id,'active',owner.principalId,true);
 const reply:GameAdviceReply={helpId:item.helpId,helpRevision:1,...owner,channelRef:item.channelRef,recipientRef:item.recipientRef,sourceTurnRef:turn,sourceSessionRef:'test-only:authenticated-human-session',memoryId:m.id,memoryRevision:2,quotedAdvice:quote,questionDeliveryEvidenceRef:'test-only:actual-question-delivery',authenticatedReplyEvidenceRef:'test-only:authenticated-human-input',receivedAt:new Date(now).toISOString()},o=structuredClone(sources.observations[0]!);o.observationId=randomUUID();o.capturedAt=o.receivedAt=o.interpretedAt=new Date(now).toISOString();for(const s of o.screenshots){s.screenshotId=randomUUID();s.capturedAt=o.capturedAt;s.expiresAt=new Date(now+6000).toISOString();}o.facts[0]!.sourceScreenshotIds=o.screenshots.map(s=>s.screenshotId);
 const input={scope:structuredClone(e.scope),reply,observation:o,maximumBytes:8192,maximumObservationAgeMs:6000,nowMs:now,freshUntilMs:now+5000},ports:GameAdvicePorts={memories,help,boundaryRevision:()=>String(revision),scopeCurrent:()=>current&&db.connection.prepare('SELECT enabled FROM automatic_memory_policies').get()!.enabled===1,replyCurrent:()=>authenticated,observationCurrent:()=>current,adviceRelevantCurrent:()=>relevant,now:()=>now};
 return {unpause:()=>paused=false,db,e,item,m,reply,memories,help,input,ports,advance:(ms:number)=>now+=ms,withdraw:()=>{current=false;revision++;},unauthenticate:()=>authenticated=false,irrelevant:()=>relevant=false,change:()=>revision++};
}
test('retained exact Human input and qualified reply select inert attributed advice with distinct Human session',t=>{
 const f=fixture(t),v=selectGameAdvice(f.input,f.ports);assert.equal(v.state,'selected');assert.equal(v.isCurrent(),true);assert.equal(v.entry!.kind,'humanAdvice');assert.equal(v.entry!.epistemicKind,'humanAdvice');assert.equal(v.entry!.content,f.m.content);assert.equal(v.entry!.sourceSessionRef,f.reply.sourceSessionRef);assert.notEqual(v.entry!.sourceSessionRef,f.e.scope.contextBinding.sessionId);assert.equal(v.playAuthority,false);assert.equal(v.resumeAuthority,false);assert.equal(v.sendAuthority,false);
 const source=JSON.parse(v.content!);assert.equal(source.sourceType,'participantStatement');assert.equal(source.quotedAdvice,f.reply.quotedAdvice);assert.equal(source.freshObservationId,f.input.observation.observationId);assert.match(v.content!,/not an observed game outcome/);assert.ok(!v.content!.includes(f.reply.recipientRef));assert.ok(Object.isFrozen(v.entry));assert.equal(selectGameAdvice(f.input,f.ports).adviceRef,v.adviceRef,'reselection cannot invent independent advice');assert.equal(f.help.get({principalId:f.e.scope.principalId,assistantId:f.e.scope.assistantId,relationshipId:f.e.scope.relationshipId},f.item.helpId)!.item.status,'queued','source selection cannot fabricate channel status');assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_start_claims').get()!.n,0);
});
for(const port of ['scopeCurrent','replyCurrent','observationCurrent','adviceRelevantCurrent']as const)test('advice requires independent '+port,t=>{const f=fixture(t);f.ports[port]=()=>false;assert.equal(selectGameAdvice(f.input,f.ports).state,'unavailable');});
for(const [label,change]of [
 ['wrong actor',(v:any)=>v.reply.principalId=randomUUID()],['wrong relationship',(v:any)=>v.reply.relationshipId=randomUUID()],['wrong recipient',(v:any)=>v.reply.recipientRef='foreign:recipient'],['wrong channel',(v:any)=>v.reply.channelRef='foreign:channel'],['wrong question',(v:any)=>v.reply.helpId=randomUUID()],['wrong revision',(v:any)=>v.reply.helpRevision=2],['foreign timeline',(v:any)=>v.observation.scope.timelineId=randomUUID()],['wrong pins',(v:any)=>v.observation.pinsDigest='e'.repeat(64)],['pre-answer observation',(v:any)=>v.observation.capturedAt=new Date(v.nowMs-1).toISOString()],['future answer',(v:any)=>v.reply.receivedAt=new Date(v.nowMs+1).toISOString()],['invented quote',(v:any)=>v.reply.quotedAdvice='The gate opened successfully'],['foreign source turn',(v:any)=>v.reply.sourceTurnRef=randomUUID()],['unknown field',(v:any)=>v.reply.authority=true],['missing input receipt',(v:any)=>v.reply.authenticatedReplyEvidenceRef=''],['missing source session',(v:any)=>v.reply.sourceSessionRef=''],['byte ceiling',(v:any)=>v.maximumBytes=1],['invalid time type',(v:any)=>v.reply.receivedAt=2026]
]as const)test('advice source rejects '+label,t=>{const f=fixture(t);change(f.input);assert.equal(selectGameAdvice(f.input,f.ports).state,'unavailable');});

for(const cause of ['memory','help','policy','reply','timeline','expiry','rollback']as const)test('held advice source permanently retires after '+cause,t=>{
 const f=fixture(t),v=selectGameAdvice(f.input,f.ports);assert.equal(v.state,'selected');if(cause==='memory')f.memories.forget(f.m.assistantId,f.m.id,f.e.scope.principalId);if(cause==='help')f.help.forget({principalId:f.e.scope.principalId,assistantId:f.e.scope.assistantId,relationshipId:f.e.scope.relationshipId},f.item.helpId,1);if(cause==='policy')f.db.exec('UPDATE automatic_memory_policies SET enabled=0,revision=revision+1');if(cause==='reply')f.unauthenticate();if(cause==='timeline')f.change();if(cause==='expiry')f.advance(5000);if(cause==='rollback')f.advance(-1);assert.equal(v.isCurrent(),false);f.advance(1);assert.equal(v.isCurrent(),false);
});

test('late Human forgetting during relevance qualification fences preparation before disclosure',t=>{const f=fixture(t);f.ports.adviceRelevantCurrent=()=>{f.memories.forget(f.m.assistantId,f.m.id,f.e.scope.principalId);return true;};assert.equal(selectGameAdvice(f.input,f.ports).state,'unavailable');});
test('caller mutation cannot replace captured authentication or retained source content',t=>{const f=fixture(t),v=selectGameAdvice(f.input,f.ports);f.ports.replyCurrent=()=>true;f.input.reply.quotedAdvice='Invented later claim';assert.equal(v.isCurrent(),true);assert.doesNotMatch(v.content!,/Invented later/);f.unauthenticate();assert.equal(v.isCurrent(),false);});
for(const cause of ['gameOrigin','visualOrigin','summaryTransform','inactive','sourceFamily']as const)test('game dialogue or unattributed memory cannot become Human advice '+cause,t=>{const f=fixture(t),r=f.memories.get(f.m.assistantId,f.m.id)!;if(cause==='gameOrigin')r.provenance.gameEpisodeId=randomUUID();if(cause==='visualOrigin')r.provenance.visualEpisodeId=randomUUID();if(cause==='summaryTransform')r.provenance.transformation='model-summary';if(cause==='sourceFamily')r.provenance.sourceFamily='game:fiction';if(cause==='inactive')r.lifecycle.status='candidate';f.db.connection.prepare('UPDATE memories SET provenance_json=?,lifecycle_json=? WHERE id=?').run(JSON.stringify(r.provenance),JSON.stringify(r.lifecycle),r.id);assert.equal(selectGameAdvice(f.input,f.ports).state,'unavailable');});

test('qualified advice entry reuses existing bounded journal/context and Human forgetting erases dependent prose',t=>{
 const f=fixture(t),advice=selectGameAdvice(f.input,f.ports);assert.equal(advice.state,'selected');const j=campaignJournalFixture(f.input.nowMs),owner={principalId:f.e.scope.principalId,assistantId:f.e.scope.assistantId,relationshipId:f.e.scope.relationshipId};j.campaignId=f.e.scope.campaignId;j.entries=[structuredClone(advice.entry!)];j.summary='An attributed Human suggestion remains to be tested.';j.summaryEntryIds=[advice.entry!.entryId];j.goals=[];
 const repo=new CampaignJournalRepository(f.db,{maxJournals:4,maxEntryIdentities:16,maxSourceFences:32,maxJournalBytes:8192,scopeCurrent:()=>true,quarantined:()=>false,policyFor:()=>({enabled:true,revision:1,retentionMs:30000,retentionPolicyRef:j.retentionPolicyRef}),allowCreate:()=>true,sourceCurrent:(_o,entry)=>entry.entryId===advice.entry!.entryId&&advice.isCurrent(),journalCurrent:()=>advice.isCurrent(),now:()=>f.input.nowMs});repo.put(owner,j,0);const context=selectCampaignContext(repo.get(owner,j.journalId)!,8192,f.input.nowMs,()=>advice.isCurrent());assert.equal(context.status,'selected');assert.match(context.content!,/humanAdvice/);assert.match(context.content!,/Try the visible lever/);assert.match(context.content!,/not an observed game outcome/);
 f.memories.forget(f.m.assistantId,f.m.id,owner.principalId);assert.equal(context.isCurrent(),false);assert.equal(repo.get(owner,j.journalId),null);assert.equal(repo.inspect(owner,j.journalId)!.state,'needsReview');assert.equal(f.db.connection.prepare('SELECT payload_json FROM campaign_journal_entries').get()!.payload_json,null);assert.equal(f.db.connection.prepare('SELECT header_json FROM campaign_journals').get()!.header_json,null);assert.doesNotMatch(JSON.stringify(repo.inspect(owner,j.journalId)),/Try the visible lever/);
});

test('resumed native lifecycle withholds current advice while retained original Human/question lineage remains historical',t=>{
 const f=fixture(t),advice=selectGameAdvice(f.input,f.ports);assert.equal(advice.state,'selected');assert.equal(gameAdviceHistoricalSourceCurrent(advice),true);f.unpause();assert.equal(advice.isCurrent(),false);assert.equal(f.help.get({principalId:f.e.scope.principalId,assistantId:f.e.scope.assistantId,relationshipId:f.e.scope.relationshipId},f.item.helpId),null);assert.equal(gameAdviceHistoricalSourceCurrent(advice),true);assert.equal(advice.playAuthority,false);assert.equal(advice.resumeAuthority,false);assert.equal(advice.sendAuthority,false);
});
for(const cause of ['memory','help','policy','reply','source','expiry','rollback']as const)test('historical advice lineage permanently retires after '+cause,t=>{
 const f=fixture(t),advice=selectGameAdvice(f.input,f.ports);assert.equal(gameAdviceHistoricalSourceCurrent(advice),true);if(cause==='memory')f.memories.forget(f.m.assistantId,f.m.id,f.e.scope.principalId);if(cause==='help')f.help.forget({principalId:f.e.scope.principalId,assistantId:f.e.scope.assistantId,relationshipId:f.e.scope.relationshipId},f.item.helpId,1);if(cause==='policy')f.db.exec('UPDATE automatic_memory_policies SET enabled=0,revision=revision+1');if(cause==='reply')f.unauthenticate();if(cause==='source')f.withdraw();if(cause==='expiry')f.advance(30000);if(cause==='rollback')f.advance(-1);assert.equal(gameAdviceHistoricalSourceCurrent(advice),false);f.advance(1);assert.equal(gameAdviceHistoricalSourceCurrent(advice),false);
});
test('copying advice metadata cannot mint historical custody or restore current planning authority',t=>{const f=fixture(t),advice=selectGameAdvice(f.input,f.ports);assert.equal(gameAdviceHistoricalSourceCurrent({...advice,isCurrent:()=>true}),false);f.advance(5000);assert.equal(advice.isCurrent(),false);assert.equal(gameAdviceHistoricalSourceCurrent(advice),true);});


test('late Human forgetting during historical authentication recheck fences retained lineage',t=>{const f=fixture(t);let armed=false,calls=0;f.ports.replyCurrent=()=>{if(armed&&++calls===2)f.memories.forget(f.m.assistantId,f.m.id,f.e.scope.principalId);return true;};const advice=selectGameAdvice(f.input,f.ports);assert.equal(advice.state,'selected');armed=true;assert.equal(gameAdviceHistoricalSourceCurrent(advice),false);assert.equal(f.memories.get(f.m.assistantId,f.m.id)!.content,'');});

function outcomeFixture(t:import('node:test').TestContext){
 const f=fixture(t),advice=selectGameAdvice(f.input,f.ports),campaign=gameCampaignFixture(),scope=f.e.scope,now=f.input.nowMs;assert.equal(advice.state,'selected');const journal=campaign.input.journal;journal.updatedAt=new Date(now).toISOString();journal.campaignId=scope.campaignId;journal.entries=[structuredClone(advice.entry!)];journal.summary='An attributed suggestion is not yet tested.';journal.summaryEntryIds=[advice.entry!.entryId];journal.goals=[];
 const observation=structuredClone(f.input.observation);observation.visibleState=[{fieldId:'test-only:visible-lever',value:'closed',visibility:'visibleNow',firstObservedRef:observation.observationId,lastObservedRef:observation.observationId,timelineId:scope.timelineId,observedAt:observation.receivedAt,freshUntil:new Date(now+5000).toISOString(),decoderRevision:'1.0.0',manifestDigest:f.e.pinsDigest,limitations:['Scripted visible source only.']}];
 Object.assign(campaign.input,{expectedScope:scope,pinsDigest:f.e.pinsDigest,observation,journal,nowMs:now,freshUntilMs:now+5000});Object.assign(campaign.input.binding,{scope,journal,pinsDigest:f.e.pinsDigest,ordinarySaveLineageRef:null,ordinarySaveArtifact:null,entryBindings:[{entryId:advice.entry!.entryId,runId:scope.runId,timelineId:scope.timelineId,sourceObservationIds:[],sourceActionIds:[],sourceAdviceRefs:[advice.adviceRef!],ordinarySaveDigest:null,currentDisposition:'current'}],reconciledObservationId:observation.observationId,reconciledAt:observation.receivedAt});campaign.clock(now);
 const context=scope.contextBinding,binding=createPreparedTurnBinding({viewId:randomUUID(),revision:1,invalidationKey:randomUUID(),scope:{principalId:scope.principalId,assistantId:scope.assistantId,relationshipId:scope.relationshipId,conversationId:context.conversationId,sessionId:context.sessionId,endpointId:context.endpointId},conversation:'[]',sourceRevisions:{advice:advice.adviceRef!}}),selection=selectGameCampaignContext(campaign.input,campaign.boundary),game=(assert.equal(selection.status,'selected',selection.reason),prepareGameCampaignContext(selection,binding)),turn=finalizePreparedTurn({assistantId:scope.assistantId,sessionId:context.sessionId,endpointId:context.endpointId,interactionId:randomUUID(),origin:'activityStep',conversation:'[]',preparedTurnBinding:binding,preparedGameCampaignContext:game},()=>true),decision=gameDecisionInput(game,binding,requestForFinalizedTurn(turn,binding,()=>true),100,now,now+5000);
 const proposal:G.GameActionProposal={schemaVersion:'1.0.0',recordType:'gameActionProposal',scope,proposalId:randomUUID(),observationId:observation.observationId,observationRevision:1,preparedViewId:binding.viewId,preparedViewRevision:binding.revision,invalidationKey:binding.invalidationKey,buttons:['a'],durationFrames:2,maxWallMs:1000,expectedVisibleOutcome:'The visible lever may change.',uncertainty:'Scripted only, not actual play.',adviceRefs:[advice.adviceRef!],reason:'Test the attributed suggestion against the visible lever.',preconditions:[{predicateId:randomUUID(),fieldId:'test-only:visible-lever',expectedValue:'closed',sourceObservationId:observation.observationId}]};
 const data={disposition:'used' as 'used'|'rejected'|'obsolete',reason:'The recorded plan selected the suggestion; no execution is established.',proposal,admission:null as G.GameAdmission|null,receipt:null as G.GameActionReceipt|null,resultObservation:null as G.GameObservation|null,nowMs:now,freshUntilMs:now+4000,maximumObservationAgeMs:6000,maximumBytes:8192},ports:GameAdviceOutcomePorts={boundaryRevision:()=> 'test-only:outcome-epoch:1',dispositionGroundedCurrent:()=>true,receiptCurrent:()=>true,outcomeCurrent:()=>true,now:()=>now};
 const execute=()=>{data.admission={admissionId:randomUUID(),capabilityInvocationId:randomUUID(),authorityContextRef:{providerRef:'test-only:authority',contextId:randomUUID(),revision:1},dispatchReceipt:{reference:'test-only:immutable-dispatch',sha256:'c'.repeat(64),mediaType:'application/json',schemaRef:'test-only:dispatch-schema',byteLength:100},scopeDigest:'c'.repeat(64),inputDigest:'d'.repeat(64),policyRevision:1,issuedAt:new Date(now).toISOString(),expiresAt:new Date(now+5000).toISOString()};data.receipt={schemaVersion:'1.0.0',recordType:'gameActionReceipt',scope,actionId:randomUUID(),proposalId:proposal.proposalId,idempotencyKey:randomUUID(),inputDigest:data.admission.inputDigest,admissionId:data.admission.admissionId,disposition:'completed',beforeFrame:30,afterFrame:32,framesApplied:2,buttonsNeutralized:true,startedAt:new Date(now).toISOString(),completedAt:new Date(now).toISOString(),resultingObservationIds:[],recordedAt:new Date(now).toISOString(),reason:null};};
 const observe=()=>{execute();const o=structuredClone(observation);o.observationId=randomUUID();o.frameNumber=32;o.previousActionId=data.receipt!.actionId;o.screenshots.forEach(frame=>{frame.frameNumber=32;});o.visibleState=[];data.receipt!.resultingObservationIds=[o.observationId];data.resultObservation=o;data.reason='The resulting visible frame still shows the gate closed; hidden cause unknown.';};
 return {f,campaign,input:{advice,game,binding,decision,data},ports,execute,observe};
}
test('authentic prepared advice citation is planned only before a recorded started action',t=>{const f=outcomeFixture(t),v=selectGameAdviceOutcome(f.input,f.ports);assert.equal(v.state,'selected');assert.equal(v.evidenceState,'planned');assert.equal(v.entry!.epistemicKind,'inference');assert.equal(v.adviceSuccessEstablished,false);assert.equal(v.playAuthority,false);assert.equal(v.resumeAuthority,false);assert.equal(v.sendAuthority,false);assert.match(v.content!,/missing result evidence remains unknown/);});
for(const disposition of ['rejected','obsolete']as const)test('recorded advice '+disposition+' needs a separately grounded reason and cannot fabricate an action',t=>{const f=outcomeFixture(t);f.input.data.disposition=disposition;f.input.data.proposal.adviceRefs=[];f.input.data.reason='The observed menu does not support that proposed approach.';const v=selectGameAdviceOutcome(f.input,f.ports);assert.equal(v.state,'selected');assert.equal(v.evidenceState,disposition);assert.equal(v.entry!.kind,'unresolvedThread');f.ports.dispositionGroundedCurrent=()=>false;assert.equal(selectGameAdviceOutcome(f.input,f.ports).state,'unavailable');});
test('recorded admission/start without resulting evidence remains attempted outcome unknown',t=>{const f=outcomeFixture(t);f.execute();const v=selectGameAdviceOutcome(f.input,f.ports);assert.equal(v.state,'selected');assert.equal(v.evidenceState,'attemptedOutcomeUnknown');assert.equal(v.entry!.epistemicKind,'inference');assert.ok(v.entry!.sourceRefs.some(ref=>ref.startsWith('game-admission:')));assert.equal(v.adviceSuccessEstablished,false);});
test('qualified recorded action and resulting observation are attributed after scene/native lifecycle advances without reviving planning',t=>{const f=outcomeFixture(t);f.observe();f.f.unpause();f.campaign.deny();assert.equal(f.input.advice.isCurrent(),false);assert.equal(gameAdviceHistoricalSourceCurrent(f.input.advice),true);const v=selectGameAdviceOutcome(f.input,f.ports);assert.equal(v.state,'selected');assert.equal(v.evidenceState,'observedAttempt');assert.equal(v.entry!.epistemicKind,'observation');assert.equal(v.adviceSuccessEstablished,false);assert.equal(v.resumeAuthority,false);assert.ok(v.content!.includes(f.input.data.resultObservation!.observationId));});
for(const [label,change]of [
 ['copied advice',(f:ReturnType<typeof outcomeFixture>)=>f.input.advice={...f.input.advice}],['copied decision',(f:ReturnType<typeof outcomeFixture>)=>f.input.decision={...f.input.decision}],['wrong proposal',(f:ReturnType<typeof outcomeFixture>)=>f.input.data.receipt!.proposalId=randomUUID()],['wrong admission',(f:ReturnType<typeof outcomeFixture>)=>f.input.data.receipt!.admissionId=randomUUID()],['wrong digest',(f:ReturnType<typeof outcomeFixture>)=>f.input.data.receipt!.inputDigest='e'.repeat(64)],['queued only',(f:ReturnType<typeof outcomeFixture>)=>{f.input.data.receipt!.disposition='admitted';f.input.data.receipt!.startedAt=null;}],['wrong timeline',(f:ReturnType<typeof outcomeFixture>)=>f.input.data.resultObservation!.scope={...f.input.data.resultObservation!.scope,timelineId:randomUUID()}],['wrong pins',(f:ReturnType<typeof outcomeFixture>)=>f.input.data.resultObservation!.pinsDigest='f'.repeat(64)],['wrong result id',(f:ReturnType<typeof outcomeFixture>)=>f.input.data.receipt!.resultingObservationIds=[]],['wrong action',(f:ReturnType<typeof outcomeFixture>)=>f.input.data.resultObservation!.previousActionId=randomUUID()],['future result',(f:ReturnType<typeof outcomeFixture>)=>f.input.data.resultObservation!.receivedAt=new Date(f.input.data.nowMs+1).toISOString()],['unconfirmed controls',(f:ReturnType<typeof outcomeFixture>)=>f.input.data.receipt!.buttonsNeutralized=false],['frame mismatch',(f:ReturnType<typeof outcomeFixture>)=>f.input.data.receipt!.afterFrame=35],['bytes',(f:ReturnType<typeof outcomeFixture>)=>f.input.data.maximumBytes=1]
]as const)test('advice outcome rejects '+label,t=>{const f=outcomeFixture(t);f.observe();change(f);assert.equal(selectGameAdviceOutcome(f.input,f.ports).state,'unavailable');});
for(const port of ['dispositionGroundedCurrent','receiptCurrent','outcomeCurrent']as const)test('advice outcome requires independent '+port,t=>{const f=outcomeFixture(t);f.observe();f.ports[port]=()=>false;assert.equal(selectGameAdviceOutcome(f.input,f.ports).state,'unavailable');});
test('Human forgetting during observed-outcome qualification fences preparation before journal source return',t=>{const f=outcomeFixture(t);f.observe();f.ports.outcomeCurrent=()=>{f.f.memories.forget(f.f.m.assistantId,f.f.m.id,f.f.e.scope.principalId);return true;};assert.equal(selectGameAdviceOutcome(f.input,f.ports).state,'unavailable');});
test('held outcome source retires on receipt epoch withdrawal and cannot replay an action',t=>{const f=outcomeFixture(t);f.observe();let current=true;f.ports.boundaryRevision=()=>current?'test-only:epoch:1':'test-only:epoch:2';const v=selectGameAdviceOutcome(f.input,f.ports);assert.equal(v.state,'selected');current=false;assert.equal(v.isCurrent(),false);current=true;assert.equal(v.isCurrent(),false);assert.equal(v.playAuthority,false);assert.equal(f.f.db.connection.prepare('SELECT count(*) AS n FROM game_start_claims').get()!.n,0);});

test('qualified observed advice attempt persists in the existing journal and Human forgetting erases dependent prose',t=>{
 const f=outcomeFixture(t);f.observe();f.f.unpause();f.campaign.deny();const outcome=selectGameAdviceOutcome(f.input,f.ports);assert.equal(outcome.state,'selected');const journal=f.campaign.input.journal;journal.entries.push(structuredClone(outcome.entry!));journal.summary='An attributed suggestion was tried; the visible gate remained closed.';journal.summaryEntryIds.push(outcome.entry!.entryId);const owner={principalId:f.f.e.scope.principalId,assistantId:f.f.e.scope.assistantId,relationshipId:f.f.e.scope.relationshipId},repo=new CampaignJournalRepository(f.f.db,{maxJournals:4,maxEntryIdentities:16,maxSourceFences:32,maxJournalBytes:8192,scopeCurrent:()=>true,quarantined:()=>false,policyFor:()=>({enabled:true,revision:1,retentionMs:30000,retentionPolicyRef:journal.retentionPolicyRef}),allowCreate:()=>true,sourceCurrent:(_owner,entry)=>entry.entryId===outcome.entry!.entryId?outcome.isCurrent():gameAdviceHistoricalSourceCurrent(f.input.advice),journalCurrent:()=>outcome.isCurrent()&&gameAdviceHistoricalSourceCurrent(f.input.advice),now:()=>f.input.data.nowMs});repo.put(owner,journal,0);const read=repo.get(owner,journal.journalId)!;const recorded=read.entries.find(entry=>entry.entryId===outcome.entry!.entryId)!;assert.equal(recorded.epistemicKind,'observation');assert.ok(recorded.sourceRefs.includes(f.input.advice.adviceRef!));assert.equal(outcome.adviceSuccessEstablished,false);f.f.memories.forget(f.f.m.assistantId,f.f.m.id,owner.principalId);assert.equal(outcome.isCurrent(),false);assert.equal(repo.get(owner,journal.journalId),null);assert.equal(f.f.db.connection.prepare('SELECT count(*) AS n FROM campaign_journal_entries WHERE payload_json IS NOT NULL').get()!.n,0);assert.equal(f.f.db.connection.prepare('SELECT header_json FROM campaign_journals').get()!.header_json,null);
});


test('only the exact minted authenticated advice source exposes inert episode retention references',t=>{const f=fixture(t),advice=selectGameAdvice(f.input,f.ports),source=gameAdviceEpisodeSource(advice);assert.ok(source);assert.equal(source.adviceRef,advice.adviceRef);assert.equal(source.memoryId,f.m.id);assert.equal(source.sourceSessionRef,f.input.reply.sourceSessionRef);assert.doesNotMatch(JSON.stringify(source),/quotedAdvice|recipient|Try the visible/);assert.equal(gameAdviceEpisodeSource({...advice}),null);f.unauthenticate();assert.equal(gameAdviceEpisodeSource(advice),null);});


test('authentic selected reply and recorded observed attempt reach durable unverified advice-bearing memory; Human forgetting scrubs it',t=>{
 const f=outcomeFixture(t);f.observe();const outcome=selectGameAdviceOutcome(f.input,f.ports);assert.equal(outcome.evidenceState,'observedAttempt');assert.equal(outcome.adviceSuccessEstablished,false);const source=gameAdviceEpisodeSource(f.input.advice)!;assert.ok(source);const now=f.input.data.nowMs,receipt=f.input.data.receipt!,observation=f.input.data.resultObservation!,episode=fixtureEpisode(now);episode.scope=structuredClone(f.input.decision.scope);episode.pinsDigest=observation.pinsDigest;episode.frameRange={from:receipt.beforeFrame!,to:receipt.afterFrame!};episode.occurredFrom=receipt.startedAt!;episode.occurredTo=receipt.completedAt!;episode.recordedAt=new Date(now).toISOString();episode.expiresAt=new Date(now+20000).toISOString();episode.adviceRefs=[source.adviceRef];episode.sourceAdmissionIds=[receipt.admissionId];episode.sourceActionIds=[receipt.actionId];episode.sourceObservationIds=[observation.observationId];episode.summary='A recorded action tested attributed advice; the visible gate remained closed, with its hidden cause unknown.';
 const owner={principalId:episode.scope.principalId,assistantId:episode.scope.assistantId,relationshipId:episode.scope.relationshipId},records={observations:[observation],actions:[receipt],advice:[source]},repo=new GameExperienceRepository(f.f.db,{maximumFences:4,scopeCurrent:()=>true,quarantined:()=>false,retentionFor:()=>({retentionMs:86400000,retentionPolicyRef:episode.retentionPolicyRef,maximumEpisodes:4,maximumBytes:8192}),sourceRecordsFor:()=>records,meaningfulGroundingCurrent:()=>true,publicationCurrent:()=>true,retainedSourceCurrent:()=>true,adviceSourceCurrent:(_episode,s)=>gameAdviceHistoricalSourceCurrent(f.input.advice)&&JSON.stringify(gameAdviceEpisodeSource(f.input.advice))===JSON.stringify(s),now:()=>now});
 assert.equal(repo.admit(episode),true);const memories=new MemoryRepository(f.f.db,repo.memorySources(4)),saved=memories.saveGameProjection(projection(episode,now));assert.ok(memories.activateGameCandidate(owner.assistantId,saved.id,owner.principalId,1));assert.equal(memories.get(owner.assistantId,saved.id)!.lifecycle.factuality,'unverified');assert.equal(memories.get(owner.assistantId,saved.id)!.lifecycle.lastReinforcedAt,null);assert.ok(memories.contextRecords(owner.assistantId,owner.principalId).some(m=>m.id===saved.id));
 f.f.memories.forget(owner.assistantId,f.f.m.id,owner.principalId);assert.equal(repo.get(owner,episode.episodeId),null);assert.equal(f.f.db.connection.prepare('SELECT content FROM memories WHERE id=?').get(saved.id)!.content,'');assert.equal(f.f.db.connection.prepare('SELECT source_json FROM game_episode_advice_sources WHERE episode_id=?').get(episode.episodeId)!.source_json,null);assert.equal(outcome.isCurrent(),false);
});
