import assert from 'node:assert/strict';
import test from 'node:test';
import {randomUUID} from 'node:crypto';
import type * as G from '@lifestream/contracts/game-activity';
import {selectGameCampaignContext,prepareGameCampaignContext,gameDecisionInput,selectGameDispatchValidation} from '@lifestream/runtime/activity/game-journal';
import {createPreparedTurnBinding,finalizePreparedTurn,requestForFinalizedTurn} from '@lifestream/runtime/inference/prompt';
import {Database} from '../../../packages/storage-sqlite/src/database.ts';
import {ActivityCheckpointRepository,type ActivityMetadataOptions} from '../../../packages/storage-sqlite/src/game-activity.ts';
import {guardGameActivityAdapter} from '../../../packages/providers-bizhawk/src/provider.ts';
import {gameCampaignFixture} from '../../../packages/runtime/test/fixtures/game-campaign.ts';
import {scriptedGameBounds} from '../../../packages/runtime/test/fixtures/game-policy.ts';
import {runCheckpointedGameController,type CheckpointedGameControllerPorts} from '../src/runtime/game-activity.ts';
function fixture(){
 const f=gameCampaignFixture(),scope=f.input.expectedScope,o=f.input.observation;let now=f.input.nowMs,current=true,native=true,claim=true,calls=0,claims=0;
 o.visibleState=[{fieldId:'scripted:menu',value:'open',visibility:'visibleNow',firstObservedRef:o.observationId,lastObservedRef:o.observationId,timelineId:scope.timelineId,observedAt:o.receivedAt,freshUntil:new Date(f.input.freshUntilMs).toISOString(),decoderRevision:'1.0.0',manifestDigest:f.input.pinsDigest,limitations:['No native game.']}];
 const owner={assistantId:scope.assistantId,principalId:scope.principalId,relationshipId:scope.relationshipId},c=scope.contextBinding;
 const binding=createPreparedTurnBinding({viewId:randomUUID(),revision:1,invalidationKey:randomUUID(),scope:{...owner,conversationId:c.conversationId,sessionId:c.sessionId,endpointId:c.endpointId},conversation:'[]',sourceRevisions:{journal:String(f.input.journal.revision)}}),game=prepareGameCampaignContext(selectGameCampaignContext(f.input,f.boundary),binding),turn=finalizePreparedTurn({assistantId:scope.assistantId,sessionId:c.sessionId,endpointId:c.endpointId,interactionId:randomUUID(),origin:'activityStep',conversation:'[]',preparedTurnBinding:binding,preparedGameCampaignContext:game,deadlineAt:new Date(now+10000).toISOString()},()=>true),decision=gameDecisionInput(game,binding,requestForFinalizedTurn(turn,binding,()=>true),100,now,f.input.freshUntilMs);
 const proposal:G.GameActionProposal={schemaVersion:'1.0.0',recordType:'gameActionProposal',scope:structuredClone(scope),proposalId:randomUUID(),observationId:o.observationId,observationRevision:1,preparedViewId:binding.viewId,preparedViewRevision:binding.revision,invalidationKey:binding.invalidationKey,buttons:['a'],durationFrames:2,maxWallMs:100,expectedVisibleOutcome:'Scripted menu might change.',uncertainty:'No native source.',adviceRefs:[],reason:'Scripted host join.',preconditions:[{predicateId:randomUUID(),fieldId:'scripted:menu',expectedValue:'open',sourceObservationId:o.observationId}]};
 const fresh=structuredClone(o);fresh.observationId=randomUUID();fresh.capturedAt=new Date(now).toISOString();fresh.receivedAt=fresh.capturedAt;fresh.screenshots=fresh.screenshots.map(s=>({...s,screenshotId:randomUUID(),capturedAt:fresh.capturedAt}));fresh.visibleState=fresh.visibleState.map(v=>({...v,lastObservedRef:fresh.observationId,observedAt:fresh.receivedAt}));
 const dispatch=selectGameDispatchValidation(game,binding,decision,proposal,fresh,{maxPlanningAgeMs:30000,maxPlanningFrameDelta:120,maximumObservationAgeMs:10000,validatorRef:'scripted:dispatch',observationCurrent:()=>current,now:()=>now});assert.ok(dispatch.validation);
 const request:G.GameActionRequest={schemaVersion:'1.0.0',operation:'GameActivityAdapter.applyController',requestId:randomUUID(),correlationId:randomUUID(),deadlineAt:new Date(now+10000).toISOString(),cancellationId:randomUUID(),executionMode:'simulation',scope:structuredClone(scope),idempotencyKey:randomUUID(),payload:{actionId:randomUUID(),proposal,admission:{admissionId:randomUUID(),capabilityInvocationId:randomUUID(),authorityContextRef:{providerRef:'scripted:authority',contextId:randomUUID(),revision:1},dispatchReceipt:{reference:'scripted:receipt',sha256:'a'.repeat(64),mediaType:'application/json',schemaRef:'scripted:receipt',byteLength:1},scopeDigest:'a'.repeat(64),inputDigest:'a'.repeat(64),policyRevision:1,issuedAt:new Date(now).toISOString(),expiresAt:new Date(now+10000).toISOString()},inputOwnerLeaseId:randomUUID(),buttonVector:{up:false,down:false,left:false,right:false,a:true,b:false,x:false,y:false,l:false,r:false,start:false,select:false},protectedMenuOperation:'none',expectedFrameNumber:10,expectedPinsDigest:f.input.pinsDigest,dispatchValidation:structuredClone(dispatch.validation!)}};
 const policy={enabled:true,revision:1,retentionMs:3600000,bounds:structuredClone(scriptedGameBounds)},options:ActivityMetadataOptions={maxRuns:4,maxReservations:8,maxControllerReservations:8,maxCheckpointBytes:32768,scopeCurrent:()=>current,quarantined:()=>false,policyFor:()=>policy,allowCreate:()=>true,checkpointCurrent:()=>current,transitionCurrent:()=>true,planningCurrent:()=>current,usageCurrent:()=>current,controllerCurrent:()=>current,controllerUsageCurrent:()=>current&&native,now:()=>now};
 const db=new Database({path:':memory:'});db.migrate();const repository=new ActivityCheckpointRepository(db,options),checkpoint:G.ActivityCheckpoint={schemaVersion:'1.0.0',recordType:'activityCheckpoint',scope,checkpointId:randomUUID(),revision:1,stateRevision:1,policyRevision:1,pinsDigest:f.input.pinsDigest,goalSummary:'Unfinished scripted goal.',recentObservationIds:[o.observationId],adviceRefs:[],lastObservationId:o.observationId,lastActionReceipt:null,saveArtifact:null,budgetUsed:{wallMs:0,frames:0,actions:0,starts:1,equivalentFailures:0,modelCalls:0,inputTokens:0,outputTokens:0,retries:0,checkpointBytes:0,memoryEpisodes:0},recordedAt:new Date(now).toISOString(),resumeDisposition:'requiresReconciliation',campaignJournalRef:{campaignId:f.input.journal.campaignId,journalId:f.input.journal.journalId,revision:1,accessRevision:1}};repository.put(owner,checkpoint,0);
 const rawAdapter={observe:async()=>{throw Error('No observation effect');},releaseControls:async()=>{throw Error('No release effect');},controlSave:async()=>{throw Error('No save effect');},applyController:async(r:G.GameActionRequest):Promise<G.GameActionResult>=>{calls++;now=Date.now();f.clock(now);const time=new Date(now).toISOString();return {schemaVersion:'1.0.0',operation:r.operation,requestId:r.requestId,correlationId:r.correlationId,providerRef:'scripted:guarded',completedAt:time,outcome:{status:'succeeded',error:null,payload:{schemaVersion:'1.0.0',recordType:'gameActionReceipt',scope:structuredClone(r.scope),actionId:r.payload.actionId,proposalId:r.payload.proposal.proposalId,idempotencyKey:r.idempotencyKey,inputDigest:r.payload.admission.inputDigest,admissionId:r.payload.admission.admissionId,disposition:'completed',beforeFrame:10,afterFrame:12,framesApplied:2,buttonsNeutralized:true,startedAt:time,completedAt:time,resultingObservationIds:[],recordedAt:time,reason:null}}};}};
 const adapter=guardGameActivityAdapter(rawAdapter,{providerRef:'scripted:guarded',maxDurationMs:10000,sourceAvailable:()=>current,acceptAction:()=>native,claimEffect:async()=>{claims++;return claim;}}),controller=new AbortController();
 const ports:CheckpointedGameControllerPorts={repository,adapter,signal:controller.signal,current:()=>current,usageFor:(_r,result)=>result.outcome.payload?{receipt:result.outcome.payload,wallMs:10,completionRef:'scripted:qualified-monotonic-usage'}:null},input={game,binding,decision,dispatch,request};
 return {f,db,options,repository,owner,checkpoint,ports,input,rawAdapter,controller,policy,calls:()=>calls,claims:()=>claims,withdraw:()=>current=false,native:(v:boolean)=>native=v,claim:(v:boolean)=>claim=v};
}
test('actual prepared dispatch joins SQLite controller budget and independently guarded result without a new authority owner',async t=>{const f=fixture();t.after(()=>f.db.close());const result=await runCheckpointedGameController(f.input,f.ports);assert.equal(result.state,'settled');assert.equal(result.reservationHeld,false);assert.equal(result.adapterInvoked,true);assert.equal(result.playAuthority,false);assert.equal(f.calls(),1);assert.equal(f.claims(),1);assert.equal(f.repository.get(f.owner,f.input.request.scope.runId)!.used.frames,2);assert.equal(f.repository.get(f.owner,f.input.request.scope.runId)!.used.wallMs,10);assert.equal((await runCheckpointedGameController(f.input,f.ports)).state,'suppressed');assert.equal(f.calls(),1);});
for(const mode of ['copiedSelection','copiedView','copiedBinding','copiedDecision','alteredProposal','alteredValidation','foreignScope','aborted','sourceDenied','quotaDisabled']as const)test('controller host refuses '+mode+' before adapter entry',async t=>{const f=fixture();t.after(()=>f.db.close());const input={...f.input};if(mode==='copiedSelection')input.dispatch={...input.dispatch,isCurrent:()=>true};if(mode==='copiedView')input.game={...input.game};if(mode==='copiedBinding')input.binding={...input.binding};if(mode==='copiedDecision')input.decision={...input.decision};if(mode==='alteredProposal')input.request.payload.proposal.reason='Changed original proposal.';if(mode==='alteredValidation')input.request.payload.dispatchValidation.validatorRef='other:validator';if(mode==='foreignScope')input.request.scope.timelineId=randomUUID();if(mode==='aborted')f.controller.abort();if(mode==='sourceDenied')f.withdraw();if(mode==='quotaDisabled')f.ports.repository=new ActivityCheckpointRepository(f.db,{...f.options,maxControllerReservations:undefined});const result=await runCheckpointedGameController(input,f.ports);assert.equal(result.state,'suppressed');assert.equal(result.reservationHeld,false);assert.equal(f.calls(),0);assert.equal(f.claims(),0);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM activity_controller_reservations').get()!.n,0);});
for(const mode of ['deniedAdmission','deniedNative','missingUsage','wrongUsage','usageDenied','sourceAfterReserve','sourceAfterResult','changedPort','unknownOutcome']as const)test('controller host '+mode+' preserves held budget for reconciliation',async t=>{const f=fixture();t.after(()=>f.db.close());if(mode==='deniedAdmission')f.claim(false);if(mode==='deniedNative')f.native(false);if(mode==='missingUsage')f.ports.usageFor=()=>null;if(mode==='wrongUsage')f.ports.usageFor=(_r,result)=>({receipt:{...result.outcome.payload!,actionId:randomUUID()},wallMs:10,completionRef:'scripted:wrong-usage'});if(mode==='usageDenied')f.options.controllerUsageCurrent=()=>false;if(mode==='sourceAfterReserve'){let calls=0;f.options.controllerCurrent=()=>{if(++calls===2)f.withdraw();return true;};}if(['sourceAfterResult','changedPort','unknownOutcome'].includes(mode)){const original=f.rawAdapter.applyController;f.rawAdapter.applyController=async r=>{const result=await original(r);if(mode==='sourceAfterResult')f.withdraw();if(mode==='changedPort')f.ports.usageFor=()=>null;if(mode==='unknownOutcome')Object.assign(result.outcome.payload!,{disposition:'outcomeUnknown',beforeFrame:null,afterFrame:null,framesApplied:null,startedAt:null,completedAt:null,buttonsNeutralized:false});return result;};}const result=await runCheckpointedGameController(f.input,f.ports);assert.equal(result.state,mode==='sourceAfterReserve'?'suppressed':'requiresReconciliation');assert.equal(result.reservationHeld,mode!=='sourceAfterReserve');if(mode!=='sourceAfterReserve'){assert.equal(f.repository.get(f.owner,f.input.request.scope.runId)?.used.actions??0,0);assert.equal(f.db.connection.prepare('SELECT state FROM activity_controller_reservations').get()!.state,'reserved');}assert.equal((await runCheckpointedGameController(f.input,f.ports)).state,'suppressed');});

test('late owner loss after reservation withholds adapter entry while retaining durable held resources',async t=>{
 const f=fixture();t.after(()=>f.db.close());let checks=0;f.ports.current=()=>{if(++checks===2)f.withdraw();return checks<2;};const r=await runCheckpointedGameController(f.input,f.ports);assert.equal(r.state,'requiresReconciliation');assert.equal(r.reservationHeld,true);assert.equal(r.adapterInvoked,false);assert.equal(f.calls(),0);assert.equal(f.claims(),0);assert.equal(f.db.connection.prepare('SELECT state FROM activity_controller_reservations').get()!.state,'reserved');
});
test('abort fences an outstanding guarded action, retains resources and ignores its late native result',async t=>{
 const f=fixture();t.after(()=>f.db.close());let enter!:()=>void,release!:()=>void;const started=new Promise<void>(r=>enter=r),held=new Promise<void>(r=>release=r),original=f.rawAdapter.applyController;t.after(()=>release());f.rawAdapter.applyController=async r=>{enter();await held;return original(r);};const pending=runCheckpointedGameController(f.input,f.ports);await started;f.controller.abort();const result=await pending;assert.equal(result.state,'requiresReconciliation');assert.equal(result.reservationHeld,true);assert.equal(result.adapterInvoked,true);assert.equal(result.result,null);release();await new Promise(r=>setImmediate(r));assert.equal(f.db.connection.prepare('SELECT state FROM activity_controller_reservations').get()!.state,'reserved');assert.equal(JSON.parse(f.db.connection.prepare('SELECT used_json FROM activity_checkpoints').get()!.used_json as string).actions,0);assert.equal((await runCheckpointedGameController(f.input,f.ports)).state,'suppressed');
});
test('source loss after committed usage preserves accounting and withholds the result from current planning',async t=>{
 const f=fixture();t.after(()=>f.db.close());f.ports.current=()=>{const usage=JSON.parse(f.db.connection.prepare('SELECT used_json FROM activity_checkpoints').get()!.used_json as string);if(usage.actions===1){f.withdraw();return false;}return true;};const result=await runCheckpointedGameController(f.input,f.ports);assert.equal(result.state,'requiresReconciliation');assert.equal(result.reservationHeld,false);assert.equal(result.result,null);assert.equal(f.db.connection.prepare('SELECT state FROM activity_controller_reservations').get()!.state,'settled');assert.equal(JSON.parse(f.db.connection.prepare('SELECT used_json FROM activity_checkpoints').get()!.used_json as string).actions,1);assert.equal(f.calls(),1);assert.equal((await runCheckpointedGameController(f.input,f.ports)).state,'suppressed');
});
test('reentrant host qualification cannot admit a second invocation of the same selected dispatch',async t=>{
 const f=fixture();t.after(()=>f.db.close());const nested:Array<ReturnType<typeof runCheckpointedGameController>>=[];f.ports.current=()=>{nested.push(runCheckpointedGameController(f.input,f.ports));return true;};assert.equal((await runCheckpointedGameController(f.input,f.ports)).state,'settled');for(const result of await Promise.all(nested))assert.equal(result.state,'suppressed');assert.equal(f.calls(),1);assert.equal(f.claims(),1);
});
