import assert from 'node:assert/strict';
import test from 'node:test';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import type * as G from '@lifestream/contracts/game-activity';
import {selectGameCampaignContext,prepareGameCampaignContext} from '@lifestream/runtime/activity/game-journal';
import {createPreparedTurnBinding,finalizePreparedTurn,requestForFinalizedTurn} from '@lifestream/runtime/inference/prompt';
import type {InferenceProvider,InferenceRequest} from '@lifestream/runtime/inference';
import type {GamePlanningResult} from '@lifestream/runtime/activity/coordinator';
import {Database} from '../../../packages/storage-sqlite/src/database.ts';
import {ActivityCheckpointRepository,type ActivityMetadataOptions} from '../../../packages/storage-sqlite/src/game-activity.ts';
import {gameCampaignFixture} from '../../../packages/runtime/test/fixtures/game-campaign.ts';
import {scriptedGameBounds} from '../../../packages/runtime/test/fixtures/game-policy.ts';
import {DiscoveryAdministration} from '../src/admin/understanding.ts';
import {runCheckpointedGamePlanning,type CheckpointedGamePlanningPorts} from '../src/runtime/game-activity.ts';
function fixture(path=':memory:',modelCallBudget=2){
 const f=gameCampaignFixture(),scope=f.input.expectedScope,owner={assistantId:scope.assistantId,principalId:scope.principalId,relationshipId:scope.relationshipId};let authorized=true,quarantined=false,sourceCurrent=true;
 f.input.observation.visibleState.push({fieldId:'scripted-visible-menu',value:'open',visibility:'visibleNow',firstObservedRef:f.input.observation.observationId,lastObservedRef:f.input.observation.observationId,timelineId:scope.timelineId,observedAt:f.input.observation.receivedAt,freshUntil:new Date(f.input.freshUntilMs).toISOString(),decoderRevision:'1.0.0',manifestDigest:f.input.pinsDigest,limitations:['Scripted visible field; no actual game.']});
 const context=scope.contextBinding,binding=createPreparedTurnBinding({viewId:randomUUID(),revision:1,invalidationKey:randomUUID(),scope:{...owner,conversationId:context.conversationId,sessionId:context.sessionId,endpointId:context.endpointId},conversation:'[]',sourceRevisions:{conversation:'scripted:1'}}),game=prepareGameCampaignContext(selectGameCampaignContext(f.input,f.boundary),binding),turn=finalizePreparedTurn({assistantId:scope.assistantId,sessionId:context.sessionId,endpointId:context.endpointId,interactionId:randomUUID(),conversation:'[]',origin:'activityStep',preparedTurnBinding:binding,preparedGameCampaignContext:game,maximumOutputTokens:1024},()=>true);
 const policy={enabled:true,revision:1,retentionMs:3600000,bounds:{...structuredClone(scriptedGameBounds),modelCallBudget}},options:ActivityMetadataOptions={maxRuns:4,maxReservations:8,maxCheckpointBytes:32768,scopeCurrent:()=>authorized,quarantined:()=>quarantined,policyFor:()=>policy,allowCreate:()=>true,checkpointCurrent:()=>sourceCurrent,transitionCurrent:()=>true,planningCurrent:()=>sourceCurrent,usageCurrent:(_c,_r,u)=>sourceCurrent&&u.completionRef==='scripted-qualified-provider-terminal'};
 const checkpoint:G.ActivityCheckpoint={schemaVersion:'1.0.0',recordType:'activityCheckpoint',scope,checkpointId:randomUUID(),revision:1,stateRevision:1,policyRevision:1,pinsDigest:f.input.pinsDigest,goalSummary:'Scripted unfinished campaign goal; no actual game progress.',recentObservationIds:[f.input.observation.observationId],adviceRefs:[],lastObservationId:f.input.observation.observationId,lastActionReceipt:null,saveArtifact:null,budgetUsed:{wallMs:0,frames:0,actions:0,starts:1,equivalentFailures:0,modelCalls:0,inputTokens:0,outputTokens:0,retries:0,checkpointBytes:0,memoryEpisodes:0},recordedAt:new Date(f.input.nowMs).toISOString(),resumeDisposition:'requiresReconciliation',campaignJournalRef:{campaignId:f.input.journal.campaignId,journalId:f.input.journal.journalId,revision:1,accessRevision:1}};
 let db=new Database({path});db.migrate();let repository=new ActivityCheckpointRepository(db,options);repository.put(owner,checkpoint,0);
 const adminFactory=()=>new DiscoveryAdministration(db,{snapshot:()=>({boundary:'scripted',configuration:undefined}),evidenceAllowed:()=>false,sourceAllowed:()=>false,forget:()=> 'missing',changed:()=>{}});let admin=adminFactory();let calls=0;const requests:InferenceRequest[]=[],published:GamePlanningResult[]=[];
 const provider:InferenceProvider={tokenize:async value=>({count:typeof value==='string'?50:100,identity:'scripted-tokenizer:1'}),async *generate(request){calls++;requests.push(request);yield {kind:'text',text:'null'};yield {kind:'done'};}};
 const ports:CheckpointedGamePlanningPorts={repository,background:admin,current:()=>authorized,terminalRef:()=> 'scripted-qualified-provider-terminal',publishDecision:value=>{published.push(value);return true;},providerRevision:'scripted-provider:1',tokenizerIdentity:'scripted-tokenizer:1',providerPreemptionBoundMs:1,providerSlotReleaseBoundMs:1};
 const input={scope,turn,binding,game,provider,bounds:{maximumInputTokens:8192,maximumOutputTokens:1024,maximumOutputBytes:32768,maximumChunks:100,deadlineMs:3000}};
 return {...f,sourceInput:f.input,input,scope,owner,checkpoint,policy,options,ports,provider,requests,published,get db(){return db;},get repository(){return repository;},get admin(){return admin;},calls:()=>calls,authority:(v:boolean)=>{authorized=v;},source:(v:boolean)=>{sourceCurrent=v;},quarantine:(v:boolean)=>{quarantined=v;},close:()=>{admin.close();db.close();},reopen:()=>{admin.close();db.close();db=new Database({path});db.migrate();repository=new ActivityCheckpointRepository(db,options);admin=adminFactory();ports.repository=repository;ports.background=admin;}};
}
test('existing runtime P2 coordinator uses the exact canonical nine-section request and durable once-only settlement for one inert decision',async t=>{
 const f=fixture();t.after(()=>f.close());const request=requestForFinalizedTurn(f.input.turn,f.input.binding,()=>true),result=await runCheckpointedGamePlanning(f.input,f.ports);assert.equal(result.state,'published');assert.equal(f.calls(),1);assert.equal(f.requests[0],request);assert.equal(request.sections.length,9);assert.equal(request.sections[8]!.content,'');assert.equal(f.published[0]!.proposal,null);const state=f.repository.get(f.owner,f.scope.runId)!;assert.equal(state.used.modelCalls,1);assert.equal(state.used.inputTokens,100);assert.equal(state.used.outputTokens,50);assert.equal(state.reserved.modelCalls,0);assert.equal(state.checkpoint.budgetUsed.modelCalls,0);assert.equal(state.continuationAuthority,false);assert.equal((await runCheckpointedGamePlanning(f.input,f.ports)).state,'suppressed');assert.equal(f.calls(),1);
});
test('actual SQLite reopen preserves settled view identity and charges but metadata cannot enable a restored run',async t=>{
 const root=mkdtempSync(join(tmpdir(),'game-planning-')),f=fixture(join(root,'state.sqlite'));t.after(()=>{f.close();rmSync(root,{recursive:true,force:true});});assert.equal((await runCheckpointedGamePlanning(f.input,f.ports)).state,'published');f.reopen();assert.equal(f.repository.get(f.owner,f.scope.runId)!.used.modelCalls,1);assert.equal((await runCheckpointedGamePlanning(f.input,f.ports)).state,'suppressed');assert.equal(f.calls(),1);f.ports.current=()=>false;assert.equal((await runCheckpointedGamePlanning(f.input,f.ports)).reason,'currentGameRunUnavailable');assert.equal(f.calls(),1);
});
test('foreign game/checkpoint scope, pins or campaign revision cannot reserve a different ledger or reach inference',async t=>{
 for(const mode of ['scope','context','journal','access','pins','copy'])await t.test(mode,async()=>{const f=fixture();try{let input=f.input;if(mode==='scope')input={...input,scope:{...input.scope,timelineId:randomUUID()}};if(mode==='context')input={...input,scope:{...input.scope,contextBinding:{...input.scope.contextBinding,sessionId:randomUUID()}}};if(mode==='copy')input={...input,game:{...input.game}};if(['journal','access','pins'].includes(mode)){const record=f.repository.get(f.owner,f.scope.runId)!.checkpoint;record.revision++;record.stateRevision++;if(mode==='journal')record.campaignJournalRef.revision++;if(mode==='access')record.campaignJournalRef.accessRevision++;if(mode==='pins')record.pinsDigest='b'.repeat(64);f.repository.put(f.owner,record,1);}assert.equal((await runCheckpointedGamePlanning(input,f.ports)).state,'suppressed');assert.equal(f.calls(),0);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM activity_planning_reservations').get()!.n,0);}finally{f.close();}});
});
test('missing actual current lifecycle/authority, restored quarantine, policy or source refuses planning without creating capacity',async t=>{
 for(const mode of ['lifecycle','authority','quarantine','policy','source','preparedSource','closed'])await t.test(mode,async()=>{const f=fixture();try{if(mode==='lifecycle')f.ports.current=()=>false;if(mode==='authority')f.authority(false);if(mode==='quarantine')f.quarantine(true);if(mode==='policy')f.policy.enabled=false;if(mode==='source')f.source(false);if(mode==='preparedSource')f.deny();if(mode==='closed')f.admin.close();assert.equal((await runCheckpointedGamePlanning(f.input,f.ports)).state,'suppressed');assert.equal(f.calls(),0);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM activity_planning_reservations').get()!.n,0);}finally{f.close();}});
});
test('unqualified/missing terminal or failed publication keeps truthful actual/held accounting without fabricating a game attempt',async t=>{
 for(const mode of ['missingTerminal','unqualifiedTerminal','failedPublication','missingDone','malformedOutput'])await t.test(mode,async()=>{const f=fixture();try{if(mode==='missingTerminal')f.ports.terminalRef=()=>null;if(mode==='unqualifiedTerminal')f.ports.terminalRef=()=> 'unqualified';if(mode==='failedPublication')f.ports.publishDecision=()=>false;if(mode==='missingDone')f.provider.generate=async function*(){yield {kind:'text',text:'null'};};if(mode==='malformedOutput')f.provider.generate=async function*(){yield {kind:'text',text:'not-json'};yield {kind:'done'};};const result=await runCheckpointedGamePlanning(f.input,f.ports);assert.notEqual(result.state,'published');assert.equal(f.published.length,0);const state=f.repository.get(f.owner,f.scope.runId)!;assert.equal(state.used.modelCalls,mode==='failedPublication'?1:0);assert.equal(state.reserved.modelCalls,mode==='failedPublication'?0:1);assert.equal((await runCheckpointedGamePlanning(f.input,f.ports)).state,'suppressed');}finally{f.close();}});
});
test('foreground preemption and actual runtime closure cancel suspended planning through the same coordinator; no late settlement/publication or fan-out',async t=>{
 for(const mode of ['foreground','close'])await t.test(mode,async()=>{const f=fixture();try{let resolve!:()=>void,entered!:()=>void,signal:AbortSignal|undefined;const gate=new Promise<void>(r=>{resolve=r;}),ready=new Promise<void>(r=>{entered=r;});f.provider.generate=async function*(request,context){signal=context?.signal;entered();await gate;yield {kind:'text',text:'null'};yield {kind:'done'};};const running=runCheckpointedGamePlanning(f.input,f.ports);await ready;const release=mode==='foreground'?f.admin.foregroundStarted():(f.admin.close(),()=>{});assert.equal(signal?.aborted,true);assert.equal(f.admin.backgroundIdle(),false);assert.equal((await runCheckpointedGamePlanning(f.input,f.ports)).state,'suppressed');resolve();assert.equal((await running).state,'cancelled');release();assert.equal(f.published.length,0);const state=f.repository.get(f.owner,f.scope.runId)!;assert.equal(state.used.modelCalls,0);assert.equal(state.reserved.modelCalls,1);if(mode==='close')assert.equal((await runCheckpointedGamePlanning(f.input,f.ports)).reason,'runtimeClosed');}finally{f.close();}});
});
test('source/provider/priority withdrawal after tokenizer await fences inference and leaves reserved capacity held',async t=>{
 for(const mode of ['source','provider','priority','owner'])await t.test(mode,async()=>{const f=fixture();try{f.provider.tokenize=async()=>{if(mode==='source')f.deny();if(mode==='provider')f.ports.providerRevision='replacement';if(mode==='priority')f.ports.providerSlotReleaseBoundMs=1000;if(mode==='owner')f.authority(false);return {count:100,identity:'scripted-tokenizer:1'};};assert.equal((await runCheckpointedGamePlanning(f.input,f.ports)).state,'cancelled');assert.equal(f.calls(),0);assert.equal(f.published.length,0);const row=f.db.connection.prepare('SELECT state FROM activity_planning_reservations').get()!;assert.equal(row.state,'reserved');}finally{f.close();}});
});
test('shutdown accounting keeps a running key tracked when a duplicate background call settles first',async t=>{
 const f=fixture();t.after(()=>f.close());let resolve!:()=>void,entered!:()=>void;const gate=new Promise<void>(r=>{resolve=r;}),ready=new Promise<void>(r=>{entered=r;});f.provider.generate=async function*(){entered();await gate;yield {kind:'text',text:'null'};yield {kind:'done'};};const active=runCheckpointedGamePlanning(f.input,f.ports);await ready;assert.equal((await runCheckpointedGamePlanning(f.input,f.ports)).state,'suppressed');f.admin.close();resolve();assert.equal((await active).state,'cancelled');assert.equal(f.published.length,0);
});
test('a source-bound canonical controller proposal is persisted only as inert planning output without creating dispatch or receipt',async t=>{
 const f=fixture();t.after(()=>f.close());const proposal:G.GameActionProposal={schemaVersion:'1.0.0',recordType:'gameActionProposal',scope:f.scope,proposalId:randomUUID(),observationId:f.checkpoint.lastObservationId!,observationRevision:1,preparedViewId:f.input.binding.viewId,preparedViewRevision:1,invalidationKey:f.input.binding.invalidationKey,buttons:['a'],durationFrames:1,maxWallMs:100,expectedVisibleOutcome:'A scripted menu may change.',uncertainty:'Synthetic planning; no execution.',adviceRefs:[],reason:'Consider the currently observed synthetic menu.',preconditions:[{predicateId:randomUUID(),fieldId:'scripted-visible-menu',expectedValue:'open',sourceObservationId:f.checkpoint.lastObservationId!}]};f.provider.generate=async function*(){yield {kind:'text',text:JSON.stringify(proposal)};yield {kind:'done'};};assert.equal((await runCheckpointedGamePlanning(f.input,f.ports)).state,'published');assert.deepEqual(f.published[0]!.proposal,proposal);assert.equal(Object.hasOwn(f.published[0]!,'admission'),false);assert.equal(f.repository.get(f.owner,f.scope.runId)!.checkpoint.lastActionReceipt,null);
});
test('a new authentic view cannot bypass consumed model-call budget even though its once-only identity differs',async t=>{
 const f=fixture(':memory:',1);t.after(()=>f.close());assert.equal((await runCheckpointedGamePlanning(f.input,f.ports)).state,'published');const binding=createPreparedTurnBinding({viewId:randomUUID(),revision:1,invalidationKey:randomUUID(),scope:f.input.binding.scope,conversation:'[]',sourceRevisions:{conversation:'scripted:1'}}),game=prepareGameCampaignContext(selectGameCampaignContext(f.sourceInput,f.boundary),binding),turn=finalizePreparedTurn({assistantId:f.scope.assistantId,sessionId:f.scope.contextBinding.sessionId,endpointId:f.scope.contextBinding.endpointId,interactionId:randomUUID(),conversation:'[]',origin:'activityStep',preparedTurnBinding:binding,preparedGameCampaignContext:game,maximumOutputTokens:1024},()=>true);assert.equal((await runCheckpointedGamePlanning({...f.input,binding,game,turn},f.ports)).state,'failed');assert.equal(f.calls(),1);assert.equal(f.repository.get(f.owner,f.scope.runId)!.used.modelCalls,1);assert.equal(f.repository.get(f.owner,f.scope.runId)!.reserved.modelCalls,0);
});
test('a checkpoint/source change while qualifying terminal prevents settlement and publication; worst-case capacity remains held',async t=>{
 const f=fixture();t.after(()=>f.close());f.ports.terminalRef=()=>{const checkpoint=f.repository.get(f.owner,f.scope.runId)!.checkpoint;checkpoint.revision++;checkpoint.stateRevision++;checkpoint.campaignJournalRef.accessRevision++;f.repository.put(f.owner,checkpoint,1);return 'scripted-qualified-provider-terminal';};assert.equal((await runCheckpointedGamePlanning(f.input,f.ports)).state,'cancelled');assert.equal(f.published.length,0);const state=f.repository.get(f.owner,f.scope.runId)!;assert.equal(state.used.modelCalls,0);assert.equal(state.reserved.modelCalls,1);
});
test('store or coordinator replacement during tokenizer work cannot migrate a pending reservation or publish its result',async t=>{
 for(const mode of ['store','coordinator'])await t.test(mode,async()=>{const f=fixture();try{f.provider.tokenize=async()=>{if(mode==='store')f.ports.repository=new ActivityCheckpointRepository(f.db,f.options);else f.ports.background={runBackground:work=>f.admin.runBackground(work)};return {count:100,identity:'scripted-tokenizer:1'};};assert.equal((await runCheckpointedGamePlanning(f.input,f.ports)).state,'cancelled');assert.equal(f.calls(),0);assert.equal(f.published.length,0);assert.equal(f.db.connection.prepare('SELECT state FROM activity_planning_reservations').get()!.state,'reserved');}finally{f.close();}});
});
