import assert from "node:assert/strict";
import { test, type TestContext } from "node:test";
import { randomBytes } from "node:crypto";
import { mkdtempSync, rmSync, readFileSync, readdirSync, copyFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Database } from "../../../packages/storage-sqlite/src/database.ts";
import { LocalAuthentication, AUTH_PARAMETERS, totpCode, encodeBase32, type LocalAuthOptions, type ProposedOperation } from "../src/auth/local-auth.ts";
const password = () => `synthetic-${randomBytes(24).toString("hex")}`;
const origin = "http://127.0.0.1:33000";
function environment(t: TestContext, extra: Partial<LocalAuthOptions> = {}) { const root=mkdtempSync(join(tmpdir(),"ls-auth-")), path=join(root,"db.sqlite"), stateDirectory=join(root,"safety"); let now=1_800_000_000_000; const database=new Database({path});database.migrate();const options={stateDirectory,installerToken:randomBytes(32).toString("hex"),now:()=>now,...extra}; const auth=new LocalAuthentication(database,options);t.after(()=>{try{database.close();}catch{}rmSync(root,{recursive:true,force:true});});return {root,path,stateDirectory,database,auth,options,advance:(ms:number)=>{now+=ms;},time:()=>now}; }

test("single installer claim survives concurrency, retry, process restart and interrupted setup", async t=>{
  const e=environment(t);const secret=password();const results=await Promise.allSettled([e.auth.setup("owner",secret,e.options.installerToken,origin),e.auth.setup("second",secret,e.options.installerToken,origin)]);assert.equal(results.filter(r=>r.status==="fulfilled").length,1);assert.equal(e.auth.status().setupRequired,false);assert.equal((e.database.connection.prepare("SELECT COUNT(*) AS n FROM local_accounts WHERE owner=1").get() as {n:number}).n,1);assert.equal(new LocalAuthentication(e.database,e.options).status().setupRequired,false);await assert.rejects(e.auth.setup("third",secret,e.options.installerToken,origin));
  const interrupted=environment(t,{afterSafetyWrite:()=>{throw new Error("synthetic interrupted commit");}});const p=password();await assert.rejects(interrupted.auth.setup("owner",p,interrupted.options.installerToken,origin),/interrupted/);const resumed=new LocalAuthentication(interrupted.database,{stateDirectory:interrupted.stateDirectory,now:interrupted.options.now});assert.equal(resumed.status().setupRequired,false);assert.ok(await resumed.signIn("owner",p,"",origin,"loopback"));
});

test("password verifiers, recovery values and MFA secrets are protected; attempts are bounded",async t=>{
  const e=environment(t),p=password();const setup=await e.auth.setup("owner",p,e.options.installerToken,origin);assert.equal(setup.recoveryCodes.length,10);assert.equal(new Set(setup.recoveryCodes).size,10);const row=e.database.connection.prepare("SELECT password_verifier FROM local_accounts").get() as {password_verifier:string};assert.notEqual(row.password_verifier,p);assert.match(row.password_verifier,/^[a-f0-9]{32}:[a-f0-9]{64}$/);for(let i=0;i<5;i++)await assert.rejects(e.auth.signIn("owner",password(),"",origin,"loopback"));await assert.rejects(e.auth.signIn("owner",p,"",origin,"loopback"),/attempt limit/);e.advance(900_000);assert.ok(await e.auth.signIn("owner",p,"",origin,"loopback"));const databaseBytes=readFileSync(e.path).toString("binary");assert.ok(!databaseBytes.includes(p));for(const code of setup.recoveryCodes)assert.ok(!databaseBytes.includes(code));
});

test("offline TOTP matches RFC6238 SHA1 vectors, enrolls using interoperable URI and rejects replay and clock boundaries",async t=>{
  const secret=encodeBase32(Buffer.from("12345678901234567890"));for(const [seconds,expected] of [[59,"94287082"],[1111111109,"07081804"],[1111111111,"14050471"],[1234567890,"89005924"],[2000000000,"69279037"],[20000000000,"65353130"]] as const)assert.equal(totpCode(secret,seconds*1000,8),expected);
  const e=environment(t),p=password();const enrolled=await e.auth.setup("owner",p,e.options.installerToken,origin),context=e.auth.context(enrolled.session.token,origin)!;const mfa=await e.auth.beginMfa(context,p);const uri=new URL(mfa.uri);assert.equal(uri.protocol,"otpauth:");assert.equal(uri.searchParams.get("period"),"30");assert.equal(uri.searchParams.get("algorithm"),"SHA1");assert.equal(uri.searchParams.get("secret"),mfa.secret);e.auth.confirmMfa(context,totpCode(mfa.secret,e.time()));assert.equal(e.auth.context(enrolled.session.token,origin),undefined);await assert.rejects(e.auth.signIn("owner",p,"",origin,"loopback"));await assert.rejects(e.auth.signIn("owner",p,totpCode(mfa.secret,e.time()),origin,"loopback"));e.advance(30_000);const code=totpCode(mfa.secret,e.time());assert.ok(await e.auth.signIn("owner",p,code,origin,"loopback"));await assert.rejects(e.auth.signIn("owner",p,code,origin,"loopback"));const restarted=new LocalAuthentication(e.database,e.options);await assert.rejects(restarted.signIn("owner",p,code,origin,"loopback"));e.advance(900_000);await assert.rejects(restarted.signIn("owner",p,totpCode(mfa.secret,e.time()-60_000),origin,"loopback"));const row=e.database.connection.prepare("SELECT totp_secret FROM local_accounts").get() as {totp_secret:string};assert.notEqual(row.totp_secret,mfa.secret);for(const file of readdirSync(e.stateDirectory))if(file.endsWith('.json'))assert.ok(!readFileSync(join(e.stateDirectory,file),'utf8').includes(mfa.secret));
});

test("two MFA enrollment sessions cannot overwrite the first confirmed factor",async t=>{const e=environment(t),p=password();const setup=await e.auth.setup("owner",p,e.options.installerToken,origin);const second=await e.auth.signIn("owner",p,"",origin,"loopback");const a=e.auth.context(setup.session.token,origin)!,b=e.auth.context(second.token,origin)!;const first=await e.auth.beginMfa(a,p),other=await e.auth.beginMfa(b,p);e.auth.confirmMfa(a,totpCode(first.secret,e.time()));assert.throws(()=>e.auth.confirmMfa(b,totpCode(other.secret,e.time())),/authentication/);});

test("administration expires exactly at 1800 seconds; polling and unlimited conversation do not extend it",async t=>{const e=environment(t),p=password();const setup=await e.auth.setup("owner",p,e.options.installerToken,origin);e.advance(1_799_000);const context=e.auth.context(setup.session.token,origin)!;assert.ok(context);assert.equal(e.auth.renewCsrf(context),setup.session.csrfToken);assert.ok(e.auth.context(setup.session.token,origin,false));e.advance(1_000);assert.equal(e.auth.context(setup.session.token,origin),undefined);assert.ok(e.auth.context(setup.session.token,origin,false));assert.throws(()=>e.auth.touch(context),/authentication/);const fresh=await e.auth.signIn("owner",p,"",origin,"loopback"),freshContext=e.auth.context(fresh.token,origin)!;e.advance(1_000_000);e.auth.touch(freshContext);e.advance(1_000_000);assert.ok(e.auth.context(fresh.token,origin));e.auth.logout(freshContext);assert.equal(e.auth.context(fresh.token,origin,false),undefined);assert.equal(AUTH_PARAMETERS.adminIdleMs,1_800_000);});

test("recovery needs neither lost factor, consumes atomically, preserves unused codes and revokes all sessions",async t=>{const e=environment(t),p=password();const setup=await e.auth.setup("owner",p,e.options.installerToken,origin),context=e.auth.context(setup.session.token,origin)!;const mfa=await e.auth.beginMfa(context,p);e.auth.confirmMfa(context,totpCode(mfa.secret,e.time()));const recoveredPassword=password();const results=await Promise.allSettled([e.auth.recover("owner",setup.recoveryCodes[0]!,recoveredPassword,"loopback"),e.auth.recover("owner",setup.recoveryCodes[0]!,recoveredPassword,"loopback")]);assert.equal(results.filter(result=>result.status==="fulfilled").length,1);await assert.rejects(e.auth.recover("owner",setup.recoveryCodes[0]!,password(),"loopback"));assert.ok(await e.auth.signIn("owner",recoveredPassword,"",origin,"loopback"));assert.equal(e.auth.context(setup.session.token,origin,false),undefined);const restarted=new LocalAuthentication(e.database,e.options);await assert.rejects(restarted.recover("owner",setup.recoveryCodes[0]!,password(),"loopback"));assert.ok(await restarted.recover("owner",setup.recoveryCodes[1]!,password(),"loopback"));});

test("interrupted recovery resumes and an older database cannot restore consumed codes or credentials",async t=>{const e=environment(t),p=password();const setup=await e.auth.setup("owner",p,e.options.installerToken,origin);const backup=join(e.root,"before.sqlite");await e.database.backup(backup);const next=password();const interrupted=new LocalAuthentication(e.database,{...e.options,afterSafetyWrite:()=>{throw new Error("synthetic interrupted commit");}});await assert.rejects(interrupted.recover("owner",setup.recoveryCodes[0]!,next,"loopback"),/interrupted/);const recovered=new LocalAuthentication(e.database,e.options);assert.ok(await recovered.signIn("owner",next,"",origin,"loopback"));await assert.rejects(recovered.recover("owner",setup.recoveryCodes[0]!,password(),"loopback"));e.database.close();copyFileSync(backup,e.path);const restored=new Database({path:e.path});restored.migrate();t.after(()=>restored.close());const auth=new LocalAuthentication(restored,e.options);await assert.rejects(auth.signIn("owner",p,"",origin,"loopback"));assert.ok(await auth.signIn("owner",next,"",origin,"loopback"));await assert.rejects(auth.recover("owner",setup.recoveryCodes[0]!,password(),"loopback"));assert.equal(auth.context(setup.session.token,origin,false),undefined);});

test("Owner provisions accounts without scope; proposal approval is content/session/revision bound and one-use",async t=>{const e=environment(t),p=password();const setup=await e.auth.setup("owner",p,e.options.installerToken,origin),owner=e.auth.context(setup.session.token,origin)!;const userPassword=password();const user=await e.auth.provision(owner,"member",userPassword);assert.deepEqual(user.assistantPermissions,[]);const session=await e.auth.signIn("member",userPassword,"",origin,"loopback"),member=e.auth.context(session.token,origin)!;await assert.rejects(e.auth.provision(member,"intruder",password()),/owner required/);assert.throws(()=>e.auth.accounts(member),/owner required/);const operation:ProposedOperation={method:"POST",path:"/api/admin/v1/assistants",body:{displayName:"Synthetic"},expectedRevision:null};const proposal=e.auth.propose(owner,operation);let applied=0;assert.throws(()=>e.auth.approve(member,proposal.proposalId,proposal.digest,true,()=>++applied));assert.throws(()=>e.auth.approve(owner,proposal.proposalId,'0'.repeat(64),true,()=>++applied));assert.throws(()=>e.auth.approve(owner,proposal.proposalId,proposal.digest,false,()=>++applied));assert.equal(e.auth.approve(owner,proposal.proposalId,proposal.digest,true,()=>++applied),1);assert.throws(()=>e.auth.approve(owner,proposal.proposalId,proposal.digest,true,()=>++applied));const stale=e.auth.propose(owner,operation);const reauth=await e.auth.signIn("owner",p,"",origin,"loopback");assert.throws(()=>e.auth.review(e.auth.context(reauth.token,origin)!,stale.proposalId),/fresh review/);e.auth.revokeAccount(owner,user.principalId);assert.equal(e.auth.context(session.token,origin,false),undefined);});
