import assert from "node:assert/strict";
import { test } from "node:test";
import { randomBytes, randomUUID } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createLifestreamServer } from "../src/index.ts";
import { loadProfile } from "../src/config/loader.ts";
const secret=()=>`synthetic-${randomBytes(24).toString("hex")}`;
test('audience evidence and declarations survive admin expiry while CSRF, revocation and disclosure fences remain enforced',{timeout:15000},async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-audience-idle-'));t.after(()=>rm(root,{recursive:true,force:true}));let now=Date.now();
 const config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};
 const installerToken=secret(),app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'auth'),installerToken,now:()=>now},audiencePrivacy:{sourceIds:[]}});await app.start();t.after(()=>app.shutdown());
 const base=`http://127.0.0.1:${app.address().port}`,headers:Record<string,string>={origin:base,'content-type':'application/json'};
 const request=(path:string,body?:unknown,extra:Record<string,string>={})=>fetch(base+path,{method:body===undefined?'GET':'POST',headers:{...headers,...extra},...(body===undefined?{}:{body:JSON.stringify(body)})});
 const setup=await request('/api/auth/v1/setup',{username:'synthetic-owner',password:secret(),installerToken});assert.equal(setup.status,201);headers.cookie=setup.headers.get('set-cookie')!.split(';')[0]!;const {session}=await setup.json() as {session:{csrfToken:string;sessionId:string}};headers['x-lifestream-csrf']=session.csrfToken;
 assert.equal((await request('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'})).status,200);
 assert.equal((await request('/api/runtime/v1/audience',{mode:'solo',seconds:300})).status,200);
 const activity=()=>app.database.connection.prepare('SELECT admin_last_activity FROM local_sessions WHERE session_id=?').get(session.sessionId)!.admin_last_activity,original=activity();
 const stream=await request('/api/runtime/v1/audience/events');assert.equal(stream.status,200);const reader=stream.body!.getReader();t.after(()=>reader.cancel());assert.equal((await reader.read()).done,false);
 now+=1_800_000;
 assert.equal((await request('/api/auth/v1/session')).status,401);assert.equal((await request('/api/admin/v1/assistants',{})).status,401);
 const next=await reader.read();assert.equal(next.done,false,'Audience heartbeat must use continuing conversation authority');assert.match(Buffer.from(next.value!).toString(),/"privateAllowed":true/);
 assert.equal((await request('/api/runtime/v1/audience',{mode:'solo',seconds:300},{'x-lifestream-csrf':'wrong'})).status,403);
 assert.equal((await request('/api/runtime/v1/audience',{mode:'solo',seconds:300})).status,200,'Expiring declarations must remain renewable without extending administration');
 for(const [mode,allowed] of [['shared',false],['solo',true],['lock',false],['unlock',false],['solo',true],['clear',false]] as const){const response=await request('/api/runtime/v1/audience',{mode,seconds:300});assert.equal(response.status,200);assert.equal((await response.json() as {privateAllowed:boolean}).privateAllowed,allowed);}
 assert.equal(activity(),original,'Runtime audience activity must not refresh administration');assert.equal((await request('/api/auth/v1/session')).status,401);
 assert.equal((await request('/api/auth/v1/sign-out',{})).status,200);
 let ended=false;while(!ended){ended=(await reader.read()).done===true;}
 assert.equal((await request('/api/runtime/v1/audience')).status,401);assert.equal((await request('/api/runtime/v1/audience',{mode:'solo'})).status,401);
});
test("real local sessions protect actual administration, scope and approvals while idle-expired conversation continues",async t=>{
 const root=await mkdtemp(join(tmpdir(),"ls-auth-http-"));t.after(()=>rm(root,{recursive:true,force:true}));let now=1_800_000_000_000;const config=loadProfile("test");config.storage={databasePath:join(root,"db.sqlite"),artifactDirectory:join(root,"artifacts")};config.authority.authentication="local-password";const installerToken=secret();const app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,"safety"),installerToken,now:()=>now}});await app.start();t.after(()=>app.shutdown());const base=`http://127.0.0.1:${app.address().port}`;let cookie="",csrf="";const request=(path:string,body?:unknown,extra:Record<string,string>={})=>fetch(base+path,{method:body===undefined?"GET":"POST",headers:{origin:base,"content-type":"application/json",cookie,"x-lifestream-csrf":csrf,...extra},...(body===undefined?{}:{body:JSON.stringify(body)})});
 assert.equal((await request('/api/runtime/v1/session-context')).status,401);
 assert.equal((await request('/api/admin/v1/assistants',{})).status,401);assert.equal((await request('/api/admin/v1/assistants',{}, {'x-lifestream-fixture-session':'spoof','x-lifestream-fixture-principal':'owner'})).status,401);
 assert.equal((await request('/api/auth/v1/setup',{username:'owner',password:secret(),installerToken},{origin:'https://untrusted.invalid'})).status,403);
 const password=secret();const enrollment=await request('/api/auth/v1/setup',{username:'owner',password,installerToken});assert.equal(enrollment.status,201);const setCookie=enrollment.headers.get('set-cookie')!;assert.match(setCookie,/HttpOnly/);assert.match(setCookie,/SameSite=Strict/);cookie=setCookie.split(';')[0]!;const setup=await enrollment.json() as {session:{csrfToken:string;principalId:string;sessionId:string};recoveryCodes:string[]};csrf=setup.session.csrfToken;
 assert.equal((await request('/api/admin/v1/assistants',{displayName:'Synthetic'},{'x-lifestream-csrf':'wrong'})).status,403);assert.equal((await request('/api/admin/v1/assistants',{displayName:'Synthetic'},{origin:'https://untrusted.invalid'})).status,403);
 const repeated=await request('/api/auth/v1/session');assert.equal((await repeated.json() as {csrfToken:string}).csrfToken,csrf);
 const create=await request('/api/admin/v1/assistants',{displayName:'Synthetic Assistant'});assert.equal(create.status,201);const assistant=await create.json() as {assistantId:string;profile:{profileId:string}};const relationshipResponse=await request(`/api/admin/v1/assistants/${assistant.assistantId}/relationships`,{});assert.equal(relationshipResponse.status,201);const relationship=await relationshipResponse.json() as {relationship:{relationshipId:string}};
 const memberPassword=secret();const provision=await request('/api/auth/v1/accounts',{username:'member',password:memberPassword});assert.equal(provision.status,201);const member=await provision.json() as {principalId:string;assistantPermissions:string[]};assert.deepEqual(member.assistantPermissions,[]);const ownerCookie=cookie,ownerCsrf=csrf;
 const signIn=await request('/api/auth/v1/sign-in',{username:'member',password:memberPassword});cookie=signIn.headers.get('set-cookie')!.split(';')[0]!;csrf=(await signIn.json() as {session:{csrfToken:string}}).session.csrfToken;
 assert.equal((await request(`/api/admin/v1/assistants/${assistant.assistantId}`)).status,403);assert.equal((await request('/api/auth/v1/accounts',{username:'unapproved',password:secret()})).status,403);
 const memberCookie=cookie,memberCsrf=csrf;cookie=ownerCookie;csrf=ownerCsrf;assert.equal((await request('/api/auth/v1/permissions',{principalId:member.principalId,assistantId:assistant.assistantId,administer:true})).status,200);cookie=memberCookie;csrf=memberCsrf;
 assert.equal((await request(`/api/admin/v1/assistants/${assistant.assistantId}`)).status,200);assert.equal((await request(`/api/admin/v1/assistants/${assistant.assistantId}/relationships/${relationship.relationship.relationshipId}`)).status,404);
 cookie=ownerCookie;csrf=ownerCsrf;const operation={method:'POST',path:`/api/admin/v1/assistants/${assistant.assistantId}/activate`,body:{profileId:assistant.profile.profileId,expectedActiveRevision:null},expectedRevision:null};const proposed=await request('/api/auth/v1/proposals',{operation});assert.equal(proposed.status,201);const proposal=await proposed.json() as {proposalId:string;digest:string};assert.equal((await request(`/api/auth/v1/proposals/${proposal.proposalId}/approve`,{reviewedDigest:proposal.digest,humanConfirmed:false})).status,409);assert.equal((await request(`/api/auth/v1/proposals/${proposal.proposalId}/approve`,{reviewedDigest:'0'.repeat(64),humanConfirmed:true})).status,409);assert.equal((await request(`/api/auth/v1/proposals/${proposal.proposalId}/approve`,{reviewedDigest:proposal.digest,humanConfirmed:true})).status,200);assert.equal((await request(`/api/auth/v1/proposals/${proposal.proposalId}/approve`,{reviewedDigest:proposal.digest,humanConfirmed:true})).status,409);
 assert.equal((await request('/api/admin/v1/assistants',{displayName:'AI bypass',authoredBy:'ai'})).status,403);
 const staleOperation={method:'POST',path:`/api/admin/v1/assistants/${assistant.assistantId}/revisions`,body:{displayName:'Proposed stale revision',expectedRevision:1},expectedRevision:1};const staleProposal=await (await request('/api/auth/v1/proposals',{operation:staleOperation})).json() as {proposalId:string;digest:string};assert.equal((await request(`/api/admin/v1/assistants/${assistant.assistantId}/revisions`,{displayName:'Independent current revision',expectedRevision:1})).status,201);assert.equal((await request(`/api/auth/v1/proposals/${staleProposal.proposalId}/approve`,{reviewedDigest:staleProposal.digest,humanConfirmed:true})).status,409);
 assert.equal((await request('/api/auth/v1/proposals',{operation:{...staleOperation,expectedRevision:null}})).status,409);
 cookie=memberCookie;csrf=memberCsrf;const scopedProposal=await (await request('/api/auth/v1/proposals',{operation:{...staleOperation,body:{displayName:'Scoped proposed revision',expectedRevision:2},expectedRevision:2}})).json() as {proposalId:string;digest:string};cookie=ownerCookie;csrf=ownerCsrf;await request('/api/auth/v1/permissions',{principalId:member.principalId,assistantId:assistant.assistantId,administer:false});cookie=memberCookie;csrf=memberCsrf;assert.equal((await request(`/api/auth/v1/proposals/${scopedProposal.proposalId}/approve`,{reviewedDigest:scopedProposal.digest,humanConfirmed:true})).status,403);cookie=ownerCookie;csrf=ownerCsrf;

 now+=1_799_000;assert.equal((await request('/api/auth/v1/session')).status,200);now+=1_000;assert.equal((await request('/api/admin/v1/assistants',{displayName:'Expired'})).status,401);const conversation=await request('/api/runtime/v1/messages',{assistantId:assistant.assistantId,userInput:'Continue synthetic conversation.'});assert.equal(conversation.status,200);assert.match(await conversation.text(),/Fixture response/);assert.equal((await request('/api/auth/v1/session')).status,401);assert.equal((await request('/api/auth/v1/sign-out',{})).status,200);assert.equal((await request('/api/runtime/v1/messages',{assistantId:assistant.assistantId,userInput:'Revoked'})).status,401);
});

test("real session logout, permission, audience and endpoint changes fence pending typed output", async t => {
 const { FixtureInferenceProvider } = await import('@lifestream/runtime/inference/fixture');
 for (const action of ['logout','permission','audience','endpoint'] as const) {
  const root=await mkdtemp(join(tmpdir(),'ls-auth-fence-'));const config=loadProfile('test');config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};config.authority.authentication='local-password';const installerToken=secret();const app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'safety'),installerToken}});await app.start();
  const base=`http://127.0.0.1:${app.address().port}`;let cookie='',csrf='';const post=(path:string,body:unknown)=>fetch(base+path,{method:'POST',headers:{origin:base,'content-type':'application/json',cookie,'x-lifestream-csrf':csrf},body:JSON.stringify(body)});
  const setup=await post('/api/auth/v1/setup',{username:'owner',password:secret(),installerToken});cookie=setup.headers.get('set-cookie')!.split(';')[0]!;const identity=await setup.json() as {session:{csrfToken:string;principalId:string}};csrf=identity.session.csrfToken;
  const created=await (await post('/api/admin/v1/assistants',{displayName:'Synthetic scoped runtime'})).json() as {assistantId:string;profile:{profileId:string}};await post(`/api/admin/v1/assistants/${created.assistantId}/activate`,{profileId:created.profile.profileId,expectedActiveRevision:null});
  if (action === 'audience' || action === 'endpoint') { const scoped=await post('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'}); assert.equal(scoped.status,200); }
  const original=FixtureInferenceProvider.prototype.generate;let release!:()=>void;const held=new Promise<void>(r=>{release=r;});FixtureInferenceProvider.prototype.generate=async function*(){await held;yield {kind:'text',text:'REVOKED_PENDING_CONTEXT'};yield {kind:'done'};};
  try {
   const response=await post('/api/runtime/v1/messages',{assistantId:created.assistantId,userInput:'Synthetic pending reply'});assert.equal(response.status,200);const output=response.text();
   const changed=action==='audience'||action==='endpoint'?await post('/api/runtime/v1/session-context',{expectedRevision:1,mode:action==='endpoint'?'none':'text',audienceScope:'unknown'}):action==='logout'?await post('/api/auth/v1/sign-out',{}):await post('/api/auth/v1/permissions',{principalId:identity.session.principalId,assistantId:created.assistantId,administer:false});assert.equal(changed.status,200);release();const text=await output;assert.doesNotMatch(text,/REVOKED_PENDING_CONTEXT/);assert.match(text,/runtime_input_stale/);assert.doesNotMatch(text,/event: interaction.completed/);
  } finally {release();FixtureInferenceProvider.prototype.generate=original;await app.shutdown();await rm(root,{recursive:true,force:true});}
 }
});


test('authenticated sessions on one remembered endpoint isolate actual prepared memory and retain their disclosure across restart',async t=>{
 const {FixtureInferenceProvider}=await import('@lifestream/runtime/inference/fixture');const root=await mkdtemp(join(tmpdir(),'ls-two-session-scope-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};config.authority.authentication='local-password';const installerToken=secret(),password=secret(),options={config,localAuth:{stateDirectory:join(root,'safety'),installerToken},audiencePrivacy:{sourceIds:[]}};let app=createLifestreamServer(options);await app.start();t.after(()=>app.shutdown());let base=`http://127.0.0.1:${app.address().port}`;
 type Client={cookie:string;csrf:string};const first:Client={cookie:'',csrf:''},second:Client={cookie:'',csrf:''};
 const request=(client:Client,path:string,body?:unknown)=>fetch(base+path,{method:body===undefined?'GET':'POST',headers:{origin:base,'content-type':'application/json',cookie:client.cookie,'x-lifestream-csrf':client.csrf},...(body===undefined?{}:{body:JSON.stringify(body)})});
 const api=async(client:Client,path:string,body?:unknown)=>{const res=await request(client,path,body),data=await res.json() as any;assert.ok(res.ok,JSON.stringify(data));return data;};
 const authenticate=async(client:Client,setup=false)=>{const res=await request(client,setup?'/api/auth/v1/setup':'/api/auth/v1/sign-in',{username:'owner',password,...(setup?{installerToken}:{})});assert.ok(res.ok);client.cookie=res.headers.get('set-cookie')!.split(';')[0]!;client.csrf=(await res.json() as any).session.csrfToken;};
 await authenticate(first,true);await authenticate(second);const assistant=await api(first,'/api/admin/v1/assistants',{displayName:'Synthetic session isolation'});await api(first,`/api/admin/v1/assistants/${assistant.assistantId}/activate`,{profileId:assistant.profile.profileId,expectedActiveRevision:null});await api(first,`/api/admin/v1/assistants/${assistant.assistantId}/relationships`,{});const memory=(await api(first,`/api/admin/v1/assistants/${assistant.assistantId}/memories`,{content:'The synthetic project code is PRIVATE_SESSION_SENTINEL.'})).memory;await api(first,`/api/admin/v1/assistants/${assistant.assistantId}/memories/${memory.id}/lifecycle`,{status:'active',expectedRevision:1});
 const bindingKey=randomUUID(),one=await api(first,'/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'unknown',bindingKey}),two=await api(second,'/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession',bindingKey});assert.equal(one.endpoint.endpointId,two.endpoint.endpointId);
 const captured:any[]=[];const original=FixtureInferenceProvider.prototype.generate;FixtureInferenceProvider.prototype.generate=async function*(request,context){captured.push(request);yield* original.call(this,request,context);};t.after(()=>{FixtureInferenceProvider.prototype.generate=original;});
 const turn=async(client:Client)=>{const response=await request(client,'/api/runtime/v1/messages',{assistantId:assistant.assistantId,userInput:'What is the synthetic project code?'});assert.equal(response.status,200);assert.match(await response.text(),/interaction.completed/);return captured.at(-1).sections.find((s:{kind:string})=>s.kind==='preparedMemory').content;};
 for(let attempt=0;attempt<2;attempt++){
  await api(first,'/api/runtime/v1/audience',{mode:'solo',seconds:300});await api(second,'/api/runtime/v1/audience',{mode:'solo',seconds:300});
  const a=await api(first,'/api/runtime/v1/session-context'),b=await api(second,'/api/runtime/v1/session-context');assert.equal(a.runtimeSelfContext.audienceScope,'unknown');assert.equal(b.runtimeSelfContext.audienceScope,'authenticatedSession');assert.deepEqual(a.endpoint.outputModalities,['text']);assert.deepEqual(b.endpoint.outputModalities,['text']);
  assert.doesNotMatch(await turn(first),/PRIVATE_SESSION_SENTINEL/);assert.match(await turn(second),/PRIVATE_SESSION_SENTINEL/);
  if(attempt===0){const port=app.address().port;await app.shutdown();app=createLifestreamServer({...options,port});await app.start();base=`http://127.0.0.1:${app.address().port}`;}
 }
});


test('sign-out while a session settings request body is pending prevents its later mutation',{timeout:10000},async t=>{
 const {request:httpRequest}=await import('node:http');
 const root=await mkdtemp(join(tmpdir(),'ls-delayed-settings-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};config.authority.authentication='local-password';const installerToken=secret(),app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'auth'),installerToken}});await app.start();t.after(()=>app.shutdown());const base=`http://127.0.0.1:${app.address().port}`,headers:Record<string,string>={origin:base,'content-type':'application/json'};
 const post=(path:string,body:unknown)=>fetch(base+path,{method:'POST',headers,body:JSON.stringify(body)}),setup=await post('/api/auth/v1/setup',{username:'owner',password:secret(),installerToken});assert.equal(setup.status,201);headers.cookie=setup.headers.get('set-cookie')!.split(';')[0]!;const identity=await setup.json();headers['x-lifestream-csrf']=identity.session.csrfToken;
 assert.equal((await post('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'unknown'})).status,200);
 const state=()=>app.database.connection.prepare('SELECT * FROM session_endpoint_settings WHERE session_id=?').get(identity.session.sessionId);const before=state();assert.ok(before);
 const body=JSON.stringify({expectedRevision:1,mode:'text',audienceScope:'authenticatedSession'});let observed!:()=>void;const received=new Promise<void>(r=>{observed=r;});app.server.once('request',request=>request.once('data',observed));
 let send!:import('node:http').ClientRequest;const result=new Promise<number>((resolve,reject)=>{send=httpRequest(base+'/api/runtime/v1/session-context',{method:'POST',headers:{...headers,'content-length':String(Buffer.byteLength(body))}},response=>{response.resume();response.on('end',()=>resolve(response.statusCode!));});send.on('error',reject);});t.after(()=>send.destroy());send.write(body.slice(0,10));await received;
 assert.equal((await post('/api/auth/v1/sign-out',{})).status,200);send.end(body.slice(10));assert.equal(await result,401);assert.deepEqual(state(),before,'revoked authentication cannot persist a later private disclosure');
});
