import assert from 'node:assert/strict';
import test from 'node:test';
import {mkdtemp,rm,mkdir,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes,randomUUID,createHash} from 'node:crypto';
import {WebSocket} from 'ws';
import {Database} from '../../../packages/storage-sqlite/src/database.ts';
import {PresentationPackages,PresentationSelection} from '../src/admin/presentation-packages.ts';
import {createLifestreamServer} from '../src/index.ts';
import {loadProfile} from '../src/config/loader.ts';
import {FixtureInferenceProvider} from '@lifestream/runtime/inference/fixture';
import type {InferenceRequest} from '@lifestream/runtime/inference';

test('saved presentation reaches actual prepared input without claiming rendering or exposing asset metadata',{timeout:15000},async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-presentation-self-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};config.authority.authentication='local-password';const installerToken=randomBytes(32).toString('hex'),app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'auth'),installerToken},audiencePrivacy:{sourceIds:[]}});await app.start();t.after(()=>app.shutdown());
 const base=`http://127.0.0.1:${app.address().port}`,headers:Record<string,string>={origin:base,'content-type':'application/json'};const request=(path:string,body?:unknown)=>fetch(base+path,{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:JSON.stringify(body)})});
 const setup=await request('/api/auth/v1/setup',{username:'owner',password:randomBytes(24).toString('hex'),installerToken});assert.equal(setup.status,201);headers.cookie=setup.headers.get('set-cookie')!.split(';')[0]!;const identity=(await setup.json()).session;headers['x-lifestream-csrf']=identity.csrfToken;
 await request('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'unknown'});await request('/api/runtime/v1/audience',{mode:'solo',seconds:300});const created=await(await request('/api/admin/v1/assistants',{displayName:'Synthetic display configuration'})).json();await request(`/api/admin/v1/assistants/${created.assistantId}/activate`,{profileId:created.profile.profileId,expectedActiveRevision:null});
 const self=async()=>((await(await request('/api/runtime/v1/session-context')).json()).runtimeSelfContext);const unconfigured=await self();assert.equal(unconfigured.outputModalities.presentation,'notConfigured');
 assert.equal((await request('/api/runtime/v1/presentation',{scope:'session',id:'neutral',digest:'neutral-v1',expectedRevision:0})).status,200);const configured=await self();assert.equal(configured.outputModalities.presentation,'configuredNotObserved');assert.deepEqual(configured.modalityFacts.presentation,{implemented:true,configured:true,connected:false,activeForSession:false,authorized:true});assert.equal(configured.inputModalities.visual,'notConfigured');assert.notEqual(configured.sourceRevision,unconfigured.sourceRevision);assert.doesNotMatch(JSON.stringify(configured),/neutral-v1|package_id|model\.glb/);
 let captured:InferenceRequest|undefined;t.mock.method(FixtureInferenceProvider.prototype,'generate',async function*(value:InferenceRequest){captured=value;yield {kind:'text',text:'Synthetic reply.'};yield {kind:'done'};});
 const turn=await request('/api/runtime/v1/messages',{assistantId:created.assistantId,userInput:'What presentation is configured?',runtimeSelfContext:{presentation:'active',physicalCamera:true}});assert.equal(turn.status,200);assert.match(await turn.text(),/interaction.completed/);const state=captured!.sections.find(s=>s.kind==='interactionState')!;assert.match(state.content,/output.presentation=configuredNotObserved/);assert.match(state.content,/input.visual=notConfigured/);assert.doesNotMatch(state.content,/physicalCamera|neutral-v1/);
 // The real authenticated WebSocket uses the same host projection after transcription.
 (app as any).providers.stt={async *transcribe(){yield {kind:'data',payload:{type:'committed',text:'What presentation is configured for this voice turn?'}};yield {kind:'terminal',outcome:'succeeded'};}};
 (app as any).providers.tts={async *synthesize(value:any){yield {kind:'data',segmentId:value.segmentId,frame:{frameId:randomUUID(),sequence:0,format:value.format,sampleOffset:0,sampleCount:10,dataBase64:Buffer.alloc(20).toString('base64')},mappingRevision:'fixture-map'};yield {kind:'terminal',outcome:'succeeded',outputSamples:10,frameCount:1,mappingRevision:'fixture-map',degradedDimensions:[],disposition:'fullyApplied'};}};
 const current=await(await request('/api/runtime/v1/session-context')).json();const revised=await request('/api/runtime/v1/session-context',{expectedRevision:current.revision,mode:'audio',audienceScope:'authenticatedSession'});const audioContext=await revised.json();assert.equal(revised.status,200,JSON.stringify({current,audioContext}));
 const socket=new WebSocket(base.replace('http:','ws:')+'/api/runtime/v1/audio',{origin:base,headers:{cookie:headers.cookie!,'x-lifestream-csrf':headers['x-lifestream-csrf']!}});t.after(()=>socket.terminate());const events:any[]=[];let accepted:()=>void=()=>{},completed:()=>void=()=>{};const ready=new Promise<void>(r=>{accepted=r;}),done=new Promise<void>(r=>{completed=r;});
 socket.on('message',raw=>{const event=JSON.parse(raw.toString());events.push(event);if(event.type==='accepted')accepted();if(event.event?.payload.type==='terminal')completed();});await new Promise<void>((resolve,reject)=>{socket.once('open',resolve);socket.once('error',reject);});
 const audioInputId=randomUUID(),format={encoding:'pcm_s16le',sampleRateHz:16000,channels:1};captured=undefined;socket.send(JSON.stringify({type:'start',request:{schemaVersion:'1.0.0',requestId:randomUUID(),correlationId:randomUUID(),sessionId:identity.sessionId,expectedSessionRevision:audioContext.revision,endpointId:audioContext.endpoint.endpointId,assistantId:created.assistantId,audioInputId,format}}));await ready;
 socket.send(JSON.stringify({type:'frame',audioInputId,frame:{frameId:randomUUID(),sequence:0,format,sampleOffset:0,sampleCount:10,dataBase64:Buffer.alloc(20).toString('base64')}}));socket.send(JSON.stringify({type:'commitTurn',audioInputId,nextSequence:1,sampleCount:10}));await done;assert.equal(events.at(-1).event.payload.state,'completed');
 const audioState=(captured as InferenceRequest|undefined)!.sections.find(section=>section.kind==='interactionState')!;assert.match(audioState.content,/output.presentation=configuredNotObserved/);assert.match(audioState.content,/input.microphone=activeForSession/);assert.match(audioState.content,/input.visual=notConfigured/);assert.doesNotMatch(audioState.content,/neutral-v1|physicalCamera/);socket.terminate();
 await request('/api/runtime/v1/audience',{mode:'shared'});const shared=await self();assert.equal(shared.outputModalities.presentation,'unavailable');assert.equal(shared.modalityFacts.presentation.authorized,false);assert.equal(shared.modalityFacts.presentation.configured,false);assert.notEqual(shared.sourceRevision,configured.sourceRevision);
 await request('/api/runtime/v1/audience',{mode:'solo',seconds:300});assert.equal((await self()).outputModalities.presentation,'configuredNotObserved');
 await request('/api/runtime/v1/presentation',{operation:'clearSessionOverride',expectedRevision:1});assert.equal((await self()).outputModalities.presentation,'notConfigured');
});


test('saved presentation truth is digest pinned, owner scoped and distinct from unobserved playback',async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-presentation-state-'));t.after(()=>rm(root,{recursive:true,force:true}));const directory=join(root,'synthetic-pack');await mkdir(directory);const bytes=Buffer.from(JSON.stringify({asset:{version:'2.0'},scenes:[{nodes:[]}],scene:0}));await writeFile(join(directory,'model.gltf'),bytes);
 const manifest={schemaVersion:'1.0.0',id:'synthetic-pack',version:'1',label:'Synthetic reference',renderer:'three-glb.v1',model:'model.gltf',resources:[{path:'model.gltf',sha256:createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length,mime:'model/gltf+json'}],framing:{distance:1.2,targetHeight:.5},animations:{},capabilities:{lipSync:'none',facialAnimation:false},fallback:'neutral'};await writeFile(join(directory,'manifest.json'),JSON.stringify(manifest));await writeFile(join(root,'index.json'),JSON.stringify(['synthetic-pack']));
 const database=new Database({path:join(root,'state.sqlite')});database.migrate();t.after(()=>database.close());const selection=new PresentationSelection(database),catalog=new PresentationPackages({directory:root,ownerPrincipalId:'owner'}),pack=catalog.list('owner')[0]!;
 const state=(owner='owner',endpoint:string|null='endpoint',session='session-a',permitted=true,packages=catalog)=>selection.runtimeState(owner,endpoint,session,packages,permitted);
 assert.equal(state().state,'notConfigured');assert.equal(state('owner',null).state,'notConfigured');selection.select('owner','endpoint','session-a',{scope:'default',id:pack.id,digest:pack.digest,expectedRevision:0},catalog);const configured=state();assert.equal(configured.state,'configuredNotObserved');assert.equal(state('other').state,'notConfigured');assert.equal(state('owner','other-endpoint').state,'notConfigured');assert.equal(state('owner','endpoint','session-a',false).state,'unavailable');assert.equal(state('owner','endpoint','session-a',true,new PresentationPackages()).state,'unavailable');
 selection.select('owner','endpoint','session-a',{scope:'session',id:'neutral',digest:'neutral-v1',expectedRevision:0},catalog);const override=state();assert.equal(override.state,'configuredNotObserved');assert.notEqual(override.revision,configured.revision);assert.equal(state('owner','endpoint','session-b').revision,configured.revision);
 selection.select('owner','endpoint','session-a',{scope:'default',id:'neutral',digest:'neutral-v1',expectedRevision:1},catalog);assert.equal(state().revision,override.revision);selection.select('owner','endpoint','session-a',{operation:'clearSessionOverride',expectedRevision:1},catalog);assert.notEqual(state().revision,override.revision);
 selection.select('owner','endpoint','session-a',{scope:'session',id:pack.id,digest:pack.digest,expectedRevision:2},catalog);manifest.version='2';await writeFile(join(directory,'manifest.json'),JSON.stringify(manifest));const changed=new PresentationPackages({directory:root,ownerPrincipalId:'owner'});assert.equal(state('owner','endpoint','session-a',true,changed).state,'unavailable');assert.doesNotMatch(JSON.stringify(state()),/synthetic-pack|model.gltf/);
});
