import assert from 'node:assert/strict';
import { test } from 'node:test';
import { randomBytes,randomUUID } from 'node:crypto';
import { mkdtemp,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { createLifestreamServer } from '../src/index.ts';
import { loadProfile } from '../src/config/loader.ts';

test('real authenticated tuning pins activation, rolls back failed transactions and inspects the actual stream',async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-controls-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};let now=Date.now();const installerToken=randomBytes(32).toString('hex');const app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'safety'),installerToken,now:()=>now}});await app.start();t.after(()=>app.shutdown());const base=`http://127.0.0.1:${app.address().port}`,headers:Record<string,string>={origin:base,'content-type':'application/json'};
 const request=(path:string,body?:unknown,extra:Record<string,string>={})=>fetch(base+path,{method:body===undefined?'GET':'POST',headers:{...headers,...extra},...(body===undefined?{}:{body:JSON.stringify(body)})});const api=async(path:string,body?:unknown)=>{const response=await request(path,body),result=await response.json() as Record<string,any>;assert.ok(response.ok,`${response.status}: ${JSON.stringify(result)}`);return result;};
 const setup=await request('/api/auth/v1/setup',{username:'owner',password:randomBytes(32).toString('hex'),installerToken});headers.cookie=setup.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=((await setup.json()) as Record<string,any>).session.csrfToken;
 const assistant=await api('/api/admin/v1/assistants',{displayName:'Synthetic Tuning'});await api(`/api/admin/v1/assistants/${assistant.assistantId}/activate`,{profileId:assistant.profile.profileId,expectedActiveRevision:null});const relationship=(await api(`/api/admin/v1/assistants/${assistant.assistantId}/relationships`,{})).relationship,path=`/api/admin/v1/assistants/${assistant.assistantId}/relationships/${relationship.relationshipId}`;await api('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'});
 const candidate=(await api(path+'/candidates',{content:'For cache examples, use the synthetic project Silver Meadow.',source:'authored',sourceFamily:'one',uncertainty:'high',expectedRevision:1,idempotencyKey:randomUUID()})).candidate;await api(path+`/candidates/${candidate.candidateId}/decision`,{decision:'approved',expectedRevision:2,idempotencyKey:randomUUID()});
 const inventory=(await api(path+'/configurations')).controls;assert.equal(inventory.filter((item:Record<string,any>)=>item.enabled).length,12);assert.deepEqual([...new Set(inventory.map((item:Record<string,any>)=>item.family))].sort(),['communication','evidence','insights','labAdapters','personalContext','representation']);for(const item of inventory){assert.ok(item.schema&&item.scope&&item.source&&item.effect&&item.limitation&&item.reset&&item.acceptanceCaseIds.includes('LS-TEST-105'));if(item.enabled)assert.ok(item.default>=item.minimum&&item.default<=item.maximum);}
 assert.equal((await request(path+'/configurations',{preset:'balanced',controls:{decay:0.9},idempotencyKey:randomUUID()})).status,422);assert.equal((await request(path+'/configurations',{preset:'balanced',controls:null,idempotencyKey:randomUUID()})).status,422);
 const create=async(name:string,controls:Record<string,number>)=>(await api(path+'/configurations',{name,preset:'balanced',controls,idempotencyKey:randomUUID()})).configuration;
 const first=await create('Brief',{verbosity:0,callbackFrequency:0}),stale=await create('Concurrent',{verbosity:1});const activate=(configuration:Record<string,any>,key=randomUUID())=>request(path+`/configurations/${configuration.configurationId}/activate`,{expectedRevision:configuration.revision,idempotencyKey:key});assert.equal((await activate(first)).status,200);assert.equal((await activate(stale)).status,409);assert.equal((await api(path+`/configurations/${stale.configurationId}/preview`)).basisCurrent,false);
 const next=await create('Detailed',{verbosity:1,callbackFrequency:1});const db=new DatabaseSync(config.storage.databasePath);t.after(()=>db.close());db.exec(`CREATE TRIGGER test_configuration_failure BEFORE UPDATE ON assistant_relationship_configurations WHEN NEW.configuration_id='${next.configurationId}' AND json_extract(NEW.payload_json,'$.status')='active' BEGIN SELECT RAISE(ABORT,'synthetic transaction failure'); END;`);const key=randomUUID();assert.equal((await activate(next,key)).status,500);assert.equal((await api(path+'/configurations')).configurations.find((item:Record<string,any>)=>item.status==='active').configurationId,first.configurationId);const persisted=db.prepare("SELECT configuration_id AS id FROM assistant_relationship_configurations WHERE json_extract(payload_json,'$.status')='active'").all();assert.deepEqual(persisted.map(row=>row.id),[first.configurationId]);db.exec('DROP TRIGGER test_configuration_failure');assert.equal((await activate(next,key)).status,200);
 const body={assistantId:assistant.assistantId,relationshipId:relationship.relationshipId,userInput:'Give a concrete cache example.',inspect:true,fullPromptPreview:true};const observed=await request('/api/runtime/v1/messages',body);const stream=await observed.text();assert.match(stream,/event: input.inspection/u);assert.match(stream,/event: input.prompt-preview/u);assert.match(stream,/Silver Meadow/u);assert.match(stream,/Explain relevant reasoning and practical detail at greater length/u);assert.match(stream,/interaction.completed/u);assert.match(stream,/Fixture response/u);assert.doesNotMatch(await (await request('/api/runtime/v1/messages',{...body,inspect:false,fullPromptPreview:false})).text(),/input.inspection|input.prompt-preview/u);
 assert.equal((await request('/api/runtime/v1/messages',body,{'x-lifestream-csrf':'wrong'})).status,403);
 const reset=(await api(path+'/configurations',{action:'reset',idempotencyKey:randomUUID()})).configuration;assert.equal(reset.status,'draft');assert.equal(reset.controls.verbosity,0.5);assert.equal((await api(path+'/configurations')).configurations.find((item:Record<string,any>)=>item.status==='active').configurationId,next.configurationId);
 const rollback=(await api(path+`/configurations/${first.configurationId}/rollback`,{expectedRevision:first.revision,idempotencyKey:randomUUID()})).configuration;assert.equal(rollback.status,'draft');assert.equal(rollback.controls.verbosity,0);assert.equal((await activate(rollback)).status,200);assert.equal((await activate(reset)).status,409);
 now+=1800001;assert.equal((await request('/api/runtime/v1/messages',body)).status,401);assert.equal((await request('/api/runtime/v1/messages',{assistantId:assistant.assistantId,userInput:'Continue ordinary conversation.'})).status,200);
});
