import assert from "node:assert/strict";
import {test} from "node:test";
import {randomUUID,randomBytes} from "node:crypto";
import {mkdtemp,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {analyzeRelationship,reviewInsight,type InsightSource} from "../src/admin/relationship-insights.ts";
import {createLifestreamServer} from "../src/index.ts";
import {loadProfile} from "../src/config/loader.ts";

test("insight findings distinguish correlated duplicates, explicit contrary evidence and insufficient inference",()=>{
 const record={candidateId:'one',content:'Use short replies',revision:2,status:'approved' as const,source:'authored',sourceFamily:'family',uncertainty:'high' as const};const source:InsightSource={relationshipId:'relationship',revision:3,candidates:[record,{...record,candidateId:'two'}]};let findings=analyzeRelationship(source,null);assert.equal(findings.length,5);assert.deepEqual(findings[0]!.counterEvidenceIds,[]);assert.match(findings[0]!.observation,/2 approved records across 1 attributed families/);assert.match(findings[3]!.observation,/1 exact normalized duplicate groups/);assert.equal(findings[1]!.proposedControls,undefined);assert.match(findings[4]!.observation,/no purpose-specific training consent/);
 source.candidates[0]!.conflicts=[{recordId:'two',status:'retained'}];source.candidates[1]!.conflicts=[{recordId:'one',status:'retained'}];source.candidates[1]!.content='Use long replies';source.revision++;
 findings=analyzeRelationship(source,null);assert.deepEqual(new Set(findings[0]!.counterEvidenceIds),new Set(['one','two']));assert.match(findings[0]!.observation,/2 records retain contradictions/);assert.match(findings[3]!.observation,/0 exact normalized duplicate groups/);
 const proposal=findings[0]!;source.revision++;assert.throws(()=>reviewInsight(proposal,source,null,'accepted',1),/conflict/);assert.equal(reviewInsight(proposal,source,null,'rejected',1).status,'rejected');
});

test("real-authenticated insight jobs pin sources, separate feedback and prepare reversible activation drafts",async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-insight-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex'),options={config,localAuth:{stateDirectory:join(root,'safety'),installerToken}};let app=createLifestreamServer(options);await app.start();t.after(()=>app.shutdown());let base=`http://127.0.0.1:${app.address().port}`;const headers:Record<string,string>={'content-type':'application/json',origin:base},password=randomBytes(32).toString('hex');
 const request=(path:string,body?:unknown)=>fetch(base+path,{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:JSON.stringify(body)})}),api=async(path:string,body?:unknown)=>{const response=await request(path,body),result=await response.json() as Record<string,any>;assert.ok(response.ok,JSON.stringify(result));return result;};
 const setup=await request('/api/auth/v1/setup',{username:'owner',password,installerToken});headers.cookie=setup.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=((await setup.json()) as any).session.csrfToken;const assistant=await api('/api/admin/v1/assistants',{displayName:'Insight Assistant'}),rel=(await api(`/api/admin/v1/assistants/${assistant.assistantId}/relationships`,{})).relationship,path=`/api/admin/v1/assistants/${assistant.assistantId}/relationships/${rel.relationshipId}`;
 const candidate=(await api(path+'/candidates',{content:'Use concise explanations',source:'authored',sourceFamily:'one',uncertainty:'high',expectedRevision:1,idempotencyKey:randomUUID()})).candidate;await api(path+`/candidates/${candidate.candidateId}/decision`,{decision:'approved',expectedRevision:2,idempotencyKey:randomUUID()});
 assert.equal((await request(path+'/feedback',{targetId:candidate.candidateId,kind:'style',value:'preferBrief'})).status,409);const feedback=(await api(path+'/feedback',{targetId:candidate.candidateId,expectedTargetRevision:2,kind:'style',value:'preferBrief'})).feedback;assert.equal(feedback.independentSupport,false);
 const run=async()=>{await api(path+'/insights',{});for(let n=0;n<30;n++){const state=await api(path+'/insights');if(state.job.status!=='queued'){assert.equal(state.job.status,'completed');return state;}await new Promise(r=>setTimeout(r,5));}throw new Error('analysis did not complete');};let state=await run();const insight=state.insights.find((i:any)=>i.lens==='communicationFit');assert.equal(insight.proposedControls.verbosity,0);assert.deepEqual((await api(path+'/configurations')).configurations,[]);
 const reviewed=await api(path+`/insights/${insight.insightId}/decision`,{decision:'accepted',expectedRevision:1}),draft=reviewed.configuration;assert.equal(draft.status,'draft');assert.equal(reviewed.activeStateChanged,false);await api(path+`/configurations/${draft.configurationId}/activate`,{expectedRevision:draft.revision,idempotencyKey:randomUUID()});
 const reversed=await api(path+`/insights/${insight.insightId}/decision`,{decision:'reversed',expectedRevision:2});assert.equal(reversed.configuration.status,'draft');assert.equal((await api(path+'/configurations')).configurations.find((c:any)=>c.status==='active').configurationId,draft.configurationId);await api(path+`/configurations/${reversed.configuration.configurationId}/activate`,{expectedRevision:reversed.configuration.revision,idempotencyKey:randomUUID()});assert.equal((await api(path+'/configurations')).configurations.find((c:any)=>c.status==='active').controls.verbosity,0.5);
 state=await run();const newest=state.insights.filter((i:any)=>i.lens==='communicationFit').at(-1);await api(path+`/feedback/${feedback.feedbackId}/reverse`,{});assert.equal((await request(path+`/insights/${newest.insightId}/decision`,{decision:'accepted',expectedRevision:1})).status,409);
 let pending:(()=>void)|undefined;const realImmediate=globalThis.setImmediate;const immediate=t.mock.method(globalThis,'setImmediate',((callback:()=>void)=>{if(!String(callback).includes("analyzeRelationship"))return realImmediate(callback);pending=callback;return {} as NodeJS.Immediate;}) as typeof setImmediate);
 const queued=await api(path+'/insights',{});await api(path+'/insights/cancel',{expectedRevision:queued.job.revision});immediate.mock.restore();pending!();assert.equal((await api(path+'/insights')).job.status,'cancelled');
 const hold=t.mock.method(globalThis,'setImmediate',((callback:()=>void)=>{if(!String(callback).includes("analyzeRelationship"))return realImmediate(callback);pending=callback;return {} as NodeJS.Immediate;}) as typeof setImmediate);await api(path+'/insights',{});await api(path+'/feedback',{targetId:candidate.candidateId,expectedTargetRevision:2,kind:'helpfulness',value:'useful'});hold.mock.restore();pending!();assert.equal((await api(path+'/insights')).job.status,'failed');
 const restartHold=t.mock.method(globalThis,'setImmediate',((callback:()=>void)=>{if(!String(callback).includes("analyzeRelationship"))return realImmediate(callback);pending=callback;return {} as NodeJS.Immediate;}) as typeof setImmediate);await api(path+'/insights',{});restartHold.mock.restore();await app.shutdown();app=createLifestreamServer(options);await app.start();base=`http://127.0.0.1:${app.address().port}`;headers.origin=base;const login=await request('/api/auth/v1/sign-in',{username:'owner',password});headers.cookie=login.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=((await login.json()) as any).session.csrfToken;state=await api(path+'/insights');assert.equal(state.job.status,'failed');assert.match(state.job.failure,/Restart interrupted/);assert.equal(state.insights.find((i:any)=>i.insightId===insight.insightId).status,'reversed');
});
