import assert from 'node:assert/strict';
import {test} from 'node:test';
import {randomUUID,randomBytes} from 'node:crypto';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createLifestreamServer} from '../src/index.ts';
import {loadProfile} from '../src/config/loader.ts';

test('readiness binds real authentication, source consent, split lineage, review, revocation and restart',async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-lab-api-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex'),password=randomBytes(32).toString('hex'),options={config,localAuth:{stateDirectory:join(root,'safety'),installerToken}};let app=createLifestreamServer(options);await app.start();t.after(()=>app.shutdown());let base=`http://127.0.0.1:${app.address().port}`;const headers:Record<string,string>={origin:base,'content-type':'application/json'},request=(path:string,body?:unknown)=>fetch(base+path,{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:JSON.stringify(body)})}),api=async(path:string,body?:unknown)=>{const r=await request(path,body),result=await r.json() as Record<string,any>;assert.ok(r.ok,JSON.stringify(result));return result;};
 const setup=await request('/api/auth/v1/setup',{username:'owner',password,installerToken});headers.cookie=setup.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=((await setup.json()) as any).session.csrfToken;const assistant=await api('/api/admin/v1/assistants',{displayName:'Lab Assistant'});await api(`/api/admin/v1/assistants/${assistant.assistantId}/activate`,{profileId:assistant.profile.profileId,expectedActiveRevision:null});await api('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'});const relationship=(await api(`/api/admin/v1/assistants/${assistant.assistantId}/relationships`,{})).relationship,path=`/api/admin/v1/assistants/${assistant.assistantId}/relationships/${relationship.relationshipId}`,readinessPath=path+'/readiness';

 const ids:string[]=[];for(let n=0;n<3;n++){const rel=(await api(path)).relationship,c=(await api(path+'/candidates',{content:`Synthetic source ${n}`,source:'synthetic-authored',sourceFamily:`independent-family-${n}`,uncertainty:'low',expectedRevision:rel.revision,idempotencyKey:randomUUID()})).candidate;const current=(await api(path)).relationship;await api(path+`/candidates/${c.candidateId}/decision`,{decision:'approved',expectedRevision:current.revision,idempotencyKey:randomUUID()});ids.push(c.candidateId);}
 const post=async(action:string,body:Record<string,unknown>)=>api(readinessPath+'/'+action,{expectedRevision:(await api(readinessPath)).relationshipRevision,idempotencyKey:randomUUID(),...body});
 assert.equal((await request(readinessPath+'/consent',{expectedRevision:(await api(readinessPath)).relationshipRevision,idempotencyKey:randomUUID(),sourceRefs:ids.map(id=>`${id}:2`),purpose:'personalization',approve:true,syntheticOnly:true})).status,409);
 const consent=(await post('consent',{sourceRefs:ids.map(id=>`${id}:2`),purpose:'trainingDataset',approve:true,syntheticOnly:true})).consent;
 const members=ids.map((recordId,n)=>({recordId,revision:3,split:['train','validation','test'][n]}));const dataset=(await post('dataset',{syntheticOnly:true,members})).dataset;assert.equal(dataset.records.length,3);assert.equal((await api(readinessPath+'/datasets/'+dataset.datasetId)).dataset.digest,dataset.digest);
 const behavioral=(await post('register-fixture',{syntheticOnly:true,datasetId:dataset.datasetId,kind:'behavioral'})).artifact,concrete=(await post('register-fixture',{syntheticOnly:true,datasetId:dataset.datasetId,kind:'concreteFactHypothesis'})).artifact;assert.ok(concrete.evaluations.some((e:string)=>e.includes('hallucinated-extensions')));assert.equal(behavioral.trainingSettings.executed,false);await post('approve-fixture',{syntheticOnly:true,artifactId:concrete.artifactId,artifactRevision:'1',registryRevision:(await api(readinessPath)).registry.revision});
 const routeBody={artifactId:behavioral.artifactId,artifactRevision:'1',syntheticOnly:true};assert.equal((await api(readinessPath+'/simulate-route',routeBody)).route,'fallback');await post('approve-fixture',{syntheticOnly:true,artifactId:behavioral.artifactId,artifactRevision:'1',registryRevision:(await api(readinessPath)).registry.revision});assert.equal((await api(readinessPath+'/simulate-route',routeBody)).route,'adapter');const actual=await api(readinessPath+'/route',routeBody);assert.equal(actual.route,'fallback');assert.equal(actual.weightsLoaded,false);const comparison=(await post('compare-fixtures',{syntheticOnly:true,datasetId:dataset.datasetId})).comparison;assert.equal(comparison.learnedQuality,'notEvaluated');assert.equal(comparison.checks.filter((c:any)=>c.route==='adapter').length,2);assert.equal(comparison.checks.filter((c:any)=>c.route==='fallback').length,4);
 await app.shutdown();app=createLifestreamServer(options);await app.start();base=`http://127.0.0.1:${app.address().port}`;headers.origin=base;const login=await request('/api/auth/v1/sign-in',{username:'owner',password});headers.cookie=login.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=((await login.json()) as any).session.csrfToken;assert.equal((await api(readinessPath)).registry.artifacts.length,2);
 await post('revoke-consent',{consentId:consent.consentId,consentRevision:1});assert.equal((await api(readinessPath)).registry.artifacts[0].status,'quarantined');assert.equal((await request(readinessPath+'/datasets/'+dataset.datasetId)).status,409);assert.equal((await api(readinessPath+'/simulate-route',routeBody)).route,'fallback');assert.match(await (await request('/api/runtime/v1/messages',{assistantId:assistant.assistantId,userInput:'Hello after consent revocation'})).text(),/interaction.completed/);
 const consent2=(await post('consent',{sourceRefs:ids.map(id=>`${id}:3`),purpose:'trainingDataset',approve:true,syntheticOnly:true})).consent;assert.equal(consent2.status,'approved');const second=(await post('dataset',{syntheticOnly:true,members:members.map(m=>({...m,revision:4}))})).dataset;const rel=(await api(path)).relationship;await api(path+`/records/${ids[0]}/operations`,{operation:'annotate',text:'Changed source review',expectedRevision:rel.revision,expectedRecordRevision:4,idempotencyKey:randomUUID()});assert.equal((await request(readinessPath+'/datasets/'+second.datasetId)).status,409);
 const other=await api('/api/admin/v1/assistants',{displayName:'Other'}),otherRel=(await api(`/api/admin/v1/assistants/${other.assistantId}/relationships`,{})).relationship;assert.equal((await request(`/api/admin/v1/assistants/${other.assistantId}/relationships/${otherRel.relationshipId}/readiness/datasets/${dataset.datasetId}`)).status,409);
});
