import assert from 'node:assert/strict';
import {test} from 'node:test';
import {randomUUID,randomBytes} from 'node:crypto';
import {mkdtemp,rm,copyFile,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createLifestreamServer} from '../src/index.ts';
import {DatabaseSync} from 'node:sqlite';
import {FixtureInferenceProvider} from '@lifestream/runtime/inference/fixture';
import {loadProfile} from '../src/config/loader.ts';

test('joined forgetting removes derived payload, fences late Lab/replay/import, and applies current tombstones after old database restore',async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-lab-api-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex'),password=randomBytes(32).toString('hex'),options={config,localAuth:{stateDirectory:join(root,'safety'),installerToken}};let app=createLifestreamServer(options);await app.start();t.after(()=>app.shutdown());let base=`http://127.0.0.1:${app.address().port}`;const headers:Record<string,string>={origin:base,'content-type':'application/json'},request=(path:string,body?:unknown)=>fetch(base+path,{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:JSON.stringify(body)})}),api=async(path:string,body?:unknown)=>{const r=await request(path,body),result=await r.json() as Record<string,any>;assert.ok(r.ok,JSON.stringify(result));return result;};
 const setup=await request('/api/auth/v1/setup',{username:'owner',password,installerToken});headers.cookie=setup.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=((await setup.json()) as any).session.csrfToken;const assistant=await api('/api/admin/v1/assistants',{displayName:'Lab Assistant'});await api(`/api/admin/v1/assistants/${assistant.assistantId}/activate`,{profileId:assistant.profile.profileId,expectedActiveRevision:null});await api('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'});const relationship=(await api(`/api/admin/v1/assistants/${assistant.assistantId}/relationships`,{})).relationship,path=`/api/admin/v1/assistants/${assistant.assistantId}/relationships/${relationship.relationshipId}`,readinessPath=path+'/readiness';


 const marker='SYNTHETIC_AMBER_SECRET',ids:string[]=[],creationKeys:string[]=[];
 for(let n=0;n<3;n++){const rel=(await api(path)).relationship,key=randomUUID();creationKeys.push(key);const c=(await api(path+'/candidates',{content:n===0?`The synthetic project is ${marker}.`:`Independent safe synthetic preference ${n}`,contextUse:'baseline',source:'synthetic-authored',sourceFamily:`independent-family-${n}`,uncertainty:'low',expectedRevision:rel.revision,idempotencyKey:key})).candidate;const current=(await api(path)).relationship;await api(path+`/candidates/${c.candidateId}/decision`,{decision:'approved',expectedRevision:current.revision,idempotencyKey:randomUUID()});ids.push(c.candidateId);}
 const readyPost=async(action:string,body:Record<string,unknown>)=>api(readinessPath+'/'+action,{expectedRevision:(await api(readinessPath)).relationshipRevision,idempotencyKey:randomUUID(),...body});await readyPost('consent',{sourceRefs:ids.map(id=>`${id}:2`),purpose:'trainingDataset',approve:true,syntheticOnly:true});const dataset=(await readyPost('dataset',{syntheticOnly:true,members:ids.map((recordId,n)=>({recordId,revision:3,split:['train','validation','test'][n]}))})).dataset;const artifact=(await readyPost('register-fixture',{syntheticOnly:true,datasetId:dataset.datasetId,kind:'behavioral'})).artifact;await readyPost('approve-fixture',{syntheticOnly:true,artifactId:artifact.artifactId,artifactRevision:'1',registryRevision:(await api(readinessPath)).registry.revision});
 const memoryId=randomUUID();await api(`/api/admin/v1/assistants/${assistant.assistantId}/memories/import`,{dataScope:'assistant-memories',assistantId:assistant.assistantId,memories:[{id:memoryId,assistantId:assistant.assistantId,content:`Summary ${marker}`,provenance:{sourceId:ids[0]},lifecycle:{status:'candidate',revision:1},createdAt:new Date().toISOString()}]});await api(`/api/admin/v1/assistants/${assistant.assistantId}/memories/${memoryId}/lifecycle`,{status:'active',expectedRevision:1});await api(`/api/admin/v1/assistants/${assistant.assistantId}/memories/${memoryId}/correction`,{content:`Pending correction ${marker}`});
 const profile=(await api('/api/admin/v1/people/me',{expectedActiveRevision:null,declarations:[{key:'project',value:marker,sensitivity:'personal'}],assistantScopes:[{assistantId:assistant.assistantId,purposes:['conversation','personalization','mention'],audiences:['authenticatedSession'],allowedKeys:['project']}]})).profile;await api('/api/admin/v1/people/me/activate',{profileId:profile.profileId,expectedRevision:profile.revision,expectedActiveRevision:null});
 const db=new DatabaseSync(config.storage.databasePath);t.after(()=>{try{db.close();}catch{}});const linked={...profile,status:'active',sourceRefs:[ids[0]]};db.prepare('UPDATE user_profile_revisions SET payload_json=? WHERE profile_id=?').run(JSON.stringify(linked),profile.profileId);db.prepare('INSERT INTO prepared_context VALUES (?,?,?,?,?)').run('synthetic-cache',assistant.assistantId,'old',JSON.stringify({content:marker}),new Date(Date.now()+100000).toISOString());
 await api(path+'/insights',{});for(let n=0;n<100&&(await api(path+'/insights')).job.status==='queued';n++)await new Promise(r=>setTimeout(r,5));
 const lab=(await api(path+'/lab',{syntheticOnly:true,transmissionApproved:true,scenarios:[{id:'comparison',prompt:'What is the synthetic project?',sourceFamily:'comparison',split:'comparison',forbiddenTerms:[]},{id:'held',prompt:'Explain a cache.',sourceFamily:'held',split:'heldOut',forbiddenTerms:[]}],criteria:['nonempty','noForbiddenTerms'],repeatedRuns:2,candidateControls:{verbosity:0},candidateRepresentation:'conventionOriented'})).lab;
 const original=FixtureInferenceProvider.prototype.generate;let entered=false,release:()=>void=()=>{};const gate=new Promise<void>(resolve=>{release=resolve;});t.mock.method(FixtureInferenceProvider.prototype,'generate',async function*(this:FixtureInferenceProvider,input,context){if(input.scope.sessionId.startsWith('lab:')){entered=true;await gate;}yield* original.call(this,input,context);});await api(path+'/lab/run',{expectedRevision:lab.revision});for(let n=0;n<100&&!entered;n++)await new Promise(r=>setTimeout(r,5));assert.equal(entered,true);
 const backup=join(root,'old.sqlite');db.exec(`VACUUM INTO '${backup}'`);const oldRelationship=(await api(path)).relationship,privacyKey=randomUUID(),forget={action:'forget-derived-information',expectedRevision:oldRelationship.revision,idempotencyKey:privacyKey,targets:[{kind:'record',id:ids[0],revision:3}]};const response=await api(path+'/privacy',forget);assert.equal(response.receipt.status,'completed');assert.ok(response.receipt.artifacts.some((a:any)=>a.owner==='native-memory'));assert.ok(response.receipt.artifacts.some((a:any)=>a.owner==='user-profile'));assert.ok(response.receipt.artifacts.some((a:any)=>a.owner==='dataset'));release();await new Promise(r=>setTimeout(r,30));
 const verify=async()=>{const rel=(await api(path)).relationship;assert.equal(rel.candidates.find((c:any)=>c.candidateId===ids[0]).content,'');assert.match(rel.candidates.find((c:any)=>c.candidateId===ids[1]).content,/safe synthetic/);assert.equal(rel.lab.status,'cancelled');assert.equal(rel.lab.comparison,undefined);assert.equal((await api(readinessPath)).registry.artifacts[0].status,'quarantined');assert.equal((await request(readinessPath+'/datasets/'+dataset.datasetId)).status,409);assert.doesNotMatch(JSON.stringify([rel,(await api('/api/admin/v1/people/me')).profiles,(await api(`/api/admin/v1/assistants/${assistant.assistantId}/memories`)).memories,(await api(`/api/admin/v1/assistants/${assistant.assistantId}/memories/${memoryId}/history`)).history]),new RegExp(marker));assert.equal((await request(path+'/candidates',{idempotencyKey:creationKeys[0]})).status,409);assert.equal((await request(path+'/candidates',{content:`The synthetic project is ${marker}.`,source:'old-export',sourceFamily:'renamed',uncertainty:'low',expectedRevision:rel.revision,idempotencyKey:randomUUID()})).status,409);assert.match(await (await request('/api/runtime/v1/messages',{assistantId:assistant.assistantId,userInput:'Hello after forgetting'})).text(),/interaction.completed/);};await verify();assert.equal((await api(path+'/privacy',forget)).receipt.operationId,response.receipt.operationId);
 await app.shutdown();db.close();await copyFile(backup,config.storage.databasePath);app=createLifestreamServer(options);await app.start();base=`http://127.0.0.1:${app.address().port}`;headers.origin=base;const login=await request('/api/auth/v1/sign-in',{username:'owner',password});headers.cookie=login.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=((await login.json()) as any).session.csrfToken;await verify();const journal=await readFile(join(root,'safety','relationship-recovery','journal.json'),'utf8');assert.doesNotMatch(journal,new RegExp(marker));
});

test('privacy operations preserve separate purposes and failed cleanup withholds use until retry; unknown safety currency does not replay data',async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-lab-api-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex'),password=randomBytes(32).toString('hex'),options={config,localAuth:{stateDirectory:join(root,'safety'),installerToken}};let app=createLifestreamServer(options);await app.start();t.after(()=>app.shutdown());let base=`http://127.0.0.1:${app.address().port}`;const headers:Record<string,string>={origin:base,'content-type':'application/json'},request=(path:string,body?:unknown)=>fetch(base+path,{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:JSON.stringify(body)})}),api=async(path:string,body?:unknown)=>{const r=await request(path,body),result=await r.json() as Record<string,any>;assert.ok(r.ok,JSON.stringify(result));return result;};
 const setup=await request('/api/auth/v1/setup',{username:'owner',password,installerToken});headers.cookie=setup.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=((await setup.json()) as any).session.csrfToken;const assistant=await api('/api/admin/v1/assistants',{displayName:'Lab Assistant'});await api(`/api/admin/v1/assistants/${assistant.assistantId}/activate`,{profileId:assistant.profile.profileId,expectedActiveRevision:null});await api('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'});const relationship=(await api(`/api/admin/v1/assistants/${assistant.assistantId}/relationships`,{})).relationship,path=`/api/admin/v1/assistants/${assistant.assistantId}/relationships/${relationship.relationshipId}`,readinessPath=path+'/readiness';


 const add=async(content:string)=>{let rel=(await api(path)).relationship;const c=(await api(path+'/candidates',{content,contextUse:'baseline',source:'synthetic',sourceFamily:randomUUID(),uncertainty:'low',expectedRevision:rel.revision,idempotencyKey:randomUUID()})).candidate;rel=(await api(path)).relationship;await api(path+`/candidates/${c.candidateId}/decision`,{decision:'approved',expectedRevision:rel.revision,idempotencyKey:randomUUID()});return c.candidateId;};
 const privacy=async(action:string,id?:string)=>{const rel=(await api(path)).relationship,record=rel.candidates.find((r:any)=>r.candidateId===id);return api(path+'/privacy',{action,expectedRevision:rel.revision,idempotencyKey:randomUUID(),targets:id?[{kind:'record',id,revision:record.revision}]:[]});};
 const personalization=await add('Use the synthetic Silver Marsh example.'),training=await add('Use the synthetic Copper Ridge example.'),processing=await add('Use the synthetic Violet Hill example.');
 await privacy('stop-personalization',personalization);let rel=(await api(path)).relationship;assert.match(rel.candidates.find((r:any)=>r.candidateId===personalization).content,/Silver Marsh/);assert.equal(rel.candidates.find((r:any)=>r.candidateId===personalization).processingRevoked,undefined);
 await privacy('prohibit-training',training);rel=(await api(path)).relationship;assert.equal(rel.candidates.find((r:any)=>r.candidateId===training).suppressed,undefined);assert.equal(rel.candidates.find((r:any)=>r.candidateId===training).trainingExcluded,true);assert.equal((await request(readinessPath+'/consent',{expectedRevision:rel.revision,idempotencyKey:randomUUID(),purpose:'trainingDataset',approve:true,syntheticOnly:true,sourceRefs:[`${training}:${rel.candidates.find((r:any)=>r.candidateId===training).revision}`]})).status,409);
 await privacy('revoke-processing',processing);rel=(await api(path)).relationship;assert.match(rel.candidates.find((r:any)=>r.candidateId===processing).content,/Violet Hill/);assert.equal(rel.candidates.find((r:any)=>r.candidateId===processing).processingRevoked,true);const view=await api(path+'/effective-context');assert.ok(view.approvedBaseline.some((r:any)=>r.id===training));assert.ok(!view.approvedBaseline.some((r:any)=>r.id===processing||r.id===personalization));
 const source=await add('SYNTHETIC_DELETION_SOURCE'),splitState=(await api(path)).relationship;const split=(await api(path+`/records/${source}/operations`,{operation:'split',contents:['SYNTHETIC_DERIVED_ONE','SYNTHETIC_DERIVED_TWO'],expectedRevision:splitState.revision,expectedRecordRevision:2,idempotencyKey:randomUUID()})).relationship;const derivatives=split.candidates.filter((r:any)=>r.derivedFrom?.includes(source));await privacy('delete-source',source);rel=(await api(path)).relationship;assert.equal(rel.candidates.find((r:any)=>r.candidateId===source).content,'');assert.ok(derivatives.every((d:any)=>rel.candidates.find((r:any)=>r.candidateId===d.candidateId).content.startsWith('SYNTHETIC_DERIVED')));assert.ok(derivatives.every((d:any)=>rel.candidates.find((r:any)=>r.candidateId===d.candidateId).processingRevoked));await privacy('forget-derived-information',source);rel=(await api(path)).relationship;assert.ok(derivatives.every((d:any)=>rel.candidates.find((r:any)=>r.candidateId===d.candidateId).content===''));
 const files=[{name:'synthetic.txt',format:'notes-v1',content:'A bounded synthetic selected source.',authoredBy:'user',ownedBySubject:true}],job=(await api(path+'/profile-builder',{files})).job;await api(path+`/profile-builder/${job.jobId}/snapshot`,{files,expectedRevision:job.revision});await privacy('stop-collection');const cancelled=(await api(path+`/profile-builder/${job.jobId}`)).job;assert.equal(cancelled.status,'cancelled');assert.equal((await request(path+`/profile-builder/${job.jobId}/extract`,{expectedRevision:cancelled.revision})).status,409);
 const doomed=await add('SYNTHETIC_FAILED_CLEANUP_MARKER'),db=new DatabaseSync(config.storage.databasePath);const before=(await api(path)).relationship,body={action:'forget-derived-information',expectedRevision:before.revision,idempotencyKey:randomUUID(),targets:[{kind:'record',id:doomed,revision:2}]};db.exec("CREATE TRIGGER fail_privacy BEFORE UPDATE ON assistant_relationships BEGIN SELECT RAISE(FAIL,'synthetic cleanup failure'); END");const failed=await request(path+'/privacy',body);assert.equal(failed.status,202);assert.equal(((await failed.json()) as any).receipt.retryRequired,true);assert.equal((await request(path)).status,503);const text=await (await request('/api/runtime/v1/messages',{assistantId:assistant.assistantId,userInput:'Hello during cleanup failure'})).text();assert.match(text,/interaction.completed/);assert.doesNotMatch(text,/SYNTHETIC_FAILED_CLEANUP_MARKER/);db.exec('DROP TRIGGER fail_privacy');assert.equal((await api(path+'/privacy',body)).receipt.status,'completed');db.close();
 await app.shutdown();await rm(join(root,'safety','relationship-recovery','journal.json'));app=createLifestreamServer(options);await app.start();base=`http://127.0.0.1:${app.address().port}`;headers.origin=base;const login=await request('/api/auth/v1/sign-in',{username:'owner',password});headers.cookie=login.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=((await login.json()) as any).session.csrfToken;assert.equal((await api(path+'/privacy')).currency,'unknown');assert.equal((await request(path)).status,503);assert.equal((await request('/api/admin/v1/people/me')).status,503);const safe=await (await request('/api/runtime/v1/messages',{assistantId:assistant.assistantId,userInput:'Hello with unavailable safety currency'})).text();assert.match(safe,/interaction.completed/);assert.doesNotMatch(safe,/Silver Marsh|Copper Ridge|Violet Hill|FAILED_CLEANUP/);
});

test('accepted record and native corrections plus User Profile revocation cannot revive through an older database restore',async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-lab-api-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex'),password=randomBytes(32).toString('hex'),options={config,localAuth:{stateDirectory:join(root,'safety'),installerToken}};let app=createLifestreamServer(options);await app.start();t.after(()=>app.shutdown());let base=`http://127.0.0.1:${app.address().port}`;const headers:Record<string,string>={origin:base,'content-type':'application/json'},request=(path:string,body?:unknown)=>fetch(base+path,{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:JSON.stringify(body)})}),api=async(path:string,body?:unknown)=>{const r=await request(path,body),result=await r.json() as Record<string,any>;assert.ok(r.ok,JSON.stringify(result));return result;};
 const setup=await request('/api/auth/v1/setup',{username:'owner',password,installerToken});headers.cookie=setup.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=((await setup.json()) as any).session.csrfToken;const assistant=await api('/api/admin/v1/assistants',{displayName:'Lab Assistant'});await api(`/api/admin/v1/assistants/${assistant.assistantId}/activate`,{profileId:assistant.profile.profileId,expectedActiveRevision:null});await api('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'});const relationship=(await api(`/api/admin/v1/assistants/${assistant.assistantId}/relationships`,{})).relationship,path=`/api/admin/v1/assistants/${assistant.assistantId}/relationships/${relationship.relationshipId}`,readinessPath=path+'/readiness';


 const candidate=(await api(path+'/candidates',{content:'The synthetic project is Old Amber.',contextUse:'baseline',source:'synthetic',sourceFamily:'one',uncertainty:'low',expectedRevision:1,idempotencyKey:randomUUID()})).candidate;await api(path+`/candidates/${candidate.candidateId}/decision`,{decision:'approved',expectedRevision:2,idempotencyKey:randomUUID()});const memory=(await api(`/api/admin/v1/assistants/${assistant.assistantId}/memories`,{content:'The synthetic memory is Old Birch.'})).memory;await api(`/api/admin/v1/assistants/${assistant.assistantId}/memories/${memory.id}/lifecycle`,{status:'active',expectedRevision:1});const proposal=(await api(`/api/admin/v1/assistants/${assistant.assistantId}/memories/${memory.id}/correction`,{content:'The synthetic memory is New Birch.'})).event;
 const profile=(await api('/api/admin/v1/people/me',{expectedActiveRevision:null,declarations:[{key:'project',value:'Old Cedar',sensitivity:'personal'}],assistantScopes:[{assistantId:assistant.assistantId,purposes:['conversation','personalization','mention'],audiences:['authenticatedSession'],allowedKeys:['project']}]})).profile;await api('/api/admin/v1/people/me/activate',{profileId:profile.profileId,expectedRevision:profile.revision,expectedActiveRevision:null});const db=new DatabaseSync(config.storage.databasePath),backup=join(root,'before-corrections.sqlite');db.exec(`VACUUM INTO '${backup}'`);db.close();
 let rel=(await api(path)).relationship;await api(path+`/records/${candidate.candidateId}/operations`,{operation:'correct',content:'The synthetic project is New Amber.',expectedRevision:rel.revision,expectedRecordRevision:2,idempotencyKey:randomUUID()});await api(`/api/admin/v1/assistants/${assistant.assistantId}/memories/${memory.id}/correction`,{applyRevision:proposal.revision,expectedRevision:2});await api('/api/admin/v1/people/me/revoke',{profileId:profile.profileId,expectedRevision:profile.revision,expectedActiveRevision:profile.revision});const current=await api(path+'/effective-request',{userInput:'What is the synthetic project and memory?'});assert.doesNotMatch(JSON.stringify(current.preparedRequest),/Old Amber|Old Birch|Old Cedar/);
 await app.shutdown();await copyFile(backup,config.storage.databasePath);app=createLifestreamServer(options);await app.start();base=`http://127.0.0.1:${app.address().port}`;headers.origin=base;const login=await request('/api/auth/v1/sign-in',{username:'owner',password});headers.cookie=login.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=((await login.json()) as any).session.csrfToken;rel=(await api(path)).relationship;assert.equal(rel.candidates[0].processingRevoked,true);assert.equal((await api('/api/admin/v1/people/me')).profiles[0].status,'revoked');assert.equal((await request(`/api/admin/v1/assistants/${assistant.assistantId}/memories/${memory.id}/correction`,{applyRevision:proposal.revision,expectedRevision:2})).status,409);const reply=await (await request('/api/runtime/v1/messages',{assistantId:assistant.assistantId,userInput:'What is the synthetic project and memory?'})).text();assert.match(reply,/interaction.completed/);assert.doesNotMatch(reply,/Old Amber|Old Birch|Old Cedar/);
});

test('forgetting a shared User Profile purges dependent Lab payloads across only its owned Assistant relationships',async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-lab-api-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex'),password=randomBytes(32).toString('hex'),options={config,localAuth:{stateDirectory:join(root,'safety'),installerToken}};let app=createLifestreamServer(options);await app.start();t.after(()=>app.shutdown());let base=`http://127.0.0.1:${app.address().port}`;const headers:Record<string,string>={origin:base,'content-type':'application/json'},request=(path:string,body?:unknown)=>fetch(base+path,{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:JSON.stringify(body)})}),api=async(path:string,body?:unknown)=>{const r=await request(path,body),result=await r.json() as Record<string,any>;assert.ok(r.ok,JSON.stringify(result));return result;};
 const setup=await request('/api/auth/v1/setup',{username:'owner',password,installerToken});headers.cookie=setup.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=((await setup.json()) as any).session.csrfToken;const assistant=await api('/api/admin/v1/assistants',{displayName:'Lab Assistant'});await api(`/api/admin/v1/assistants/${assistant.assistantId}/activate`,{profileId:assistant.profile.profileId,expectedActiveRevision:null});await api('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'});const relationship=(await api(`/api/admin/v1/assistants/${assistant.assistantId}/relationships`,{})).relationship,path=`/api/admin/v1/assistants/${assistant.assistantId}/relationships/${relationship.relationshipId}`,readinessPath=path+'/readiness';


 const other=await api('/api/admin/v1/assistants',{displayName:'Other Owned Assistant'});await api(`/api/admin/v1/assistants/${other.assistantId}/activate`,{profileId:other.profile.profileId,expectedActiveRevision:null});const otherRel=(await api(`/api/admin/v1/assistants/${other.assistantId}/relationships`,{})).relationship,otherPath=`/api/admin/v1/assistants/${other.assistantId}/relationships/${otherRel.relationshipId}`,marker='SYNTHETIC_SHARED_PROFILE_MARKER';
 const profile=(await api('/api/admin/v1/people/me',{expectedActiveRevision:null,declarations:[{key:'project',value:marker,sensitivity:'personal'}],assistantScopes:[assistant.assistantId,other.assistantId].map(assistantId=>({assistantId,purposes:['conversation','personalization','mention'],audiences:['authenticatedSession'],allowedKeys:['project']}))})).profile;await api('/api/admin/v1/people/me/activate',{profileId:profile.profileId,expectedRevision:profile.revision,expectedActiveRevision:null});const input={syntheticOnly:true,transmissionApproved:true,scenarios:[{id:'one',prompt:'What project?',sourceFamily:'one',split:'comparison',forbiddenTerms:[]},{id:'two',prompt:'Explain a cache.',sourceFamily:'two',split:'heldOut',forbiddenTerms:[]}],criteria:['nonempty','noForbiddenTerms'],repeatedRuns:2,candidateControls:{verbosity:0},candidateRepresentation:'recordOriented'};for(const target of [path,otherPath]){const lab=(await api(target+'/lab',input)).lab;assert.match(JSON.stringify(lab.sourceSnapshot.records),new RegExp(marker));}const rel=(await api(path)).relationship;await api(path+'/privacy',{action:'forget-derived-information',expectedRevision:rel.revision,idempotencyKey:randomUUID(),targets:[{kind:'userProfile',id:profile.profileId,revision:profile.revision}]});for(const target of [path,otherPath]){const lab=(await api(target+'/lab')).lab;assert.equal(lab.status,'cancelled');assert.doesNotMatch(JSON.stringify(lab),new RegExp(marker));}assert.doesNotMatch(JSON.stringify((await api('/api/admin/v1/people/me')).profiles),new RegExp(marker));
});

test('forgotten selected-file intake cannot return through renamed or changed-container reimport',async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-lab-api-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex'),password=randomBytes(32).toString('hex'),options={config,localAuth:{stateDirectory:join(root,'safety'),installerToken}};let app=createLifestreamServer(options);await app.start();t.after(()=>app.shutdown());let base=`http://127.0.0.1:${app.address().port}`;const headers:Record<string,string>={origin:base,'content-type':'application/json'},request=(path:string,body?:unknown)=>fetch(base+path,{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:JSON.stringify(body)})}),api=async(path:string,body?:unknown)=>{const r=await request(path,body),result=await r.json() as Record<string,any>;assert.ok(r.ok,JSON.stringify(result));return result;};
 const setup=await request('/api/auth/v1/setup',{username:'owner',password,installerToken});headers.cookie=setup.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=((await setup.json()) as any).session.csrfToken;const assistant=await api('/api/admin/v1/assistants',{displayName:'Lab Assistant'});await api(`/api/admin/v1/assistants/${assistant.assistantId}/activate`,{profileId:assistant.profile.profileId,expectedActiveRevision:null});await api('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'});const relationship=(await api(`/api/admin/v1/assistants/${assistant.assistantId}/relationships`,{})).relationship,path=`/api/admin/v1/assistants/${assistant.assistantId}/relationships/${relationship.relationshipId}`,readinessPath=path+'/readiness';


 const content='Use the synthetic Fern Lantern example.',files=[{name:'synthetic.txt',format:'notes-v1',content,authoredBy:'user',ownedBySubject:true}],create=async(files:unknown[])=>{const job=(await api(path+'/profile-builder',{files})).job;const pinned=(await api(path+`/profile-builder/${job.jobId}/snapshot`,{expectedRevision:job.revision,files})).job;await api(path+`/profile-builder/${job.jobId}/extract`,{expectedRevision:pinned.revision});for(let n=0;n<100;n++){const value=await api(path+`/profile-builder/${job.jobId}`);if(value.job.status!=='extracting')return value;await new Promise(r=>setTimeout(r,5));}throw new Error('Bounded builder failed to settle');};let value=await create(files);let candidate=value.candidates[0];value=await api(path+`/profile-builder/${value.job.jobId}/review`,{expectedRevision:value.job.revision,items:[{candidateId:candidate.candidateId,expectedRevision:candidate.revision,decision:'approved',use:{personalization:true,mention:true,training:false}}]});candidate=value.candidates[0];const rel=(await api(path)).relationship;await api(path+`/profile-builder/${value.job.jobId}/admit`,{expectedRevision:value.job.revision,expectedRelationshipRevision:rel.revision,items:[{candidateId:candidate.candidateId,expectedRevision:candidate.revision}]});const admitted=(await api(path)).relationship;await api(path+'/privacy',{action:'forget-derived-information',expectedRevision:admitted.revision,idempotencyKey:randomUUID(),targets:[{kind:'record',id:candidate.candidateId,revision:1}]});const erased=await api(path+`/profile-builder/${value.job.jobId}`);assert.equal(erased.job.status,'cancelled');assert.equal(erased.candidates[0].value,'');assert.equal(erased.job.sources[0].path,'forgotten-source');assert.equal((await request(path+'/profile-builder',{files:[{...files[0],name:'renamed.txt'}]})).status,409);const changed=await create([{...files[0],content:content+'\nA new harmless extra line.'}]);assert.equal(changed.job.status,'cancelled');assert.equal(changed.candidates.length,0);const db=new DatabaseSync(config.storage.databasePath);assert.equal((db.prepare('SELECT COUNT(*) AS n FROM profile_builder_snapshots').get() as {n:number}).n,0);db.close();
});
