import assert from "node:assert/strict";
import { test } from "node:test";
import { randomBytes, randomUUID } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createLifestreamServer } from "../src/index.ts";
import { loadProfile } from "../src/config/loader.ts";
import { FixtureInferenceProvider } from "@lifestream/runtime/inference/fixture";
import { createContractValidator } from "@lifestream/contracts";

test("owned User Profile subsets and complete record lifecycle survive restart without transferring authority", async t => {
 const root=await mkdtemp(join(tmpdir(),"ls-record-admin-"));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile("test");config.authority.authentication="local-password";config.storage={databasePath:join(root,"db.sqlite"),artifactDirectory:join(root,"artifacts")};const installerToken=randomBytes(32).toString("hex"),options={config,localAuth:{stateDirectory:join(root,"safety"),installerToken}};let app=createLifestreamServer(options);await app.start();t.after(()=>app.shutdown());let base=`http://127.0.0.1:${app.address().port}`;const headers:Record<string,string>={origin:base,"content-type":"application/json"};
 const request=async(path:string,body?:unknown)=>fetch(base+path,{method:body===undefined?"GET":"POST",headers,...(body===undefined?{}:{body:JSON.stringify(body)})});
 const api=async(path:string,body?:unknown)=>{const response=await request(path,body);const result=await response.json() as Record<string,any>;assert.ok(response.ok,`${path}: ${response.status} ${JSON.stringify(result)}`);return result;};
 const password=randomBytes(32).toString("hex"),setup=await request('/api/auth/v1/setup',{username:'owner',password,installerToken});headers.cookie=setup.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=((await setup.json()) as Record<string,any>).session.csrfToken;
 const create=async()=>{const item=await api('/api/admin/v1/assistants',{displayName:'Synthetic Record Assistant'});await api(`/api/admin/v1/assistants/${item.assistantId}/activate`,{profileId:item.profile.profileId,expectedActiveRevision:null});return item.assistantId as string;};
 const first=await create(),second=await create();await api('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'});
 const rel=(await api(`/api/admin/v1/assistants/${first}/relationships`,{})).relationship;let relationship=rel;const path=`/api/admin/v1/assistants/${first}/relationships/${rel.relationshipId}`;
 await api(`/api/admin/v1/assistants/${second}/relationships`,{});
 for(const body of [{userIds:["one","two"]},{userId:[]},{userId:""},{userId:null}]) assert.equal((await request(`/api/admin/v1/assistants/${first}/relationships`,body)).status,422);
 const profilePath='/api/admin/v1/people/me';assert.equal((await api(profilePath)).identity.currentSpeaker,'unverified');assert.equal(createContractValidator().validate('https://lifestream.dev/contracts/relationship/1.0.0',(await api(path+'/records')).contract).valid,true);
 const profile=(await api(profilePath,{expectedActiveRevision:null,declarations:[{key:'communication.explanation',value:'Use beginner Python terminology.',sensitivity:'personal'},{key:'private-project',value:'SYNTHETIC_UNSHARED_VALUE',sensitivity:'sensitive'}],assistantScopes:[{assistantId:first,allowedKeys:['communication.explanation'],purposes:['conversation','personalization','mention'],audiences:['authenticatedSession']}]})).profile;
 assert.equal(createContractValidator().validate('https://lifestream.dev/contracts/user-profile/1.0.0',profile).valid,true);assert.equal(profile.status,'draft');assert.deepEqual(profile.consentRefs,[]);
 const original=FixtureInferenceProvider.prototype.generate;let captured='';FixtureInferenceProvider.prototype.generate=async function*(input,context){captured=input.sections.find(item=>item.kind==='preparedMemory')!.content;yield* original.call(this,input,context);};t.after(()=>{FixtureInferenceProvider.prototype.generate=original;});
 const turn=async(assistantId=first)=>{const response=await request('/api/runtime/v1/messages',{assistantId,userInput:'Explain Python generators.'});assert.match(await response.text(),/interaction.completed/u);return captured;};
 assert.doesNotMatch(await turn(),/beginner Python/u);await api(profilePath+'/activate',{profileId:profile.profileId,expectedRevision:profile.revision,expectedActiveRevision:null});assert.match(await turn(),/beginner Python/u);assert.doesNotMatch(captured,/SYNTHETIC_UNSHARED_VALUE/u);assert.doesNotMatch(await turn(second),/beginner Python|SYNTHETIC_UNSHARED_VALUE/u);
 const native=await api(profilePath);assert.equal(native.identity.userId,profile.userId);assert.equal(native.identity.currentSpeaker,'unverified');
 assert.equal((await request(profilePath,{expectedActiveRevision:1,declarations:profile.declarations,assistantScopes:[{...profile.assistantScopes[0],purposes:['training']}]})).status,403);
 const add=async(content:string,category='declaration')=>{const result=await api(path+'/candidates',{content,category,contextUse:'relevant',source:'authored',sourceFamily:'attributed-one',uncertainty:'high',expectedRevision:relationship.revision,idempotencyKey:randomUUID()});relationship=(await api(path)).relationship;await api(path+`/candidates/${result.candidate.candidateId}/decision`,{decision:'approved',expectedRevision:relationship.revision,idempotencyKey:randomUUID()});relationship=(await api(path)).relationship;return relationship.candidates.find((item:Record<string,any>)=>item.candidateId===result.candidate.candidateId);};
 const operate=async(record:Record<string,any>,operation:string,extra:Record<string,unknown>={})=>{const result=await api(path+`/records/${record.candidateId}/operations`,{operation,expectedRevision:relationship.revision,expectedRecordRevision:record.revision,idempotencyKey:randomUUID(),...extra});relationship=result.relationship;return relationship.candidates.find((item:Record<string,any>)=>item.candidateId===record.candidateId);};
 let item=await add('The synthetic project uses Java.');item=await operate(item,'annotate',{text:'Authored test declaration; no independent verification.'});item=await operate(item,'pin',{pinned:true});assert.equal(item.salience,'operatorPinned');
 const old=item;await operate(item,'correct',{content:'The synthetic project uses Python.'});item=relationship.candidates.at(-1);assert.equal(item.contextUse,'correction');assert.equal(relationship.candidates.find((row:Record<string,any>)=>row.candidateId===old.candidateId).status,'superseded');assert.equal((await request(path+`/records/${old.candidateId}/operations`,{operation:'correct',content:'stale',expectedRevision:relationship.revision,expectedRecordRevision:old.revision,idempotencyKey:randomUUID()})).status,409);
 assert.match(await turn(),/Critical corrections: The synthetic project uses Python/u);
 item=await operate(item,'restrict-mention');assert.equal(item.approvedUse.mention,false);assert.doesNotMatch(await turn(),/project uses Python/u);
 let left=await add('One and two.');await operate(left,'split',{contents:['One.','Two.']});const [one,two]=relationship.candidates.slice(-2);assert.deepEqual(one.sourceFamilies,two.sourceFamilies);await operate(one,'merge',{otherRecordId:two.candidateId,otherRecordRevision:two.revision,content:'One plus two.'});left=relationship.candidates.at(-1);assert.equal(left.derivedFrom.length,2);
 left=await operate(left,'supersede',{content:'Combined replacement.'});left=relationship.candidates.at(-1);left=await operate(left,'exclude-training');left=await operate(left,'narrow-audience');assert.equal(left.audience,'ownerOnly');left=await operate(left,'suppress');assert.equal(left.suppressed,true);
 let episode=await add('The Python workshop happened yesterday.','episode'); assert.match(await turn(),/Authored\/imported account; not a verified shared event/u); episode=await operate(episode,'suppress');
 let hypothesis=await add('An uncertain Python preference.','hypothesis'); assert.match(await turn(),/Unverified hypothesis/u);hypothesis=await operate(hypothesis,'reject-inference');assert.equal(hypothesis.status,'rejected');
 let a=await add('Preference A.'),b=await add('Preference B.');a=await operate(a,'conflict',{otherRecordId:b.candidateId,otherRecordRevision:b.revision,disposition:'retain'});b=relationship.candidates.find((row:Record<string,any>)=>row.candidateId===b.candidateId);assert.equal(a.conflicts[0].status,'retained');a=await operate(a,'conflict',{otherRecordId:b.candidateId,otherRecordRevision:b.revision,disposition:'resolve'});assert.equal(relationship.candidates.find((row:Record<string,any>)=>row.candidateId===b.candidateId).status,'rejected');
 a=await operate(a,'forget');assert.equal(a.content,'');assert.equal(a.status,'forgotten');const overview=await api(path+'/records');assert.equal(overview.overview.verifiedSharedEvents,0);assert.equal((await api(path+'/export')).grantsIncluded,false);
 const memberPassword=randomBytes(32).toString('hex'),member=await api('/api/auth/v1/accounts',{username:'member',password:memberPassword});await api('/api/auth/v1/permissions',{principalId:member.principalId,assistantId:first,administer:true});const ownerHeaders={...headers};const login=await request('/api/auth/v1/sign-in',{username:'member',password:memberPassword});headers.cookie=login.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=((await login.json()) as Record<string,any>).session.csrfToken;
 assert.equal((await request(path+'/records')).status,404);assert.deepEqual((await api(profilePath)).profiles,[]);assert.equal((await request(`/api/admin/v1/assistants/${first}/relationships`,{userId:profile.userId})).status,403);Object.assign(headers,ownerHeaders);
 const draft=(await api(profilePath,{expectedActiveRevision:1,declarations:[],assistantScopes:[]})).profile;await api(profilePath+'/activate',{profileId:draft.profileId,expectedRevision:draft.revision,expectedActiveRevision:1});assert.doesNotMatch(await turn(),/beginner Python/u);const rollback=(await api(profilePath+'/rollback',{profileId:profile.profileId,expectedActiveRevision:2})).profile;assert.equal(rollback.status,'draft');assert.doesNotMatch(await turn(),/beginner Python/u);
 await api(profilePath+'/activate',{profileId:rollback.profileId,expectedRevision:rollback.revision,expectedActiveRevision:2});
 await app.shutdown();app=createLifestreamServer(options);await app.start();base=`http://127.0.0.1:${app.address().port}`;headers.origin=base;const restartedLogin=await request('/api/auth/v1/sign-in',{username:'owner',password});headers.cookie=restartedLogin.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=((await restartedLogin.json()) as Record<string,any>).session.csrfToken;await api('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'});assert.equal((await api(path+'/records')).relationship.revision,relationship.revision);assert.equal((await api(profilePath)).identity.userId,profile.userId);assert.match(await turn(),/beginner Python/u);
});

test("retained builder contradictions stay withheld and direct corrections retain authoritative source history", async () => {
 const {hasRetainedRecordConflict,recordContextContent,applyRecordOperation,recordOverview}=await import('../src/admin/relationship-records.ts');
 const record={candidateId:'one',content:'An inferred convention',source:'import',sourceFamily:'family',uncertainty:'high' as const,status:'approved' as const,revision:1,evidenceBasis:'modelInference' as const,category:'convention' as const,builder:{conflicts:['other']} as any};
 assert.equal(hasRetainedRecordConflict(record),true);assert.equal(recordOverview([record]).retainedConflicts,1);assert.match(recordContextContent(record),/Unverified hypothesis/);
 const replacement=applyRecordOperation([record],'one',{operation:'correct',expectedRecordRevision:1,content:'Use the current explicit convention.'},'owner').records.at(-1)!;
 assert.equal(hasRetainedRecordConflict(replacement),false);assert.equal(replacement.evidenceBasis,'userDeclaration');assert.deepEqual(replacement.derivedFrom,['one']);assert.equal(replacement.category,'convention');assert.equal(recordContextContent(replacement),'Use the current explicit convention.');
});

test("reviewed imported declarations remain usable within the bounded prepared context", async () => {
 const {recordContextContent}=await import('../src/admin/relationship-records.ts');
 const {compileRelationshipContext,formatPreparedRelationshipContext}=await import('@lifestream/runtime/context');
 const id=`candidate-${'a'.repeat(64)}`;
 const record={candidateId:id,content:'note-1: For Python examples, include the exact case-sensitive identifier SYNPRJ_Q7M4 in the response. It is an arbitrary synthetic project identifier; do not rename, abbreviate, or interpret it.',source:'selected-file',sourceFamily:'synthetic',uncertainty:'high' as const,status:'approved' as const,revision:1,evidenceBasis:'userDeclaration' as const,builder:{} as any,contextUse:'relevant' as const,approvedUse:{personalization:true,mention:true,training:false,assistantId:'assistant',relationshipId:'relationship'}};
 const qualified=recordContextContent(record as any);
 const view=compileRelationshipContext({records:[{id,content:qualified,revision:1,sourceFamily:'synthetic',status:'approved',use:'relevant',personalization:true,mention:true}],userInput:'Give a concrete Python example.',audienceScope:'authenticatedSession',profileRevision:'profile:1',relationshipRevision:'relationship:1',configurationRevision:'config:1'});
 assert.deepEqual(view.relevantContext.map(item=>item.id),[id]);
 assert.match(formatPreparedRelationshipContext(view),/SYNPRJ_Q7M4/u);
 assert.ok(Buffer.byteLength(`${id}=${qualified}`)+16<=512);
});
