import assert from 'node:assert/strict';
import {test} from 'node:test';
import {randomUUID,randomBytes} from 'node:crypto';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createLifestreamServer} from '../src/index.ts';
import {loadProfile} from '../src/config/loader.ts';
import {FixtureInferenceProvider} from '@lifestream/runtime/inference/fixture';

test('actual isolated Lab calls, source-separated holdout, guarded promotion and interrupted work preserve conversation',async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-lab-api-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex'),password=randomBytes(32).toString('hex'),options={config,localAuth:{stateDirectory:join(root,'safety'),installerToken}};let app=createLifestreamServer(options);await app.start();t.after(()=>app.shutdown());let base=`http://127.0.0.1:${app.address().port}`;const headers:Record<string,string>={origin:base,'content-type':'application/json'},request=(path:string,body?:unknown)=>fetch(base+path,{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:JSON.stringify(body)})}),api=async(path:string,body?:unknown)=>{const r=await request(path,body),result=await r.json() as Record<string,any>;assert.ok(r.ok,JSON.stringify(result));return result;};
 const setup=await request('/api/auth/v1/setup',{username:'owner',password,installerToken});headers.cookie=setup.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=((await setup.json()) as any).session.csrfToken;const assistant=await api('/api/admin/v1/assistants',{displayName:'Lab Assistant'});await api(`/api/admin/v1/assistants/${assistant.assistantId}/activate`,{profileId:assistant.profile.profileId,expectedActiveRevision:null});await api('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'});const relationship=(await api(`/api/admin/v1/assistants/${assistant.assistantId}/relationships`,{})).relationship,path=`/api/admin/v1/assistants/${assistant.assistantId}/relationships/${relationship.relationshipId}`,labPath=path+'/lab';
 const add=async(content:string,contextUse='baseline')=>{let rel=(await api(path)).relationship;const candidate=(await api(path+'/candidates',{content,contextUse,source:'authored',sourceFamily:'context-family',uncertainty:'high',expectedRevision:rel.revision,idempotencyKey:randomUUID()})).candidate;rel=(await api(path)).relationship;await api(path+`/candidates/${candidate.candidateId}/decision`,{decision:'approved',expectedRevision:rel.revision,idempotencyKey:randomUUID()});return candidate;};const first=await add('Use short explanations.');await add('Use short explanations.');await add('The synthetic project codename is Azure Birch.','correction');
 const originalConfig=(await api(path+'/configurations',{preset:'balanced',name:'Known Good',controls:{verbosity:0.5},idempotencyKey:randomUUID()})).configuration;await api(path+`/configurations/${originalConfig.configurationId}/activate`,{expectedRevision:originalConfig.revision,idempotencyKey:randomUUID()});
 const input={syntheticOnly:true,transmissionApproved:true,scenarios:[{id:'comparison',prompt:'What is the synthetic project codename?',sourceFamily:'scenario-one',split:'comparison',forbiddenTerms:['FORBIDDEN_MARKER']},{id:'held',prompt:'Explain a cache.',sourceFamily:'scenario-held',split:'heldOut',forbiddenTerms:['FORBIDDEN_MARKER']}],criteria:['nonempty','noForbiddenTerms'],repeatedRuns:2,candidateControls:{verbosity:0},candidateRepresentation:'conventionOriented'};
 assert.equal((await request(labPath,{...input,transmissionApproved:false})).status,422);assert.equal((await request(labPath,{...input,providerRefs:['live:bad']})).status,422);assert.equal((await request(labPath,{...input,scenarios:[input.scenarios[0],{...input.scenarios[1],sourceFamily:'scenario-one'}]})).status,422);
 const original=FixtureInferenceProvider.prototype.generate;let calls=0,mode:'normal'|'hold'|'capability'='normal',release:()=>void=()=>{},entered=false;let gate:Promise<void>=Promise.resolve();t.mock.method(FixtureInferenceProvider.prototype,'generate',async function*(this:FixtureInferenceProvider,input,context){if(input.scope.sessionId.startsWith('lab:')){calls++;if(mode==='hold'){entered=true;await gate;}if(mode==='capability'){yield {kind:'capabilityRequest' as const,capability:{name:'forbidden',input:{},effect:'read-only' as const}};return;}}yield* original.call(this,input,context);});
 const prepare=async()=>(await api(labPath,input)).lab,wait=async()=>{for(let n=0;n<200;n++){const lab=(await api(labPath)).lab;if(lab.status!=='running')return lab;await new Promise(r=>setTimeout(r,5));}throw new Error('bounded Lab did not settle');},run=async(action='/run')=>{const lab=(await api(labPath)).lab;await api(labPath+action,{expectedRevision:lab.revision});return wait();};
 let lab=await prepare();lab=await run();assert.equal(calls,12);assert.equal(lab.comparison.resultCount,12);assert.ok(Object.values(lab.comparison.variability).every(v=>v===0));assert.notEqual(lab.comparison.results.find((r:any)=>r.representation==='recordOriented'&&r.variant==='current').output.preparedContext,lab.comparison.results.find((r:any)=>r.representation==='conventionOriented'&&r.variant==='current').output.preparedContext);assert.ok(lab.comparison.results.every((r:any)=>r.output.capabilityDispatches===0&&r.output.liveMemoryWrites===0));assert.equal((await request(labPath+'/decision',{expectedRevision:lab.revision,decision:'promoted'})).status,409);
 lab=await run('/held-out');assert.equal(calls,24);const promoted=await api(labPath+'/decision',{expectedRevision:lab.revision,decision:'promoted'});assert.equal(promoted.configuration.status,'draft');assert.equal((await api(path+'/configurations')).configurations.find((c:any)=>c.status==='active').configurationId,originalConfig.configurationId);await api(path+`/configurations/${promoted.configuration.configurationId}/activate`,{expectedRevision:promoted.configuration.revision,idempotencyKey:randomUUID()});assert.equal((await api(path+'/effective-context')).representationRevision,'convention-oriented:1');const rollback=(await api(path+`/configurations/${originalConfig.configurationId}/rollback`,{expectedRevision:originalConfig.revision,idempotencyKey:randomUUID()})).configuration;await api(path+`/configurations/${rollback.configurationId}/activate`,{expectedRevision:rollback.revision,idempotencyKey:randomUUID()});assert.equal((await api(path+'/effective-context')).representationRevision,'record-oriented:1');
 lab=await prepare();lab=await run();lab=await run('/held-out');const rel=(await api(path)).relationship;await api(path+`/records/${first.candidateId}/operations`,{operation:'annotate',text:'Source review changed.',expectedRevision:rel.revision,expectedRecordRevision:2,idempotencyKey:randomUUID()});assert.equal((await request(labPath+'/decision',{expectedRevision:lab.revision,decision:'promoted'})).status,409);
 mode='hold';gate=new Promise(resolve=>{release=resolve;});lab=await prepare();await api(labPath+'/run',{expectedRevision:lab.revision});for(let n=0;n<100&&!entered;n++)await new Promise(r=>setTimeout(r,5));assert.equal(entered,true);const ordinary=await request('/api/runtime/v1/messages',{assistantId:assistant.assistantId,userInput:'Hello during background work'});assert.match(await ordinary.text(),/interaction.completed/);lab=(await api(labPath)).lab;await api(labPath+'/cancel',{expectedRevision:lab.revision});release();await new Promise(r=>setTimeout(r,20));lab=(await api(labPath)).lab;assert.equal(lab.status,'cancelled');assert.equal(lab.comparison?.resultCount??0,0);
 mode='capability';await prepare();lab=await run();assert.equal(lab.status,'failed');assert.equal(lab.comparison.resultCount,0);assert.ok(lab.comparison.results.every((r:any)=>/zero dispatch/.test(r.error)));assert.match(await (await request('/api/runtime/v1/messages',{assistantId:assistant.assistantId,userInput:'Hello after background failure'})).text(),/interaction.completed/);
 mode='hold';entered=false;gate=new Promise(resolve=>{release=resolve;});lab=await prepare();await api(labPath+'/run',{expectedRevision:lab.revision});for(let n=0;n<100&&!entered;n++)await new Promise(r=>setTimeout(r,5));await app.shutdown();release();await new Promise(r=>setTimeout(r,20));mode='normal';app=createLifestreamServer(options);await app.start();base=`http://127.0.0.1:${app.address().port}`;headers.origin=base;const login=await request('/api/auth/v1/sign-in',{username:'owner',password});headers.cookie=login.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=((await login.json()) as any).session.csrfToken;for(let n=0;n<200;n++){lab=(await api(labPath)).lab;if(lab.status!=='partial'&&lab.status!=='running')break;await new Promise(r=>setTimeout(r,5));}assert.equal(lab.status,'completed');assert.equal(lab.comparison.resultCount,12);
 const other=await api('/api/admin/v1/assistants',{displayName:'Other Assistant'}),otherRel=(await api(`/api/admin/v1/assistants/${other.assistantId}/relationships`,{})).relationship;assert.equal((await request(`/api/admin/v1/assistants/${other.assistantId}/relationships/${otherRel.relationshipId}/lab/experiments/${lab.experimentId}`)).status,404);
});
