import assert from 'node:assert/strict';
import test from 'node:test';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes} from 'node:crypto';
import {Database} from '@lifestream/storage-sqlite';
import {SavedVoiceAdministration,voiceSummary,savedVoiceConfiguration} from '../src/admin/saved-voices.ts';
import {defaultVoiceSettings} from '../src/runtime/voice-settings.ts';
import {createLifestreamServer} from '../src/index.ts';
import {loadProfile} from '../src/config/loader.ts';
import {savedVoiceFixture} from './saved-voice-fixture.ts';
test('saved voice compatibility follows TTS configuration and survives storage relocation',()=>{
 const config=loadProfile('ai5090'),before=savedVoiceConfiguration(config);config.storage.databasePath='/different/isolated/state.sqlite';assert.equal(savedVoiceConfiguration(config),before);config.ttsProfile!.modelRevision='different-model';assert.notEqual(savedVoiceConfiguration(config),before);
});
test('voice definitions validate conditioning and do not expose raw reference audio',t=>{
 const db=new Database({path:':memory:'});db.migrate();t.after(()=>db.close());const admin=new SavedVoiceAdministration(db),reference={sampleRateHz:16000,dataBase64:Buffer.alloc(64000).toString('base64'),transcript:'Synthetic source',consent:true};
 const input={label:'Synthetic reference',language:'en',settings:{...defaultVoiceSettings,reference}},controls={description:true,reference:true};const v=admin.create('assistant',input,'provider',controls);assert.equal(voiceSummary(v).settings.reference?.durationMs,2000);assert.doesNotMatch(JSON.stringify(voiceSummary(v)),/dataBase64|Synthetic source/);assert.throws(()=>admin.create('assistant',input,'provider',{description:true,reference:false}),/support/);assert.throws(()=>admin.create('assistant',{...input,settings:{...input.settings,reference:{...reference,consent:false}}},'provider',controls),/permission/);assert.throws(()=>admin.create('assistant',{...input,settings:{description:'(injected instructions)'}},'provider',controls),/parentheses/);assert.throws(()=>admin.create('assistant',{...input,settings:{reference:{...reference,dataBase64:'bad'}}},'provider',controls));assert.throws(()=>admin.definition('other',v.voiceRef,'provider'),/unavailable/);assert.throws(()=>admin.definition('assistant',v.voiceRef,'other'),/different provider/);
});
test('reference-only provider previews a saved reference without enabling description or seed controls',async t=>{
 const root=mkdtempSync(join(tmpdir(),'reference-only-preview-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const fixture=await savedVoiceFixture({description:false,reference:true});t.after(fixture.close);
 const config=loadProfile('test');config.providers.tts='voxcpm';config.ttsProfile=fixture.profile;config.storage={databasePath:join(root,'state.sqlite'),artifactDirectory:join(root,'artifacts')};config.authority.authentication='local-password';const installerToken=randomBytes(32).toString('hex');const app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'safety'),installerToken},audiencePrivacy:{}});await app.start();t.after(()=>app.shutdown());const base=`http://127.0.0.1:${app.address().port}`;let cookie='',csrf='';
 const request=(path:string,body?:unknown)=>fetch(base+path,{method:body===undefined?'GET':'POST',headers:{origin:base,cookie,'content-type':'application/json','x-lifestream-csrf':csrf},...(body===undefined?{}:{body:JSON.stringify(body)})});
 const setup=await request('/api/auth/v1/setup',{username:'owner',password:randomBytes(32).toString('hex'),installerToken});cookie=setup.headers.get('set-cookie')!.split(';')[0]!;csrf=(await setup.json()).session.csrfToken;const session=await (await request('/api/runtime/v1/session-context')).json();await request('/api/runtime/v1/session-context',{expectedRevision:session.revision,mode:'text',audienceScope:'authenticatedSession'});await request('/api/runtime/v1/audience',{mode:'solo',seconds:300});
 const assistant=await (await request('/api/admin/v1/assistants',{displayName:'Synthetic reference Assistant'})).json();await request(`/api/admin/v1/assistants/${assistant.assistantId}/activate`,{profileId:assistant.profile.profileId,expectedActiveRevision:null});const path=`/api/admin/v1/assistants/${assistant.assistantId}/voices`,reference={sampleRateHz:16000,dataBase64:Buffer.alloc(64000).toString('base64'),transcript:'Synthetic source',consent:true},candidate={label:'Reference only',language:'en',settings:{reference}};
 const created=await request(path,candidate);assert.equal(created.status,201);const {voice}=await created.json();assert.deepEqual((await (await request(path)).json()).controls,{description:false,reference:true});
 for(const settings of [{reference,description:'Unsupported description'},{reference,seed:4}]){assert.equal((await request(path,{...candidate,settings})).status,422);assert.equal((await request('/api/runtime/v1/tts',{text:'Preview.',voiceSettings:settings})).status,422);}assert.equal(fixture.requests.length,0);
 const preview=await request('/api/runtime/v1/tts',{assistantId:assistant.assistantId,voiceRef:voice.voiceRef,text:'Speak only this comparison sentence.'});assert.equal(preview.status,200);const events=(await preview.text()).trim().split('\n').map(line=>JSON.parse(line)),terminal=events.at(-1);assert.equal(terminal.outcome,'succeeded');assert.equal(terminal.voicePreview.voiceRef,voice.voiceRef);assert.ok(events.some(event=>event.kind==='data'));assert.equal(fixture.requests.at(-1)!.voiceReference.dataBase64,reference.dataBase64);assert.equal(fixture.requests.at(-1)!.voiceReference.transcript,reference.transcript);assert.equal(fixture.requests.at(-1)!.text,'Speak only this comparison sentence.');assert.equal((await (await request(path)).json()).activeVoiceRef,null,'preview must not activate the saved voice');
});
test('authenticated preview and reviewed activation bind the existing Assistant profile and survive restart',async t=>{
 const root=mkdtempSync(join(tmpdir(),'saved-voice-http-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const fixture=await savedVoiceFixture();t.after(fixture.close);const config=loadProfile('test');config.providers.tts='voxcpm';config.ttsProfile=fixture.profile;config.storage={databasePath:join(root,'state.sqlite'),artifactDirectory:join(root,'artifacts')};config.authority.authentication='local-password';const installerToken=randomBytes(32).toString('hex'),password=randomBytes(32).toString('hex'),localAuth={stateDirectory:join(root,'safety'),installerToken};let app=createLifestreamServer({config,localAuth,audiencePrivacy:{}});await app.start();let base=`http://127.0.0.1:${app.address().port}`,cookie='',csrf='';t.after(()=>app.shutdown());
 const request=(path:string,body?:unknown,headers:Record<string,string>={},signal?:AbortSignal)=>fetch(base+path,{method:body===undefined?'GET':'POST',headers:{origin:base,cookie,'content-type':'application/json','x-lifestream-csrf':csrf,...headers},...(body===undefined?{}:{body:JSON.stringify(body)}),signal});
 const setup=await request('/api/auth/v1/setup',{username:'owner',password,installerToken});cookie=setup.headers.get('set-cookie')!.split(';')[0]!;csrf=(await setup.json()).session.csrfToken;const privateSession=async()=>{const state=await (await request('/api/runtime/v1/session-context')).json();await request('/api/runtime/v1/session-context',{expectedRevision:state.revision,mode:'text',audienceScope:'authenticatedSession'});assert.equal((await request('/api/runtime/v1/audience',{mode:'solo',seconds:300})).status,200);};await privateSession();
 const assistant=await (await request('/api/admin/v1/assistants',{displayName:'Synthetic voice Assistant'})).json();await request(`/api/admin/v1/assistants/${assistant.assistantId}/activate`,{profileId:assistant.profile.profileId,expectedActiveRevision:null});const path=`/api/admin/v1/assistants/${assistant.assistantId}/voices`,candidate={label:'Calm synthetic',language:'en',settings:{...defaultVoiceSettings,description:'Calm clear delivery',seed:4}};
 assert.equal((await request(path,candidate,{'x-lifestream-csrf':'wrong'})).status,403);const created=await request(path,candidate);assert.equal(created.status,201);const {voice}=await created.json();const before=await (await request(`/api/admin/v1/assistants/${assistant.assistantId}`)).json();assert.equal(before.profiles.find((p:any)=>p.status==='active').voiceProfile,null);
 assert.equal((await request(path+'/activate',{voiceRef:voice.voiceRef,previewId:'missing',reviewed:true,expectedActiveRevision:1})).status,409);
 const previewBody={assistantId:assistant.assistantId,voiceRef:voice.voiceRef,text:'This is shared comparison text.'};
 fixture.state.fail=true;const failed=await request('/api/runtime/v1/tts',previewBody);assert.doesNotMatch(await failed.text(),/voicePreview/);fixture.state.fail=false;
 fixture.state.delayMs=250;const previousCount=fixture.requests.length,pending=request('/api/runtime/v1/tts',previewBody);for(let i=0;i<100&&fixture.requests.length===previousCount;i++)await new Promise(r=>setTimeout(r,5));assert.ok(fixture.requests.length>previousCount);await request('/api/runtime/v1/audience',{mode:'shared',seconds:300});const cancelled=await pending;const stopped=await cancelled.text();assert.doesNotMatch(stopped,/voicePreview|"kind":"data"/,'audience restriction fences late preview audio and eligibility');fixture.state.delayMs=0;await request('/api/runtime/v1/audience',{mode:'solo',seconds:300});
 const preview=await request('/api/runtime/v1/tts',previewBody);assert.equal(preview.status,200);const events=(await preview.text()).trim().split('\n').map(x=>JSON.parse(x)),terminal=events.at(-1);assert.equal(terminal.outcome,'succeeded');assert.equal(fixture.requests.at(-1)!.text,previewBody.text);assert.equal(fixture.requests.at(-1)!.voiceDesign.description,candidate.settings.description);assert.doesNotMatch(fixture.requests.at(-1)!.text,/Calm clear delivery/);
 const activation={voiceRef:voice.voiceRef,previewId:terminal.voicePreview.previewId,reviewed:true,expectedActiveRevision:1};fixture.state.ready=false;assert.equal((await request(path+'/activate',activation)).status,503);fixture.state.ready=true;assert.equal((await request(path+'/activate',{...activation,reviewed:false})).status,422);assert.equal((await request(path+'/activate',{...activation,expectedActiveRevision:7})).status,409);assert.equal((await request(path+'/activate',activation)).status,200);assert.equal((await request(path+'/remove',{voiceRef:voice.voiceRef,expectedRevision:voice.revision})).status,422,'active voice reference cannot be removed');assert.equal((await request(path+'/activate',activation)).status,409);
 const db=new Database({path:config.storage.databasePath});const admin=new SavedVoiceAdministration(db),binding=admin.resolve(assistant.assistantId,(await (await request(path)).json()).providerBinding);assert.equal(binding.voiceProfile.voiceRef,voice.voiceRef);assert.equal(binding.settings.description,candidate.settings.description);db.close();
 await app.shutdown();app=createLifestreamServer({config,localAuth,audiencePrivacy:{}});await app.start();base=`http://127.0.0.1:${app.address().port}`;const signed=await request('/api/auth/v1/sign-in',{username:'owner',password});cookie=signed.headers.get('set-cookie')!.split(';')[0]!;csrf=(await signed.json()).session.csrfToken;assert.equal((await request(path)).status,403,'new session starts protected');await privateSession();const after=await (await request(path)).json();assert.equal(after.activeVoiceRef,voice.voiceRef);assert.equal(after.voices.length,1);assert.equal((await request(path+'/activate',{...activation,expectedActiveRevision:after.activeProfileRevision})).status,409,'preview does not transfer to another session');
 assert.equal((await request('/api/auth/v1/sign-out',{})).status,200);assert.equal((await request(path)).status,401);
});
