import assert from "node:assert/strict";
import { test } from "node:test";
import { randomBytes, randomUUID } from "node:crypto";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Database, AssistantProfileRepository, AdmissionRepository } from "@lifestream/storage-sqlite";
import { LocalAuthentication } from "../src/auth/local-auth.ts";
import { SecurityAdministration } from "../src/admin/security-administration.ts";
import { FixtureCapabilityProvider } from "../../../packages/providers-fixture/src/capability/provider.ts";
import type { CapabilityDefinition } from "../../../packages/runtime/src/capabilities/ports.ts";
const call=()=>({requestId:randomUUID(),correlationId:randomUUID(),deadlineAt:new Date(Date.now()+5000).toISOString(),executionMode:"live" as const,signal:new AbortController().signal,isCurrent:()=>true});
const password=()=>`synthetic-${randomBytes(24).toString('hex')}`;
const origin="http://127.0.0.1:32000";
const capability:CapabilityDefinition={id:"synthetic.echo",version:"1.0.0",inputSchema:{type:"object",required:["text"],properties:{text:{type:"string"}}},outputSchema:{type:"object"},sideEffect:"reversible",authorization:"required",idempotency:"idempotent",latencyClass:"fast",offlineAvailable:true,simulationSupported:true,route:"synthetic-fixture"};
const artifact={reference:"synthetic:schema",sha256:"0".repeat(64),mediaType:"application/schema+json",schemaRef:"https://json-schema.org/draft/2020-12/schema",byteLength:2};
const draft=(assistantId:string)=>({schemaVersion:"1.0.0",skillId:randomUUID(),assistantId,revision:1,version:"1.0.0",status:"draft",name:"Synthetic echo",description:"Bounded isolated check",inputSchema:artifact,outputSchema:artifact,requiredCapabilities:[{capabilityId:capability.id,version:capability.version}],preconditions:[],maxSteps:1,steps:[{stepId:"00000000-0000-4000-8000-000000000001",capabilityId:capability.id,capabilityVersion:capability.version,inputBindings:[{targetPointer:"/text",source:{type:"input",pointer:"/text"}}],onMissingInput:"reject"}],outputBindings:[],failurePolicy:"stop",compensationGuidance:"Stop for review",provenance:{sourceRefs:["synthetic-note"],transformationId:"manual",transformationVersion:"1.0.0"},createdAt:"2026-09-13T01:00:00Z",createdBy:"synthetic",activationRef:null});
test("existing grants persist with once/session/persistent admission, current scope, expiry and revocation",async t=>{
 const root=mkdtempSync(join(tmpdir(),"ls-security-"));let now=Date.now();const database=new Database({path:join(root,'db.sqlite')});database.migrate();t.after(()=>{database.close();rmSync(root,{recursive:true,force:true});});const options={stateDirectory:join(root,'safety'),installerToken:password(),now:()=>now};const auth=new LocalAuthentication(database,options),p=password(),setup=await auth.setup('owner',p,options.installerToken,origin),context=auth.context(setup.session.token,origin)!;const profiles=new AssistantProfileRepository(database),assistantId=randomUUID();profiles.create({schemaVersion:'2.0.0',assistantId,profileId:randomUUID(),revision:1,status:'draft',createdBy:context.principalId,createdAt:new Date(now).toISOString()});auth.permitCreator(context,assistantId);const provider=new FixtureCapabilityProvider([capability]),admin=new SecurityAdministration(database,auth,provider,()=>now),base=`/api/authority/v1/assistants/${assistantId}`;
 const requestGrant=(durationMode:string)=>{const grant=admin.handleLocal('POST',`${base}/grants`,context,{scope:[capability.id],durationSeconds:3600,durationMode}).body.grant as {id:string;revision:number};admin.handleLocal('POST',`${base}/grants/${grant.id}/decision`,context,{expectedRevision:1,decision:'active'});return grant.id;};
 const once=requestGrant('allowOnce');const invoke=(grantId:string)=>admin.handle('POST',`${base}/tools/${capability.id}/invoke`,context,{grantId,input:{text:'synthetic'}},call());assert.equal((await invoke(once)).status,200);assert.equal((await invoke(once)).status,403);assert.equal((admin.handleLocal('GET',`${base}/grants`,context,{}).body.grants as Array<{status:string}>)[0]?.status,'consumed');
 const sessionGrant=requestGrant('allowSession'),persistent=requestGrant('allowPersistent');assert.equal((await invoke(sessionGrant)).status,200);assert.equal((await invoke(sessionGrant)).status,200);const refreshed=await auth.signIn('owner',p,'',origin,'loopback'),second=auth.context(refreshed.token,origin)!;assert.equal((await admin.handle('POST',`${base}/tools/${capability.id}/invoke`,second,{grantId:sessionGrant,input:{text:'synthetic'}},call())).status,403);assert.equal((await admin.handle('POST',`${base}/tools/${capability.id}/invoke`,second,{grantId:persistent,input:{text:'synthetic'}},call())).status,200);admin.handleLocal('POST',`${base}/grants/${persistent}/decision`,second,{expectedRevision:2,decision:'revoked'});assert.equal((await admin.handle('POST',`${base}/tools/${capability.id}/invoke`,second,{grantId:persistent,input:{text:'synthetic'}},call())).status,403);
 const audit=admin.handleLocal('GET',`${base}/audit`,context,{}).body.events as Array<{event:string}>;assert.ok(audit.some(event=>event.event==='consumed'));assert.ok(audit.some(event=>event.event==='revoked'));const restarted=new SecurityAdministration(database,new LocalAuthentication(database,options),provider,()=>now);assert.equal((restarted.handleLocal('GET',`${base}/grants`,context,{}).body.grants as unknown[]).length,3);
 const otherId=randomUUID();profiles.create({schemaVersion:'2.0.0',assistantId:otherId,profileId:randomUUID(),revision:1,status:'draft',createdBy:context.principalId,createdAt:new Date(now).toISOString()});auth.permitCreator(context,otherId);assert.equal((await admin.handle('POST',`/api/authority/v1/assistants/${otherId}/tools/${capability.id}/invoke`,context,{grantId:sessionGrant,input:{text:'synthetic'}},call())).status,403);
 now+=1_800_000;await assert.rejects(()=>invoke(sessionGrant),/authentication/);
});

test("one-use admission is atomic across durable repository instances and binds replay inputs",async t=>{const root=mkdtempSync(join(tmpdir(),'ls-admission-'));const db=new Database({path:join(root,'db.sqlite')});db.migrate();const other=new Database({path:join(root,'db.sqlite')});other.migrate();t.after(()=>{db.close();other.close();rmSync(root,{recursive:true,force:true});});const grant=randomUUID();db.connection.prepare('INSERT INTO authority_grants VALUES (?,?,?,?,?,?,?,?)').run(grant,'human','assistant','active',JSON.stringify(['test']),1,JSON.stringify({durationMode:'allowOnce',sessionId:'session',expiresAt:'2999-01-01T00:00:00Z'}),'2026-09-13T01:00:00Z');const a=new AdmissionRepository(db),b=new AdmissionRepository(other);const input={grantId:grant,principalId:'human',assistantId:'assistant',sessionId:'session',capabilityId:'test',invocationId:randomUUID(),inputDigest:'synthetic',now:'2026-09-13T01:00:00Z',assertCurrent:()=>{}};assert.equal(a.admitGoverned(input).status,'admitted');assert.throws(()=>b.admitGoverned({...input,invocationId:randomUUID()}),/not admissible/);});

test("existing Skill schema, current rows and immutable history support draft/review/activation without grants",async t=>{const root=mkdtempSync(join(tmpdir(),'ls-skills-'));const database=new Database({path:join(root,'db.sqlite')});database.migrate();t.after(()=>{database.close();rmSync(root,{recursive:true,force:true});});const auth=new LocalAuthentication(database,{stateDirectory:join(root,'safety'),installerToken:'synthetic-installer'}),setup=await auth.setup('owner',password(),'synthetic-installer',origin),context=auth.context(setup.session.token,origin)!;const assistantId=randomUUID();new AssistantProfileRepository(database).create({schemaVersion:'2.0.0',assistantId,profileId:randomUUID(),revision:1,status:'draft',createdBy:context.principalId,createdAt:new Date().toISOString()});auth.permitCreator(context,assistantId);const admin=new SecurityAdministration(database,auth),base=`/api/authority/v1/assistants/${assistantId}/skills`;assert.throws(()=>admin.handleLocal('POST',base,context,{skill:{...draft(assistantId),status:'active',activationRef:{reference:'self'}}}),/draft conflict/);assert.throws(()=>admin.handleLocal('POST',base,context,{skill:{...draft(assistantId),grants:['injected']}}),/invalid skill/);const created=admin.handleLocal('POST',base,context,{skill:draft(assistantId)});assert.equal(created.status,201);const skill=created.body.skill as {skillId:string;revision:number};const activated=admin.handleLocal('POST',`${base}/${skill.skillId}/activate`,context,{expectedRevision:1});assert.equal(activated.status,200);assert.equal(activated.body.grantsAuthority,false);assert.throws(()=>admin.handleLocal('POST',`${base}/${skill.skillId}/activate`,context,{expectedRevision:1}),/conflict/);assert.equal((admin.handleLocal('GET',`${base}/${skill.skillId}/history`,context,{}).body.revisions as unknown[]).length,2);const next=admin.handleLocal('POST',`${base}/${skill.skillId}/revisions`,context,{skill:draft(assistantId),expectedRevision:2});assert.equal((next.body.skill as {revision:number}).revision,3);assert.equal((database.connection.prepare('SELECT revision FROM skills WHERE skill_id=?').get(skill.skillId) as {revision:number}).revision,2,'draft cannot deselect the active Skill');assert.equal((admin.handleLocal('GET',`/api/authority/v1/assistants/${assistantId}/grants`,context,{}).body.grants as unknown[]).length,0);assert.equal((await admin.handle('POST',`${base}/${skill.skillId}/simulate`,context,{input:{text:'test'}},call())).body.liveEffects,false);});

test('authenticated HTTP tools await providers and logout fences late discovery',async t=>{
 const {createLifestreamServer}=await import('../src/index.ts'),{loadProfile}=await import('../src/config/loader.ts');
 const root=mkdtempSync(join(tmpdir(),'ls-async-tools-'));t.after(()=>rmSync(root,{recursive:true,force:true}));
 const config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'data.sqlite'),artifactDirectory:join(root,'artifacts')};
 const installerToken=password(),schemas=FixtureCapabilityProvider.schemaArtifacts([capability],()=>true),provider=new FixtureCapabilityProvider([capability],schemas),app=createLifestreamServer({config,capabilityProvider:provider,capabilitySchemas:schemas,localAuth:{stateDirectory:join(root,'safety'),installerToken}});await app.start();t.after(()=>app.shutdown());
 const base=`http://127.0.0.1:${app.address().port}`,headers:Record<string,string>={origin:base,'content-type':'application/json'};
 const request=(path:string,body?:unknown)=>fetch(base+path,{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:JSON.stringify(body)})});
 const setup=await request('/api/auth/v1/setup',{username:'owner',password:password(),installerToken});headers.cookie=setup.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=((await setup.json()) as any).session.csrfToken;
 const created=await (await request('/api/admin/v1/assistants',{displayName:'Synthetic Async Tools'})).json() as any,path=`/api/authority/v1/assistants/${created.assistantId}`;
 const listing=await request(path+'/tools');assert.equal(listing.status,200);const listed=(await listing.json()) as any;assert.equal(listed.tools[0].id,capability.id);assert.match(listed.tools[0].inputSchemaRef.sha256,/^[a-f0-9]{64}$/);
 const pending=await (await request(path+'/grants',{scope:[capability.id],durationSeconds:60,durationMode:'allowOnce'})).json() as any;
 assert.equal((await request(path+`/grants/${pending.grant.id}/decision`,{expectedRevision:1,decision:'active'})).status,200);
 const inspect=new Database({path:config.storage.databasePath});t.after(()=>inspect.close());
 const originalInvoke=provider.invoke.bind(provider);let claimedBeforeProvider=false;
 provider.invoke=async(invocation,definition,context)=>{
   const record=inspect.connection.prepare('SELECT identity_json FROM governed_admission_evidence WHERE invocation_id=?').get(invocation.invocationId) as {identity_json:string}|undefined;
   assert.ok(record);const checked=JSON.parse(record.identity_json);
   assert.equal(checked.capabilityId,definition.id);assert.equal(checked.binding.capabilityVersion,definition.version);
   assert.equal(checked.binding.providerRoute,definition.route);assert.equal(checked.assistantId,created.assistantId);
   assert.equal(checked.binding.snapshotId,invocation.snapshotId);assert.equal(checked.binding.deadlineAt,context.deadlineAt);
   assert.ok(inspect.connection.prepare('SELECT claimed_at FROM governed_dispatch_claims WHERE invocation_id=?').get(invocation.invocationId));
   claimedBeforeProvider=true;return originalInvoke(invocation,definition,context);
 };
 const invoked=await request(path+`/tools/${capability.id}/invoke`,{grantId:pending.grant.id,input:{text:'synthetic'}});assert.equal(invoked.status,200);const result=(await invoked.json()) as any;assert.equal(result.result.lifecycle,'succeeded');assert.deepEqual(result.result.outputSchema,listed.tools[0].outputSchemaRef);assert.equal(claimedBeforeProvider,true);
 let release!:()=>void,entered!:()=>void;const held=new Promise<void>(resolve=>{release=resolve;}),started=new Promise<void>(resolve=>{entered=resolve;});const original=provider.getSnapshot.bind(provider);
 provider.getSnapshot=async(input,context)=>{entered();await held;return original(input,{...context,isCurrent:()=>true});};
 const slow=request(path+'/tools');await started;assert.equal((await request('/api/auth/v1/sign-out',{})).status,200);release();
 const revoked=await slow;assert.equal(revoked.status,503);assert.equal(((await revoked.json()) as any).code,'capability_unavailable');
});
