import assert from 'node:assert/strict';
import test from 'node:test';
import {randomBytes} from 'node:crypto';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Database,MemoryRepository} from '@lifestream/storage-sqlite';
import {FixtureInferenceProvider} from '@lifestream/runtime/inference/fixture';
import {createLifestreamServer} from '../src/index.ts';
import {loadProfile} from '../src/config/loader.ts';
test('private authenticated search composes semantic selection, zero results and withdrawal/audience fences',{timeout:30000},async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-semantic-memory-http-'));let app:ReturnType<typeof createLifestreamServer>|undefined,db:Database|undefined;t.after(async()=>{await app?.shutdown();db?.close();await rm(root,{recursive:true,force:true});});
 const original=FixtureInferenceProvider.prototype.generate;let calls=0;FixtureInferenceProvider.prototype.generate=async function*(request){const data=JSON.parse(request.sections.at(-1)!.content);assert.equal(data.task,'semantic-memory-recall-v1');calls++;const chosen=data.query==='What equipment can deter bugs from sprouts?'?data.candidates.filter((c:any)=>c.id==='guidance'):[];yield {kind:'text',text:JSON.stringify({version:1,queryDigest:data.queryDigest,sourceDigest:data.sourceDigest,items:chosen.map((c:any)=>({id:c.id,revision:c.revision,rationale:'Retained participant guidance addresses protecting seedlings; applicability unverified.'}))})};yield {kind:'done'};};t.after(()=>{FixtureInferenceProvider.prototype.generate=original;});
 const config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'state.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex');app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'safety'),installerToken},audiencePrivacy:{sourceIds:[]}});await app.start();const base='http://127.0.0.1:'+app.address().port,headers:Record<string,string>={'content-type':'application/json',origin:base};
 const request=async(path:string,body:unknown,expected=200)=>{const response=await fetch(base+path,{method:'POST',headers,body:JSON.stringify(body)}),data=await response.json();assert.equal(response.status,expected,JSON.stringify(data));if(response.headers.get('set-cookie'))headers.cookie=response.headers.get('set-cookie')!.split(';')[0]!;if(data.session)headers['x-lifestream-csrf']=data.session.csrfToken;return data;};
 const setup=await request('/api/auth/v1/setup',{username:'owner',password:randomBytes(32).toString('hex'),installerToken},201),actor=setup.session.principalId;await request('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'});await request('/api/runtime/v1/audience',{mode:'solo',seconds:300});
 const assistant=await request('/api/admin/v1/assistants',{displayName:'Synthetic semantic search'},201),assistantId=assistant.assistantId;await request('/api/admin/v1/assistants/'+assistantId+'/activate',{profileId:assistant.profile.profileId,expectedActiveRevision:null});const relationship=(await request('/api/admin/v1/assistants/'+assistantId+'/relationships',{},201)).relationship;
 await request('/api/runtime/v1/memory',{assistantId,relationshipId:relationship.relationshipId,enabled:true,expectedRevision:0});
 db=new Database({path:config.storage.databasePath});const memories=new MemoryRepository(db);for(const [id,content] of [['guidance','Participant advice: Put fine netting over the vegetable bed.'],['literal','Quoted typing exercise: What equipment can deter bugs from sprouts?']] as const){memories.save({id,assistantId,content,provenance:{actor,relationshipId:relationship.relationshipId,sourceFamily:'fixture:'+id},lifecycle:{status:'candidate',revision:1,kind:'proceduralHint',factuality:'unverified',lastReinforcedAt:null},createdAt:new Date().toISOString()});memories.transition(assistantId,id,'active',actor);}
 const path='/api/admin/v1/assistants/'+assistantId+'/memories/search',found=await request(path,{query:'What equipment can deter bugs from sprouts?'});assert.deepEqual(found.memories.map((r:any)=>r.id),['guidance']);assert.equal(found.semanticSelection.state,'selected');const empty=await request(path,{query:'How do volcanic islands form?'});assert.equal(empty.memories.length,0);assert.equal(empty.semanticSelection.state,'empty');assert.equal(calls,2);
 await request('/api/runtime/v1/memory',{assistantId,relationshipId:relationship.relationshipId,enabled:false,expectedRevision:1});await request(path,{query:'What equipment can deter bugs from sprouts?'},503);assert.equal(calls,2);await request('/api/runtime/v1/audience',{mode:'shared',seconds:300});await request(path,{query:'What equipment can deter bugs from sprouts?'},403);assert.equal(calls,2);
});
