import assert from 'node:assert/strict';
import test from 'node:test';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes,randomUUID} from 'node:crypto';
import {createLifestreamServer} from '../src/index.ts';
import {loadProfile} from '../src/config/loader.ts';
import {FixtureInferenceProvider} from '@lifestream/runtime/inference/fixture';

test('authenticated session context projects only its own active conversation for native binding',{timeout:15000},async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-session-binding-'));t.after(()=>rm(root,{recursive:true,force:true}));
 const config=loadProfile('test');config.storage={databasePath:join(root,'state.sqlite'),artifactDirectory:join(root,'artifacts')};config.authority.authentication='local-password';
 const password=randomBytes(24).toString('hex'),installerToken=randomBytes(32).toString('hex'),app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'auth'),installerToken}});
 await app.start();t.after(()=>app.shutdown());const base=`http://127.0.0.1:${app.address().port}`,headers:Record<string,string>={origin:base,'content-type':'application/json'};
 const request=(path:string,body?:unknown)=>fetch(base+path,{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:JSON.stringify(body)})});
 assert.equal((await request('/api/runtime/v1/session-context')).status,401);
 const setup=await request('/api/auth/v1/setup',{username:'owner',password,installerToken});headers.cookie=setup.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=(await setup.json()).session.csrfToken;
 assert.equal((await(await request('/api/runtime/v1/session-context')).json()).conversationId,null);
 const bindingKey=randomUUID();await request('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession',bindingKey});
 const first=await(await request('/api/runtime/v1/session-context')).json();assert.match(first.conversationId,/^[a-f0-9-]{36}$/);const oldCookie=headers.cookie;
 const signIn=await request('/api/auth/v1/sign-in',{username:'owner',password});headers.cookie=signIn.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=(await signIn.json()).session.csrfToken;
 await request('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession',bindingKey});
 const second=await(await request('/api/runtime/v1/session-context')).json();assert.notEqual(second.conversationId,first.conversationId);assert.equal(second.endpoint.endpointId,first.endpoint.endpointId);
 const unchanged=await(await fetch(base+'/api/runtime/v1/session-context',{headers:{...headers,cookie:oldCookie}})).json();assert.equal(unchanged.conversationId,first.conversationId);
 await request('/api/auth/v1/sign-out',{});assert.equal((await request('/api/runtime/v1/session-context')).status,401);
});

test('structured session settings preview without mutation and apply only current authenticated revisions',{timeout:15000},async t=>{
 const root=await mkdtemp(join(tmpdir(),'ls-session-definition-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.storage={databasePath:join(root,'state.sqlite'),artifactDirectory:join(root,'artifacts')};config.authority.authentication='local-password';const password=randomBytes(24).toString('hex'),installerToken=randomBytes(32).toString('hex');let app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'auth'),installerToken},audiencePrivacy:{sourceIds:[]}});await app.start();t.after(()=>app.shutdown());const port=app.address().port,base=`http://127.0.0.1:${port}`,headers:Record<string,string>={origin:base,'content-type':'application/json'};
 const request=(path:string,body?:unknown,extra={})=>fetch(base+path,{method:body===undefined?'GET':'POST',headers:{...headers,...extra},...(body===undefined?{}:{body:JSON.stringify(body)})});const path='/api/runtime/v1/session-definition';assert.equal((await request(path)).status,401);const setup=await request('/api/auth/v1/setup',{username:'owner',password,installerToken});headers.cookie=setup.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=(await setup.json()).session.csrfToken;assert.equal((await request(path)).status,403);
 const bindingKey=randomUUID();await request('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'unknown',bindingKey});await request('/api/runtime/v1/audience',{mode:'solo',seconds:300});const current=await(await request(path)).json();assert.deepEqual(current.definition,{schemaVersion:'1.0.0',mode:'text',audienceScope:'unknown'});assert.equal(current.sessionRevision,1);
 const definition={...current.definition,audienceScope:'authenticatedSession'},previewRequest={operation:'preview',definition,expectedRevision:current.sessionRevision};const preview=await request(path,previewRequest);assert.equal(preview.status,200);const reviewed=await preview.json();assert.equal(reviewed.changes.length,1);assert.equal(reviewed.changes[0].field,'audienceScope');assert.equal((await(await request('/api/runtime/v1/session-context')).json()).revision,1);assert.equal((await(await request(path)).json()).definition.audienceScope,'unknown');
 for(const operation of [['apply'],['preview'],'unsupported'])assert.equal((await request(path,{...previewRequest,operation})).status,422);
 const apply={...previewRequest,operation:'apply',reviewDigest:reviewed.reviewDigest};assert.equal((await request(path,apply,{'x-lifestream-csrf':'wrong'})).status,403);assert.equal((await request(path,{...apply,definition:{...definition,mode:'audio'}})).status,409);assert.equal((await request(path,apply)).status,200);const after=await(await request(path)).json();assert.equal(after.sessionRevision,2);assert.equal(after.definition.audienceScope,'authenticatedSession');assert.equal((await request(path,apply)).status,409);
 for(const invalid of [{...definition,provider:'replace'},{...definition,mode:'camera'},{...definition,mode:['text']},{...definition,audienceScope:['unknown']},{...definition,script:'execute'},{...definition,scope:'default'},{...definition,principalId:'another'},{...definition,schemaVersion:'2.0.0'}])assert.equal((await request(path,{operation:'preview',definition:invalid,expectedRevision:2})).status,422);
 assert.equal((await request(path,{operation:'preview',definition:{...definition,mode:'audio'},expectedRevision:2})).status,409,'unconfigured audio cannot be previewed as available');
 const pending=await(await request(path,{operation:'preview',definition:current.definition,expectedRevision:2})).json();await request('/api/runtime/v1/audience',{mode:'shared'});assert.equal((await request(path,{operation:'apply',definition:current.definition,expectedRevision:2,reviewDigest:pending.reviewDigest})).status,403);await request('/api/runtime/v1/audience',{mode:'solo',seconds:300});assert.equal((await request(path,{operation:'apply',definition:current.definition,expectedRevision:2,reviewDigest:pending.reviewDigest})).status,409,'audience changes invalidate review even when solo returns');
 const ownerCookie=headers.cookie,ownerCsrf=headers['x-lifestream-csrf'];const signedIn=await request('/api/auth/v1/sign-in',{username:'owner',password});headers.cookie=signedIn.headers.get('set-cookie')!.split(';')[0]!;headers['x-lifestream-csrf']=(await signedIn.json()).session.csrfToken;await request('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'unknown',bindingKey});await request('/api/runtime/v1/audience',{mode:'solo',seconds:300});assert.equal((await(await request(path)).json()).definition.audienceScope,'unknown');headers.cookie=ownerCookie;headers['x-lifestream-csrf']=ownerCsrf;
 await app.shutdown();app=createLifestreamServer({config,port,localAuth:{stateDirectory:join(root,'auth'),installerToken},audiencePrivacy:{sourceIds:[]}});await app.start();assert.equal((await request(path)).status,403);await request('/api/runtime/v1/audience',{mode:'solo',seconds:300});assert.equal((await(await request(path)).json()).definition.audienceScope,'authenticatedSession');assert.equal((await request(path+'?sessionId=other')).status,422);
 // Two supported negotiated configurations, still without any physical capture/playback.
 (app as any).providers.stt={};(app as any).providers.tts={};const voiceDefinition={schemaVersion:'1.0.0',mode:'audio',audienceScope:'authenticatedSession'},audioReview=await(await request(path,{operation:'preview',definition:voiceDefinition,expectedRevision:2})).json();assert.equal((await request(path,{operation:'apply',definition:voiceDefinition,expectedRevision:2,reviewDigest:audioReview.reviewDigest})).status,200);assert.deepEqual((await(await request('/api/runtime/v1/session-context')).json()).endpoint.inputModalities,['text','audio']);
 // Applying a disclosure boundary through this same operation fences an actual pending typed turn.
 const assistant=await(await request('/api/admin/v1/assistants',{displayName:'Synthetic definition fence'})).json();await request(`/api/admin/v1/assistants/${assistant.assistantId}/activate`,{profileId:assistant.profile.profileId,expectedActiveRevision:null});let enter:()=>void=()=>{},release:()=>void=()=>{};const entered=new Promise<void>(r=>{enter=r;}),gate=new Promise<void>(r=>{release=r;});t.after(release);t.mock.method(FixtureInferenceProvider.prototype,'generate',async function*(){enter();await gate;yield {kind:'text',text:'LATE_SYNTHETIC_OUTPUT'};yield {kind:'done'};});
 const pendingTurn=request('/api/runtime/v1/messages',{assistantId:assistant.assistantId,userInput:'Synthetic fence request.'});await entered;const restricted={...voiceDefinition,audienceScope:'unknown'},restriction=await(await request(path,{operation:'preview',definition:restricted,expectedRevision:3})).json();try{assert.equal((await request(path,{operation:'apply',definition:restricted,expectedRevision:3,reviewDigest:restriction.reviewDigest})).status,200);}finally{release();}const output=await(await pendingTurn).text();assert.doesNotMatch(output,/LATE_SYNTHETIC_OUTPUT/);assert.match(output,/runtime_input_stale/);assert.doesNotMatch(output,/interaction.completed/);

});
