import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
import {crc32} from 'node:zlib';
import {createServer} from 'node:http';
import {fixtureEpisode,fixtureGameHelpItem} from '../../../packages/runtime/test/fixtures/game-memory.ts';
import {TelegramGameHelpAttachmentTransport} from '../src/channels/telegram-game-help-attachment.ts';
const token='9999:synthetic_credential_not_for_live_use';
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4//8/AwAI/AL+5gz/qwAAAABJRU5ErkJggg==','base64');
function fixture(){const now=Date.now(),e=fixtureEpisode(now),item=fixtureGameHelpItem(e,now),digest=createHash('sha256').update(png).digest('hex');item.screenshotStatus='ready';item.imageTransportSupported=true;item.question='Which visible lever would you try?';item.attemptsSummary='The visible gate stayed closed.';
 item.screenshot={sourceDomain:'simulatedGame',captureRegion:'gameFramebuffer',screenshotId:randomUUID(),observationId:item.sourceObservationIds[0]!,activityId:item.scope.activityId,runId:item.scope.runId,timelineId:item.scope.timelineId,frameNumber:30,capturedAt:new Date(now-100).toISOString(),sha256:digest,byteLength:png.length,mediaType:'image/png',width:1,height:1,attachmentArtifact:{reference:'test-only:private-game-attachment',sha256:digest,byteLength:png.length,mediaType:'image/png',schemaRef:'test-only:framebuffer-png'},retentionPolicyRef:'test-only:separate-image-retention',expiresAt:new Date(now+60000).toISOString(),ageAtSendMs:null,captureTimeDisclosed:false};
 let current=true;return {item,bytes:new Uint8Array(png),now,current:()=>current,withdraw:()=>current=false};}
const controller=()=>new AbortController();
function receipt(init:RequestInit|undefined,overrides:Record<string,unknown>={}){const body=init!.body as FormData;return new Response(JSON.stringify({ok:true,result:{message_id:42,chat:{id:1234,type:'private'},caption:body.get('caption'),photo:[{file_id:'synthetic:provider-photo',width:1,height:1}],...overrides}}));}
const options=(f:ReturnType<typeof fixture>)=>({botId:'9999',token:()=>token,enabled:()=>true,now:()=>f.now});
test('image transport stays separately disabled by default; existing chat activation is insufficient',async()=>{const f=fixture();let calls=0;const api=new TelegramGameHelpAttachmentTransport({botId:'9999',token:()=>token,fetch:async()=>{calls++;throw Error('not allowed');}});assert.equal((await api.send(f.item,'1234',f.bytes,controller().signal,f.current)).status,'notStarted');assert.equal(calls,0);api.close();});
test('bounded multipart upload carries exact PNG, attempts, question and honest capture age without private lineage or formatting',async()=>{const f=fixture();let body!:FormData;const api=new TelegramGameHelpAttachmentTransport({...options(f),fetch:async(url,init)=>{assert.equal(String(url),`https://api.telegram.org/bot${token}/sendPhoto`);assert.equal(init!.redirect,'error');assert.equal(init!.headers,undefined);body=init!.body as FormData;return receipt(init);}});
 const r=await api.send(f.item,'1234',f.bytes,controller().signal,(item,chat)=>{assert.equal(chat,'1234');assert.ok(Object.isFrozen(item.scope));return f.current();});assert.deepEqual(r,{status:'accepted',messageId:42,attachmentStatus:'sent',deliveryStatus:'unknown',capturedAt:f.item.screenshot!.capturedAt,ageAtSendMs:100});assert.deepEqual([...body.keys()].sort(),['allow_paid_broadcast','caption','chat_id','photo','protect_content']);assert.equal(body.get('chat_id'),'1234');assert.equal(body.get('protect_content'),'true');assert.equal(body.get('allow_paid_broadcast'),'false');const photo=body.get('photo') as File;assert.equal(photo.name,'game-frame.png');assert.equal(photo.type,'image/png');assert.deepEqual(new Uint8Array(await photo.arrayBuffer()),f.bytes);assert.match(String(body.get('caption')),/age at dispatch 100 ms/);assert.match(String(body.get('caption')),/Which visible lever/);for(const secret of [f.item.scope.principalId,f.item.scope.relationshipId!,f.item.helpId,f.item.recipientRef,f.item.screenshot!.attachmentArtifact.reference])assert.equal(String(body.get('caption')).includes(secret),false);assert.equal(f.item.status,'queued');assert.equal(f.item.screenshot!.ageAtSendMs,null);api.close();});
test('invalid or unqualified source, image, private destination or credential never starts transport',async()=>{for(const reason of ['source','timeline','digest','expiry','future','pending','oldReceipt','unsupported','caption','group','credential'] as const){const f=fixture();let calls=0;const api=new TelegramGameHelpAttachmentTransport({...options(f),token:()=>reason==='credential'?'invalid':token,fetch:async()=>{calls++;throw Error('must not call');}});
 if(reason==='source')f.withdraw();if(reason==='timeline')f.item.screenshot!.timelineId=randomUUID();if(reason==='digest')f.bytes[42]^=1;if(reason==='expiry')f.item.screenshot!.expiresAt=new Date(f.now).toISOString();if(reason==='future')f.item.screenshot!.capturedAt=new Date(f.now+1).toISOString();if(reason==='pending')f.item.screenshotStatus='pending';if(reason==='oldReceipt')f.item.messageSentEvidenceRef='test-only:old-send';if(reason==='unsupported')f.item.imageTransportSupported=false;if(reason==='caption')f.item.question='long '.repeat(210);
 assert.equal((await api.send(f.item,reason==='group'?'-1234':'1234',f.bytes,controller().signal,f.current)).status,'notStarted',reason);assert.equal(calls,0,reason);api.close();}});
test('metadata code and proxies rejected; byte snapshot uses intrinsics without caller getters or iterator execution',async()=>{const f=fixture();let touched=0,calls=0;const api=new TelegramGameHelpAttachmentTransport({...options(f),fetch:async(_url,init)=>{calls++;return receipt(init);}});const bad={...f.item};Object.defineProperty(bad,'question',{enumerable:true,get(){touched++;return 'forged';}});assert.equal((await api.send(bad,'1234',f.bytes,controller().signal,f.current)).status,'notStarted');assert.equal((await api.send(new Proxy(f.item,{get(){touched++;throw Error();}}),'1234',f.bytes,controller().signal,f.current)).status,'notStarted');assert.equal((await api.send(f.item,'1234',new Proxy(f.bytes,{get(){touched++;throw Error();}}),controller().signal,f.current)).status,'notStarted');Object.defineProperty(f.bytes,'byteLength',{get(){touched++;throw Error();}});Object.defineProperty(f.bytes,'buffer',{get(){touched++;throw Error();}});Object.defineProperty(f.bytes,Symbol.iterator,{value:()=>{touched++;throw Error();}});assert.equal((await api.send(f.item,'1234',f.bytes,controller().signal,f.current)).status,'accepted');assert.equal(touched,0);assert.equal(calls,1);api.close();});
test('PNG metadata, trailing bytes, corrupt CRC, dimensions and oversized/shared buffers are withheld',async()=>{for(const reason of ['metadata','trailing','crc','dimensions','large','shared'] as const){const f=fixture();let calls=0;const api=new TelegramGameHelpAttachmentTransport({...options(f),fetch:async()=>{calls++;throw Error();}});if(reason==='metadata'){const text=Buffer.from('key\0private overlay text'),chunk=Buffer.alloc(text.length+12);chunk.writeUInt32BE(text.length,0);chunk.write('tEXt',4);text.copy(chunk,8);chunk.writeUInt32BE(crc32(chunk.subarray(4,-4)),chunk.length-4);f.bytes=new Uint8Array(Buffer.concat([png.subarray(0,-12),chunk,png.subarray(-12)]));}if(reason==='trailing')f.bytes=new Uint8Array(Buffer.concat([png,Buffer.from([0])]));if(reason==='crc')f.bytes[29]^=1;if(reason==='dimensions')f.item.screenshot!.width=2;if(reason==='large')f.bytes=new Uint8Array(2097153);if(reason==='shared'){f.bytes=new Uint8Array(new SharedArrayBuffer(png.length));f.bytes.set(png);}const s=f.item.screenshot!;s.sha256=s.attachmentArtifact.sha256=createHash('sha256').update(f.bytes).digest('hex');s.byteLength=s.attachmentArtifact.byteLength=f.bytes.length;assert.equal((await api.send(f.item,'1234',f.bytes,controller().signal,f.current)).status,'notStarted',reason);assert.equal(calls,0);api.close();}});
test('server text success, wrong recipient, oversized or invalid response cannot prove an image sent or delivered',async()=>{for(const reason of ['text','foreign','caption','business','invalidUtf8','large','wrongOk'] as const){const f=fixture();const api=new TelegramGameHelpAttachmentTransport({...options(f),fetch:async(_url,init)=>{if(reason==='invalidUtf8')return new Response(new Uint8Array([255]));if(reason==='large')return new Response('x'.repeat(65537));if(reason==='wrongOk')return new Response(JSON.stringify({ok:false}),{status:200});return receipt(init,reason==='text'?{photo:undefined}:reason==='foreign'?{chat:{id:8888,type:'private'}}:reason==='caption'?{caption:'changed question'}:{business_connection_id:'foreign'});}});const r=await api.send(f.item,'1234',f.bytes,controller().signal,f.current);assert.equal(r.status,'unknown',reason);assert.equal(r.attachmentStatus,'unknown');assert.equal(r.deliveryStatus,'unknown');assert.equal(r.messageId,null);api.close();}});
test('unknown and rejected attempts never retry or leak errors; one help identity is fenced for this instance',async()=>{for(const rejected of [false,true]){const f=fixture();let calls=0;const api=new TelegramGameHelpAttachmentTransport({...options(f),fetch:async()=>{calls++;if(rejected)return new Response(JSON.stringify({ok:false,description:token}),{status:403});throw Error(token);}});const r=await api.send(f.item,'1234',f.bytes,controller().signal,f.current);assert.equal(r.status,rejected?'rejected':'unknown');assert.equal(r.deliveryStatus,'unknown');assert.equal(JSON.stringify(r).includes(token),false);assert.equal((await api.send(f.item,'1234',f.bytes,controller().signal,f.current)).status,'notStarted');assert.equal(calls,1);api.close();}});
test('abort-ignoring fetch is quarantined and late acceptance cannot restart or upgrade the aborted operation',async()=>{const f=fixture(),c=controller();let finish!:(r:Response)=>void,init!:RequestInit,calls=0;const api=new TelegramGameHelpAttachmentTransport({...options(f),fetch:async(_url,i)=>{calls++;init=i!;return await new Promise<Response>(resolve=>finish=resolve);}});const pending=api.send(f.item,'1234',f.bytes,c.signal,f.current);assert.equal(calls,1);c.abort();assert.equal((await pending).status,'unknown');const next={...f.item,helpId:randomUUID()};assert.equal((await api.send(next,'1234',f.bytes,controller().signal,f.current)).status,'notStarted');finish(receipt(init));await new Promise<void>(resolve=>setImmediate(resolve));assert.equal((await api.send(f.item,'1234',f.bytes,controller().signal,f.current)).status,'notStarted');assert.equal(calls,1);api.close();});
test('source withdrawal aborts outstanding image work without granting resume or a delivery receipt',async()=>{const f=fixture();let started!:AbortSignal;const api=new TelegramGameHelpAttachmentTransport({...options(f),fetch:async(_url,init)=>{started=init!.signal!;return await new Promise<Response>((_resolve,reject)=>started.addEventListener('abort',()=>reject(Error('synthetic canceled')),{once:true}));}});const pending=api.send(f.item,'1234',f.bytes,controller().signal,f.current);f.withdraw();const r=await pending;assert.equal(started.aborted,true);assert.equal(r.status,'unknown');assert.equal(r.deliveryStatus,'unknown');assert.equal(f.item.status,'queued');api.close();});
test('close fences active work and future calls even if the transport returns a late valid receipt',async()=>{const f=fixture();let finish!:(r:Response)=>void,init!:RequestInit;const api=new TelegramGameHelpAttachmentTransport({...options(f),fetch:async(_url,i)=>{init=i!;return await new Promise<Response>(resolve=>finish=resolve);}});const pending=api.send(f.item,'1234',f.bytes,controller().signal,f.current);api.close();assert.equal((await pending).status,'unknown');finish(receipt(init));assert.equal((await api.send({...f.item,helpId:randomUUID()},'1234',f.bytes,controller().signal,f.current)).status,'notStarted');});
test('original bounded deadline completes an ignored fetch without allowing replacement fanout',async()=>{const f=fixture();let calls=0,finish!:(r:Response)=>void,init!:RequestInit;const api=new TelegramGameHelpAttachmentTransport({...options(f),timeoutMs:25,fetch:async(_url,i)=>{calls++;init=i!;return await new Promise<Response>(resolve=>finish=resolve);}});const r=await api.send(f.item,'1234',f.bytes,controller().signal,f.current);assert.equal(r.status,'unknown');assert.equal(init.signal!.aborted,true);assert.equal((await api.send({...f.item,helpId:randomUUID()},'1234',f.bytes,controller().signal,f.current)).status,'notStarted');assert.equal(calls,1);finish(receipt(init));api.close();});
test('clock rollback and expiry during transport prevent false success',async()=>{for(const expiry of [false,true]){const f=fixture();let now=f.now;const api=new TelegramGameHelpAttachmentTransport({...options(f),now:()=>now,fetch:async(_url,init)=>{now=expiry?Date.parse(f.item.screenshot!.expiresAt):f.now-1;return receipt(init);}});assert.equal((await api.send(f.item,'1234',f.bytes,controller().signal,f.current)).status,'unknown');api.close();}});
test('captured immutable source and binary snapshot survive caller mutation after dispatch',async()=>{const f=fixture();let body!:FormData;const api=new TelegramGameHelpAttachmentTransport({...options(f),fetch:async(_url,init)=>{body=init!.body as FormData;f.item.question='changed afterward';f.bytes.fill(0);return receipt(init);}});assert.equal((await api.send(f.item,'1234',f.bytes,controller().signal,()=>true)).status,'accepted');assert.match(String(body.get('caption')),/Which visible lever/);assert.doesNotMatch(String(body.get('caption')),/changed afterward/);assert.deepEqual(Buffer.from(await (body.get('photo') as File).arrayBuffer()),png);api.close();});
test('trusted setup reentrancy cannot reserve a second request slot',async()=>{const f=fixture();let entered=false,calls=0,nested!:Promise<unknown>;let api!:TelegramGameHelpAttachmentTransport;api=new TelegramGameHelpAttachmentTransport({...options(f),enabled:()=>{if(!entered){entered=true;nested=api.send({...f.item,helpId:randomUUID()},'1234',f.bytes,controller().signal,f.current);}return true;},fetch:async(_url,init)=>{calls++;return receipt(init);}});assert.equal((await api.send(f.item,'1234',f.bytes,controller().signal,f.current)).status,'accepted');assert.equal((await nested as {status:string}).status,'notStarted');assert.equal(calls,1);api.close();});
test('finite per-instance attempt fence refuses capacity instead of evicting and resending an old topic',async()=>{const f=fixture();let calls=0;const api=new TelegramGameHelpAttachmentTransport({...options(f),fetch:async(_url,init)=>{calls++;return receipt(init);}});const original=f.item.helpId;for(let i=0;i<128;i++){f.item.helpId=randomUUID();assert.equal((await api.send(f.item,'1234',f.bytes,controller().signal,f.current)).status,'accepted');}f.item.helpId=original;assert.equal((await api.send(f.item,'1234',f.bytes,controller().signal,f.current)).status,'notStarted');assert.equal(calls,128);api.close();});
test('real isolated HTTP carries bounded multipart PNG; response is synthetic and never contacts Telegram',async t=>{
 const f=fixture();let caption='',wire=Buffer.alloc(0),contentType='';const server=createServer(async(req,res)=>{const chunks:Buffer[]=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>65536){res.writeHead(413);res.end();return;}chunks.push(chunk);}wire=Buffer.concat(chunks);contentType=String(req.headers['content-type']);const marker=Buffer.from('name="caption"\r\n\r\n'),start=wire.indexOf(marker)+marker.length,end=wire.indexOf(Buffer.from('\r\n--'),start);const actualCaption=wire.subarray(start,end).toString('utf8');assert.equal(actualCaption,caption.replace(/\n/gu,'\r\n'));res.setHeader('content-type','application/json');res.end(JSON.stringify({ok:true,result:{message_id:73,chat:{id:1234,type:'private'},caption:actualCaption,photo:[{file_id:'synthetic:loopback-photo',width:1,height:1}]}}));});
 t.after(()=>new Promise<void>(resolve=>{server.closeAllConnections();server.close(()=>resolve());}));await new Promise<void>((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',()=>resolve());});const address=server.address();assert.ok(address&&typeof address!=='string');
 const api=new TelegramGameHelpAttachmentTransport({...options(f),fetch:async(url,init)=>{assert.equal(new URL(String(url)).hostname,'api.telegram.org');caption=String((init!.body as FormData).get('caption'));return await fetch(`http://127.0.0.1:${address.port}/synthetic-bot`,init);}});t.after(()=>api.close());const r=await api.send(f.item,'1234',f.bytes,controller().signal,f.current);assert.equal(r.status,'accepted');assert.equal(r.messageId,73);assert.equal(r.deliveryStatus,'unknown');assert.match(contentType,/^multipart\/form-data; boundary=/);assert.ok(wire.includes(png));assert.ok(wire.includes(Buffer.from(caption.replace(/\n/gu,'\r\n'))));assert.match(wire.toString('latin1'),/filename="game-frame.png"/);for(const secret of [f.item.helpId,f.item.recipientRef,f.item.scope.principalId,f.item.screenshot!.attachmentArtifact.reference,token])assert.equal(wire.includes(Buffer.from(secret)),false);assert.ok(wire.length<65536);
});
