import assert from 'node:assert/strict';
import test from 'node:test';
import {randomUUID} from 'node:crypto';
import {Database,ChannelSubscriptionRepository,TelegramPairingRepository} from '@lifestream/storage-sqlite';
import {TelegramAlerts} from '../src/channels/telegram-alerts.ts';
import {UrgentAttentionRuntime} from '../src/runtime/urgent-attention.ts';
import type {PwceCondition,PwceConditionResponse} from '@lifestream/providers-pwce';
const wait=async(check:()=>boolean)=>{for(let i=0;i<100;i++){if(check())return;await new Promise(r=>setTimeout(r,10));}throw Error('Alert transition timed out');};
function fixture(){
 const database=new Database({path:':memory:'});database.migrate();const assistant=randomUUID(),owner=randomUUID(),person=randomUUID(),subscriptions=new ChannelSubscriptionRepository(database),pairs=new TelegramPairingRepository(database),sessions=new Map<string,{sessionId:string;endpointId:string;revision:number}>(),conditions:PwceCondition[]=[],sourceBinding={sourceRef:'source',eventClass:'critical-condition',worldRef:'world',siteRef:'site',zoneRef:'zone',label:'Synthetic zone'};
 for(const [id,name,isOwner] of [[owner,'owner',1],[person,'member',0]] as const)database.connection.prepare('INSERT INTO local_accounts(principal_id,username,owner,password_verifier,created_at) VALUES(?,?,?,?,?)').run(id,name,isOwner,'synthetic',Date.now());database.connection.prepare('INSERT INTO local_assistant_permissions VALUES(?,?,1)').run(owner,assistant);
 const policy=new UrgentAttentionRuntime(database,{bindings:[sourceBinding],allowSynthetic:true});let available=true,admitted=true,release:undefined|(()=>void),hold=false;const sent:string[]=[];
 const response=(operation:'snapshot'|'changes',cursor=0):PwceConditionResponse=>({profileId:'synthetic',profileVersion:'1.0.0',operation,status:'ok',evaluatedAt:new Date().toISOString(),conditions:structuredClone(conditions.slice(cursor)),nextCursor:conditions.length,hasMore:false,resyncReason:null,acknowledgment:null,replay:true});
 const options={database,botId:'9999',ready:()=>available,assistantAvailable:()=>true,session:(b:{subscriptionId:string})=>{let s=sessions.get(b.subscriptionId);if(!s){s={sessionId:randomUUID(),endpointId:randomUUID(),revision:1};sessions.set(b.subscriptionId,s);}return s;},runtime:policy,pollIntervalMs:30000,source:{snapshot:async()=>response('snapshot'),changes:async(cursor:number)=>response('changes',cursor)},authority:(b:{assistantId:string;subscriptionId:string},s:{sessionId:string;endpointId:string})=>({scope:{assistantId:b.assistantId,endpointId:s.endpointId,sessionId:s.sessionId,environment:'synthetic',authorityContextRef:{providerRef:'synthetic',contextId:b.subscriptionId,revision:1}},current:()=>admitted,dispatch:async(r:{invocationId:string})=>({invocationId:r.invocationId,status:'admitted' as const,grantRevision:1})}),api:{send:async(chat:string)=>{sent.push(chat);if(hold)await new Promise<void>(r=>release=r);return {status:'accepted' as const,messageId:1};}}};
 const alerts=new TelegramAlerts(options),pair=(chat:string,principalId=person)=>{const sub=subscriptions.apply(assistant,owner,{operation:'create',principalId,channel:'telegram',label:'Synthetic '+chat,requestedConversations:true,requestedAlerts:true}),issued=pairs.issue(assistant,sub.id,principalId,1,'9999');pairs.claim('9999',issued.challenge,{chatId:chat,userId:chat,privateChat:true,isBot:false,sentAt:Date.now()});const claimed=pairs.inspect(assistant,sub.id,principalId),paired=pairs.confirm(assistant,sub.id,principalId,claimed.revision,claimed.claimId!);pairs.enable(assistant,sub.id,principalId,paired.revision,false,true);alerts.reconcile();return sub;};
 const configure=(id:string)=>{const route=alerts.ownerRoute(assistant,owner,id)!;policy.configure(route.scope,{expectedRevision:policy.settings(route.scope).revision,rules:[{sourceRef:'source',eventClass:'critical-condition',enabled:true,bypassQuietHours:false}],quietHours:null,modality:'text',snoozedUntil:null});return route;};
 const emit=()=>{const at=new Date().toISOString();conditions.push({sourceRef:'source',eventClass:'critical-condition',worldRef:'world',siteRef:'site',zoneRef:'zone',conditionRef:'condition.'+conditions.length,revision:1,sourceRevision:1,status:'open',transition:'open',severity:'critical',summary:'PRIVATE',occurredAt:at,receivedAt:at,updatedAt:at,freshUntil:new Date(Date.now()+60000).toISOString(),expiresAt:new Date(Date.now()+120000).toISOString(),freshness:'fresh',basis:'synthetic',qualification:{state:'qualified',confidence:1,limitations:[],evidenceRefs:[]}});};
 return {database,assistant,owner,person,subscriptions,pairs,alerts,policy,options,pair,configure,emit,sent,hold:()=>hold=true,release:()=>release?.(),unavailable:()=>available=false,deny:()=>admitted=false,close:()=>{alerts.close();database.close();}};
}
test('starting a second subscriber worker preserves another destination delivery already in flight',async t=>{
 const f=fixture();t.after(f.close);const first=f.pair('1234'),route=f.configure(first.id);await route.worker.tick();f.hold();f.emit();await route.worker.tick();await wait(()=>f.sent.length===1);const pending=route.worker.inspect(route.scope).deliveries[0]!;assert.equal(pending.state,'attempted');
 const second=f.pair('2345',f.owner);assert.ok(f.alerts.ownerRoute(f.assistant,f.owner,second.id));assert.deepEqual(route.worker.inspect(route.scope).deliveries[0],pending);f.release();await wait(()=>route.worker.inspect(route.scope).deliveries[0]?.state==='accepted');assert.equal(f.sent.length,1);
 assert.equal(f.alerts.inspectOwner(f.assistant,f.owner).length,2);assert.deepEqual(f.alerts.inspectOwner(f.assistant,f.person),[]);assert.equal(f.alerts.ownerRoute(f.assistant,f.person,first.id),undefined);
});
test('owner permission, subscription and account revocation remove destinations without granting recipient administration',t=>{
 const f=fixture();t.after(f.close);const first=f.pair('1234');assert.equal(f.alerts.inspectOwner(f.assistant,f.owner).length,1);assert.equal(f.database.connection.prepare('SELECT count(*) AS n FROM local_assistant_permissions WHERE principal_id=?').get(f.person)!.n,0);
 f.database.connection.prepare('UPDATE local_assistant_permissions SET administer=0 WHERE principal_id=?').run(f.owner);f.alerts.reconcile();assert.equal(f.alerts.inspectOwner(f.assistant,f.owner).length,0);
 f.database.connection.prepare('UPDATE local_assistant_permissions SET administer=1 WHERE principal_id=?').run(f.owner);f.alerts.reconcile();assert.equal(f.alerts.inspectOwner(f.assistant,f.owner).length,1);
 f.subscriptions.apply(f.assistant,f.owner,{operation:'disable',id:first.id,expectedRevision:1});f.alerts.reconcile();assert.equal(f.alerts.inspectOwner(f.assistant,f.owner).length,0);
 f.pair('2345');f.database.connection.prepare('UPDATE local_accounts SET disabled=1 WHERE principal_id=?').run(f.person);f.alerts.reconcile();assert.equal(f.alerts.inspectOwner(f.assistant,f.owner).length,0);assert.deepEqual(f.sent,[]);
});
test('capacity bounds alert workers and unavailable host or authority cannot configure a sending destination',t=>{
 const f=fixture();t.after(f.close);for(let i=0;i<8;i++)f.pair(String(2000+i));assert.equal(f.alerts.canEnable('new'),false);assert.equal(f.alerts.inspectOwner(f.assistant,f.owner).length,8);f.deny();f.alerts.reconcile();assert.equal(f.alerts.inspectOwner(f.assistant,f.owner).length,0);f.unavailable();assert.equal(f.alerts.available(),false);assert.equal(f.alerts.canEnable('new'),false);assert.deepEqual(f.sent,[]);
});
