import assert from 'node:assert/strict';
import test from 'node:test';
import {randomUUID} from 'node:crypto';
import {Database,ChannelSubscriptionRepository,TelegramPairingRepository} from '@lifestream/storage-sqlite';
import {CapabilityResolver} from '@lifestream/runtime/capabilities/resolver';
import type {CapabilityCallContext,AdmittedCapabilityInvocation} from '@lifestream/runtime/capabilities/ports';
import {TelegramNoticeProvider,telegramNoticeCapability} from '../src/channels/telegram-notice-provider.ts';
import {URGENT_AWAY_NOTICE,URGENT_AWAY_SIMULATION_NOTICE,UrgentAwayRuntime,type UrgentAwaySource} from '../src/runtime/urgent-away.ts';
import {UrgentAttentionRuntime} from '../src/runtime/urgent-attention.ts';
import type {PwceCondition} from '@lifestream/providers-pwce';
function fixture(){
 const db=new Database({path:':memory:'});db.migrate();const principal=randomUUID(),assistant=randomUUID();db.connection.prepare('INSERT INTO local_accounts(principal_id,username,owner,password_verifier,created_at) VALUES (?,?,?,?,?)').run(principal,'synthetic',1,'synthetic',Date.now());const subscriptions=new ChannelSubscriptionRepository(db),pairs=new TelegramPairingRepository(db),sub=subscriptions.apply(assistant,principal,{operation:'create',principalId:principal,channel:'telegram',label:'Synthetic notice',requestedConversations:false,requestedAlerts:true});const i=pairs.issue(assistant,sub.id,principal,1,'9999');pairs.claim('9999',i.challenge,{chatId:'1234',userId:'1234',privateChat:true,isBot:false,sentAt:Date.now()});const claim=pairs.inspect(assistant,sub.id,principal),paired=pairs.confirm(assistant,sub.id,principal,claim.revision,claim.claimId!);pairs.enable(assistant,sub.id,principal,paired.revision,false,true);const binding=pairs.binding('9999','1234','1234')!,scope={assistantId:assistant,endpointId:randomUUID(),sessionId:randomUUID(),environment:'synthetic',authorityContextRef:{providerRef:'synthetic-authority',contextId:'existing-context',revision:1}},sent:{chat:string;text:string}[]=[];let allowed=true,unknown=false;
 const options={database:db,scope,binding,allowed:()=>allowed,api:{send:async(chat:string,text:string)=>{sent.push({chat,text});return unknown?{status:'unknown' as const}:{status:'accepted' as const,messageId:42};}}},provider=new TelegramNoticeProvider(options);
 const call=():CapabilityCallContext=>({requestId:randomUUID(),correlationId:randomUUID(),deadlineAt:new Date(Date.now()+10000).toISOString(),executionMode:'live',signal:new AbortController().signal,isCurrent:()=>true});
 const invocation=():AdmittedCapabilityInvocation=>{const id=randomUUID();return {...scope,invocationId:id,interactionId:id,capabilityId:telegramNoticeCapability.id,capabilityVersion:telegramNoticeCapability.version,snapshotId:'telegram-notice:'+sub.id,snapshotRevision:binding.revision,idempotencyKey:id,dispatchReceipt:{invocationId:id,status:'admitted',grantRevision:1},input:{schemaVersion:'1.0.0',destinationRef:sub.id,notificationRef:id,conditionRef:'condition',expiresAt:new Date(Date.now()+60000).toISOString(),message:URGENT_AWAY_NOTICE,evidenceRefs:[]}};};
 return {db,principal,assistant,sub,subscriptions,pairs,binding,scope,sent,provider,options,call,invocation,deny:()=>allowed=false,unknown:()=>unknown=true};
}
test('Telegram notice requires current dispatch admission and sends only fixed redacted text once',async t=>{
 const f=fixture();t.after(()=>f.db.close());const invocation=f.invocation();assert.equal((await f.provider.invoke({...invocation,dispatchReceipt:null},telegramNoticeCapability,f.call())).lifecycle,'denied');assert.deepEqual(f.sent,[]);
 const result=await f.provider.invoke(invocation,telegramNoticeCapability,f.call());assert.equal(result.lifecycle,'succeeded');assert.deepEqual(f.sent,[{chat:'1234',text:URGENT_AWAY_NOTICE}]);assert.equal((await f.provider.invoke(invocation,telegramNoticeCapability,f.call())).lifecycle,'succeeded');assert.equal(f.sent.length,1);assert.equal((await f.provider.getInvocation({...f.scope,invocationId:invocation.invocationId},f.call()))!.lifecycle,'succeeded');assert.doesNotMatch(JSON.stringify(f.db.connection.prepare('SELECT * FROM telegram_notice_deliveries').get()),/critical condition|1234/);
});
test('arbitrary text, evidence references, changed scope, expired condition and revoked subscriber cannot send',async t=>{
 const f=fixture();t.after(()=>f.db.close());for(const patch of [{message:'PRIVATE_INCIDENT_CONTENT'},{evidenceRefs:['private:incident']},{expiresAt:new Date(Date.now()-1000).toISOString()},{destinationRef:randomUUID()},{extra:'not_allowed'}]){const invocation=f.invocation();invocation.input={...invocation.input as object,...patch};assert.equal((await f.provider.invoke(invocation,telegramNoticeCapability,f.call())).lifecycle,'denied');}
 const invocation=f.invocation();assert.equal((await f.provider.invoke({...invocation,endpointId:randomUUID()},telegramNoticeCapability,f.call())).lifecycle,'denied');f.subscriptions.apply(f.assistant,f.principal,{operation:'disable',id:f.sub.id,expectedRevision:1});assert.equal((await f.provider.invoke(invocation,telegramNoticeCapability,f.call())).lifecycle,'denied');assert.deepEqual(f.sent,[]);
});
test('unknown outcome persists across provider restart with no resend or Human acknowledgment claim',async t=>{
 const f=fixture();t.after(()=>f.db.close());f.unknown();const invocation=f.invocation();assert.equal((await f.provider.invoke(invocation,telegramNoticeCapability,f.call())).lifecycle,'outcomeUnknown');const restarted=new TelegramNoticeProvider(f.options);assert.equal((await restarted.invoke(invocation,telegramNoticeCapability,f.call())).lifecycle,'outcomeUnknown');assert.equal(f.sent.length,1);
 const changed={...invocation,input:{...invocation.input as object,conditionRef:'another'}};assert.equal((await restarted.invoke(changed,telegramNoticeCapability,f.call())).lifecycle,'denied');assert.equal(f.sent.length,1);
});
test('real capability resolver denies missing authority and admits a separately approved Telegram notice',async t=>{
 const f=fixture();t.after(()=>f.db.close());let admit=false;const resolver=new CapabilityResolver(f.provider,undefined,async request=>({invocationId:request.invocationId,status:admit?'admitted':'denied',grantRevision:1})),call=f.call();await resolver.snapshot(f.scope,call);const {dispatchReceipt:_unused,...request}=f.invocation();const denied=await resolver.invoke(request,call);assert.equal(denied.lifecycle,'denied');assert.deepEqual(f.sent,[]);admit=true;const {dispatchReceipt:_other,...next}=f.invocation();assert.equal((await resolver.invoke(next,f.call())).lifecycle,'succeeded');assert.equal(f.sent.length,1);
});
test('qualified condition joins existing urgent policy, durable away journal, authority and Telegram redaction',async t=>{
 const f=fixture(),scope={principalId:f.principal,assistantId:f.assistant,endpointId:f.scope.endpointId},now=()=>new Date().toISOString(),sourceBinding={sourceRef:'source',eventClass:'critical-condition',worldRef:'world',siteRef:'site',zoneRef:'zone',label:'Private zone'},policy=new UrgentAttentionRuntime(f.db,{bindings:[sourceBinding],allowSynthetic:true});let events:PwceCondition[]=[],cursor=0;
 const source:UrgentAwaySource={snapshot:async()=>({profileId:'synthetic',profileVersion:'1.0.0',operation:'snapshot',status:'ok',evaluatedAt:now(),conditions:[],nextCursor:cursor,hasMore:false,resyncReason:null,acknowledgment:null,replay:true}),changes:async()=>{const conditions=events;events=[];cursor+=conditions.length;return {profileId:'synthetic',profileVersion:'1.0.0',operation:'changes',status:'ok',evaluatedAt:now(),conditions,nextCursor:cursor,hasMore:false,resyncReason:null,acknowledgment:null,replay:true};}};
 const runtime=new UrgentAwayRuntime(f.db,{runtime:policy,source,pollIntervalMs:30000,destinations:[{destinationRef:f.sub.id,revision:f.binding.revision,scope,identity:{assistantRef:f.assistant,endpointRef:f.scope.endpointId,participantRefs:[f.principal],audienceRef:'redacted-recipient'},capabilityScope:f.scope,capabilityId:telegramNoticeCapability.id,capabilityVersion:telegramNoticeCapability.version,capabilityRoute:telegramNoticeCapability.route,provider:f.provider,dispatch:async r=>({invocationId:r.invocationId,status:'admitted',grantRevision:1}),current:()=>f.pairs.current(f.binding),facts:()=>({scope,sessionId:f.scope.sessionId,sessionRevision:1,audienceRevision:1,authorizationRevision:1,authorized:true,privateAudience:true,attentionSuitable:true,outputReady:true})}]});t.after(()=>{runtime.close();f.db.close();});policy.configure(scope,{expectedRevision:policy.settings(scope).revision,rules:[{sourceRef:'source',eventClass:'critical-condition',enabled:true,bypassQuietHours:false}],quietHours:null,modality:'text',snoozedUntil:null});runtime.start();for(let i=0;i<100&&!runtime.inspect(scope).destinations[0]!.connected;i++)await new Promise(r=>setTimeout(r,5));assert.equal(runtime.inspect(scope).destinations[0]!.connected,true);
 events=[{sourceRef:sourceBinding.sourceRef,eventClass:sourceBinding.eventClass,worldRef:sourceBinding.worldRef,siteRef:sourceBinding.siteRef,zoneRef:sourceBinding.zoneRef,conditionRef:'condition',revision:1,sourceRevision:1,status:'open',transition:'open',severity:'critical',summary:'PRIVATE_EVENT_DETAIL',occurredAt:now(),receivedAt:now(),updatedAt:now(),freshUntil:new Date(Date.now()+60000).toISOString(),expiresAt:new Date(Date.now()+120000).toISOString(),freshness:'fresh',basis:'synthetic',qualification:{state:'qualified',confidence:1,limitations:[],evidenceRefs:['private:incident']}}];await runtime.tick();for(let i=0;i<100&&!f.sent.length;i++)await new Promise(r=>setTimeout(r,5));assert.deepEqual(f.sent,[{chat:'1234',text:URGENT_AWAY_SIMULATION_NOTICE}],JSON.stringify(runtime.inspect(scope)));for(let i=0;i<100&&runtime.inspect(scope).deliveries[0]?.state!=='accepted';i++)await new Promise(r=>setTimeout(r,5));const row=runtime.inspect(scope).deliveries[0]!;assert.equal(row.state,'accepted');assert.equal(row.acknowledgedAt,null);
});
