import assert from 'node:assert/strict';import test from 'node:test';import {randomBytes,createHash} from 'node:crypto';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {createLifestreamServer} from '../src/index.ts';import {loadProfile} from '../src/config/loader.ts';import {FixtureInferenceProvider} from '@lifestream/runtime/inference/fixture';import {defaultTopics} from '@lifestream/contracts/experience';
const delay=(ms:number)=>new Promise(r=>setTimeout(r,ms));
test('accepted private Telegram conversations learn from retained experience, affect later choices and survive restart',async t=>{
 const root=await mkdtemp(join(tmpdir(),'experience-http-'));t.after(()=>rm(root,{recursive:true,force:true}));const original=FixtureInferenceProvider.prototype.generate,requests:any[]=[];let heldStarted=false,heldAborted=false;
 FixtureInferenceProvider.prototype.generate=async function*(request,context){requests.push(request);if(request.scope.sessionId==='automatic-memory-worker'){const source=JSON.parse(request.sections.at(-1)!.content).source;yield {kind:'text',text:JSON.stringify({items:[{key:'project.'+createHash('sha256').update(source).digest('hex').slice(0,16),kind:'experiential',quote:source,subject:'owner',epistemic:'userStatement'}]})};yield {kind:'done'};return;}
 if(request.scope.sessionId.startsWith('experience:')){const data=JSON.parse(request.sections.at(-1)!.content),refs=data.sources.map((s:any)=>s.id),items=['reading','gardening'].map((topic,i)=>{const old=data.workspace.find((s:any)=>s.id===['a-reading','z-garden'][i]);return {id:['a-reading','z-garden'][i],expectedRevision:old?.revision??0,kind:'project',topic,statement:'Continue the '+topic+' project',nextStep:topic==='reading'?'Compare two essays':'Plan a soil comparison',uncertainty:'medium',sourceRefs:refs,disposition:'open'};});yield {kind:'text',text:JSON.stringify({recordType:'reflectionResult',decision:'change',conclusion:'Independent retained outcomes support next steps.',items,changes:data.episodes.length>=2&&!data.alreadyContributed[0]?.episodes.length?[{dimension:'attentionGardening',delta:.05,episodeRefs:data.episodes.map((e:any)=>e.id),confidence:.9,reason:'Independent outcomes'}]:[]})};yield {kind:'done'};return;}
 if(request.sections.at(-1)!.content==='Hold a learned reply'){heldStarted=true;await new Promise<void>(resolve=>context.signal.addEventListener('abort',()=>{heldAborted=true;resolve();},{once:true}));yield {kind:'text',text:'LATE_LEARNED_REPLY'};yield {kind:'done'};return;}
 const memory=request.sections.find(s=>s.kind==='preparedMemory')!.content;yield {kind:'text',text:memory.includes('Selected eligible continuation')?(memory.includes('Plan a soil comparison')?'Compare soil in two beds, keeping water and light equal.':'Compare the argument in two nature essays.'):'Understood.'};yield {kind:'done'};
 };t.after(()=>{FixtureInferenceProvider.prototype.generate=original;});const clock={now:Date.now()},config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex'),password=randomBytes(32).toString('hex');let inbox:any[]=[],sequence=0;const sent:string[]=[];const push=(text:string)=>inbox.push({updateId:++sequence,messageId:sequence,chatId:'1234',userId:'1234',sentAt:Date.now(),text});const options={config,experienceTestClock:()=>clock.now,localAuth:{stateDirectory:join(root,'safety'),installerToken},telegram:{botId:'9999',token:()=>undefined,enabled:()=>true,transport:{verify:async()=>{},updates:async(offset:number)=>{const messages=inbox;inbox=[];return {messages,nextOffset:Math.max(offset,...messages.map(m=>m.updateId+1))};},send:async(_chat:string,text:string)=>{sent.push(text);return {status:'accepted' as const,messageId:sent.length};}}}};let app=createLifestreamServer(options);await app.start();t.after(()=>app.shutdown());let base=`http://127.0.0.1:${app.address().port}`,cookie='',csrf='';const request=(path:string,body?:unknown)=>fetch(base+path,{method:body===undefined?'GET':'POST',headers:{origin:base,cookie,'content-type':'application/json','x-lifestream-csrf':csrf},...(body===undefined?{}:{body:JSON.stringify(body)})});
 const setup=await request('/api/auth/v1/setup',{username:'synthetic',password,installerToken});cookie=setup.headers.get('set-cookie')!.split(';')[0]!;const owner=(await setup.json()).session;csrf=owner.csrfToken;
 const a=await (await request('/api/admin/v1/assistants',{displayName:'Synthetic learning Assistant',adaptivePersonaPolicy:{dimensions:[{key:'attentionGardening',valueType:'number',minimum:-1,maximum:1,maxDeltaPerDreamingRun:.05,sensitive:false,activation:'automatic'}]}})).json();assert.equal((await request(`/api/admin/v1/assistants/${a.assistantId}/activate`,{profileId:a.profile.profileId,expectedActiveRevision:null})).status,200);const rel=(await (await request(`/api/admin/v1/assistants/${a.assistantId}/relationships`,{})).json()).relationship,scope={assistantId:a.assistantId,relationshipId:rel.relationshipId},path=`/api/admin/v1/assistants/${a.assistantId}/relationships/${rel.relationshipId}/experience/v1`;
 let view=await (await request(path)).json();assert.equal(view.state.configuration.enabled,false);const configure=()=>({schemaVersion:'1.0.0',operation:'configure',expectedRevision:view.state.revision,enabled:true,frozen:false,retention:'sourceBound',topicPolicies:defaultTopics});assert.equal((await request(path,configure())).status,409,'missing retained processing policy fails closed');assert.equal((await request('/api/runtime/v1/memory',{...scope,enabled:true,expectedRevision:0})).status,200);view=await (await request(path)).json();assert.equal((await request(path,configure())).status,200);assert.equal((await request('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'})).status,200);
 const sub=(await (await request('/api/runtime/v1/channel-subscriptions?assistantId='+a.assistantId,{operation:'create',principalId:owner.principalId,channel:'telegram',label:'Synthetic experience chat',requestedConversations:true,requestedAlerts:false})).json()).subscriptions[0],mine='/api/runtime/v1/my-channel-pairings',issued=(await (await request(mine,{operation:'issue',id:sub.id,expectedRevision:1,pairingRevision:0,botId:'9999'})).json()).issued;push('/start '+issued.challenge);let pairing:any;
 for(let n=0;n<100;n++){pairing=(await (await request(mine)).json()).subscriptions[0].pairing;if(pairing.state==='claimed')break;await delay(50);}assert.equal(pairing.state,'claimed');pairing=(await (await request(mine,{operation:'confirm',id:sub.id,expectedRevision:pairing.revision,claimId:pairing.claimId})).json()).subscriptions[0].pairing;assert.equal((await request(mine,{operation:'enable',id:sub.id,expectedRevision:pairing.revision,conversations:true})).status,200);
 const turn=async(userInput:string)=>{const before=sent.length;push(userInput);for(let n=0;n<300&&sent.length===before;n++)await delay(50);assert.equal(sent.length,before+1,'Expected one accepted channel reply');return sent.at(-1)!;};
 assert.match(await turn('/private'),/manual declaration/);
 const waitFor=async(fn:()=>Promise<boolean>)=>{for(let n=0;n<100;n++){if(await fn())return;await delay(50);}assert.fail('bounded wait failed '+JSON.stringify({view,requests:requests.map(r=>r.scope.sessionId)}));};
 await turn('I enjoyed the gardening and reading projects on our first trial day.');await waitFor(async()=>{const v=await (await request('/api/runtime/v1/memory?'+new URLSearchParams(scope))).json();return v.jobs.some((j:any)=>j.state==='saved');});await delay(1100);clock.now+=61000;await waitFor(async()=>{view=await (await request(path)).json();return view.state.items.length===2;});
 await turn('I enjoyed comparing garden soil and reading essays during our second independent trial day.');await waitFor(async()=>{const v=await (await request('/api/runtime/v1/memory?'+new URLSearchParams(scope))).json();return v.jobs.filter((j:any)=>j.state==='saved').length===2;});await delay(1100);clock.now+=61000;await waitFor(async()=>{view=await (await request(path)).json();return view.state.imprints[0].value===.05;});const answer=await turn('What should we work on next?');assert.match(answer,/Compare soil in two beds/);view=await (await request(path)).json();assert.equal(view.state.funnel.eligible,2);assert.equal(view.state.funnel.calls,2);assert.equal(view.state.funnel.outputs,1);assert.ok(view.selections.some((s:any)=>s.selected==='z-garden'&&s.observedOutput));assert.equal(requests.filter(r=>r.scope.sessionId.startsWith('experience:')).length,2);
 await app.shutdown();app=createLifestreamServer(options);await app.start();base=`http://127.0.0.1:${app.address().port}`;const login=await request('/api/auth/v1/sign-in',{username:'synthetic',password});assert.equal(login.status,200);cookie=login.headers.get('set-cookie')!.split(';')[0]!;csrf=(await login.json()).session.csrfToken;view=await (await request(path)).json();assert.equal(view.state.imprints[0].value,.05);assert.equal(view.state.items.length,2);assert.match(await turn('/privacy'),/shared or unknown/);assert.match(await turn('/private'),/manual declaration/);
 const beforeFreeze=sent.length;push('Hold a learned reply');await waitFor(async()=>heldStarted);view=await (await request(path)).json();
 assert.equal((await request(path,{schemaVersion:'1.0.0',operation:'configure',expectedRevision:view.state.revision,enabled:true,frozen:true,retention:'sourceBound',topicPolicies:defaultTopics})).status,200);await waitFor(async()=>heldAborted);assert.equal(sent.length,beforeFreeze);assert.ok(!sent.includes('LATE_LEARNED_REPLY'));const frozen=await turn('What should we work on next?');assert.doesNotMatch(frozen,/Compare soil/);assert.equal((await request(path,{...configure(),authority:true})).status,422);
});
