import assert from 'node:assert/strict';
import test,{type TestContext} from 'node:test';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {Database,ChannelSubscriptionRepository,TelegramPairingRepository} from '@lifestream/storage-sqlite';
import {CapabilityResolver} from '@lifestream/runtime/capabilities/resolver';
import type {CapabilityInvocation,CapabilityCallContext} from '@lifestream/runtime/capabilities/ports';
import {LocalAuthentication,AUTH_PARAMETERS} from '../src/auth/local-auth.ts';
import {TelegramNoticeAuthority} from '../src/channels/telegram-notice-authority.ts';
import {TelegramNoticeProvider,telegramNoticeCapability} from '../src/channels/telegram-notice-provider.ts';
import {URGENT_AWAY_NOTICE} from '../src/runtime/urgent-away.ts';
import {quarantineRestoredChannels} from '../src/channels/telegram-recovery.ts';
async function fixture(t:TestContext){
 const directory=mkdtempSync(join(tmpdir(),'ls-notice-authority-')),db=new Database({path:join(directory,'state.sqlite')});db.migrate();t.after(()=>{db.close();rmSync(directory,{recursive:true,force:true});});
 let now=Date.now();const authOptions={stateDirectory:join(directory,'auth'),installerToken:'synthetic-installer',now:()=>now},auth=new LocalAuthentication(db,authOptions),origin='http://127.0.0.1:33001',setup=await auth.setup('owner','synthetic-owner-password',authOptions.installerToken,origin),local=auth.context(setup.session.token,origin)!,assistantId=randomUUID(),person=await auth.provision(local,'recipient','synthetic-member-password');auth.permitCreator(local,assistantId);
 const subscriptions=new ChannelSubscriptionRepository(db),pairs=new TelegramPairingRepository(db),sub=subscriptions.apply(assistantId,local.principalId,{operation:'create',principalId:person.principalId,channel:'telegram',label:'Synthetic recipient',requestedConversations:true,requestedAlerts:true});
 const issue=pairs.issue(assistantId,sub.id,person.principalId,1,'9999');pairs.claim('9999',issue.challenge,{chatId:'1234',userId:'1234',privateChat:true,isBot:false,sentAt:Date.now()});const claimed=pairs.inspect(assistantId,sub.id,person.principalId),confirmed=pairs.confirm(assistantId,sub.id,person.principalId,claimed.revision,claimed.claimId!);pairs.enable(assistantId,sub.id,person.principalId,confirmed.revision,false,true);const binding=pairs.binding('9999','1234','1234')!,session={sessionId:randomUUID(),endpointId:randomUUID(),revision:1};
 const options={database:db,auth,environmentId:randomUUID(),session:()=>session,assistantAvailable:()=>true,now:()=>now},authority=new TelegramNoticeAuthority(options),terms=()=>({expiresAt:new Date(now+86400000).toISOString(),reviewAfter:new Date(now+7200000).toISOString()}),request=()=>authority.request(binding,local,terms()),approve=(p=request())=>authority.approve(binding,local,{requestId:p.requestId,expectedRevision:p.revision,confirmationDigest:p.confirmationDigest});
 const call=():CapabilityCallContext=>({requestId:randomUUID(),correlationId:randomUUID(),deadlineAt:new Date(now+10000).toISOString(),executionMode:'live',signal:new AbortController().signal,isCurrent:()=>true});
 const invocation=():CapabilityInvocation=>{const id=randomUUID(),route=authority.authority(binding,session)!;return {...route.scope,invocationId:id,interactionId:id,capabilityId:telegramNoticeCapability.id,capabilityVersion:telegramNoticeCapability.version,snapshotId:'telegram-notice:'+sub.id,snapshotRevision:binding.revision,idempotencyKey:id,input:{schemaVersion:'1.0.0',notificationRef:id,destinationRef:sub.id,conditionRef:'synthetic.condition',expiresAt:new Date(now+60000).toISOString(),message:URGENT_AWAY_NOTICE,evidenceRefs:[]}};};
 return {db,auth,authOptions,local,origin,assistantId,person,subscriptions,pairs,sub,binding,session,options,authority,terms,request,approve,call,invocation,now:()=>now,advance:(ms:number)=>now+=ms};
}
test('explicit owner request and approval admit one real canonical dispatch to a separately consenting recipient',async t=>{
 const f=await fixture(t);assert.equal(f.authority.authority(f.binding,f.session),undefined);const pending=f.request();assert.equal(pending.state,'pending');assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM canonical_grants').get()!.n,0);assert.deepEqual(pending.scope.dataScopeRefs,[]);assert.equal(f.authority.authority(f.binding,f.session),undefined);
 const grant=f.approve(pending);assert.equal(grant.grantClass,'allowPersistent');assert.equal(grant.sessionId,null);assert.equal(grant.principalId,f.local.principalId);assert.notEqual(grant.principalId,f.person.principalId);const route=f.authority.authority(f.binding,f.session)!;assert.ok(route?.current());
 const sent:string[]=[],provider=new TelegramNoticeProvider({database:f.db,binding:f.binding,scope:route.scope,allowed:route.current,api:{send:async(_chat,text)=>{sent.push(text);return {status:'accepted',messageId:17};}}}),resolver=new CapabilityResolver(provider,undefined,route.dispatch);await resolver.snapshot(route.scope,f.call());const invocation=f.invocation(),result=await resolver.invoke(invocation,f.call());assert.equal(result.lifecycle,'succeeded');assert.deepEqual(sent,[URGENT_AWAY_NOTICE]);
 assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM canonical_dispatch_admissions').get()!.n,1);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM canonical_dispatch_claims').get()!.n,1);assert.equal(await route.dispatch(invocation,telegramNoticeCapability,f.call()),undefined);assert.equal((await resolver.invoke(invocation,f.call())).lifecycle,'succeeded');assert.equal(sent.length,1);
 const row=f.db.connection.prepare('SELECT payload_json FROM canonical_dispatch_admissions').get() as {payload_json:string},admission=JSON.parse(row.payload_json);assert.equal(admission.decision.disposition,'authorized');assert.equal(admission.decision.principalId,f.local.principalId);assert.equal(admission.request.scope.sessionId,f.session.sessionId);assert.notEqual(admission.request.scope.sessionId,f.local.sessionId);
});
test('forged scope, arbitrary content, stale snapshot and simulation cannot acquire a dispatch claim',async t=>{
 const f=await fixture(t);f.approve();const route=f.authority.authority(f.binding,f.session)!;
 for(const patch of [{endpointId:randomUUID()},{capabilityId:'arbitrary.tool'},{snapshotRevision:f.binding.revision+1},{idempotencyKey:randomUUID()}])assert.equal(await route.dispatch({...f.invocation(),...patch},telegramNoticeCapability,f.call()),undefined);
 for(const patch of [{message:'private content'},{evidenceRefs:['incident:private']},{destinationRef:randomUUID()},{expiresAt:new Date(f.now()-1000).toISOString()},{expiresAt:new Date(f.now()).toISOString()}]){const input=f.invocation();assert.equal(await route.dispatch({...input,input:{...input.input as object,...patch}},telegramNoticeCapability,f.call()),undefined);}
 assert.equal(await route.dispatch(f.invocation(),telegramNoticeCapability,{...f.call(),executionMode:'simulation'}),undefined);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM canonical_dispatch_admissions').get()!.n,0);
});
test('background use survives admin idle and host reconstruction but does not refresh admin privileges; logout stops it',async t=>{
 const f=await fixture(t);f.approve();const activity=f.db.connection.prepare('SELECT admin_last_activity FROM local_sessions WHERE token_hash=?').get(f.local.tokenHash);f.advance(AUTH_PARAMETERS.adminIdleMs+1000);
 assert.throws(()=>f.auth.assertCurrent(f.local));f.auth.assertCurrent(f.local,false);const restarted=new TelegramNoticeAuthority({...f.options,auth:new LocalAuthentication(f.db,f.authOptions)}),route=restarted.authority(f.binding,f.session)!;assert.ok(route?.current());assert.ok(await route.dispatch(f.invocation(),telegramNoticeCapability,f.call()));assert.deepEqual(f.db.connection.prepare('SELECT admin_last_activity FROM local_sessions WHERE token_hash=?').get(f.local.tokenHash),activity);assert.throws(()=>f.request());f.auth.logout(f.local);assert.equal(route.current(),false);assert.equal(restarted.authority(f.binding,f.session),undefined);
});
test('review deadline, grant revoke, subscriber consent and session changes each fence previously captured routes',async t=>{
 const f=await fixture(t);const grant=f.approve(),route=f.authority.authority(f.binding,f.session)!;f.authority.revoke(f.binding,f.local,grant.grantId,grant.revision);assert.equal(route.current(),false);assert.equal(f.authority.authority(f.binding,f.session),undefined);
 f.approve();const second=f.authority.authority(f.binding,f.session)!;f.session.revision++;assert.equal(second.current(),false);f.session.revision--;assert.ok(second.current());f.pairs.enable(f.assistantId,f.sub.id,f.person.principalId,f.binding.revision,false,false);assert.equal(second.current(),false);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM telegram_notice_authority').get()!.n,0);
 const g=await fixture(t);g.approve();const due=g.authority.authority(g.binding,g.session)!;g.advance(7200000);assert.equal(due.current(),false);assert.equal(g.authority.authority(g.binding,g.session),undefined);
});
test('another principal, changed binding, stale approval or unbounded terms cannot issue; restore clears selection',async t=>{
 const f=await fixture(t),pending=f.request();const memberSession=await f.auth.signIn('recipient','synthetic-member-password','',f.origin,'loopback'),member=f.auth.context(memberSession.token,f.origin)!;
 assert.throws(()=>f.authority.request(f.binding,member,f.terms()));assert.throws(()=>f.authority.approve(f.binding,member,{requestId:pending.requestId,expectedRevision:1,confirmationDigest:pending.confirmationDigest}));assert.throws(()=>f.authority.approve(f.binding,f.local,{requestId:pending.requestId,expectedRevision:2,confirmationDigest:pending.confirmationDigest}));assert.throws(()=>f.authority.request(f.binding,f.local,{expiresAt:'2099-01-01T00:00:00Z',reviewAfter:'2099-01-01T00:00:00Z'}));assert.throws(()=>f.authority.approve({...f.binding,chatId:'9876'},f.local,{requestId:pending.requestId,expectedRevision:1,confirmationDigest:pending.confirmationDigest}));
 f.approve(pending);const route=f.authority.authority(f.binding,f.session)!;quarantineRestoredChannels(f.db);assert.equal(route.current(),false);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM telegram_notice_authority').get()!.n,0);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM canonical_grants').get()!.n,1);
});

test('cancelled reviews and failed selection writes never enable a destination',async t=>{
 const f=await fixture(t),p=f.request();assert.equal(f.authority.cancel(f.binding,f.local,p.requestId,p.revision).state,'cancelled');assert.throws(()=>f.approve(p));assert.equal(f.authority.authority(f.binding,f.session),undefined);
 const next=f.request();f.db.exec("CREATE TRIGGER synthetic_selection_failure BEFORE INSERT ON telegram_notice_authority BEGIN SELECT RAISE(ABORT,'synthetic failure'); END");assert.throws(()=>f.approve(next));assert.equal(f.authority.authority(f.binding,f.session),undefined);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM canonical_grants').get()!.n,1);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM telegram_notice_authority').get()!.n,0);
});
