import assert from 'node:assert/strict';
import test from 'node:test';
import {Database,MemoryRepository} from '@lifestream/storage-sqlite';
import {AutomaticMemory} from '../src/runtime/automatic-memory.ts';
import {visualEpisode,visualOwner} from '../../../packages/storage-sqlite/test/fixtures/visual-episode.ts';
function setup(t:import('node:test').TestContext){const db=new Database({path:':memory:'});db.migrate();const owner=visualOwner();let allowed=true,content=()=>true,calls=0;const worker=new AutomaticMemory({database:db,memories:new MemoryRepository(db),provider:()=>({revision:'unused-synthetic',provider:{async *generate(){calls++;yield {kind:'done' as const};}}}),idle:()=>false,scopeAllowed:()=>allowed,contentAllowed:()=>content(),changed:()=>{}});t.after(async()=>{await worker.close();db.close();});return {db,owner,worker,calls:()=>calls,deny:()=>allowed=false,content:(fn:()=>boolean)=>content=fn,make:()=>visualEpisode(owner,worker.inspect(owner).visual.policy,Date.now())};}
test('visual intake requires separate approval and never enters owner-statement extraction or invents a memory record',t=>{
 const f=setup(t);assert.throws(()=>f.worker.configureVisual(f.owner,true,0,86400000),/requires/);f.worker.configure(f.owner,true,0);assert.equal(f.worker.inspect(f.owner).visual.policy.enabled,false);f.worker.configureVisual(f.owner,true,0,86400000);const v=f.make();assert.equal(f.worker.enqueueVisual(f.owner,v.episode,v.admission).state,'retained');assert.equal(f.worker.inspect(f.owner).visual.episodes.length,1);assert.equal(f.calls(),0);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM automatic_memory_work').get()!.n,0);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM memories').get()!.n,0);
 f.worker.configure(f.owner,false,1);assert.equal(f.worker.inspect(f.owner).visual.policy.enabled,false);assert.equal(f.worker.inspect(f.owner).visual.episodes[0]!.episode,null);assert.equal(f.worker.enqueueVisual(f.owner,v.episode,v.admission).state,'policyDenied');
});
test('audience/relationship withdrawal and content callbacks fence visual admission without sending data to a provider',async t=>{
 for(const mode of ['scope','memory','visual','forbidden','secret'])await t.test(mode,child=>{const f=setup(child);f.worker.configure(f.owner,true,0);f.worker.configureVisual(f.owner,true,0,86400000);const v=f.make();if(mode==='scope')f.deny();if(mode==='memory')f.content(()=>{f.worker.configure(f.owner,false,f.worker.policy(f.owner).revision);return true;});if(mode==='visual')f.content(()=>{f.worker.configureVisual(f.owner,false,f.worker.inspect(f.owner).visual.policy.revision,86400000);return true;});if(mode==='forbidden')f.content(()=>false);if(mode==='secret')v.episode.summary='The password is a synthetic secret.';assert.equal(f.worker.enqueueVisual(f.owner,v.episode,v.admission).state,'policyDenied');assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM visual_observation_episodes').get()!.n,0);assert.equal(f.calls(),0);});
});
test('operator inspection/forget guards scope and revision and cannot replay forgotten source',t=>{
 const f=setup(t);f.worker.configure(f.owner,true,0);f.worker.configureVisual(f.owner,true,0,86400000);const v=f.make();assert.equal(f.worker.enqueueVisual(f.owner,v.episode,v.admission).state,'retained');f.deny();assert.equal(f.worker.inspect(f.owner).visual.episodes.length,0);assert.throws(()=>f.worker.forgetVisual(f.owner,v.episode.episodeId,1),/scope/);
});

test('authenticated public memory API configures explicit visual consent, inspects typed episodes and forgets with CSRF and ownership',async t=>{
 const {mkdtemp,rm}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join}=await import('node:path'),{randomBytes}=await import('node:crypto'),{createLifestreamServer}=await import('../src/index.ts'),{loadProfile}=await import('../src/config/loader.ts');
 const root=await mkdtemp(join(tmpdir(),'ls-visual-memory-http-'));t.after(()=>rm(root,{recursive:true,force:true}));const config=loadProfile('test');config.authority.authentication='local-password';config.storage={databasePath:join(root,'db.sqlite'),artifactDirectory:join(root,'artifacts')};const installerToken=randomBytes(32).toString('hex'),password=randomBytes(32).toString('hex'),app=createLifestreamServer({config,localAuth:{stateDirectory:join(root,'safety'),installerToken},audiencePrivacy:{sourceIds:[]}});await app.start();t.after(()=>app.shutdown());
 const base=`http://127.0.0.1:${app.address().port}`;let cookie='',csrf='';const request=(path:string,body?:unknown,headers:Record<string,string>={})=>fetch(base+path,{method:body===undefined?'GET':'POST',headers:{origin:base,cookie,'content-type':'application/json','x-lifestream-csrf':csrf,...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});
 const setup=await request('/api/auth/v1/setup',{username:'synthetic',password,installerToken});assert.equal(setup.status,201);cookie=setup.headers.get('set-cookie')!.split(';')[0]!;const identity=(await setup.json()).session;csrf=identity.csrfToken;
 const a=await (await request('/api/admin/v1/assistants',{displayName:'Synthetic visual-memory Assistant'})).json();assert.equal((await request(`/api/admin/v1/assistants/${a.assistantId}/activate`,{profileId:a.profile.profileId,expectedActiveRevision:null})).status,200);const relationship=(await (await request(`/api/admin/v1/assistants/${a.assistantId}/relationships`,{})).json()).relationship;
 assert.equal((await request('/api/runtime/v1/session-context',{expectedRevision:0,mode:'text',audienceScope:'authenticatedSession'})).status,200);assert.equal((await request('/api/runtime/v1/audience',{mode:'solo',seconds:300})).status,200);
 const scope={assistantId:a.assistantId,relationshipId:relationship.relationshipId},path='/api/runtime/v1/memory',query=path+'?'+new URLSearchParams(scope),operation={...scope,operation:'configureVisual',enabled:true,expectedRevision:0,retentionMs:86400000};
 assert.equal((await request(path,operation,{'x-lifestream-csrf':'wrong'})).status,403);assert.equal((await request(path,operation)).status,409);assert.equal((await request(path,{...scope,enabled:true,expectedRevision:0})).status,200);assert.equal((await request(path,{...operation,retentionMs:null})).status,409);assert.equal((await request(path,{...operation,authority:true})).status,422);
 let response=await request(path,operation);assert.equal(response.status,200);const view=await response.json();assert.equal(view.visual.policy.enabled,true);
 const owner={principalId:identity.principalId,...scope},v=visualEpisode(owner,view.visual.policy,Date.now());const worker=(app as any).automaticMemory as AutomaticMemory;assert.equal(worker.enqueueVisual(owner,v.episode,v.admission).state,'retained');response=await request(query);const observed=await response.json();assert.equal(observed.visual.episodes[0].episode.memoryFactuality,'unverified');
 assert.equal((await request(path,{...scope,operation:'forgetVisual',id:v.episode.episodeId,expectedRevision:2})).status,409);assert.equal((await request(path,{...scope,operation:'forgetVisual',id:v.episode.episodeId,expectedRevision:1})).status,200);assert.equal((await (await request(query)).json()).visual.episodes[0].episode,null);assert.equal(worker.enqueueVisual(owner,v.episode,v.admission).state,'duplicateSource');
 // Client payload intake and provider authority are deliberately absent from the public control route.
 assert.equal((await request(path,{...scope,operation:'admitVisual',episode:v.episode})).status,422);
});

test('reflection adapter retains typed provenance without a projection and fences withdrawal during content checks',async t=>{const {retainedExperienceSources}=await import('../src/runtime/experience-inputs.ts');const f=setup(t);f.worker.configure(f.owner,true,0);f.worker.configureVisual(f.owner,true,0,86400000);const v=f.make();assert.equal(f.worker.enqueueVisual(f.owner,v.episode,v.admission).state,'retained');const episodes=f.worker.retainedVisualEpisodes(f.owner);assert.equal(episodes.length,1);const sources=retainedExperienceSources(new MemoryRepository(f.db),f.owner,()=>true,episodes);assert.equal(sources.length,1);assert.equal(sources[0]!.family,'visual:'+v.episode.independenceKeys[0]);assert.equal(sources[0]!.occurredAt,v.episode.occurredAt);assert.equal(JSON.parse(sources[0]!.content).sourceKind,'modelVisualObservation');assert.equal(JSON.parse(sources[0]!.content).memoryRecordId,null);assert.equal(f.calls(),0);f.content(()=>{f.worker.configure(f.owner,false,f.worker.policy(f.owner).revision);return true;});assert.deepEqual(f.worker.retainedVisualEpisodes(f.owner),[]);});

test('typed reflection source selection retires correction, forgetting and reentrant source deletion',async t=>{for(const mode of ['correction','forget','reentrant-forget'])await t.test(mode,child=>{const f=setup(child);f.worker.configure(f.owner,true,0);f.worker.configureVisual(f.owner,true,0,86400000);const v=f.make();assert.equal(f.worker.enqueueVisual(f.owner,v.episode,v.admission).state,'retained');const selected=f.worker.retainedVisualEpisodes(f.owner);assert.equal(selected.length,1);if(mode==='correction')f.worker.correctVisual(f.owner,v.episode.episodeId,1,'The sampled hat description is mistaken.');else if(mode==='forget')f.worker.forgetVisual(f.owner,v.episode.episodeId,1);else f.content(()=>{f.worker.forgetVisual(f.owner,v.episode.episodeId,1);return true;});assert.deepEqual(f.worker.retainedVisualEpisodes(f.owner),[]);assert.equal(f.worker.visualEpisodesCurrent(f.owner,selected,1),false);});});
