import assert from 'node:assert/strict';
import test,{type TestContext} from 'node:test';
import {createHash,randomUUID} from 'node:crypto';
import {createContractValidator} from '@lifestream/contracts';
import {Database,MemoryRepository,VisualMemoryRepository,isVisualCorrectionEvidence} from '@lifestream/storage-sqlite';
import {AutomaticMemory} from '../src/runtime/automatic-memory.ts';
import {VisualMemoryCandidateEvidence,isVisualMemoryCorrectionTrace,isVisualMemoryLifecycleTrace,isVisualMemoryCandidateTrace} from '../src/runtime/visual-memory-candidate-evidence.ts';
import {visualEpisode,visualOwner} from '../../../packages/storage-sqlite/test/fixtures/visual-episode.ts';
import {correlateVisualMemoryCorrection,replayVisualMemoryCorrection} from '../src/runtime/turn-context-trace.ts';
const sha=(s:string)=>createHash('sha256').update(s).digest('hex');
function fixture(t:TestContext,project=true,hasEnvironment=true){
 const environmentId=randomUUID(),db=new Database({path:':memory:'});db.migrate();const owner=visualOwner(),memories=new MemoryRepository(db);let allowed=true,changed=()=>{},calls=0;let scopeRead=()=>allowed;
 const worker=new AutomaticMemory({...(hasEnvironment?{environmentId}:{}),database:db,memories,provider:()=>({revision:'unused-synthetic',provider:{async *generate(){calls++;yield {kind:'done' as const};}}}),idle:()=>false,scopeAllowed:()=>scopeRead(),changed:()=>changed()});t.after(async()=>{await worker.close();db.close();});
 worker.configure(owner,true,0);worker.configureVisual(owner,true,0,86400000);const source=new VisualMemoryRepository(db),v=visualEpisode(owner,worker.inspect(owner).visual.policy,Date.now());assert.equal(worker.enqueueVisual(owner,v.episode,v.admission).state,'retained');
 const p=project?worker.projectVisual(owner,v.episode.episodeId,1,{value:0.6,basis:'Synthetic estimated transformation',policyRef:'synthetic-transform-v1'}):null;const memoryId=p&&'memoryId' in p?p.memoryId!:null;
 const correct=()=>worker.correctVisual(owner,v.episode.episodeId,project?2:1,'PRIVATE_SYNTHETIC_HUMAN_CORRECTION');
 return {db,environmentId,owner,memories,worker,source,v,memoryId,correct,calls:()=>calls,deny:()=>allowed=false,onChange:(fn:()=>void)=>changed=fn,onScope:(fn:()=>boolean)=>scopeRead=fn};
}
test('actual original correction read produces a distinct restricted trace only after asynchronous drain',async t=>{
 const f=fixture(t),reply=f.correct(),source=f.source.correctionEvidence(f.owner,f.memoryId!)!;assert.ok(isVisualCorrectionEvidence(source));assert.equal(source.sourceReceipt.eventId,reply.correctionMutationEventId);assert.equal(source.sourceReceipt.humanEntryId,reply.correctionId);assert.notEqual(reply.correctionId,reply.correctionMutationEventId);assert.equal(source.sourceReceipt.oldRevision,1);assert.equal(source.sourceReceipt.newRevision,2);
 assert.deepEqual(f.worker.visualCorrectionHistory(f.owner),[]);await Promise.resolve();const [trace]=f.worker.visualCorrectionHistory(f.owner);assert.ok(trace);assert.equal(isVisualMemoryCorrectionTrace(trace),true);assert.equal(isVisualMemoryLifecycleTrace(trace),false);assert.equal(isVisualMemoryCandidateTrace(trace),false);
 const e=trace.event;assert.equal(createContractValidator().validate('https://lifestream.dev/contracts/interaction-trace-event/2.0.0',e).valid,true);assert.equal(e.eventType,'memory.lifecycleChanged');assert.equal(e.traceScope,'background');assert.equal(e.interactionTraceId,null);assert.equal(e.monotonic,null);assert.equal(e.environmentId,f.environmentId);assert.notEqual(e.environmentId,f.v.episode.scope.environmentId);assert.equal(e.conversationId,null);assert.equal(e.sessionId,null);assert.equal(e.endpointId,null);assert.equal(e.eventTime,source.sourceReceipt.occurredAt);assert.deepEqual(e.sourceEventIds,[reply.correctionMutationEventId]);assert.deepEqual(e.payload,{memoryId:f.memoryId,lifecycleEventId:reply.correctionMutationEventId,oldRevision:1,newRevision:2,sourceRevision:source.sourceReceipt.sourceRevision});assert.deepEqual(trace.sourceReceipt,source.sourceReceipt);
 assert.equal('sourceMutation' in trace,false);assert.equal(createContractValidator().validate('https://lifestream.dev/contracts/memory-operations/1.0.0',trace.sourceReceipt).valid,false);assert.equal(trace.artifact.reference.sha256,sha(trace.artifact.bytes));assert.equal(trace.artifact.reference.byteLength,Buffer.byteLength(trace.artifact.bytes));assert.equal(JSON.parse(trace.artifact.bytes).correctedFactProved,false);
 assert.doesNotMatch(JSON.stringify(trace),/PRIVATE_SYNTHETIC_HUMAN_CORRECTION|blue hat|estimated transformation|synthetic-transform-v1/);assert.equal(trace.learningAuthority,false);assert.equal(trace.effectAuthority,false);assert.equal(trace.complete,false);assert.equal(trace.durable,false);assert.equal(f.calls(),0);assert.deepEqual(f.worker.visualCandidateHistory(f.owner),[]);assert.deepEqual(f.worker.visualLifecycleHistory(f.owner),[]);
 assert.equal(Reflect.set(trace.sourceReceipt,'eventId',randomUUID()),false);for(const key of ['principalId','assistantId','relationshipId'] as const){assert.equal(f.source.correctionEvidence({...f.owner,[key]:randomUUID()},f.memoryId!),null);assert.deepEqual(f.worker.visualCorrectionHistory({...f.owner,[key]:randomUUID()}),[]);}
});
test('copy, proxy, accessor, legacy and foreign owner cannot donate correction provenance; exact genuine sources deduplicate',async t=>{
 const f=fixture(t);f.correct();const source=f.source.correctionEvidence(f.owner,f.memoryId!)!,journal=new VisualMemoryCandidateEvidence();t.after(()=>journal.close());let accesses=0;const hostile={...source};Object.defineProperty(hostile,'sourceReceipt',{get(){accesses++;return source.sourceReceipt;}});
 for(const invalid of [structuredClone(source),{...source},new Proxy(source,{}),hostile])journal.recordCorrection(f.owner,invalid);journal.recordCorrection({...f.owner,relationshipId:randomUUID()},source);await Promise.resolve();assert.deepEqual(journal.correctionTraces(f.owner),[]);assert.equal(accesses,0);assert.equal(isVisualCorrectionEvidence({...source}),false);assert.equal(isVisualCorrectionEvidence(source),true);
 journal.recordCorrection(f.owner,source);journal.recordCorrection(f.owner,source);await Promise.resolve();assert.equal(journal.correctionTraces(f.owner).length,1);assert.deepEqual(journal.traces(f.owner),[]);assert.deepEqual(journal.lifecycleTraces(f.owner),[]);
 f.db.connection.prepare("UPDATE memory_lifecycle_events SET payload_json=? WHERE event_type='visualCorrectionApplied' AND memory_id=?").run(JSON.stringify({actor:f.owner.principalId,correctionId:source.sourceReceipt.humanEntryId,status:'contradicted',sourceEpisodeRevision:2}),f.memoryId!);assert.equal(f.source.correctionEvidence(f.owner,f.memoryId!),null);
});
test('source-only correction and failed transaction produce no projected correction trace',async t=>{
 const only=fixture(t,false),reply=only.correct();assert.equal(reply.correctionMutationEventId,null);await Promise.resolve();assert.deepEqual(only.worker.visualCorrectionHistory(only.owner),[]);
 const f=fixture(t);f.db.exec("CREATE TRIGGER correction_projection_failure BEFORE INSERT ON memory_lifecycle_events WHEN NEW.event_type='visualUserCorrection' BEGIN SELECT RAISE(ABORT,'synthetic correction failure'); END");assert.throws(()=>f.correct(),/correction failure/);await Promise.resolve();assert.equal(f.source.correctionEvidence(f.owner,f.memoryId!),null);assert.deepEqual(f.worker.visualCorrectionHistory(f.owner),[]);assert.equal(f.memories.get(f.owner.assistantId,f.memoryId!)!.lifecycle.status,'candidate');
});
test('current source, consent, scope and close fence queued or retained correction evidence without admitting old scene recall',async t=>{
 for(const mode of ['scope','memory','visual','sourceForget','memoryForget','close','revision','entry','sourceDigest','utc','environment','mutationShape','expiry'] as const)await t.test(mode,async child=>{
  const f=fixture(child);f.correct();
  if(mode==='scope')f.deny();else if(mode==='memory')f.worker.configure(f.owner,false,1);else if(mode==='visual')f.worker.configureVisual(f.owner,false,1,86400000);else if(mode==='sourceForget')f.worker.forgetVisual(f.owner,f.v.episode.episodeId,3);else if(mode==='memoryForget')f.memories.forget(f.owner.assistantId,f.memoryId!,f.owner.principalId);else if(mode==='close')await f.worker.close();else if(mode==='revision')f.db.connection.prepare("UPDATE memories SET lifecycle_json=json_set(lifecycle_json,'$.revision',99) WHERE id=?").run(f.memoryId!);else if(mode==='entry')f.db.exec("UPDATE memory_lifecycle_events SET payload_json=json_set(payload_json,'$.correctionId','forged') WHERE event_type='visualUserCorrection'");else if(mode==='sourceDigest')f.db.exec("UPDATE visual_observation_episodes SET payload_json=json_set(payload_json,'$.sourceDigest','forged')");else if(mode==='environment')f.db.exec("UPDATE memory_lifecycle_events SET payload_json=json_set(payload_json,'$.visualMutationEnvironmentId',NULL) WHERE event_type='visualCorrectionApplied'");else if(mode==='mutationShape')f.db.exec("UPDATE memory_lifecycle_events SET payload_json=json_set(payload_json,'$.visualMutation.unknown','forged') WHERE event_type='visualCorrectionApplied'");else if(mode==='expiry')f.db.exec('UPDATE visual_observation_episodes SET expires_at=0');else f.db.exec("UPDATE memory_lifecycle_events SET occurred_at='2099-01-01T00:00:00.000Z' WHERE event_type='visualCorrectionApplied'");
  await Promise.resolve();assert.deepEqual(f.worker.visualCorrectionHistory(f.owner),[]);assert.equal(f.memories.contextRecords(f.owner.assistantId,f.owner.principalId).length,0);
 });
});
test('correction during final host scope hook cannot return a source erased by that hook',async t=>{
 const f=fixture(t);f.correct();await Promise.resolve();assert.equal(f.worker.visualCorrectionHistory(f.owner).length,1);
 // The owned scope adapter can perform a concurrent privacy mutation. Inject
 // it on the final read hook without changing any production privacy guard.
 let checks=0;f.onScope(()=>{if(++checks===2)f.memories.forget(f.owner.assistantId,f.memoryId!,f.owner.principalId);return true;});assert.deepEqual(f.worker.visualCorrectionHistory(f.owner),[]);
});
test('correction journal retains existing dual-clock TTL, reset and close limits',async t=>{
 const f=fixture(t);f.correct();const source=f.source.correctionEvidence(f.owner,f.memoryId!)!;for(const mode of ['utc','mono','reset','close','rollback'] as const){let utc=Date.now(),mono=10;const journal=new VisualMemoryCandidateEvidence({utcMs:()=>utc,monotonicMs:()=>mono});journal.recordCorrection(f.owner,source);await Promise.resolve();assert.equal(journal.correctionTraces(f.owner).length,1);if(mode==='utc')utc+=60000;else if(mode==='mono')mono+=60000;else if(mode==='reset')journal.reset();else if(mode==='close')journal.close();else utc--;assert.deepEqual(journal.correctionTraces(f.owner),[]);journal.close();}
});
test('genuine candidate and correction join source identity without certifying the Human correction or omitted history',async t=>{
 const f=fixture(t);await Promise.resolve();const candidate=f.worker.visualCandidateHistory(f.owner)[0]!;f.correct();await Promise.resolve();const correction=f.worker.visualCorrectionHistory(f.owner)[0]!,join=correlateVisualMemoryCorrection(candidate,correction);assert.ok(join);assert.equal(join.memoryId,f.memoryId);assert.equal(join.sourceMutationEventId,correction.sourceReceipt.eventId);assert.equal(join.humanEntryId,correction.sourceReceipt.humanEntryId);assert.equal(join.memorySourcesOwnerMatched,true);assert.equal(join.currentEligibilityProved,false);assert.equal(join.correctedFactProved,false);assert.equal(join.replyFencingProved,false);assert.equal(join.intermediateHistoryComplete,false);
 assert.equal(correlateVisualMemoryCorrection({...candidate},correction),null);assert.equal(correlateVisualMemoryCorrection(candidate,{...correction}),null);const other=fixture(t);await Promise.resolve();assert.equal(correlateVisualMemoryCorrection(other.worker.visualCandidateHistory(other.owner)[0]!,correction),null);
});
test('isolated correction replay after real source forgetting preserves original entry/mutation and leaves storage unchanged',async t=>{
 const f=fixture(t);await Promise.resolve();const candidate=f.worker.visualCandidateHistory(f.owner)[0]!;f.correct();await Promise.resolve();const correction=f.worker.visualCorrectionHistory(f.owner)[0]!,original=JSON.stringify({candidate,correction});f.worker.forgetVisual(f.owner,f.v.episode.episodeId,3);const before=JSON.stringify(f.worker.inspect(f.owner)),replay=replayVisualMemoryCorrection(candidate,correction);assert.ok(replay);assert.equal(replay.sourceReceipt,correction.sourceReceipt);assert.equal(replay.complete,false);assert.equal(replay.liveEffects,false);assert.equal(replay.durableReinforcement,false);assert.equal(replay.sourceMonotonicClockAvailable,false);assert.equal(f.calls(),0);assert.equal(JSON.stringify(f.worker.inspect(f.owner)),before);assert.equal(JSON.stringify({candidate,correction}),original);assert.equal('operation' in replay.sourceReceipt,false);
 for(const [i,e] of replay.events.entries()){const source=[candidate.event,correction.event][i]!;assert.equal(createContractValidator().validate('https://lifestream.dev/contracts/interaction-trace-event/2.0.0',e).valid,true);assert.equal(e.environmentId,replay.environmentId);assert.equal(e.executionMode,'replay');assert.equal(e.eventTime,source.eventTime);assert.deepEqual(e.sourceEventIds,[source.eventId]);assert.deepEqual(e.payload,source.payload);assert.equal(e.monotonic,null);assert.notEqual(e.eventId,source.eventId);assert.equal(e.sequence,i);}
 assert.equal(replay.events[0]!.backgroundJobId,replay.events[1]!.backgroundJobId);assert.notEqual(replay.events[0]!.backgroundJobId,candidate.event.backgroundJobId);assert.equal(replayVisualMemoryCorrection(candidate,replay as never),null);assert.doesNotMatch(JSON.stringify(replay),/PRIVATE_SYNTHETIC_HUMAN_CORRECTION|blue hat|Synthetic estimated transformation/);
});
test('missing actual correction-host deployment never borrows the original capture environment or fabricates background session context',async t=>{
 const f=fixture(t,true,false),reply=f.correct();assert.ok(reply.correctionMutationEventId);assert.equal(f.memories.get(f.owner.assistantId,f.memoryId!)!.lifecycle.status,'contradicted');assert.equal(f.source.correctionEvidence(f.owner,f.memoryId!),null);await Promise.resolve();assert.deepEqual(f.worker.visualCorrectionHistory(f.owner),[]);const row=f.memories.history(f.owner.assistantId,f.memoryId!).at(-1)!;assert.equal(row.payload.visualMutationEnvironmentId,null);assert.equal(f.v.episode.scope.environmentId.length,36);
});
test('a later Human correction has a new original entry/mutation and retires earlier source projection without reinforcement',async t=>{
 const f=fixture(t);await Promise.resolve();const candidate=f.worker.visualCandidateHistory(f.owner)[0]!;const first=f.correct();await Promise.resolve();const prior=f.worker.visualCorrectionHistory(f.owner)[0]!;
 const second=f.worker.correctVisual(f.owner,f.v.episode.episodeId,3,'A second synthetic Human correction.');await Promise.resolve();const [current]=f.worker.visualCorrectionHistory(f.owner);assert.ok(current);assert.notEqual(second.correctionId,first.correctionId);assert.notEqual(second.correctionMutationEventId,first.correctionMutationEventId);assert.equal(current.sourceReceipt.eventId,second.correctionMutationEventId);assert.equal(current.sourceReceipt.humanEntryId,second.correctionId);assert.equal(current.sourceReceipt.oldRevision,2);assert.equal(current.sourceReceipt.newRevision,3);assert.notEqual(current.artifact.reference.sha256,prior.artifact.reference.sha256);assert.equal(correlateVisualMemoryCorrection(candidate,current)!.intermediateHistoryComplete,false);assert.equal(f.memories.list(f.owner.assistantId).length,1);assert.equal(f.memories.contextRecords(f.owner.assistantId,f.owner.principalId).length,0);assert.equal(f.calls(),0);
});
