import type { Database } from "../database.js";
export type Admission = { invocationId: string; grantId: string; grantRevision: number; inputDigest: string; status: "admitted" | "consumed" | "unknown" };
export class AdmissionRepository {
  private readonly admissions = new Map<string, Admission>(); private readonly database: Database | undefined;
  constructor(database?: Database) { this.database = database; if (database) database.exec("CREATE TABLE IF NOT EXISTS dispatch_admissions (invocation_id TEXT PRIMARY KEY, grant_id TEXT NOT NULL, grant_revision INTEGER NOT NULL, input_digest TEXT NOT NULL, status TEXT NOT NULL); CREATE TABLE IF NOT EXISTS authority_grants (id TEXT PRIMARY KEY, status TEXT NOT NULL, revision INTEGER NOT NULL)"); }
  admit(admission: Admission): Admission { if (this.database) return this.database.transaction((tx) => { const prior = tx.get<Admission>("SELECT invocation_id AS invocationId, grant_id AS grantId, grant_revision AS grantRevision, input_digest AS inputDigest, status FROM dispatch_admissions WHERE invocation_id = ?", admission.invocationId); if (prior) return prior; tx.run("INSERT INTO dispatch_admissions VALUES (?, ?, ?, ?, ?)", admission.invocationId, admission.grantId, admission.grantRevision, admission.inputDigest, admission.status); return admission; }); const prior = this.admissions.get(admission.invocationId); if (prior) return structuredClone(prior); this.admissions.set(admission.invocationId, structuredClone(admission)); return structuredClone(admission); }
  updateStatus(invocationId: string, status: Admission["status"]): Admission { const current = this.get(invocationId); if (!current) throw new Error("unknown invocation"); const next = { ...current, status }; if (this.database) this.database.transaction((tx) => tx.run("UPDATE dispatch_admissions SET status = ? WHERE invocation_id = ?", status, invocationId)); else this.admissions.set(invocationId, next); return next; }
  admitOneUse(grantId: string, grantRevision: number, invocationId: string, inputDigest: string): Admission { if (!this.database) return this.admit({ invocationId, grantId, grantRevision, inputDigest, status: "admitted" }); return this.database.transaction((tx) => { const prior = tx.get<Admission>("SELECT invocation_id AS invocationId, grant_id AS grantId, grant_revision AS grantRevision, input_digest AS inputDigest, status FROM dispatch_admissions WHERE invocation_id = ?", invocationId); if (prior) return prior; const grant = tx.get<{ revision: number; status: string }>("SELECT revision, status FROM authority_grants WHERE id = ?", grantId); if (!grant || grant.revision !== grantRevision || grant.status !== "active") throw new Error("grant is not admissible"); tx.run("UPDATE authority_grants SET status = 'consumed', revision = revision + 1 WHERE id = ? AND revision = ? AND status = 'active'", grantId, grantRevision); tx.run("INSERT INTO dispatch_admissions VALUES (?, ?, ?, ?, ?)", invocationId, grantId, grantRevision, inputDigest, "admitted"); return { invocationId, grantId, grantRevision, inputDigest, status: "admitted" }; }); }
  admitGoverned(input: { grantId: string; principalId: string; assistantId: string; sessionId: string; capabilityId: string; invocationId: string; inputDigest: string; now: string; assertCurrent: () => void }): Admission {
    if (!this.database) throw new Error("durable authority admission requires storage");
    return this.database.transaction(tx => {
      input.assertCurrent();
      const grant=tx.get<{revision:number;status:string;principal_id:string;assistant_id:string;scope_json:string;terms_json:string}>("SELECT * FROM authority_grants WHERE id=?",input.grantId);
      if (!grant || grant.principal_id!==input.principalId || grant.assistant_id!==input.assistantId || grant.status!=="active" || !(JSON.parse(grant.scope_json) as string[]).includes(input.capabilityId)) throw new Error("grant is not admissible");
      const terms=JSON.parse(grant.terms_json) as {durationMode:string;expiresAt:string;sessionId:string};
      if (!Number.isFinite(Date.parse(terms.expiresAt)) || Date.parse(terms.expiresAt)<=Date.parse(input.now) || !["allowOnce","allowSession","allowPersistent"].includes(terms.durationMode) || (terms.durationMode!=="allowPersistent" && terms.sessionId!==input.sessionId)) throw new Error("grant terms are not current");
      const prior=tx.get<Admission>("SELECT invocation_id AS invocationId,grant_id AS grantId,grant_revision AS grantRevision,input_digest AS inputDigest,status FROM dispatch_admissions WHERE invocation_id=?",input.invocationId);
      if (prior) { if (prior.grantId!==input.grantId || prior.inputDigest!==input.inputDigest) throw new Error("invocation binding conflict"); return prior; }
      if (terms.durationMode==="allowOnce") { tx.run("UPDATE authority_grants SET status='consumed',revision=revision+1 WHERE id=? AND revision=? AND status='active'",input.grantId,grant.revision); if(tx.get<{changes:number}>("SELECT changes() AS changes")?.changes!==1) throw new Error("grant consumption conflict"); tx.run("INSERT INTO authority_events (grant_id,event,actor,occurred_at) VALUES (?,?,?,?)",input.grantId,"consumed",input.principalId,input.now); }
      tx.run("INSERT INTO dispatch_admissions VALUES (?,?,?,?,?)",input.invocationId,input.grantId,grant.revision,input.inputDigest,"admitted");
      return {invocationId:input.invocationId,grantId:input.grantId,grantRevision:grant.revision,inputDigest:input.inputDigest,status:"admitted"};
    });
  }
  get(invocationId: string): Admission | undefined { if (this.database) { const row = this.database.connection.prepare("SELECT invocation_id AS invocationId, grant_id AS grantId, grant_revision AS grantRevision, input_digest AS inputDigest, status FROM dispatch_admissions WHERE invocation_id = ?").get(invocationId) as Admission | undefined; return row && structuredClone(row); } const a = this.admissions.get(invocationId); return a && structuredClone(a); }
}
