import type { Database } from "../database.js";
export type Admission = { invocationId: string; grantId: string; grantRevision: number; inputDigest: string; status: "admitted" | "consumed" | "unknown" };
export class AdmissionRepository {
  private readonly admissions = new Map<string, Admission>(); private readonly database: Database | undefined;
  constructor(database?: Database) { this.database = database; if (database) database.exec("CREATE TABLE IF NOT EXISTS dispatch_admissions (invocation_id TEXT PRIMARY KEY, grant_id TEXT NOT NULL, grant_revision INTEGER NOT NULL, input_digest TEXT NOT NULL, status TEXT NOT NULL)"); }
  admit(admission: Admission): Admission { if (this.database) return this.database.transaction((tx) => { const prior = tx.get<Admission>("SELECT invocation_id AS invocationId, grant_id AS grantId, grant_revision AS grantRevision, input_digest AS inputDigest, status FROM dispatch_admissions WHERE invocation_id = ?", admission.invocationId); if (prior) return prior; tx.run("INSERT INTO dispatch_admissions VALUES (?, ?, ?, ?, ?)", admission.invocationId, admission.grantId, admission.grantRevision, admission.inputDigest, admission.status); return admission; }); const prior = this.admissions.get(admission.invocationId); if (prior) return structuredClone(prior); this.admissions.set(admission.invocationId, structuredClone(admission)); return structuredClone(admission); }
  updateStatus(invocationId: string, status: Admission["status"]): Admission { const current = this.get(invocationId); if (!current) throw new Error("unknown invocation"); const next = { ...current, status }; if (this.database) this.database.transaction((tx) => tx.run("UPDATE dispatch_admissions SET status = ? WHERE invocation_id = ?", status, invocationId)); else this.admissions.set(invocationId, next); return next; }
  get(invocationId: string): Admission | undefined { if (this.database) { const row = this.database.connection.prepare("SELECT invocation_id AS invocationId, grant_id AS grantId, grant_revision AS grantRevision, input_digest AS inputDigest, status FROM dispatch_admissions WHERE invocation_id = ?").get(invocationId) as Admission | undefined; return row && structuredClone(row); } const a = this.admissions.get(invocationId); return a && structuredClone(a); }
}
