import type { Database } from "../database.js";
export type Grant = { id: string; principalId: string; assistantId: string; status: "pending" | "active" | "denied" | "revoked" | "consumed"; scope: string[]; revision: number; terms: Record<string, unknown>; createdAt: string };
type Row = { id: string; principal_id: string; assistant_id: string; status: Grant["status"]; scope_json: string; revision: number; terms_json: string; created_at: string };
const project = (row: Row): Grant => ({ id: row.id, principalId: row.principal_id, assistantId: row.assistant_id, status: row.status, scope: JSON.parse(row.scope_json) as string[], revision: row.revision, terms: JSON.parse(row.terms_json) as Record<string, unknown>, createdAt: row.created_at });
export class GrantRepository {
  private readonly grants = new Map<string, Grant>(); private readonly database: Database | undefined;
  constructor(database?: Database) { this.database = database; }
  create(grant: Grant): Grant { if (this.database) this.database.transaction(tx => { tx.run("INSERT INTO authority_grants VALUES (?,?,?,?,?,?,?,?)", grant.id, grant.principalId, grant.assistantId, grant.status, JSON.stringify(grant.scope), grant.revision, JSON.stringify(grant.terms), grant.createdAt); tx.run("INSERT INTO authority_events (grant_id,event,actor,occurred_at) VALUES (?,?,?,?)", grant.id, "requested", grant.principalId, grant.createdAt); }); else { if (this.grants.has(grant.id)) throw new Error("duplicate grant"); this.grants.set(grant.id, structuredClone(grant)); } return structuredClone(grant); }
  get(id: string, principalId: string): Grant | undefined { if (this.database) { const row = this.database.connection.prepare("SELECT * FROM authority_grants WHERE id=? AND principal_id=?").get(id, principalId) as Row | undefined; return row && project(row); } const grant = this.grants.get(id); return grant?.principalId === principalId ? structuredClone(grant) : undefined; }
  list(principalId: string, assistantId: string): Grant[] { if (this.database) return (this.database.connection.prepare("SELECT * FROM authority_grants WHERE principal_id=? AND assistant_id=?").all(principalId, assistantId) as Row[]).map(project); return [...this.grants.values()].filter(grant => grant.principalId === principalId && grant.assistantId === assistantId).map(grant => structuredClone(grant)); }
  decide(id: string, principalId: string, expectedRevision: number, status: Grant["status"]): Grant { const grant = this.get(id, principalId); if (!grant || grant.revision !== expectedRevision) throw new Error("stale or unauthorized grant"); if (!(grant.status === "pending" && ["active", "denied"].includes(status)) && !(grant.status === "active" && status === "revoked")) throw new Error("terminal grant"); const next = { ...grant, status, revision: grant.revision + 1 }; if (this.database) this.database.transaction(tx => { tx.run("UPDATE authority_grants SET status=?,revision=? WHERE id=? AND principal_id=? AND revision=? AND status=?", status, next.revision, id, principalId, expectedRevision, grant.status); if (tx.get<{ changes: number }>("SELECT changes() AS changes")?.changes !== 1) throw new Error("stale or unauthorized grant"); tx.run("INSERT INTO authority_events (grant_id,event,actor,occurred_at) VALUES (?,?,?,?)", id, status, principalId, new Date().toISOString()); }); else this.grants.set(id, next); return structuredClone(next); }
}
