export type PwceProfile = { readonly profileId: string; readonly profileVersion: string; readonly bundleId: string; readonly bundleVersion: string; readonly schemaStatus: string; readonly schemaDigest: string; readonly operationCatalogVersion: string; readonly operationCatalogDigest: string; readonly compatibilityRange?: { readonly minimum: string; readonly maximum: string }; readonly operationCatalog: readonly { readonly operation: string; readonly kind?: string; readonly availability?: string }[] };
export type PwceBundle = { readonly bundleId: string; readonly bundleVersion: string; readonly bundleDigest: string; readonly artifacts: readonly { readonly path: string; readonly sha256: string }[]; readonly generatedClient: { readonly path: string; readonly sha256: string } };
export type PwceClientOptions = { readonly baseUrl: string; readonly token: string; readonly fetchImpl?: typeof fetch };
export type PwceClientResult = { readonly status: string; readonly [key: string]: unknown };
export type PwceInvalidationEvent = { readonly id: string | null; readonly event: string; readonly data: string };
export const EXPECTED_PWCE_PROFILE = Object.freeze({ profileId: "pwce-agent-gateway.v1", profileVersion: "1.0.0", bundleId: "pwce-agent-gateway.bundle.v1", bundleVersion: "1.0.0", schemaDigest: "32c555ba675b61b4c1ec82245e314a8f6ca537484defbeb48b9fe1b6bdf4e2e2", operationCatalogVersion: "0.1.0", operationCatalogDigest: "445cb4e4b9811a26a41c5821c7d68b09f377b69d24d42ec6dcd0acec5d950b65" });
export const EXPECTED_PWCE_ARTIFACTS = Object.freeze([
  { path: "contracts/gateway/operation-catalog.json", sha256: "51bfb941913fc27578dc3c4b3ca038d4bfdf4433eda72f2069173503e7b19a0c" },
  { path: "contracts/gateway/pwce-agent-gateway-profile.schema.json", sha256: "268a4e670ba9b32457725944c87ec46fda7dda821dc2f48fc5d8ff022f434e36" },
  { path: "contracts/gateway/pwce-agent-gateway-request.schema.json", sha256: "56fdd84719ddbe6d5d2a9644e9079b25df2e719dcbf0a9e33b3bf16d79760175" },
  { path: "contracts/gateway/pwce-agent-gateway-response.schema.json", sha256: "06fc6a9635c192329d43723f596330a336f1f3e57edd05e7d634110ebbb6f9ae" },
  { path: "contracts/gateway/pwce-lifestream-compatibility-lock.schema.json", sha256: "25fe08baaf362deb929abdb99980a7911fc6b63a4cbaf651749d66b021ffd78e" },
  { path: "contracts/gateway/pwce-agent-gateway-authority-request.schema.json", sha256: "c88e5eb7bb98c867ed5e0a2bf71c4e58f012aa068ecd8fc93cd40caecc42b318" },
  { path: "contracts/gateway/pwce-agent-gateway-authority-response.schema.json", sha256: "b064fc855886a63beb7ca934cdef8f2c51a20e9244c399a0d19afeb635a2c82f" },
] as const);
export const EXPECTED_PWCE_GENERATED_CLIENT_SHA256 = "fdb2a5a425b1a54e0d41c923e6ae701eb865e710334869c885b499f06abde175";

export class PwceGatewayClient {
  private readonly baseUrl: string; private readonly token: string; private readonly fetchImpl: typeof fetch;
  constructor(options: PwceClientOptions) { if (!options.baseUrl || !options.token) throw new Error("PWCE gateway URL and token are required"); this.baseUrl = options.baseUrl.replace(/\/$/, ""); this.token = options.token; this.fetchImpl = options.fetchImpl ?? fetch; }
  async profile(signal?: AbortSignal): Promise<PwceProfile> { const profile = await this.json<PwceProfile>("/gateway/v1/profile", { ...(signal ? { signal } : {}) }); if (profile.profileId !== EXPECTED_PWCE_PROFILE.profileId || profile.profileVersion !== EXPECTED_PWCE_PROFILE.profileVersion || profile.bundleId !== EXPECTED_PWCE_PROFILE.bundleId || profile.bundleVersion !== EXPECTED_PWCE_PROFILE.bundleVersion || profile.schemaDigest !== EXPECTED_PWCE_PROFILE.schemaDigest || profile.operationCatalogVersion !== EXPECTED_PWCE_PROFILE.operationCatalogVersion || profile.operationCatalogDigest !== EXPECTED_PWCE_PROFILE.operationCatalogDigest || profile.schemaStatus !== "published") throw new Error("PWCE gateway profile is incompatible"); return profile; }
  async bundle(signal?: AbortSignal): Promise<PwceBundle> { const bundle = await this.json<PwceBundle>("/gateway/v1/bundle", { ...(signal ? { signal } : {}) }); if (bundle.bundleId !== EXPECTED_PWCE_PROFILE.bundleId || bundle.bundleVersion !== EXPECTED_PWCE_PROFILE.bundleVersion || bundle.bundleDigest !== EXPECTED_PWCE_PROFILE.schemaDigest || bundle.generatedClient.path !== "src/gateway/generated-client.js" || bundle.generatedClient.sha256 !== EXPECTED_PWCE_GENERATED_CLIENT_SHA256 || JSON.stringify(bundle.artifacts) !== JSON.stringify(EXPECTED_PWCE_ARTIFACTS)) throw new Error("PWCE gateway bundle is incompatible"); return bundle; }
  async negotiate(signal?: AbortSignal): Promise<{ readonly profile: PwceProfile; readonly bundle: PwceBundle }> { const [profile, bundle] = await Promise.all([this.profile(signal), this.bundle(signal)]); return { profile, bundle }; }
  async authority(siteRefs: readonly string[], signal?: AbortSignal): Promise<PwceClientResult> { await this.negotiate(signal); return this.json("/gateway/v1/authority", { method: "POST", body: { siteRefs: [...siteRefs] }, ...(signal ? { signal } : {}) }); }
  async request(payload: Record<string, unknown>, signal?: AbortSignal): Promise<PwceClientResult> { const { profile } = await this.negotiate(signal); if (!profile.operationCatalog.some((entry) => entry.operation === payload.operation)) throw new Error("PWCE operation is not advertised"); return this.json("/gateway/v1/request", { method: "POST", body: payload, ...(signal ? { signal } : {}) }); }
  getPreparedInputs(authorityContextRef: string, siteRef: string, signal?: AbortSignal): Promise<PwceClientResult> { return this.request({ operation: "context.getPreparedInputs", authorityContextRef, siteRef }, signal); }
  queryContext(authorityContextRef: string, query: Record<string, unknown>, signal?: AbortSignal): Promise<PwceClientResult> { return this.request({ operation: "context.query", authorityContextRef, ...query }, signal); }
  getEvidence(authorityContextRef: string, evidenceRef: string, signal?: AbortSignal): Promise<PwceClientResult> { return this.request({ operation: "evidence.get", authorityContextRef, evidenceRef }, signal); }
  getGrants(authorityContextRef: string, signal?: AbortSignal): Promise<PwceClientResult> { return this.request({ operation: "authority.getGrants", authorityContextRef }, signal); }
  evaluate(authorityContextRef: string, input: Record<string, unknown>, signal?: AbortSignal): Promise<PwceClientResult> { return this.request({ operation: "authority.evaluate", authorityContextRef, ...input }, signal); }
  authorizeDispatch(authorityContextRef: string, input: Record<string, unknown>, signal?: AbortSignal): Promise<PwceClientResult> { return this.request({ operation: "authority.authorizeDispatch", authorityContextRef, ...input }, signal); }
  getCapabilities(authorityContextRef: string, signal?: AbortSignal): Promise<PwceClientResult> { return this.request({ operation: "capabilities.getSnapshot", authorityContextRef }, signal); }
  invoke(authorityContextRef: string, input: Record<string, unknown>, signal?: AbortSignal): Promise<PwceClientResult> { return this.request({ operation: "capabilities.invoke", authorityContextRef, ...input }, signal); }
  getInvocation(authorityContextRef: string, actionRef: string, signal?: AbortSignal): Promise<PwceClientResult> { return this.request({ operation: "capabilities.getInvocation", authorityContextRef, actionRef }, signal); }
  publishTrace(authorityContextRef: string, input: Record<string, unknown>, signal?: AbortSignal): Promise<PwceClientResult> { return this.request({ operation: "trace.publish", authorityContextRef, ...input }, signal); }
  eventsUrl(authorityContextRef: string, siteRef: string, afterCursor = "0", limit = 100): string { const params = new URLSearchParams({ authorityContextRef, siteRef, afterCursor, limit: String(limit) }); return `${this.baseUrl}/gateway/v1/events?${params}`; }
  async *subscribeInvalidations(authorityContextRef: string, siteRef: string, options: { readonly afterCursor?: string; readonly limit?: number; readonly signal?: AbortSignal } = {}): AsyncGenerator<PwceInvalidationEvent> {
    await this.negotiate(options.signal);
    const response = await this.fetchImpl(this.eventsUrl(authorityContextRef, siteRef, options.afterCursor ?? "0", options.limit ?? 100), { method: "GET", headers: { Authorization: `Bearer ${this.token}`, Accept: "text/event-stream" }, ...(options.signal ? { signal: options.signal } : {}) });
    if (!response.ok || !response.body) throw new Error(`PWCE gateway event stream failed with status ${response.status}`);
    const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; let event: { id?: string; event?: string; data: string[] } = { data: [] };
    const emit = (): PwceInvalidationEvent | null => { if (!event.data.length) return null; const value = { id: event.id ?? null, event: event.event ?? "message", data: event.data.join("\n") }; event = { data: [] }; return value; };
    try {
      while (true) {
        const chunk = await reader.read(); buffer += decoder.decode(chunk.value ?? new Uint8Array(), { stream: !chunk.done }); const lines = buffer.split("\n"); buffer = lines.pop() ?? "";
        for (const rawLine of lines) { const line = rawLine.endsWith("\r") ? rawLine.slice(0, -1) : rawLine; if (!line) { const parsed = emit(); if (parsed) yield parsed; continue; } if (line.startsWith(":")) continue; const separator = line.indexOf(":"); const field = separator < 0 ? line : line.slice(0, separator); const value = separator < 0 ? "" : line.slice(separator + 1).replace(/^ /, ""); if (field === "id") event.id = value; else if (field === "event") event.event = value; else if (field === "data") event.data.push(value); }
        if (chunk.done) { const parsed = emit(); if (parsed) yield parsed; break; }
      }
    } finally { reader.releaseLock(); }
  }
  health(authorityContextRef: string, signal?: AbortSignal): Promise<PwceClientResult> { return this.request({ operation: "health.get", authorityContextRef }, signal); }
  private async json<T extends object>(path: string, options: { readonly method?: string; readonly body?: unknown; readonly signal?: AbortSignal } = {}): Promise<T> { const response = await this.fetchImpl(`${this.baseUrl}${path}`, { method: options.method ?? "GET", headers: { Authorization: `Bearer ${this.token}`, "Content-Type": "application/json" }, ...(options.body === undefined ? {} : { body: JSON.stringify(options.body) }), ...(options.signal ? { signal: options.signal } : {}) }); const value = await response.json() as T & { readonly error?: { readonly message?: string } }; if (!response.ok) throw new Error(value.error?.message ?? "PWCE gateway request failed"); return value; }
}
