export type PwceProfile = { readonly profileId: string; readonly profileVersion: string; readonly schemaStatus: string; readonly schemaDigest: string; readonly operationCatalogVersion: string; readonly operationCatalogDigest: string; readonly compatibilityRange: { readonly minimum: string; readonly maximum: string }; readonly operationCatalog: readonly { readonly operation: string; readonly kind?: string; readonly availability?: string }[] };
export type PwceClientOptions = { readonly baseUrl: string; readonly token: string; readonly fetchImpl?: typeof fetch };
export type PwceClientResult = { readonly status: string; readonly [key: string]: unknown };
export const EXPECTED_PWCE_PROFILE = Object.freeze({ profileId: "pwce-agent-gateway.v1", profileVersion: "1.0.0", schemaDigest: "b3e3d12384c17a2e659f0b66504d8cc226673bd2bc25bf135fdbe58fb8909717", operationCatalogDigest: "445cb4e4b9811a26a41c5821c7d68b09f377b69d24d42ec6dcd0acec5d950b65" });

export class PwceGatewayClient {
  private readonly baseUrl: string; private readonly token: string; private readonly fetchImpl: typeof fetch;
  constructor(options: PwceClientOptions) { if (!options.baseUrl || !options.token) throw new Error("PWCE gateway URL and token are required"); this.baseUrl = options.baseUrl.replace(/\/$/, ""); this.token = options.token; this.fetchImpl = options.fetchImpl ?? fetch; }
  async profile(signal?: AbortSignal): Promise<PwceProfile> { const profile = await this.json<PwceProfile>("/gateway/v1/profile", { signal }); if (profile.profileId !== EXPECTED_PWCE_PROFILE.profileId || profile.profileVersion !== EXPECTED_PWCE_PROFILE.profileVersion || profile.schemaDigest !== EXPECTED_PWCE_PROFILE.schemaDigest || profile.operationCatalogDigest !== EXPECTED_PWCE_PROFILE.operationCatalogDigest || profile.schemaStatus !== "published") throw new Error("PWCE gateway profile is incompatible"); return profile; }
  authority(siteRefs: readonly string[], signal?: AbortSignal): Promise<PwceClientResult> { return this.json("/gateway/v1/authority", { method: "POST", body: { siteRefs: [...siteRefs] }, signal }); }
  async request(payload: Record<string, unknown>, signal?: AbortSignal): Promise<PwceClientResult> { const profile = await this.profile(signal); if (!profile.operationCatalog.some((entry) => entry.operation === payload.operation)) throw new Error("PWCE operation is not advertised"); return this.json("/gateway/v1/request", { method: "POST", body: payload, signal }); }
  getPreparedInputs(authorityContextRef: string, siteRef: string, signal?: AbortSignal): Promise<PwceClientResult> { return this.request({ operation: "context.getPreparedInputs", authorityContextRef, siteRef }, signal); }
  queryContext(authorityContextRef: string, query: Record<string, unknown>, signal?: AbortSignal): Promise<PwceClientResult> { return this.request({ operation: "context.query", authorityContextRef, ...query }, signal); }
  health(authorityContextRef: string, signal?: AbortSignal): Promise<PwceClientResult> { return this.request({ operation: "health.get", authorityContextRef }, signal); }
  private async json<T extends PwceClientResult | PwceProfile>(path: string, options: { readonly method?: string; readonly body?: unknown; readonly signal?: AbortSignal } = {}): Promise<T> { const response = await this.fetchImpl(`${this.baseUrl}${path}`, { method: options.method ?? "GET", headers: { Authorization: `Bearer ${this.token}`, "Content-Type": "application/json" }, ...(options.body === undefined ? {} : { body: JSON.stringify(options.body) }), signal: options.signal }); const value = await response.json() as T & { readonly error?: { readonly message?: string } }; if (!response.ok) throw new Error(value.error?.message ?? "PWCE gateway request failed"); return value; }
}
