import {createHash} from 'node:crypto';
import {isDeepStrictEqual} from 'node:util';
import {validateCapabilitySchema,boundedJson} from '@lifestream/runtime/capabilities/schema-validation';
import {PwceGatewayClient} from './client.ts';
import {PwceCallScope,PwceTransportError,boundedFetch,readJsonObject,checkStatus,cancelBody} from './transport.ts';
import {EXPECTED_PWCE_INCIDENT_BUNDLE as contract,PWCE_INCIDENT_REQUEST_SCHEMA,PWCE_INCIDENT_RESPONSE_SCHEMA} from './incident-bundle.ts';
export type PwceIncidentIdentity={assistantRef:string;endpointRef:string;participantRefs:string[];audienceRef:string};
export type PwceIncident={evidenceRef:string;siteRef:string;zoneRef:string;eventClass:string;state:'pending'|'ready'|'failed'|'expired';occurredAt:string;lastTriggerAt:string;windowStart:string;windowEnd:string;expiresAt:string;summary:string;media:null|{sha256:string;bytes:number;mime:string;actualStart:string;actualEnd:string};limitations:string[]};
export type PwceIncidentOptions={baseUrl:string;token:string;worldRef:string;siteRef:string;replay?:boolean;fetchImpl?:typeof fetch};
const fail=(code:string):never=>{throw new PwceTransportError(code,'Incident evidence is unavailable ('+code+').');};
/** Read-only public contract client. No media is sent to prompt, memory or trace sinks. */
export class PwceIncidentClient{
 private readonly options:PwceIncidentOptions;private readonly fetch:typeof fetch;private readonly gateway:PwceGatewayClient;
 constructor(options:PwceIncidentOptions){this.gateway=new PwceGatewayClient(options);const u=new URL(options.baseUrl);if(u.pathname!=='/'||!options.worldRef||!options.siteRef)throw Error('Incident endpoint requires an origin, World and site');this.options={...options,baseUrl:u.origin};this.fetch=options.fetchImpl??fetch;}
 private async call<T>(identity:PwceIncidentIdentity,current:()=>boolean,signal:AbortSignal|undefined,action:(request:Record<string,unknown>,scope:PwceCallScope)=>Promise<T>):Promise<T>{
  identity=structuredClone(identity);const scope=new PwceCallScope(10000,signal);try{if(!current())return fail('scope_invalidated');const headers={authorization:'Bearer '+this.options.token};const bundleResponse=await boundedFetch(this.fetch,this.options.baseUrl+contract.routes.bundle,{headers},scope),bundle=await readJsonObject(bundleResponse,scope);checkStatus(bundleResponse,bundle);if(!isDeepStrictEqual(bundle,contract))return fail('incompatible_incident_contract');
   const authority=await this.gateway.authority([this.options.siteRef],scope.signal,identity);if(!current())return fail('scope_invalidated');const request={operation:'list',authorityContextRef:authority.authorityContextRef,siteRef:this.options.siteRef,worldRef:this.options.worldRef,executionEnvironmentRef:'normal',...structuredClone(identity),deadline:new Date(Date.now()+9000).toISOString()};if(!boundedJson(request,8192)||!await validateCapabilitySchema(PWCE_INCIDENT_REQUEST_SCHEMA,request,scope.signal,false,65536))return fail('invalid_incident_scope');const result=await action(request,scope);scope.check();if(!current())return fail('scope_invalidated');return result;
  }finally{scope.close();}
 }
 private async post(path:string,body:Record<string,unknown>,scope:PwceCallScope){return boundedFetch(this.fetch,this.options.baseUrl+path,{method:'POST',headers:{authorization:'Bearer '+this.options.token,'content-type':'application/json','x-pwce-incident-contract':contract.bundleDigest},body:JSON.stringify(body)},scope);}
 private async query(body:Record<string,unknown>,scope:PwceCallScope):Promise<PwceIncident[]>{const response=await this.post(contract.routes.query,body,scope),value=await readJsonObject(response,scope);checkStatus(response,value);if(!boundedJson(value,contract.maximumResponseBytes)||!await validateCapabilitySchema(PWCE_INCIDENT_RESPONSE_SCHEMA,value,scope.signal,false,131072))return fail('invalid_incident_response');const records=value.incidents as PwceIncident[];if(records.some(i=>i.siteRef!==this.options.siteRef||(i.state==='ready')!==!!i.media)||new Set(records.map(i=>i.evidenceRef)).size!==records.length)return fail('invalid_incident_scope');return records;}
 list(identity:PwceIncidentIdentity,current:()=>boolean,signal?:AbortSignal){return this.call(identity,current,signal,async(request,scope)=>({replay:this.options.replay===true,incidents:await this.query(request,scope)}));}
 media(evidenceRef:string,identity:PwceIncidentIdentity,current:()=>boolean,signal?:AbortSignal){return this.call(identity,current,signal,async(request,scope)=>{
  if(!/^pwce:incident:[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/.test(evidenceRef))return fail('invalid_incident_reference');const items=await this.query({...request,operation:'get',evidenceRef},scope),item=items[0];if(items.length!==1||item?.evidenceRef!==evidenceRef||item.state!=='ready'||!item.media||Date.parse(item.expiresAt)<=Date.now())return fail('incident_media_unavailable');const expected=item.media,response=await this.post(contract.routes.media,{...request,operation:'media',evidenceRef},scope);if(!response.ok){checkStatus(response,await readJsonObject(response,scope));return fail('incident_media_unavailable');}
  if(response.headers.get('content-type')!==expected.mime||Number(response.headers.get('content-length'))!==expected.bytes||response.headers.get('x-pwce-content-sha256')!==expected.sha256||!response.body){cancelBody(response.body);return fail('incident_media_integrity');}const reader=response.body.getReader(),parts:Uint8Array[]=[];let length=0;try{while(true){const part=await scope.wait(reader.read());if(part.done)break;length+=part.value.length;if(length>expected.bytes||length>contract.maximumMediaBytes)return fail('incident_media_limit');parts.push(part.value);}}finally{void reader.cancel().catch(()=>{});reader.releaseLock();}
  const bytes=Buffer.concat(parts);if(bytes.length!==expected.bytes||createHash('sha256').update(bytes).digest('hex')!==expected.sha256)return fail('incident_media_integrity');const after=(await this.query({...request,operation:'get',evidenceRef},scope))[0];if(!after||after.state!=='ready'||!isDeepStrictEqual(after.media,expected))return fail('incident_media_invalidated');return {bytes,mime:expected.mime,evidenceRef};
 });}
}
