import assert from "node:assert/strict";
import { test } from "node:test";
import { VoxCpmProvider } from "../src/provider.ts";
import { parseNdjson, validateProtocolEvents } from "../src/protocol.ts";

const request = { contractVersion: "2.0.0" as const, deadlineAt: "2026-09-07T00:01:00Z", now: () => "2026-09-07T00:00:00Z", text: "Hello", segmentId: "segment-1", format: { encoding: "pcm_s16le" as const, sampleRateHz: 48000 as const, channels: 1 as const }, voiceProfile: { voiceRef: "opaque-voice", revision: 1 }, decision: { decisionId: "decision-1", revision: 2, valence: 0, arousal: 0.4, urgency: "normal" as const, deliveryMode: "neutral" as const, pace: 0.5, energy: 0.5 }, delivery: { interactionId: "interaction-1", segmentId: "segment-1", decisionId: "decision-1", decisionRevision: 2, deliveryMode: "neutral" as const, urgency: "normal" as const, pace: 0.5, energy: 0.5 } };
const response = (body: string): Response => new Response(body, { status: 200, headers: { "content-type": "application/x-ndjson" } });
const stream = () => JSON.stringify({ kind: "preAudio", sequence: 0, requestId: "r", correlationId: "decision-1", voiceBundleRevision: 1, requestedDelivery: request.delivery, appliedDelivery: request.delivery, degradedDimensions: [], mappingRevision: "voxcpm2-map-1", effectiveSynthesis: { mode: "neutral" }, format: request.format, runtimeRevision: "19b6bf7590025418821a86dcb817504e0ad7e5df", modelRevision: "hf-snapshot" }) + "\n" + JSON.stringify({ kind: "data", sequence: 1, sampleOffset: 0, sampleCount: 10, dataBase64: "AAAA", format: request.format }) + "\n" + JSON.stringify({ kind: "terminal", sequence: 2, outcome: "completed", outputSamples: 10, frameCount: 1 }) + "\n";

test("VoxCPM adapter maps the private preAudio/data/terminal protocol", async () => { const provider = new VoxCpmProvider({ baseUrl: "http://127.0.0.1:8787", voiceBundleKey: "fixture-voice-design", voiceBundleRevision: 1, runtimeRevision: "19b6bf7590025418821a86dcb817504e0ad7e5df", modelRevision: "hf-snapshot", mappingRevision: "voxcpm2-map-1", fetch: async () => response(stream()) }); const events = []; for await (const event of provider.synthesize(request)) events.push(event); assert.deepEqual(events.map((event) => event.kind), ["preAudio", "data", "terminal"]); assert.equal(events[0]?.decisionId, "decision-1"); assert.equal(events[1]?.frame.sampleOffset, 0); assert.equal(events.at(-1)?.outcome, "succeeded"); });
test("VoxCPM adapter fences transport cancellation and validates malformed protocol", async () => { const controller = new AbortController(); controller.abort(); const provider = new VoxCpmProvider({ baseUrl: "http://127.0.0.1:8787", voiceBundleKey: "fixture", voiceBundleRevision: 1, runtimeRevision: "r", modelRevision: "m", mappingRevision: "map", fetch: async () => { throw new Error("aborted"); } }); const events = []; for await (const event of provider.synthesize(request, controller.signal)) events.push(event); assert.equal(events.at(-1)?.outcome, "cancelled"); assert.throws(() => validateProtocolEvents(parseNdjson(JSON.stringify({ kind: "data", sequence: 0, sampleOffset: 0, sampleCount: 1, dataBase64: "AAAA", format: request.format }))), /lifecycle/); });
test("VoxCPM adapter yields preAudio before the complete response is available", async () => { let release: (() => void) | undefined; const gate = new Promise<void>((resolve) => { release = resolve; }); const first = JSON.stringify({ kind: "preAudio", sequence: 0, requestId: "r", correlationId: "decision-1", voiceBundleRevision: 1, requestedDelivery: request.delivery, appliedDelivery: request.delivery, degradedDimensions: [], mappingRevision: "voxcpm2-map-1", effectiveSynthesis: {}, format: request.format, runtimeRevision: "r", modelRevision: "m" }) + "\n"; const rest = stream().split("\n").slice(1).filter(Boolean).join("\n") + "\n"; const body = new ReadableStream<Uint8Array>({ start(controller) { controller.enqueue(new TextEncoder().encode(first)); void gate.then(() => { controller.enqueue(new TextEncoder().encode(rest)); controller.close(); }); } }); const provider = new VoxCpmProvider({ baseUrl: "http://127.0.0.1:8787", voiceBundleKey: "fixture", voiceBundleRevision: 1, runtimeRevision: "r", modelRevision: "m", mappingRevision: "map", fetch: async () => new Response(body, { status: 200 }) }); const iterator = provider.synthesize(request)[Symbol.asyncIterator](); const firstEvent = await iterator.next(); assert.equal(firstEvent.value?.kind, "preAudio"); release?.(); const events = [firstEvent.value]; for await (const event of { [Symbol.asyncIterator]: () => iterator }) events.push(event); assert.equal(events.at(-1)?.kind, "terminal"); });
