import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import { access, mkdir, readFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { AssistantProfileRepository, Database, type AssistantProfile } from "@lifestream/storage-sqlite";
import { loadProfile, redactedDigest } from "./config/loader.ts";
import { createProviderRegistry, type ProviderInstanceHealth, type ProviderRegistry } from "./composition/providers.ts";
import type { RuntimeConfig } from "./config/schema.js";
import { streamMessage } from "./runtime/inference.ts";

export type HealthState = "starting" | "ready" | "degraded" | "draining" | "stopped";
export type ServerOptions = { config: RuntimeConfig; host?: string; port?: number; shutdownDeadlineMs?: number; controlUiDirectory?: string };
type Json = Record<string, unknown>;
type AuthContext = { principalId: string; sessionId: string; expiresAt: string; origin: string };
const json = (response: ServerResponse, status: number, body: Json) => { const payload = JSON.stringify(body); response.writeHead(status, { "content-type": "application/json; charset=utf-8", "cache-control": "no-store", "content-length": Buffer.byteLength(payload) }); response.end(payload); };
const text = (response: ServerResponse, status: number, contentType: string, body: string) => { response.writeHead(status, { "content-type": contentType, "cache-control": "no-store", "content-length": Buffer.byteLength(body) }); response.end(body); };
const originFor = (request: IncomingMessage): string => { const origin = request.headers.origin; return typeof origin === "string" && origin.length > 0 ? origin : `http://${request.headers.host ?? "localhost"}`; };
const fixtureContext = (request: IncomingMessage, origin: string): AuthContext | undefined => { const session = request.headers["x-lifestream-fixture-session"]; const principal = request.headers["x-lifestream-fixture-principal"]; if (typeof session !== "string" || !session || typeof principal !== "string" || !principal) return undefined; return { principalId: principal, sessionId: session, expiresAt: "2999-01-01T00:00:00.000Z", origin }; };
const authorityApi = (method: string, path: string, context: AuthContext | undefined, requestOrigin: string, body: unknown): Json & { status: number } => { const mutation = new Set(["POST", "PUT", "PATCH", "DELETE"]); if (!context || Date.parse(context.expiresAt) <= Date.now()) return { status: 401, code: "authentication_required", message: "authentication required" }; if (context.origin !== requestOrigin) return { status: 403, code: "origin_rejected", message: "origin rejected" }; if (mutation.has(method) && (!body || typeof body !== "object")) return { status: 422, code: "invalid_request", message: "invalid request" }; if (!path.startsWith("/api/authority/v1/")) return { status: 404, code: "not_found", message: "not found" }; if (path.includes("/dispatch") || path === "/api/authority/v1/grants") return { status: method === "GET" ? 200 : 405, code: method === "GET" ? "ok" : "method_not_allowed", message: method === "GET" ? "ok" : "method not allowed" }; if (method === "GET") return { status: 200, code: "ok", message: "ok" }; return { status: 202, code: "accepted", message: `request accepted for ${context.principalId}` }; };
const requestPath = (request: IncomingMessage): string => new URL(request.url ?? "/", "http://lifestream.invalid").pathname;
const readBody = async (request: IncomingMessage): Promise<unknown> => { const chunks: Buffer[] = []; for await (const chunk of request) chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)); if (!chunks.length) return {}; try { return JSON.parse(Buffer.concat(chunks).toString("utf8")); } catch { return undefined; } };
const ensureStorage = async (config: RuntimeConfig) => { if (config.storage.databasePath !== ":memory:") { await mkdir(dirname(resolve(config.storage.databasePath)), { recursive: true }); await access(dirname(resolve(config.storage.databasePath))); } await mkdir(resolve(config.storage.artifactDirectory), { recursive: true }); await access(resolve(config.storage.artifactDirectory)); };
const uiRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../../control-web");
type AdminResult = { status: number; body: Record<string, unknown> };
const asObject = (value: unknown): Record<string, unknown> | undefined => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : undefined;
const profileFor = (assistantId: string, profileId: string, revision: number, input: Record<string, unknown>, actor: string): AssistantProfile => ({ schemaVersion: "2.0.0", assistantId, profileId, revision, status: "draft", createdAt: new Date().toISOString(), createdBy: actor, displayName: typeof input.displayName === "string" && input.displayName.trim() ? input.displayName.trim() : "Example Assistant", corePersona: input.corePersona ?? { canonicalName: "Example Assistant", identityStatement: "A user-authored Assistant.", values: [], prohibitions: [], relationshipBoundaries: [], styleBoundaries: [] }, adaptivePersonaPolicy: input.adaptivePersonaPolicy ?? { dimensions: [] }, voiceProfile: input.voiceProfile ?? null, embodimentProfile: input.embodimentProfile ?? null, presentationProfile: input.presentationProfile ?? null, providerProfile: input.providerProfile ?? { inference: "fixture", memory: "fixture", stt: "fixture", tts: "fixture", renderer: "fixture" } });
class AssistantAdminApi {
  private readonly profiles: AssistantProfileRepository;
  constructor(profiles: AssistantProfileRepository) { this.profiles = profiles; }
  handle(method: string, path: string, actor: string, body: unknown = {}): AdminResult { const parts = path.split("/").filter(Boolean); if (parts[0] !== "api" || parts[1] !== "admin" || parts[2] !== "v1" || parts[3] !== "assistants") return { status: 404, body: { code: "not_found", message: "not found" } }; const input = asObject(body); if (method === "POST" && parts.length === 4) { const assistantId = randomUUID(); const profile = profileFor(assistantId, randomUUID(), 1, input ?? {}, actor); this.profiles.create(profile); return { status: 201, body: { assistantId, activeRevision: null, profile } }; } const assistantId = parts[4]; if (!assistantId) return { status: 422, body: { code: "invalid_request", message: "assistant id required" } }; const profiles = this.profiles.list(assistantId); if (!profiles.length) return { status: 404, body: { code: "not_found", message: "assistant not found" } }; if (method === "GET" && parts.length === 5) return { status: 200, body: { assistantId, profiles, activeProfile: profiles.find((profile) => profile.status === "active") ?? null } }; if (method === "POST" && parts[5] === "revisions") { const latest = profiles[profiles.length - 1]; const profile = profileFor(assistantId, randomUUID(), (latest?.revision ?? 0) + 1, input ?? {}, actor); this.profiles.create(profile); return { status: 201, body: { profile } }; } if (method === "POST" && parts[5] === "activate") { const profileId = typeof input?.profileId === "string" ? input.profileId : ""; const expectedValue = input?.expectedActiveRevision; const expected = expectedValue === null || Number.isInteger(expectedValue) ? expectedValue as number | null : null; if (!profileId) return { status: 422, body: { code: "invalid_request", message: "profileId is required" } }; try { return { status: 200, body: { profile: this.profiles.activate(profileId, expected, actor, typeof input?.reason === "string" ? input.reason : "Activated from control panel", new Date().toISOString()) } }; } catch (error) { const message = error instanceof Error ? error.message : "activation failed"; return { status: message.includes("conflict") ? 409 : 422, body: { code: message.includes("conflict") ? "revision_conflict" : "invalid_request", message } }; } } if (method === "GET" && parts[5] === "export") return { status: 200, body: { schemaVersion: "1.0.0", assistantId, exportedAt: new Date().toISOString(), profiles } }; return { status: 404, body: { code: "not_found", message: "admin operation not found" } }; }
}
export class LifestreamServer {
  readonly config: RuntimeConfig; readonly server: Server; readonly host: string; readonly port: number; readonly shutdownDeadlineMs: number;
  private readonly controlUiDirectory: string; private state: HealthState = "starting"; private storageReady = false; private listening = false; private readonly activeWork = new Set<Promise<unknown>>(); private readonly database: Database; private readonly admin: AssistantAdminApi; private readonly providers: ProviderRegistry; private migrationRecords: ReturnType<Database["migrate"]> = [];
  constructor(options: ServerOptions) { this.config = options.config; this.host = options.host ?? "127.0.0.1"; this.port = options.port ?? 0; this.shutdownDeadlineMs = options.shutdownDeadlineMs ?? 2_000; this.controlUiDirectory = options.controlUiDirectory ?? uiRoot; this.providers = createProviderRegistry(this.config); this.database = new Database({ path: this.config.storage.databasePath }); this.migrationRecords = this.database.migrate(); this.storageReady = true; this.admin = new AssistantAdminApi(new AssistantProfileRepository(this.database)); this.server = createServer((request, response) => { if (request.method === "POST" && request.url?.startsWith("/api/runtime/v1/messages")) void this.handleRuntime(request, response); else void this.handle(request, response); }); }
  get health(): Json { const providerHealth: Record<string, ProviderInstanceHealth> = this.providers.providers; const ready = this.storageReady && this.providers.ready && this.state === "ready" && this.listening; const status = this.state === "starting" ? "starting" : this.state === "draining" ? "draining" : this.state === "stopped" ? "stopped" : ready ? "ready" : "degraded"; return { status, profile: this.config.profile, configurationDigest: redactedDigest(this.config), storage: this.storageReady ? "ready" : "unavailable", migrations: { applied: this.migrationRecords.length, ids: this.migrationRecords.map((migration) => migration.id), expectedIds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13] }, authority: this.config.authority.provider === "fixture" ? "fixture-authenticated" : "unavailable", providers: providerHealth, acceptingInteractions: ready }; }
  async start(): Promise<void> { if (this.listening) return; await ensureStorage(this.config); this.migrationRecords = this.database.migrate(); this.storageReady = true; await new Promise<void>((resolveStart, reject) => { const onError = (error: Error) => { this.server.off("listening", onListening); reject(error); }; const onListening = () => { this.server.off("error", onError); resolveStart(); }; this.server.once("error", onError); this.server.once("listening", onListening); this.server.listen(this.port, this.host); }); this.listening = true; await this.providers.probe(); this.state = this.providers.ready ? "ready" : "degraded"; }
  async runBoundedWork<T>(work: Promise<T>): Promise<T> { if (this.state !== "ready") throw new Error("server is not accepting work"); const tracked = work.finally(() => this.activeWork.delete(tracked)); this.activeWork.add(tracked); return tracked as Promise<T>; }
  async shutdown(deadlineMs = this.shutdownDeadlineMs): Promise<void> { if (this.state === "stopped") return; this.state = "draining"; this.listening = false; const close = new Promise<void>((resolveClose) => this.server.close(() => resolveClose())); const bounded = Promise.allSettled([...this.activeWork]).then(() => undefined); await Promise.race([Promise.all([close, bounded]), new Promise<void>((resolveDeadline) => setTimeout(resolveDeadline, deadlineMs))]); this.activeWork.clear(); this.database.close(); this.state = "stopped"; }
  address(): { host: string; port: number } { const address = this.server.address(); if (!address || typeof address === "string") throw new Error("server is not listening"); return { host: address.address, port: address.port }; }
  private async handle(request: IncomingMessage, response: ServerResponse): Promise<void> { const path = requestPath(request); if (path === "/health/live") return json(response, 200, { status: "live", profile: this.config.profile }); if (path === "/health/ready") return json(response, this.health.status === "ready" ? 200 : 503, this.health); if (path === "/health/degraded") return json(response, this.health.status === "degraded" ? 503 : 200, this.health); if (path === "/health") return json(response, this.health.status === "ready" ? 200 : 503, this.health); if (path === "/api/interactions" && request.method === "POST") { if (this.health.status !== "ready") return json(response, 503, { code: "server_draining", message: "server is not accepting new interactions" }); return json(response, 202, { code: "accepted", message: "interaction admitted to bounded runtime" }); } if (path.startsWith("/api/admin/v1/")) { if (this.config.profile !== "test" || this.config.authority.authentication !== "fixture") return json(response, 503, { code: "admin_unavailable", message: "fixture administration is unavailable" }); const origin = originFor(request); const context = fixtureContext(request, origin); if (!context) return json(response, 401, { code: "authentication_required", message: "authentication required" }); const body = request.method === "GET" ? {} : await readBody(request); const result = this.admin.handle(request.method ?? "GET", path, context.principalId, body); return json(response, result.status, result.body); } if (path.startsWith("/api/authority/v1/")) { if (this.config.profile !== "test" || this.config.authority.authentication !== "fixture") return json(response, 503, { code: "authority_unavailable", message: "authenticated authority is unavailable" }); const origin = originFor(request); const body = request.method === "GET" ? {} : await readBody(request); const result = authorityApi(request.method ?? "GET", path, fixtureContext(request, origin), origin, body); const { status, ...bodyResult } = result; return json(response, status, bodyResult); } if (path === "/control" || path === "/control/") return this.serveUi(response, "index.html", "text/html; charset=utf-8"); if (path.startsWith("/control/")) return this.serveUi(response, path.slice("/control/".length), undefined); return json(response, 404, { code: "not_found", message: "not found" }); }
  private async handleRuntime(request: IncomingMessage, response: ServerResponse): Promise<void> { if (this.health.status !== "ready") return json(response, 503, { code: "server_draining", message: "runtime is not accepting messages" }); const origin = originFor(request); const context = fixtureContext(request, origin); if (!context) return json(response, 401, { code: "authentication_required", message: "authentication required" }); const body = await readBody(request); if (!body || typeof body !== "object" || Array.isArray(body)) return json(response, 422, { code: "invalid_request", message: "message body must be an object" }); const disconnected = new AbortController(); request.once("close", () => disconnected.abort()); await streamMessage(response, this.providers.inference, body as Record<string, unknown>, context.sessionId, disconnected.signal); }
  private async serveUi(response: ServerResponse, relativePath: string, contentType: string | undefined): Promise<void> { if (!/^[A-Za-z0-9_.-]+$/.test(relativePath)) return json(response, 404, { code: "not_found", message: "not found" }); try { const body = await readFile(resolve(this.controlUiDirectory, relativePath), "utf8"); const type = contentType ?? (relativePath.endsWith(".css") ? "text/css; charset=utf-8" : relativePath.endsWith(".js") ? "text/javascript; charset=utf-8" : "application/octet-stream"); return text(response, 200, type, body); } catch { return json(response, 404, { code: "not_found", message: "not found" }); } }
}
export const createLifestreamServer = (options: ServerOptions): LifestreamServer => new LifestreamServer(options);
if (process.argv[1] === fileURLToPath(import.meta.url)) { const profile = process.env.LIFESTREAM_PROFILE === "local-dev" ? "local-dev" : "test"; const app = createLifestreamServer({ config: loadProfile(profile), port: Number(process.env.PORT ?? 3000) }); await app.start(); process.once("SIGTERM", () => { void app.shutdown().then(() => process.exit(0)); }); process.once("SIGINT", () => { void app.shutdown().then(() => process.exit(0)); }); console.log(`Lifestream server listening on http://${app.host}:${app.address().port}/control/`); }
