import { randomUUID } from "node:crypto";
import { applyProposal, guardDerivedProposal, rejectInsightProposal } from "@lifestream/runtime/dreaming/apply";
import { validateInsightProposal } from "@lifestream/runtime/dreaming/proposal-validator";
import { hasRetainedRecordConflict, type RelationshipRecord } from "./relationship-records.ts";
export type RelationshipFeedback = { feedbackId: string; targetId: string; targetRevision: number; kind: "reaffirmation"|"correction"|"helpfulness"|"style"|"salience"; attributedBy: string; sourceFamily?: string; value?: string; affects: "evidence"|"communication"|"salience"; independentSupport: false; createdAt: string; reversedAt?: string };
export type InsightSource = { relationshipId: string; revision: number; candidates: RelationshipRecord[]; feedback?: RelationshipFeedback[] };
export type RelationshipInsight = { insightId: string; lens: "evidenceQuality"|"communicationFit"|"contextUse"|"structureCompression"|"trainingOpportunity"; observation: string; supportEvidenceIds: string[]; counterEvidenceIds: string[]; relationshipScope: string; uncertainty: string; intervention: string; benefit: string; cost: string; risk: string; validationScenario: string; inverse: string; status: "proposed"|"rejected"|"accepted"|"reversed"; createdAt: string; sourceRefs: string[]; sourceRevision: number; basisActiveConfigurationId: string|null; proposedControls?: {verbosity:number}; configurationId?: string; reversalConfigurationId?: string; revision: number };
export type InsightJob = { jobId: string; revision: number; status: "queued"|"completed"|"cancelled"|"failed"; sourceRefs: string[]; sourceRevision: number; basisActiveConfigurationId: string|null; createdAt: string; completedAt?: string; failure?: string; limits: {records:256;feedback:256;proposals:5;providerCalls:0;durationMs:2000}; elapsedMs?: number };
export const insightRefs = (source: InsightSource): string[] => [...source.candidates.filter(r=>r.status!=="forgotten").map(r=>`record:${r.candidateId}:${r.revision}`),...(source.feedback??[]).map(f=>`feedback:${f.feedbackId}:${f.reversedAt??"current"}`)].sort();
export function analyzeRelationship(source: InsightSource, basisActiveConfigurationId: string|null): RelationshipInsight[] {
 if(source.candidates.length>256||(source.feedback?.length??0)>256)throw new Error("Insight input capacity exceeded");
 const visible=source.candidates.filter(r=>r.status!=="forgotten"),approved=visible.filter(r=>r.status==="approved"),families=new Set(approved.flatMap(r=>r.sourceFamilies??[r.sourceFamily])),contrary=new Set(approved.flatMap(r=>[...(r.conflicts??[]).filter(c=>c.status==="retained").map(c=>c.recordId),...(r.builder?.conflicts??[])])),conflicted=approved.filter(hasRetainedRecordConflict),uncertain=approved.filter(r=>r.uncertainty==="high"||r.evidenceBasis==="modelInference"),suppressed=approved.filter(r=>r.suppressed||r.approvedUse?.personalization===false||r.approvedUse?.mention===false||r.audience==="ownerOnly"),feedback=(source.feedback??[]).filter(f=>!f.reversedAt&&visible.some(r=>r.candidateId===f.targetId&&r.revision===f.targetRevision)),styles=feedback.filter(f=>f.kind==="style"&&["preferBrief","preferDetailed"].includes(f.value??"")),latest=styles.at(-1),styleConflict=new Set(styles.map(f=>f.value)).size>1,groups=new Map<string,RelationshipRecord[]>();
 for(const record of approved){const key=record.content.trim().toLowerCase().replace(/\s+/gu," ");groups.set(key,[...(groups.get(key)??[]),record]);}
 const duplicates=[...groups.values()].filter(g=>g.length>1),duplicateIds=duplicates.flatMap(g=>g.map(r=>r.candidateId)),corrections=approved.filter(r=>r.contextUse==="correction"),support=[...new Map(approved.map(r=>[r.sourceFamily,r.candidateId])).values()],refs=insightRefs(source),common={relationshipScope:source.relationshipId,sourceRevision:source.revision,sourceRefs:refs,basisActiveConfigurationId,revision:1,status:"proposed" as const,createdAt:new Date().toISOString(),inverse:"Reject or reverse this proposal. Any configuration change remains an explicitly activated draft; restore prior settings through normal rollback.",uncertainty:"Attributed records are not independent factual verification. No psychological or learned-quality score is inferred."};
 const findings: Omit<RelationshipInsight,keyof typeof common|"insightId">[]=[
 {lens:"evidenceQuality",observation:`${approved.length} approved records across ${families.size} attributed families; ${conflicted.length} records retain contradictions; ${uncertain.length} have high uncertainty or an inference basis. ${Math.max(0,approved.length-families.size)} records share an attributed family.`,supportEvidenceIds:support,counterEvidenceIds:[...contrary],intervention:conflicted.length?"Review linked contradictions; retain both or explicitly correct/resolve them in Records.":"Review uncertain sources before treating them as facts; correlated repetition adds no independent support.",benefit:"Preserve unresolved evidence and source attribution.",cost:"Manual source review.",risk:"Authorship or repeated statements may be mistaken for verification.",validationScenario:"Compare duplicate statements without contradiction, then retain an explicit contrary pair."},
 {lens:"communicationFit",observation:`${feedback.filter(f=>f.affects==="communication").length} current attributed communication feedback items; ${styles.length} explicit brevity/detail preferences. ${styleConflict?"Preferences conflict; no automatic recommendation is available.":latest?`Latest explicit preference: ${latest.value}.`:"Insufficient evidence to recommend a communication change."}`,supportEvidenceIds:styles.map(f=>f.feedbackId),counterEvidenceIds:styleConflict?styles.map(f=>f.feedbackId):[],intervention:latest&&!styleConflict?"Prepare a named verbosity draft for comparison. Review and activate separately.":"Collect explicit scoped style feedback; do not infer preference from silence or engagement.",benefit:"Test the declared communication preference.",cost:"Requires a separate comparison and activation.",risk:"Subjective feedback does not establish factual correctness.",validationScenario:"Compare the same ordinary request before and after explicit activation; current requests retain priority.",...(latest&&!styleConflict?{proposedControls:{verbosity:latest.value==="preferBrief"?0:1}}:{})},
 {lens:"contextUse",observation:`${suppressed.length} approved records are restricted or suppressed; ${conflicted.length} are withheld for contradictions. No retrieval-frequency history is available, so underuse/overuse cannot be inferred.`,supportEvidenceIds:suppressed.map(r=>r.candidateId),counterEvidenceIds:[],intervention:"Inspect one actual request's selections and omissions before changing salience or use scope.",benefit:"Explain eligibility instead of treating recall as reinforcement.",cost:"One explicit runtime inspection.",risk:"Inclusion does not prove response causation or personal importance.",validationScenario:"Inspect a relevant request and an unrelated one; compare omissions without increasing support."},
 {lens:"structureCompression",observation:`${duplicates.length} exact normalized duplicate groups contain ${duplicateIds.length} records; ${corrections.length} approved direct corrections must remain separately recoverable.`,supportEvidenceIds:duplicateIds,counterEvidenceIds:[...contrary],intervention:duplicates.length?"Review duplicate groups for compatible merge; preserve all provenance and contradictions.":"No exact duplicate compression is supported by this snapshot. Preserve correction and contradiction links.",benefit:"Reduce duplicated context when supported.",cost:"Explicit record merge review; no automatic summary rewrite.",risk:"Loss of correction or contrary-source detail.",validationScenario:"Use a Lab representation comparison with linked corrections and a retained contradiction."},
 {lens:"trainingOpportunity",observation:`${styles.length} explicit style examples and ${families.size} attributed families are available; no purpose-specific training consent or separated dataset is established by this analysis.`,supportEvidenceIds:styles.map(f=>f.feedbackId),counterEvidenceIds:[],intervention:"Review a prompt/example comparison first. Any training-opportunity intake requires separate purpose consent, lineage and held-out dataset validation.",benefit:"Assess whether a simpler context intervention is sufficient.",cost:"Readiness review only; no training job or artifact activation.",risk:"Correlated examples and missing consent make training ineligible.",validationScenario:"Reject a readiness request without purpose consent and source-separated validation/test splits."}
 ];
 return findings.map(f=>{const result={...common,...f,insightId:randomUUID()};validateInsightProposal({...result,id:result.insightId,kind:"insight"});return result;});
}
export function reviewInsight(insight: RelationshipInsight, source: InsightSource, activeId: string|null, decision: "accepted"|"rejected"|"reversed", expectedRevision: unknown): RelationshipInsight {
 if(!Number.isInteger(expectedRevision)||insight.revision!==expectedRevision)throw new Error("Insight revision changed; refresh review");
 if(decision==="reversed") {if(insight.status!=="accepted")throw new Error("Only an accepted insight can be reversed");return {...insight,status:"reversed",revision:insight.revision+1};}
 if(insight.status!=="proposed")throw new Error("Insight already reviewed");
 if(decision==="rejected")return {...rejectInsightProposal(insight,"proposed"),revision:insight.revision+1};
 applyProposal({id:insight.insightId,kind:"insight",evidenceIds:insight.supportEvidenceIds},insight.sourceRevision,source.revision);
 guardDerivedProposal(insight,{sourceRefs:insight.sourceRefs,currentRefs:insightRefs(source),status:insight.basisActiveConfigurationId===activeId?"eligible":"quarantined"});
 return {...insight,status:"accepted",revision:insight.revision+1};
}
