import {randomUUID} from 'node:crypto';
import {TrainingRegistry,trainingContentDigest,type DatasetAuthority,type TrainingConsent,type TrainingRegistryState,type AdapterManifest,type AdapterRouteRequest} from '@lifestream/runtime/training';
import {hasRetainedRecordConflict,type RelationshipRecord} from './relationship-records.ts';
export type RelationshipReadiness={schemaVersion:'2.0.0';consents:TrainingConsent[];registry:TrainingRegistryState;comparisons?:{comparisonId:string;datasetDigest:string;manifestKinds:string[];checks:{name:string;route:string}[];learnedQuality:'notEvaluated'}[]};
type Owner={userId:string;assistantId:string;relationshipId:string;revision:number;candidates:RelationshipRecord[];readiness?:RelationshipReadiness};
export const readinessLimitations=['Synthetic contract readiness only: no training, adapter load or learned-quality evidence.','The selected development backend has no approved concurrent private-adapter serving contract. Ordinary inference uses its untouched base. LS-S082 remains a separate gate.','Canonical editable records remain authoritative. Dataset deletion does not establish weight unlearning; external exports and backups cannot be recalled.'];
export function readinessState(owner:Owner):RelationshipReadiness{return structuredClone(owner.readiness??{schemaVersion:'2.0.0',consents:[],registry:new TrainingRegistry().snapshot()});}
export function readinessAuthority(owner:Owner,state=readinessState(owner)):DatasetAuthority{return {scope:{subjectId:owner.userId,assistantId:owner.assistantId,relationshipId:owner.relationshipId},consents:state.consents,sources:owner.candidates.map(r=>({id:r.candidateId,revision:String(r.revision),family:r.sourceFamily,contentDigest:trainingContentDigest(r.content),eligible:r.status==='approved'&&r.trainingExcluded===false&&!hasRetainedRecordConflict(r)&&r.sensitivity!=='sensitive'}))};}
export function readinessView(owner:Owner){const state=readinessState(owner);return {schemaVersion:state.schemaVersion,relationshipRevision:owner.revision,consents:state.consents,registry:state.registry,comparisons:state.comparisons??[],records:owner.candidates.filter(r=>r.status==='approved').map(r=>({id:r.candidateId,revision:r.revision,sourceFamily:r.sourceFamily,content:r.content,trainingExcluded:r.trainingExcluded!==false})),runtimeSupported:false,limits:{sources:256,datasets:16,artifacts:64,consents:64},limitations:readinessLimitations};}
export function applyReadiness(owner:Owner,action:string,raw:Record<string,unknown>):{owner:Owner;result:Record<string,unknown>}{
 if(raw.expectedRevision!==owner.revision)throw new Error('Relationship revision changed; refresh readiness');
 const next=structuredClone(owner),state=readinessState(next);next.readiness=state;const registry=new TrainingRegistry(state.registry);let result:Record<string,unknown>={};
 if(action==='consent'){
  if(raw.purpose!=='trainingDataset'||raw.syntheticOnly!==true||raw.approve!==true||!Array.isArray(raw.sourceRefs)||!raw.sourceRefs.length||raw.sourceRefs.length>256||state.consents.length>=64)throw new Error('Explicit synthetic trainingDataset consent and bounded source revisions are required');
  const refs=raw.sourceRefs as unknown[];if(new Set(refs).size!==refs.length)throw new Error('Duplicate consent source');
  const selected=refs.map(ref=>next.candidates.find(r=>`${r.candidateId}:${r.revision}`===ref));if(selected.some(r=>!r||r.status!=='approved'||r.sensitivity==='sensitive'||hasRetainedRecordConflict(r)||r.history?.some(h=>h.operation==='exclude-training')))throw new Error('Current approved ordinary sources without explicit training prohibition are required');
  for(const r of selected){if(!r)continue;if((r.history?.length??0)>=256)throw new Error('Source history capacity reached');r.trainingExcluded=false;r.revision++;r.history=[...(r.history??[]),{operation:'grant-training-dataset-consent',actor:owner.userId,at:new Date().toISOString(),revision:r.revision,relatedIds:[]}];}
  const consent:TrainingConsent={...readinessAuthority(next,state).scope,consentId:randomUUID(),revision:1,sourceRefs:selected.map(r=>`${r!.candidateId}:${r!.revision}`),purpose:'trainingDataset',status:'approved',grantedBy:owner.userId,createdAt:new Date().toISOString()};state.consents.push(consent);result={consent,trainingExecuted:false};
 }else if(action==='revoke-consent'){
  const consent=state.consents.find(c=>c.consentId===raw.consentId);if(!consent||consent.revision!==raw.consentRevision||consent.status!=='approved')throw new Error('Current approved consent required');const ref=`${consent.consentId}:${consent.revision}`;consent.status='revoked';consent.revision++;registry.invalidate([ref]);result={consent,weightsUnlearned:false};
 }else if(action==='dataset'){
  if(raw.syntheticOnly!==true||!Array.isArray(raw.members)||raw.members.length<3||raw.members.length>256)throw new Error('Select three or more synthetic records and explicit independent splits');
  const authority=readinessAuthority(next,state),records=raw.members.map(member=>{const m=member as Record<string,unknown>,r=next.candidates.find(r=>r.candidateId===m.recordId&&r.revision===m.revision);if(!r)throw new Error('Source revision unavailable');const sourceRef=`${r.candidateId}:${r.revision}`,consent=state.consents.find(c=>c.status==='approved'&&c.sourceRefs.includes(sourceRef));if(!consent)throw new Error('Separate current source-bound dataset consent required');const consentRef=`${consent.consentId}:${consent.revision}`;return {...authority.scope,recordId:randomUUID(),sourceId:r.candidateId,sourceRevision:String(r.revision),sourceFamily:r.sourceFamily,content:r.content,contentDigest:trainingContentDigest(r.content),consent:'approved' as const,consentRef,purpose:'training' as const,sensitivity:'ordinary' as const,split:m.split as 'train'|'validation'|'test',transformed:'none' as const,dependencyIds:[sourceRef,consentRef,...(r.derivedFrom??[]),...(r.sourceFamilies??[]).map(f=>`family:${f}`)]};});
  result={dataset:registry.addDataset({schemaVersion:'2.0.0',datasetId:randomUUID(),revision:1,records,exclusions:['Secrets, sensitive and nonconsenting third-party content excluded; synthetic-only operator attestation required.'],syntheticGenerator:'explicit-synthetic-relationship-records:1',createdAt:new Date().toISOString(),exportPolicy:'fixture-only'},authority)};
 }else if(action==='register-fixture'){
  if(raw.syntheticOnly!==true||!['behavioral','concreteFactHypothesis'].includes(String(raw.kind)))throw new Error('Explicit synthetic behavioral or concrete-fact hypothesis fixture required');const dataset=registry.exportDataset(String(raw.datasetId),readinessAuthority(next,state));
  const requirements=raw.kind==='concreteFactHypothesis'?['exact-and-paraphrased-recall','current-corrections-and-conflicts','unrelated-task-regressions','hallucinated-extensions','attribution-limitations','cross-subject-and-audience-leakage','retirement-and-revocation']:['style-fit','current-request-priority','unrelated-task-regressions','scope-isolation','retirement-and-revocation'];
  const manifest:AdapterManifest={schemaVersion:'2.0.0',artifactId:randomUUID(),artifactRevision:'1',kind:raw.kind as AdapterManifest['kind'],baseModel:'fixture-untouched-base',baseModelRevision:'1',tokenizer:'fixture-tokenizer:1',chatTemplate:'fixture-template:1',runtime:'fixture-adapter-simulator:1',quantization:'none',datasetDigest:dataset.digest,datasetLineage:[...new Set(dataset.records.flatMap(r=>r.dependencyIds))],trainingSettings:{executed:false,syntheticOnly:true},toolVersions:{registry:'2.0.0'},resourceEvidence:['contract-fixture:no-model-or-gpu-allocation'],evaluations:requirements.map(r=>`required-not-executed:${r}`),approvedSubjectId:owner.userId,approvedAssistantId:owner.assistantId,approvedAudience:'private',activationDependency:`explicit-fixture-review:${dataset.datasetId}`,revocationDependency:`dataset-currency:${dataset.datasetId}`,fallback:{baseModel:'fixture-untouched-base',baseModelRevision:'1',untouched:true,merged:false},status:'candidate'};
  result={artifact:registry.register(manifest,readinessAuthority(next,state)),comparison:{simplerInterventions:['approved-context','examples-and-prompt','record-and-convention-representations'],adapterKind:manifest.kind,requiredEvaluations:requirements,learnedQuality:'notEvaluated',promotion:'Explicit fixture review only; real training and serving require LS-S082.'}};
 }else if(action==='compare-fixtures'){
  if(raw.syntheticOnly!==true||(state.comparisons?.length??0)>=16)throw new Error('Bounded synthetic contract comparison required');
  const dataset=registry.exportDataset(String(raw.datasetId),readinessAuthority(next,state)),artifacts=registry.snapshot().artifacts.filter(m=>m.datasetDigest===dataset.digest&&m.status==='approved');
  if(!['behavioral','concreteFactHypothesis'].every(kind=>artifacts.some(m=>m.kind===kind)))throw new Error('Review both behavioral and concrete-fact fixture manifests before comparing');
  const checks=[{name:'Ordinary prompt/context path retains untouched base',route:'base'}];
  for(const m of artifacts){for(const audience of ['private','unknown'] as const){const route=routeReadiness(next,m.artifactId,m.artifactRevision,audience,true);checks.push({name:`${m.kind}: ${audience} contract route`,route:route.route});}checks.push({name:`${m.kind}: selected runtime remains unsupported`,route:routeReadiness(next,m.artifactId,m.artifactRevision,'private',false).route});}
  const comparison={comparisonId:randomUUID(),datasetDigest:dataset.digest,manifestKinds:artifacts.map(m=>m.kind),checks,learnedQuality:'notEvaluated' as const};state.comparisons=[...(state.comparisons??[]),comparison];result={comparison,outputsGenerated:false,promotion:'Contract review cannot promote or load weights; use executed Relationship Lab for approved context/representation candidates.'};
 }else if(action==='approve-fixture'){
  if(raw.syntheticOnly!==true)throw new Error('Synthetic fixture review required');result={artifact:registry.approve(String(raw.artifactId),String(raw.artifactRevision),Number(raw.registryRevision),readinessAuthority(next,state)),liveActivation:false};
 }else throw new Error('Unsupported readiness operation');
 state.registry=registry.snapshot();next.revision++;return {owner:next,result:{...result,relationshipRevision:next.revision,limitations:readinessLimitations}};
}
export function routeReadiness(owner:Owner,id:string,artifactRevision:string,audience:'private'|'unknown',simulate=false){
 const registry=new TrainingRegistry(readinessState(owner).registry),m=registry.snapshot().artifacts.find(m=>m.artifactId===id&&m.artifactRevision===artifactRevision);
 const request:AdapterRouteRequest={subjectId:owner.userId,assistantId:owner.assistantId,audience,artifactRevision,baseModel:simulate?'fixture-untouched-base':'selected-development-base',baseModelRevision:'1',tokenizer:'fixture-tokenizer:1',chatTemplate:'fixture-template:1',runtime:'fixture-adapter-simulator:1',quantization:'none',datasetDigest:m?.datasetDigest??'',activeDependencies:m?[...m.datasetLineage,m.activationDependency,m.revocationDependency]:[],runtimeSupported:simulate};
 return {...registry.route(id,request,readinessAuthority(owner)),simulation:simulate,trainingExecuted:false,weightsLoaded:false};
}
export function exportReadiness(owner:Owner,id:string){return new TrainingRegistry(readinessState(owner).registry).exportDataset(id,readinessAuthority(owner));}
