import {createHash,randomUUID} from "node:crypto";
import {createLabExperiment,runLabComparison,type LabExperiment,type LabComparison,type LabScenarioResult,type LabRepresentation} from "@lifestream/runtime/replay";
import {compileRelationshipContext,formatPreparedRelationshipContext,RELATIONSHIP_COMPILER_REVISION,type RelationshipContextRecord,relationshipControlDefaults} from "@lifestream/runtime/context";
import {buildCanonicalPrompt,type AssistantPersonaProjection,type RuntimeSelfContext} from "@lifestream/runtime/inference/prompt";
import type {InferenceProvider} from "@lifestream/runtime/inference";
export type LabScenario={id:string;prompt:string;sourceFamily:string;split:"comparison"|"heldOut";forbiddenTerms:string[]};
export type LabSnapshot={boundary:string;records:RelationshipContextRecord[];profileRevision:string;relationshipRevision:string;configurationRevision:string;configurationId:string|null;controls:Record<string,number>;representation:LabRepresentation;profileProjection?:AssistantPersonaProjection;selfContext:RuntimeSelfContext;assistantId:string;relationshipId:string;subjectId:string};
export type LabRuntime={provider:InferenceProvider;identity:{implementation:string;model:string;revision:string;configurationDigest:string;fixture:boolean}};
export type RelationshipLab=LabExperiment&{revision:number;sourceSnapshot:LabSnapshot;scenarios:LabScenario[];candidateControls:Record<string,number>;candidateRepresentation:LabRepresentation;criteria:LabExperiment["criteria"];consent:{actor:string;purpose:"isolatedEvaluation";dataScope:"synthetic";transmissionApproved:true;at:string};runtime:LabRuntime["identity"];comparison?:LabComparison;heldOut?:LabComparison;configurationId?:string;promotion?:{kind:"relationshipConfiguration";representation:LabRepresentation;controlKeys:string[];promptOrWeightsChanged:false};failure?:string};
const digest=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
const bounded=(value:unknown,max:number):value is string=>typeof value==='string'&&!!value.trim()&&value.length<=max;
export function prepareRelationshipLab(snapshot:LabSnapshot,raw:Record<string,unknown>,runtime:LabRuntime['identity']):RelationshipLab {
 if(raw.syntheticOnly!==true||raw.transmissionApproved!==true)throw new Error('Explicit synthetic-data evaluation and selected-provider transmission consent is required');
 if(Object.keys(raw).some(k=>!['syntheticOnly','transmissionApproved','scenarios','criteria','repeatedRuns','candidateControls','candidateRepresentation'].includes(k)))throw new Error('Unsupported Lab input; provider routes and external effects cannot be selected');
 if(!Array.isArray(raw.scenarios)||raw.scenarios.length<2||raw.scenarios.length>4)throw new Error('Declare two to four bounded source-separated scenarios');
 const scenarios:LabScenario[]=raw.scenarios.map(value=>{const row=value as Record<string,unknown>;if(!row||!bounded(row.id,100)||!bounded(row.prompt,1000)||!bounded(row.sourceFamily,150)||!['comparison','heldOut'].includes(String(row.split))||!Array.isArray(row.forbiddenTerms)||row.forbiddenTerms.length>8||row.forbiddenTerms.some(x=>!bounded(x,100)))throw new Error('Invalid scenario identity, prompt, family, split or forbidden terms');return {id:row.id,prompt:row.prompt,sourceFamily:row.sourceFamily,split:row.split as LabScenario['split'],forbiddenTerms:row.forbiddenTerms as string[]};});
 if(new Set(scenarios.map(s=>s.id)).size!==scenarios.length||!scenarios.some(s=>s.split==='comparison')||!scenarios.some(s=>s.split==='heldOut'))throw new Error('Unique comparison and held-out scenarios are required');
 for(const held of scenarios.filter(s=>s.split==='heldOut'))if(scenarios.some(s=>s.split==='comparison'&&(s.sourceFamily===held.sourceFamily||s.prompt.trim().toLowerCase()===held.prompt.trim().toLowerCase()))||snapshot.records.some(r=>r.sourceFamily===held.sourceFamily))throw new Error('Held-out source/prompt overlaps comparison or prepared records');
 if(!Array.isArray(raw.criteria)||raw.criteria.length!==2||!raw.criteria.includes('nonempty')||!raw.criteria.includes('noForbiddenTerms'))throw new Error('Declare nonempty and noForbiddenTerms criteria before running; subjective fit remains Human review');
 if(!Number.isInteger(raw.repeatedRuns)||(raw.repeatedRuns as number)<2||(raw.repeatedRuns as number)>3||scenarios.length*6*(raw.repeatedRuns as number)>48)throw new Error('Two to three repeats, within 48 total requests, are supported');
 const controls={...snapshot.controls},supplied=raw.candidateControls;if(!supplied||typeof supplied!=='object'||Array.isArray(supplied))throw new Error('Declare candidate controls');for(const [key,value]of Object.entries(supplied)){if(!(key in relationshipControlDefaults)||typeof value!=='number'||!Number.isFinite(value)||value<0||value>1)throw new Error('Unsupported candidate control');controls[key]=value;}
 if(!['recordOriented','conventionOriented'].includes(String(raw.candidateRepresentation)))throw new Error('Choose a supported candidate representation');
 const experimentId=randomUUID(),base=createLabExperiment({experimentId,sourceRelationshipId:snapshot.relationshipId,sourceConfigurationRevision:snapshot.configurationRevision,representations:['recordOriented','conventionOriented'],promptVariants:['ordinary-unpersonalized','approved-current','reviewed-candidate'],controlVariants:['current','candidate'],scenarioIds:scenarios.map(s=>s.id),heldOutScenarioIds:scenarios.filter(s=>s.split==='heldOut').map(s=>s.id),criteria:[{id:'nonempty',description:'Completed nonempty reply',weight:1},{id:'noForbiddenTerms',description:'No declared forbidden term in output',weight:1}],repeatedRuns:raw.repeatedRuns as number,datasetRef:`synthetic-scenarios:${digest(scenarios)}`,sourceSnapshotRef:`relationship-snapshot:${digest(snapshot)}`,providerRefs:[`isolated-inference:${runtime.implementation}:${runtime.revision}`],compilerVersion:RELATIONSHIP_COMPILER_REVISION,cacheNamespace:`lab-cache:${experimentId}`,grantNamespace:`lab-grants:${experimentId}`});
 return {...base,revision:1,sourceSnapshot:structuredClone(snapshot),scenarios,candidateControls:controls,candidateRepresentation:raw.candidateRepresentation as LabRepresentation,consent:{actor:snapshot.subjectId,purpose:'isolatedEvaluation',dataScope:'synthetic',transmissionApproved:true,at:new Date().toISOString()},runtime:structuredClone(runtime)};
}
export async function executeRelationshipLab(lab:RelationshipLab,runtime:LabRuntime,phase:'comparison'|'heldOut',signal:AbortSignal,current:()=>boolean,onResult:(result:LabScenarioResult)=>void):Promise<LabComparison>{
 if(digest(lab.runtime)!==digest(runtime.identity)||lab.compilerVersion!==RELATIONSHIP_COMPILER_REVISION)throw new Error('Pinned runtime or compiler changed');
 if(phase==='heldOut'&&lab.comparison?.status!=='completed')throw new Error('Complete the frozen comparison before held-out evaluation');
 signal=AbortSignal.any([signal,AbortSignal.timeout(120000)]);
 const snapshot=lab.sourceSnapshot,prior=phase==='comparison'?lab.comparison:lab.heldOut;
 return runLabComparison({...lab,status:prior?'partial':'prepared'},lab.scenarioIds,async(scenarioId,representation,variant,repeat)=>{
  if(!current())throw new Error('Lab source, consent or authorization changed');const scenario=lab.scenarios.find(s=>s.id===scenarioId)!,started=performance.now(),controls=variant==='candidate'?lab.candidateControls:snapshot.controls;
  const prepared=compileRelationshipContext({records:variant==='unpersonalized'?[]:snapshot.records,userInput:scenario.prompt,audienceScope:'authenticatedSession',profileRevision:snapshot.profileRevision,relationshipRevision:snapshot.relationshipRevision,configurationRevision:variant==='candidate'?`lab:${lab.experimentId}:candidate`:snapshot.configurationRevision,controls:variant==='unpersonalized'?relationshipControlDefaults:controls,representation});
  const request=buildCanonicalPrompt({assistantId:snapshot.assistantId,sessionId:`lab:${lab.experimentId}`,interactionId:`${lab.experimentId}:${phase}:${scenarioId}:${representation}:${variant}:${repeat}`,endpointId:null,userInput:scenario.prompt,preparedRelationshipContext:prepared,...(snapshot.profileProjection?{profileProjection:snapshot.profileProjection}:{}),runtimeSelfContext:snapshot.selfContext,capabilities:'No capabilities or effects are available in this isolated experiment.',conversation:'No prior conversation or historical effects are supplied.'});
  const timeout=AbortSignal.timeout(10000),combined=AbortSignal.any([signal,timeout]);let output='',done=false,firstTokenMs:number|undefined;
  const iterator=runtime.provider.generate(request,{signal:combined})[Symbol.asyncIterator]();let abortListener:()=>void=()=>{};
  const aborted=new Promise<never>((_resolve,reject)=>{abortListener=()=>reject(new Error("Lab inference cancelled or timed out"));combined.addEventListener('abort',abortListener,{once:true});if(combined.aborted)abortListener();});
  try { while(true){const next=await Promise.race([iterator.next(),aborted]);if(next.done)break;const chunk=next.value;
   if(combined.aborted||!current())throw new Error('Lab input invalidated or request cancelled');
   if(chunk.kind==='capabilityRequest')throw new Error('Lab capability request denied; zero dispatch');
   if(chunk.kind==='error')throw new Error(`Lab provider failed: ${chunk.error?.code??'unknown'}`);
   if(chunk.kind==='text'){firstTokenMs??=performance.now()-started;output+=chunk.text??'';if(Buffer.byteLength(output)>16384)throw new Error('Lab output byte limit exceeded');}
   if(chunk.kind==='done')done=true;
  }} finally {combined.removeEventListener('abort',abortListener);if(combined.aborted)void iterator.return?.().catch(()=>{});}

  if(!done||combined.aborted||!current())throw new Error('Lab output did not complete on current input');
  const evaluations=[{criterion:'nonempty',pass:!!output.trim()},{criterion:'noForbiddenTerms',pass:scenario.forbiddenTerms.every(term=>!output.toLowerCase().includes(term.toLowerCase()))}];
  return {output:{text:output,evaluations,subjectiveFit:'Human review pending',preparedContext:formatPreparedRelationshipContext(prepared),preparedBudget:prepared.budget,inputManifest:request.manifest,firstTokenMs:firstTokenMs??null,sourceRevisions:prepared.sourceRevisions,compilerRevision:prepared.compilerRevision,representationRevision:prepared.representationRevision,capabilityDispatches:0,liveMemoryWrites:0,speechDelivery:0},latencyMs:performance.now()-started,tokenCount:request.manifest.sections.reduce((n,s)=>n+s.tokenCount,0)};
 },{signal,phase,initialResults:prior?.results??[],onResult,maximumDurationMs:120000});
}
export function assertLabPromotion(lab:RelationshipLab,currentBoundary:string,actor:string,expectedRevision:unknown):void{
 if(lab.revision!==expectedRevision||lab.status!=='completed'||lab.comparison?.status!=='completed'||lab.heldOut?.status!=='completed')throw new Error('Both frozen comparison and held-out evaluation must complete before review');
 if(actor!==lab.consent.actor||lab.sourceSnapshot.boundary!==currentBoundary)throw new Error('Lab sources or consent changed');
 if([...lab.comparison.results,...lab.heldOut.results].some(r=>r.status==='failed'||!Array.isArray(r.output.evaluations)||(r.output.evaluations as {pass:boolean}[]).some(e=>!e.pass)))throw new Error('Declared deterministic criteria failed; candidate cannot be promoted');
}
