import {randomUUID} from 'node:crypto';
import {TrainingRegistry} from '@lifestream/runtime/training';
import {relationshipControlDefaults} from '@lifestream/runtime/context';
import type {Database,MemoryRepository,ProfileBuilderJob,ProfileCandidate} from '@lifestream/storage-sqlite';
import type {RelationshipRecord} from './relationship-records.ts';
import type {RelationshipReadiness} from './relationship-readiness.ts';
import type {RelationshipInsight,RelationshipFeedback,InsightJob} from './relationship-insights.ts';
import type {RelationshipLab} from './relationship-lab.ts';
import {RecoveryJournal,recoveryDigest,privacyActions,type PrivacyAction,type RecoveryIntent} from './recovery-journal.ts';
export type RecoveryReceipt={operationId:string;action:PrivacyAction;status:'completed'|'partial';artifacts:{owner:string;id:string;disposition:string}[];retryRequired:boolean;limitations:string[]};
export type RecoveryRelationship={deploymentId?:string;relationshipId:string;assistantId:string;userId:string;revision:number;status:'active'|'skipped';candidates:RelationshipRecord[];feedback?:RelationshipFeedback[];insights?:RelationshipInsight[];insightJob?:InsightJob;lab?:RelationshipLab;labHistory?:RelationshipLab[];readiness?:RelationshipReadiness;collectionStopped?:boolean;recoveryReceipts?:RecoveryReceipt[]};
export const recoveryLimitations=['External exports, provider-held data and backups are outside this owner-local erase; delete them separately.','Logical stored payload removal is verified; forensic filesystem erasure, weight unlearning and cross-provider atomic deletion are not claimed.','Tombstones must remain outside database backups. Missing or older safety currency withholds stored personalization until current safety evidence is restored.'];
const referenceMatches=(value:unknown,ids:Set<string>):boolean=>typeof value==='string'?[...ids].some(id=>value===id||value===`record:${id}`||value.startsWith(`${id}:`)||value.startsWith(`record:${id}:`)||value.startsWith(`user-profile:${id}:`)):Array.isArray(value)?value.some(v=>referenceMatches(v,ids)):!!value&&typeof value==='object'?Object.values(value).some(v=>referenceMatches(v,ids)):false;
export class RelationshipRecovery {
 readonly journal:RecoveryJournal;private indexedRevision=-1;private deniedIds=new Map<string,Set<string>>();private operations=new Map<string,string[]>();private profileIntents:RecoveryIntent[]=[];private db:Database;private memories:MemoryRepository;
 constructor(db:Database,memories:MemoryRepository,directory?:string){this.db=db;this.memories=memories;this.journal=new RecoveryJournal(db,directory);}
 private rows<T>(table:string,column='payload_json'):T[]{return (this.db.connection.prepare(`SELECT ${column} AS payload FROM ${table}`).all() as {payload:string}[]).map(r=>JSON.parse(r.payload) as T);}
 epoch():string{return `${this.journal.currency}:${this.journal.revision}`;}
 private index():void{if(this.indexedRevision===this.journal.revision)return;this.deniedIds.clear();this.operations.clear();this.profileIntents=[];for(const i of this.journal.snapshot().intents){if(i.profileIds.length&&!["prohibit-training","stop-collection"].includes(i.action))this.profileIntents.push(i);this.operations.set(i.relationshipId,[...(this.operations.get(i.relationshipId)??[]),i.operationId]);for(const purpose of ['processing','personalization','training'])if(['delete-source','forget-derived-information','revoke-processing'].includes(i.action)||purpose==='personalization'&&i.action==='stop-personalization'||purpose==='training'&&i.action==='prohibit-training'){const key=JSON.stringify([i.actor,purpose]),ids=this.deniedIds.get(key)??new Set<string>();for(const id of [...i.recordIds,...i.memoryIds,...i.profileIds])ids.add(id);this.deniedIds.set(key,ids);}}this.indexedRevision=this.journal.revision;}
 pending(relationship:RecoveryRelationship):boolean{this.index();const complete=(id:string)=>relationship.recoveryReceipts?.some(r=>r.operationId===id&&r.status==='completed');return (this.operations.get(relationship.relationshipId)??[]).some(id=>!complete(id))||this.profileIntents.some(i=>i.actor===relationship.userId&&!complete(i.operationId)&&[relationship.lab,...(relationship.labHistory??[])].some(l=>l?.sourceSnapshot?.records.some(r=>i.profileIds.some(id=>r.id.startsWith(`user-profile:${id}:`)))));}
 denied(actor:string,_relationshipId:string,id:string,purpose:'processing'|'personalization'|'training'='processing'):boolean{this.index();return this.journal.currency!=='current'||!!this.deniedIds.get(JSON.stringify([actor,purpose]))?.has(id);}
 referencesDenied(actor:string,value:unknown):boolean{this.index();return this.journal.currency!=='current'||referenceMatches(value,this.deniedIds.get(JSON.stringify([actor,'processing']))??new Set<string>());}
 view(relationship:RecoveryRelationship){return {currency:this.journal.currency,epoch:this.journal.snapshot().epoch,relationshipRevision:relationship.revision,actions:privacyActions,limits:{targets:256,nativeArchiveRecords:4096,journalBytes:8388608,receiptsPerRelationship:256},collectionStopped:!!relationship.collectionStopped,receipts:[...(relationship.recoveryReceipts??[]),...this.journal.snapshot().intents.filter(i=>i.relationshipId===relationship.relationshipId&&!relationship.recoveryReceipts?.some(r=>r.operationId===i.operationId&&r.status==='completed')).map(i=>({operationId:i.operationId,action:i.action,status:'partial',retryRequired:true,affectedUse:'withheld'}))],limitations:recoveryLimitations};}
 prepare(relationship:RecoveryRelationship,raw:Record<string,unknown>):RecoveryIntent{
  if(raw.expectedRevision!==relationship.revision||typeof raw.idempotencyKey!=='string'||!raw.idempotencyKey||raw.idempotencyKey.length>200||!privacyActions.includes(raw.action as PrivacyAction))throw new Error('Current relationship revision, bounded idempotency identity and distinct privacy action required');
  if((relationship.recoveryReceipts?.length??0)>=256)throw new Error('Relationship recovery receipt capacity reached');
  if(Number((this.db.connection.prepare('SELECT COUNT(*) AS n FROM memories WHERE assistant_id=?').get(relationship.assistantId) as {n:number}).n)>4096)throw new Error('Dependency inventory exceeds the bounded 4096-record native archive limit; request was not admitted');
  const action=raw.action as PrivacyAction,targets=raw.targets;if(!Array.isArray(targets)||targets.length>256||action!=='stop-collection'&&!targets.length||action==='stop-collection'&&targets.length>0)throw new Error('Select bounded current records, memories or User Profiles');
  const recordIds=new Set<string>(),memoryIds=new Set<string>(),profileIds=new Set<string>(),sourceDigests=new Set<string>(),contentDigests=new Set<string>();
  for(const entry of targets){const target=entry as {kind:string;id:string;revision:number};if(!target||typeof target.id!=='string'||!Number.isInteger(target.revision))throw new Error('Invalid target revision');
   if(target.kind==='record'){const r=relationship.candidates.find(r=>r.candidateId===target.id&&r.revision===target.revision);if(!r)throw new Error('Record target changed or unavailable');recordIds.add(r.candidateId);}
   else if(target.kind==='memory'){const m=this.memories.get(relationship.assistantId,target.id);if(!m||m.provenance.actor!==relationship.userId||m.lifecycle.revision!==target.revision)throw new Error('Memory target changed or not owned');memoryIds.add(m.id);}
   else if(target.kind==='userProfile'){const p=this.rows<{profileId:string;userId:string;revision:number;declarations:{value:unknown}[]}>('user_profile_revisions').find(p=>p.profileId===target.id&&p.userId===relationship.userId&&p.revision===target.revision);if(!p)throw new Error('User Profile target changed or not owned');profileIds.add(p.profileId);for(const d of p.declarations??[])contentDigests.add(recoveryDigest(String(d.value)));}
   else throw new Error('Unsupported target owner');
  }
  if(profileIds.size){const profiles=this.rows<{profileId:string;userId:string;sourceRefs:string[];declarations:{value:unknown}[]}>('user_profile_revisions'),sourceRefs=new Set(profiles.filter(p=>profileIds.has(p.profileId)).flatMap(p=>p.sourceRefs));for(const p of profiles)if(p.userId===relationship.userId&&p.sourceRefs.some(r=>sourceRefs.has(r))){profileIds.add(p.profileId);for(const d of p.declarations)contentDigests.add(recoveryDigest(String(d.value)));}}
  const rootRecordIds=[...recordIds],rootMemoryIds=[...memoryIds],rootProfileIds=[...profileIds];
  const collect=(r:RelationshipRecord)=>{if(r.builder?.sourceDigest)sourceDigests.add(r.builder.sourceDigest);if(r.content)contentDigests.add(recoveryDigest(r.content));if(r.builder?.value)contentDigests.add(recoveryDigest(r.builder.value));};
  relationship.candidates.filter(r=>recordIds.has(r.candidateId)).forEach(collect);
  if(action!=='stop-collection')for(let n=0;n<256;n++){let changed=false;for(const r of relationship.candidates)if(!recordIds.has(r.candidateId)&&((r.derivedFrom??[]).some(id=>recordIds.has(id))||!!r.builder&&sourceDigests.has(r.builder.sourceDigest))){recordIds.add(r.candidateId);collect(r);changed=true;}if(!changed)break;}
  const refs=new Set([...recordIds,...memoryIds,...profileIds]);for(let n=0;n<256;n++){let changed=false;for(const m of this.memories.list(relationship.assistantId))if(m.provenance.actor===relationship.userId&&!memoryIds.has(m.id)&&referenceMatches(m.provenance,refs)){memoryIds.add(m.id);refs.add(m.id);changed=true;}if(!changed)break;}
  for(const id of memoryIds){const m=this.memories.get(relationship.assistantId,id);if(m?.content)contentDigests.add(recoveryDigest(m.content));for(const e of this.memories.history(relationship.assistantId,id))if(typeof e.payload.proposedContent==='string')contentDigests.add(recoveryDigest(e.payload.proposedContent));}
  for(const p of this.rows<{profileId:string;userId:string;sourceRefs:string[];declarations:{value:unknown}[]}>('user_profile_revisions'))if(p.userId===relationship.userId&&referenceMatches(p.sourceRefs,refs)){profileIds.add(p.profileId);for(const d of p.declarations)contentDigests.add(recoveryDigest(String(d.value)));}
  return {operationId:randomUUID(),idempotencyKey:raw.idempotencyKey,requestDigest:recoveryDigest(JSON.stringify({action,expectedRevision:raw.expectedRevision,targets:raw.targets})),rootRecordIds,rootMemoryIds,rootProfileIds,actor:relationship.userId,assistantId:relationship.assistantId,relationshipId:relationship.relationshipId,action,recordIds:[...recordIds],memoryIds:[...memoryIds],profileIds:[...profileIds],sourceDigests:[...sourceDigests],contentDigests:[...contentDigests],createdAt:new Date().toISOString()};
 }
 recover():void{if(this.journal.currency!=='current')return;let complete=true;for(const intent of this.journal.snapshot().intents)try{this.apply(intent);}catch{complete=false;}if(complete)this.db.connection.prepare('UPDATE relationship_recovery_currency SET epoch=? WHERE singleton=1').run(this.journal.snapshot().epoch);}
 apply(intent:RecoveryIntent,propagateProfiles=true):RecoveryReceipt{
  const relationship=this.rows<RecoveryRelationship>('assistant_relationships').find(r=>r.relationshipId===intent.relationshipId&&r.userId===intent.actor&&r.assistantId===intent.assistantId)??{relationshipId:intent.relationshipId,userId:intent.actor,assistantId:intent.assistantId,revision:0,status:'active' as const,candidates:[]};
  const propagate=(receipt:RecoveryReceipt)=>{if(!propagateProfiles||!intent.profileIds.length||['prohibit-training','stop-collection'].includes(intent.action))return;for(const other of this.rows<RecoveryRelationship>('assistant_relationships'))if(other.userId===intent.actor&&other.relationshipId!==intent.relationshipId&&(other.recoveryReceipts?.some(r=>r.operationId===intent.operationId)||[other.lab,...(other.labHistory??[])].some(l=>l?.sourceSnapshot?.records.some(r=>intent.profileIds.some(id=>r.id.startsWith(`user-profile:${id}:`)))))){const child=this.apply({...intent,relationshipId:other.relationshipId,assistantId:other.assistantId,recordIds:[],memoryIds:[],rootRecordIds:[],rootMemoryIds:[]},false);receipt.artifacts.push(...child.artifacts);}receipt.artifacts=[...new Map(receipt.artifacts.map(a=>[`${a.owner}:${a.id}`,a])).values()];const current=this.rows<RecoveryRelationship>('assistant_relationships').find(r=>r.relationshipId===intent.relationshipId);if(current?.recoveryReceipts?.some(r=>r.operationId===intent.operationId)){current.recoveryReceipts=current.recoveryReceipts.map(r=>r.operationId===intent.operationId?receipt:r);this.db.connection.prepare('UPDATE assistant_relationships SET payload_json=? WHERE relationship_id=?').run(JSON.stringify(current),current.relationshipId);}};
  const prior=relationship.recoveryReceipts?.find(r=>r.operationId===intent.operationId);if(prior?.status==='completed'){propagate(prior);return prior;}
  const erase=intent.action==='forget-derived-information'||intent.action==='delete-source',processing=erase||intent.action==='revoke-processing',personalization=processing||intent.action==='stop-personalization',training=processing||intent.action==='prohibit-training',ids=new Set([...intent.recordIds,...intent.memoryIds,...intent.profileIds]),receipt:RecoveryReceipt={operationId:intent.operationId,action:intent.action,status:'completed',artifacts:[],retryRequired:false,limitations:recoveryLimitations};const outcome=(owner:string,id:string,disposition:string)=>receipt.artifacts.push({owner,id,disposition});
  for(const id of intent.memoryIds){const m=this.memories.get(intent.assistantId,id);if(!m||m.provenance.actor!==intent.actor)continue;const eraseMemory=erase&&(intent.action==='forget-derived-information'||intent.rootMemoryIds.includes(id));if(eraseMemory&&!m.lifecycle.contentRemoved)this.memories.forget(intent.assistantId,id,intent.actor,'owner-local privacy request',Number(m.lifecycle.revision));else if(personalization&&['candidate','active'].includes(String(m.lifecycle.status)))this.memories.transition(intent.assistantId,id,'invalidated',intent.actor,'owner-local privacy request',Number(m.lifecycle.revision));outcome('native-memory',id,eraseMemory?'payloadRemoved':personalization?'withheld':'trainingUnsupported');}
  this.db.transaction(tx=>{
   for(const r of relationship.candidates)if(intent.recordIds.includes(r.candidateId)){if(personalization)r.suppressed=true;if(processing)r.processingRevoked=true;if(training)r.trainingExcluded=true;r.revision++;const eraseRecord=erase&&(intent.action==='forget-derived-information'||intent.rootRecordIds.includes(r.candidateId)||!!r.builder&&intent.sourceDigests.includes(r.builder.sourceDigest));if(eraseRecord){r.status='forgotten';r.content='';r.source='forgotten';r.sourceFamily='forgotten';r.sourceFamilies=[];r.annotations=[];r.approvedUse=null;delete r.builder;delete r.discoveryFeedback;}if((r.history?.length??0)<256)r.history=[...(r.history??[]),{operation:intent.action,actor:intent.actor,at:intent.createdAt,revision:r.revision,relatedIds:[]}];outcome('relationship-record',r.candidateId,eraseRecord?'payloadRemoved':personalization?'withheld':'trainingProhibited');}
   if(intent.action==='stop-collection')relationship.collectionStopped=true;
   const jobs=this.rows<ProfileBuilderJob>('profile_builder_jobs').filter(j=>j.userId===intent.actor&&j.relationshipId===intent.relationshipId&&(intent.action==='stop-collection'||processing&&(j.candidateIds.some(id=>ids.has(id))||j.sources.some(s=>intent.sourceDigests.includes(s.sha256)))));
   for(const job of jobs){const retainReview=intent.action==='stop-collection'&&job.status==='review';if(!retainReview)job.status='cancelled';job.revision++;job.collectionAccess='closed';job.failure='Closed by current owner-local privacy boundary';tx.run('DELETE FROM profile_builder_snapshots WHERE job_id=?',job.jobId);if(erase){job.sources=job.sources.map(s=>({...s,path:'forgotten-source',observedAt:null}));job.outcomes=[];}tx.run('UPDATE profile_builder_jobs SET payload_json=? WHERE job_id=?',JSON.stringify(job),job.jobId);for(const c of this.rows<ProfileCandidate>('profile_builder_candidates').filter(c=>c.jobId===job.jobId&&!retainReview)){c.status='rejected';c.revision++;c.approvedUse=null;if(erase){c.key='forgotten';c.value='';c.locator='forgotten';c.sourceDate=null;c.observedAt=null;c.conflicts=[];}tx.run('UPDATE profile_builder_candidates SET payload_json=? WHERE candidate_id=?',JSON.stringify(c),c.candidateId);}outcome('builder',job.jobId,erase?'payloadRemovedAndClosed':'cancelledAndClosed');}
   if(personalization){
    relationship.feedback=(relationship.feedback??[]).filter(f=>!ids.has(f.targetId));
    for(const insight of relationship.insights??[]){insight.status='rejected';insight.revision++;delete insight.proposedControls;if(erase){insight.observation='Source payload forgotten';insight.intervention='Unavailable after source deletion';insight.benefit='';insight.cost='';insight.risk='';insight.validationScenario='';insight.inverse='';insight.uncertainty='Source unavailable';}outcome('insight',insight.insightId,erase?'payloadRemoved':'quarantined');}
    if(relationship.insightJob){relationship.insightJob.status='cancelled';relationship.insightJob.revision++;relationship.insightJob.failure='Source use revoked';outcome('insight-job',relationship.insightJob.jobId,'cancelled');}
    for(const lab of [relationship.lab,...(relationship.labHistory??[])]){if(!lab)continue;lab.status='cancelled';lab.revision++;lab.failure='Source use revoked; preserved metadata cannot resume or promote';delete lab.comparison;delete lab.heldOut;lab.scenarios=[];lab.scenarioIds=[];lab.heldOutScenarioIds=[];lab.candidateControls={...relationshipControlDefaults};if(lab.sourceSnapshot){lab.sourceSnapshot.records=[];delete lab.sourceSnapshot.profileProjection;lab.sourceSnapshot.controls={...relationshipControlDefaults};}outcome('lab',lab.experimentId,'payloadRemovedAndQuarantined');}
    for(const config of this.rows<{configurationId:string;relationshipId:string;derivedInsightId?:string;derivedLabId?:string;status:string;quarantined?:boolean;controls:Record<string,number>;name?:string}>('assistant_relationship_configurations'))if(config.relationshipId===intent.relationshipId&&(config.derivedInsightId||config.derivedLabId)){config.quarantined=true;config.status='superseded';config.controls={...relationshipControlDefaults};config.name='Quarantined source-derived configuration';tx.run('UPDATE assistant_relationship_configurations SET payload_json=? WHERE configuration_id=?',JSON.stringify(config),config.configurationId);outcome('relationship-configuration',config.configurationId,'quarantined');}
    tx.run('DELETE FROM prepared_context WHERE assistant_id=?',intent.assistantId);outcome('prepared-context',intent.assistantId,'payloadRemoved');
   }
   for(const profile of this.rows<{profileId:string;userId:string;revision:number;status:string;declarations:unknown[];assistantScopes:unknown[];revokedAt:string|null;sourceRefs:string[];consentRefs:string[]}>('user_profile_revisions'))if(personalization&&profile.userId===intent.actor&&intent.profileIds.includes(profile.profileId)){profile.status='revoked';profile.revokedAt=intent.createdAt;const eraseProfile=erase&&(intent.action==='forget-derived-information'||intent.rootProfileIds.includes(profile.profileId));if(eraseProfile){profile.declarations=[];profile.assistantScopes=[];profile.sourceRefs=[];profile.consentRefs=[];}tx.run("UPDATE user_profile_revisions SET status='revoked',payload_json=? WHERE profile_id=?",JSON.stringify(profile),profile.profileId);outcome('user-profile',profile.profileId,eraseProfile?'payloadRemoved':'revoked');}
   if(training&&relationship.readiness){const registry=new TrainingRegistry(relationship.readiness.registry);const refs=[...ids];for(const c of relationship.readiness.consents)if(c.sourceRefs.some(r=>referenceMatches(r,ids))){refs.push(`${c.consentId}:${c.revision}`);c.status='revoked';c.revision++;}registry.invalidate(refs,intent.action==='forget-derived-information');relationship.readiness.registry=registry.snapshot();if(intent.action==='forget-derived-information')for(const d of relationship.readiness.registry.datasets)if(d.status==='revoked')for(const r of d.records)r.sourceFamily='forgotten';if(erase)relationship.readiness.comparisons=[];for(const d of relationship.readiness.registry.datasets)if(d.status!=='prepared')outcome('dataset',d.datasetId,intent.action==='forget-derived-information'?'payloadRemoved':'quarantined');for(const a of relationship.readiness.registry.artifacts)if(a.status==='quarantined')outcome('adapter',a.artifactId,'quarantinedNotUnlearned');}
   if(processing){for(const row of tx.all<{id:string;evidence_json:string}>('SELECT id,evidence_json FROM persona_adaptations WHERE assistant_id=?',intent.assistantId))if(referenceMatches(JSON.parse(row.evidence_json),ids)){tx.run("UPDATE persona_adaptations SET status='reversed',evidence_json=? WHERE id=?",JSON.stringify({references:[...ids],revoked:true}),row.id);if(erase)tx.run('UPDATE persona_adaptation_events SET payload_json=? WHERE adaptation_id=?',JSON.stringify({payloadRemoved:true}),row.id);outcome('adaptation',row.id,'quarantined');}for(const row of tx.all<{id:string;proposals_json:string}>('SELECT id,proposals_json FROM dreaming_runs WHERE assistant_id=?',intent.assistantId))if(referenceMatches(JSON.parse(row.proposals_json),ids)){tx.run("UPDATE dreaming_runs SET proposals_json='[]' WHERE id=?",row.id);outcome('dreaming',row.id,'payloadRemoved');}}
   if(personalization){tx.run('DELETE FROM understanding_artifacts WHERE relationship_id=?',intent.relationshipId);tx.run("UPDATE understanding_work SET payload_json=NULL,state=CASE WHEN state='published' THEN state ELSE 'cancelled' END WHERE relationship_id=?",intent.relationshipId);outcome('discovery',intent.relationshipId,'derivedPayloadRemovedAndReplayFenced');}
   tx.run('UPDATE assistant_relationship_idempotency SET response_json=? WHERE relationship_id=?',JSON.stringify({status:409,body:{code:'privacy_replay_fenced',message:'Stored response payload removed after source use changed'}}),intent.relationshipId);outcome('idempotency',intent.relationshipId,'payloadRemovedAndReplayFenced');relationship.revision++;relationship.recoveryReceipts=[...(relationship.recoveryReceipts??[]).filter(r=>r.operationId!==intent.operationId),receipt];tx.run('UPDATE assistant_relationships SET payload_json=? WHERE relationship_id=?',JSON.stringify(relationship),intent.relationshipId);
  });propagate(receipt);return receipt;
 }
}
