import { randomUUID, createHash } from "node:crypto";
import type { Database } from "@lifestream/storage-sqlite";
import { GrantRepository, AdmissionRepository } from "@lifestream/storage-sqlite";
import { createContractValidator } from "@lifestream/contracts";
import { SkillExecutor, validateSkill, type Skill } from "@lifestream/runtime/skills";
import { CapabilityResolver } from "@lifestream/runtime/capabilities/resolver";
import type { CapabilityProvider, CapabilityScope } from "@lifestream/runtime/capabilities/ports";
import { AuthenticationError, type LocalAuthentication, type LocalContext } from "../auth/local-auth.ts";
export type SecurityResult = { status: number; body: Record<string, unknown> };
const object = (value: unknown): Record<string, unknown> => { if (!value || typeof value !== "object" || Array.isArray(value)) throw new AuthenticationError(422, "invalid_request"); return value as Record<string, unknown>; };
export class SecurityAdministration {
  private readonly database: Database; private readonly auth: LocalAuthentication; private readonly grants: GrantRepository; private readonly admissions: AdmissionRepository; private readonly provider: CapabilityProvider | undefined; private readonly now: () => number; private readonly validator = createContractValidator();
  constructor(database: Database, auth: LocalAuthentication, provider?: CapabilityProvider, now: () => number = Date.now) { this.database = database; this.auth = auth; this.grants = new GrantRepository(database); this.admissions = new AdmissionRepository(database); this.provider = provider; this.now = now; }
  handle(method: string, path: string, context: LocalContext, input: unknown): SecurityResult {
    this.auth.assertCurrent(context); const parts = path.split("/").filter(Boolean), assistantId = parts[4], body = object(input);
    if (parts[3] !== "assistants" || !assistantId || !this.auth.canAdminister(context, assistantId)) throw new AuthenticationError(403, "assistant_scope_denied");
    const base = { assistantId, principalId: context.principalId, grantsAuthority: false };
    if (parts[5] === "grants" && parts.length === 6) {
      if (method === "GET") return { status: 200, body: { ...base, grants: this.grants.list(context.principalId, assistantId) } };
      if (method === "POST") { if (!Array.isArray(body.scope) || body.scope.length < 1 || body.scope.length > 16 || body.scope.some(value => typeof value !== "string" || !/^[a-zA-Z0-9_.-]{1,128}$/.test(value)) || typeof body.durationSeconds !== "number" || !Number.isInteger(body.durationSeconds) || body.durationSeconds < 1 || body.durationSeconds > 86400 || !["allowOnce","allowSession","allowPersistent"].includes(String(body.durationMode)) || Object.keys(body).some(key => !["scope", "durationSeconds", "durationMode"].includes(key))) throw new AuthenticationError(422, "invalid_grant_request"); const grant = this.grants.create({ id: randomUUID(), principalId: context.principalId, assistantId, status: "pending", scope: [...new Set(body.scope as string[])], revision: 1, terms: { durationMode: body.durationMode, sessionId: context.sessionId, expiresAt: new Date(this.now() + body.durationSeconds * 1000).toISOString() }, createdAt: new Date(this.now()).toISOString() }); return { status: 201, body: { ...base, grant } }; }
    }
    if (parts[5] === "grants" && parts[6] && parts[7] === "decision" && parts.length === 8 && method === "POST") { const grant = this.grants.get(parts[6], context.principalId); if (!grant || grant.assistantId !== assistantId || !["active", "denied", "revoked"].includes(String(body.decision)) || !Number.isInteger(body.expectedRevision)) throw new AuthenticationError(409, "grant_decision_conflict"); try { return { status: 200, body: { ...base, grant: this.grants.decide(grant.id, context.principalId, body.expectedRevision as number, body.decision as "active" | "denied" | "revoked") } }; } catch { throw new AuthenticationError(409, "grant_decision_conflict"); } }
    if (parts[5] === "audit" && parts.length === 6 && method === "GET") return { status: 200, body: { ...base, events: this.database.connection.prepare("SELECT e.event,e.occurred_at AS occurredAt,e.grant_id AS grantId,e.actor FROM authority_events e JOIN authority_grants g ON e.grant_id=g.id WHERE g.assistant_id=? AND g.principal_id=? ORDER BY e.id").all(assistantId, context.principalId) } };
    if (parts[5] === "skills") return this.skills(method, parts, context, body, assistantId);
    if (parts[5] === "tools") {
      if (!this.provider) return { status: 200, body: { ...base, tools: [], status: "unavailable", reason: "No capability provider is attached to this local administration instance; no live dispatch is inferred." } };
      const scope: CapabilityScope = { assistantId, endpointId: "administration", sessionId: context.sessionId, environment: "local-administration", authorityContextRef: { providerRef: "local-human", contextId: context.principalId, revision: 1 } };
      const resolver = new CapabilityResolver(this.provider, undefined, invocation => {
        if (typeof body.grantId!=="string") return undefined;
        try { const admission=this.admissions.admitGoverned({grantId:body.grantId,principalId:context.principalId,assistantId,sessionId:context.sessionId,capabilityId:invocation.capabilityId,invocationId:invocation.invocationId,inputDigest:createHash("sha256").update(JSON.stringify(invocation.input)).digest("hex"),now:new Date(this.now()).toISOString(),assertCurrent:()=>{this.auth.assertCurrent(context);if(!this.auth.canAdminister(context,assistantId))throw new AuthenticationError(403,"assistant_scope_denied");}});return {invocationId:admission.invocationId,status:"admitted",grantRevision:admission.grantRevision};} catch {return undefined;}
      }, () => new Date(this.now()).toISOString());
      const snapshot = resolver.snapshot(scope);
      if (method === "GET" && parts.length === 6) return { status: 200, body: { ...base, tools: snapshot.capabilities, snapshotRevision: snapshot.revision, expiresAt: snapshot.expiresAt, status: "available", limitation: "Discovery and Skill activation do not grant invocation authority." } };
      if (method === "POST" && parts.length === 8 && parts[7] === "simulate") { const capability = snapshot.capabilities.find(item => item.id === parts[6]); return { status: 200, body: { ...base, status: capability?.simulationSupported ? "simulated" : "unknown", providerInvoked: false, liveEffects: false } }; }
      if (method === "POST" && parts.length === 8 && parts[7] === "invoke") { const capability = snapshot.capabilities.find(item => item.id === parts[6]); if (!capability) throw new AuthenticationError(404, "capability_not_found"); const result = resolver.invoke({ ...scope, invocationId: randomUUID(), interactionId: randomUUID(), capabilityId: capability.id, capabilityVersion: capability.version, snapshotId: snapshot.snapshotId, snapshotRevision: snapshot.revision, input: body.input }); return { status: result.lifecycle === "succeeded" ? 200 : 403, body: { ...base, result } }; }
    }
    return { status: 404, body: { code: "not_found", message: "administration operation not found" } };
  }
  private skills(method: string, parts: string[], context: LocalContext, body: Record<string, unknown>, assistantId: string): SecurityResult {
    const current = parts[6] ? this.database.connection.prepare("SELECT payload_json FROM skills WHERE skill_id=? AND assistant_id=?").get(parts[6], assistantId) as { payload_json: string } | undefined : undefined;
    const existing = current ? JSON.parse(current.payload_json) as Skill : undefined;
    if (method === "GET" && parts.length === 6) return { status: 200, body: { skills: (this.database.connection.prepare("SELECT payload_json FROM skills WHERE assistant_id=? ORDER BY created_at").all(assistantId) as Array<{ payload_json: string }>).map(row => JSON.parse(row.payload_json) as Skill), grantsAuthority: false } };
    if (method === "GET" && existing && parts[7] === "history") return { status: 200, body: { revisions: (this.database.connection.prepare("SELECT payload_json FROM local_skill_revisions WHERE skill_id=? ORDER BY revision").all(existing.skillId) as Array<{ payload_json: string }>).map(row => JSON.parse(row.payload_json) as Skill) } };
    if (method === "POST" && (parts.length === 6 || existing && parts[7] === "revisions")) {
      const proposed = object(body.skill); if (proposed.status !== "draft" || proposed.activationRef !== null || (proposed.assistantId !== undefined && proposed.assistantId !== assistantId) || (existing && body.expectedRevision !== existing.revision)) throw new AuthenticationError(409, "skill_draft_conflict");
      if (/(?:__proto__|constructor|prototype)/.test(JSON.stringify(proposed))) throw new AuthenticationError(422,"unsafe_skill_binding");
      const skill = { ...proposed, skillId: existing?.skillId ?? randomUUID(), assistantId, revision: existing ? existing.revision + 1 : 1, createdBy: context.principalId, createdAt: new Date(this.now()).toISOString() } as unknown as Skill;
      if (!this.validator.validate("https://lifestream.dev/contracts/skill/1.0.0", skill).valid) throw new AuthenticationError(422, "invalid_skill"); try { validateSkill(skill); } catch { throw new AuthenticationError(422, "invalid_skill"); }
      this.persistSkill(skill, existing?.revision); return { status: 201, body: { skill, grantsAuthority: false } };
    }
    if (method === "POST" && existing && parts.length === 8 && parts[7] === "activate") { if (body.expectedRevision !== existing.revision || existing.status !== "draft") throw new AuthenticationError(409, "skill_activation_conflict"); const next = { ...existing, revision: existing.revision + 1, status: "active" as const, activationRef: { reference: `human-review:${context.principalId}:${existing.skillId}:${existing.revision}`, sha256: createHash("sha256").update(JSON.stringify(existing)).digest("hex"), mediaType: "application/json", schemaRef: "https://lifestream.dev/contracts/skill/1.0.0", byteLength: Buffer.byteLength(JSON.stringify(existing)) } }; if(!this.validator.validate("https://lifestream.dev/contracts/skill/1.0.0",next).valid)throw new AuthenticationError(422,"invalid_skill_activation");this.persistSkill(next, existing.revision); return { status: 200, body: { skill: next, grantsAuthority: false } }; }
    if (method === "POST" && existing && parts.length === 8 && parts[7] === "simulate") { const result = new SkillExecutor(() => false, () => ({ lifecycle: "denied", reason: "simulation_has_no_dispatch" })).execute(existing, body.input, randomUUID()); return { status: 200, body: { result, liveEffects: false, memoryWrites: false, grantsAuthority: false } }; }
    return { status: 404, body: { code: "not_found", message: "Skill operation not found" } };
  }
  private persistSkill(skill: Skill, expected?: number): void { this.database.transaction(tx => { const row = tx.get<{ revision: number }>("SELECT revision FROM skills WHERE skill_id=?", skill.skillId); if ((row?.revision) !== expected) throw new AuthenticationError(409, "skill_revision_conflict"); tx.run("INSERT INTO skills VALUES (?,?,?,?,?,?) ON CONFLICT(skill_id) DO UPDATE SET revision=excluded.revision,status=excluded.status,payload_json=excluded.payload_json", skill.skillId, skill.assistantId, skill.revision, skill.status, JSON.stringify(skill), skill.createdAt); tx.run("INSERT INTO local_skill_revisions VALUES (?,?,?)", skill.skillId, skill.revision, JSON.stringify(skill)); }); }
}
