export const relationshipControlDefaults: Readonly<Record<string, number>> = Object.freeze({ formality: 0.5, directness: 0.5, warmth: 0.5, humor: 0.2, verbosity: 0.5, explanationLevel: 0.5, examples: 0.5, challenge: 0.5, terminology: 0.5, personalizationIntensity: 0.5, callbackFrequency: 0.2, relevanceThreshold: 0.7 });
const expression: Record<string, [string, string]> = {
 formality: ['Use relaxed, plain wording.', 'Use formal, precise wording.'], directness: ['Provide a brief orienting explanation before recommendations.', 'Lead with the answer or recommendation.'], warmth: ['Use a neutral professional tone.', 'Use considerate encouraging wording without flattery or claims of attachment.'], humor: ['Avoid optional jokes.', 'Allow light task-appropriate humor when useful; avoid sensitive-topic jokes.'], verbosity: ['Keep optional explanation brief: prefer one or two short sentences, aiming for at most 45 words unless the current request explicitly asks otherwise.', 'Explain relevant reasoning and practical detail at greater length, aiming for up to three short paragraphs and 150 words unless the current request explicitly asks otherwise.'], explanationLevel: ['Start with simple concepts and define unfamiliar terms.', 'Use detailed technical explanations where suitable.'], examples: ['Omit optional examples unless requested or necessary.', 'Include a relevant concrete example when useful.'], challenge: ['Avoid unsolicited critique while preserving necessary corrections.', 'Offer evidence-based pushback when assumptions warrant it.'], terminology: ['Use familiar language and define specialist terms.', 'Use precise domain terminology appropriate to the task.']
};
export function describeRelationshipControls(controls: Readonly<Record<string, number>>): string {
 return Object.entries(expression).map(([key,[low,high]])=>`${key}: ${(controls[key]??relationshipControlDefaults[key]!)<0.34?low:(controls[key]??relationshipControlDefaults[key]!)>0.66?high:'Use a moderate task-appropriate setting.'}`).join(' ') + ' These expression preferences never override the current request, necessary factual corrections, privacy, policy or Core Persona bounds.';
}
export function relationshipControlInventory() {
 const implemented=Object.entries(relationshipControlDefaults).map(([key,value])=>({key,family:key in expression?'communication':'personalContext',schema:{type:'number',minimum:0,maximum:1},minimum:0,maximum:1,default:value,enabled:true,scope:'relationship',source:'active reviewed configuration or balanced-v1 defaults',effect:key in expression?`${expression[key]![0]} At high values: ${expression[key]![1]} Values from 0.34 through 0.66 request a moderate setting.`:key==='callbackFrequency'?'Zero omits optional callbacks; otherwise at most ceil(4 × value) relevant records. Mandatory corrections remain.':key==='personalizationIntensity'?'Zero omits optional personal context and baseline preferences; direct corrections remain. Nonzero allows eligible context.':'A record needs lexical overlap/(overlap+0.25) at or above this threshold, plus nonzero current-task overlap.',limitation:'Input policy and observed replies are distinct. No authority, factual support, privacy or speech delivery guarantee changes.',reset:'Prepare balanced-v1 defaults as an inactive draft; activate explicitly.',acceptanceCaseIds:['LS-TEST-095','LS-TEST-105']}));
 const unavailable:Record<string,string[]>={personalContext:['continuity','permittedTopics','repeatCooldown'],representation:['representationPreset','baselineAllocation','episodeAllocation','semanticAllocation','proceduralAllocation','compression','contextBudget'],evidence:['sourcePriority','independenceThreshold','reviewThreshold','decay','revalidation','corroboration','perKindSalience'],insights:['cadence','candidateVolume','enabledLenses','adaptationLimits','automaticAdmission'],labAdapters:['variant','cohort','resourceLimits','datasetRevision','adapterIdentity']};
 return [...implemented,...Object.entries(unavailable).flatMap(([family,keys])=>keys.map(key=>({key,family,schema:{type:key==='contextBudget'?'integer':'string'},default:key==='contextBudget'?8192:key==='representationPreset'?'recordOriented':'unsupported',enabled:false,scope:'relationship',source:'fixed implementation boundary',effect:'No editable runtime effect in this control.',limitation:family==='labAdapters'?'Use the isolated Lab and readiness workbench; no live adapter is eligible through a tuning slider.':key==='contextBudget'?'The context budget is fixed at 8192 UTF-8 bytes; mandatory restrictions cannot be discarded.':family==='representation'?'Record-oriented and convention-oriented compilers are available through isolated Lab comparison and explicit configuration promotion/activation; no numeric slider selects them.':'No implemented bounded automatic policy for this control. Use explicit record review; this input cannot activate unsupported behavior.',reset:'No editable value to reset.',acceptanceCaseIds:['LS-TEST-105']})))];
}
