import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {fixtureEpisode,fixtureGameEpisodeSources} from './fixtures/game-memory.ts';
import {selectGameHelpSource,type GameHelpSourceInput,type GameHelpSourceBoundary} from '../src/activity/help.ts';
function fixture(){
 let now=Date.now(),revision=1,enabled=true;const episode=fixtureEpisode(now),observation=fixtureGameEpisodeSources(episode).observations[0]!;
 const item:GameHelpSourceInput['item']={schemaVersion:'1.0.0',recordType:'gameHelpItem',scope:structuredClone(episode.scope),helpId:randomUUID(),question:'How would you approach the visible gate?',attemptsSummary:episode.summary,attemptedActionIds:episode.sourceActionIds,sourceObservationIds:episode.sourceObservationIds,channelRef:'test-only:configured-channel',recipientRef:'test-only:configured-owner',contactPolicyRevision:1,queuedAt:new Date(now).toISOString(),status:'queued',screenshotStatus:'pending',screenshot:null,imageTransportSupported:null,sentAt:null,messageSentEvidenceRef:null,attachmentSentEvidenceRef:null,deliveryEvidenceRef:null,replyAdviceRef:null,authenticatedReplyEvidenceRef:null,limitation:null,attachmentStatus:'queued',attachmentTransferredEvidenceRef:null,attachmentDeliveryEvidenceRef:null,screenshotUnavailableDisclosed:false};
 const input:GameHelpSourceInput={item,episode,observation,maximumBytes:8192,maximumObservationAgeMs:6000,nowMs:now,freshUntilMs:now+5000};
 const host:GameHelpSourceBoundary={boundaryRevision:()=>String(revision),episodeCurrent:()=>enabled,observationCurrent:()=>enabled,pauseCurrent:()=>enabled,configuredRecipientCurrent:()=>enabled,questionGroundedCurrent:()=>enabled,attachmentCurrent:()=>enabled,now:()=>now};
 return {input,host,withdraw:()=>{enabled=false;revision++;},advance:(ms:number)=>now+=ms,change:()=>revision++};
}
test('inert pending help cites original actual-attempt lineage and preserves uncertainty without claiming delivery',()=>{const f=fixture(),v=selectGameHelpSource(f.input,f.host);assert.equal(v.state,'prepared');assert.equal(v.isCurrent(),true);assert.equal(v.sendAuthority,false);assert.equal(v.resumeAuthority,false);const data=JSON.parse(v.content!);assert.equal(data.attemptsSummary,f.input.episode.summary);assert.equal(data.scope.timelineId,f.input.episode.scope.timelineId);assert.deepEqual(data.attemptedActionIds,f.input.episode.sourceActionIds);assert.equal(data.uncertainty,f.input.episode.uncertainty);assert.equal(data.rawEvidenceAvailability,'notRetained');assert.ok(Object.isFrozen(v));assert.match(v.content!,/No message or image delivery/);assert.equal(v.content!.includes(f.input.item.recipientRef),false);});
for(const port of ['episodeCurrent','observationCurrent','pauseCurrent','configuredRecipientCurrent','questionGroundedCurrent']as const)test('help selection requires independent '+port,()=>{const f=fixture();f.host[port]=()=>false;assert.equal(selectGameHelpSource(f.input,f.host).state,'unavailable');});
test('a late source withdrawal in semantic grounding changes the atomic boundary and cannot produce a selected help source',()=>{const f=fixture();f.host.questionGroundedCurrent=()=>{f.withdraw();return true;};assert.equal(selectGameHelpSource(f.input,f.host).state,'unavailable');});
test('selection expiry, clock rollback and privacy withdrawal retire a view permanently',()=>{for(const why of ['expiry','rollback','source']){const f=fixture(),v=selectGameHelpSource(f.input,f.host);assert.equal(v.state,'prepared');if(why==='expiry')f.advance(5000);if(why==='rollback')f.advance(-1);if(why==='source')f.withdraw();assert.equal(v.isCurrent(),false);f.advance(1);assert.equal(v.isCurrent(),false);}});
test('caller mutation cannot replace captured pause/source callbacks or prepared source content',()=>{const f=fixture(),v=selectGameHelpSource(f.input,f.host);f.host.pauseCurrent=()=>false;f.input.item.question='Forged later question';assert.equal(v.isCurrent(),true);assert.match(v.content!,/How would you approach/);assert.doesNotMatch(v.content!,/Forged later/);f.withdraw();assert.equal(v.isCurrent(),false);});
for(const [label,change]of [
 ['foreign timeline',(v:GameHelpSourceInput)=>v.item.scope.timelineId=randomUUID()],['unrecorded action',(v:GameHelpSourceInput)=>v.item.attemptedActionIds=[randomUUID()]],['invented attempts',(v:GameHelpSourceInput)=>v.item.attemptsSummary='The game was won.'],['different observation',(v:GameHelpSourceInput)=>v.observation.observationId=randomUUID()],['late future source',(v:GameHelpSourceInput)=>v.observation.receivedAt=new Date(v.nowMs+1).toISOString()],['claimed send',(v:GameHelpSourceInput)=>{v.item.sentAt=new Date(v.nowMs).toISOString();v.item.messageSentEvidenceRef='forged:send';}],['empty question',(v:GameHelpSourceInput)=>v.item.question=' '],['hidden state',(v:GameHelpSourceInput)=>(v.observation as any).unrevealedFlag=true],['byte limit',(v:GameHelpSourceInput)=>v.maximumBytes=1]
]as const)test('help source refuses '+label,()=>{const f=fixture();change(f.input);assert.equal(selectGameHelpSource(f.input,f.host).state,'unavailable');});
test('independently retained attachment must bind exactly to the pictured game observation and separate custody',()=>{
 const f=fixture(),o=f.input.observation,frame=o.screenshots[0]!;f.input.item.screenshotStatus='ready';f.input.item.screenshot={sourceDomain:'simulatedGame',captureRegion:'gameFramebuffer',screenshotId:frame.screenshotId,observationId:o.observationId,activityId:o.scope.activityId,runId:o.scope.runId,timelineId:o.scope.timelineId,frameNumber:o.frameNumber,capturedAt:o.capturedAt,sha256:frame.sha256,byteLength:frame.byteLength,mediaType:frame.mediaType,width:frame.width,height:frame.height,attachmentArtifact:{reference:'test-only:bounded-game-attachment',sha256:frame.sha256,mediaType:frame.mediaType,schemaRef:'test-only:game-framebuffer-png',byteLength:frame.byteLength},retentionPolicyRef:'test-only:separate-attachment-policy',expiresAt:new Date(f.input.nowMs+6000).toISOString(),ageAtSendMs:null,captureTimeDisclosed:false};
 const selected=selectGameHelpSource(f.input,f.host);assert.equal(selected.state,'prepared');assert.ok(!selected.content!.includes('bounded-game-attachment'));f.host.attachmentCurrent=()=>false;assert.equal(selectGameHelpSource(f.input,f.host).state,'unavailable');f.host.attachmentCurrent=()=>true;
 for(const change of [(v:any)=>v.timelineId=randomUUID(),(v:any)=>v.sourceDomain='camera',(v:any)=>v.captureRegion='desktop',(v:any)=>v.attachmentArtifact.sha256='f'.repeat(64),(v:any)=>v.attachmentArtifact.byteLength++,(v:any)=>v.ageAtSendMs=0,(v:any)=>v.expiresAt=new Date(f.input.nowMs).toISOString()]){const altered=structuredClone(f.input);change(altered.item.screenshot);assert.equal(selectGameHelpSource(altered,f.host).state,'unavailable');}
});
