import assert from 'node:assert/strict';
import test from 'node:test';
import {randomUUID} from 'node:crypto';
import {selectCampaignContext} from '../src/activity/journal.ts';
import {campaignJournalFixture} from '../../storage-sqlite/test/fixtures/campaign-journal.ts';
test('bounded existing-section campaign materialization includes sourced summary and unfinished goals without executable controls',()=>{const now=Date.now(),journal=campaignJournalFixture(now),selection=selectCampaignContext(journal,8192,now,()=>true);assert.equal(selection.status,'selected');const material=JSON.parse(selection.content!);assert.equal(material.untrusted,true);assert.equal(material.entries.length,2);assert.equal(material.goals[0].status,'active');assert.match(material.limitations.join(' '),/reconciliation/);assert.equal(selection.ref!.revision,journal.revision);assert.equal(selection.isCurrent(),true);journal.summary='MUTATED_CALLER';assert.doesNotMatch(selection.content!,/MUTATED_CALLER/);});
test('selection refuses oversize or missing grounded summary without dropping unfinished or contrary source context',()=>{const now=Date.now(),journal=campaignJournalFixture(now);assert.equal(selectCampaignContext(journal,1,now,()=>true).reason,'budgetExceeded');journal.summaryEntryIds=[randomUUID()];assert.equal(selectCampaignContext(journal,8192,now,()=>true).reason,'invalidJournal');});
test('source/access revision invalidation retires a held selection permanently even after a later permissive signal',()=>{const now=Date.now(),journal=campaignJournalFixture(now);let current=true;const selection=selectCampaignContext(journal,8192,now,()=>current);current=false;assert.equal(selection.isCurrent(),false);current=true;assert.equal(selection.isCurrent(),false);assert.equal(selectCampaignContext(journal,8192,now,()=>{throw Error('Private source error');}).reason,'sourceChanged');});
test('goal supersession cycles and duplicate identities cannot become compact planning history',()=>{const now=Date.now(),journal=campaignJournalFixture(now),first=journal.goals[0]!,other={...first,goalId:randomUUID(),status:'superseded' as const,supersedesGoalId:first.goalId};first.status='superseded';first.supersedesGoalId=other.goalId;journal.goals.push(other);assert.equal(selectCampaignContext(journal,8192,now,()=>true).reason,'invalidJournal');});
