import assert from 'node:assert/strict';
import test from 'node:test';
import {randomUUID} from 'node:crypto';
import {projectGameEpisode} from '../src/activity/memory.ts';
import {gameEpisodeSnapshot,gameProjectionSnapshot,gameEpisodeFamilyKey} from '@lifestream/contracts/game-memory';
import {fixtureEpisode,projection} from './fixtures/game-memory.ts';
test('direct game candidate preserves simulation, source time/range, uncertainty and independent transformation attribution',()=>{
 const now=Date.now(),e=fixtureEpisode(now),p=projection(e,now);assert.ok(p);assert.equal(p.memoryRecord.factuality,'unverified');assert.equal(p.memoryRecord.kind,'experiential');assert.equal(p.memoryRecord.status,'candidate');assert.equal(p.memoryRecord.provenance.sourceType,'interaction');assert.equal(p.episode.rawEvidenceAvailability,'notRetained');assert.equal(p.memoryRecord.lastReinforcedAt,null);assert.equal(p.memoryRecord.content,e.summary);assert.deepEqual(p.episode,e);assert.ok(Object.isFrozen(p.episode.scope));assert.equal(Object.keys(p.memoryRecord.extensions!).length,1);assert.equal(p.memoryRecord.extensions!['lifestream.localGameActivity']!.transformationConfidence.value,0.6);
});
for(const [label,change]of [
 ['unstarted attempt',(e:any)=>{e.sourceAdmissionIds=[];}],['reversed frame range',(e:any)=>{e.frameRange.from=31;}],['reversed time',(e:any)=>{e.occurredTo=e.occurredFrom;e.occurredFrom=new Date(Date.parse(e.occurredTo)+1).toISOString();}],['future recording',(e:any)=>{e.recordedAt=new Date(Date.now()+100000).toISOString();}],['expired source',(e:any)=>{e.expiresAt=e.recordedAt;}],['duplicate observation',(e:any)=>{e.sourceObservationIds.push(e.sourceObservationIds[0]);}],['invalidated source',(e:any)=>{e.state='invalidated';}],['physical source',(e:any)=>{e.sourceKind='physicalCamera';}],['extra hidden state',(e:any)=>{e.rngState=42;}]
]as const)test('episode rejects '+label,()=>{const now=Date.now(),e=fixtureEpisode(now);change(e);assert.equal(gameEpisodeSnapshot(e,now),null);assert.equal(projection(e,now),null);});
for(const [label,change]of [
 ['foreign actor',(p:any)=>{p.memoryRecord.createdBy=randomUUID();}],['foreign Assistant',(p:any)=>{p.memoryRecord.assistantId=randomUUID();}],['fabricated Human statement',(p:any)=>{p.memoryRecord.factuality='participantStatement';}],['physical world fact',(p:any)=>{p.memoryRecord.factuality='worldGrounded';p.memoryRecord.worldEvidenceRefs=[{provider:'fake',reference:'fake',schemaVersion:'1'}];}],['independent reinforcement',(p:any)=>{p.memoryRecord.lastReinforcedAt=p.memoryRecord.createdAt;}],['unattributed confidence',(p:any)=>{p.memoryRecord.confidence=1;}],['changed timeline',(p:any)=>{p.memoryRecord.extensions['lifestream.localGameActivity'].timelineId=randomUUID();}],['invented achievement',(p:any)=>{p.memoryRecord.content='I solved an unseen puzzle.';}],['unknown extra binding',(p:any)=>{p.memoryRecord.extensions.authority=true;}],['learning enabled',(p:any)=>{p.memoryRecord.status='active';}]
]as const)test('projection rejects '+label,()=>{const now=Date.now(),p=structuredClone(projection(fixtureEpisode(now),now));change(p);assert.equal(gameProjectionSnapshot(p,now),null);});
test('timeline reload and run replacement preserve the same independent family; another campaign remains distinct',()=>{const e=fixtureEpisode(),r=structuredClone(e);r.scope.timelineId=randomUUID();r.scope.runId=randomUUID();assert.equal(gameEpisodeFamilyKey(r),gameEpisodeFamilyKey(e));r.scope.campaignId=randomUUID();assert.notEqual(gameEpisodeFamilyKey(r),gameEpisodeFamilyKey(e));});
test('source withdrawal during projection cannot publish a candidate',()=>{const now=Date.now(),e=fixtureEpisode(now);let calls=0;assert.equal(projectGameEpisode({episode:e,memoryId:randomUUID(),estimate:{value:0.2,basis:'scripted',policyRef:'scripted:1'},nowMs:now},()=>++calls===1),null);assert.equal(calls,2);});
test('source callback receives immutable data; getters and proxies never execute during intake',()=>{const now=Date.now(),e=fixtureEpisode(now);let reads=0;const input:any={episode:e,memoryId:randomUUID(),estimate:{value:0.2,basis:'scripted',policyRef:'scripted:1'},nowMs:now};Object.defineProperty(input,'episode',{enumerable:true,get(){reads++;throw Error('must not run');}});assert.equal(projectGameEpisode(input,()=>true),null);assert.equal(reads,0);assert.equal(projectGameEpisode(new Proxy({},{} )as any,()=>true),null);});
