import assert from "node:assert/strict";
import { test } from "node:test";
import { BehaviorController } from "../src/embodiment/controller.ts";

const identity = { stateId: "00000000-0000-4000-8000-000000000025", interactionTraceId: "00000000-0000-4000-8000-000000000026", assistantId: "00000000-0000-4000-8000-000000000027", endpointId: "00000000-0000-4000-8000-000000000028" };
const affect = { valence: 0, arousal: 0.2, confidence: 1 };

test("audio truth owns speaking state and sequences are monotonic", () => { const controller = new BehaviorController(identity); const generated = controller.update({ interaction: "generating", audioPlaying: false, interrupted: false, affect, now: "2026-09-07T00:00:00Z" }); const speaking = controller.update({ interaction: "generating", audioPlaying: true, interrupted: false, affect, now: "2026-09-07T00:00:01Z" }); assert.equal(generated.speechState, "silent"); assert.equal(speaking.speechState, "speaking"); assert.equal(speaking.sequence, generated.sequence + 1); });
test("interruption and policy override are observable; expired transient state falls back", () => { const controller = new BehaviorController(identity); const interrupted = controller.update({ interaction: "speaking", audioPlaying: true, interrupted: true, affect, now: "2026-09-07T00:00:00Z" }); assert.equal(interrupted.speechState, "interrupted"); const overridden = controller.update({ interaction: "speaking", audioPlaying: true, interrupted: false, policyOverride: { speechState: "silent", urgency: "high" }, affect, now: "2026-09-07T00:00:01Z" }); assert.equal(overridden.source, "policyOverride"); assert.equal(overridden.speechState, "silent"); assert.equal(overridden.urgency, "high"); assert.equal(controller.current("2026-09-07T00:00:07Z")?.speechState, "silent"); });
test("affect is expressive data and cannot change authority inputs", () => { const controller = new BehaviorController(identity); const calm = controller.update({ interaction: "working", audioPlaying: false, interrupted: false, affect, now: "2026-09-07T00:00:00Z" }); const excited = controller.update({ interaction: "working", audioPlaying: false, interrupted: false, affect: { ...affect, arousal: 1 }, now: "2026-09-07T00:00:01Z" }); assert.equal(calm.activity, excited.activity); assert.equal(calm.urgency, excited.urgency); });
