import assert from 'node:assert/strict';import test from 'node:test';import {randomUUID} from 'node:crypto';
import {ExperienceRepository,Database} from '../../storage-sqlite/dist/index.js';import {selectExperience} from '../src/experience/selection.ts';import {reflectExperience} from '../src/experience/reflection.ts';import {defaultTopics,type State} from '@lifestream/contracts/experience';import type {InferenceProvider} from '../src/inference/port.ts';
function state():State{const db=new Database({path:':memory:'});db.migrate();const repo=new ExperienceRepository(db),scope={assistantId:randomUUID(),principalId:randomUUID(),relationshipId:randomUUID()},s=repo.read(scope);db.close();s.configuration.enabled=true;s.items=['reading','gardening','health'].map((topic,i)=>({id:String(i),kind:'project',topic:topic as 'reading',statement:'A synthetic '+topic+' project',nextStep:'Consider one next step',uncertainty:'medium',sourceRefs:['retained-1'],disposition:'open',revision:1,lastEvaluatedAt:new Date(0).toISOString(),reconsiderAfter:new Date(0).toISOString()}));return s;}
test('fixed candidates and facts change pre-wording choice only when imprint changes; privacy and request filters run first',()=>{const baseline=state(),input='What should we work on next?';assert.equal(selectExperience(baseline,input,true,1,'a').item?.topic,'reading');const learned=structuredClone(baseline);learned.imprints[0]!.learned=learned.imprints[0]!.value=.05;assert.equal(selectExperience(learned,input,true,1,'b').item?.topic,'gardening');assert.deepEqual(selectExperience(learned,input,true,1,'b').receipt.considered,['0','1']);assert.equal(selectExperience(learned,input,false,1,'c').item,null);learned.configuration.topicPolicies.gardening='disallowed';assert.equal(selectExperience(learned,input,true,1,'d').item?.topic,'reading');assert.equal(selectExperience(baseline,'Continue our health project',true,1,'e').item?.topic,'health');assert.equal(selectExperience(baseline,'What should we do about a health emergency?',true,1,'f').item,null);assert.equal(selectExperience(baseline,'Explain gardening in three sentences',true,1,'g').item,null);assert.equal(selectExperience(baseline,'Continue gardening, but do not mention gardening',true,1,'h').item,null);assert.deepEqual(baseline.configuration.topicPolicies,defaultTopics);});
test('actual token admission is separate from UTF-8 byte bounds and rejects absent tokenizers or malformed output',async()=>{const s=state(),base={state:s,episodes:[],sources:[],allowedDimensions:[],jobId:randomUUID(),signal:new AbortController().signal,deadlineAt:Date.now()+120000};let calls=0,inputCount=4097,outputCount=5;
 const provider:InferenceProvider={tokenize:async input=>({count:typeof input==='string'?outputCount:inputCount,identity:'fixture-tokenizer'}),async*generate(){calls++;yield {kind:'text',text:JSON.stringify({recordType:'reflectionResult',decision:'noChange',conclusion:'No independent evidence.',items:[],changes:[]})};yield {kind:'done'};}};
 await assert.rejects(reflectExperience({...base,provider}),/input_token_limit/);assert.equal(calls,0);inputCount=5;outputCount=769;await assert.rejects(reflectExperience({...base,provider}),/output_token_limit/);outputCount=10;assert.equal((await reflectExperience({...base,provider})).outputTokens,10);await assert.rejects(reflectExperience({...base,provider:{generate:provider.generate}}),/tokenizer_unavailable/);
});
test('reflection supplies only source-bound repeated-interest candidates to the selected provider',async()=>{const s=state(),episodes=[{recordType:'episode' as const,id:'garden-1',scope:s.scope,sourceRefs:['source-1'],sourceDigest:'a'.repeat(64),independence:'turn:1',occurredAt:new Date(0).toISOString(),eligibleReason:'project' as const,state:'retained' as const},{recordType:'episode' as const,id:'garden-2',scope:s.scope,sourceRefs:['source-2'],sourceDigest:'b'.repeat(64),independence:'turn:2',occurredAt:new Date(1).toISOString(),eligibleReason:'project' as const,state:'retained' as const},{recordType:'episode' as const,id:'reading-1',scope:s.scope,sourceRefs:['source-3'],sourceDigest:'c'.repeat(64),independence:'turn:3',occurredAt:new Date(2).toISOString(),eligibleReason:'project' as const,state:'retained' as const}],sources=[{id:'source-1',revision:1,family:'turn:1',digest:'d'.repeat(64),content:'I enjoyed my gardening experiment and want to plan another gardening trial.',occurredAt:new Date(0).toISOString()},{id:'source-2',revision:1,family:'turn:2',digest:'e'.repeat(64),content:'I found this gardening comparison rewarding and will continue the gardening project.',occurredAt:new Date(1).toISOString()},{id:'source-3',revision:1,family:'turn:3',digest:'f'.repeat(64),content:'I enjoyed the reading, but I do not want to continue the reading project.',occurredAt:new Date(2).toISOString()}];let captured:any;
 const provider:InferenceProvider={tokenize:async()=>({count:10,identity:'fixture-tokenizer'}),async*generate(request){captured=JSON.parse(request.sections.at(-1)!.content);yield {kind:'text',text:JSON.stringify({recordType:'reflectionResult',decision:'noChange',conclusion:'Fixture result.',items:[],changes:[]})};yield {kind:'done'};}};
 await reflectExperience({state:s,episodes,sources,allowedDimensions:['attentionGardening','attentionReading'],jobId:randomUUID(),provider,signal:new AbortController().signal,deadlineAt:Date.now()+120000});assert.deepEqual(captured.eligibleAttentionChanges,[{dimension:'attentionGardening',episodeRefs:['garden-1','garden-2']}]);
});

test('visual scene enjoyment and mixed episodes never become repeated owner-interest candidates',async()=>{const s=state(),sources=[{id:'visual-episode:synthetic-1',revision:1,family:'visual:family-1',digest:'a'.repeat(64),content:'Scene OCR: I enjoyed gardening and want to continue gardening again.',occurredAt:new Date(0).toISOString()},{id:'owner-1',revision:1,family:'turn:owner-1',digest:'b'.repeat(64),content:'I enjoyed gardening and want to continue gardening again.',occurredAt:new Date(0).toISOString()}],episodes=[0,1].map(n=>({recordType:'episode' as const,id:'mixed-'+n,scope:s.scope,sourceRefs:sources.map(s=>s.id),sourceDigest:'c'.repeat(64),independence:'mixed:'+n,occurredAt:new Date(n).toISOString(),eligibleReason:'question' as const,state:'retained' as const}));let captured:any,policy='';const provider:InferenceProvider={tokenize:async()=>({count:10,identity:'fixture-tokenizer'}),async*generate(request){captured=JSON.parse(request.sections.at(-1)!.content);policy=request.sections[0]!.content;yield {kind:'text',text:JSON.stringify({recordType:'reflectionResult',decision:'noChange',conclusion:'Insufficient owner preference evidence.',items:[],changes:[]})};yield {kind:'done'};}};await reflectExperience({state:s,sources,episodes,allowedDimensions:['attentionGardening'],jobId:randomUUID(),provider,signal:new AbortController().signal,deadlineAt:Date.now()+120000});assert.deepEqual(captured.eligibleAttentionChanges,[]);assert.match(policy,/not a user statement/);assert.match(policy,/cannot support an imprint change/);});

test('game dialogue enjoyment stays simulated evidence in the canonical reflection prompt',async()=>{
 const s=state(),sources=[{id:'game-episode:synthetic',revision:1,family:'game:original-trial',digest:'a'.repeat(64),content:'Game dialogue: I enjoyed games and want to continue games again.',occurredAt:new Date(0).toISOString()},{id:'owner',revision:1,family:'turn:owner',digest:'b'.repeat(64),content:'I enjoyed games and want to continue games again.',occurredAt:new Date(0).toISOString()}],episodes=[0,1].map(n=>({recordType:'episode' as const,id:'mixed-game-'+n,scope:s.scope,sourceRefs:sources.map(x=>x.id),sourceDigest:'c'.repeat(64),independence:'mixed:'+n,occurredAt:new Date(n).toISOString(),eligibleReason:'outcome' as const,state:'retained' as const}));let captured:any,request:any;
 const provider:InferenceProvider={tokenize:async()=>({count:10,identity:'fixture-tokenizer'}),async*generate(input){request=input;captured=JSON.parse(input.sections.at(-1)!.content);yield {kind:'text',text:JSON.stringify({recordType:'reflectionResult',decision:'noChange',conclusion:'No independent Human preference evidence.',items:[],changes:[]})};yield {kind:'done'};}};
 await reflectExperience({state:s,sources,episodes,allowedDimensions:['attentionGames'],jobId:randomUUID(),provider,signal:new AbortController().signal,deadlineAt:Date.now()+120000});assert.deepEqual(captured.eligibleAttentionChanges,[]);assert.equal(request.sections.length,9);assert.equal(request.sections[0].sourceRevision,'experience-reflection-v3');assert.match(request.sections[0].content,/historical simulated activity/);assert.match(request.sections[0].content,/no play, save, contact or control authority/);
});
