import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import type * as G from '@lifestream/contracts/game-activity';
import {gameCampaignFixture} from './fixtures/game-campaign.ts';
import {selectGameCampaignContext,prepareGameCampaignContext,gameDecisionInput,selectGameDispatchValidation,gameDispatchValidationFor,type GameDispatchBoundary} from '../src/activity/game-journal.ts';
import {createPreparedTurnBinding,finalizePreparedTurn,requestForFinalizedTurn} from '../src/inference/prompt.ts';
function fixture(){
 const f=gameCampaignFixture(),s=f.input.expectedScope,o=f.input.observation;let now=f.input.nowMs+50,qualified=true;
 o.visibleState=[{fieldId:'scripted:visible-menu',value:'open',visibility:'visibleNow',firstObservedRef:o.observationId,lastObservedRef:o.observationId,timelineId:s.timelineId,observedAt:o.receivedAt,freshUntil:new Date(f.input.freshUntilMs).toISOString(),decoderRevision:'1.0.0',manifestDigest:'b'.repeat(64),limitations:['Scripted reviewed visibility, not native proof.']}];
 const c=s.contextBinding,binding=createPreparedTurnBinding({viewId:randomUUID(),revision:1,invalidationKey:randomUUID(),scope:{assistantId:s.assistantId,principalId:s.principalId,relationshipId:s.relationshipId,conversationId:c.conversationId,sessionId:c.sessionId,endpointId:c.endpointId},conversation:'[]',sourceRevisions:{journal:String(f.input.journal.revision)}}),game=prepareGameCampaignContext(selectGameCampaignContext(f.input,f.boundary),binding),turn=finalizePreparedTurn({assistantId:s.assistantId,sessionId:c.sessionId,endpointId:c.endpointId,interactionId:randomUUID(),origin:'activityStep',conversation:'[]',preparedTurnBinding:binding,preparedGameCampaignContext:game,deadlineAt:new Date(f.input.nowMs+10000).toISOString()},()=>true),request=requestForFinalizedTurn(turn,binding,()=>true),decision=gameDecisionInput(game,binding,request,100,f.input.nowMs,f.input.freshUntilMs);
 const proposal:G.GameActionProposal={schemaVersion:'1.0.0',recordType:'gameActionProposal',scope:structuredClone(s),proposalId:randomUUID(),observationId:o.observationId,observationRevision:o.revision,preparedViewId:binding.viewId,preparedViewRevision:binding.revision,invalidationKey:binding.invalidationKey,buttons:['a'],durationFrames:2,maxWallMs:100,expectedVisibleOutcome:'A scripted menu might change.',uncertainty:'No actual native input.',adviceRefs:[],reason:'Scripted dispatch source check.',preconditions:[{predicateId:randomUUID(),fieldId:'scripted:visible-menu',expectedValue:'open',sourceObservationId:o.observationId}]};
 const fresh=structuredClone(o);fresh.observationId=randomUUID();fresh.frameNumber=12;fresh.capturedAt=new Date(now-20).toISOString();fresh.receivedAt=new Date(now-10).toISOString();fresh.screenshots=fresh.screenshots.map(v=>({...v,screenshotId:randomUUID(),capturedAt:fresh.capturedAt,frameNumber:fresh.frameNumber}));fresh.visibleState=fresh.visibleState.map(v=>({...v,lastObservedRef:fresh.observationId,observedAt:fresh.receivedAt}));
 const boundary:GameDispatchBoundary={maxPlanningAgeMs:1000,maxPlanningFrameDelta:5,maximumObservationAgeMs:200,validatorRef:'scripted:qualified-dispatch',observationCurrent:()=>qualified,now:()=>now};f.clock(now);
 const select=()=>selectGameDispatchValidation(game,binding,decision,proposal,fresh,boundary);
 return {f,game,binding,decision,proposal,fresh,boundary,select,withdraw:()=>qualified=false,advance:(ms:number)=>{now+=ms;f.clock(now);},rollback:()=>{now--;f.clock(now);}};
}

test('genuine prepared proposal revalidates unchanged typed predicates at a newer frame with finite original-source expiry',()=>{
 const f=fixture(),s=f.select(),v=gameDispatchValidationFor(s)!;assert.equal(s.status,'selected');assert.equal(v.planningFrameNumber,10);assert.equal(v.checkedFrameNumber,12);assert.equal(v.dispatchObservationId,f.fresh.observationId);assert.equal(v.predicateChecks[0]!.sourceObservationId,f.fresh.observationId);assert.equal(v.predicateChecks[0]!.observedValue,'open');assert.ok(Date.parse(v.preparedContextFreshUntil)<=f.f.input.freshUntilMs);assert.ok(Object.isFrozen(v.predicateChecks));assert.equal(gameDispatchValidationFor({...s,isCurrent:()=>true}),null);f.withdraw();assert.equal(gameDispatchValidationFor(s),null);f.boundary.observationCurrent=()=>true;assert.equal(gameDispatchValidationFor(s),null,'retirement is irreversible');
});
for(const mode of ['copiedView','copiedBinding','copiedDecision','foreignScope','wrongPins','oldFrame','excessFrameDelta','oldCapture','futureReceived','futureInterpretation','changedPredicate','missingPredicate','historicalField','foreignFieldTimeline','wrongFieldSource','staleField','futureField','staleScreenshot','wrongScreenshotFrame','detachedFact','duplicateField','spoofedSourceIdentity','invalidBounds','zeroObservationAge','deniedSource','sourceClockRollback','preparedWithdrawal']as const)test('fresh dispatch refuses '+mode,()=>{
 const f=fixture(),o=f.fresh;
 if(mode==='foreignScope')o.scope.timelineId=randomUUID();if(mode==='wrongPins')o.pinsDigest='f'.repeat(64);if(mode==='oldFrame')o.frameNumber=9;if(mode==='excessFrameDelta')f.boundary.maxPlanningFrameDelta=1;if(mode==='oldCapture')o.capturedAt=f.f.input.observation.capturedAt;if(mode==='futureReceived')o.receivedAt=new Date(Date.now()+10000).toISOString();if(mode==='futureInterpretation')o.interpretedAt=new Date(Date.now()+10000).toISOString();if(mode==='changedPredicate')o.visibleState[0]!.value='closed';if(mode==='missingPredicate')o.visibleState=[];if(mode==='historicalField')o.visibleState[0]!.visibility='previouslyObserved';if(mode==='foreignFieldTimeline')o.visibleState[0]!.timelineId=randomUUID();if(mode==='wrongFieldSource')o.visibleState[0]!.lastObservedRef=randomUUID();if(mode==='staleField')o.visibleState[0]!.freshUntil=new Date(0).toISOString();if(mode==='futureField')o.visibleState[0]!.observedAt=new Date(Date.now()+10000).toISOString();if(mode==='staleScreenshot')o.screenshots[0]!.expiresAt=new Date(0).toISOString();if(mode==='wrongScreenshotFrame')o.screenshots[0]!.frameNumber=1;if(mode==='detachedFact')o.facts=[{factId:randomUUID(),description:'Scripted feature.',epistemicKind:'visibleFeature',sourceScreenshotIds:[randomUUID()],extractionKind:'screenPixels',extractorRef:null,uncertainty:'Synthetic.',limitations:[],sourceKind:'playerVisibleGameObservation',untrusted:true}];if(mode==='duplicateField')o.visibleState.push({...o.visibleState[0]!});if(mode==='spoofedSourceIdentity')o.observationId=f.f.input.observation.observationId;if(mode==='invalidBounds')f.boundary.maxPlanningAgeMs=Infinity;if(mode==='zeroObservationAge')f.boundary.maximumObservationAgeMs=0;if(mode==='deniedSource')f.withdraw();if(mode==='sourceClockRollback')f.boundary.now=()=>-1;if(mode==='preparedWithdrawal')f.f.deny();
 const s=selectGameDispatchValidation(mode==='copiedView'?{...f.game}:f.game,mode==='copiedBinding'?{...f.binding}:f.binding,mode==='copiedDecision'?{...f.decision}:f.decision,f.proposal,o,f.boundary);assert.equal(s.status,'unavailable');assert.equal(gameDispatchValidationFor(s),null);
});
for(const mode of ['expiry','rollback','limits','qualifier','validator','prepared']as const)test('selected dispatch is fenced irreversibly after '+mode,()=>{
 const f=fixture(),s=f.select();assert.ok(gameDispatchValidationFor(s));if(mode==='expiry')f.advance(200);if(mode==='rollback')f.rollback();if(mode==='limits')f.boundary.maxPlanningAgeMs++;if(mode==='qualifier')f.boundary.observationCurrent=()=>true;if(mode==='validator')f.boundary.validatorRef='changed:validator';if(mode==='prepared')f.f.deny();assert.equal(gameDispatchValidationFor(s),null);
});
test('late host/source withdrawal and reentrant qualification cannot expose stale dispatch metadata',()=>{
 for(const mode of ['source','configuration','reentrant']){const f=fixture();let selection:ReturnType<typeof f.select>|undefined;f.boundary.observationCurrent=()=>{if(mode==='source')f.f.deny();if(mode==='configuration')f.boundary.maxPlanningFrameDelta++;if(mode==='reentrant'&&selection)selection.isCurrent();return true;};selection=f.select();if(mode==='reentrant'){assert.equal(selection.status,'selected');assert.equal(gameDispatchValidationFor(selection),null);}else assert.equal(selection.status,'unavailable');}
});
test('hostile observation getters/proxies/cycles cannot execute or donate model-authored dispatch identity',()=>{
 const f=fixture();let calls=0;const getter={...f.fresh};Object.defineProperty(getter,'scope',{enumerable:true,get(){calls++;return f.fresh.scope;}});const cyclic:any={...f.fresh};cyclic.self=cyclic;for(const raw of [getter,new Proxy(f.fresh,{}),cyclic,{...f.fresh,grant:true}])assert.equal(selectGameDispatchValidation(f.game,f.binding,f.decision,f.proposal,raw as G.GameObservation,f.boundary).status,'unavailable');assert.equal(calls,0);
});
