import assert from "node:assert/strict"; import { test } from "node:test"; import { FixtureInferenceProvider } from "../src/inference/fixture.ts"; import { buildCanonicalPrompt } from "../src/inference/prompt.ts";
const context = { signal: new AbortController().signal };
test("voice instructions extend only trusted policy and remain reflected in the manifest",()=>{
  const input={assistantId:"a",sessionId:"s",interactionId:"i",endpointId:null,userInput:"Keep numbers and uncertainty."};
  const typed=buildCanonicalPrompt(input),voice=buildCanonicalPrompt({...input,voiceMode:true});
  assert.deepEqual(voice.sections.slice(1),typed.sections.slice(1));
  assert.equal(voice.sections[0].trusted,true);assert.match(voice.sections[0].content,/spoken conversation/);
  assert.notEqual(voice.sections[0].contentDigest,typed.sections[0].contentDigest);
  assert.equal(voice.manifest.sections[0].contentDigest,voice.sections[0].contentDigest);
  assert.equal(voice.manifest.sections[0].sourceRef,"policy:spoken-v1");
});
test("runtime self-context is host-owned, bounded, and pinned in interaction state", () => {
  const request = buildCanonicalPrompt({ assistantId: "a", sessionId: "s", interactionId: "i", endpointId: "endpoint", userInput: "hello", runtimeSelfContext: { sourceRevision: "runtime-self-context:test-v1", runtimeStatus: "ready", inputModalities: { text: "active", microphone: "inactive", visual: "notConfigured" }, outputModalities: { text: "active", speechGeneration: "healthy", speechDelivery: "notObserved", presentation: "notConfigured" }, endpointScope: "sessionEndpoint", audienceScope: "authenticatedSession", permissionState: "authenticatedSession", limitations: ["physical audibility is not observed"] } });
  const state = request.sections.find((section) => section.kind === "interactionState");
  assert.equal(state?.trusted, true); assert.equal(state?.sourceRef, "runtime-self-context:v1"); assert.match(state?.content ?? "", /status=ready/); assert.match(state?.content ?? "", /input\.microphone=inactive/); assert.match(state?.content ?? "", /physical audibility is not observed/); assert.equal(request.manifest.sections.find((section) => section.kind === "interactionState")?.sourceRef, "runtime-self-context:v1");
});
test("prepared relationship context stays lower trust and preserves mandatory corrections", () => { const request = buildCanonicalPrompt({ assistantId: "a", sessionId: "s", interactionId: "i", endpointId: null, userInput: "hello", preparedRelationshipContext: { profileRevision: "profile:1", relationshipRevision: "relationship:1", configurationRevision: "config:1", approvedBaseline: ["concise"], criticalCorrections: ["never claim completion"], relevantContext: [], limitations: [] } }); const section = request.sections.find((item) => item.kind === "preparedMemory"); assert.equal(section?.trusted, false); assert.equal(section?.sourceRef, "relationship-context:prepared-v1"); assert.match(section?.content ?? "", /never claim completion/); });
test("inference uses the canonical four-item prepared-context budget", () => { const request = buildCanonicalPrompt({ assistantId: "a", sessionId: "s", interactionId: "i", endpointId: null, userInput: "hello", preparedRelationshipContext: { profileRevision: "profile:1", relationshipRevision: "relationship:1", configurationRevision: "config:1", approvedBaseline: [], criticalCorrections: [], relevantContext: Array.from({ length: 12 }, (_, index) => ({ id: `memory-${String(index).padStart(2, "0")}`, content: `item ${index}`, rank: index })), limitations: [] } }); const content = request.sections.find((item) => item.kind === "preparedMemory")?.content ?? ""; assert.match(content, /memory-00=item 0/); assert.match(content, /memory-03=item 3/); assert.doesNotMatch(content, /memory-04=item 4/); assert.doesNotMatch(content, /memory-11=item 11/); });
test("relational opportunities carry explicit origin without fabricated user speech", () => { const request = buildCanonicalPrompt({ assistantId: "a", sessionId: "s", interactionId: "i", endpointId: "endpoint", origin: "relationalOpportunity" }); const state = request.sections.find((item) => item.kind === "interactionState"); const input = request.sections.find((item) => item.kind === "userInput"); assert.match(state?.content ?? "", /origin=relationalOpportunity/); assert.equal(input?.content, ""); assert.equal(input?.sourceRef, "user-input:empty-v1"); });
test("fixture inference has deterministic section output", async () => { const request = buildCanonicalPrompt({ assistantId: "a", sessionId: "s", interactionId: "i", endpointId: null, userInput: "hello" }); const a = []; for await (const c of new FixtureInferenceProvider().generate(request, context)) a.push(c); assert.equal(a[0].text, "Fixture response: hello"); assert.deepEqual(request.sections.map((section) => section.kind), ["policy", "corePersona", "adaptivePersona", "interactionState", "preparedMemory", "worldContext", "capabilityState", "conversation", "userInput"]); assert.equal(request.manifest.sections.length, 9); });
test("replay fixture inference produces no live output", async () => { const request = buildCanonicalPrompt({ assistantId: "a", sessionId: "s", interactionId: "i", endpointId: null, userInput: "hello", executionMode: "replay" }); const chunks = []; for await (const chunk of new FixtureInferenceProvider().generate(request, context)) chunks.push(chunk); assert.deepEqual(chunks, []); });


test("LS-TEST-134: actual canonical request labels conservative counts and bounds legacy optional Unicode context", () => {
  const view = { approvedBaseline: ["Keep the established approved baseline."], criticalCorrections: ["The current subject is Python."], relevantContext: [{ id: "long", content: "Python " + "界".repeat(200), rank: 0 }, { id: "short", content: "Python examples should show the result.", rank: 1 }], profileRevision: "p:1", relationshipRevision: "r:1", configurationRevision: "c:1", limitations: [] };
  const request = buildCanonicalPrompt({ assistantId: "a", sessionId: "s", interactionId: "i", endpointId: null, userInput: "Explain Python", preparedRelationshipContext: view });
  const memory = request.sections.find(section => section.kind === "preparedMemory")!;
  assert.match(memory.content, /established approved baseline/); assert.match(memory.content, /current subject is Python/); assert.match(memory.content, /examples should show/);
  assert.doesNotMatch(memory.content, /界/);
  assert.equal(memory.tokenCount, Buffer.byteLength(memory.content));
  assert.equal(request.manifest.tokenizer, "estimate:utf8-bytes-upper-bound-v1");
});
