import assert from "node:assert/strict"; import { test } from "node:test"; import { TraceOutbox } from "../src/observability/outbox.ts";
test("trace outbox preserves order and deduplicates receipts", () => { const o = new TraceOutbox(); o.append({ id: "2", traceId: "t", sequence: 2, payload: {} }); o.append({ id: "1", traceId: "t", sequence: 1, payload: {} }); o.append({ id: "1", traceId: "t", sequence: 1, payload: { changed: true } }); assert.deepEqual(o.pending().map((e) => e.id), ["1", "2"]); });
test('bounded outage queue refuses new events without displacing retained evidence or changing source aliases',()=>{
 const outbox=new TraceOutbox({maxEvents:2,maxBytes:512,maxEventBytes:256}),first={id:'first',traceId:'source',sequence:2,payload:{nested:{value:'original'}}};
 assert.equal(outbox.append(first),'queued');first.payload.nested.value='mutated';assert.equal(outbox.append({id:'second',traceId:'source',sequence:1,payload:{}}),'queued');assert.equal(outbox.append({id:'third',traceId:'source',sequence:0,payload:{}}),'overflow');assert.deepEqual(outbox.pending().map(e=>e.id),['second','first']);assert.deepEqual(outbox.pending()[1]!.payload,{nested:{value:'original'}});assert.equal(outbox.usage().refusedEvents,1);assert.ok(outbox.usage().bytes<=512);assert.equal(outbox.usage().complete,false);
 outbox.pending()[0]!.payload.changed=true;assert.deepEqual(outbox.pending()[0]!.payload,{});outbox.close();assert.deepEqual(outbox.pending(),[]);assert.equal(outbox.usage().bytes,0);assert.equal(outbox.append(first),'closed');
});
test('byte pressure, malformed or executable data stays bounded without invoking code',()=>{
 const outbox=new TraceOutbox({maxEvents:128,maxBytes:256,maxEventBytes:256}),event=(id:string)=>({id,traceId:'t',sequence:0,payload:{data:'x'.repeat(80)}});
 assert.equal(outbox.append(event('a')),'queued');assert.equal(outbox.append(event('b')),'overflow');let touched=0;const bad:any[]=[{...event('c'),payload:{get value(){touched++;return 'secret';}}},new Proxy(event('d'),{get(){touched++;throw Error('untrusted');}}),{...event('e'),payload:{media:new Uint8Array([1])}},{...event('f'),payload:{value:NaN}},{...event('g'),payload:{value:Array(3)}},{...event('h'),sequence:-1},{...event('i'),payload:{data:'x'.repeat(32769)}}];
 const cycle:any={};cycle.self=cycle;bad.push({...event('cycle'),payload:cycle});for(const input of bad)assert.equal(outbox.append(input),'invalid');assert.equal(touched,0);assert.equal(outbox.pending().length,1);assert.throws(()=>new TraceOutbox({maxEvents:0}));assert.throws(()=>new TraceOutbox({maxBytes:Infinity}));
});
