import assert from "node:assert/strict";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { RealtimePcmReplaySource, ReplaySourceError, type ReplayAudioInput } from "../src/voice/replay-source.ts";
import { validateSttInput } from "../src/voice/ports.ts";

const format = { encoding: "pcm_s16le" as const, sampleRateHz: 16000 as const, channels: 1 as const };
const fixtureRef = "fixture:assistant-neutral-speech:v1";
async function fixture(bytes = 6400): Promise<{ dir: string; path: string }> { const dir = await mkdtemp(join(tmpdir(), "lifestream-neutral-audio-")); const path = join(dir, "neutral-speech.pcm"); const pcm = Buffer.alloc(bytes); for (let i = 0; i < pcm.length; i += 2) pcm.writeInt16LE(Math.round(Math.sin(i / 17) * 400), i); await writeFile(path, pcm); return { dir, path }; }
async function collect(source: RealtimePcmReplaySource): Promise<ReplayAudioInput[]> { const items: ReplayAudioInput[] = []; for await (const item of source.stream()) items.push(item); return items; }

test("replay enters the canonical SttInput boundary with identity, provenance, pacing, and terminal", async () => { const f = await fixture(); try { const sleeps: number[] = []; const traces: string[] = []; const source = new RealtimePcmReplaySource({ fixturePath: f.path, fixtureRef, format, endpointId: "endpoint-1", sessionId: "session-1", interactionId: "interaction-1", audioInputId: "audio-1", frameSamples: 1600, now: (() => { let n = 1000; return () => n; })(), sleep: async (ms) => { sleeps.push(ms); }, onTrace: (event) => traces.push(event.phase) }); const items = await collect(source); assert.equal(items.length, 3); assert.equal(items[0]?.type, "frame"); assert.equal(items[0]?.metadata.sourceType, "realtimePcmReplay"); assert.equal(items[0]?.metadata.fixtureRef, fixtureRef); assert.equal(items[1]?.frame.sampleOffset, 1600); assert.equal(items[2]?.type, "end"); assert.equal(items[2]?.nextSequence, 2); assert.equal(items[2]?.sampleCount, 3200); assert.equal(sleeps.length, 1); assert.deepEqual(traces, ["started", "frame", "frame", "ended"]); assert.deepEqual(await validateSttInput(source.stream(), format), { frames: 2, samples: 3200 }); } finally { await rm(f.dir, { recursive: true, force: true }); } });

test("replay is deterministic and stops without fabricating an end after cancellation", async () => { const f = await fixture(9600); try { const make = () => new RealtimePcmReplaySource({ fixturePath: f.path, fixtureRef, format, endpointId: "endpoint-1", sessionId: "session-1", interactionId: "interaction-1", audioInputId: "audio-1", pace: false, now: () => 1000 }); const one = await collect(make()); const two = await collect(make()); assert.deepEqual(one, two); const source = make(); const iterator = source.stream(); assert.equal((await iterator.next()).value?.type, "frame"); source.stop(); assert.equal((await iterator.next()).done, true); } finally { await rm(f.dir, { recursive: true, force: true }); } });

test("replay rejects malformed raw and WAV input before it reaches STT", async () => { const f = await fixture(4); try { await writeFile(f.path, Buffer.alloc(3)); const source = new RealtimePcmReplaySource({ fixturePath: f.path, fixtureRef, format, endpointId: "endpoint-1", sessionId: "session-1", interactionId: "interaction-1", audioInputId: "audio-1", pace: false }); await assert.rejects(() => collect(source), ReplaySourceError); } finally { await rm(f.dir, { recursive: true, force: true }); } });

test("fault-capable replay cases remain bounded at the canonical validator", async () => { const base = { frameId: "f", sequence: 0, format, sampleOffset: 0, sampleCount: 2, dataBase64: "AAAA" }; const cases: Record<string, ReplayAudioInput[]> = { "dropped-frame": [{ type: "frame", audioInputId: "a", frame: { ...base, sequence: 1 } }, { type: "end", audioInputId: "a", nextSequence: 2, sampleCount: 2, metadata: {} as never }], "duplicate-frame": [{ type: "frame", audioInputId: "a", frame: base }, { type: "frame", audioInputId: "a", frame: base }, { type: "end", audioInputId: "a", nextSequence: 2, sampleCount: 4, metadata: {} as never }], "out-of-order-offset": [{ type: "frame", audioInputId: "a", frame: base }, { type: "frame", audioInputId: "a", frame: { ...base, frameId: "g", sequence: 1, sampleOffset: 9 } }, { type: "end", audioInputId: "a", nextSequence: 2, sampleCount: 4, metadata: {} as never }] }; for (const [name, input] of Object.entries(cases)) await assert.rejects(() => validateSttInput((async function* () { yield* input; })(), format), { message: name === "out-of-order-offset" ? /sample offset mismatch/ : /audio sequence gap/ }); });
