import assert from "node:assert/strict";
import { test } from "node:test";
import { createCapabilityProposal, SkillExecutor, validateSkill, type Skill } from "../src/skills/skill.ts";

const baseSkill = (status: Skill["status"] = "active"): Skill => ({ schemaVersion: "1.0.0", skillId: "skill-1", assistantId: "assistant-1", revision: 1, version: "1.0.0", status, name: "Greeting", description: "A bounded greeting", requiredCapabilities: [{ capabilityId: "message.send", version: "1.0.0" }], preconditions: [{ type: "inputPresent", pointer: "/text" }], maxSteps: 1, steps: [{ stepId: "step-1", capabilityId: "message.send", capabilityVersion: "1.0.0", inputBindings: [{ targetPointer: "/text", source: { type: "input", pointer: "/text" } }], onMissingInput: "reject" }], outputBindings: [], failurePolicy: "stop", compensationGuidance: "Stop and request review.", provenance: {}, createdAt: "2026-09-07T00:00:00Z", createdBy: "human", activationRef: status === "active" ? { reference: "review-1" } : null });

test("active Skill executes only current available capabilities", () => { const calls: unknown[] = []; const result = new SkillExecutor((id, version) => id === "message.send" && version === "1.0.0", (invocation) => { calls.push(invocation); return { lifecycle: "succeeded", output: { sent: true } }; }).execute(baseSkill(), { text: "hello" }, "execution-1"); assert.equal(result.status, "succeeded"); assert.equal(calls.length, 1); });
test("missing capability, invalid input, and non-active Skill stop", () => { assert.equal(new SkillExecutor(() => false, () => ({ lifecycle: "succeeded" })).execute(baseSkill(), { text: "hello" }, "e").reason, "capability_missing"); assert.equal(new SkillExecutor(() => true, () => ({ lifecycle: "succeeded" })).execute(baseSkill(), {}, "e").reason, "precondition_failed"); assert.equal(new SkillExecutor(() => true, () => ({ lifecycle: "succeeded" })).execute(baseSkill("draft"), { text: "hello" }, "e").reason, "skill_not_active"); });
test("approval and unknown outcomes stop without compensation or retry", () => { for (const lifecycle of ["approvalRequired", "outcomeUnknown"] as const) { const result = new SkillExecutor(() => true, () => ({ lifecycle })).execute(baseSkill(), { text: "hello" }, "e"); assert.equal(result.status, lifecycle); assert.deepEqual(result.completedStepIds, []); } });
test("drafts and proposals cannot carry activation, secrets, or authority", () => { const draft = baseSkill("draft"); assert.doesNotThrow(() => validateSkill(draft)); assert.throws(() => validateSkill({ ...draft, activationRef: { reference: "bad" } }), /activation/); assert.throws(() => createCapabilityProposal({ proposalId: "p", assistantId: "a", capabilityId: "message.send", userValue: "x", interactionRef: "i", requiredData: ["oauth token"], effects: [], risks: [], candidateProviders: [] }), /forbidden/); assert.equal(createCapabilityProposal({ proposalId: "p", assistantId: "a", capabilityId: "message.send", userValue: "x", interactionRef: "i", requiredData: [], effects: [], risks: [], candidateProviders: [] }).status, "inert"); });
