import assert from "node:assert/strict";
import { test } from "node:test";
import { createCapabilityProposal, SkillExecutor, validateSkill, type Skill } from "../src/skills/skill.ts";

const call=()=>({requestId:"request",correlationId:"correlation",deadlineAt:new Date(Date.now()+5000).toISOString(),executionMode:"live" as const,signal:new AbortController().signal,isCurrent:()=>true});
const baseSkill = (status: Skill["status"] = "active"): Skill => ({ schemaVersion: "1.0.0", skillId: "skill-1", assistantId: "assistant-1", revision: 1, version: "1.0.0", status, name: "Greeting", description: "A bounded greeting", requiredCapabilities: [{ capabilityId: "message.send", version: "1.0.0" }], preconditions: [{ type: "inputPresent", pointer: "/text" }], maxSteps: 1, steps: [{ stepId: "step-1", capabilityId: "message.send", capabilityVersion: "1.0.0", inputBindings: [{ targetPointer: "/text", source: { type: "input", pointer: "/text" } }], onMissingInput: "reject" }], outputBindings: [], failurePolicy: "stop", compensationGuidance: "Stop and request review.", provenance: {}, createdAt: "2026-09-07T00:00:00Z", createdBy: "human", activationRef: status === "active" ? { reference: "review-1" } : null });

test("active Skill executes only current available capabilities", async () => { const calls: unknown[] = []; const result = (await new SkillExecutor(async (id, version) => id === "message.send" && version === "1.0.0", async (invocation) => { calls.push(invocation); return { lifecycle: "succeeded", output: { sent: true } }; }).execute(baseSkill(), { text: "hello" }, "execution-1",call())); assert.equal(result.status, "succeeded"); assert.equal(calls.length, 1); });
test("missing capability, invalid input, and non-active Skill stop", async () => { assert.equal((await new SkillExecutor(async () => false, async () => ({ lifecycle: "succeeded" })).execute(baseSkill(), { text: "hello" }, "e",call())).reason, "capability_missing"); assert.equal((await new SkillExecutor(async () => true, async () => ({ lifecycle: "succeeded" })).execute(baseSkill(), {}, "e",call())).reason, "precondition_failed"); assert.equal((await new SkillExecutor(async () => true, async () => ({ lifecycle: "succeeded" })).execute(baseSkill("draft"), { text: "hello" }, "e",call())).reason, "skill_not_active"); });
test("approval and unknown outcomes stop without compensation or retry", async () => { for (const lifecycle of ["approvalRequired", "outcomeUnknown"] as const) { const result = (await new SkillExecutor(async () => true, async () => ({ lifecycle })).execute(baseSkill(), { text: "hello" }, "e",call())); assert.equal(result.status, lifecycle); assert.deepEqual(result.completedStepIds, []); } });
test("drafts and proposals cannot carry activation, secrets, or authority", () => { const draft = baseSkill("draft"); assert.doesNotThrow(() => validateSkill(draft)); assert.throws(() => validateSkill({ ...draft, activationRef: { reference: "bad" } }), /activation/); assert.throws(() => createCapabilityProposal({ proposalId: "p", assistantId: "a", capabilityId: "message.send", userValue: "x", interactionRef: "i", requiredData: ["oauth token"], effects: [], risks: [], candidateProviders: [] }), /forbidden/); assert.equal(createCapabilityProposal({ proposalId: "p", assistantId: "a", capabilityId: "message.send", userValue: "x", interactionRef: "i", requiredData: [], effects: [], risks: [], candidateProviders: [] }).status, "inert"); });

test('asynchronous Skill steps preserve invocation identities and stop before dependent effects on uncertainty',async()=>{
 const skill=baseSkill();skill.maxSteps=2;skill.steps.push({...skill.steps[0]!,stepId:'step-2'});const calls:string[]=[];
 const result=await new SkillExecutor(async()=>true,async invocation=>{calls.push(invocation.invocationId);await Promise.resolve();return {lifecycle:'outcomeUnknown'};}).execute(skill,{text:'hello'},'execution',call());
 assert.deepEqual(calls,['execution:step-1']);assert.deepEqual(result.invocationIds,calls);assert.equal(result.status,'outcomeUnknown');assert.equal(result.stoppedAtStepId,'step-1');
});
test('Skill input is fixed before asynchronous capability discovery',async()=>{
 const source={text:'original'};const result=await new SkillExecutor(async()=>{source.text='changed';return true;},async invocation=>{assert.deepEqual(invocation.input,{text:'original'});return {lifecycle:'succeeded'};}).execute(baseSkill(),source,'execution',call());assert.equal(result.status,'succeeded');
});
