import assert from "node:assert/strict";
import { test } from "node:test";
import { buildDatasetManifest, routeAdapter, validateAdapterEligibility, type AdapterManifest } from "../src/ports/training.ts";

const record = (split: "train" | "validation" | "test") => ({ recordId: `record-${split}`, sourceId: `source-${split}`, sourceRevision: "r1", sourceFamily: "fixture", subjectId: "subject-1", relationshipId: "relationship-1", sensitivity: "ordinary" as const, purpose: "training" as const, consent: "approved" as const, contentDigest: `digest-${split}`, split, transformed: "normalized" as const, dependencyIds: [] });
const manifest: AdapterManifest = { artifactId: "adapter-1", artifactRevision: "1", baseModel: "fixture-model", baseModelRevision: "r1", tokenizer: "fixture-tokenizer", chatTemplate: "fixture-chat", runtime: "fixture-runtime", quantization: "none", datasetDigest: "dataset-digest", datasetLineage: ["source-r1"], trainingSettings: { epochs: 1 }, toolVersions: { trainer: "fixture-1" }, resourceEvidence: ["fixture-only"], evaluations: ["held-out-1"], approvedSubjectId: "subject-1", approvedAssistantId: "assistant-1", approvedAudience: "private", activationDependency: "human-review", revocationDependency: "source-r1", status: "approved" };

test("dataset readiness requires consented independent splits and remains fixture-safe", () => { const dataset = buildDatasetManifest({ datasetId: "dataset-1", revision: 1, digest: "dataset-digest", records: [record("train"), record("validation"), record("test")], exclusions: ["nonconsenting-source"], syntheticGenerator: "fixture-generator-v1", createdAt: "2026-09-11T00:00:00Z", exportPolicy: "fixture-only" }); assert.equal(dataset.status, "prepared"); assert.throws(() => buildDatasetManifest({ ...dataset, status: undefined as never, records: [record("train"), record("validation")] }), /train\/validation\/test/); });
test("adapter routing requires exact authenticated scope and quarantines revocation", () => { const request = { assistantId: "assistant-1", subjectId: "subject-1", audience: "private" as const, baseModel: "fixture-model", baseModelRevision: "r1", tokenizer: "fixture-tokenizer", chatTemplate: "fixture-chat", datasetDigest: "dataset-digest" }; assert.deepEqual(validateAdapterEligibility(manifest, request), { eligible: true }); assert.equal(routeAdapter(manifest, { ...request, audience: "shared" }).route, "fallback"); assert.equal(routeAdapter(manifest, { ...request, revokedDependencies: ["source-r1"] }).route, "fallback"); });
