import assert from 'node:assert/strict';
import {test} from 'node:test';
import {buildDatasetManifest,trainingContentDigest,TrainingRegistry,validateDatasetManifest,type AdapterManifest,type AdapterRouteRequest,type DatasetAuthority,type DatasetRecord} from '../src/ports/training.ts';
import {FixtureAdapterSession} from '../../providers-fixture/src/training.ts';
const scope={subjectId:'subject-1',assistantId:'assistant-1',relationshipId:'relationship-1'};
const records:DatasetRecord[]=(['train','validation','test'] as const).map((split,n)=>({ ...scope,recordId:`record-${n}`,sourceId:`source-${n}`,sourceRevision:'1',sourceFamily:`family-${n}`,content:`Synthetic independent example ${n}`,contentDigest:trainingContentDigest(`Synthetic independent example ${n}`),consent:'approved',consentRef:'consent:1',purpose:'training',sensitivity:'ordinary',split,transformed:'none',dependencyIds:[`source-${n}:1`,'consent:1']}));
const authority:DatasetAuthority={scope,consents:[{...scope,consentId:'consent',revision:1,sourceRefs:records.map(r=>`${r.sourceId}:1`),purpose:'trainingDataset',status:'approved',grantedBy:scope.subjectId,createdAt:'2026-09-13T00:00:00Z'}],sources:records.map(r=>({id:r.sourceId,revision:r.sourceRevision,family:r.sourceFamily,contentDigest:r.contentDigest,eligible:true}))};
const input={schemaVersion:'2.0.0' as const,datasetId:'dataset',revision:1,records,exclusions:['nonconsenting third-party data'],syntheticGenerator:'authored-test-v1',createdAt:'2026-09-13T00:00:00Z',exportPolicy:'fixture-only' as const};
const artifact=(digest:string):AdapterManifest=>({schemaVersion:'2.0.0',artifactId:'adapter',artifactRevision:'1',kind:'behavioral',baseModel:'fixture-base',baseModelRevision:'1',tokenizer:'fixture-tokenizer:1',chatTemplate:'fixture-template:1',runtime:'fixture-runtime:1',quantization:'none',datasetDigest:digest,datasetLineage:[...new Set(records.flatMap(r=>r.dependencyIds))],trainingSettings:{executed:false},toolVersions:{simulator:'1'},resourceEvidence:['fixture-only:no-training'],evaluations:['contract-only:no-learned-quality'],approvedSubjectId:scope.subjectId,approvedAssistantId:scope.assistantId,approvedAudience:'private',activationDependency:'review:1',revocationDependency:'currency:1',fallback:{baseModel:'fixture-base',baseModelRevision:'1',untouched:true,merged:false},status:'candidate'});
const request=(m:AdapterManifest):AdapterRouteRequest=>({...scope,audience:'private',artifactRevision:m.artifactRevision,baseModel:m.baseModel,baseModelRevision:m.baseModelRevision,tokenizer:m.tokenizer,chatTemplate:m.chatTemplate,runtime:m.runtime,quantization:m.quantization,datasetDigest:m.datasetDigest,activeDependencies:[...m.datasetLineage,m.activationDependency,m.revocationDependency],runtimeSupported:true});
test('versioned dataset recomputes content digest and checks independent source families, content and dependencies',()=>{
 const d=buildDatasetManifest(input,authority);validateDatasetManifest(d,authority);assert.equal(d.digest.length,64);
 for(const mutate of [(x:typeof input)=>{x.records[1]!.sourceFamily=x.records[0]!.sourceFamily;},(x:typeof input)=>{x.records[1]!.content=x.records[0]!.content;x.records[1]!.contentDigest=x.records[0]!.contentDigest;},(x:typeof input)=>{x.records[1]!.dependencyIds.push('shared');x.records[0]!.dependencyIds.push('shared');}]){const x=structuredClone(input);mutate(x);const a=structuredClone(authority);a.sources=x.records.map(r=>({id:r.sourceId,revision:r.sourceRevision,family:r.sourceFamily,contentDigest:r.contentDigest,eligible:true}));assert.throws(()=>buildDatasetManifest(x,a),/leakage/);}
 assert.throws(()=>validateDatasetManifest({...d,digest:'invented'},authority),/digest/);assert.throws(()=>buildDatasetManifest({...input,records:records.slice(0,2)},authority),/bounded/);assert.throws(()=>buildDatasetManifest({...input,records:records.map(r=>({...r,content:'tampered'}))},authority),/content/);assert.throws(()=>buildDatasetManifest(input,{...authority,scope:{...scope,subjectId:'other'}}),/scope/);
 for(const a of [{...authority,consents:[]},{...authority,consents:authority.consents.map(c=>({...c,status:'revoked' as const}))},{...authority,sources:authority.sources.map(s=>({...s,eligible:false}))}])assert.throws(()=>buildDatasetManifest(input,a),/consent|source/);
});
test('registry uses explicit review, exact runtime and current consent, and durable quarantine',()=>{
 const registry=new TrainingRegistry(),d=registry.addDataset(input,authority),m=artifact(d.digest),r=request(m);registry.register(m,authority);assert.equal(registry.route(m.artifactId,r,authority).route,'fallback');assert.throws(()=>registry.approve(m.artifactId,'1',1,authority),/revision/);const approved=registry.approve(m.artifactId,'1',registry.snapshot().revision,authority);assert.equal(registry.route(m.artifactId,r,authority).route,'adapter');
 for(const field of ['subjectId','assistantId','artifactRevision','baseModel','baseModelRevision','tokenizer','chatTemplate','runtime','quantization','datasetDigest'] as const)assert.equal(registry.route(m.artifactId,{...r,[field]:'wrong'},authority).route,'fallback',field);
 for(const audience of ['shared','unknown'] as const)assert.equal(registry.route(m.artifactId,{...r,audience},authority).route,'fallback');assert.equal(registry.route(m.artifactId,{...r,runtimeSupported:false},authority).route,'fallback');assert.equal(registry.route(m.artifactId,{...r,activeDependencies:[]},authority).route,'fallback');assert.equal(registry.route(m.artifactId,r,{...authority,consents:[]}).route,'fallback');assert.equal(approved.fallback.untouched,true);
 registry.invalidate(['consent:1']);assert.throws(()=>registry.exportDataset('dataset',authority),/eligible/);const restored=new TrainingRegistry(registry.snapshot());assert.equal(restored.route(m.artifactId,r,authority).route,'fallback');assert.equal(restored.snapshot().artifacts[0]!.status,'quarantined');restored.invalidate(['source-0'],true);assert.ok(restored.snapshot().datasets[0]!.records.every(r=>r.content===''));
});
test('fixture route switching and revocation clear all three caches and fence pending work',()=>{
 const session=new FixtureAdapterSession(),m={...artifact(buildDatasetManifest(input,authority).digest),status:'approved' as const},r=request(m);assert.equal(session.route(m,r).route,'adapter');for(const c of Object.values(session.caches))c.set('private','payload');let pending=session.begin();assert.equal(session.route(m,r).route,'adapter');assert.equal(pending.signal.aborted,false);session.route(m,{...r,subjectId:'other'});assert.equal(pending.signal.aborted,true);assert.ok(Object.values(session.caches).every(c=>c.size===0));session.route(m,r);pending=session.begin();const fallback=session.route(m,{...r,revokedDependencies:['consent:1']});assert.equal(fallback.route,'fallback');assert.equal(fallback.liveEffects,false);assert.equal(pending.signal.aborted,true);
});
