type DatasetRecord = { recordId: string; sourceId: string; sourceRevision: string; sourceFamily: string; subjectId: string; relationshipId: string; sensitivity: "ordinary" | "sensitive"; purpose: "evaluation" | "training"; consent: "approved" | "excluded"; contentDigest: string; split: "train" | "validation" | "test"; transformed: "none" | "redacted" | "normalized"; dependencyIds: string[] };
type DatasetManifest = { datasetId: string; revision: number; digest: string; records: DatasetRecord[]; exclusions: string[]; syntheticGenerator: string; createdAt: string; exportPolicy: "fixture-only" | "approved-runtime"; status: "prepared" | "quarantined" | "revoked" };
type AdapterManifest = { artifactId: string; artifactRevision: string; baseModel: string; baseModelRevision: string; tokenizer: string; chatTemplate: string; datasetDigest: string; datasetLineage: string[]; approvedSubjectId: string; approvedAssistantId: string; approvedAudience: "private" | "shared" | "unknown"; revocationDependency: string; status: "candidate" | "approved" | "quarantined" | "revoked" };
type AdapterRouteRequest = { assistantId: string; subjectId: string; audience: "private" | "shared" | "unknown"; baseModel: string; baseModelRevision: string; tokenizer: string; chatTemplate: string; datasetDigest: string; revokedDependencies?: string[] };
type AdapterRoute = { route: "adapter" | "fallback"; artifactId?: string; reason: string; cacheInvalidated: boolean; liveEffects: false };
const buildDatasetManifest = (input: Omit<DatasetManifest, "status">): DatasetManifest => { if (!input.records.some((record) => record.split === "train") || !input.records.some((record) => record.split === "validation") || !input.records.some((record) => record.split === "test")) throw new Error("dataset requires train/validation/test splits"); return { ...structuredClone(input), status: "prepared" }; };
const routeAdapter = (manifest: AdapterManifest, request: AdapterRouteRequest): AdapterRoute => { const reason = manifest.status !== "approved" ? `adapter status is ${manifest.status}` : request.audience !== "private" || manifest.approvedAudience !== "private" ? "private adapter requires a private audience" : manifest.approvedAssistantId !== request.assistantId || manifest.approvedSubjectId !== request.subjectId ? "authenticated scope does not match" : manifest.baseModel !== request.baseModel || manifest.baseModelRevision !== request.baseModelRevision || manifest.tokenizer !== request.tokenizer || manifest.chatTemplate !== request.chatTemplate ? "runtime compatibility does not match" : manifest.datasetDigest !== request.datasetDigest ? "dataset digest does not match" : (request.revokedDependencies ?? []).some((dependency) => manifest.datasetLineage.includes(dependency) || dependency === manifest.revocationDependency) ? "adapter dependency is revoked" : ""; return reason ? { route: "fallback", reason, cacheInvalidated: true, liveEffects: false } : { route: "adapter", artifactId: manifest.artifactId, reason: "approved fixture manifest matched", cacheInvalidated: true, liveEffects: false }; };

export type FixtureTrainingProvider = { prepareDataset(input: Omit<DatasetManifest, "status">): DatasetManifest; route(manifest: AdapterManifest, request: AdapterRouteRequest): AdapterRoute };
export const fixtureTrainingProvider: FixtureTrainingProvider = { prepareDataset: buildDatasetManifest, route: routeAdapter };
