export type SemanticState = { schemaVersion: "1.0.0"; stateId: string; interactionTraceId: string; assistantId: string; endpointId: string; sequence: number; effectiveAt: string; expiresAt?: string; source: "runtime" | "behaviorController" | "policyOverride" | "replay"; attention: "none" | "participant" | "object" | "environment" | "task"; attentionTargetRef?: string; engagement: "idle" | "available" | "engaged" | "disengaging"; affect: { valence: number; arousal: number; confidence: number; label?: string }; speechState: "silent" | "listening" | "preparing" | "speaking" | "interrupted"; activity: "idle" | "conversing" | "working" | "waiting" | "notifying" | "error"; urgency: "low" | "normal" | "high" | "critical"; transitionHint?: "immediate" | "smooth" | "endpointDefault" };
export type BehaviorInput = { interaction: "idle" | "listening" | "preparing" | "generating" | "speaking" | "working" | "waiting" | "error"; audioPlaying: boolean; interrupted: boolean; attention?: SemanticState["attention"]; attentionTargetRef?: string; affect: SemanticState["affect"]; policyOverride?: { speechState?: "silent" | "interrupted"; urgency?: SemanticState["urgency"] }; now: string };

export class BehaviorController {
  private sequence = 0; private currentState: SemanticState | undefined;
  private readonly identity: Pick<SemanticState, "stateId" | "interactionTraceId" | "assistantId" | "endpointId">;
  constructor(identity: Pick<SemanticState, "stateId" | "interactionTraceId" | "assistantId" | "endpointId">) { this.identity = identity; }
  update(input: BehaviorInput): SemanticState { const policy = input.policyOverride; const speechState = policy?.speechState ?? (input.interrupted ? "interrupted" : input.audioPlaying ? "speaking" : input.interaction === "listening" ? "listening" : input.interaction === "preparing" ? "preparing" : "silent"); const state: SemanticState = { ...this.identity, schemaVersion: "1.0.0", sequence: ++this.sequence, effectiveAt: input.now, source: policy ? "policyOverride" : "behaviorController", attention: input.attention ?? (input.interaction === "working" ? "task" : "none"), ...(input.attentionTargetRef ? { attentionTargetRef: input.attentionTargetRef } : {}), engagement: input.interaction === "idle" ? "available" : "engaged", affect: structuredClone(input.affect), speechState, activity: input.interaction === "error" ? "error" : input.interaction === "working" ? "working" : input.interaction === "waiting" ? "waiting" : input.interaction === "idle" ? "idle" : "conversing", urgency: policy?.urgency ?? "normal", transitionHint: "endpointDefault", ...(speechState === "speaking" || speechState === "interrupted" ? { expiresAt: new Date(Date.parse(input.now) + 5000).toISOString() } : {}) }; this.currentState = structuredClone(state); return structuredClone(state); }
  current(now: string): SemanticState | undefined { if (!this.currentState) return undefined; if (this.currentState.expiresAt && this.currentState.expiresAt <= now) return this.update({ interaction: "idle", audioPlaying: false, interrupted: false, affect: this.currentState.affect, now }); return structuredClone(this.currentState); }
}
