type TtsRequest = { contractVersion: "2.0.0"; text: string; segmentId: string; format: { encoding: "pcm_s16le"; sampleRateHz: 16000 | 24000 | 48000; channels: 1 | 2 }; voiceProfile: { voiceRef: string; revision: number }; decision: { decisionId: string; revision: number }; delivery: { interactionId: string; segmentId: string; decisionId: string; decisionRevision: number }; deadlineAt: string };
type TtsEvent = { kind: "preAudio"; sequence: number; segmentId: string; decisionId: string; decisionRevision: number; delivery: Record<string, unknown>; disposition: "fullyApplied" | "partiallyApplied"; degradedDimensions: string[]; mappingRevision: string } | { kind: "data"; sequence: number; segmentId: string; frame: { frameId: string; sequence: number; format: TtsRequest["format"]; sampleOffset: number; sampleCount: number; dataBase64: string }; mappingRevision: string } | { kind: "terminal"; sequence: number; segmentId: string; outcome: "succeeded" | "cancelled" | "timedOut" | "failed"; outputSamples: number; frameCount: number; disposition: "fullyApplied" | "partiallyApplied" | "providerFailure" | "cancelled" | "timedOut"; degradedDimensions: string[]; mappingRevision: string };
type TtsCapabilities = { contractVersion: "2.0.0"; supportedDimensions: readonly string[]; degradableDimensions: readonly string[]; supportsStreaming: true; maxOutputSamples: number };
interface TextToSpeechProvider { capabilities(): TtsCapabilities; synthesize(request: TtsRequest, signal?: AbortSignal): AsyncIterable<TtsEvent>; }
const PROTOCOL_VERSION = "voxcpm.loopback.v1" as const;
type ProtocolRequest = { protocolVersion: typeof PROTOCOL_VERSION; requestId: string; correlationId: string; interactionId: string; deadlineAt: string; voiceBundleKey: string; voiceBundleRevision: number; text: string; delivery: Record<string, unknown>; format: { encoding: "pcm_s16le"; sampleRateHz: 48000; channels: 1 } };
type ProtocolEvent = { kind: "preAudio"; sequence: 0; requestId: string; correlationId: string; voiceBundleRevision: number; requestedDelivery: Record<string, unknown>; appliedDelivery: Record<string, unknown>; degradedDimensions: string[]; mappingRevision: string; effectiveSynthesis: Record<string, unknown>; format: ProtocolRequest["format"]; runtimeRevision: string; modelRevision: string } | { kind: "data"; sequence: number; sampleOffset: number; sampleCount: number; dataBase64: string; format: ProtocolRequest["format"] } | { kind: "terminal"; sequence: number; outcome: "completed" | "cancelled" | "deadlineExceeded" | "retryableProviderFailure" | "nonRetryableProviderFailure" | "malformedRequest" | "unsupportedRequest" | "providerUnavailable"; outputSamples: number; frameCount: number };
const parseNdjson = (body: string): ProtocolEvent[] => body.split("\n").map((line) => line.trim()).filter(Boolean).map((line) => JSON.parse(line) as ProtocolEvent);
const validateProtocolEvents = (events: readonly ProtocolEvent[]): void => { if (!events.length || events[0]?.kind !== "preAudio" || events.at(-1)?.kind !== "terminal") throw new Error("protocol lifecycle invalid"); events.forEach((event, index) => { if (event.sequence !== index) throw new Error("protocol sequence invalid"); }); };

export type VoxCpmOptions = { baseUrl: string; voiceBundleKey: string; voiceBundleRevision: number; runtimeRevision: string; modelRevision: string; mappingRevision: string; fetch?: typeof globalThis.fetch };
export class VoxCpmProvider implements TextToSpeechProvider {
  private readonly options: VoxCpmOptions; private readonly requestFetch: typeof globalThis.fetch;
  constructor(options: VoxCpmOptions) { this.options = options; this.requestFetch = options.fetch ?? globalThis.fetch; }
  capabilities(): TtsCapabilities { return { contractVersion: "2.0.0", supportedDimensions: ["affect", "urgency", "deliveryMode", "pace", "energy"], degradableDimensions: ["affect", "pace", "energy"], supportsStreaming: true, maxOutputSamples: 48000 }; }
  async *synthesize(request: TtsRequest, signal?: AbortSignal): AsyncIterable<TtsEvent> {
    const body: ProtocolRequest = { protocolVersion: PROTOCOL_VERSION, requestId: `${request.delivery.interactionId}:${request.segmentId}`, correlationId: request.decision.decisionId, interactionId: request.delivery.interactionId, deadlineAt: request.deadlineAt, voiceBundleKey: this.options.voiceBundleKey, voiceBundleRevision: this.options.voiceBundleRevision, text: request.text, delivery: request.delivery, format: { encoding: "pcm_s16le", sampleRateHz: 48000, channels: 1 } };
    let response: Response;
    try { response = await this.requestFetch(`${this.options.baseUrl}/v1/tts/synthesize`, { method: "POST", headers: { "content-type": "application/json", accept: "application/x-ndjson" }, body: JSON.stringify(body), ...(signal ? { signal } : {}) }); } catch { yield { kind: "terminal", sequence: 0, segmentId: request.segmentId, outcome: signal?.aborted ? "cancelled" : "failed", outputSamples: 0, frameCount: 0, disposition: signal?.aborted ? "cancelled" : "providerFailure", degradedDimensions: [], mappingRevision: this.options.mappingRevision }; return; }
    if (!response.ok || !response.body) { yield { kind: "terminal", sequence: 0, segmentId: request.segmentId, outcome: "failed", outputSamples: 0, frameCount: 0, disposition: "providerFailure", degradedDimensions: [], mappingRevision: this.options.mappingRevision }; return; }
    const events = parseNdjson(await response.text()); validateProtocolEvents(events);
    for (const event of events) yield this.mapEvent(event, request);
  }
  private mapEvent(event: ProtocolEvent, request: TtsRequest): TtsEvent { if (event.kind === "preAudio") return { kind: "preAudio", sequence: 0, segmentId: request.segmentId, decisionId: request.decision.decisionId, decisionRevision: request.decision.revision, delivery: structuredClone(request.delivery), disposition: event.degradedDimensions.length ? "partiallyApplied" : "fullyApplied", degradedDimensions: event.degradedDimensions as never[], mappingRevision: event.mappingRevision }; if (event.kind === "data") return { kind: "data", sequence: event.sequence, segmentId: request.segmentId, frame: { frameId: `${request.segmentId}:${event.sequence}`, sequence: event.sequence - 1, format: request.format, sampleOffset: event.sampleOffset, sampleCount: event.sampleCount, dataBase64: event.dataBase64 }, mappingRevision: this.options.mappingRevision }; return { kind: "terminal", sequence: event.sequence, segmentId: request.segmentId, outcome: event.outcome === "completed" ? "succeeded" : event.outcome === "cancelled" ? "cancelled" : event.outcome === "deadlineExceeded" ? "timedOut" : "failed", outputSamples: event.outputSamples, frameCount: event.frameCount, disposition: event.outcome === "completed" ? "fullyApplied" : event.outcome === "cancelled" ? "cancelled" : event.outcome === "deadlineExceeded" ? "timedOut" : "providerFailure", degradedDimensions: [], mappingRevision: this.options.mappingRevision }; }
}
