import {createHash,randomUUID} from 'node:crypto';
import {createContractValidator} from '@lifestream/contracts';
import {defaultTopics,dimensions,experienceBounds,type ExperienceScope,type ExperiencePolicy,type Source,type State,type Item,type Episode,type Job,type ReflectionResult,type Lineage,type Selection,type Dimension} from '@lifestream/contracts/experience';
import type {Database} from './database.ts';
const digest=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
const key=(s:ExperienceScope)=>digest([s.principalId,s.assistantId,s.relationshipId]);
const validator=createContractValidator(),schema='https://lifestream.dev/contracts/experiential-learning/1.0.0';
function assert(condition:unknown,reason:string):asserts condition{if(!condition)throw new Error(reason);}
const validate=(type:string,value:unknown)=>assert(validator.validate(schema+'#/$defs/'+type,value).valid,'invalid_'+type);
const stamp=(n:number)=>new Date(n).toISOString();
export class ExperienceRepository{
 private database:Database;private now:()=>number;
 constructor(database:Database,now:()=>number=Date.now){this.database=database;this.now=now;}
 scopes():ExperienceScope[]{return this.database.connection.prepare('SELECT scope_json FROM experience_state LIMIT 256').all().map(x=>JSON.parse(String(x.scope_json)));}
 read(scope:ExperienceScope):State{validate('Scope',scope);const row=this.database.connection.prepare('SELECT payload_json FROM experience_state WHERE scope_key=?').get(key(scope));if(row)return JSON.parse(String(row.payload_json));return {recordType:'experienceState',schemaVersion:'1.0.0',scope,revision:0,epoch:0,configuration:{recordType:'configuration',revision:0,enabled:false,frozen:false,retention:'sourceBound',processingPolicyRevision:0,bounds:{...experienceBounds},topicPolicies:{...defaultTopics}},items:[],imprints:dimensions.map(d=>({dimension:d,seed:0,learned:0,value:0,seedRevision:0,revision:0,contributingEpisodes:[],confidence:0,processingPolicyRevision:0})),funnel:{eligible:0,admitted:0,calls:0,failures:0,skips:0,noChange:0,published:0,considered:0,selected:0,outputs:0},lastReason:'disabled',lastEligibleEpisode:null};}
 private save(state:State){validate('State',state);this.database.connection.prepare('INSERT INTO experience_state VALUES (?,?,?,?) ON CONFLICT(scope_key) DO UPDATE SET revision=excluded.revision,payload_json=excluded.payload_json').run(key(state.scope),JSON.stringify(state.scope),state.revision,JSON.stringify(state));}
 private change(scope:ExperienceScope,expected:number|undefined,fn:(s:State)=>void):State{return this.database.transaction(()=>{const s=this.read(scope);if(expected!==undefined)assert(s.revision===expected,'experience_revision_conflict');fn(s);s.revision++;this.save(s);return s;});}
 private history(s:State,operation:Lineage['operation'],changes:Lineage['changes'],sourceRefs:string[],jobId:string|null,before:Item[]=[],summary=''){const line:Lineage={id:randomUUID(),revision:s.revision+1,operation,at:stamp(this.now()),jobId,sourceRefs:[...new Set(sourceRefs)],summary:summary.slice(0,600),changes,reversed:false,originOmittedFromModel:true};validate('Lineage',line);this.database.connection.prepare('INSERT INTO experience_lineage VALUES (?,?,?,?,?)').run(key(s.scope),line.id,this.now(),JSON.stringify(line),JSON.stringify(before));return line;}
 private allLineage(scope:ExperienceScope):Lineage[]{return this.database.connection.prepare('SELECT payload_json FROM experience_lineage WHERE scope_key=? ORDER BY at_ms DESC,rowid DESC').all(key(scope)).map(x=>JSON.parse(String(x.payload_json)));}
 lineage(scope:ExperienceScope):Lineage[]{return this.allLineage(scope).slice(0,128);}
 episodes(scope:ExperienceScope):Episode[]{return this.database.connection.prepare('SELECT payload_json FROM experience_episodes WHERE scope_key=? ORDER BY rowid DESC LIMIT 256').all(key(scope)).map(x=>JSON.parse(String(x.payload_json)));}
 jobs(scope:ExperienceScope):Job[]{return this.database.connection.prepare('SELECT payload_json FROM experience_jobs WHERE scope_key=? ORDER BY rowid DESC LIMIT 32').all(key(scope)).map(x=>JSON.parse(String(x.payload_json)));}
 private saveJob(job:Job,epoch:number){validate('Job',job);this.database.connection.prepare('INSERT INTO experience_jobs VALUES (?,?,?,?) ON CONFLICT(scope_key,id) DO UPDATE SET payload_json=excluded.payload_json').run(key(job.scope),job.id,epoch,JSON.stringify(job));}
 private cancelJobs(scope:ExperienceScope,reason:string){for(const row of this.database.connection.prepare('SELECT id,epoch,payload_json FROM experience_jobs WHERE scope_key=?').all(key(scope))){const j:Job=JSON.parse(String(row.payload_json));if(j.state==='queued'||j.state==='running'){j.state='cancelled';j.reason=reason;this.saveJob(j,Number(row.epoch));}}}
 configure(scope:ExperienceScope,expected:number,input:{enabled:boolean;frozen:boolean;retention:'sourceBound';topicPolicies:State['configuration']['topicPolicies']},policy:ExperiencePolicy){assert(!input.enabled||policy.allowed&&policy.revision>0,'retained_processing_policy_required');return this.change(scope,expected,s=>{if(input.enabled)for(const i of s.imprints)if(i.value!==0){const d=policy.dimensions[i.dimension];assert(d&&i.value>=d.minimum&&i.value<=d.maximum,'existing_imprint_outside_profile');}s.configuration={...s.configuration,...input,revision:s.configuration.revision+1,processingPolicyRevision:policy.revision};s.epoch++;s.lastReason=input.enabled?(input.frozen?'frozen':'enabled'):'disabled';this.cancelJobs(scope,'policy_changed');this.history(s,'configure',[],[],null);});}
 seed(scope:ExperienceScope,expected:number,dimension:Dimension,value:number,policy:ExperiencePolicy){const allowed=policy.dimensions[dimension];assert(allowed&&Number.isFinite(value)&&Math.abs(value)<=1&&value>=allowed.minimum&&value<=allowed.maximum,'dimension_not_allowed');return this.change(scope,expected,s=>{const imprint=s.imprints.find(i=>i.dimension===dimension)!;assert(Math.abs(value+imprint.learned)<=1&&value+imprint.learned>=allowed.minimum&&value+imprint.learned<=allowed.maximum,'imprint_range');const delta=value-imprint.seed;imprint.seed=value;imprint.value=value+imprint.learned;imprint.seedRevision++;imprint.revision++;imprint.confidence=1;imprint.processingPolicyRevision=policy.revision;s.epoch++;this.cancelJobs(scope,'seed_changed');this.history(s,'seed',[{dimension,delta,inverse:-delta,episodeRefs:[],confidence:1}],[],null);});}
 enqueue(scope:ExperienceScope,sources:Source[],reason:Episode['eligibleReason'],policy:ExperiencePolicy):Job|null{
  const state=this.read(scope);if(!state.configuration.enabled||state.configuration.frozen||!policy.allowed||policy.revision!==state.configuration.processingPolicyRevision||!sources.length)return null;
  sources.forEach(s=>validate('Source',s));assert(sources.length<=16,'episode_bound');const sourceDigest=digest(sources.map(({id,revision,digest:d})=>[id,revision,d]));const independence=digest(sources.map(s=>s.content.trim().toLowerCase().replace(/\s+/g,' ')).sort());
  if(this.episodes(scope).some(e=>e.independence===independence))return null;
  const episodes=this.episodes(scope);if(episodes.length>=256){this.change(scope,undefined,s=>{s.lastReason='episode_capacity';s.funnel.skips++;});return null;}const pending=this.jobs(scope).filter(j=>j.state==='queued'||j.state==='running');if(pending.length>=8)return null;
  return this.database.transaction(()=>{const s=this.read(scope),id=digest([key(scope),sourceDigest]),episode:Episode={recordType:'episode',id,scope,sourceRefs:sources.map(x=>x.id),sourceDigest,independence,occurredAt:stamp(this.now()),eligibleReason:reason,state:'retained'};validate('Episode',episode);this.database.connection.prepare('INSERT INTO experience_episodes VALUES (?,?,?,?)').run(key(scope),id,independence,JSON.stringify(episode));const job:Job={recordType:'job',id,scope,policyRevision:s.configuration.revision,state:'queued',attempts:0,episodeRefs:[id],createdAt:stamp(this.now()),eligibleAt:stamp(this.now()+s.configuration.bounds.idleMs),reason:'idle_debounce',providerRevision:null,inputTokens:null,outputTokens:null,queueMs:null,elapsedMs:null};this.saveJob(job,s.epoch);s.funnel.eligible++;s.lastEligibleEpisode=id;s.lastReason='queued';s.revision++;this.save(s);return job;});
 }

 enqueueConsolidation(scope:ExperienceScope,policy:ExperiencePolicy):Job|null{
  const s=this.read(scope);if(!s.configuration.enabled||s.configuration.frozen||!policy.allowed||policy.revision!==s.configuration.processingPolicyRevision||!s.items.some(i=>['open','deferred'].includes(i.disposition)&&Math.max(Date.parse(i.reconsiderAfter),Date.parse(i.lastEvaluatedAt)+86400000)<=this.now()))return null;
  if(this.jobs(scope).some(j=>j.state==='queued'||j.state==='running'))return null;
  const id=digest([key(scope),'dreaming',stamp(this.now()).slice(0,10)]);if(this.database.connection.prepare('SELECT 1 FROM experience_jobs WHERE scope_key=? AND id=?').get(key(scope),id))return null;
  const episodeRefs=this.episodes(scope).filter(e=>e.state==='retained').slice(0,16).map(e=>e.id);if(!episodeRefs.length)return null;
  const job:Job={recordType:'job',id,scope,policyRevision:s.configuration.revision,state:'queued',attempts:0,episodeRefs,createdAt:stamp(this.now()),eligibleAt:stamp(this.now()+s.configuration.bounds.idleMs),reason:'dreaming_consolidation',providerRevision:null,inputTokens:null,outputTokens:null,queueMs:null,elapsedMs:null};this.saveJob(job,s.epoch);return job;
 }
 defer(job:Job,reason:string){const current=this.jobs(job.scope).find(j=>j.id===job.id);if(!current||current.state!=='queued')return;const s=this.read(job.scope);current.reason=current.reason==='daily_call_budget'?current.reason:reason;current.eligibleAt=stamp(this.now()+s.configuration.bounds.idleMs);this.saveJob(current,s.epoch);if(s.lastReason!==current.reason)this.change(job.scope,undefined,state=>{state.lastReason=current.reason;state.funnel.skips++;});}
 fault(){for(const scope of this.scopes())if(this.read(scope).configuration.enabled)this.change(scope,undefined,s=>{s.lastReason='background_host_failure';});}
 current(job:Job):boolean{const s=this.read(job.scope),row=this.database.connection.prepare('SELECT epoch,payload_json FROM experience_jobs WHERE scope_key=? AND id=?').get(key(job.scope),job.id);return !!row&&Number(row.epoch)===s.epoch&&s.configuration.enabled&&!s.configuration.frozen&&s.configuration.revision===job.policyRevision&&['queued','running'].includes(JSON.parse(String(row.payload_json)).state);}
 admit(job:Job,providerRevision:string):boolean{return this.database.transaction(()=>{const s=this.read(job.scope),current=this.jobs(job.scope).find(x=>x.id===job.id);if(!current||!this.current(current)||Date.parse(current.eligibleAt)>this.now()||current.attempts>=2)return false;const day=stamp(this.now()).slice(0,10),used=this.database.connection.prepare('SELECT count(*) AS n FROM experience_calls WHERE scope_key=? AND day=?').get(key(job.scope),day);if(Number(used?.n)>=s.configuration.bounds.callsPerDay){current.reason='daily_call_budget';this.saveJob(current,s.epoch);return false;}current.attempts++;current.state='running';current.providerRevision=providerRevision;current.queueMs=this.now()-Date.parse(current.createdAt);this.database.connection.prepare('INSERT INTO experience_calls VALUES (?,?,?,?)').run(key(job.scope),job.id,current.attempts,day);this.saveJob(current,s.epoch);s.funnel.admitted++;s.revision++;this.save(s);Object.assign(job,current);return true;});}
 finish(job:Job,reason:string,metrics?:{inputTokens:number;outputTokens:number;elapsedMs:number}){return this.change(job.scope,undefined,s=>{const current=this.jobs(job.scope).find(x=>x.id===job.id);if(!current||!['queued','running'].includes(current.state))return;if(metrics)Object.assign(current,metrics);current.reason=reason;s.lastReason=reason;
  if(reason==='published'||reason==='noChange'){current.state=reason==='published'?'published':'noChange';s.funnel[reason==='published'?'published':'noChange']++;}
  else if(this.current(current)&&current.attempts<2){current.state='queued';current.eligibleAt=stamp(this.now()+s.configuration.bounds.idleMs);s.funnel.failures++;}
  else{current.state='failed';s.funnel.failures++;}this.saveJob(current,s.epoch);
 });}
 called(scope:ExperienceScope){this.change(scope,undefined,s=>{s.funnel.calls++;});}
 recover(){for(const scope of this.scopes())for(const j of this.jobs(scope))if(j.state==='running'){this.finish(j,'restart_interrupted');}}
 publish(job:Job,result:ReflectionResult,policy:ExperiencePolicy,sources:Source[]):State{
 validate('Result',result);assert(Buffer.byteLength(JSON.stringify(result))<=8192,'reflection_bytes');assert(this.current(job)&&policy.allowed,'reflection_stale');const sourceMap=new Map(sources.map(s=>[s.id,s])),episodes=this.episodes(job.scope).filter(e=>e.state==='retained');
 return this.change(job.scope,undefined,s=>{assert(this.current(job)&&s.configuration.processingPolicyRevision===policy.revision,'reflection_stale');if(result.decision==='noChange')assert(!result.changes.length&&!result.items.length,'no_change_has_mutation');const before=structuredClone(s.items),changes:Lineage['changes']=[],refs=new Set(sources.map(source=>source.id));
  for(const proposal of result.items){assert(proposal.sourceRefs.length&&proposal.sourceRefs.every(id=>sourceMap.has(id)),'item_sources');assert(Buffer.byteLength(JSON.stringify(proposal))<=s.configuration.bounds.itemBytes,'item_bytes');proposal.sourceRefs.forEach(id=>refs.add(id));const old=s.items.find(i=>i.id===proposal.id);assert(proposal.expectedRevision===(old?.revision??0),'item_revision');assert(!old||!['resolved','invalidated'].includes(old.disposition)||proposal.disposition===old.disposition,'closed_item_reopen');const {expectedRevision,...rest}=proposal;void expectedRevision;const item:Item={...rest,revision:(old?.revision??0)+1,lastEvaluatedAt:stamp(this.now()),reconsiderAfter:stamp(this.now())};assert(Buffer.byteLength(JSON.stringify(item))<=s.configuration.bounds.itemBytes,'item_bytes');s.items=s.items.filter(i=>i.id!==item.id);s.items.push(item);}
  assert(s.items.filter(i=>i.disposition==='open'||i.disposition==='deferred').length<=16&&s.items.length<=128,'workspace_capacity');const seen=new Set<Dimension>();
  const history=this.allLineage(job.scope);
  for(const change of result.changes){const allowed=policy.dimensions[change.dimension];assert(allowed&&!seen.has(change.dimension)&&change.delta!==0&&Math.abs(change.delta)<=Math.min(.05,allowed.delta),'delta_not_allowed');assert(change.confidence>=(allowed.confidence??0),'confidence_below_profile');seen.add(change.dimension);const contributing=episodes.filter(e=>change.episodeRefs.includes(e.id));assert(contributing.length===new Set(change.episodeRefs).size&&contributing.length>=Math.max(2,allowed.minimumEvidence??2),'independent_episodes_required');assert(new Set(contributing.map(e=>e.independence)).size>=2,'duplicate_episode');const families=new Set(contributing.flatMap(e=>e.sourceRefs.map(id=>sourceMap.get(id)?.family).filter(Boolean)));assert(families.size>=2&&contributing.every(e=>e.sourceRefs.every(id=>sourceMap.has(id))),'independent_sources_required');assert(!history.some(l=>l.changes.some(c=>c.dimension===change.dimension&&c.episodeRefs.some(id=>change.episodeRefs.includes(id)))),'episode_already_contributed');const recent=history.filter(l=>l.operation==='reflection'&&Date.parse(l.at)>this.now()-30*86400000).flatMap(l=>l.changes).filter(c=>c.dimension===change.dimension).reduce((n,c)=>n+Math.abs(c.delta),0);assert(recent+Math.abs(change.delta)<=Math.min(.2,allowed.rolling??.2)+1e-12,'rolling_delta_limit');const imprint=s.imprints.find(i=>i.dimension===change.dimension)!;const value=imprint.value+change.delta;assert(value>=Math.max(-1,allowed.minimum)&&value<=Math.min(1,allowed.maximum),'imprint_range');imprint.learned+=change.delta;imprint.value=value;imprint.revision++;imprint.confidence=change.confidence;imprint.processingPolicyRevision=policy.revision;imprint.contributingEpisodes.push(...change.episodeRefs);contributing.flatMap(e=>e.sourceRefs).forEach(id=>refs.add(id));changes.push({dimension:change.dimension,delta:change.delta,inverse:-change.delta,episodeRefs:change.episodeRefs,confidence:change.confidence});}
  this.history(s,'reflection',changes,[...refs],job.id,before,[result.conclusion,...result.changes.map(c=>c.reason)].join(' '));s.lastReason=result.decision==='noChange'?'noChange':'published';
 });}
 reconcile(scope:ExperienceScope,sources:Source[],policy:ExperiencePolicy):void{
 const s=this.read(scope);if(!s.revision)return;const sourceMap=new Map(sources.map(s=>[s.id,s]));const invalid=this.episodes(scope).filter(e=>e.state==='retained'&&(!policy.allowed||e.sourceRefs.some(id=>!sourceMap.has(id))||e.sourceDigest!==digest(e.sourceRefs.map(id=>{const x=sourceMap.get(id)!;return [x.id,x.revision,x.digest];}))));
 const orphaned=this.allLineage(scope).some(l=>(l.summary||!l.reversed)&&l.sourceRefs.some(id=>!sourceMap.has(id)));if(!invalid.length&&!orphaned&&(!s.configuration.enabled||s.configuration.processingPolicyRevision===policy.revision))return;
 this.change(scope,undefined,next=>{next.epoch++;this.cancelJobs(scope,'source_or_policy_invalidated');const refs=new Set(invalid.flatMap(e=>e.sourceRefs));for(const episode of invalid){episode.state='invalidated';this.database.connection.prepare('UPDATE experience_episodes SET payload_json=? WHERE scope_key=? AND id=?').run(JSON.stringify(episode),key(scope),episode.id);}
  for(const row of this.database.connection.prepare('SELECT id,payload_json,inverse_items_json FROM experience_lineage WHERE scope_key=?').all(key(scope))){const l:Lineage=JSON.parse(String(row.payload_json));const affected=l.sourceRefs.some(id=>refs.has(id)||!sourceMap.has(id))||!policy.allowed;
   if(affected){if(!l.reversed&&l.operation==='reflection')for(const c of l.changes){const i=next.imprints.find(x=>x.dimension===c.dimension)!;i.learned-=c.delta;i.value=i.seed+i.learned;i.revision++;i.contributingEpisodes=i.contributingEpisodes.filter(id=>!c.episodeRefs.includes(id));}l.reversed=true;l.summary='';this.database.connection.prepare('UPDATE experience_lineage SET payload_json=?,inverse_items_json=? WHERE scope_key=? AND id=?').run(JSON.stringify(l),'[]',key(scope),l.id);}
   else {const before:Item[]=JSON.parse(String(row.inverse_items_json));this.database.connection.prepare('UPDATE experience_lineage SET inverse_items_json=? WHERE scope_key=? AND id=?').run(JSON.stringify(before.filter(i=>i.sourceRefs.every(id=>sourceMap.has(id)))),key(scope),l.id);}
  }
  next.items=next.items.map(item=>!policy.allowed||item.sourceRefs.some(id=>refs.has(id)||!sourceMap.has(id))?{...item,revision:item.revision+1,statement:'',nextStep:'',sourceRefs:[],disposition:'invalidated'}:item);for(const i of next.imprints){const surviving=this.allLineage(scope).filter(l=>l.operation==='reflection'&&!l.reversed).flatMap(l=>l.changes).filter(c=>c.dimension===i.dimension);i.confidence=surviving.length?Math.min(...surviving.map(c=>c.confidence)):i.seed===0?0:1;}next.lastReason='source_or_policy_invalidated';if(next.configuration.processingPolicyRevision!==policy.revision||!policy.allowed){next.configuration.enabled=false;next.configuration.revision++;}this.history(next,'invalidate',[],[...refs],null);
 });
 }
 reverse(scope:ExperienceScope,expected:number,id:string){const row=this.database.connection.prepare('SELECT payload_json,inverse_items_json FROM experience_lineage WHERE scope_key=? AND id=?').get(key(scope),id);assert(row,'lineage_unavailable');const line:Lineage=JSON.parse(String(row!.payload_json));if(line.reversed)return this.read(scope);return this.change(scope,expected,s=>{assert(['reflection','seed'].includes(line.operation),'lineage_not_reversible');for(const c of line.changes){const i=s.imprints.find(x=>x.dimension===c.dimension)!;if(line.operation==='seed'){i.seed-=c.delta;i.seedRevision++;}else i.learned-=c.delta;i.value=i.seed+i.learned;i.revision++;assert(Math.abs(i.value)<=1,'reverse_range');i.contributingEpisodes=i.contributingEpisodes.filter(id=>!c.episodeRefs.includes(id));}if(line.operation==='reflection'){const later=this.allLineage(scope).some(l=>l.operation==='reflection'&&!l.reversed&&l.revision>line.revision);assert(!later,'reverse_latest_reflection_first');s.items=JSON.parse(String(row!.inverse_items_json));}line.reversed=true;this.database.connection.prepare('UPDATE experience_lineage SET payload_json=?,inverse_items_json=? WHERE scope_key=? AND id=?').run(JSON.stringify(line),'[]',key(scope),id);for(const i of s.imprints){const surviving=this.allLineage(scope).filter(l=>l.operation==='reflection'&&!l.reversed).flatMap(l=>l.changes).filter(c=>c.dimension===i.dimension);i.confidence=surviving.length?Math.min(...surviving.map(c=>c.confidence)):i.seed===0?0:1;}s.epoch++;this.cancelJobs(scope,'reversed');this.history(s,'reverse',line.changes.map(c=>({...c,delta:c.inverse,inverse:c.delta})),line.sourceRefs,id);});}
 reset(scope:ExperienceScope,expected:number){return this.change(scope,expected,s=>{s.items=[];for(const i of s.imprints){i.seed=i.learned=i.value=0;i.seedRevision++;i.revision++;i.confidence=0;i.contributingEpisodes=[];}s.epoch++;this.cancelJobs(scope,'reset');for(const l of this.allLineage(scope)){l.reversed=true;l.summary='';this.database.connection.prepare('UPDATE experience_lineage SET payload_json=?,inverse_items_json=? WHERE scope_key=? AND id=?').run(JSON.stringify(l),'[]',key(scope),l.id);}this.history(s,'reset',[],[],null);s.lastReason='reset';});}
 recordSelection(scope:ExperienceScope,selection:Selection){validate('Selection',selection);this.change(scope,undefined,s=>{s.funnel.considered+=selection.considered.length;if(selection.selected)s.funnel.selected++;this.database.connection.prepare('INSERT INTO experience_selections VALUES (?,?,?)').run(key(scope),selection.id,JSON.stringify(selection));this.database.connection.prepare('DELETE FROM experience_selections WHERE scope_key=? AND rowid NOT IN (SELECT rowid FROM experience_selections WHERE scope_key=? ORDER BY rowid DESC LIMIT 32)').run(key(scope),key(scope));});}
 selections(scope:ExperienceScope):Selection[]{return this.database.connection.prepare('SELECT payload_json FROM experience_selections WHERE scope_key=? ORDER BY rowid DESC LIMIT 32').all(key(scope)).map(x=>JSON.parse(String(x.payload_json)));}
 observe(scope:ExperienceScope,id:string){const selection=this.selections(scope).find(x=>x.id===id);if(!selection||selection.observedOutput)return;this.change(scope,undefined,s=>{selection.observedOutput=true;s.funnel.outputs++;this.database.connection.prepare('UPDATE experience_selections SET payload_json=? WHERE scope_key=? AND id=?').run(JSON.stringify(selection),key(scope),id);});}
}
