import {createHash} from 'node:crypto';
import {isDeepStrictEqual} from 'node:util';
import {createContractValidator} from '@lifestream/contracts';
import {boundedGameDataSnapshot} from '@lifestream/contracts/game-journal';
import type * as G from '@lifestream/contracts/game-activity';
import type {Database} from './database.ts';
export type ActivityOwner=Pick<G.ActivityScope,'principalId'|'assistantId'|'relationshipId'>;
export type ActivityMetadataPolicy={enabled:boolean;revision:number;retentionMs:number;bounds:G.GameBounds};
export type PlanningReservation={viewId:string;viewRevision:number;invalidationKey:string;providerRevision:string;maximumInputTokens:number;maximumOutputTokens:number};
export type PlanningUsage={inputTokens:number;outputTokens:number;providerRevision:string;completionRef:string};
type Used=G.ActivityCheckpoint['budgetUsed'];
type Row={run_id:string;owner_key:string;activity_id:string;checkpoint_revision:number;state_revision:number;ledger_revision:number;epoch:number;timeline_id:string;timeline_revision:number;policy_digest:string;expires_at:number;state:string;payload_json:string|null;used_json:string};
type ReservationRow={fingerprint:string;state:string;settlement_digest:string|null;reserved_input:number;reserved_output:number};
export type ActivityMetadataOptions={
 maxRuns:number;maxReservations:number;maxCheckpointBytes:number;
 scopeCurrent:(owner:ActivityOwner)=>boolean;quarantined:()=>boolean;
 policyFor:(owner:ActivityOwner,activityId:string)=>ActivityMetadataPolicy|null;
 allowCreate:(checkpoint:G.ActivityCheckpoint)=>boolean;
 checkpointCurrent:(checkpoint:G.ActivityCheckpoint)=>boolean;
 transitionCurrent:(previous:G.ActivityCheckpoint|null,next:G.ActivityCheckpoint)=>boolean;
 planningCurrent:(checkpoint:G.ActivityCheckpoint,reservation:PlanningReservation)=>boolean;
 usageCurrent:(checkpoint:G.ActivityCheckpoint,reservation:PlanningReservation,usage:PlanningUsage)=>boolean;
 now?:()=>number;
};
export class ActivityMetadataError extends Error{readonly code:'invalidMetadata'|'unavailable'|'revisionConflict'|'budgetExceeded'|'capacity'|'clockUncertain';constructor(code:ActivityMetadataError['code']){super('Activity metadata '+code);this.code=code;}}
const validator=createContractValidator(),schema='https://lifestream.dev/contracts/local-game-activity/1.0.0#/$defs/',uuid=(s:unknown):s is string=>typeof s==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/u.test(s),positive=(n:unknown,max=2147483647):n is number=>typeof n==='number'&&Number.isSafeInteger(n)&&n>=1&&n<=max;
const ownerKey=(o:ActivityOwner)=>JSON.stringify([o.principalId,o.assistantId,o.relationshipId]);
const canonical=(v:any):any=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;
const hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex');
const freeze=<T>(v:T):T=>{if(v&&typeof v==='object'){for(const child of Object.values(v))freeze(child);Object.freeze(v);}return v;};
const budgetMap:Record<keyof Used,keyof G.GameBounds>={wallMs:'wallBudgetMs',frames:'frameBudget',actions:'actionBudget',starts:'startBudget',equivalentFailures:'equivalentFailureBudget',modelCalls:'modelCallBudget',inputTokens:'inputTokenBudget',outputTokens:'outputTokenBudget',retries:'retryBudget',checkpointBytes:'checkpointByteBudget',memoryEpisodes:'memoryEpisodeBudget'};
/** Persistent metadata is never controller admission or an exact recovery point.
 * Grounding/policy/ordinary-save/source qualification remains trusted host truth. */
export class ActivityCheckpointRepository{
 private readonly database:Database;private readonly options:ActivityMetadataOptions;private readonly limits:Readonly<{maxRuns:number;maxReservations:number;maxCheckpointBytes:number}>;
 constructor(database:Database,options:ActivityMetadataOptions){if(!positive(options.maxRuns,128)||!positive(options.maxReservations,8192)||!positive(options.maxCheckpointBytes,262144))throw new ActivityMetadataError('invalidMetadata');this.database=database;this.options=options;this.limits=Object.freeze({maxRuns:options.maxRuns,maxReservations:options.maxReservations,maxCheckpointBytes:options.maxCheckpointBytes});}
 private time(){const now=(this.options.now??Date.now)(),previous=this.database.connection.prepare('SELECT observed_at FROM activity_metadata_clock WHERE singleton=1').get()!.observed_at as number;if(!Number.isSafeInteger(now)||now<previous||!Number.isFinite(new Date(now).getTime()))throw new ActivityMetadataError('clockUncertain');this.database.connection.prepare('UPDATE activity_metadata_clock SET observed_at=? WHERE singleton=1').run(now);return now;}
 private owner(value:ActivityOwner):ActivityOwner{const o=boundedGameDataSnapshot(value) as ActivityOwner|null;if(!o||Object.keys(o).sort().join(',')!=='assistantId,principalId,relationshipId'||!uuid(o.assistantId)||!uuid(o.principalId)||o.relationshipId!==null&&!uuid(o.relationshipId))throw new ActivityMetadataError('invalidMetadata');return freeze(o);}
 private policy(owner:ActivityOwner,id:string):ActivityMetadataPolicy{let p:ActivityMetadataPolicy|null=null;try{if(this.options.quarantined()!==false||this.options.scopeCurrent(owner)!==true)throw 0;p=boundedGameDataSnapshot(this.options.policyFor(owner,id)) as ActivityMetadataPolicy|null;}catch{throw new ActivityMetadataError('unavailable');}if(!p||Object.keys(p).sort().join(',')!=='bounds,enabled,retentionMs,revision'||p.enabled!==true||!positive(p.revision)||!positive(p.retentionMs)||!validator.validate(schema+'GameBounds',p.bounds).valid)throw new ActivityMetadataError('unavailable');return freeze(p);}
 private current(owner:ActivityOwner,id:string,policy:ActivityMetadataPolicy){try{return isDeepStrictEqual(this.policy(owner,id),policy);}catch{return false;}}
 private checked(fn:()=>boolean){try{return fn()===true;}catch{return false;}}
 private row(owner:ActivityOwner,id:string){return this.database.connection.prepare('SELECT * FROM activity_checkpoints WHERE owner_key=? AND run_id=?').get(ownerKey(owner),id) as Row|undefined;}
 private retire(row:Row,state:string){this.database.connection.prepare('UPDATE activity_checkpoints SET state=?,payload_json=NULL,ledger_revision=ledger_revision+1 WHERE run_id=?').run(state,row.run_id);}
 private active(owner:ActivityOwner,id:string){const now=this.time(),row=this.row(owner,id);if(!row)return null;if(row.expires_at<=now){if(row.state==='active'||row.state==='needsReview')this.retire(row,'expired');return null;}let policy:ActivityMetadataPolicy;try{policy=this.policy(owner,row.activity_id);}catch{if(['active','needsReview'].includes(row.state)&&this.checked(()=>this.options.quarantined()===false&&this.options.scopeCurrent(owner)))this.retire(row,'retracted');return null;}if(row.expires_at<=now){if(row.state==='active'||row.state==='needsReview')this.retire(row,'expired');return null;}if(row.policy_digest!==hash(policy)){if(row.state==='active'||row.state==='needsReview')this.retire(row,'retracted');return null;}if(row.state!=='active'||!row.payload_json)return null;const checkpoint=freeze(JSON.parse(row.payload_json) as G.ActivityCheckpoint);if(!this.checked(()=>this.options.checkpointCurrent(checkpoint))){this.retire(row,'needsReview');return null;}if(!this.current(owner,row.activity_id,policy)||this.time()>=row.expires_at)return null;const latest=this.row(owner,id);return latest?.state==='active'&&latest.ledger_revision===row.ledger_revision?{row,policy,checkpoint}:null;}
 private reserved(id:string){const row=this.database.connection.prepare("SELECT count(*) AS calls,coalesce(sum(reserved_input),0) AS input,coalesce(sum(reserved_output),0) AS output FROM activity_planning_reservations WHERE run_id=? AND state='reserved'").get(id)!;return {modelCalls:row.calls as number,inputTokens:row.input as number,outputTokens:row.output as number};}
 private within(used:Used,bounds:G.GameBounds,reserved=this.reserved('')){for(const [key,limit]of Object.entries(budgetMap) as [keyof Used,keyof G.GameBounds][]){const n=used[key]+(Object.hasOwn(reserved,key)?reserved[key as keyof typeof reserved]:0);if(!Number.isSafeInteger(n)||n<0||n>(bounds[limit] as number))throw new ActivityMetadataError('budgetExceeded');}}
 put(value:ActivityOwner,raw:G.ActivityCheckpoint,expectedRevision:number):G.ActivityCheckpoint{
  const owner=this.owner(value),now=this.time(),checkpoint=boundedGameDataSnapshot(raw,this.limits.maxCheckpointBytes) as G.ActivityCheckpoint|null;if(!checkpoint||!validator.validate(schema+'ActivityCheckpoint',checkpoint).valid||!isDeepStrictEqual(owner,{assistantId:checkpoint.scope.assistantId,principalId:checkpoint.scope.principalId,relationshipId:checkpoint.scope.relationshipId})||Date.parse(checkpoint.recordedAt)>now||checkpoint.campaignJournalRef.campaignId!==checkpoint.scope.campaignId||checkpoint.lastActionReceipt&&(['assistantId','principalId','relationshipId','environmentId','activityId','runId','campaignId'] as const).some(k=>checkpoint.lastActionReceipt!.scope[k]!==checkpoint.scope[k])||checkpoint.saveArtifact&&(checkpoint.saveArtifact.pinsDigest!==checkpoint.pinsDigest||Date.parse(checkpoint.saveArtifact.verifiedAt)>now))throw new ActivityMetadataError('invalidMetadata');
  const policy=this.policy(owner,checkpoint.scope.activityId),anyRow=this.database.connection.prepare('SELECT owner_key FROM activity_checkpoints WHERE run_id=?').get(checkpoint.scope.runId);if(anyRow&&anyRow.owner_key!==ownerKey(owner))throw new ActivityMetadataError('unavailable');const previous=this.row(owner,checkpoint.scope.runId),prior=previous?.payload_json?freeze(JSON.parse(previous.payload_json) as G.ActivityCheckpoint):null;
  if(previous&&(previous.activity_id!==checkpoint.scope.activityId||previous.policy_digest!==hash(policy)||previous.expires_at<=now||!['active','needsReview'].includes(previous.state))||expectedRevision!==(previous?.checkpoint_revision??0)||checkpoint.revision!==expectedRevision+1||checkpoint.policyRevision!==policy.revision||previous&&(checkpoint.stateRevision<previous.state_revision||checkpoint.scope.activityEpoch<previous.epoch||checkpoint.scope.timelineId===previous.timeline_id&&checkpoint.scope.timelineRevision<previous.timeline_revision||checkpoint.scope.timelineId!==previous.timeline_id&&checkpoint.scope.activityEpoch<=previous.epoch))throw new ActivityMetadataError('revisionConflict');
  if(!previous&&!this.checked(()=>this.options.allowCreate(freeze(structuredClone(checkpoint)))))throw new ActivityMetadataError('unavailable');
  const used:Used=previous?JSON.parse(previous.used_json):Object.fromEntries(Object.keys(budgetMap).map(k=>[k,0])) as Used;for(const k of Object.keys(budgetMap) as (keyof Used)[])if(checkpoint.budgetUsed[k]<used[k])throw new ActivityMetadataError('budgetExceeded');
  // This store owns actual cumulative serialized metadata-byte charges.
  const floor=checkpoint.budgetUsed.checkpointBytes;let bytes=0;for(let i=0;i<8;i++){checkpoint.budgetUsed.checkpointBytes=floor+bytes;const next=Buffer.byteLength(JSON.stringify(checkpoint));if(next===bytes)break;bytes=next;}if(Buffer.byteLength(JSON.stringify(checkpoint))>this.limits.maxCheckpointBytes)throw new ActivityMetadataError('capacity');
  this.within(checkpoint.budgetUsed,policy.bounds,this.reserved(checkpoint.scope.runId));freeze(checkpoint);
  if(!this.checked(()=>this.options.transitionCurrent(prior,checkpoint))||!this.checked(()=>this.options.checkpointCurrent(checkpoint))||!this.current(owner,checkpoint.scope.activityId,policy))throw new ActivityMetadataError('unavailable');
  this.database.transaction(tx=>{const occupied=tx.get<{owner_key:string}>('SELECT owner_key FROM activity_checkpoints WHERE run_id=?',checkpoint.scope.runId);if(occupied&&occupied.owner_key!==ownerKey(owner))throw new ActivityMetadataError('unavailable');const latest=this.row(owner,checkpoint.scope.runId);if(latest?.ledger_revision!==previous?.ledger_revision)throw new ActivityMetadataError('revisionConflict');if(!previous&&tx.get<{n:number}>('SELECT count(*) AS n FROM activity_checkpoints')!.n>=this.limits.maxRuns)throw new ActivityMetadataError('capacity');tx.run('INSERT INTO activity_checkpoints VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(run_id) DO UPDATE SET checkpoint_revision=excluded.checkpoint_revision,state_revision=excluded.state_revision,ledger_revision=excluded.ledger_revision,epoch=excluded.epoch,timeline_id=excluded.timeline_id,timeline_revision=excluded.timeline_revision,state=excluded.state,payload_json=excluded.payload_json,used_json=excluded.used_json',checkpoint.scope.runId,ownerKey(owner),checkpoint.scope.activityId,checkpoint.revision,checkpoint.stateRevision,(previous?.ledger_revision??0)+1,checkpoint.scope.activityEpoch,checkpoint.scope.timelineId,checkpoint.scope.timelineRevision,hash(policy),previous?.expires_at??now+policy.retentionMs,'active',JSON.stringify(checkpoint),JSON.stringify(checkpoint.budgetUsed));if(!this.checked(()=>this.options.checkpointCurrent(checkpoint))||!this.current(owner,checkpoint.scope.activityId,policy)||this.time()>=(previous?.expires_at??now+policy.retentionMs))throw new ActivityMetadataError('unavailable');});return structuredClone(checkpoint);
 }
 /** Always recovery-only metadata after process restart; never queued action
  * replay, live authority, fake save reconstruction or automatic resume. */
 get(ownerValue:ActivityOwner,id:string){if(!uuid(id))return null;const owner=this.owner(ownerValue),active=this.active(owner,id);if(!active)return null;const {row,checkpoint}=active;return {checkpoint:structuredClone(checkpoint),ledgerRevision:row.ledger_revision,used:JSON.parse(row.used_json) as Used,reserved:this.reserved(id),recoveryDisposition:checkpoint.saveArtifact?'requiresReconciliation' as const:'unavailable' as const,continuationAuthority:false as const};}
 reservePlanning(ownerValue:ActivityOwner,scope:G.ActivityScope,raw:PlanningReservation):boolean{
  const scoped=boundedGameDataSnapshot(scope) as G.ActivityScope|null;if(!scoped||!validator.validate(schema+'ActivityScope',scoped).valid)return false;scope=freeze(scoped);const owner=this.owner(ownerValue),active=this.active(owner,scope.runId),r=boundedGameDataSnapshot(raw) as PlanningReservation|null;if(!active||!r||Object.keys(r).sort().join(',')!=='invalidationKey,maximumInputTokens,maximumOutputTokens,providerRevision,viewId,viewRevision'||!uuid(r.viewId)||!uuid(r.invalidationKey)||!positive(r.viewRevision)||!positive(r.maximumInputTokens,32768)||!positive(r.maximumOutputTokens,4096)||typeof r.providerRevision!=='string'||!r.providerRevision.trim()||Buffer.byteLength(r.providerRevision)>1024||!isDeepStrictEqual(scope,active.checkpoint.scope))return false;freeze(r);const {row,policy,checkpoint}=active;
  return this.database.transaction(tx=>{const existing=tx.get('SELECT view_id FROM activity_planning_reservations WHERE run_id=? AND view_id=? AND view_revision=?',scope.runId,r.viewId,r.viewRevision);if(existing||this.row(owner,scope.runId)?.ledger_revision!==row.ledger_revision)return false;if(tx.get<{n:number}>('SELECT count(*) AS n FROM activity_planning_reservations')!.n>=this.limits.maxReservations)throw new ActivityMetadataError('capacity');const held=this.reserved(scope.runId);held.modelCalls++;held.inputTokens+=r.maximumInputTokens;held.outputTokens+=r.maximumOutputTokens;this.within(JSON.parse(row.used_json) as Used,policy.bounds,held);if(!this.checked(()=>this.options.planningCurrent(checkpoint,r))||!this.checked(()=>this.options.checkpointCurrent(checkpoint))||!this.current(owner,row.activity_id,policy))return false;tx.run("INSERT INTO activity_planning_reservations VALUES(?,?,?,?,?,?,'reserved',NULL)",scope.runId,r.viewId,r.viewRevision,hash(r),r.maximumInputTokens,r.maximumOutputTokens);tx.run('UPDATE activity_checkpoints SET ledger_revision=ledger_revision+1 WHERE run_id=?',scope.runId);if(!this.checked(()=>this.options.planningCurrent(checkpoint,r))||!this.checked(()=>this.options.checkpointCurrent(checkpoint))||!this.current(owner,row.activity_id,policy)||this.time()>=row.expires_at)throw new ActivityMetadataError('unavailable');return true;});
 }
 /** Only an independently evidenced provider terminal may replace a held
  * worst-case reservation by actual usage. Unknown/cancelled work stays held. */
 settlePlanning(ownerValue:ActivityOwner,scope:G.ActivityScope,raw:PlanningReservation,usageValue:PlanningUsage):boolean{
  const scoped=boundedGameDataSnapshot(scope) as G.ActivityScope|null;if(!scoped||!validator.validate(schema+'ActivityScope',scoped).valid)return false;scope=freeze(scoped);const owner=this.owner(ownerValue),active=this.active(owner,scope.runId),r=boundedGameDataSnapshot(raw) as PlanningReservation|null,u=boundedGameDataSnapshot(usageValue) as PlanningUsage|null;if(!active||!r||!u||Object.keys(u).sort().join(',')!=='completionRef,inputTokens,outputTokens,providerRevision'||!Number.isSafeInteger(u.inputTokens)||u.inputTokens<0||u.inputTokens>r.maximumInputTokens||!Number.isSafeInteger(u.outputTokens)||u.outputTokens<0||u.outputTokens>r.maximumOutputTokens||u.providerRevision!==r.providerRevision||typeof u.completionRef!=='string'||!u.completionRef.trim()||Buffer.byteLength(u.completionRef)>2048||!isDeepStrictEqual(scope,active.checkpoint.scope))return false;freeze(r);freeze(u);const {row,policy,checkpoint}=active;
  return this.database.transaction(tx=>{const reserved=tx.get<ReservationRow>('SELECT * FROM activity_planning_reservations WHERE run_id=? AND view_id=? AND view_revision=?',scope.runId,r.viewId,r.viewRevision);if(!reserved||reserved.fingerprint!==hash(r)||reserved.state!=='reserved'||this.row(owner,scope.runId)?.ledger_revision!==row.ledger_revision)return false;if(!this.checked(()=>this.options.usageCurrent(checkpoint,r,u))||!this.checked(()=>this.options.checkpointCurrent(checkpoint))||!this.current(owner,row.activity_id,policy))return false;const used:Used=JSON.parse(row.used_json);used.modelCalls++;used.inputTokens+=u.inputTokens;used.outputTokens+=u.outputTokens;const held=this.reserved(scope.runId);held.modelCalls--;held.inputTokens-=reserved.reserved_input;held.outputTokens-=reserved.reserved_output;this.within(used,policy.bounds,held);tx.run("UPDATE activity_planning_reservations SET state='settled',settlement_digest=? WHERE run_id=? AND view_id=? AND view_revision=?",hash(u),scope.runId,r.viewId,r.viewRevision);tx.run('UPDATE activity_checkpoints SET used_json=?,ledger_revision=ledger_revision+1 WHERE run_id=?',JSON.stringify(used),scope.runId);if(!this.checked(()=>this.options.usageCurrent(checkpoint,r,u))||!this.checked(()=>this.options.checkpointCurrent(checkpoint))||!this.current(owner,row.activity_id,policy)||this.time()>=row.expires_at)throw new ActivityMetadataError('unavailable');return true;});
 }
 invalidate(ownerValue:ActivityOwner,id:string){const owner=this.owner(ownerValue);this.time();if(this.options.quarantined()!==false||!this.checked(()=>this.options.scopeCurrent(owner)))throw new ActivityMetadataError('unavailable');const row=this.row(owner,id);if(row?.state==='active')this.retire(row,'needsReview');}
 /** Host wires this into existing bounded cleanup; no schedule is enrolled. */
 sweep(){const now=this.time();this.database.connection.prepare("UPDATE activity_checkpoints SET state='expired',payload_json=NULL,ledger_revision=ledger_revision+1 WHERE expires_at<=? AND state IN ('active','needsReview')").run(now);}
}
