import type { Database } from "./database.js";
export type MemoryRecord = { id: string; assistantId: string; content: string; provenance: Record<string, unknown>; lifecycle: Record<string, unknown>; createdAt: string };
export class MemoryRepository {
  private readonly records = new Map<string, MemoryRecord>();
  private readonly database: Database | undefined;
  constructor(database?: Database) { this.database = database; }
  save(record: MemoryRecord): MemoryRecord { const copy = structuredClone(record); if (this.database) { try { this.database.transaction((tx) => tx.run("INSERT INTO memories (id, assistant_id, content, provenance_json, lifecycle_json, created_at) VALUES (?, ?, ?, ?, ?, ?)", copy.id, copy.assistantId, copy.content, JSON.stringify(copy.provenance), JSON.stringify(copy.lifecycle), copy.createdAt)); } catch { throw new Error("memory is immutable"); } } else { if (this.records.has(copy.id)) throw new Error("memory is immutable"); this.records.set(copy.id, copy); } return structuredClone(copy); }
  get(assistantId: string, id: string): MemoryRecord | undefined { if (this.database) { const row = this.database.connection.prepare("SELECT id, assistant_id AS assistantId, content, provenance_json AS provenance, lifecycle_json AS lifecycle, created_at AS createdAt FROM memories WHERE assistant_id = ? AND id = ?").get(assistantId, id) as { id: string; assistantId: string; content: string; provenance: string; lifecycle: string; createdAt: string } | undefined; return row ? { ...row, provenance: JSON.parse(row.provenance), lifecycle: JSON.parse(row.lifecycle) } : undefined; } const r = this.records.get(id); return r?.assistantId === assistantId ? structuredClone(r) : undefined; }
  list(assistantId: string): MemoryRecord[] { if (this.database) return (this.database.connection.prepare("SELECT id, assistant_id AS assistantId, content, provenance_json AS provenance, lifecycle_json AS lifecycle, created_at AS createdAt FROM memories WHERE assistant_id = ? ORDER BY id").all(assistantId) as { id: string; assistantId: string; content: string; provenance: string; lifecycle: string; createdAt: string }[]).map((row) => ({ ...row, provenance: JSON.parse(row.provenance), lifecycle: JSON.parse(row.lifecycle) })); return [...this.records.values()].filter((r) => r.assistantId === assistantId).map((r) => structuredClone(r)); }
}
