export type AudioOwnershipLease = { leaseId: string; sessionId: string; ownerEndpointId: string; revision: number; expiresAt: string; fencingToken: number };
export type HandoffRequest = { handoffId: string; sessionId: string; sourceEndpointId: string; destinationEndpointId: string; expectedLeaseRevision: number; initiatorRef: string; authorized: boolean; destinationAvailable: boolean; privacyCompatible: boolean; occurredAt: string };
export type HandoffRecord = { handoffId: string; sessionId: string; sourceEndpointId: string; destinationEndpointId: string; authorization: "authorized" | "denied"; oldLeaseId: string | null; newLease: AudioOwnershipLease | null; outcome: "completed" | "failed"; reason: string };

export class SessionHandoffService {
  private readonly leases = new Map<string, AudioOwnershipLease>();
  private readonly records = new Map<string, HandoffRecord>();

  seedLease(lease: AudioOwnershipLease): AudioOwnershipLease { if (this.leases.has(lease.sessionId)) throw new Error("session already has audio owner"); this.leases.set(lease.sessionId, structuredClone(lease)); return structuredClone(lease); }
  handoff(request: HandoffRequest): HandoffRecord { const duplicate = this.records.get(request.handoffId); if (duplicate) return structuredClone(duplicate); const current = this.leases.get(request.sessionId); const fail = (reason: string): HandoffRecord => { const record = { handoffId: request.handoffId, sessionId: request.sessionId, sourceEndpointId: request.sourceEndpointId, destinationEndpointId: request.destinationEndpointId, authorization: request.authorized ? "authorized" as const : "denied" as const, oldLeaseId: current?.leaseId ?? null, newLease: null, outcome: "failed" as const, reason }; this.records.set(request.handoffId, record); return structuredClone(record); }; if (!current || current.ownerEndpointId !== request.sourceEndpointId || current.revision !== request.expectedLeaseRevision) return fail("stale_lease"); if (!request.authorized) return fail("handoff_not_authorized"); if (!request.destinationAvailable) return fail("destination_unavailable"); if (!request.privacyCompatible) return fail("privacy_downgrade"); const next: AudioOwnershipLease = { leaseId: request.handoffId, sessionId: request.sessionId, ownerEndpointId: request.destinationEndpointId, revision: current.revision + 1, expiresAt: request.occurredAt, fencingToken: current.fencingToken + 1 }; const record = { handoffId: request.handoffId, sessionId: request.sessionId, sourceEndpointId: request.sourceEndpointId, destinationEndpointId: request.destinationEndpointId, authorization: "authorized" as const, oldLeaseId: current.leaseId, newLease: next, outcome: "completed" as const, reason: "handoff_completed" }; this.leases.set(request.sessionId, structuredClone(next)); this.records.set(request.handoffId, record); return structuredClone(record); }
  currentLease(sessionId: string): AudioOwnershipLease | undefined { const lease = this.leases.get(sessionId); return lease && structuredClone(lease); }
  activeOwnerCount(sessionId: string): number { return this.leases.has(sessionId) ? 1 : 0; }
}
