type AudioFormat = { encoding: "pcm_s16le"; sampleRateHz: 16000 | 24000 | 48000; channels: 1 | 2 };
type AudioFrame = { frameId: string; sequence: number; format: AudioFormat; sampleOffset: number; sampleCount: number; dataBase64: string };
type SttInput = { type: "frame"; audioInputId: string; frame: AudioFrame } | { type: "end"; audioInputId: string; nextSequence: number; sampleCount: number };
type SttEvent = { kind: "data"; sequence: number; payload: { type: "partial" | "committed"; utteranceId: string; text: string; startSample: number; endSample: number; speakerRef: null; confidence: number } } | { kind: "terminal"; sequence: number; outcome: "succeeded" | "cancelled" | "timedOut" | "failed"; inputSamples: number };
type ExpressiveDimension = "affect" | "urgency" | "deliveryMode" | "pace" | "energy";
type TtsCapabilities = { contractVersion: "2.0.0"; supportedDimensions: readonly ExpressiveDimension[]; degradableDimensions: readonly ExpressiveDimension[]; supportsStreaming: true; maxOutputSamples: number };
type TtsRequest = SpeechRequest & { contractVersion: "2.0.0"; text: string; segmentId: string; format: AudioFormat; voiceProfile: { voiceRef: string; revision: number }; decision: { decisionId: string; revision: number; urgency: "low" | "normal" | "high" | "critical"; deliveryMode: "neutral" | "explanation" | "reassurance" | "concern" | "celebration" | "warning" | "emergency"; pace: number; energy: number }; delivery: { interactionId: string; segmentId: string; decisionId: string; decisionRevision: number; urgency: string; deliveryMode: string; pace: number; energy: number } };
type TtsEvent = { kind: "preAudio"; sequence: number; segmentId: string; decisionId: string; decisionRevision: number; delivery: TtsRequest["delivery"]; disposition: "fullyApplied" | "partiallyApplied"; degradedDimensions: ExpressiveDimension[]; mappingRevision: string } | { kind: "data"; sequence: number; segmentId: string; frame: AudioFrame; mappingRevision: string } | { kind: "terminal"; sequence: number; segmentId: string; outcome: "succeeded" | "cancelled" | "timedOut" | "failed"; outputSamples: number; frameCount: number; disposition: "fullyApplied" | "partiallyApplied" | "cancelled" | "timedOut"; degradedDimensions: ExpressiveDimension[]; mappingRevision: string };
type SpeechRequest = { deadlineAt: string; now: () => string };

export class FixtureSpeechToTextProvider {
  async *transcribe(request: SpeechRequest, audio: AsyncIterable<SttInput>, signal?: AbortSignal): AsyncIterable<SttEvent> { let sequence = 0; let samples = 0; for await (const item of audio) { if (signal?.aborted) { yield { kind: "terminal", sequence, outcome: "cancelled", inputSamples: samples }; return; } if (Date.parse(request.now()) >= Date.parse(request.deadlineAt)) { yield { kind: "terminal", sequence, outcome: "timedOut", inputSamples: samples }; return; } if (item.type === "frame") { samples += item.frame.sampleCount; yield { kind: "data", sequence: sequence++, payload: { type: "partial", utteranceId: "00000000-0000-4000-8000-000000000019", text: "fixture", startSample: item.frame.sampleOffset, endSample: item.frame.sampleOffset + item.frame.sampleCount, speakerRef: null, confidence: 1 } }; } else { yield { kind: "data", sequence: sequence++, payload: { type: "committed", utteranceId: "00000000-0000-4000-8000-000000000019", text: "fixture", startSample: 0, endSample: samples, speakerRef: null, confidence: 1 } }; yield { kind: "terminal", sequence, outcome: "succeeded", inputSamples: samples }; return; } } }
}

export class FixtureTextToSpeechProvider {
  private readonly unsupported: readonly ExpressiveDimension[];
  constructor(options: { unsupportedDimensions?: readonly ExpressiveDimension[] } = {}) { this.unsupported = options.unsupportedDimensions ?? []; }
  capabilities(): TtsCapabilities { const dimensions: ExpressiveDimension[] = ["affect", "urgency", "deliveryMode", "pace", "energy"]; return { contractVersion: "2.0.0", supportedDimensions: dimensions.filter((d) => !this.unsupported.includes(d)), degradableDimensions: this.unsupported, supportsStreaming: true, maxOutputSamples: 48000 }; }
  async *synthesize(request: TtsRequest, signal?: AbortSignal): AsyncIterable<TtsEvent> { const mappingRevision = "fixture-expressive-2"; if (request.contractVersion !== "2.0.0" || !request.text.trim() || request.delivery.segmentId !== request.segmentId || request.delivery.decisionId !== request.decision.decisionId || request.delivery.decisionRevision !== request.decision.revision) throw new Error("tts request correlation invalid"); const degradedDimensions = this.unsupported.filter((dimension) => dimension === "deliveryMode" ? request.decision.deliveryMode !== "neutral" : dimension === "urgency" ? request.decision.urgency !== "normal" : true); const disposition = degradedDimensions.length ? "partiallyApplied" : "fullyApplied"; yield { kind: "preAudio", sequence: 0, segmentId: request.segmentId, decisionId: request.decision.decisionId, decisionRevision: request.decision.revision, delivery: structuredClone(request.delivery), disposition, degradedDimensions, mappingRevision }; if (signal?.aborted) { yield { kind: "terminal", sequence: 1, segmentId: request.segmentId, outcome: "cancelled", outputSamples: 0, frameCount: 0, disposition: "cancelled", degradedDimensions: [], mappingRevision }; return; } if (Date.parse(request.now()) >= Date.parse(request.deadlineAt)) { yield { kind: "terminal", sequence: 1, segmentId: request.segmentId, outcome: "timedOut", outputSamples: 0, frameCount: 0, disposition: "timedOut", degradedDimensions: [], mappingRevision }; return; } const frame: AudioFrame = { frameId: "00000000-0000-4000-8000-000000000020", sequence: 0, format: request.format, sampleOffset: 0, sampleCount: 10, dataBase64: "AAAA" }; yield { kind: "data", sequence: 1, segmentId: request.segmentId, frame, mappingRevision }; yield { kind: "terminal", sequence: 2, segmentId: request.segmentId, outcome: "succeeded", outputSamples: 10, frameCount: 1, disposition, degradedDimensions, mappingRevision }; }
}
