type AudioFormat = { encoding: "pcm_s16le"; sampleRateHz: 16000 | 24000 | 48000; channels: 1 | 2 };
type AudioFrame = { frameId: string; sequence: number; format: AudioFormat; sampleOffset: number; sampleCount: number; dataBase64: string };
type SttInput = { type: "frame"; audioInputId: string; frame: AudioFrame } | { type: "end"; audioInputId: string; nextSequence: number; sampleCount: number };
type SttEvent = { kind: "data"; sequence: number; payload: { type: "partial" | "committed"; utteranceId: string; text: string; startSample: number; endSample: number; speakerRef: null; confidence: number } } | { kind: "terminal"; sequence: number; outcome: "succeeded" | "cancelled" | "timedOut" | "failed"; inputSamples: number };
type TtsEvent = { kind: "data"; sequence: number; segmentId: string; frame: AudioFrame } | { kind: "terminal"; sequence: number; segmentId: string; outcome: "succeeded" | "cancelled" | "timedOut" | "failed"; outputSamples: number; frameCount: number };
type SpeechRequest = { deadlineAt: string; now: () => string };

export class FixtureSpeechToTextProvider {
  async *transcribe(request: SpeechRequest, audio: AsyncIterable<SttInput>, signal?: AbortSignal): AsyncIterable<SttEvent> { let sequence = 0; let samples = 0; for await (const item of audio) { if (signal?.aborted) { yield { kind: "terminal", sequence, outcome: "cancelled", inputSamples: samples }; return; } if (Date.parse(request.now()) >= Date.parse(request.deadlineAt)) { yield { kind: "terminal", sequence, outcome: "timedOut", inputSamples: samples }; return; } if (item.type === "frame") { samples += item.frame.sampleCount; yield { kind: "data", sequence: sequence++, payload: { type: "partial", utteranceId: "00000000-0000-4000-8000-000000000019", text: "fixture", startSample: item.frame.sampleOffset, endSample: item.frame.sampleOffset + item.frame.sampleCount, speakerRef: null, confidence: 1 } }; } else { yield { kind: "data", sequence: sequence++, payload: { type: "committed", utteranceId: "00000000-0000-4000-8000-000000000019", text: "fixture", startSample: 0, endSample: samples, speakerRef: null, confidence: 1 } }; yield { kind: "terminal", sequence, outcome: "succeeded", inputSamples: samples }; return; } } }
}

export class FixtureTextToSpeechProvider {
  async *synthesize(request: SpeechRequest, segmentId: string, _text: string, format: AudioFormat, signal?: AbortSignal): AsyncIterable<TtsEvent> { if (signal?.aborted) { yield { kind: "terminal", sequence: 0, segmentId, outcome: "cancelled", outputSamples: 0, frameCount: 0 }; return; } if (Date.parse(request.now()) >= Date.parse(request.deadlineAt)) { yield { kind: "terminal", sequence: 0, segmentId, outcome: "timedOut", outputSamples: 0, frameCount: 0 }; return; } const frame: AudioFrame = { frameId: "00000000-0000-4000-8000-000000000020", sequence: 0, format, sampleOffset: 0, sampleCount: 10, dataBase64: "AAAA" }; yield { kind: "data", sequence: 0, segmentId, frame }; yield { kind: "terminal", sequence: 1, segmentId, outcome: "succeeded", outputSamples: 10, frameCount: 1 }; }
}
