import {createHash} from 'node:crypto';
export type ReadinessScope={subjectId:string;assistantId:string;relationshipId:string};
export type TrainingConsent=ReadinessScope&{consentId:string;revision:number;sourceRefs:string[];purpose:'trainingDataset';status:'approved'|'revoked';grantedBy:string;createdAt:string};
export type TrainingSource=ReadinessScope&{sourceId:string;sourceRevision:string;sourceFamily:string;sensitivity:'ordinary'|'sensitive';purpose:'training';consent:'approved'|'excluded';consentRef:string;contentDigest:string};
export type DatasetRecord=TrainingSource&{recordId:string;content:string;split:'train'|'validation'|'test';transformed:'none'|'redacted'|'normalized';dependencyIds:string[]};
export type DatasetManifest={schemaVersion:'2.0.0';datasetId:string;revision:number;digest:string;records:DatasetRecord[];exclusions:string[];syntheticGenerator:string;createdAt:string;exportPolicy:'fixture-only'|'approved-runtime';status:'prepared'|'quarantined'|'revoked'};
export type DatasetAuthority={scope:ReadinessScope;consents:TrainingConsent[];sources:{id:string;revision:string;family:string;contentDigest:string;eligible:boolean}[]};
export type AdapterManifest={schemaVersion:'2.0.0';artifactId:string;artifactRevision:string;kind:'behavioral'|'concreteFactHypothesis';baseModel:string;baseModelRevision:string;tokenizer:string;chatTemplate:string;runtime:string;quantization:string;datasetDigest:string;datasetLineage:string[];trainingSettings:Record<string,string|number|boolean>;toolVersions:Record<string,string>;resourceEvidence:string[];evaluations:string[];approvedSubjectId:string;approvedAssistantId:string;approvedAudience:'private'|'shared'|'unknown';activationDependency:string;revocationDependency:string;fallback:{baseModel:string;baseModelRevision:string;untouched:true;merged:false};status:'candidate'|'approved'|'quarantined'|'revoked'};
export type AdapterRouteRequest={assistantId:string;subjectId:string;audience:'private'|'shared'|'unknown';artifactRevision:string;baseModel:string;baseModelRevision:string;tokenizer:string;chatTemplate:string;runtime:string;quantization:string;datasetDigest:string;activeDependencies:string[];revokedDependencies?:string[];runtimeSupported:boolean};
export type AdapterRoute={route:'adapter'|'fallback';artifactId?:string;artifactRevision?:string;reason:string;cacheInvalidated:boolean;liveEffects:false};
const text=(v:unknown,max=256):v is string=>typeof v==='string'&&!!v.trim()&&v.length<=max;
const sha=(v:string)=>createHash('sha256').update(v).digest('hex');
export const trainingContentDigest=(value:string)=>sha(value);
const stable=(v:unknown):unknown=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,stable(x)])):v;
export function datasetDigest(input:Omit<DatasetManifest,'digest'|'status'>):string{return sha(JSON.stringify(stable(input)));}
export function buildDatasetManifest(input:Omit<DatasetManifest,'status'|'digest'>,authority:DatasetAuthority):DatasetManifest{
 if(input.schemaVersion!=='2.0.0'||!text(input.datasetId)||!Number.isInteger(input.revision)||input.revision<1||!text(input.syntheticGenerator)||!Number.isFinite(Date.parse(input.createdAt))||!Array.isArray(input.records)||input.records.length<3||input.records.length>256||!['fixture-only','approved-runtime'].includes(input.exportPolicy))throw new Error('Dataset 2.0.0 requires bounded identity, version, generator, date and records; legacy manifests need requalification');
 if(!['train','validation','test'].every(split=>input.records.some(r=>r.split===split)))throw new Error('Dataset requires train/validation/test splits');
 const ids=new Set<string>(),membership=new Map<string,string>();
 for(const r of input.records){
  if(!text(r.recordId)||ids.has(r.recordId)||!text(r.sourceId)||!text(r.sourceRevision)||!text(r.sourceFamily)||!text(r.content,4000)||!['train','validation','test'].includes(r.split)||!['none','redacted','normalized'].includes(r.transformed)||!['ordinary','sensitive'].includes(r.sensitivity)||!Array.isArray(r.dependencyIds)||r.dependencyIds.length>32||r.dependencyIds.some(d=>!text(d)))throw new Error('Invalid or duplicate dataset record');ids.add(r.recordId);
  if(r.subjectId!==authority.scope.subjectId||r.assistantId!==authority.scope.assistantId||r.relationshipId!==authority.scope.relationshipId)throw new Error('Dataset source crosses authenticated scope');
  if(r.consent!=='approved'||r.purpose!=='training')throw new Error('Dataset requires separate purpose-specific training consent');
  const consent=authority.consents.find(c=>`${c.consentId}:${c.revision}`===r.consentRef);if(!consent||consent.status!=='approved'||consent.purpose!=='trainingDataset'||consent.grantedBy!==r.subjectId||consent.subjectId!==r.subjectId||consent.assistantId!==r.assistantId||consent.relationshipId!==r.relationshipId||!consent.sourceRefs.includes(`${r.sourceId}:${r.sourceRevision}`))throw new Error('Dataset consent is missing, revoked or not source-bound');
  const source=authority.sources.find(s=>s.id===r.sourceId&&s.revision===r.sourceRevision);if(!source?.eligible||source.family!==r.sourceFamily||source.contentDigest!==r.contentDigest||trainingContentDigest(r.content)!==r.contentDigest)throw new Error('Dataset source content or revision changed');
  if(!r.dependencyIds.includes(`${r.sourceId}:${r.sourceRevision}`)||!r.dependencyIds.includes(r.consentRef))throw new Error('Dataset source and consent lineage are required');
  if(r.sensitivity==='sensitive'&&input.exportPolicy!=='approved-runtime')throw new Error('Sensitive data cannot use fixture-only export');
  for(const group of [`family:${r.sourceFamily}`,`source:${r.sourceId}`,`content:${r.contentDigest}`,...r.dependencyIds.filter(d=>d!==r.consentRef).map(d=>`dependency:${d}`)]){if(membership.has(group)&&membership.get(group)!==r.split)throw new Error('Correlated source/content/dependency leakage across dataset splits');membership.set(group,r.split);}
 }
 if(!Array.isArray(input.exclusions)||input.exclusions.length>256||input.exclusions.some(x=>!text(x)))throw new Error('Invalid bounded exclusions');
 const value=structuredClone(input);return {...value,digest:datasetDigest(value),status:'prepared'};
}
export function validateDatasetManifest(manifest:DatasetManifest,authority:DatasetAuthority):void{if(manifest.status!=='prepared')throw new Error('Dataset is not eligible');const {digest,status,...input}=manifest;void status;if(buildDatasetManifest(input,authority).digest!==digest)throw new Error('Dataset digest mismatch');}
export function validateAdapterManifest(m:AdapterManifest):void{
 if(m.schemaVersion!=='2.0.0'||!['behavioral','concreteFactHypothesis'].includes(m.kind)||!['candidate','approved','quarantined','revoked'].includes(m.status)||!['private','shared','unknown'].includes(m.approvedAudience)||[m.artifactId,m.artifactRevision,m.baseModel,m.baseModelRevision,m.tokenizer,m.chatTemplate,m.runtime,m.quantization,m.datasetDigest,m.approvedSubjectId,m.approvedAssistantId,m.activationDependency,m.revocationDependency].some(x=>!text(x)))throw new Error('Adapter 2.0.0 manifest identity or compatibility is incomplete');
 for(const refs of [m.datasetLineage,m.resourceEvidence,m.evaluations])if(!Array.isArray(refs)||!refs.length||refs.length>256||refs.some(x=>!text(x)))throw new Error('Adapter requires bounded lineage, resource evidence and evaluations');
 if(!m.trainingSettings||!Object.keys(m.trainingSettings).length||Object.keys(m.trainingSettings).length>32||Object.values(m.trainingSettings).some(v=>!['string','number','boolean'].includes(typeof v)||(typeof v==='number'&&!Number.isFinite(v)))||!m.toolVersions||!Object.keys(m.toolVersions).length||Object.keys(m.toolVersions).length>32||Object.values(m.toolVersions).some(x=>!text(x)))throw new Error('Adapter training settings/tool versions are incomplete');
 if(m.fallback?.untouched!==true||m.fallback.merged!==false||m.fallback.baseModel!==m.baseModel||m.fallback.baseModelRevision!==m.baseModelRevision)throw new Error('Untouched unmerged approved base fallback is required');
}
export function validateAdapterEligibility(m:AdapterManifest,r:AdapterRouteRequest):{eligible:true}|{eligible:false;reason:string}{
 try{validateAdapterManifest(m);}catch(error){return {eligible:false,reason:error instanceof Error?error.message:'Invalid adapter manifest'};}
 const deny=(reason:string)=>({eligible:false as const,reason});if(m.status!=='approved')return deny(`Adapter status is ${m.status}`);if(!r.runtimeSupported)return deny('Selected runtime has no approved private-adapter serving contract; use the untouched base');
 if(r.audience!=='private'||m.approvedAudience!=='private')return deny('Private adapters require an authenticated private audience');if(m.approvedAssistantId!==r.assistantId||m.approvedSubjectId!==r.subjectId)return deny('Authenticated Assistant or subject scope does not match');
 if(m.artifactRevision!==r.artifactRevision||m.baseModel!==r.baseModel||m.baseModelRevision!==r.baseModelRevision||m.tokenizer!==r.tokenizer||m.chatTemplate!==r.chatTemplate||m.runtime!==r.runtime||m.quantization!==r.quantization)return deny('Exact artifact/runtime compatibility does not match');if(m.datasetDigest!==r.datasetDigest)return deny('Dataset digest does not match');
 if(!r.activeDependencies?.includes(m.activationDependency)||m.datasetLineage.some(d=>!r.activeDependencies.includes(d))||!r.activeDependencies.includes(m.revocationDependency))return deny('Activation, source or revocation currency is unknown');if((r.revokedDependencies??[]).some(d=>m.datasetLineage.includes(d)||d===m.revocationDependency||d===m.activationDependency))return deny('Adapter dependency revoked; quarantine required');return {eligible:true};
}
export function routeAdapter(manifest:AdapterManifest,request:AdapterRouteRequest):AdapterRoute{const e=validateAdapterEligibility(manifest,request);return e.eligible?{route:'adapter',artifactId:manifest.artifactId,artifactRevision:manifest.artifactRevision,reason:'Approved fixture-compatible identity and current authenticated dependencies matched',cacheInvalidated:true,liveEffects:false}:{route:'fallback',reason:e.reason,cacheInvalidated:true,liveEffects:false};}
export type TrainingRegistryState={datasets:DatasetManifest[];artifacts:AdapterManifest[];revokedDependencies:string[];revision:number};
export class TrainingRegistry{
 private state:TrainingRegistryState;constructor(state:TrainingRegistryState={datasets:[],artifacts:[],revokedDependencies:[],revision:1}){this.state=structuredClone(state);}
 snapshot():TrainingRegistryState{return structuredClone(this.state);}
 addDataset(input:Omit<DatasetManifest,'status'|'digest'>,authority:DatasetAuthority):DatasetManifest{if(this.state.datasets.length>=16||this.state.datasets.some(d=>d.datasetId===input.datasetId))throw new Error('Dataset capacity or identity conflict');const dataset=buildDatasetManifest(input,authority);if(dataset.records.some(r=>r.dependencyIds.some(d=>this.state.revokedDependencies.includes(d))))throw new Error('Dataset dependency is revoked');this.state.datasets.push(dataset);this.state.revision++;return structuredClone(dataset);}
 exportDataset(id:string,authority:DatasetAuthority):DatasetManifest{const dataset=this.state.datasets.find(d=>d.datasetId===id);if(!dataset)throw new Error('Dataset unavailable');validateDatasetManifest(dataset,authority);return structuredClone(dataset);}
 register(manifest:AdapterManifest,authority:DatasetAuthority):AdapterManifest{validateAdapterManifest(manifest);if(manifest.status!=='candidate'||this.state.artifacts.length>=64||this.state.artifacts.some(m=>m.artifactId===manifest.artifactId&&m.artifactRevision===manifest.artifactRevision))throw new Error('Register a unique bounded candidate artifact');const dataset=this.state.datasets.find(d=>d.digest===manifest.datasetDigest);if(!dataset)throw new Error('Registered dataset required');validateDatasetManifest(dataset,authority);if(manifest.approvedSubjectId!==authority.scope.subjectId||manifest.approvedAssistantId!==authority.scope.assistantId||dataset.records.some(r=>r.dependencyIds.some(d=>!manifest.datasetLineage.includes(d))))throw new Error('Artifact scope or complete dataset lineage is missing');this.state.artifacts.push(structuredClone(manifest));this.state.revision++;return structuredClone(manifest);}
 approve(id:string,revision:string,expectedRegistryRevision:number,authority:DatasetAuthority):AdapterManifest{if(expectedRegistryRevision!==this.state.revision)throw new Error('Registry revision changed');const m=this.state.artifacts.find(m=>m.artifactId===id&&m.artifactRevision===revision);if(!m||m.status!=='candidate')throw new Error('Current candidate artifact required');const dataset=this.state.datasets.find(d=>d.digest===m.datasetDigest);if(!dataset)throw new Error('Dataset unavailable');validateDatasetManifest(dataset,authority);m.status='approved';this.state.revision++;return structuredClone(m);}
 invalidate(refs:string[],forget=false):void{this.state.revokedDependencies=[...new Set([...this.state.revokedDependencies,...refs])];for(const d of this.state.datasets)if(d.records.some(r=>refs.includes(r.sourceId)||r.dependencyIds.some(x=>refs.includes(x)))){d.status=forget?'revoked':'quarantined';if(forget)for(const r of d.records)r.content='';}for(const m of this.state.artifacts)if(m.datasetLineage.some(x=>refs.includes(x))||refs.includes(m.activationDependency)||refs.includes(m.revocationDependency)||this.state.datasets.some(d=>d.digest===m.datasetDigest&&d.status!=='prepared'))m.status='quarantined';this.state.revision++;}
 route(id:string,request:AdapterRouteRequest,authority:DatasetAuthority):AdapterRoute{const m=this.state.artifacts.find(m=>m.artifactId===id&&m.artifactRevision===request.artifactRevision);if(!m)return {route:'fallback',reason:'Registered artifact unavailable',cacheInvalidated:true,liveEffects:false};const d=this.state.datasets.find(d=>d.digest===m.datasetDigest);try{if(!d)throw new Error('Dataset unavailable');validateDatasetManifest(d,authority);}catch{return {route:'fallback',reason:'Dataset source or consent is stale; quarantine required',cacheInvalidated:true,liveEffects:false};}return routeAdapter(m,{...request,revokedDependencies:[...(request.revokedDependencies??[]),...this.state.revokedDependencies]});}
}
