export type TrainingSource = { sourceId: string; sourceRevision: string; sourceFamily: string; subjectId: string; relationshipId: string; sensitivity: "ordinary" | "sensitive"; purpose: "evaluation" | "training"; consent: "approved" | "excluded"; contentDigest: string };
export type DatasetRecord = TrainingSource & { recordId: string; split: "train" | "validation" | "test"; transformed: "none" | "redacted" | "normalized"; dependencyIds: string[] };
export type DatasetManifest = { datasetId: string; revision: number; digest: string; records: DatasetRecord[]; exclusions: string[]; syntheticGenerator: string; createdAt: string; exportPolicy: "fixture-only" | "approved-runtime"; status: "prepared" | "quarantined" | "revoked" };
export type AdapterManifest = { artifactId: string; artifactRevision: string; baseModel: string; baseModelRevision: string; tokenizer: string; chatTemplate: string; runtime: string; quantization: string; datasetDigest: string; datasetLineage: string[]; trainingSettings: Record<string, string | number | boolean>; toolVersions: Record<string, string>; resourceEvidence: string[]; evaluations: string[]; approvedSubjectId: string; approvedAssistantId: string; approvedAudience: "private" | "shared" | "unknown"; activationDependency: string; revocationDependency: string; status: "candidate" | "approved" | "quarantined" | "revoked" };
export type AdapterRouteRequest = { assistantId: string; subjectId: string; audience: "private" | "shared" | "unknown"; baseModel: string; baseModelRevision: string; tokenizer: string; chatTemplate: string; datasetDigest: string; revokedDependencies?: string[] };
export type AdapterRoute = { route: "adapter" | "fallback"; artifactId?: string; reason: string; cacheInvalidated: boolean; liveEffects: false };

const bounded = (value: string, label: string): string => { if (!value.trim() || value.length > 256) throw new Error(`${label} must be a bounded non-empty string`); return value.trim(); };
export function buildDatasetManifest(input: Omit<DatasetManifest, "status">): DatasetManifest {
  if (!input.datasetId || input.revision < 1 || !input.digest || !input.syntheticGenerator || !input.records.length || !input.records.some((record) => record.split === "train") || !input.records.some((record) => record.split === "validation") || !input.records.some((record) => record.split === "test")) throw new Error("dataset requires identity, digest, consented records and train/validation/test splits");
  for (const record of input.records) { bounded(record.sourceId, "sourceId"); bounded(record.sourceFamily, "sourceFamily"); if (record.consent !== "approved" || record.purpose !== "training") throw new Error("dataset contains a record without purpose-specific training consent"); if (record.sensitivity === "sensitive" && input.exportPolicy !== "approved-runtime") throw new Error("sensitive records are not allowed in fixture-only export"); }
  return { ...structuredClone(input), status: "prepared" };
}
export function validateAdapterEligibility(manifest: AdapterManifest, request: AdapterRouteRequest): { eligible: true } | { eligible: false; reason: string } {
  if (manifest.status !== "approved") return { eligible: false, reason: `adapter status is ${manifest.status}` };
  if (request.audience !== "private" || manifest.approvedAudience !== "private") return { eligible: false, reason: "private-fact adapters require a private authenticated audience" };
  if (manifest.approvedAssistantId !== request.assistantId || manifest.approvedSubjectId !== request.subjectId) return { eligible: false, reason: "authenticated Assistant or subject scope does not match" };
  if (manifest.baseModel !== request.baseModel || manifest.baseModelRevision !== request.baseModelRevision || manifest.tokenizer !== request.tokenizer || manifest.chatTemplate !== request.chatTemplate) return { eligible: false, reason: "runtime compatibility identity does not match" };
  if (manifest.datasetDigest !== request.datasetDigest) return { eligible: false, reason: "dataset digest does not match" };
  if ((request.revokedDependencies ?? []).some((dependency) => manifest.datasetLineage.includes(dependency) || dependency === manifest.revocationDependency)) return { eligible: false, reason: "adapter dependency is revoked; adapter is quarantined" };
  return { eligible: true };
}
export function routeAdapter(manifest: AdapterManifest, request: AdapterRouteRequest): AdapterRoute { const eligibility = validateAdapterEligibility(manifest, request); return eligibility.eligible ? { route: "adapter", artifactId: manifest.artifactId, reason: "approved manifest and authenticated compatibility scope matched", cacheInvalidated: true, liveEffects: false } : { route: "fallback", reason: eligibility.reason, cacheInvalidated: true, liveEffects: false }; }
