import assert from "node:assert/strict"; import { createServer } from "node:http"; import { test } from "node:test"; import { SglangInferenceProvider } from "../src/provider.ts";
const request = { sections: [], manifest: { schemaVersion: "1.0.0", sections: [], tokenizer: "test" }, deadlineAt: new Date(Date.now() + 1000).toISOString(), executionMode: "live" as const, scope: { assistantId: "a", sessionId: "s", interactionId: "i", endpointId: null } };
test('only trusted spoken policy requests direct answers and split SSE frames are retained',async t=>{
  const bodies: Array<Record<string,unknown>>=[];
  const server=createServer(async(req,res)=>{let input='';for await(const chunk of req)input+=chunk; bodies.push(JSON.parse(input));res.writeHead(200,{'content-type':'text/event-stream'});res.write('data: {"choices":[{"delta":{"con');setTimeout(()=>res.end('tent":"hello"}}]}\n\ndata: [DONE]\n\n'),10);});
  await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>server.close());
  const provider=new SglangInferenceProvider({endpoint:`http://127.0.0.1:${(server.address() as {port:number}).port}`,model:'qwen3.8-27b-local'});
  for(const trusted of [true,false]){
    const section={kind:'policy',trusted,sourceRef:'policy:spoken-v1',sourceRevision:'v1',content:'test',contentDigest:'test',redaction:'none' as const,tokenCount:1};const chunks=[];
    for await(const chunk of provider.generate({...request,sections:[section]},{signal:new AbortController().signal}))chunks.push(chunk);
    assert.deepEqual(chunks.map(c=>c.kind),['text','done']);
  }
  assert.deepEqual(bodies[0]?.chat_template_kwargs,{enable_thinking:false});assert.equal(bodies[1]?.chat_template_kwargs,undefined);
});
test('truncated or provider-limited inference cannot claim completion',async t=>{
  let limited=false;const server=createServer((_req,res)=>res.end(limited?'data: {"choices":[{"finish_reason":"length"}]}\n\ndata: [DONE]\n\n':'data: {"choices":'));
  await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>server.close());const provider=new SglangInferenceProvider({endpoint:`http://127.0.0.1:${(server.address() as {port:number}).port}`,model:'qwen3.8-27b-local'});
  for(const expected of ['malformed_provider_event','response_limit']){const chunks=[];for await(const chunk of provider.generate(request,{signal:new AbortController().signal}))chunks.push(chunk);assert.equal(chunks.at(-1)?.error?.code,expected);limited=true;}
});
test("SGLang adapter streams terminal output and preserves model request", async (t) => { const server = createServer((req, res) => { assert.equal(req.url, "/v1/chat/completions"); res.writeHead(200, { "content-type": "text/event-stream" }); res.write('data: {"choices":[{"delta":{"content":"hello"}}]}\n\n'); res.end("data: [DONE]\n\n"); }); await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve)); t.after(() => server.close()); const port = (server.address() as { port: number }).port; const chunks = []; for await (const chunk of new SglangInferenceProvider({ endpoint: `http://127.0.0.1:${port}`, model: "qwen3.8-27b-local" }).generate(request, { signal: new AbortController().signal })) chunks.push(chunk); assert.deepEqual(chunks.map((chunk) => chunk.kind), ["text", "done"]); });
test("SGLang adapter rejects live provider during replay", async () => { const chunks = []; for await (const chunk of new SglangInferenceProvider({ endpoint: "http://127.0.0.1:1", model: "qwen3.8-27b-local" }).generate({ ...request, executionMode: "replay" }, { signal: new AbortController().signal })) chunks.push(chunk); assert.equal(chunks[0]?.error?.code, "replay_live_provider_forbidden"); });
test("SGLang adapter reports outage and response-limit failures truthfully", async () => { const outage = []; for await (const chunk of new SglangInferenceProvider({ endpoint: "http://127.0.0.1:1", model: "qwen3.8-27b-local" }).generate(request, { signal: new AbortController().signal })) outage.push(chunk); assert.equal(outage.at(-1)?.error?.code, "inference_unavailable"); const server = createServer((_req, res) => { res.writeHead(200, { "content-type": "text/event-stream" }); res.end('data: {"choices":[{"delta":{"content":"too-long"}}]}\n\ndata: [DONE]\n\n'); }); await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve)); const port = (server.address() as { port: number }).port; const limited = []; for await (const chunk of new SglangInferenceProvider({ endpoint: `http://127.0.0.1:${port}`, model: "qwen3.8-27b-local", maxResponseBytes: 2 }).generate(request, { signal: new AbortController().signal })) limited.push(chunk); server.close(); assert.equal(limited.at(-1)?.error?.code, "response_limit"); });
