export function installAutomaticMemory({anchor,api,context}) {
 const section=document.createElement('section');section.className='room-memory';section.setAttribute('aria-label','Automatic memory');
 section.innerHTML='<h3>Memory for this relationship</h3><p>Useful preferences, conventions, recurring goals, project decisions and shared experiences can be saved automatically from your typed messages. Secrets and unverified speakers are excluded. You can inspect, correct or forget saved records at any time.</p><label><input type="checkbox" data-memory-enabled checked> Allow automatic memory in this relationship</label><div class="actions"><button type="button" data-memory-apply>Apply memory mode</button><button type="button" class="secondary" data-memory-refresh>Refresh memory status</button><a href="#memory">Inspect saved memory</a></div><div data-memory-retries></div><p role="status">Review and apply this scope once. Ordinary admission needs no per-item review.</p>';
 const visualPane=document.createElement('div');visualPane.className='visual-memory';
 visualPane.innerHTML='<h4>Visual observation memory</h4><p>Save selected visual observations only with separate consent and a host-confirmed subject. Camera permission alone does not enable memory. Observations remain unverified; images are never retained here.</p><label><input type="checkbox" data-visual-memory-enabled> Allow visual memory in this relationship</label><label>Retention in days <input type="number" min="1" step="1" inputmode="numeric" data-visual-memory-days aria-label="Visual memory retention in days"></label><button type="button" class="secondary" data-visual-memory-apply>Apply visual memory policy</button><p role="status" data-visual-memory-status>Visual memory is off until explicitly configured.</p><div data-visual-memory-episodes></div>';
 section.append(visualPane);
 anchor.append(section);const status=section.querySelector('[role="status"]'),enabled=section.querySelector('[data-memory-enabled]'),apply=section.querySelector('[data-memory-apply]');let snapshot,epoch=0;
 const scope=()=>{const c=context();if(!c?.assistantId||!c.relationship?.relationshipId)throw new Error('Select an Assistant and relationship first.');return {assistantId:c.assistantId,relationshipId:c.relationship.relationshipId};};
 const describe=value=>{const counts={};let rejected=0;for(const job of value.jobs){counts[job.state]=(counts[job.state]??0)+1;try{const n=JSON.parse(job.result??'{}').rejectedItemCount;if(Number.isSafeInteger(n)&&n>0)rejected+=n;}catch{ /* Older jobs may have no extraction receipt. */ }}return `${value.policy.enabled?'Automatic memory enabled':'Automatic memory off'} · ${value.jobs.length?Object.entries(counts).map(([state,count])=>`${count} ${state}`).join(', '):'No queued work'}. ${rejected?`${rejected} unsafe or malformed extracted item${rejected===1?'':'s'} rejected; valid items were handled separately. `:''}Saved status is reported only after durable persistence.`;};
 const visualEnabled=section.querySelector('[data-visual-memory-enabled]'),visualDays=section.querySelector('[data-visual-memory-days]'),visualApply=section.querySelector('[data-visual-memory-apply]'),visualStatus=section.querySelector('[data-visual-memory-status]');let visualRevision;
 const renderVisual=value=>{const visual=value.visual;if(!visual){visualApply.disabled=true;visualStatus.textContent='Visual memory is unavailable on this service revision.';return;}
  visualApply.disabled=false;if(visualRevision!==visual.policy.revision){visualEnabled.checked=visual.policy.enabled;visualDays.value=visual.policy.retentionMs===null?'':String(visual.policy.retentionMs/86400000);visualRevision=visual.policy.revision;}
  visualStatus.textContent=`Visual memory ${visual.policy.enabled?'enabled':'off'} · ${visual.episodes.length} retained or retired receipt${visual.episodes.length===1?'':'s'}. ${visual.complete?'Inventory complete.':'Inventory limited; missing coverage cannot support a pattern.'} Canonical observation intake requires a configured host adapter.`;
  const list=section.querySelector('[data-visual-memory-episodes]');list.replaceChildren();for(const row of visual.episodes){const article=document.createElement('article'),text=document.createElement('p');text.textContent=row.episode?`${row.state} · Unverified observation: ${row.episode.summary} · ${row.episode.occurredAt} · expires ${row.expiresAt}`:`${row.state} · Observation payload removed.`;article.append(text);if(row.episode){const button=document.createElement('button');button.type='button';button.className='secondary';button.textContent='Forget visual observation';button.onclick=()=>void(async()=>{button.disabled=true;await api('/api/runtime/v1/memory',{method:'POST',body:JSON.stringify({...scope(),operation:'forgetVisual',id:row.episodeId,expectedRevision:row.revision})});await refresh();})().catch(error=>{button.disabled=false;visualStatus.textContent=error.message;});article.append(button);}list.append(article);}
 };
 visualApply.onclick=()=>void(async()=>{if(!snapshot)await refresh();if(!snapshot?.visual)throw Error('Refresh visual memory policy first.');const days=visualDays.value.trim()===''?null:Number(visualDays.value),retentionMs=days===null?null:days*86400000;if(visualEnabled.checked&&(days===null||!Number.isSafeInteger(days)||days<1)||retentionMs!==null&&!Number.isSafeInteger(retentionMs))throw Error('Enter an explicit positive whole-day retention duration.');const ticket=epoch;visualApply.disabled=true;const value=await api('/api/runtime/v1/memory',{method:'POST',body:JSON.stringify({...scope(),operation:'configureVisual',enabled:visualEnabled.checked,expectedRevision:snapshot.visual.policy.revision,retentionMs})});if(ticket!==epoch)return;snapshot=value;renderVisual(value);})().catch(error=>{visualApply.disabled=false;visualStatus.textContent=error.message;});
 const refresh=async()=>{if(!window.lifestreamAuth.session)return;const ticket=epoch,s=scope(),value=await api('/api/runtime/v1/memory?'+new URLSearchParams(s));if(ticket!==epoch)return;if(!snapshot||snapshot.policy.revision!==value.policy.revision)enabled.checked=value.policy.enabled;snapshot=value;status.textContent=describe(value);renderVisual(value);apply.disabled=false;const retries=section.querySelector('[data-memory-retries]');retries.replaceChildren();for(const job of value.jobs.filter(j=>j.state==='failed')){const button=document.createElement('button');button.type='button';button.className='secondary';button.textContent='Retry failed memory extraction · '+new Date(job.createdAt).toLocaleTimeString();button.onclick=run(async()=>{await api('/api/runtime/v1/memory',{method:'POST',body:JSON.stringify({...scope(),operation:'retry',id:job.id})});await refresh();});retries.append(button);}};
 const run=fn=>()=>void fn().catch(error=>{status.textContent=error.message;});section.querySelector('[data-memory-refresh]').onclick=run(refresh);
 apply.onclick=run(async()=>{if(!snapshot)await refresh();const ticket=epoch,value=await api('/api/runtime/v1/memory',{method:'POST',body:JSON.stringify({...scope(),enabled:enabled.checked,expectedRevision:snapshot.policy.revision})});if(ticket!==epoch)return;snapshot=value;status.textContent=describe(value);renderVisual(value);});
 const clear=()=>{epoch++;snapshot=null;visualRevision=undefined;visualEnabled.checked=false;visualDays.value="";visualApply.disabled=true;section.querySelector("[data-visual-memory-episodes]").replaceChildren();visualStatus.textContent="Select an owned relationship and refresh its visual memory policy.";enabled.checked=true;apply.disabled=true;status.textContent='Select an owned relationship and refresh its memory mode.';void refresh().catch(()=>{});};for(const event of ['lifestream-auth','lifestream-assistant','lifestream-relationship'])window.addEventListener(event,clear);
 const timer=setInterval(()=>{if(!document.hidden&&location.hash==='#conversation'&&snapshot?.policy.enabled)void refresh().catch(()=>{});},3000);window.addEventListener('pagehide',()=>clearInterval(timer));
 return {refresh:run(refresh)};
}
