export function installAutomaticMemory({anchor,api,context}) {
 const section=document.createElement('section');section.className='room-memory';section.setAttribute('aria-label','Automatic memory');
 section.innerHTML='<h3>Memory for this relationship</h3><p>Useful preferences, conventions, recurring goals, project decisions and shared experiences can be saved automatically from your typed messages. Secrets and unverified speakers are excluded. You can inspect, correct or forget saved records at any time.</p><label><input type="checkbox" data-memory-enabled checked> Allow automatic memory in this relationship</label><div class="actions"><button type="button" data-memory-apply>Apply memory mode</button><button type="button" class="secondary" data-memory-refresh>Refresh memory status</button><a href="#memory">Inspect saved memory</a></div><div data-memory-retries></div><p role="status">Review and apply this scope once. Ordinary admission needs no per-item review.</p>';
 anchor.append(section);const status=section.querySelector('[role="status"]'),enabled=section.querySelector('[data-memory-enabled]'),apply=section.querySelector('[data-memory-apply]');let snapshot,epoch=0;
 const scope=()=>{const c=context();if(!c?.assistantId||!c.relationship?.relationshipId)throw new Error('Select an Assistant and relationship first.');return {assistantId:c.assistantId,relationshipId:c.relationship.relationshipId};};
 const describe=value=>{const counts={};let rejected=0;for(const job of value.jobs){counts[job.state]=(counts[job.state]??0)+1;try{const n=JSON.parse(job.result??'{}').rejectedItemCount;if(Number.isSafeInteger(n)&&n>0)rejected+=n;}catch{ /* Older jobs may have no extraction receipt. */ }}return `${value.policy.enabled?'Automatic memory enabled':'Automatic memory off'} · ${value.jobs.length?Object.entries(counts).map(([state,count])=>`${count} ${state}`).join(', '):'No queued work'}. ${rejected?`${rejected} unsafe or malformed extracted item${rejected===1?'':'s'} rejected; valid items were handled separately. `:''}Saved status is reported only after durable persistence.`;};
 const refresh=async()=>{if(!window.lifestreamAuth.session)return;const ticket=epoch,s=scope(),value=await api('/api/runtime/v1/memory?'+new URLSearchParams(s));if(ticket!==epoch)return;if(!snapshot||snapshot.policy.revision!==value.policy.revision)enabled.checked=value.policy.enabled;snapshot=value;status.textContent=describe(value);apply.disabled=false;const retries=section.querySelector('[data-memory-retries]');retries.replaceChildren();for(const job of value.jobs.filter(j=>j.state==='failed')){const button=document.createElement('button');button.type='button';button.className='secondary';button.textContent='Retry failed memory extraction · '+new Date(job.createdAt).toLocaleTimeString();button.onclick=run(async()=>{await api('/api/runtime/v1/memory',{method:'POST',body:JSON.stringify({...scope(),operation:'retry',id:job.id})});await refresh();});retries.append(button);}};
 const run=fn=>()=>void fn().catch(error=>{status.textContent=error.message;});section.querySelector('[data-memory-refresh]').onclick=run(refresh);
 apply.onclick=run(async()=>{if(!snapshot)await refresh();const ticket=epoch,value=await api('/api/runtime/v1/memory',{method:'POST',body:JSON.stringify({...scope(),enabled:enabled.checked,expectedRevision:snapshot.policy.revision})});if(ticket!==epoch)return;snapshot=value;status.textContent=describe(value);});
 const clear=()=>{epoch++;snapshot=null;enabled.checked=true;apply.disabled=true;status.textContent='Select an owned relationship and refresh its memory mode.';void refresh().catch(()=>{});};for(const event of ['lifestream-auth','lifestream-assistant','lifestream-relationship'])window.addEventListener(event,clear);
 const timer=setInterval(()=>{if(!document.hidden&&location.hash==='#conversation'&&snapshot?.policy.enabled)void refresh().catch(()=>{});},3000);window.addEventListener('pagehide',()=>clearInterval(timer));
 return {refresh:run(refresh)};
}
