const fixtureHeaders={"content-type":"application/json","x-lifestream-fixture-session":"browser-conversation","x-lifestream-fixture-principal":"human"};
const $=id=>document.getElementById(id);let stream=null,audioContext=null,analyser=null,levelFrame=0,requestController=null;
$("connect").textContent="Start microphone";
$("voice-note").textContent="Local microphone and speaker controls are available. Backend STT/TTS are not configured in this development composition, so this is not a voice-session connection.";
const setStatus=(id,text,kind="")=>{$(id).textContent=text;$(id).dataset.kind=kind};
async function refreshBackend(){try{const response=await fetch("/health",{cache:"no-store"}),body=await response.json(),ready=response.ok&&body.status==="ready";setStatus("connection",ready?"Connected":"Backend degraded",ready?"ready":"error");if(!ready)setStatus("events",`Backend: ${body.status||"unavailable"} — inference or voice services may be unavailable`,"error")}catch(error){setStatus("connection","Backend unreachable","error");setStatus("events",`Backend: ${error.message||"health check failed"}`,"error")}}
const retryBackend=document.createElement("button");retryBackend.type="button";retryBackend.className="secondary";retryBackend.textContent="Retry backend connection";$("connection").after(retryBackend);retryBackend.addEventListener("click",refreshBackend);
const addMessage=(role,text)=>{const node=document.createElement("article");node.className=`message ${role}`;node.innerHTML=`<strong>${role==="user"?"You":"Assistant"}</strong><pre></pre>`;node.querySelector("pre").textContent=text;$("messages").append(node);node.scrollIntoView({block:"end"});return node.querySelector("pre")};
async function refreshDevices(){if(!navigator.mediaDevices?.enumerateDevices)return;const devices=await navigator.mediaDevices.enumerateDevices();$("microphone").replaceChildren(...devices.filter(device=>device.kind==="audioinput").map((device,index)=>{const option=document.createElement("option");option.value=device.deviceId;option.textContent=device.label||`Microphone ${index+1}`;return option}))}
function meter(){if(!analyser)return;const data=new Uint8Array(analyser.frequencyBinCount);analyser.getByteTimeDomainData(data);const rms=Math.sqrt(data.reduce((sum,value)=>sum+(value-128)**2,0)/data.length)/128;$("level").style.width=`${Math.min(100,Math.round(rms*220))}%`;levelFrame=requestAnimationFrame(meter)}
async function connect(){if(!window.isSecureContext){setStatus("permission","Microphone requires a trustworthy localhost origin.","error");return}if(!navigator.mediaDevices?.getUserMedia){setStatus("permission","This browser does not expose getUserMedia.","error");return}try{stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,sampleRate:16000,echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});const track=stream.getAudioTracks()[0],settings=track.getSettings();setStatus("permission",`Microphone permission: granted (${settings.sampleRate||"browser"} Hz, ${settings.channelCount||"?"} channel)`);setStatus("capture","Capture: running");$("connect").disabled=true;$("stop-capture").disabled=false;$("mute").disabled=false;audioContext=new AudioContext();const source=audioContext.createMediaStreamSource(stream);analyser=audioContext.createAnalyser();analyser.fftSize=512;source.connect(analyser);cancelAnimationFrame(levelFrame);meter();await refreshDevices()}catch(error){setStatus("permission",`Microphone permission: ${error.name||"failed"} — ${error.message||"request failed"}`,"error")}}
function stopCapture(){stream?.getTracks().forEach(track=>track.stop());stream=null;analyser=null;cancelAnimationFrame(levelFrame);$("level").style.width="0";setStatus("capture","Capture: stopped");$("connect").disabled=false;$("stop-capture").disabled=true;$("mute").disabled=true}
async function speakerTest(){audioContext??=new AudioContext();await audioContext.resume();const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();gain.gain.value=.04;oscillator.frequency.value=660;oscillator.connect(gain).connect(audioContext.destination);oscillator.start();oscillator.stop(audioContext.currentTime+.18);setStatus("events","Events: local speaker test played")}
async function sendMessage(event){event.preventDefault();const prompt=$("prompt").value.trim();if(!prompt)return;addMessage("user",prompt);$("prompt").value="";const answer=addMessage("assistant","");requestController=new AbortController();$("send").disabled=true;$("stop-response").disabled=false;try{const response=await fetch("/api/runtime/v1/messages",{method:"POST",headers:fixtureHeaders,body:JSON.stringify({userInput:prompt,readOnlyCapability:{name:"capability.read-only.status",input:{scope:"assistant-neutral"}}}),signal:requestController.signal});if(!response.ok)throw new Error(`Runtime returned ${response.status}`);setStatus("connection","Connected","ready");const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="";while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const frames=buffer.split("\n\n");buffer=frames.pop()||"";for(const frame of frames){const eventName=frame.match(/^event: (.+)$/m)?.[1],data=frame.match(/^data: (.+)$/m)?.[1];if(!data)continue;const payload=JSON.parse(data);if(eventName==="message.delta")answer.textContent+=payload.text||"";if(eventName==="input.manifest")setStatus("events",`Events: manifest (${payload.sections?.length||9} sections)`);if(eventName==="capability.read-only")setStatus("events","Events: harmless read-only capability selected");if(eventName==="interaction.completed")setStatus("events",`Events: completed (${payload.provider?.model||"provider identity"})`);if(eventName==="interaction.error")setStatus("events",`Events: runtime error — ${payload.message||"unknown error"}`,"error")}}}catch(error){if(error.name!=="AbortError")setStatus("events",`Events: ${error.message}`,"error")}finally{requestController=null;$("send").disabled=false;$("stop-response").disabled=true}}
$("connect").addEventListener("click",connect);$("stop-capture").addEventListener("click",stopCapture);$("mute").addEventListener("click",()=>{const track=stream?.getAudioTracks()[0];if(!track)return;track.enabled=!track.enabled;$("mute").textContent=track.enabled?"Mute microphone":"Unmute microphone";setStatus("capture",`Capture: ${track.enabled?"running":"muted"}`)});$("speaker-test").addEventListener("click",speakerTest);$("message-form").addEventListener("submit",sendMessage);$("stop-response").addEventListener("click",()=>requestController?.abort());refreshDevices();refreshBackend();
