import {ConversationOutput} from './conversation-output.js';
import {ConversationCapture} from './conversation-capture.js';
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dimensions=['initiative','warmth','curiosity','followThrough','persistence'];
const pretty=value=>String(value??'Unknown').replace(/([a-z])([A-Z])/g,'$1 $2').replace(/^./,c=>c.toUpperCase());
export function installConversationRoom({anchor,api,context}){
 anchor.innerHTML=`<div class="room-layout"><section class="room-dialogue" aria-label="Conversation"><div class="section-head"><h3>Talk with your Assistant</h3><span class="status draft" id="room-output-state">Openings off</span></div><p id="room-scope" class="muted">Select an Assistant.</p><p id="room-status" role="status" aria-live="polite"></p><ol id="room-turns" class="room-turns" aria-label="Conversation turns"><li class="muted" data-room-empty>No messages in this page session.</li></ol><form id="room-message-form"><label for="room-message">Your message<textarea id="room-message" rows="3" maxlength="4000" required placeholder="Type a reply…"></textarea></label><div class="actions"><button id="room-send" type="submit">Send message</button><button id="room-stop" type="button" class="secondary">Stop response & speech</button></div></form><p class="muted">The microphone stays off until you start it. With capture on, sustained speech interrupts playback and becomes your next reply. This page displays up to 100 turns. The signed-in session keeps bounded recent context for up to 30 minutes across microphone reconnections. Scope changes and forgetting invalidate that context; no durable memory is created.</p><div class="room-microphone"><div class="actions"><button id="room-mic-start" type="button" class="secondary">Start microphone</button><button id="room-mic-stop" type="button" class="secondary" disabled>Stop microphone</button></div><p id="room-mic-status" role="status">Microphone off</p><details><summary>Speech detection</summary><label for="room-sensitivity">Speech sensitivity<input id="room-sensitivity" type="range" min="0" max="100" value="50"></label><p class="muted">Balanced by default. Lower values require stronger speech evidence; higher values admit softer speech. Audio remains in a bounded local buffer until speech qualifies.</p></details></div></section>
 <details class="room-setup" aria-label="Session output" open><summary>Output for this session</summary><p id="room-disclosure" class="muted">Refresh to read the current session.</p><a href="#session">Review session disclosure →</a><label for="room-modality">Opening output<select id="room-modality"><option value="text">Text in this conversation</option><option value="speech">Speech and its transcript</option></select></label><div class="actions"><button id="room-enable" type="button">Enable selected output</button><button id="room-disable" type="button" class="secondary">Turn openings off</button></div><p class="muted">Readiness does not opt you in or start the microphone. Your reviewed Initiative settings still decide whether an opening is allowed. Speech uses the configured voice; prosodic warmth is not supported by its current mapping.</p><a href="#initiative">Review Initiative settings →</a><p id="room-timing" class="muted" role="status">No pending timing adjustment.</p><details><summary>Temporary attention</summary><p>These controls apply only to the current session. Durable settings stay unchanged.</p><div class="actions"><button id="room-quiet" type="button">Quiet for this session</button><button id="room-clear-mode" type="button" class="secondary">Clear temporary mode</button></div><form id="room-companionship"><h4>Temporary companionship</h4><div class="room-dimensions">${dimensions.map(d=>`<label for="room-${d}">${pretty(d)}<input id="room-${d}" type="number" min="0" max="11" step="1" value="0" required></label>`).join('')}</div><label for="room-minutes">End after<select id="room-minutes"><option value="15">15 minutes</option><option value="30" selected>30 minutes</option><option value="60">1 hour</option></select></label><p class="muted">Requires existing consent, allowed output and the Assistant’s protected bounds. Clearing or expiry does not replay old opportunities.</p><button type="submit">Apply temporary companionship</button></form></details></details></div>
 <details class="room-simulation" hidden><summary>Synthetic opening test</summary><p>Choose a prepared case, enable its output here, then run it. These are simulated events; this form cannot establish identity, physical arrival, audience or consent.</p><form id="room-simulate"><div id="room-catalog" hidden><label for="room-case">Prepared synthetic case<select id="room-case"><option value="">Choose a case…</option></select></label><p id="room-case-status" role="status"></p><div class="actions"><button id="room-case-enable" type="button">Enable case output</button><button id="room-sources-refresh" type="button" class="secondary">Refresh prepared cases</button></div><p id="room-case-output-status" role="status">Openings off</p></div><details id="room-source-details" open><summary>Prepared source details</summary><div class="form-grid"><label for="room-source">Host occurrence ID<input id="room-source" required maxlength="200" autocomplete="off"></label><label for="room-kind">Prepared occurrence kind<select id="room-kind"><option value="availableCheckIn">Available check-in</option><option value="arrivalReturn">Arrival or return</option><option value="groundedFollowUp">Grounded follow-up</option></select></label></div><label for="room-topic">Prepared topic reference (if supplied by the host)<input id="room-topic" maxlength="200" autocomplete="off"></label></details><p class="muted">The host must already bind this occurrence to the signed-in synthetic subject and session. Suppression is a valid result; nothing will be retried or sent through another channel.</p><button id="room-run" type="submit">Run this synthetic opening</button></form></details>
 <section class="room-history" aria-label="Opening history"><div class="section-head"><h3>Recent openings</h3><button id="room-refresh" type="button" class="secondary">Refresh session & history</button></div><p id="room-history-status" class="muted">No history loaded. Refresh does not replay speech or text.</p><label for="room-opportunity">Inspect an opportunity<select id="room-opportunity"><option value="">No opportunities</option></select></label><div id="room-outcome"></div></section>`;
 const $=id=>anchor.querySelector('#room-'+id),auth=()=>window.lifestreamAuth;
 const compact=matchMedia('(max-width:1050px)'),setup=anchor.querySelector('.room-setup');setup.open=!compact.matches;compact.addEventListener('change',()=>{setup.open=!compact.matches;});
 let epoch=0,scopeKey='',session=null,configuration=null,readyMode=null,request=null,records=[],expressionNotes=[],history=[],busy=false,catalogEnabled=false,catalog=[];
 let capture,voiceScope=null,voiceEpoch=0;const voiceTurns=new Map();
 const deliveries=new Map();
 const scope=()=>{const c=context(),s=auth().session;if(auth().mode!=='local-password'||!s||!c?.assistantId)throw new Error('Sign in and select an Assistant first.');return {assistantId:c.assistantId,relationshipId:c.relationship?.relationshipId??null,sessionId:s.sessionId,principalId:s.principalId};};
 const route=s=>{if(!s.relationshipId)throw new Error('Select a relationship before enabling Initiative. Ordinary typed messages remain available.');return `/api/admin/v1/assistants/${s.assistantId}/relationships/${s.relationshipId}/initiative/v1`;};
 const same=(s,ticket)=>{try{return epoch===ticket&&JSON.stringify(scope())===JSON.stringify(s);}catch{return false;}};
 const status=(text,error=false)=>{$('status').textContent=text;$('status').classList.toggle('error',error);};
 const state=text=>{$('output-state').textContent=text;$('case-output-status').textContent=text;};
 const call=(body,s=scope(),signal)=>api(route(s),{method:'POST',...(signal?{signal}:{}),body:JSON.stringify({schemaVersion:'1.0.0',...body})});
 const renderBusy=()=>{for(const name of ['enable','case-enable','run','send','refresh','sources-refresh'])$(name).disabled=busy||(['run','case-enable'].includes(name)&&catalogEnabled&&!$('source').value)||(['enable','case-enable','run'].includes(name)&&!!(capture?.pending||capture?.speaking||output?.turn));$('mic-start').disabled=busy||capture?.active===true;$('mic-stop').disabled=!busy&&!capture?.active;};
 const run=fn=>async event=>{event?.preventDefault();const ticket=epoch;try{await fn();}catch(error){if(ticket===epoch)status(error.message,true);}};
 const mark=(entry,text)=>{entry.node.querySelector('.room-turn-state').textContent=text;};
 const addTurn=(role,text,metadata={})=>{
  anchor.querySelector('[data-room-empty]')?.remove();const node=document.createElement('li');node.className=`room-turn ${role}`;node.innerHTML=`<header><strong>${role==='user'?'You':'Assistant'}</strong><span class="room-turn-state"></span></header><p class="room-turn-text"></p>`;node.querySelector('.room-turn-text').textContent=text;
  const entry={role,text,node,...metadata};history.push(entry);$('turns').append(node);while(history.length>100){const old=history.shift();old.node.remove();if(old.interactionId)deliveries.delete(old.interactionId);}return entry;
 };
 const annotate=entry=>{
  entry.node.dataset.opportunityId=entry.opportunityId;entry.node.dataset.interactionId=entry.interactionId;
  const detail=document.createElement('details');detail.innerHTML=`<summary>Simulated opening · references</summary><dl class="record-fields"><dt>Opportunity</dt><dd class="record-id">${escape(entry.opportunityId)}</dd><dt>Conversation</dt><dd class="record-id">${escape(entry.conversationId)}</dd><dt>Interaction</dt><dd class="record-id">${escape(entry.interactionId)}</dd></dl>`;entry.node.append(detail);
  const dismiss=document.createElement('button');dismiss.type='button';dismiss.className='quiet';dismiss.textContent='Dismiss this opening';dismiss.onclick=run(async()=>{await call({operation:'dismiss',idempotencyKey:crypto.randomUUID(),sessionId:entry.scope.sessionId,opportunityId:entry.opportunityId},entry.scope);if(!same(entry.scope,entry.epoch))return;mark(entry,'Dismissed');if(output.turn?.trace===entry.interactionId)output.stop('Opening dismissed.');const inspected=await call({operation:'inspect'},entry.scope);if(same(entry.scope,entry.epoch))renderRecords(inspected);});entry.node.append(dismiss);
 };
 const output=new ConversationOutput({onState:state,onClosed:()=>{capture?.stop(false);renderBusy();},onError:error=>{capture?.stop();status(error.message,true);renderBusy();},
 onMessage:message=>{
  if(message.type==='turnStarted'){if(!same(voiceScope,voiceEpoch))throw new Error('Voice scope changed.');$('timing').textContent='No pending timing adjustment.';capture.receive(message);output.beginReply(message.interactionTraceId);renderBusy();return true;}
  if(message.type==='transcript'){if(!capture?.traces.has(message.interactionTraceId)||!same(voiceScope,voiceEpoch)||typeof message.text!=='string'||message.text.length>16000)throw new Error('Unexpected voice transcript.');const entry=addTurn('user',message.text);mark(entry,'Recognized voice');return true;}
  if(message.event?.payload.type==='terminal'){capture?.receive(message);renderBusy();}
  return false;
 },onReplyText:(trace,text)=>{if(!same(voiceScope,voiceEpoch))throw new Error('Voice scope changed.');let entry=voiceTurns.get(trace);if(!entry){entry=addTurn('assistant','',{interactionId:trace});voiceTurns.set(trace,entry);if(voiceTurns.size>64)voiceTurns.delete(voiceTurns.keys().next().value);}entry.text=text;entry.node.querySelector('.room-turn-text').textContent=text;mark(entry,'Voice response · playback pending');},onReplyComplete:trace=>{const entry=voiceTurns.get(trace);if(entry)mark(entry,'Voice playback finished locally');state('Openings off');if(capture?.active)capture.onState('Microphone on · speak to reply or interrupt');status('Voice reply completed. Openings remain off until you enable them.');renderBusy();},onStopped:(trace,reason)=>{const entry=deliveries.get(trace)||voiceTurns.get(trace);if(entry){entry.stopped=true;mark(entry,reason);}if(trace)state('Speech stopped');},onComplete:trace=>{
  const entry=deliveries.get(trace);if(!entry)return;
  void Promise.resolve().then(async()=>{await entry.acceptance;if(entry.stopped||!same(entry.scope,entry.epoch))return;await acknowledge(entry,'playbackCompleted');mark(entry,'Playback finished · receipt confirmed');state('Speech ready');}).catch(error=>{mark(entry,'Playback finished locally · receipt unconfirmed');if(same(entry.scope,entry.epoch))status(error.message,true);});
 }});
 capture=new ConversationCapture({output,current:()=>!!voiceScope&&same(voiceScope,voiceEpoch),onBegin:()=>{request?.abort();busy=false;void suspend().catch(error=>status(error.message,true));renderBusy();},onState:text=>{$('mic-status').textContent=text;renderBusy();},onError:error=>{if(voiceScope&&same(voiceScope,voiceEpoch))status(error.message,true);renderBusy();}});
 $('sensitivity').oninput=()=>capture.frames?.configure($('sensitivity').value);
 $('mic-stop').onclick=()=>{epoch++;busy=false;request?.abort();capture.stop();void suspend().catch(()=>{});status('Microphone stopped. Speech output must be enabled again.');renderBusy();};
 $('mic-start').onclick=run(async()=>{if(capture.active||busy)return;const s=scope(),ticket=epoch;busy=true;renderBusy();try{
  const connection=output.connected?Promise.resolve():output.connect();void connection.catch(()=>{});await suspend();await connection;if(!same(s,ticket))return;
  let value=await api('/api/runtime/v1/session-context');if(!value.endpoint)throw new Error('Review and apply session disclosure before starting the microphone.');if(!value.endpoint.inputModalities.includes('audio'))value=await api('/api/runtime/v1/session-context',{method:'POST',body:JSON.stringify({expectedRevision:value.revision,mode:'audio',audienceScope:value.endpoint.privacyClass==='personal'?'authenticatedSession':'unknown'})});
  if(!same(s,ticket))return;session=value;voiceScope=s;voiceEpoch=ticket;await capture.start({sessionId:s.sessionId,expectedSessionRevision:value.revision,endpointId:value.endpoint.endpointId,assistantId:s.assistantId,...(s.relationshipId?{relationshipId:s.relationshipId}:{})});if(!same(s,ticket))return;capture.frames.configure($('sensitivity').value);status('Microphone is on. Speak naturally to reply; openings remain separately controlled.');
 }catch(error){if(same(s,ticket))capture.stop();throw error;}finally{if(epoch===ticket){busy=false;renderBusy();}}});
 const acknowledge=async(entry,kind)=>{if(!same(entry.scope,entry.epoch))throw new Error('Conversation scope changed.');const result=await call({operation:'acknowledge',sessionId:entry.scope.sessionId,opportunityId:entry.opportunityId,receiptId:entry.receiptId,kind},entry.scope);if(same(entry.scope,entry.epoch))renderRecords(result);};
 const suspend=async({close=false}={})=>{
  let s;try{s=scope();}catch{}const mode=readyMode;readyMode=null;output.stop();if(close)output.close();state('Openings off');
  if(mode&&s)await call({operation:'outputReadiness',sessionId:s.sessionId,modality:mode,ready:false},s);
 };
 const selectCase=()=>{const selected=catalog.find(item=>item.id===$('case').value);$('source').value=selected?.id??'';$('kind').value=selected?.kind??'availableCheckIn';$('topic').value=selected?.topicRef??'';$('case-status').textContent=selected?`${selected.summary}. Enable ${selected.modality==='speech'?'speech':'text'} output here, then run this case.`:'Choose a case to inspect its source details.';renderBusy();return selected;};
 const renderSources=body=>{const old=$('case').value;catalogEnabled=body.explanations.some(e=>e.code==='synthetic_catalog_enabled');catalog=body.explanations.flatMap(e=>{const match=e.code.match(/^synthetic_occurrence_(arrivalReturn|availableCheckIn|groundedFollowUp)_(text|speech)$/);return match&&e.sourceRefs.length?[{id:e.sourceRefs[0],kind:match[1],modality:match[2],topicRef:e.sourceRefs[1]??null,summary:e.summary}]:[];});$('catalog').hidden=!catalogEnabled;$('source-details').open=!catalogEnabled;$('source').readOnly=catalogEnabled;$('topic').readOnly=catalogEnabled;$('kind').disabled=catalogEnabled;
  if(catalogEnabled){$('case').innerHTML='<option value="">Choose a case…</option>'+catalog.map(item=>`<option value="${escape(item.id)}">${escape(item.summary)}</option>`).join('');$('case').disabled=!catalog.length;if(catalog.some(item=>item.id===old))$('case').value=old;selectCase();if(!catalog.length)$('case-status').textContent=body.explanations.find(e=>['synthetic_catalog_empty','synthetic_catalog_unavailable'].includes(e.code))?.summary??'No prepared cases are available. Refresh after the host prepares one.';}
  renderBusy();
 };
 const clear=()=>{epoch++;request?.abort();request=null;readyMode=null;output.close();busy=false;renderBusy();session=null;configuration=null;deliveries.clear();voiceTurns.clear();voiceScope=null;history=[];records=[];expressionNotes=[];catalog=[];catalogEnabled=false;$('case').innerHTML='<option value="">Choose a case…</option>';$('catalog').hidden=true;$('turns').innerHTML='<li class="muted" data-room-empty>No messages in this page session.</li>';$('source').value='';$('topic').value='';$('message').value='';$('outcome').replaceChildren();$('timing').textContent='No pending timing adjustment.';$('opportunity').innerHTML='<option value="">No opportunities</option>';$('history-status').textContent='Refresh to inspect this scope.';anchor.querySelector('.room-simulation').hidden=true;state('Openings off');};
 const renderOutcome=()=>{const id=$('opportunity').value,op=records.find(r=>r.recordType==='opportunity'&&r.opportunityId===id),result=records.find(r=>r.recordType==='outcome'&&r.opportunityId===id);if(!op||!result){$('outcome').replaceChildren();return;}
  const rows=[['Status',pretty(result.state)],['Last observed stage',pretty(result.lastDeliveryStage)],['Acknowledgment',result.acknowledgmentKind?pretty(result.acknowledgmentKind):'Not observed'],['Response',pretty(result.response)],['Reason',result.reasonCodes.map(pretty).join(', ')],['Mode',op.executionMode==='simulation'?'Simulation — no physical arrival evidence':op.executionMode],['Occurred',new Date(result.occurredAt).toLocaleString()],['Expires',new Date(op.expiresAt).toLocaleString()],['Opportunity ID',id],['Conversation ID',op.conversationId],['Session ID',op.sessionId],['Configuration',`${op.configurationId} · revision ${op.configurationRevision}`]];
  const expression=expressionNotes.find(e=>e.sourceRefs.includes(id)),fields=(expression?.summary??'Observation: No expression metadata in this snapshot.').split('\n').map(line=>{const i=line.indexOf(':');return [line.slice(0,i),line.slice(i+1).trim()];});
  $('outcome').innerHTML=`<dl class="record-fields">${rows.slice(0,6).map(([k,v])=>`<dt>${escape(k)}</dt><dd>${escape(v)}</dd>`).join('')}</dl><details aria-label="Expression observations"><summary>Expression observations</summary><dl class="record-fields">${fields.map(([k,v])=>`<dt>${escape(k)}</dt><dd>${escape(v)}</dd>`).join('')}</dl></details><details><summary>Record identifiers, time & evidence</summary><dl class="record-fields">${rows.slice(6).map(([k,v])=>`<dt>${escape(k)}</dt><dd class="record-id">${escape(v)}</dd>`).join('')}</dl><p class="record-id">${escape(result.policyRevision)}</p><ul>${result.sourceRefs.map(ref=>`<li class="record-id">${escape(ref)}</li>`).join('')}</ul></details><p class="muted">Emission, endpoint acceptance and playback completion are different observations. None establishes Human reception.</p>`;
 };
 const renderRecords=body=>{if(body.operation==='inspect')$('timing').textContent=body.explanations.find(e=>e.code==='initiative_timing_feedback')?.summary||'No pending timing adjustment.';records=body.records||[];expressionNotes=(body.explanations||[]).filter(e=>e.code==='initiative_expression');const ops=records.filter(r=>r.recordType==='opportunity'),selected=$('opportunity').value;$('opportunity').innerHTML=ops.length?ops.map(op=>{const r=records.find(r=>r.recordType==='outcome'&&r.opportunityId===op.opportunityId);return `<option value="${escape(op.opportunityId)}">${escape(pretty(op.kind))} · ${escape(pretty(r?.state))} · ${escape(op.opportunityId.slice(0,8))}</option>`;}).join(''):'<option value="">No opportunities</option>';if(ops.some(op=>op.opportunityId===selected))$('opportunity').value=selected;$('history-status').textContent=`Snapshot at ${new Date().toLocaleTimeString()} · ${ops.length} recent opportunities. Refresh shows metadata only; payloads never replay.`;renderOutcome();};
 const refresh=async()=>{const s=scope(),ticket=epoch;$('history-status').textContent='Refreshing current metadata…';const value=await api('/api/runtime/v1/session-context');if(!same(s,ticket))return;session=value;$('scope').textContent=`${context()?.displayName||'Assistant'} · ${s.relationshipId?'Relationship selected':'No relationship selected'}`;$('disclosure').textContent=`Session revision ${value.revision} · ${value.endpoint?.privacyClass==='personal'?'Approved context allowed':'Unknown/shared audience; private context withheld'}.`;
  if(s.relationshipId){const result=await call({operation:'inspect'},s);if(!same(s,ticket))return;anchor.querySelector('.room-simulation').hidden=!result.explanations.some(e=>e.code==='synthetic_ingress_enabled');renderSources(result);configuration=result.records.find(r=>r.recordType==='configuration'&&r.configurationId===result.activeConfigurationId);renderRecords(result);for(const d of dimensions)$(d).value=configuration?.dimensions[d]??0;}
 };
 $('refresh').onclick=run(refresh);$('sources-refresh').onclick=run(refresh);$('case').onchange=run(async()=>{const selected=selectCase();if(selected&&$('modality').value!==selected.modality){await suspend({close:true});$('modality').value=selected.modality;}});$('opportunity').onchange=renderOutcome;
 const enableOutput=async()=>{const s=scope(),ticket=epoch,mode=$('modality').value;route(s);busy=true;renderBusy();try{
   // Resume Web Audio directly from the Human click, before asynchronous requests.
   const connection=mode==='speech'&&!output.connected?output.connect():Promise.resolve();void connection.catch(()=>{});
   await suspend();await connection;if(!same(s,ticket))throw new Error('Conversation changed during output setup.');
   let value=await api('/api/runtime/v1/session-context');if(!value.endpoint)throw new Error('Review and apply session disclosure before enabling output.');
   if(mode==='speech'&&!value.endpoint.outputModalities.includes('audio'))value=await api('/api/runtime/v1/session-context',{method:'POST',body:JSON.stringify({expectedRevision:value.revision,mode:'audio',audienceScope:value.endpoint.privacyClass==='personal'?'authenticatedSession':'unknown'})});
   if(!same(s,ticket))throw new Error('Conversation changed during output setup.');session=value;await call({operation:'outputReadiness',sessionId:s.sessionId,modality:mode,ready:true},s);if(!same(s,ticket))throw new Error('Conversation changed during output setup.');readyMode=mode;state(mode==='speech'?`Speech ready · microphone ${capture.active?'on':'off'}`:'Text openings ready');status('Output is ready. Current consent, audience and Initiative settings are still checked for each opening.');
  }catch(error){if(epoch===ticket)output.close();throw error;}finally{if(epoch===ticket){busy=false;renderBusy();}}};
 $('enable').onclick=run(enableOutput);$('case-enable').onclick=run(enableOutput);
 $('disable').onclick=run(()=>suspend({close:true}));$('modality').onchange=run(()=>suspend({close:true}));
 $('stop').onclick=run(async()=>{epoch++;busy=false;renderBusy();request?.abort();capture.stop();await suspend();await refresh();status('Stopped. Output will not resume until you enable it again.');});
 $('quiet').onclick=run(async()=>{await suspend();await call({operation:'temporaryMode',idempotencyKey:crypto.randomUUID(),sessionId:scope().sessionId,mode:'quiet',endsAt:null,dimensions:null});$('timing').textContent='No pending timing adjustment.';status('Quiet applies to this session until cleared or the host restarts.');});
 $('clear-mode').onclick=run(async()=>{await suspend();await call({operation:'temporaryMode',idempotencyKey:crypto.randomUUID(),sessionId:scope().sessionId,mode:'clear',endsAt:null,dimensions:null});$('timing').textContent='No pending timing adjustment.';status('Temporary mode cleared. Enable output separately; no old opening will resume.');});
 $('companionship').onsubmit=run(async()=>{const endsAt=new Date(Date.now()+Number($('minutes').value)*60000).toISOString();await call({operation:'temporaryMode',idempotencyKey:crypto.randomUUID(),sessionId:scope().sessionId,mode:'companionship',endsAt,dimensions:Object.fromEntries(dimensions.map(d=>[d,Number($(d).value)]))});status(`Temporary companionship applies until ${new Date(endsAt).toLocaleTimeString()}. Durable settings are unchanged.`);});
 $('simulate').onsubmit=run(async()=>{const s=scope(),ticket=epoch;if(!readyMode)throw new Error('Enable the selected output first.');if(catalogEnabled&&!catalog.some(item=>item.id===$('source').value&&item.modality===readyMode))throw new Error('Choose a current prepared case and enable its matching output first.');if(busy)throw new Error('Wait for the current request.');busy=true;renderBusy();const controller=request=new AbortController();try{
   const mode=readyMode;if(mode==='speech')output.expect();const result=await call({operation:'simulate',idempotencyKey:crypto.randomUUID(),sessionId:s.sessionId,sourceEventId:$('source').value.trim(),kind:$('kind').value,topicRef:$('topic').value.trim()||null},s,controller.signal);if(!same(s,ticket))return;renderRecords(result);const newest=records.find(r=>r.recordType==='opportunity');if(newest){$('opportunity').value=newest.opportunityId;renderOutcome();}
   const delivery=result.delivery;if(!delivery){output.waiting=false;status(result.explanations.map(e=>e.summary).join(' '));return;}
   const outcome=records.find(r=>r.recordType==='outcome'&&r.opportunityId===delivery.opportunityId),op=records.find(r=>r.recordType==='opportunity'&&r.opportunityId===delivery.opportunityId);
   if(delivery.sessionId!==s.sessionId||delivery.modality!==mode||readyMode!==mode||Date.parse(delivery.expiresAt)<=Date.now()||outcome?.state!=='emitted'||!outcome.deliveryReceiptRef||!op)throw new Error('Delivery no longer matches this ready conversation.');
   const entry=addTurn('assistant',delivery.text,{scope:s,epoch:ticket,opportunityId:delivery.opportunityId,interactionId:delivery.interactionId,conversationId:op.conversationId,receiptId:outcome.deliveryReceiptRef,stopped:false});deliveries.set(entry.interactionId,entry);annotate(entry);mark(entry,'Simulated opening · emitted');
   entry.acceptance=(mode==='speech'?output.accept(delivery):Promise.resolve()).then(()=>acknowledge(entry,'endpointAccepted'));await entry.acceptance;if(!same(s,ticket))return;
   if(!entry.stopped)mark(entry,mode==='speech'?'Endpoint accepted · playback pending':'Endpoint accepted');status('Synthetic opening received in this conversation. Human reception is not inferred.');
  }catch(error){if(epoch===ticket)output.stop(error.message);if(!controller.signal.aborted)throw error;}finally{if(request===controller)request=null;if(epoch===ticket){busy=false;renderBusy();}}});
 $('message-form').onsubmit=run(async()=>{const s=scope(),ticket=epoch,text=$('message').value.trim();if(!text||busy)return;busy=true;renderBusy();let entry,controller;try{capture.stop();await suspend();if(!same(s,ticket))return;addTurn('user',text);$('message').value='';entry=addTurn('assistant','');mark(entry,'Responding');controller=request=new AbortController();
  const response=await fetch('/api/runtime/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-lifestream-csrf':auth().session.csrfToken},body:JSON.stringify({assistantId:s.assistantId,...(s.relationshipId?{relationshipId:s.relationshipId}:{}),userInput:text}),signal:controller.signal});if(!response.ok)throw new Error(`Conversation request failed (${response.status}).`);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',completed=false;
   while(true){const {done,value}=await reader.read();if(done)break;if(!same(s,ticket))throw new Error('Conversation scope changed.');buffer+=decoder.decode(value,{stream:true});if(buffer.length>262144)throw new Error('Response exceeded its stream limit.');const chunks=buffer.split('\n\n');buffer=chunks.pop()||'';for(const chunk of chunks){const event=chunk.match(/^event: (.+)$/m)?.[1],raw=chunk.match(/^data: (.+)$/m)?.[1];if(!raw)continue;const data=JSON.parse(raw);if(event==='message.delta'){entry.text+=data.text||'';if(entry.text.length>64000)throw new Error('Response exceeded its display limit.');entry.node.querySelector('.room-turn-text').textContent=entry.text;}if(event==='interaction.error')throw new Error(data.message||'Response failed.');if(event==='interaction.completed')completed=true;}}
   if(!same(s,ticket))return;if(!completed)throw new Error('Response ended without a successful completion.');mark(entry,'Completed');$('timing').textContent='No pending timing adjustment.';status('Reply completed. Openings remain off until you enable them.');
  }catch(error){if(entry)mark(entry,controller?.signal.aborted?'Stopped':'Failed');if(!controller?.signal.aborted)throw error;}finally{if(request===controller)request=null;if(epoch===ticket){busy=false;renderBusy();}}
 });
 const scopeChanged=()=>{let next='';try{next=JSON.stringify(scope());}catch{}if(next===scopeKey)return;clear();scopeKey=next;$('scope').textContent=next?'Refresh to read this Assistant’s session.':'Sign in and select an Assistant.';if(next)void refresh().catch(error=>status(error.message,true));};
 for(const event of ['lifestream-auth','lifestream-assistant','lifestream-relationship'])window.addEventListener(event,scopeChanged);
 window.addEventListener('lifestream-session-context',()=>{clear();void refresh().catch(error=>status(error.message,true));});
 window.addEventListener('hashchange',()=>{if(location.hash!=='#conversation'){epoch++;busy=false;renderBusy();request?.abort();void suspend({close:true}).catch(()=>{});}});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){epoch++;busy=false;renderBusy();request?.abort();void suspend({close:true}).catch(()=>{});}});
 window.addEventListener('pagehide',()=>{request?.abort();output.close();});
 void auth().ready.then(scopeChanged);
}
