const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const name=value=>String(value).replace(/^attention/,'').replace(/^./,c=>c.toUpperCase());
export function installExperience({anchor,api,context}){
 const section=document.createElement('section');section.className='workflow-step experience-controls';section.setAttribute('aria-label','Learning from shared experience');section.innerHTML=`<h3>Learning from shared experience</h3><p>Optionally reflect on retained experiences and carry unfinished questions or projects forward. Automatic memory must already be enabled. This adds bounded, reversible attention preferences; it does not change the model, Core Persona or permissions.</p><p>Only currently permitted memory sources are used. Correcting, forgetting or withdrawing those sources removes dependent use. Reflection waits at least 60 seconds after conversation, uses one shared background slot and permits at most eight model calls per day.</p><div class="actions"><button type="button" data-action="experience-refresh">Refresh learning</button></div><p role="status">Select a relationship and refresh.</p><form data-role="settings"><label><input type="checkbox" data-enabled> Allow reflection and low-stakes learned preferences</label><label><input type="checkbox" data-frozen> Freeze learning and its conversational use</label><fieldset data-topics><legend>Topic boundaries</legend></fieldset><button type="submit" disabled>Apply learning settings</button></form><div data-role="inspection"></div><details><summary>Initial attention preferences</summary><p>Explicitly authored seeds are separate from learned experience. The active Assistant profile must allow the selected topic and automatic low-stakes changes.</p><form data-role="seed"><label>Topic <select data-dimension>${['Gardening','Astronomy','Reading','Cooking','Music','Games'].map(v=>`<option value="attention${v}">${v}</option>`).join('')}</select></label><label>Initial value <input data-value type="number" min="-1" max="1" step="0.05" value="0" required></label><button type="submit" disabled>Set initial preference</button></form></details><label><input type="checkbox" data-reset-confirm> I want to clear this relationship's learned workspace and preferences</label><button type="button" data-action="reset" disabled>Reset learning</button><div data-role="lineage"></div>`;anchor.append(section);
 let epoch=0,snapshot=null,busy=false;const status=section.querySelector('[role=status]'),settings=section.querySelector('[data-role=settings]');
 const scope=()=>{const c=context();if(!c?.assistantId||!c.relationship?.relationshipId)throw Error('Select an Assistant and relationship first.');return `/api/admin/v1/assistants/${c.assistantId}/relationships/${c.relationship.relationshipId}/experience/v1`;};
 const render=value=>{snapshot=value;const s=value.state;section.querySelector('[data-enabled]').checked=s.configuration.enabled;section.querySelector('[data-frozen]').checked=s.configuration.frozen;section.querySelector('[data-topics]').innerHTML='<legend>Topic boundaries</legend>'+Object.entries(s.configuration.topicPolicies).map(([topic,treatment])=>`<label>${escape(name(topic))}<select data-topic="${escape(topic)}">${[['ordinary','Ordinary'],['invitationRequired','Only when invited'],['disallowed','Exclude']].map(([key,label])=>`<option value="${key}" ${key===treatment?'selected':''}>${label}</option>`).join('')}</select></label>`).join('');
 section.querySelectorAll('button[type=submit]').forEach(b=>b.disabled=false);section.querySelector('[data-action=reset]').disabled=false;
 status.textContent=`${s.configuration.enabled?(s.configuration.frozen?'Frozen':'Enabled'):'Off'} · ${s.lastReason}. ${s.funnel.eligible} eligible episodes, ${s.funnel.calls} model calls, ${s.funnel.published} published results, ${s.funnel.noChange} no-change results, ${s.funnel.outputs} completed outputs after selection.`;
 section.querySelector('[data-role=inspection]').innerHTML=`<h4>Unfinished and resolved items</h4>${s.items.length?s.items.map(i=>`<article><strong>${escape(i.statement||'Invalidated item')}</strong><p>${escape(i.disposition)} · ${escape(i.topic)} · uncertainty ${escape(i.uncertainty)} · revision ${i.revision}</p><p>${escape(i.nextStep)}</p><small>${i.sourceRefs.length} retained source references</small></article>`).join(''):'<p>No workspace items yet.</p>'}<h4>Attention preferences</h4><div class="table-scroll"><table><thead><tr><th>Topic</th><th>Authored seed</th><th>Learned</th><th>Current</th></tr></thead><tbody>${s.imprints.map(i=>`<tr><td>${escape(name(i.dimension))}</td><td>${i.seed.toFixed(2)}</td><td>${i.learned.toFixed(2)}</td><td>${i.value.toFixed(2)}</td></tr>`).join('')}</tbody></table></div><h4>Background jobs</h4>${value.jobs.length?value.jobs.map(j=>`<p>${escape(j.state)} · ${escape(j.reason)} · ${j.attempts} charged attempts · tokens ${j.inputTokens??'unmeasured'} / ${j.outputTokens??'unmeasured'}</p>`).join(''):'<p>No jobs admitted.</p>'}`;
 const lineage=section.querySelector('[data-role=lineage]');lineage.innerHTML='<h4>Change history</h4>';for(const line of value.lineage){const row=document.createElement('p');row.textContent=`${line.operation} · ${new Date(line.at).toLocaleString()} · ${line.reversed?'reversed or invalidated':'retained'} · ${line.sourceRefs.length} source references. ${line.summary||''} Origin omitted from ordinary model context. `;if(['reflection','seed'].includes(line.operation)&&!line.reversed){const button=document.createElement('button');button.type='button';button.className='secondary';button.textContent='Reverse this change';button.onclick=run(()=>mutate({operation:'reverse',lineageId:line.id}));row.append(button);}lineage.append(row);}
 };
 const refresh=async()=>{const ticket=epoch,path=scope(),value=await api(path);if(ticket===epoch&&path===scope())render(value);};
 const mutate=async payload=>{if(!snapshot)throw Error('Refresh learning before making a change.');const ticket=epoch,path=scope();await api(path,{method:'POST',body:JSON.stringify({schemaVersion:'1.0.0',expectedRevision:snapshot.state.revision,...payload})});if(ticket===epoch&&path===scope())await refresh();};
 function run(fn){return async event=>{event?.preventDefault();if(busy)return;busy=true;const ticket=epoch;try{await fn();}catch(error){if(ticket===epoch)status.textContent=error.message;}finally{busy=false;}};}
 section.querySelector('[data-action=experience-refresh]').onclick=run(refresh);settings.onsubmit=run(()=>mutate({operation:'configure',enabled:section.querySelector('[data-enabled]').checked,frozen:section.querySelector('[data-frozen]').checked,retention:'sourceBound',topicPolicies:Object.fromEntries([...section.querySelectorAll('[data-topic]')].map(e=>[e.dataset.topic,e.value]))}));
 section.querySelector('[data-role=seed]').onsubmit=run(()=>mutate({operation:'seed',dimension:section.querySelector('[data-dimension]').value,value:Number(section.querySelector('[data-value]').value)}));
 section.querySelector('[data-action=reset]').onclick=run(async()=>{if(!section.querySelector('[data-reset-confirm]').checked)throw Error('Select the reset confirmation for this relationship first.');await mutate({operation:'reset'});section.querySelector('[data-reset-confirm]').checked=false;});
 const clear=()=>{epoch++;snapshot=null;section.querySelector('[data-enabled]').checked=false;section.querySelector('[data-frozen]').checked=false;section.querySelector('[data-reset-confirm]').checked=false;section.querySelector('[data-topics]').innerHTML='<legend>Topic boundaries</legend>';section.querySelector('[data-role=inspection]').replaceChildren();section.querySelector('[data-role=lineage]').replaceChildren();section.querySelectorAll('button[type=submit],[data-action=reset]').forEach(b=>b.disabled=true);status.textContent='Scope changed. Refresh this relationship.';};
 for(const event of ['lifestream-auth','lifestream-assistant','lifestream-relationship','lifestream-audience'])window.addEventListener(event,clear);document.addEventListener('visibilitychange',()=>{if(document.hidden)clear();});return {refresh,clear};
}
