export function installIncidentReview({anchor,api,context}){
 const section=document.createElement('section');section.className='room-incidents';section.setAttribute('aria-label','Incident evidence');section.innerHTML='<h3>Incident evidence</h3><p>Review retained PWCE incidents in this private session. Evidence stays with PWCE; reviewing it grants no capture or device permission.</p><div class="actions"><button type="button" data-incidents-refresh>Refresh incidents</button><button type="button" class="secondary" data-incidents-hide>Hide incident evidence</button></div><p role="status">Incident review has not been requested.</p><div data-incidents-list></div>';anchor.append(section);
 const list=section.querySelector('[data-incidents-list]'),status=section.querySelector('[role="status"]'),urls=new Set();let epoch=0,controller,visible=false,snapshot='';
 const text=(tag,value)=>{const n=document.createElement(tag);n.textContent=value;return n;};
 const clear=()=>{epoch++;controller?.abort();controller=null;visible=false;snapshot='';for(const url of urls)URL.revokeObjectURL(url);urls.clear();list.replaceChildren();status.textContent='Incident evidence hidden.';};
 const query=()=>{if(document.documentElement.dataset.audienceProtected==='true')throw Error('Use a private session before reviewing incidents.');const c=context();if(!c?.assistantId||!window.lifestreamAuth.session)throw Error('Sign in and select an Assistant first.');return new URLSearchParams({assistantId:c.assistantId});};
 const render=async()=>{clear();const ticket=epoch,params=query();controller=new AbortController();status.textContent='Loading incident evidence…';try{const data=await api('/api/runtime/v1/incidents?'+params,{signal:controller.signal});if(ticket!==epoch)return;visible=true;snapshot=JSON.stringify(data);status.textContent=(data.replay?'SIMULATED incident replay · ':'')+(data.incidents.length?data.incidents.length+' record(s).':'No retained incidents.');for(const i of data.incidents){const card=document.createElement('article');card.className='card';card.append(text('h4',i.eventClass+' · '+i.state),text('p',i.summary),text('p','Zone '+i.zoneRef+' · '+new Date(i.occurredAt).toLocaleString()),text('p','Requested: '+i.windowStart+' — '+i.windowEnd),text('p','Expires: '+new Date(i.expiresAt).toLocaleString()),text('p',i.evidenceRef),text('p',i.limitations.join(' ')));if(i.media)card.append(text('p','Actual coverage: '+i.media.actualStart+' — '+i.media.actualEnd));
 if(i.state==='ready'){const review=text('button','Review retained media'),close=text('button','Close retained media'),view=document.createElement('div'),message=text('p',''),controls=document.createElement('div');controls.className='actions';close.className='secondary';let url;const dispose=()=>{if(url){URL.revokeObjectURL(url);urls.delete(url);url=null;}view.replaceChildren();};review.onclick=async()=>{review.disabled=true;try{const mediaParams=query();mediaParams.set('evidenceRef',i.evidenceRef);const r=await fetch('/api/runtime/v1/incidents/media?'+mediaParams,{cache:'no-store',signal:controller.signal});if(!r.ok)throw Error('Media is unavailable or private access changed.');const blob=await r.blob();if(ticket!==epoch)return;dispose();url=URL.createObjectURL(blob);urls.add(url);const media=document.createElement(blob.type.startsWith('video/')?'video':'img');if(media.tagName==='VIDEO'){media.controls=true;media.preload='metadata';}else media.alt=data.replay?'Simulated incident evidence':'Retained incident evidence';media.src=url;view.append(media);message.textContent='Retained media loaded.';}catch(e){if(ticket===epoch)message.textContent=e.message;}finally{review.disabled=false;}};close.onclick=()=>{dispose();message.textContent='Media closed.';};controls.append(review,close);card.append(controls,message,view);}list.append(card);}
 }catch(e){if(ticket===epoch){clear();status.textContent=e.message;}}};
 section.querySelector('[data-incidents-refresh]').onclick=()=>void render().catch(e=>{status.textContent=e.message;});section.querySelector('[data-incidents-hide]').onclick=clear;
 for(const event of ['lifestream-auth','lifestream-assistant','lifestream-relationship','lifestream-session-context','lifestream-audience'])window.addEventListener(event,clear);document.addEventListener('visibilitychange',()=>{if(document.hidden)clear();});
 let checking=false;const timer=setInterval(async()=>{if(!visible||checking||document.hidden)return;checking=true;const ticket=epoch;try{const data=await api('/api/runtime/v1/incidents?'+query());if(ticket===epoch&&JSON.stringify(data)!==snapshot){clear();status.textContent='Incident evidence changed. Refresh to review current records.';}}catch{if(ticket===epoch){clear();status.textContent='Incident access could not be refreshed. Evidence hidden.';}}finally{checking=false;}},5000);window.addEventListener('pagehide',()=>{clearInterval(timer);clear();});
}
