const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={reserved:'Reserved · 2',friendly:'Friendly · 5',highlyEngaged:'Highly engaged · 11',selected:'Selected settings'};
export function installInitiativeLab({anchor,call,guard}){
 const section=document.createElement('section');section.className='workflow-step initiative-lab';section.setAttribute('aria-label','Initiative comparison Lab');
 section.innerHTML='<h4>4. Compare in the synthetic Lab</h4><p>Twelve identical events over fifty virtual minutes. Reference levels use synthetic text permission; your selected settings run separately with their configured restrictions. No real message, audio, microphone, activation or memory change occurs.</p><p data-lab-basis>Select and preview a revision above.</p><button type="button" data-lab-run disabled>Run comparison</button><p role="status" data-lab-status></p><div data-lab-results></div>';
 anchor.append(section);const button=section.querySelector('[data-lab-run]'),status=section.querySelector('[data-lab-status]'),results=section.querySelector('[data-lab-results]');let selected=null;
 button.onclick=guard(async ticket=>{if(!selected)throw new Error('Select and preview an Initiative revision first.');const id=selected.configurationId;status.textContent='Checking the isolated comparison…';const body=await call({operation:'compare',configurationId:id,scenario:'initiative-gradient-v1'},ticket);if(selected?.configurationId!==id)return;
  const complete=body.explanations.find(e=>e.code==='initiative_lab_complete');button.textContent=complete?'Run comparison again':'Check results';
  if(!complete){status.textContent=body.explanations[0]?.summary||'Comparison has no report yet.';results.replaceChildren();return;}
  status.textContent='Comparison completed. These are simulated endpoint outcomes, not real delivery.';
  const configs=body.records.filter(r=>r.recordType==='configuration'),ops=body.records.filter(r=>r.recordType==='opportunity'),outcomes=body.records.filter(r=>r.recordType==='outcome');
  const variants=Object.entries(names).map(([name,label])=>{const note=body.explanations.find(e=>e.code===`initiative_lab_${name}`),id=note?.sourceRefs[0],config=configs.find(c=>c.configurationId===id),own=ops.filter(o=>o.configurationId===id),delivered=own.filter(o=>outcomes.some(r=>r.opportunityId===o.opportunityId&&r.lastDeliveryStage==='acknowledged')),cases=body.explanations.filter(e=>e.code.startsWith(`initiative_lab_case_${name}_`));return {name,label,note,config,own,delivered,cases};});
  results.innerHTML=`<div class="table-scroll"><table class="extension-table initiative-lab-summary"><caption>Same events · fixture provider · isolated storage</caption><thead><tr><th>Settings</th><th>Simulated openings</th><th>Distinct topics</th><th>Suppressed / not admitted</th><th>Observed stage</th></tr></thead><tbody>${variants.map(v=>`<tr><th scope="row">${escape(v.label)}</th><td>${v.delivered.length}</td><td>${new Set(v.delivered.map(o=>o.topicKey)).size}</td><td>${v.cases.length-v.delivered.length}</td><td>${v.delivered.length?'Synthetic endpoint accepted':'No output'}</td></tr>`).join('')}</tbody></table></div><p>Reference counts use the same synthetic events and fixture provider. Selected settings keep their configured restrictions. These results do not prove model quality or real-world delivery.</p>${variants.map(v=>`<details><summary>${escape(v.label)} · event outcomes and reasons</summary><p>${escape(v.note?.summary)}</p><dl class="record-fields"><dt>Isolated configuration ID</dt><dd class="record-id">${escape(v.config?.configurationId)}</dd><dt>Hourly opening ceiling</dt><dd>${escape(v.config?.tuning.openingsPerHour)}</dd><dt>Minimum gap</dt><dd>${escape(v.config?.tuning.minimumGapSeconds)} seconds</dd></dl><table class="extension-table"><thead><tr><th>Minute</th><th>Outcome / reason</th></tr></thead><tbody>${v.cases.map(row=>`<tr><th scope="row">${escape(row.code.split('_').at(-1))}</th><td>${escape(row.summary)}</td></tr>`).join('')}</tbody></table></details>`).join('')}<details><summary>Comparison identity and limits</summary>${body.explanations.filter(e=>e.code==='initiative_lab_basis'||e.code==='initiative_lab_complete').map(e=>`<p>${escape(e.summary)}</p><ul>${e.sourceRefs.map(ref=>`<li class="record-id">${escape(ref)}</li>`).join('')}</ul>`).join('')}<p>The same fixture wording is used at every setting. Counts, topic selection and suppression—not wording differences—show the behavioral gradient. Speech-only selected settings have no eligible text sink in this scenario.</p></details>`;
 });
 const clear=()=>{selected=null;button.disabled=true;button.textContent='Run comparison';results.replaceChildren();status.textContent='';section.querySelector('[data-lab-basis]').textContent='Select and preview a revision above.';};
 return {select(record){clear();selected=record;button.disabled=false;section.querySelector('[data-lab-basis]').textContent=`Selected revision ${record.revision} · ${record.lifecycle}. Comparison does not activate this revision.`;},invalidate:clear};
}
