// This module accepts only explicitly selected browser File objects. It has no
// directory picker, connector, provider, execution or automatic admission path.
export function installProfileBuilder({ anchor, api: transport, context, show, onAdmitted }) {
  const section = document.createElement('section'); section.className = 'memory-tools profile-builder';
  section.innerHTML = `<div class="section-head"><div><p class="eyebrow">PEOPLE &amp; CONTEXT</p><h3>Build Context From Selected Files</h3></div></div>
    <p class="muted">Inventory your selected files, pin a local snapshot, then review each extracted claim. Nothing enters ordinary conversation until you explicitly approve and admit it. All imported text stays untrusted.</p>
    <div id="builder-prerequisite" class="notice blue" role="status" aria-live="polite" hidden></div>
    <div class="form-grid"><label>Declared Format<select id="builder-format"><option value="notes-v1">UTF-8 Notes v1</option><option value="canonical-user-profile-v1">Canonical User Profile JSON</option><option value="profile-v1">Structured Profile v1.0.0</option><option value="conversation-v1">Conversation JSON v1.0.0</option><option value="conversation-ndjson-v1">Conversation NDJSON v1</option></select></label>
    <label>Source Author<select id="builder-author"><option value="unknown">Unknown / Observation</option><option value="user">Me / User-Authored</option><option value="assistant">Assistant-Generated</option></select></label>
    <label>Original Source Date (Optional)<input id="builder-date" type="datetime-local"></label><label>Selected Files<input id="builder-files" type="file" multiple accept=".txt,.md,.json,.jsonl,.ndjson"></label></div>
    <label><input id="builder-owned" type="checkbox"> These files concern me and are mine to import; excluded third-party records and credentials are absent.</label>
    <p class="muted">Up to 8 files, 64 KiB each and 256 KiB total; at most 256 candidates and 16,384 text units. Local parsers only. Archives, directories, credential files, live connectors, cloud extraction and training are unsupported. Original dates may remain unknown.</p>
    <details><summary>Supported Structured Formats</summary><p>Canonical User Profile JSON accepts the UserProfile 1.0.0 export for your authenticated subject, with scalar declarations. It does not import sharing permissions, consent or training approval. Other subjects, revoked profiles and complex values are rejected.</p><p>Profile JSON uses schemaVersion "1.0.0", kind "user-profile", subject "self", and records with key, value, basis, optional eventAt and sensitivity. Basis is userDeclaration, observation, quoted, assistantGenerated or modelInference. Conversation JSON uses kind "conversation", subject "self", and messages with role, content and optional createdAt; roles are user, assistant or quoted. NDJSON contains one such message per line. Notes use one nonempty line per candidate.</p></details>
    <div class="actions"><button id="builder-inventory" type="button">Inventory Selection</button><button id="builder-refresh" type="button" class="secondary">Refresh Jobs</button></div>
    <label>Saved Import Job<select id="builder-jobs"><option value="">Start relationship review first</option></select></label>
    <div id="builder-status" role="status" aria-live="polite"></div><div class="actions"><button id="builder-snapshot" type="button" class="secondary" disabled>Collect Pinned Snapshot</button><button id="builder-extract" type="button" disabled>Extract Candidates</button><button id="builder-resume" type="button" class="secondary" disabled>Resume Pinned Snapshot</button><button id="builder-cancel" type="button" class="quiet" disabled>Cancel Collection</button></div>
    <div id="builder-candidates" class="revisions"></div><div class="actions"><button id="builder-approve" type="button" disabled>Approve Selected</button><button id="builder-reject" type="button" class="quiet" disabled>Reject Selected</button><button id="builder-admit" type="button" disabled>Admit Approved Selection</button></div>`;
  anchor.after(section);
  const get = (id) => section.querySelector(`#${id}`);
  const renderPrerequisite = () => {
    const current = context(), missingAssistant = !current?.assistantId, missingRelationship = !missingAssistant && !current?.relationship;
    const notice = get('builder-prerequisite');
    notice.hidden = !(missingAssistant || missingRelationship);
    notice.innerHTML = missingAssistant
      ? '<strong>Select an Assistant first.</strong> Use the Assistant list, then return here.'
      : '<strong>Start the relationship review first.</strong> Open <a href="#relationship">Relationship setup</a>, click <strong>Start relationship review</strong>, and return here. This import belongs to that selected relationship.';
    get('builder-inventory').disabled = missingAssistant || missingRelationship;
  };
  const escape = (s) => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  let selected = null, job = null, candidates = [], scopeKey = null, epoch = 0;
  const api=async(...args)=>{const ticket=epoch,key=context()?.relationship?.relationshipId,result=await transport(...args);if(ticket!==epoch||key!==context()?.relationship?.relationshipId)throw new Error('Import scope changed; refresh the selected relationship.');return result;};
  const clear=()=>{epoch++;selected=null;job=null;candidates=[];scopeKey=null;get('builder-files').value='';get('builder-candidates').replaceChildren();get('builder-status').replaceChildren();get('builder-jobs').innerHTML='<option value="">Refresh this relationship’s jobs</option>';for(const id of ['builder-snapshot','builder-extract','builder-resume','builder-cancel','builder-approve','builder-reject','builder-admit'])get(id).disabled=true;renderPrerequisite();};
  window.addEventListener('lifestream-assistant',clear);window.addEventListener('lifestream-auth',clear);window.addEventListener('lifestream-relationship',renderPrerequisite);
  renderPrerequisite();
  const path = () => { const current = context(); if (!current?.assistantId || !current?.relationship) { renderPrerequisite(); throw new Error('Open Relationship setup and click Start relationship review first.'); } const key = `${current.assistantId}/${current.relationship.relationshipId}`; if (scopeKey !== key) { if (scopeKey !== null) get('builder-files').value = ''; scopeKey = key; job = null; candidates = []; selected = null; } return `/api/admin/v1/assistants/${current.assistantId}/relationships/${current.relationship.relationshipId}/profile-builder`; };
  const render = (body) => {
    job = body.job; candidates = body.candidates || [];
    if (job.status !== 'inventoried') { selected = null; get('builder-files').value = ''; }
    get('builder-status').innerHTML = `<p><strong>${escape(job.status)}</strong> · Job Revision ${job.revision} · Collection Access ${escape(job.collectionAccess)} · Egress ${escape(job.egress)}</p><small>Snapshot ${escape(job.snapshotDigest)}</small>${job.failure ? `<p class="result error">${escape(job.failure)}</p>` : ''}<ul>${job.sources.map(s => `<li>${escape(s.path)} — ${s.byteLength} bytes · ${escape(s.format)} · original date ${escape(s.observedAt || 'unknown')}</li>`).join('')}</ul>${job.outcomes.length ? `<p>${job.outcomes.map(o => `${escape(o.status)}${o.reason ? ': ' + escape(o.reason) : ''}`).join(' · ')}</p>` : ''}`;
    get('builder-snapshot').disabled = job.status !== 'inventoried' || !selected;
    get('builder-extract').disabled = job.status !== 'snapshotted'; get('builder-resume').disabled = job.status !== 'failed';
    get('builder-cancel').disabled = ['review', 'cancelled'].includes(job.status);
    for (const id of ['builder-approve', 'builder-reject', 'builder-admit']) get(id).disabled = job.status !== 'review' || !candidates.length;
    get('builder-candidates').innerHTML = candidates.map(c => `<div class="revision builder-candidate" data-id="${escape(c.candidateId)}"><label><input type="checkbox" data-select> Select ${escape(c.key)} — ${escape(c.status)} (Revision ${c.revision})</label><label>Review / Correct Value<textarea data-value rows="3" ${c.status === 'admitted' ? 'disabled' : ''}>${escape(c.value)}</textarea></label><small>Subject ${escape(c.subjectId)} · ${escape(c.evidenceBasis)} · ${escape(c.sensitivity)} · uncertainty ${escape(c.uncertainty)}</small><small>Event ${escape(c.observedAt || 'unknown')} · Source ${escape(c.sourceDate || 'unknown')} · ${escape(c.locator)} · ${escape(c.sourceDigest)}</small><small>Source family ${escape(c.sourceFamily)} · local extraction ${escape(c.extractionVersion)} · imported content is untrusted</small><label>Approved Use<select data-use ${c.status === 'admitted' ? 'disabled' : ''}><option value="retain" ${!c.approvedUse?.personalization ? 'selected' : ''}>Retain Reviewed Only</option><option value="relationship" ${c.approvedUse?.personalization ? 'selected' : ''}>Personalize / Mention in This Relationship</option></select></label>${c.conflicts.length ? `<label><input data-conflict type="checkbox" ${c.conflictDisposition === 'retain' ? 'checked' : ''}> Retain ${c.conflicts.length} unresolved conflict(s) visibly</label>` : ''}<small>Training remains excluded. Admitted records use normal relationship correction / forgetting operations.</small></div>`).join('') || '<p class="muted">No extracted candidates. Inventory and snapshot collection do not approve context.</p>';
  };
  const refresh = async () => { const base = path(); const body = await api(base); get('builder-jobs').innerHTML = '<option value="">Select a saved job</option>' + body.jobs.map(j => `<option value="${escape(j.jobId)}">${escape(j.status)} · ${escape(j.sources.map(s => s.path).join(', '))}</option>`).join(''); if (job && body.jobs.some(j => j.jobId === job.jobId)) { get('builder-jobs').value = job.jobId; render(await api(`${base}/${job.jobId}`)); } };
  const guard = (operation) => async () => { try { await operation(); } catch (error) { show(error.message, true); } };
  get('builder-inventory').onclick = guard(async () => {
    const base = path(); if (!get('builder-owned').checked) throw new Error('Confirm the explicit ownership and exclusion scope before inventory.');
    const files = [...get('builder-files').files]; if (!files.length || files.length > 8 || files.some(f => f.size > 65536) || files.reduce((n, f) => n + f.size, 0) > 262144) throw new Error('Select 1–8 files within the declared byte limits.');
    const format = get('builder-format').value, authoredBy = get('builder-author').value, observedAt = get('builder-date').value ? new Date(get('builder-date').value).toISOString() : null;
    selected = await Promise.all(files.map(async f => ({ name: f.name, format, content: await f.text(), authoredBy, observedAt, ownedBySubject: true })));
    render(await api(base, { method: 'POST', body: JSON.stringify({ files: selected }) })); await refresh(); show('Inventory pinned. Collect the matching snapshot explicitly before extraction.');
  });
  get('builder-refresh').onclick = guard(refresh);
  get('builder-jobs').onchange = guard(async () => { if (get('builder-jobs').value) { const base = path(); selected = null; render(await api(`${base}/${get('builder-jobs').value}`)); } });
  const mutate = async (action, extra = {}) => { const base = path(); if (!job) throw new Error('Select an import job first.'); render(await api(`${base}/${job.jobId}/${action}`, { method: 'POST', body: JSON.stringify({ expectedRevision: job.revision, ...extra }) })); };
  get('builder-snapshot').onclick = guard(async () => { if (!selected) throw new Error('Reselect and inventory the original files before collection.'); await mutate('snapshot', { files: selected }); selected = null; get('builder-files').value = ''; render({ job, candidates }); show('Immutable local snapshot collected. Collection access is closed.'); });
  const extract = async action => { await mutate(action); selected = null; for (let i = 0; i < 16 && job?.status === 'extracting'; i++) { await new Promise(resolve => setTimeout(resolve, 250)); const base = path(); if (!job) return; render(await api(`${base}/${job.jobId}`)); } show(job?.status === 'review' ? 'Extraction completed. Candidates remain inactive until reviewed and admitted.' : 'Extraction state updated; refresh for its current disposition.'); };
  get('builder-extract').onclick = guard(() => extract('extract')); get('builder-resume').onclick = guard(() => extract('resume'));
  get('builder-cancel').onclick = guard(async () => { await mutate('cancel'); selected = null; get('builder-files').value = ''; show('Collection cancelled. Snapshot removed and stale work fenced.'); });
  const selection = () => [...get('builder-candidates').querySelectorAll('[data-id]')].filter(row => row.querySelector('[data-select]').checked).map(row => ({ row, candidate: candidates.find(c => c.candidateId === row.dataset.id) }));
  const review = async decision => { const items = selection().map(({ row, candidate }) => ({ candidateId: candidate.candidateId, expectedRevision: candidate.revision, decision, value: row.querySelector('[data-value]').value, use: { personalization: row.querySelector('[data-use]').value === 'relationship', mention: row.querySelector('[data-use]').value === 'relationship', training: false }, retainConflicts: !!row.querySelector('[data-conflict]')?.checked })); if (!items.length) throw new Error('Select the exact candidates to review.'); await mutate('review', { items }); show('Review decisions saved. Admission remains a separate step.'); };
  get('builder-approve').onclick = guard(() => review('approved')); get('builder-reject').onclick = guard(() => review('rejected'));
  get('builder-admit').onclick = guard(async () => { const items = selection().map(({ candidate }) => ({ candidateId: candidate.candidateId, expectedRevision: candidate.revision })); if (!items.length) throw new Error('Select the approved candidates to admit.'); await mutate('admit', { expectedRelationshipRevision: context().relationship.revision, items }); await onAdmitted(); show('Per-item admission outcomes recorded. No training, sharing or configuration authority was imported.'); });
  return { refresh };
}
