export function installRelationshipAdministration({ anchor, api: transport, context, show, refreshRelationship }) {
 const api=async(...args)=>{const ticket=epoch;const result=await transport(...args);if(ticket!==epoch)throw new Error('Administration scope changed; refresh the current selection.');return result;};
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const section = document.createElement('section'); section.className = 'memory-tools'; section.id = 'relationship-administration'; anchor.after(section);
  section.innerHTML = `<h3>Relationship Record Explorer</h3><p id="record-scope" class="muted">Select an Assistant and your relationship.</p><div id="record-overview"></div>
    <div class="record-toolbar"><label>Category<select id="record-filter"><option value="all">All Records</option>${['declaration','episode','semantic','convention','hypothesis','procedure','thread','commitment'].map(value=>`<option>${value}</option>`).join('')}</select></label><label>Search records<input id="record-search" type="search" placeholder="Content or record ID"></label><label>Lifecycle<select id="record-status"><option value="all">All states</option><option>pending</option><option>approved</option><option>superseded</option><option>rejected</option><option>forgotten</option></select></label><button id="records-refresh" type="button">Refresh Records</button><button id="records-export" type="button" class="secondary">Export My Relationship</button></div>
    <details id="record-create-panel"><summary>＋ Declare new context</summary><div class="form-grid"><label>Category<select id="record-category">${['declaration','episode','semantic','convention','hypothesis','procedure','thread','commitment'].map(value=>`<option>${value}</option>`).join('')}</select></label><label>Use After Review<select id="record-lane"><option value="relevant">When Relevant</option><option value="baseline">Always Include Convention</option><option value="correction">Direct Correction</option></select></label><label>Original Event Date (Optional)<input id="record-event" type="datetime-local"></label><label>Sensitivity<select id="record-sensitivity"><option value="personal">Personal</option><option value="sensitive">Sensitive</option></select></label></div><label>Declaration<textarea id="record-content" rows="3" maxlength="4000"></textarea></label><p class="muted">Authored context starts pending. An episode entered here is an attributed account, not a verified shared event. Review before ordinary use.</p><button id="record-declare" type="button">Save Pending Declaration</button></details>
    <div id="record-list" class="revisions"></div><dialog id="record-operation-panel" class="record-dialog" aria-labelledby="record-operation-title" hidden><h4 id="record-operation-title"></h4><p id="record-operation-subject"></p><span id="record-operation-id" class="record-id"></span><label id="record-operation-text-label"><span id="record-operation-field-name">Replacement / Annotation</span><textarea id="record-operation-text" rows="3" maxlength="4000"></textarea></label><label id="record-conflict-label" hidden>Conflict decision<select id="record-conflict"><option value="retain">Retain both as unresolved; withhold both</option><option value="resolve">Keep this record; reject the selected alternative</option></select></label><label id="record-other-label">Other Compatible Record<select id="record-other"></select></label><p id="record-operation-help" class="muted"></p><div class="actions"><button id="record-operation-apply" type="button">Apply Reviewed Operation</button><button id="record-operation-cancel" type="button" class="quiet">Cancel</button></div></dialog>`;
  const get = id => section.querySelector(`#${id}`); let relationship = null, selectedOperation = null, epoch = 0, lastOverview = null, operationTrigger = null;
  const base = () => { const value = context(); if (!value?.relationship) throw new Error('Select an owned relationship first.'); return `/api/admin/v1/assistants/${value.assistantId}/relationships/${value.relationship.relationshipId}`; };
  const guard = fn => async () => { try { await fn(); } catch(error) { if(get('record-operation-panel').open)get('record-operation-help').textContent=error.message;show(error.message, true); } };
  const download = (value, name) => { const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000); };
  const render = body => {
    relationship = body.relationship; const overview=body.overview;lastOverview=overview; get('record-scope').textContent=`Assistant → Relationships → ${relationship.userId} · Revision ${relationship.revision}. Only this authenticated subject's relationship is shown.`;
    get('record-overview').innerHTML=`<div class="record-stats"><p><strong>${overview.activeRecords}</strong> Approved Records</p><p><strong>${overview.pendingReview}</strong> Need Review</p><p><strong>${overview.retainedConflicts}</strong> Retained Conflicts</p><p><strong>${overview.sourceFamilies}</strong> Attributed Source Families</p></div><details class="record-overview-notes"><summary>Coverage, sources and uncertainty</summary><p>${esc(overview.coverage)}</p><p class="muted">${esc(overview.verifiedEventsLimitation)} Latest Record: ${esc(overview.latestRecordAt||'Unknown')}. High Uncertainty: ${overview.highUncertainty}. Source labels do not prove independence. Use Settings & replies for active settings and Persona proposals for adaptations.</p></details>`;
    const query=get('record-search').value.toLowerCase();
    const filtered=relationship.candidates.filter(record=>(get('record-filter').value==='all'||(record.category||'declaration')===get('record-filter').value)&&(get('record-status').value==='all'||record.status===get('record-status').value)&&`${record.content} ${record.candidateId}`.toLowerCase().includes(query));
    get('record-list').innerHTML=filtered.length?`<table class="record-table"><caption class="muted">${filtered.length} records · Select Details &amp; actions to inspect evidence or make a change.</caption><thead><tr><th scope="col">Record / identifier</th><th scope="col">Category / state</th><th scope="col">Use / importance</th><th scope="col">Review</th></tr></thead>${filtered.map(record=>{
      const id=esc(record.candidateId),withheld=record.suppressed||record.audience==='ownerOnly'||record.approvedUse?.personalization===false;
      const fields=[['Subject',relationship.userId],['Asserted by',record.assertedBy||relationship.userId],['Evidence basis',record.evidenceBasis||'attributed declaration'],['Uncertainty',record.uncertainty],['Source',record.source],['Source families',(record.sourceFamilies||[record.sourceFamily]).join(', ')],['Original event',record.eventAt||record.builder?.observedAt||'Unknown'],['Created',record.createdAt||'Unknown'],['Sensitivity',record.sensitivity||'personal'],['Derived from',(record.derivedFrom||[]).join(', ')||'None'],['Conflicts',(record.conflicts||[]).map(item=>`${item.recordId}: ${item.status}`).join(', ')||'None'],['Audience',record.audience||'authenticatedSession'],['Mention',record.approvedUse?.mention===false?'Restricted; withheld before inference':'Only in permitted context'],['Training','Excluded'],['Sharing','No cross-Assistant sharing']];
      return `<tbody class="record-card" data-record="${id}"><tr data-record="${id}" data-status="${esc(record.status)}"><td data-label="Record"><strong>${esc(record.content||'Forgotten record')}</strong><span class="record-id">ID ${id}</span><small>Revision ${record.revision}</small></td><td data-label="Category & state">${esc(record.category||'declaration')}<br><span class="status ${esc(record.status)}">${esc(record.status)}</span></td><td data-label="Use & importance">${withheld?'Withheld':record.status==='approved'?'Eligible in authorized session':'Inactive'}<br><small>${record.salience==='operatorPinned'?'Operator-Pinned Salience (Not Truth)':'Normal priority'}</small></td><td data-label="Review"><button class="secondary" data-expand="${id}" aria-expanded="false" aria-controls="detail-${id}">Details &amp; actions</button></td></tr>
      <tr class="record-detail" data-record="${id}" id="detail-${id}" hidden><td colspan="4"><h4>Evidence, permissions &amp; history</h4><dl class="field-list">${fields.map(([label,value])=>`<dt>${esc(label)}</dt><dd>${esc(value)}</dd>`).join('')}</dl><h4>Annotations</h4>${(record.annotations||[]).map(item=>`<p>${esc(item.text)} <small>— ${esc(item.actor)}</small></p>`).join('')||'<p class="muted">No annotations yet. Choose Annotate below to add a review note.</p>'}<details><summary>Lifecycle history</summary><ol>${(record.history||[]).map(item=>`<li>${esc(item.operation)} · Revision ${item.revision} · ${esc(item.actor)} · ${esc(item.at)}</li>`).join('')||'<li>No later lifecycle operations</li>'}</ol></details><div class="actions">${record.status==='pending'?'<button data-review="approved">Approve</button><button data-review="rejected" class="quiet">Reject</button>':''}${record.status!=='forgotten'?(record.status==='superseded'?['forget']:['correct','annotate','split','merge','supersede','conflict','pin','suppress','restrict-mention','narrow-audience','exclude-training','forget',...(record.category==='hypothesis'||record.evidenceBasis==='modelInference'?['reject-inference']:[])]).map(op=>`<button type="button" class="quiet" data-operation="${op}">${esc(op.replaceAll('-',' '))}</button>`).join(''):''}</div></td></tr></tbody>`;
    }).join('')}</table>`:'<p class="record-empty">No records match this view. Declare new context or review selected files in Import &amp; review.</p>';

  };
  const refresh = async () => { const ticket=epoch, path=base(); const body=await api(path+'/records');if(ticket===epoch&&path===base())render(body); };
  get('record-status').onchange=guard(refresh);get('record-search').oninput=()=>{if(relationship)render({relationship,overview:lastOverview});};get('records-refresh').onclick=guard(refresh);get('record-filter').onchange=guard(refresh);get('records-export').onclick=guard(async()=>download(await api(base()+'/export'),'relationship-context.json'));
  get('record-declare').onclick=guard(async()=>{ const scope=context();await api(base()+'/candidates',{method:'POST',body:JSON.stringify({content:get('record-content').value,category:get('record-category').value,contextUse:get('record-lane').value,eventAt:get('record-event').value?new Date(get('record-event').value).toISOString():null,sensitivity:get('record-sensitivity').value,source:'authenticated-declaration',sourceFamily:`user:${scope.relationship.userId}`,uncertainty:'high',expectedRevision:scope.relationship.revision,idempotencyKey:crypto.randomUUID()})});get('record-content').value='';await refreshRelationship();await refresh();show('Declaration saved for explicit review.'); });
  get('record-list').onclick=async event=>{const button=event.target.closest('button');const card=button?.closest('[data-record]');if(!card)return;const record=relationship?.candidates.find(item=>item.candidateId===card.dataset.record);if(!record)return;
    try { if(button.dataset.expand){const detail=get('detail-'+button.dataset.expand);detail.hidden=!detail.hidden;button.setAttribute('aria-expanded',String(!detail.hidden));return;} if(button.dataset.review){await api(base()+`/candidates/${record.candidateId}/decision`,{method:'POST',body:JSON.stringify({decision:button.dataset.review,expectedRevision:relationship.revision,idempotencyKey:crypto.randomUUID()})});await refreshRelationship();await refresh();return;}
      if(button.dataset.operation){selectedOperation={record,operation:button.dataset.operation};operationTrigger=button;get('record-operation-panel').hidden=false;get('record-operation-panel').showModal();get('record-operation-title').textContent=`Review ${selectedOperation.operation.replaceAll('-',' ')}`;get('record-operation-subject').textContent=record.content;get('record-operation-id').textContent=`Record ID ${record.candidateId} · Revision ${record.revision}`;get('record-operation-text-label').hidden=!['correct','supersede','annotate','split','merge'].includes(selectedOperation.operation);get('record-operation-field-name').textContent=selectedOperation.operation==='annotate'?'Review note':selectedOperation.operation==='split'?'New records, one per line':'Replacement text';get('record-conflict-label').hidden=selectedOperation.operation!=='conflict';get('record-conflict').value='retain';get('record-operation-text').value=['correct','supersede'].includes(selectedOperation.operation)?record.content:'';get('record-other').innerHTML=relationship.candidates.filter(item=>item.candidateId!==record.candidateId&&['approved','pending'].includes(item.status)).map(item=>`<option value="${esc(item.candidateId)}">${esc(item.content.slice(0,100))} (r${item.revision})</option>`).join('');get('record-other-label').hidden=!['merge','conflict'].includes(selectedOperation.operation);get('record-operation-help').textContent=selectedOperation.operation==='split'?'Enter two to four parts, one per line. Original evidence family and use restrictions remain attached.':selectedOperation.operation==='conflict'?'Choose whether to withhold both conflicting records or keep this record and reject the selected alternative.':selectedOperation.operation==='forget'?'Remove this record and its derived payloads, cancel affected jobs and fence stale imports/restore. External exports and backups require their own deletion.':'Review this explicit revision before applying. Restrictions withhold context before inference; pinning changes operator salience only.';const meanings={pin:'Give this record higher operator priority. Pinning does not establish truth or automatically include it in every reply.',suppress:'Keep this record for your review but withhold it from personalization.','restrict-mention':'Withhold this record before inference so its contents cannot be mentioned by the model.','narrow-audience':'Restrict this record to owner-only administration and withhold it from ordinary session personalization.','exclude-training':'Exclude this record from training. This does not grant or revoke separate personalization approval.'};if(meanings[selectedOperation.operation])get('record-operation-help').textContent=meanings[selectedOperation.operation];(get('record-operation-text-label').hidden?get('record-operation-cancel'):get('record-operation-text')).focus();}
    }catch(error){show(error.message,true);}
  };
  const closeOperation=()=>{selectedOperation=null;get('record-operation-panel').close();get('record-operation-panel').hidden=true;operationTrigger?.focus();};get('record-operation-cancel').onclick=closeOperation;get('record-operation-panel').addEventListener('cancel',event=>{event.preventDefault();closeOperation();});
  get('record-operation-apply').onclick=guard(async()=>{if(!selectedOperation)return;const {record,operation}=selectedOperation,other=relationship.candidates.find(item=>item.candidateId===get('record-other').value);await api(base()+`/records/${record.candidateId}/operations`,{method:'POST',body:JSON.stringify({operation,expectedRevision:relationship.revision,expectedRecordRevision:record.revision,idempotencyKey:crypto.randomUUID(),content:get('record-operation-text').value,text:get('record-operation-text').value,contents:get('record-operation-text').value.split('\n'),otherRecordId:other?.candidateId,otherRecordRevision:other?.revision,disposition:operation==='conflict'?get('record-conflict').value:get('record-operation-text').value.trim(),pinned:true})});selectedOperation=null;get('record-operation-panel').close();get('record-operation-panel').hidden=true;await refreshRelationship();await refresh();get('record-list').tabIndex=-1;get('record-list').focus({preventScroll:true});show('Reviewed record operation applied.');});
  const clear=event=>{if(event?.type==='lifestream-auth'||event?.type==='lifestream-assistant'){get('record-search').value='';get('record-content').value='';get('record-event').value='';}get('record-operation-text').value='';get('record-operation-title').textContent='';get('record-operation-subject').textContent='';get('record-operation-id').textContent='';get('record-other').replaceChildren();epoch++;relationship=null;selectedOperation=null;get('record-list').replaceChildren();get('record-overview').replaceChildren();get('record-operation-panel').close();get('record-operation-panel').hidden=true;get('record-scope').textContent='Select an Assistant and your relationship.';};
  window.addEventListener('lifestream-assistant',clear);window.addEventListener('lifestream-auth',clear);window.addEventListener('lifestream-relationship',()=>{clear();if(context()?.relationship)void guard(refresh)();});
  return { refresh };
}
