export function installRelationshipAdministration({ anchor, api: transport, context, show, refreshRelationship }) {
 const api=async(...args)=>{const ticket=epoch;const result=await transport(...args);if(ticket!==epoch)throw new Error('Administration scope changed; refresh the current selection.');return result;};
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const section = document.createElement('section'); section.className = 'memory-tools'; section.id = 'relationship-administration'; anchor.after(section);
  section.innerHTML = `<h3>Relationship Record Explorer</h3><p id="record-scope" class="muted">Select an Assistant and your relationship.</p><div id="record-overview"></div>
    <div class="form-grid"><label>View<select id="record-filter"><option value="all">All Records</option>${['declaration','episode','semantic','convention','hypothesis','procedure','thread','commitment'].map(value=>`<option>${value}</option>`).join('')}</select></label><button id="records-refresh" type="button">Refresh Records</button><button id="records-export" type="button" class="secondary">Export My Relationship</button></div>
    <details open><summary>Declare Context</summary><div class="form-grid"><label>Category<select id="record-category">${['declaration','episode','semantic','convention','hypothesis','procedure','thread','commitment'].map(value=>`<option>${value}</option>`).join('')}</select></label><label>Use After Review<select id="record-lane"><option value="relevant">When Relevant</option><option value="baseline">Always Include Convention</option><option value="correction">Direct Correction</option></select></label><label>Original Event Date (Optional)<input id="record-event" type="datetime-local"></label><label>Sensitivity<select id="record-sensitivity"><option value="personal">Personal</option><option value="sensitive">Sensitive</option></select></label></div><label>Declaration<textarea id="record-content" rows="3" maxlength="4000"></textarea></label><p class="muted">Authored context starts pending. An episode entered here is an attributed account, not a verified shared event. Review before ordinary use.</p><button id="record-declare" type="button">Save Pending Declaration</button></details>
    <div id="record-list" class="revisions"></div><div id="record-operation-panel" hidden><h4 id="record-operation-title"></h4><label>Replacement / Annotation<textarea id="record-operation-text" rows="3" maxlength="4000"></textarea></label><label id="record-other-label">Other Compatible Record<select id="record-other"></select></label><p id="record-operation-help" class="muted"></p><div class="actions"><button id="record-operation-apply" type="button">Apply Reviewed Operation</button><button id="record-operation-cancel" type="button" class="quiet">Cancel</button></div></div>`;
  const get = id => section.querySelector(`#${id}`); let relationship = null, selectedOperation = null, epoch = 0;
  const base = () => { const value = context(); if (!value?.relationship) throw new Error('Select an owned relationship first.'); return `/api/admin/v1/assistants/${value.assistantId}/relationships/${value.relationship.relationshipId}`; };
  const guard = fn => async () => { try { await fn(); } catch(error) { show(error.message, true); } };
  const download = (value, name) => { const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000); };
  const render = body => {
    relationship = body.relationship; const overview=body.overview; get('record-scope').textContent=`Assistant → Relationships → ${relationship.userId} · Revision ${relationship.revision}. Only this authenticated subject's relationship is shown.`;
    get('record-overview').innerHTML=`<div class="form-grid"><p><strong>${overview.activeRecords}</strong> Approved Records</p><p><strong>${overview.pendingReview}</strong> Need Review</p><p><strong>${overview.retainedConflicts}</strong> Retained Conflicts</p><p><strong>${overview.sourceFamilies}</strong> Attributed Source Families</p></div><p>${esc(overview.coverage)}</p><p class="muted">${esc(overview.verifiedEventsLimitation)} Latest Record: ${esc(overview.latestRecordAt||'Unknown')}. High Uncertainty: ${overview.highUncertainty}. Source labels do not prove independence. Active settings and adaptations remain separate below.</p>`;
    const filtered=relationship.candidates.filter(record=>get('record-filter').value==='all'||(record.category||'declaration')===get('record-filter').value);
    get('record-list').innerHTML=filtered.map(record=>`<article class="revision record-card" data-record="${esc(record.candidateId)}"><div><strong>${esc(record.content||'Forgotten Record')}</strong><p>${esc(record.category||'declaration')} · ${esc(record.status)} · Revision ${record.revision}</p><p>${esc(record.evidenceBasis||'attributed declaration')} · Asserted By ${esc(record.assertedBy||relationship.userId)} · ${esc(record.uncertainty)} Uncertainty</p><p>Use: ${record.suppressed||record.audience==='ownerOnly'||record.approvedUse?.personalization===false?'Withheld':record.status==='approved'?'Eligible in Authorized Session':'Inactive'} · Training Excluded · ${record.salience==='operatorPinned'?'Operator-Pinned Salience (Not Truth)':'Normal Salience'}</p><details><summary>Evidence, Permissions and History</summary><p>Subject ${esc(relationship.userId)} · Source ${esc(record.source)} · Families ${esc((record.sourceFamilies||[record.sourceFamily]).join(', '))}</p><p>Event ${esc(record.eventAt||record.builder?.observedAt||'Unknown')} · Created ${esc(record.createdAt||'Unknown')} · ${esc(record.sensitivity||'personal')}</p><p>Derived From ${esc((record.derivedFrom||[]).join(', ')||'None')} · Conflicts ${esc((record.conflicts||[]).map(item=>`${item.recordId}: ${item.status}`).join(', ')||'None')}</p><p>Audience ${esc(record.audience||'authenticatedSession')} · Mention ${record.approvedUse?.mention===false?'Restricted; Withheld Before Inference':'Only in Permitted Context'} · No Cross-Assistant Sharing</p>${(record.annotations||[]).map(item=>`<p>${esc(item.text)} — ${esc(item.actor)}</p>`).join('')}<ol>${(record.history||[]).map(item=>`<li>${esc(item.operation)} · Revision ${item.revision} · ${esc(item.actor)} · ${esc(item.at)}</li>`).join('')||'<li>No later lifecycle operations</li>'}</ol></details><div class="actions">${record.status==='pending'?'<button data-review="approved">Approve</button><button data-review="rejected" class="quiet">Reject</button>':''}${!['forgotten'].includes(record.status)?(record.status==='superseded'?['forget']:['correct','annotate','split','merge','supersede','conflict','pin','suppress','restrict-mention','narrow-audience','exclude-training','forget',...(record.category==='hypothesis'||record.evidenceBasis==='modelInference'?['reject-inference']:[])]).map(op=>`<button type="button" class="quiet" data-operation="${op}">${esc(op.replaceAll('-',' '))}</button>`).join(''):''}</div></div></article>`).join('')||'<p class="muted">No records in this view. Conversation remains usable when bootstrap is skipped.</p>';
  };
  const refresh = async () => { const ticket=epoch, path=base(); const body=await api(path+'/records');if(ticket===epoch&&path===base())render(body); };
  get('records-refresh').onclick=guard(refresh);get('record-filter').onchange=guard(refresh);get('records-export').onclick=guard(async()=>download(await api(base()+'/export'),'relationship-context.json'));
  get('record-declare').onclick=guard(async()=>{ const scope=context();await api(base()+'/candidates',{method:'POST',body:JSON.stringify({content:get('record-content').value,category:get('record-category').value,contextUse:get('record-lane').value,eventAt:get('record-event').value?new Date(get('record-event').value).toISOString():null,sensitivity:get('record-sensitivity').value,source:'authenticated-declaration',sourceFamily:`user:${scope.relationship.userId}`,uncertainty:'high',expectedRevision:scope.relationship.revision,idempotencyKey:crypto.randomUUID()})});get('record-content').value='';await refreshRelationship();await refresh();show('Declaration saved for explicit review.'); });
  get('record-list').onclick=async event=>{const button=event.target.closest('button');const card=button?.closest('[data-record]');if(!card)return;const record=relationship?.candidates.find(item=>item.candidateId===card.dataset.record);if(!record)return;
    try { if(button.dataset.review){await api(base()+`/candidates/${record.candidateId}/decision`,{method:'POST',body:JSON.stringify({decision:button.dataset.review,expectedRevision:relationship.revision,idempotencyKey:crypto.randomUUID()})});await refreshRelationship();await refresh();return;}
      if(button.dataset.operation){selectedOperation={record,operation:button.dataset.operation};get('record-operation-panel').hidden=false;get('record-operation-title').textContent=`Review ${selectedOperation.operation} — Revision ${record.revision}`;get('record-operation-text').value=['correct','supersede'].includes(selectedOperation.operation)?record.content:'';get('record-other').innerHTML=relationship.candidates.filter(item=>item.candidateId!==record.candidateId&&['approved','pending'].includes(item.status)).map(item=>`<option value="${esc(item.candidateId)}">${esc(item.content.slice(0,100))} (r${item.revision})</option>`).join('');get('record-other-label').hidden=!['merge','conflict'].includes(selectedOperation.operation);get('record-operation-help').textContent=selectedOperation.operation==='split'?'Enter two to four parts, one per line. Original evidence family and use restrictions remain attached.':selectedOperation.operation==='conflict'?'Enter “retain” to preserve both as unresolved and withhold them, or “resolve” to keep this record and reject the selected alternative.':selectedOperation.operation==='forget'?'Remove this record and its derived payloads, cancel affected jobs and fence stale imports/restore. External exports and backups require their own deletion.':'Review this explicit revision before applying. Restrictions withhold context before inference; pinning changes operator salience only.';get('record-operation-panel').scrollIntoView({block:'nearest'});}
    }catch(error){show(error.message,true);}
  };
  get('record-operation-cancel').onclick=()=>{selectedOperation=null;get('record-operation-panel').hidden=true;};
  get('record-operation-apply').onclick=guard(async()=>{if(!selectedOperation)return;const {record,operation}=selectedOperation,other=relationship.candidates.find(item=>item.candidateId===get('record-other').value);await api(base()+`/records/${record.candidateId}/operations`,{method:'POST',body:JSON.stringify({operation,expectedRevision:relationship.revision,expectedRecordRevision:record.revision,idempotencyKey:crypto.randomUUID(),content:get('record-operation-text').value,text:get('record-operation-text').value,contents:get('record-operation-text').value.split('\n'),otherRecordId:other?.candidateId,otherRecordRevision:other?.revision,disposition:get('record-operation-text').value.trim(),pinned:true})});selectedOperation=null;get('record-operation-panel').hidden=true;await refreshRelationship();await refresh();show('Reviewed record operation applied.');});
  const clear=()=>{epoch++;relationship=null;selectedOperation=null;get('record-list').replaceChildren();get('record-overview').replaceChildren();get('record-operation-panel').hidden=true;get('record-scope').textContent='Select an Assistant and your relationship.';};
  window.addEventListener('lifestream-assistant',clear);window.addEventListener('lifestream-auth',clear);window.addEventListener('lifestream-relationship',()=>{clear();if(context()?.relationship)void guard(refresh)();});
  return { refresh };
}
