import {previewPlayback} from './preview-playback.js';
import {installAcknowledgmentAdministration} from './acknowledgments.js';
export function installSavedVoices({anchor,api,context,onActivated}) {
 anchor.innerHTML=`<h2>Saved voice</h2><p>Create candidates and compare the same spoken text before activating one. Conversation preview overrides are temporary and are never saved here automatically.</p><p data-voice-active role="status">Select an Assistant.</p><div class="actions"><button type="button" class="secondary" data-voice-refresh>Refresh saved voices</button><button type="button" class="secondary" data-voice-stop disabled>Stop voice preview</button></div><form data-voice-form><div class="form-grid"><label>Candidate label<input name="label" maxlength="80" required></label><label>Language<select name="language"><option value="en">English</option></select></label><label>Voice description<input name="description" maxlength="300" disabled></label><label>Seed<input name="seed" type="number" min="0" max="2147483647" step="1" value="0" disabled></label><label>Delivery<select name="deliveryMode"></select></label><label>Pace<input name="pace" type="number" min="0" max="1" step="0.01" value="0.5" required></label><label>Energy<input name="energy" type="number" min="0" max="1" step="0.01" value="0.4" required></label></div><details><summary>Optional reference conditioning</summary><p data-voice-reference-status>Checking the selected provider. This conditions inference; it is not training.</p><label>Reference audio · 2–20 seconds<input name="reference" type="file" accept="audio/wav,audio/x-wav" disabled></label><label>Reference transcript<textarea name="transcript" maxlength="1000" disabled></textarea></label><label class="checkbox"><input type="checkbox" name="consent" disabled>I have permission to use and retain this reference for this Assistant.</label></details><button type="submit" data-voice-save disabled>Save voice candidate</button></form><label>Shared comparison text<textarea data-voice-text maxlength="300" rows="2">Hello. I am ready to help you think this through.</textarea></label><p data-voice-status role="status">No preview is playing.</p><div data-voice-list></div>`;
 const form=anchor.querySelector('form'),el=name=>form.elements.namedItem(name),status=anchor.querySelector('[data-voice-status]'),list=anchor.querySelector('[data-voice-list]'),stopButton=anchor.querySelector('[data-voice-stop]');
 let snapshot,epoch=0,previewRequest,controller,source,audio,playback,settlement=Promise.resolve(),previewing=null;const reviewed=new Map();
 const say=value=>{status.textContent=value;};
 const scope=()=>{const s=context();if(!s?.assistantId||!window.lifestreamAuth.session)throw Error('Select an Assistant and sign in first.');return s.assistantId;};
 const stop=()=>{previewRequest=null;controller?.abort();controller=null;if(source){source.onended=null;source.stop();source.disconnect();source=null;}previewing=null;stopButton.disabled=true;if(playback){settlement=playback.finish('stopped');playback=null;}return settlement;};
 const audioContext=async()=>{audio??=new AudioContext({sampleRate:16000});if(audio.state==='suspended')await audio.resume();return audio;};
 const render=()=>{
  list.replaceChildren();if(!snapshot)return;anchor.querySelector('[data-voice-active]').textContent=`${snapshot.activeVoiceRef?'Saved voice '+(snapshot.voices.find(v=>v.voiceRef===snapshot.activeVoiceRef)?.label??'unavailable'):'Configured default voice'} · Assistant profile revision ${snapshot.activeProfileRevision??'not active'}.`;
  for(const voice of snapshot.voices){const row=document.createElement('section');row.className='revision saved-voice-candidate';row.dataset.voiceRef=voice.voiceRef;const body=document.createElement('div'),title=document.createElement('h3'),detail=document.createElement('p');title.textContent=voice.label;detail.textContent=`Revision ${voice.revision} · ${voice.language} · ${voice.settings.deliveryMode} · pace ${voice.settings.pace} · energy ${voice.settings.energy}${voice.settings.reference?' · retained reference':''}${voice.compatible?'':' · incompatible provider configuration'}`;body.append(title,detail);const actions=document.createElement('div');actions.className='actions';const preview=document.createElement('button');preview.type='button';preview.textContent='Preview '+voice.label;preview.disabled=!voice.compatible;preview.onclick=run(()=>play(voice));const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.disabled=!reviewed.has(voice.voiceRef);label.append(check,document.createTextNode(' I reviewed this voice'));const activate=document.createElement('button');activate.type='button';activate.className='secondary';activate.textContent='Activate '+voice.label;activate.disabled=true;check.onchange=()=>{activate.disabled=!check.checked||!reviewed.has(voice.voiceRef);};activate.onclick=run(async()=>{const assistantId=scope(),ticket=epoch;stop();const receipt=reviewed.get(voice.voiceRef);if(!receipt||!check.checked)throw Error('Preview and review this candidate first.');await api(`/api/admin/v1/assistants/${assistantId}/voices/activate`,{method:'POST',body:JSON.stringify({voiceRef:voice.voiceRef,previewId:receipt,reviewed:true,expectedActiveRevision:snapshot.activeProfileRevision})});if(ticket!==epoch)return;reviewed.clear();await onActivated();await refresh();say('Reviewed voice activated. Reconnect speech to use this revision.');});const remove=document.createElement('button');remove.type='button';remove.className='quiet';remove.textContent='Remove '+voice.label;remove.disabled=snapshot.activeVoiceRef===voice.voiceRef;remove.onclick=run(async()=>{const assistantId=scope(),ticket=epoch;stop();await api(`/api/admin/v1/assistants/${assistantId}/voices/remove`,{method:'POST',body:JSON.stringify({voiceRef:voice.voiceRef,expectedRevision:voice.revision})});if(ticket!==epoch)return;reviewed.delete(voice.voiceRef);await refresh();say('Candidate and reference removed from this database. Older backups may still contain them.');});actions.append(preview,label,activate,remove);row.append(body,actions);list.append(row);}
 };
 const refresh=async()=>{const assistantId=scope(),ticket=epoch,value=await api(`/api/admin/v1/assistants/${assistantId}/voices`);if(ticket!==epoch)return;snapshot=value;el('deliveryMode').replaceChildren(...value.deliveryModes.map(name=>new Option(name,name)));el('description').disabled=el('seed').disabled=!value.controls.description;for(const name of ['reference','transcript','consent'])el(name).disabled=!value.controls.reference;anchor.querySelector('[data-voice-reference-status]').textContent=value.controls.reference?'The selected provider supports reference conditioning. A saved reference stays in private runtime storage. This is not training.':'Reference conditioning is unavailable on the selected provider. Description and delivery support are shown independently.';anchor.querySelector('[data-voice-save]').disabled=false;render();};
 const play=async voice=>{
  window.dispatchEvent(new CustomEvent('lifestream-preview-start',{detail:'saved-voice'}));
  const assistantId=scope(),ticket=epoch,text=anchor.querySelector('[data-voice-text]').value.trim();if(!text||text.length>300)throw Error('Enter a short shared comparison text.');const stopped=stop(),attempt=previewRequest=Symbol();await stopped;if(ticket!==epoch||previewRequest!==attempt)return;const task=controller=new AbortController();previewing=voice.voiceRef;stopButton.disabled=false;reviewed.delete(voice.voiceRef);render();const ctx=await audioContext();say('Preparing '+voice.label+'…');
  try{
   const headers={'content-type':'application/json','x-lifestream-csrf':window.lifestreamAuth.session.csrfToken};const response=await fetch('/api/runtime/v1/tts',{method:'POST',headers,credentials:'same-origin',body:JSON.stringify({assistantId,voiceRef:voice.voiceRef,text}),signal:task.signal});if(!response.ok){const error=await response.json();throw Error(error.message??'Voice preview failed.');}
   const custody=playback=previewPlayback(response,headers,()=>{if(controller===task){stop();say('Preview expired.');}});if(task.signal.aborted||ticket!==epoch||controller!==task){await custody.finish('stopped');return;}
   const reader=response.body.getReader(),decoder=new TextDecoder(),frames=[];let pending='',terminal,samples=0;
   const consume=line=>{const event=JSON.parse(line);if(event.kind==='data'){const f=event.frame;if(f.sampleOffset!==samples||f.sequence!==frames.length||f.format.encoding!=='pcm_s16le'||f.format.sampleRateHz!==48000||f.format.channels!==1)throw Error('Preview audio accounting is invalid.');const bytes=Uint8Array.from(atob(f.dataBase64),c=>c.charCodeAt(0));if(bytes.byteLength!==f.sampleCount*2||samples+f.sampleCount>48000*60)throw Error('Preview audio is invalid or too long.');custody.received(f.sampleCount);samples+=f.sampleCount;frames.push(bytes);}else if(event.kind==='terminal'){if(terminal)throw Error('Duplicate preview completion.');terminal=event;}};
   while(true){const {value,done}=await reader.read();if(done)break;pending+=decoder.decode(value,{stream:true});if(pending.length>2_000_000)throw Error('Preview transport exceeded its bound.');let split;while((split=pending.indexOf('\n'))>=0){const line=pending.slice(0,split);pending=pending.slice(split+1);if(line)consume(line);}}pending+=decoder.decode();if(pending.trim())consume(pending);
   if(task.signal.aborted||ticket!==epoch||controller!==task)return;if(terminal?.outcome!=='succeeded'||terminal.outputSamples!==samples||terminal.frameCount!==frames.length||!terminal.voicePreview?.previewId||terminal.voicePreview.voiceRef!==voice.voiceRef||!samples)throw Error('Preview did not complete successfully.');
   const buffer=ctx.createBuffer(1,samples,48000),values=buffer.getChannelData(0);let offset=0;for(const bytes of frames){const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);for(let i=0;i<bytes.length;i+=2)values[offset++]=view.getInt16(i,true)/32768;}
   const node=source=ctx.createBufferSource();node.buffer=buffer;node.connect(ctx.destination);node.onended=async()=>{if(ticket!==epoch||controller!==task||source!==node)return;node.disconnect();source=null;playback=null;settlement=custody.finish('completed');const confirmed=await settlement;if(ticket!==epoch||controller!==task)return;if(!confirmed){stop();say('Playback ended; confirmation was unavailable. Retry after ownership expires.');return;}controller=null;previewing=null;reviewed.set(voice.voiceRef,terminal.voicePreview.previewId);stopButton.disabled=true;render();say('Preview finished: '+voice.label+'. Compare another candidate or confirm your review.');};node.start();say('Playing '+voice.label+'…');
  }catch(error){if(controller===task){stop();if(!task.signal.aborted)say(error.message);else say('Voice preview stopped.');}throw error;}
 };
 const run=fn=>()=>void fn().catch(error=>{if(error.name!=='AbortError')say(error.message);});
 form.onsubmit=event=>{event.preventDefault();run(async()=>{const assistantId=scope(),ticket=epoch;stop();let reference=null;const file=el('reference').files[0];if(file){if(!el('consent').checked)throw Error('Confirm permission to retain the reference first.');if(file.size>5_000_000)throw Error('Reference file is too large.');const ctx=await audioContext(),decoded=await ctx.decodeAudioData(await file.arrayBuffer());if(decoded.duration<2||decoded.duration>20)throw Error('Reference must be 2–20 seconds.');const renderer=new OfflineAudioContext(1,Math.round(decoded.duration*16000),16000),node=renderer.createBufferSource();node.buffer=decoded;node.connect(renderer.destination);node.start();const samples=(await renderer.startRendering()).getChannelData(0),bytes=new Uint8Array(samples.length*2),view=new DataView(bytes.buffer);for(let i=0;i<samples.length;i++)view.setInt16(i*2,Math.round(Math.max(-1,Math.min(1,samples[i]))*32767),true);let binary='';for(let i=0;i<bytes.length;i+=4096)binary+=String.fromCharCode(...bytes.subarray(i,i+4096));reference={sampleRateHz:16000,dataBase64:btoa(binary),transcript:el('transcript').value,consent:true};}
   if(ticket!==epoch)return;await api(`/api/admin/v1/assistants/${assistantId}/voices`,{method:'POST',body:JSON.stringify({label:el('label').value,language:el('language').value,settings:{description:el('description').disabled?'':el('description').value,seed:el('seed').disabled?0:Number(el('seed').value),deliveryMode:el('deliveryMode').value,pace:Number(el('pace').value),energy:Number(el('energy').value),reference}})});if(ticket!==epoch)return;el('reference').value='';el('transcript').value='';el('consent').checked=false;await refresh();say('Candidate saved. Preview and compare before activation.');})();};
 stopButton.onclick=()=>{stop();say('Voice preview stopped.');};anchor.querySelector('[data-voice-refresh]').onclick=run(refresh);
 const clear=()=>{epoch++;stop();snapshot=null;reviewed.clear();form.reset();list.replaceChildren();anchor.querySelector('[data-voice-save]').disabled=true;anchor.querySelector('[data-voice-active]').textContent='Select an Assistant and refresh.';say('No preview is playing.');};
 for(const event of ['lifestream-auth','lifestream-assistant'])window.addEventListener(event,()=>{clear();if(window.lifestreamAuth.session)void refresh().catch(()=>{});});
 window.addEventListener('lifestream-audience',event=>{clear();if(event.detail?.privateAllowed)void refresh().catch(()=>{});});window.addEventListener('hashchange',()=>{if(location.hash!=='#voice'){stop();say('Voice preview stopped.');}});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});window.addEventListener('pagehide',()=>{clear();void audio?.close();});
 installAcknowledgmentAdministration({anchor,api,context});
 window.addEventListener('lifestream-preview-start',event=>{if(event.detail!=='saved-voice')stop();});
 return {refresh:run(refresh),get playing(){return previewing!==null;}};
}
