(() => {
  const $ = id => document.getElementById(id), status = text => { $('security-status').textContent = text; }, auth = window.lifestreamAuth;
  const request = async (path, body) => { await auth.ready; return auth.request(path, body, body !== undefined); };
  const base = () => `/api/authority/v1/assistants/${encodeURIComponent($('security-assistant').value)}`;
  const run = operation => async () => { try { await operation(); } catch (error) { status(error.message); } };
  const button = (parent, label, callback) => { const element = document.createElement('button'); element.textContent = label; element.type = 'button'; element.onclick = run(callback); parent.append(element); };
  $('security-provision').onclick = run(async () => { const result = await request('/api/auth/v1/accounts', { username: $('security-username').value, password: $('security-password').value }); $('security-password').value = ''; $('security-principal').value = result.principalId; status('Account created with no Assistant permissions.'); });
  $('security-accounts').onclick = run(async () => { $('security-account-list').textContent = JSON.stringify((await request('/api/auth/v1/accounts')).accounts, null, 2); });
  for (const [id, administer] of [['security-grant-scope', true], ['security-revoke-scope', false]]) $(id).onclick = run(async () => { await request('/api/auth/v1/permissions', { principalId: $('security-principal').value, assistantId: $('security-assistant').value, administer }); status('Assistant administration scope updated. Relationship read access remains subject-owned.'); });
  const refresh = async () => { const grants = (await request(`${base()}/grants`)).grants; $('security-grants').replaceChildren(); for (const grant of grants) { const row = document.createElement('div'); const text = document.createElement('p'); text.textContent = `${grant.status} · revision ${grant.revision} · ${grant.scope.join(', ')} · ${grant.terms.durationMode} · expires ${grant.terms.expiresAt}`; row.append(text); for (const decision of grant.status === 'pending' ? ['active', 'denied'] : grant.status === 'active' ? ['revoked'] : []) button(row, decision === 'active' ? 'Approve grant' : decision === 'denied' ? 'Deny grant' : 'Revoke grant', async () => { await request(`${base()}/grants/${grant.id}/decision`, { expectedRevision: grant.revision, decision }); await refresh(); }); $('security-grants').append(row); } $('security-tools').textContent = JSON.stringify(await request(`${base()}/tools`), null, 2); $('security-audit').textContent = JSON.stringify(await request(`${base()}/audit`), null, 2); };
  $('security-request').onclick = run(async () => { await request(`${base()}/grants`, { scope: $('security-capabilities').value.split(',').map(value => value.trim()).filter(Boolean), durationSeconds: Number($('security-duration').value), durationMode: $('security-duration-mode').value }); await refresh(); }); $('security-refresh').onclick = run(refresh);
  let editingSkill = null;
  const refreshSkills = async () => { const result = await request(`${base()}/skills`); $('security-skills').replaceChildren(); for (const skill of result.skills) { const row = document.createElement('div'), label = document.createElement('p'); label.textContent = `${skill.name} · revision ${skill.revision} · ${skill.status}`; row.append(label); button(row, 'Edit as new draft', async () => { editingSkill = { id: skill.skillId, revision: skill.revision }; $('security-skill').value = JSON.stringify({ ...skill, status: 'draft', activationRef: null }, null, 2); status('Editing an inert draft. The active Skill remains unchanged until activation.'); }); if (skill.status === 'draft') button(row, 'Activate reviewed Skill', async () => { await request(`${base()}/skills/${skill.skillId}/activate`, { expectedRevision: skill.revision }); await refreshSkills(); }); button(row, 'Show revision history', async () => { const history = document.createElement('pre'); history.textContent = JSON.stringify(await request(`${base()}/skills/${skill.skillId}/history`), null, 2); row.append(history); }); $('security-skills').append(row); } };
  $('security-save-skill').onclick = run(async () => { const draft = JSON.parse($('security-skill').value); await request(editingSkill ? `${base()}/skills/${editingSkill.id}/revisions` : `${base()}/skills`, { skill: draft, ...(editingSkill ? { expectedRevision: editingSkill.revision } : {}) }); editingSkill = null; await refreshSkills(); status('Inert Skill draft saved; activation and tool authority are separate.'); }); $('security-refresh-skills').onclick = run(refreshSkills);
  let review = null; $('security-review-proposal').onclick = run(async () => { const id = $('security-proposal-id').value; const result = await request(`/api/auth/v1/proposals/${encodeURIComponent(id)}`); review = { id, digest: result.digest }; $('security-proposal').textContent = JSON.stringify(result.operation, null, 2); $('security-approve-proposal').disabled = result.status !== 'proposed'; });
  $('security-approve-proposal').onclick = run(async () => { if (!review) return; const selected = review; review = null; $('security-approve-proposal').disabled = true; await request(`/api/auth/v1/proposals/${encodeURIComponent(selected.id)}/approve`, { reviewedDigest: selected.digest, humanConfirmed: true }); status('The reviewed operation was submitted once through its normal validation and scope checks.'); });
  window.addEventListener('lifestream-auth', () => { review = null; $('security-approve-proposal').disabled = true; $('security-proposal').textContent = '';for(const id of ['security-account-list','security-grants','security-tools','security-audit','security-skills'])$(id).replaceChildren(); });
})();
