// Review and move an idle logical conversation. Each endpoint retains its own
// sign-in, audience decision, capture consent, appearance and authority boundary.
export function installSessionHandoff({anchor,api,context}) {
 anchor.id='session-handoff-panel';anchor.className='card';
 anchor.innerHTML='<h2>Continue on another endpoint</h2><p>Use a separate browser profile or the native app, signed in to the same account. On that destination, select the same Assistant and relationship, apply private Session Disclosure, choose Only me, and mark its fresh, unused sign-in ready. Stop speech and close microphones on both endpoints first.</p><p>Only the selected conversation’s bounded dialogue moves. Its original expiry stays in place; restarting the server clears it. The source conversation ends. Appearance, capture consent and tool grants stay separate.</p><div class="actions"><button type="button" data-handoff-refresh>Refresh endpoints &amp; receipts</button><button type="button" class="secondary" data-handoff-ready disabled>Ready to receive here</button><button type="button" class="quiet" data-handoff-cancel disabled>Cancel receiving</button></div><p class="muted" data-handoff-identity></p><p role="status" data-handoff-status></p><label for="handoff-destination">Ready destination<select id="handoff-destination"><option value="">Refresh to find a destination</option></select></label><div class="actions"><button type="button" data-handoff-prepare disabled>Review move</button><button type="button" data-handoff-commit disabled>Move conversation &amp; end source</button><button type="button" class="quiet" data-handoff-discard disabled>Discard review</button></div><p role="status" data-handoff-review></p><details><summary>Recent handoff receipts</summary><pre class="context-inspector" data-handoff-receipts></pre></details>';
 const $=s=>anchor.querySelector(s),select=$('#handoff-destination');let epoch=0,review=null,snapshot=null,busy=false,ownEvent=false;const received=new Set();
 const permitted=()=>window.lifestreamAuth?.mode==='local-password'&&!!window.lifestreamAuth.session&&document.documentElement.dataset.audienceProtected!=='true'&&!document.hidden;
 const scope=()=>{const c=context();return c?.assistantId?{assistantId:c.assistantId,...(c.relationship?.relationshipId?{relationshipId:c.relationship.relationshipId}:{})}:null;};
 const identity=()=>JSON.stringify([window.lifestreamAuth?.session?.sessionId,scope()]);
 const valid=(ticket,key)=>ticket===epoch&&key===identity()&&permitted();
 const controls=()=>{$('[data-handoff-refresh]').disabled=busy;$('[data-handoff-ready]').disabled=busy||!snapshot?.canReceive||!!snapshot?.ready;$('[data-handoff-cancel]').disabled=busy||!snapshot?.ready;select.disabled=busy||!!snapshot?.ended;$('[data-handoff-prepare]').disabled=busy||!select.value||!!snapshot?.ended;$('[data-handoff-commit]').disabled=busy||!review;$('[data-handoff-discard]').disabled=busy||!review;};
 const discard=()=>{review=null;$('[data-handoff-review]').textContent='';controls();};
 const clear=()=>{snapshot=null;busy=false;select.replaceChildren(new Option('Refresh to find a destination',''));discard();$('[data-handoff-status]').textContent='';$('[data-handoff-identity]').textContent='';$('[data-handoff-receipts]').textContent='';};
 const changed=()=>{if(ownEvent)return;epoch++;clear();anchor.hidden=!permitted();if(!anchor.hidden&&location.hash==='#session')void load();};
 const announce=()=>{ownEvent=true;try{window.dispatchEvent(new CustomEvent('lifestream-session-context'));}finally{ownEvent=false;}};
 const load=async()=>{const ticket=++epoch,key=identity();clear();anchor.hidden=!permitted();if(anchor.hidden)return;const s=scope();if(!s){$('[data-handoff-status]').textContent='Select an active Assistant first.';return;}busy=true;controls();try{const value=await api('/api/runtime/v1/handoff?'+new URLSearchParams(s));if(!valid(ticket,key))return;snapshot=value;$('[data-handoff-identity]').textContent=`This endpoint ${value.endpointId?.slice(0,8)??'ended'} · this sign-in ${value.sessionId.slice(0,8)}`;select.replaceChildren(new Option(value.destinations.length?'Choose a ready destination':'No ready destination',''));for(const d of value.destinations)select.add(new Option(`Endpoint ${d.endpointId.slice(0,8)} · session ${d.sessionId.slice(0,8)} · until ${new Date(d.expiresAt).toLocaleTimeString()}`,d.readinessId));$('[data-handoff-status]').textContent=value.ended?'This conversation has moved. Receipts remain available; sign in again to start a different conversation here.':value.ready?`Ready to receive until ${new Date(value.ready.expiresAt).toLocaleTimeString()}. Review and commit from the source endpoint.`:value.canReceive?'This unused sign-in can receive a conversation. Mark it ready only if this is the destination.':'This sign-in can send its conversation. Receiving requires a fresh unused sign-in.';$('[data-handoff-receipts]').textContent=value.records.length?JSON.stringify(value.records,null,2):'No handoff receipts for this Assistant.';const arrival=value.records.find(r=>r.status==='succeeded'&&r.result.destinationSession.sessionId===value.sessionId);if(arrival){if(!received.has(arrival.result.handoffId)){received.add(arrival.result.handoffId);announce();}$('[data-handoff-status]').textContent='Conversation received. Open Conversation and continue with this Assistant. Capture and playback still require your local choices.';}}catch(error){if(valid(ticket,key))$('[data-handoff-status]').textContent=error.message;}finally{if(valid(ticket,key)){busy=false;controls();}}};
 const mutate=async(operation,extra={})=>{const s=scope();if(!permitted()||!s||busy)return;const ticket=++epoch,key=identity();discard();busy=true;controls();try{const value=await api('/api/runtime/v1/handoff',{method:'POST',body:JSON.stringify({...s,operation,...extra})});if(!valid(ticket,key))return;if(operation==='prepare'){review=value;$('[data-handoff-review]').textContent=`Review: ${value.dialogueEntries} dialogue entries (${value.dialogueBytes} bytes) will move to session ${value.destinationSessionId.slice(0,8)}. This source ends. No grants or capture consent transfer. Review expires ${new Date(value.expiresAt).toLocaleTimeString()}. ${value.retention}`;}else await load();}catch(error){if(valid(ticket,key))$('[data-handoff-status]').textContent=error.message;}finally{if(valid(ticket,key)){busy=false;controls();}}};
 $('[data-handoff-refresh]').onclick=()=>void load();$('[data-handoff-ready]').onclick=()=>void mutate('ready');$('[data-handoff-cancel]').onclick=()=>void mutate('cancel');$('[data-handoff-prepare]').onclick=()=>void mutate('prepare',{destinationReadinessId:select.value});$('[data-handoff-discard]').onclick=discard;select.onchange=()=>{epoch++;discard();};
 $('[data-handoff-commit]').onclick=async()=>{if(!permitted()||busy||!review)return;const value=review,ticket=++epoch,key=identity();discard();busy=true;controls();try{await api(`/api/runtime/v1/sessions/${value.request.payload.sessionId}/handoff`,{method:'POST',body:JSON.stringify(value.request)});if(!valid(ticket,key))return;announce();window.lifestreamUI?.notify('Conversation moved. Refresh the destination, then continue there.');await load();}catch(error){if(valid(ticket,key)){$('[data-handoff-status]').textContent='Move could not be confirmed. Refresh endpoints & receipts before trying again. '+error.message;}}finally{if(valid(ticket,key)){busy=false;controls();}}};
 for(const name of ['lifestream-auth','lifestream-assistant','lifestream-relationship','lifestream-audience','lifestream-session-context','hashchange'])window.addEventListener(name,changed);
 document.addEventListener('visibilitychange',changed);window.addEventListener('pagehide',()=>{epoch++;clear();anchor.hidden=true;});void window.lifestreamAuth.ready.then(changed);
}
