export function installUserProfile({ anchor, api: transport, context, show }) {
 const api=async(...args)=>{const ticket=epoch;const result=await transport(...args);if(ticket!==epoch)throw new Error('Administration scope changed; refresh the current selection.');return result;};
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const section=document.createElement('section');section.className='memory-tools';section.id='user-profile';anchor.before(section);
 section.innerHTML=`<h3>People &amp; Context — My User Profile</h3><p>Keep your declarations independent of an Assistant. Share an explicit subset with each selected Assistant. Private relationship history, conversations, adaptations and grants stay separate.</p><p id="person-identity" class="muted">Sign in to review your profile.</p><div class="actions"><button id="person-refresh" type="button">Refresh My Profile</button><button id="person-export" type="button" class="secondary">Export My Profile</button></div><div class="form-grid"><label>Declaration Key<input id="person-key" maxlength="100" placeholder="communication.explanation"></label><label>Value<input id="person-value" maxlength="2000"></label><label>Sensitivity<select id="person-sensitivity"><option value="personal">Personal</option><option value="ordinary">Ordinary</option><option value="sensitive">Sensitive</option></select></label><button id="person-add" type="button">Add to Draft</button></div><div id="person-declarations" class="revisions"></div><fieldset><legend>Reviewed Assistant Subsets</legend><p>Choose exactly which draft keys this selected Assistant may use for conversation, personalization and mention in your authenticated session. Training and onward sharing are not granted.</p><label>Keys for Selected Assistant<select id="person-keys" multiple size="4"></select></label><button id="person-scope" type="button" class="secondary">Set Selected Assistant Subset</button><div id="person-subsets"></div></fieldset><div class="actions"><button id="person-preview" type="button">Save and Preview Draft</button><button id="person-activate" type="button" disabled>Activate Reviewed Profile</button><button id="person-revoke" type="button" class="quiet" disabled>Revoke Active Profile</button></div><div id="person-preview-result" role="status"></div><label>Retained Revision<select id="person-history"></select></label><button id="person-rollback" type="button" class="secondary">Prepare Rollback Draft</button>`;
 const get=id=>section.querySelector('#'+id),path='/api/admin/v1/people/me';let declarations=[],scopes=[],profiles=[],active=null,draft=null,epoch=0;
 const guard=fn=>async()=>{try{await fn();}catch(error){show(error.message,true);}};
 const renderDraft=()=>{get('person-declarations').innerHTML=declarations.map((item,index)=>`<div class="revision"><span><strong>${esc(item.key)}</strong>: ${esc(item.value)} · ${esc(item.sensitivity)}</span><button type="button" class="quiet" data-remove="${index}">Remove from Draft</button></div>`).join('')||'<p class="muted">No declarations in this draft.</p>';get('person-keys').innerHTML=declarations.map(item=>`<option value="${esc(item.key)}">${esc(item.key)}</option>`).join('');get('person-subsets').innerHTML=scopes.map(scope=>`<p>${esc(scope.assistantId)}: ${esc(scope.allowedKeys.join(', '))||'No Keys'}</p>`).join('');get('person-activate').disabled=!draft;};
 const refresh=async()=>{const ticket=epoch,body=await api(path);if(ticket!==epoch)return;profiles=body.profiles;active=profiles.find(item=>item.status==='active')||null;draft=null;declarations=structuredClone(active?.declarations||[]);scopes=structuredClone(active?.assistantScopes||[]);get('person-identity').textContent=body.identity?`Authenticated Principal ${body.identity.principalId} → Profile Subject ${body.identity.userId} · Deployment ${body.identity.deploymentId}. Speaker unverified; audience is selected separately.`:'No stable profile mapping yet. Saving a declaration explicitly establishes your authenticated subject.';get('person-history').innerHTML=profiles.map(item=>`<option value="${esc(item.profileId)}">Revision ${item.revision} · ${esc(item.status)}</option>`).join('');get('person-revoke').disabled=!active;renderDraft();};
 get('person-refresh').onclick=guard(refresh);get('person-add').onclick=()=>{const key=get('person-key').value.trim(),value=get('person-value').value.trim();if(!key||!value)return show('Enter a declaration key and value.',true);declarations=declarations.filter(item=>item.key!==key);declarations.push({key,value,sensitivity:get('person-sensitivity').value});draft=null;renderDraft();};
 get('person-declarations').onclick=event=>{const button=event.target.closest('[data-remove]');if(button){const [removed]=declarations.splice(Number(button.dataset.remove),1);scopes=scopes.map(scope=>({...scope,allowedKeys:scope.allowedKeys.filter(key=>key!==removed.key)}));draft=null;renderDraft();}};
 get('person-scope').onclick=()=>{const assistantId=context()?.assistantId;if(!assistantId)return show('Select an Assistant first.',true);scopes=scopes.filter(scope=>scope.assistantId!==assistantId);scopes.push({assistantId,allowedKeys:[...get('person-keys').selectedOptions].map(item=>item.value),purposes:['conversation','personalization','mention'],audiences:['authenticatedSession']});draft=null;renderDraft();};
 const preview=body=>{draft=body.profile;get('person-preview-result').textContent=`Draft Revision ${draft.revision}: ${draft.declarations.length} Declarations; ${draft.assistantScopes.length} Explicit Assistant Subsets. Active profile remains revision ${active?.revision||'none'}. Review before activation.`;renderDraft();};
 get('person-preview').onclick=guard(async()=>preview(await api(path,{method:'POST',body:JSON.stringify({declarations,assistantScopes:scopes,expectedActiveRevision:active?.revision??null})})));
 get('person-activate').onclick=guard(async()=>{if(!draft)return;await api(path+'/activate',{method:'POST',body:JSON.stringify({profileId:draft.profileId,expectedRevision:draft.revision,expectedActiveRevision:active?.revision??null})});await refresh();get('person-preview-result').textContent='Reviewed profile activated. Only explicit subsets are eligible.';});
 get('person-revoke').onclick=guard(async()=>{if(!active)return;await api(path+'/revoke',{method:'POST',body:JSON.stringify({profileId:active.profileId,expectedRevision:active.revision,expectedActiveRevision:active.revision})});await refresh();get('person-preview-result').textContent='Active profile revoked; its subsets are withheld.';});
 get('person-rollback').onclick=guard(async()=>{const body=await api(path+'/rollback',{method:'POST',body:JSON.stringify({profileId:get('person-history').value,expectedActiveRevision:active?.revision??null})});declarations=structuredClone(body.profile.declarations);scopes=structuredClone(body.profile.assistantScopes);preview(body);});
 get('person-export').onclick=guard(async()=>{const body=await api(path+'/export');const selected=body.profiles.find(item=>item.profileId===get('person-history').value)||body.profiles.find(item=>item.status==='active');if(!selected)throw new Error('Select a retained profile revision to export.');const link=document.createElement('a');link.download='user-profile.json';link.href=URL.createObjectURL(new Blob([JSON.stringify(selected,null,2)],{type:'application/json'}));link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);});
 window.addEventListener('lifestream-auth',()=>{epoch++;declarations=[];scopes=[];profiles=[];active=null;draft=null;get('person-identity').textContent='Sign in and refresh your profile.';get('person-preview-result').textContent='';get('person-history').replaceChildren();renderDraft();});
 return {refresh};
}
