import assert from 'node:assert/strict';
import test from 'node:test';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawnSync} from 'node:child_process';
import type * as G from '@lifestream/contracts/game-activity';
import {Database} from '../src/database.ts';
import {ActivityCheckpointRepository,type ActivityMetadataOptions,type PlanningReservation} from '../src/game-activity.ts';
import {gameCampaignFixture} from '../../runtime/test/fixtures/game-campaign.ts';
function fixture(path=':memory:',quotas:Partial<Pick<ActivityMetadataOptions,'maxRuns'|'maxReservations'|'maxCheckpointBytes'>>={}){
 const f=gameCampaignFixture(),scope=f.input.expectedScope,owner={assistantId:scope.assistantId,principalId:scope.principalId,relationshipId:scope.relationshipId};let now=f.input.nowMs,allowed=true,quarantined=false,current=true;
 const bounds:G.GameBounds={maxActionFrames:120,maxInputLeaseMs:2000,maxActionWallMs:2000,maxScreenshotBytes:1024,maxScreenshotLongEdge:256,wallBudgetMs:1000000,frameBudget:1000000,actionBudget:100,startBudget:10,equivalentFailureBudget:10,screenshotQueueByteBudget:10000,modelCallBudget:2,inputTokenBudget:10000,outputTokenBudget:10000,retryBudget:1,checkpointByteBudget:65536,memoryEpisodeBudget:8,decisionDeadlineMs:3000,renderedSpeedFactor:1,fastForwardEnabled:false,rewindEnabled:false,planningClockPolicy:'continuesNormally',maxPlanningAgeMs:30000,maxPlanningFrameDelta:120};
 const policy={enabled:true,revision:1,retentionMs:3600000,bounds};
 const options:ActivityMetadataOptions={maxRuns:4,maxReservations:8,maxCheckpointBytes:32768,...quotas,scopeCurrent:()=>allowed,quarantined:()=>quarantined,policyFor:()=>policy,allowCreate:()=>true,checkpointCurrent:()=>current,transitionCurrent:()=>true,planningCurrent:()=>current,usageCurrent:()=>current,now:()=>now};
 let db=new Database({path});db.migrate();let repository=new ActivityCheckpointRepository(db,options);
 const checkpoint:G.ActivityCheckpoint={schemaVersion:'1.0.0',recordType:'activityCheckpoint',scope,checkpointId:randomUUID(),revision:1,stateRevision:1,policyRevision:1,pinsDigest:f.input.pinsDigest,goalSummary:'Scripted unfinished goal; no real game progress.',recentObservationIds:[f.input.observation.observationId],adviceRefs:[],lastObservationId:f.input.observation.observationId,lastActionReceipt:null,saveArtifact:null,budgetUsed:{wallMs:0,frames:0,actions:0,starts:1,equivalentFailures:0,modelCalls:0,inputTokens:0,outputTokens:0,retries:0,checkpointBytes:0,memoryEpisodes:0},recordedAt:new Date(now).toISOString(),resumeDisposition:'requiresReconciliation',campaignJournalRef:{campaignId:f.input.journal.campaignId,journalId:f.input.journal.journalId,revision:1,accessRevision:1}};
 const reservation:PlanningReservation={viewId:randomUUID(),viewRevision:1,invalidationKey:randomUUID(),providerRevision:'scripted-provider:1',maximumInputTokens:8192,maximumOutputTokens:1024};
 return {f,scope,owner,checkpoint,reservation,policy,options,get db(){return db;},get repository(){return repository;},clock:(n:number)=>{now=n;},deny:()=>{allowed=false;},quarantine:(v:boolean)=>{quarantined=v;},source:(v:boolean)=>{current=v;},reopen:()=>{db.close();db=new Database({path});db.migrate();repository=new ActivityCheckpointRepository(db,options);}};
}
test('actual SQLite close/open retains metadata, usage floors and held reservation identity without controller/save bytes or resume authority',t=>{
 const root=mkdtempSync(join(tmpdir(),'activity-checkpoint-')),f=fixture(join(root,'metadata.sqlite'));t.after(()=>{f.db.close();rmSync(root,{recursive:true,force:true});});const saved=f.repository.put(f.owner,f.checkpoint,0);assert.ok(saved.budgetUsed.checkpointBytes>0);assert.equal(f.repository.reservePlanning(f.owner,f.scope,f.reservation),true);f.reopen();const restored=f.repository.get(f.owner,f.scope.runId)!;assert.deepEqual(restored.checkpoint,saved);assert.equal(restored.continuationAuthority,false);assert.equal(restored.recoveryDisposition,'unavailable');assert.deepEqual(restored.reserved,{modelCalls:1,inputTokens:8192,outputTokens:1024});assert.equal(restored.used.modelCalls,0);assert.equal(f.repository.reservePlanning(f.owner,f.scope,f.reservation),false);assert.equal(f.repository.reservePlanning(f.owner,f.scope,{...f.reservation,providerRevision:'changed'}),false);assert.doesNotMatch(JSON.stringify(restored),/emulatorSnapshot|buttonVector|saveState/);
});
test('evidenced terminal usage settles once; unknown reservations remain held and consumed usage cannot roll back',t=>{
 const f=fixture();t.after(()=>f.db.close());f.repository.put(f.owner,f.checkpoint,0);f.repository.reservePlanning(f.owner,f.scope,f.reservation);const usage={inputTokens:100,outputTokens:50,providerRevision:f.reservation.providerRevision,completionRef:'scripted-actual-provider-terminal'};assert.equal(f.repository.settlePlanning(f.owner,f.scope,f.reservation,usage),true);assert.equal(f.repository.settlePlanning(f.owner,f.scope,f.reservation,usage),false);const state=f.repository.get(f.owner,f.scope.runId)!;assert.deepEqual(state.reserved,{modelCalls:0,inputTokens:0,outputTokens:0});assert.equal(state.used.modelCalls,1);assert.equal(state.used.inputTokens,100);assert.equal(state.used.outputTokens,50);assert.equal(state.checkpoint.budgetUsed.modelCalls,0,'original checkpoint is historical, not silently rewritten');const next={...state.checkpoint,revision:2,stateRevision:2};assert.throws(()=>f.repository.put(f.owner,next,1),/budgetExceeded/);next.budgetUsed=state.used;const saved=f.repository.put(f.owner,next,1);assert.equal(saved.budgetUsed.modelCalls,1);assert.ok(saved.budgetUsed.checkpointBytes>state.used.checkpointBytes);
});
test('an older ordinary-save branch can advance epoch/timeline while preserving every usage floor and original opaque save attribution',t=>{
 const f=fixture();t.after(()=>f.db.close());const first=f.repository.put(f.owner,f.checkpoint,0),next=structuredClone(first);next.revision=2;next.stateRevision=2;next.scope.activityEpoch++;next.scope.timelineId=randomUUID();next.scope.timelineRevision=1;next.saveArtifact=f.f.input.binding.ordinarySaveArtifact;const stored=f.repository.put(f.owner,next,1);assert.notEqual(stored.saveArtifact!.sourceTimelineId,stored.scope.timelineId);const view=f.repository.get(f.owner,f.scope.runId)!;assert.equal(view.recoveryDisposition,'requiresReconciliation');assert.equal(view.continuationAuthority,false);assert.equal(f.repository.reservePlanning(f.owner,f.scope,f.reservation),false,'old epoch cannot reserve new work');assert.equal(f.repository.reservePlanning(f.owner,stored.scope,f.reservation),true);
});
test('foreign owner/run ID collisions cannot overwrite another relationship checkpoint',t=>{
 const f=fixture();t.after(()=>f.db.close());const saved=f.repository.put(f.owner,f.checkpoint,0),otherOwner={...f.owner,principalId:randomUUID()},other=structuredClone(f.checkpoint);other.scope.principalId=otherOwner.principalId;assert.throws(()=>f.repository.put(otherOwner,other,0),/unavailable/);assert.equal(f.repository.get(otherOwner,f.scope.runId),null);assert.deepEqual(f.repository.get(f.owner,f.scope.runId)!.checkpoint,saved);
});
test('checkpoint CAS, epoch/state/timeline revisions and independently qualified transition refuse rollback',async t=>{
 for(const mode of ['revision','epoch','state','timeline','newTimelineWithoutEpoch','transition'])await t.test(mode,()=>{
  const f=fixture();try{f.checkpoint.scope.timelineRevision=2;f.checkpoint.stateRevision=2;const saved=f.repository.put(f.owner,f.checkpoint,0),next=structuredClone(saved);next.revision=2;if(mode==='revision')next.revision=1;if(mode==='epoch')next.scope.activityEpoch--;if(mode==='state')next.stateRevision--;if(mode==='timeline')next.scope.timelineRevision--;if(mode==='newTimelineWithoutEpoch')next.scope.timelineId=randomUUID();if(mode==='transition')f.options.transitionCurrent=()=>false;assert.throws(()=>f.repository.put(f.owner,next,1),/revisionConflict|unavailable/);}finally{f.db.close();}
 });
});
test('finite explicit quotas and actual cumulative checkpoint bytes refuse excess; cancelled/unknown reservations never silently release capacity',async t=>{
 for(const mode of ['input','output','calls','storage','runs','reservations'])await t.test(mode,()=>{
  const f=fixture(':memory:',mode==='runs'?{maxRuns:1}:mode==='reservations'?{maxReservations:1}:{});try{if(mode==='storage')f.policy.bounds.checkpointByteBudget=1;else {if(mode==='output')f.policy.bounds.outputTokenBudget=1;if(mode==='calls')f.policy.bounds.modelCallBudget=1;f.repository.put(f.owner,f.checkpoint,0);}if(mode==='storage')assert.throws(()=>f.repository.put(f.owner,f.checkpoint,0),/budgetExceeded/);else if(mode==='runs'){const other=structuredClone(f.checkpoint);other.scope.runId=randomUUID();assert.throws(()=>f.repository.put(f.owner,other,0),/capacity/);}else{if(mode==='input')f.reservation.maximumInputTokens=10001;if(mode==='output')f.reservation.maximumOutputTokens=4096;
   if(mode==='input'||mode==='output'){assert.throws(()=>f.repository.reservePlanning(f.owner,f.scope,f.reservation),/budgetExceeded/);}else{assert.equal(f.repository.reservePlanning(f.owner,f.scope,f.reservation),true);const next={...f.reservation,viewId:randomUUID()};assert.throws(()=>f.repository.reservePlanning(f.owner,f.scope,next),/budgetExceeded|capacity/);}
  }}finally{f.db.close();}
 });
});
test('quarantine, owner withdrawal and missing current grounding withhold use, reservation and writes without granting recovery',async t=>{
 for(const mode of ['quarantine','owner','source'])await t.test(mode,()=>{const f=fixture();try{f.repository.put(f.owner,f.checkpoint,0);if(mode==='quarantine')f.quarantine(true);if(mode==='owner')f.deny();if(mode==='source')f.source(false);assert.equal(f.repository.get(f.owner,f.scope.runId),null);assert.equal(f.repository.reservePlanning(f.owner,f.scope,f.reservation),false);assert.throws(()=>f.repository.put(f.owner,{...f.checkpoint,revision:2},1),/unavailable|budgetExceeded/);if(mode==='source'){assert.equal(f.db.connection.prepare('SELECT payload_json FROM activity_checkpoints').get()!.payload_json,null);f.source(true);assert.equal(f.repository.get(f.owner,f.scope.runId),null,'forgotten source cannot revive previous prose');}}finally{f.db.close();}});
});
test('source invalidation erases checkpoint prose while preserving opaque counters/held identities, then requires grounded new metadata',t=>{
 const f=fixture();t.after(()=>f.db.close());const saved=f.repository.put(f.owner,f.checkpoint,0);f.repository.reservePlanning(f.owner,f.scope,f.reservation);f.repository.invalidate(f.owner,f.scope.runId);assert.equal(f.repository.get(f.owner,f.scope.runId),null);assert.equal(f.db.connection.prepare('SELECT payload_json FROM activity_checkpoints').get()!.payload_json,null);const next={...saved,revision:2,stateRevision:2,goalSummary:'New independently grounded scripted goal.'};f.repository.put(f.owner,next,1);assert.equal(f.repository.reservePlanning(f.owner,f.scope,f.reservation),false);assert.equal(f.repository.get(f.owner,f.scope.runId)!.reserved.modelCalls,1);
});
test('finite retention does not renew on writes, survives restart, erases payload and cannot resurrect an expired run',t=>{
 const root=mkdtempSync(join(tmpdir(),'activity-expiry-')),f=fixture(join(root,'metadata.sqlite'));t.after(()=>{f.db.close();rmSync(root,{recursive:true,force:true});});f.policy.retentionMs=100;const saved=f.repository.put(f.owner,f.checkpoint,0);f.clock(f.f.input.nowMs+50);f.repository.put(f.owner,{...saved,revision:2,stateRevision:2},1);f.reopen();f.clock(f.f.input.nowMs+101);assert.equal(f.repository.get(f.owner,f.scope.runId),null);assert.equal(f.db.connection.prepare('SELECT payload_json FROM activity_checkpoints').get()!.payload_json,null);assert.throws(()=>f.repository.put(f.owner,{...saved,revision:3},2),/revisionConflict/);
});
test('policy withdrawal/change retracts source prose and cannot reinterpret old reservations under a newly permissive configuration',async t=>{
 for(const mode of ['disabled','revision','bounds'])await t.test(mode,()=>{const f=fixture();try{f.repository.put(f.owner,f.checkpoint,0);f.repository.reservePlanning(f.owner,f.scope,f.reservation);if(mode==='disabled')f.policy.enabled=false;if(mode==='revision')f.policy.revision++;if(mode==='bounds')f.policy.bounds.inputTokenBudget++;assert.equal(f.repository.get(f.owner,f.scope.runId),null);assert.equal(f.db.connection.prepare('SELECT payload_json FROM activity_checkpoints').get()!.payload_json,null);assert.equal(f.repository.reservePlanning(f.owner,f.scope,{...f.reservation,viewId:randomUUID()}),false);}finally{f.db.close();}});
});
test('backward UTC after actual reopen refuses reads/writes/admission rather than resurrecting metadata',t=>{
 const root=mkdtempSync(join(tmpdir(),'activity-clock-')),f=fixture(join(root,'metadata.sqlite'));t.after(()=>{f.db.close();rmSync(root,{recursive:true,force:true});});f.repository.put(f.owner,f.checkpoint,0);f.reopen();f.clock(f.f.input.nowMs-1);assert.throws(()=>f.repository.get(f.owner,f.scope.runId),/clockUncertain/);assert.throws(()=>f.repository.reservePlanning(f.owner,f.scope,f.reservation),/clockUncertain/);
});
test('policy/source expiry during final callback rolls back checkpoint, reservation or usage settlement atomically',async t=>{
 for(const mode of ['checkpoint','reservation','usage'])await t.test(mode,()=>{const f=fixture();try{if(mode!=='checkpoint')f.repository.put(f.owner,f.checkpoint,0);if(mode==='usage')f.repository.reservePlanning(f.owner,f.scope,f.reservation);let calls=0;if(mode==='checkpoint')f.options.checkpointCurrent=()=>{if(++calls===2)f.policy.enabled=false;return true;};if(mode==='reservation')f.options.planningCurrent=()=>{if(++calls===2)f.policy.enabled=false;return true;};if(mode==='usage')f.options.usageCurrent=()=>{if(++calls===2)f.policy.enabled=false;return true;};if(mode==='checkpoint'){assert.throws(()=>f.repository.put(f.owner,f.checkpoint,0),/unavailable/);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM activity_checkpoints').get()!.n,0);}if(mode==='reservation'){assert.throws(()=>f.repository.reservePlanning(f.owner,f.scope,f.reservation),/unavailable/);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM activity_planning_reservations').get()!.n,0);}if(mode==='usage'){assert.throws(()=>f.repository.settlePlanning(f.owner,f.scope,f.reservation,{inputTokens:100,outputTokens:10,providerRevision:f.reservation.providerRevision,completionRef:'scripted-qualified-terminal'}),/unavailable/);assert.equal(f.db.connection.prepare('SELECT state FROM activity_planning_reservations').get()!.state,'reserved');}}finally{f.db.close();}});
});
test('unqualified/foreign/excess usage cannot settle held budget, and getters/snapshots/hidden fields are never accepted',t=>{
 const f=fixture();t.after(()=>f.db.close());f.repository.put(f.owner,f.checkpoint,0);f.repository.reservePlanning(f.owner,f.scope,f.reservation);const usage={inputTokens:100,outputTokens:10,providerRevision:f.reservation.providerRevision,completionRef:'scripted-terminal'};f.options.usageCurrent=()=>false;assert.equal(f.repository.settlePlanning(f.owner,f.scope,f.reservation,usage),false);f.options.usageCurrent=()=>true;assert.equal(f.repository.settlePlanning(f.owner,f.scope,f.reservation,{...usage,inputTokens:8193}),false);assert.equal(f.repository.settlePlanning(f.owner,f.scope,f.reservation,{...usage,providerRevision:'foreign'}),false);let reads=0;const raw:any={...f.checkpoint,revision:2};Object.defineProperty(raw,'goalSummary',{enumerable:true,get(){reads++;return 'hidden';}});assert.throws(()=>f.repository.put(f.owner,raw,1),/invalidMetadata/);assert.equal(reads,0);assert.throws(()=>f.repository.put(f.owner,{...f.checkpoint,emulatorSnapshot:'forbidden'} as any,0),/invalidMetadata/);
});
test('a separate real Node process reopens only metadata, preserves reservation deduplication and cannot obtain resume authority',t=>{
 const root=mkdtempSync(join(tmpdir(),'activity-process-')),path=join(root,'metadata.sqlite'),f=fixture(path);t.after(()=>rmSync(root,{recursive:true,force:true}));f.repository.put(f.owner,f.checkpoint,0);f.repository.reservePlanning(f.owner,f.scope,f.reservation);f.db.close();
 const script=`import {Database} from ${JSON.stringify(new URL('../src/database.ts',import.meta.url).href)};import {ActivityCheckpointRepository} from ${JSON.stringify(new URL('../src/game-activity.ts',import.meta.url).href)};const input=JSON.parse(process.argv[1]),db=new Database({path:input.path});db.migrate();const repository=new ActivityCheckpointRepository(db,{maxRuns:4,maxReservations:8,maxCheckpointBytes:32768,scopeCurrent:()=>true,quarantined:()=>false,policyFor:()=>input.policy,allowCreate:()=>false,checkpointCurrent:()=>true,transitionCurrent:()=>false,planningCurrent:()=>true,usageCurrent:()=>false});const view=repository.get(input.owner,input.scope.runId);console.log(JSON.stringify({reserved:view.reserved,used:view.used,continuationAuthority:view.continuationAuthority,recoveryDisposition:view.recoveryDisposition,duplicate:repository.reservePlanning(input.owner,input.scope,input.reservation)}));db.close();`;
 const child=spawnSync(process.execPath,['--experimental-strip-types','--input-type=module','-e',script,JSON.stringify({path,policy:f.policy,owner:f.owner,scope:f.scope,reservation:f.reservation})],{encoding:'utf8',timeout:10000});assert.equal(child.status,0,child.stderr);const result=JSON.parse(child.stdout);assert.equal(result.reserved.modelCalls,1);assert.equal(result.used.modelCalls,0);assert.equal(result.duplicate,false);assert.equal(result.continuationAuthority,false);assert.equal(result.recoveryDisposition,'unavailable');
});
test('finite repository quotas stay pinned even if the caller later mutates the options object',t=>{
 const f=fixture(':memory:',{maxRuns:1});t.after(()=>f.db.close());f.repository.put(f.owner,f.checkpoint,0);f.options.maxRuns=Infinity;const other=structuredClone(f.checkpoint);other.scope.runId=randomUUID();assert.throws(()=>f.repository.put(f.owner,other,0),/capacity/);
});
test('expiry during a final trusted callback rolls back each metadata mutation',async t=>{for(const mode of ['checkpoint','reservation','usage'])await t.test(mode,()=>{const f=fixture();try{if(mode!=='checkpoint')f.repository.put(f.owner,f.checkpoint,0);if(mode==='usage')f.repository.reservePlanning(f.owner,f.scope,f.reservation);let calls=0;const expire=()=>{if(++calls===2)f.clock(f.f.input.nowMs+f.policy.retentionMs+1);return true;};if(mode==='checkpoint')f.options.checkpointCurrent=expire;if(mode==='reservation')f.options.planningCurrent=expire;if(mode==='usage')f.options.usageCurrent=expire;if(mode==='checkpoint'){assert.throws(()=>f.repository.put(f.owner,f.checkpoint,0),/unavailable/);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM activity_checkpoints').get()!.n,0);}if(mode==='reservation'){assert.throws(()=>f.repository.reservePlanning(f.owner,f.scope,f.reservation),/unavailable/);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM activity_planning_reservations').get()!.n,0);}if(mode==='usage'){assert.throws(()=>f.repository.settlePlanning(f.owner,f.scope,f.reservation,{inputTokens:1,outputTokens:1,providerRevision:f.reservation.providerRevision,completionRef:'scripted-terminal'}),/unavailable/);assert.equal(f.db.connection.prepare('SELECT state FROM activity_planning_reservations').get()!.state,'reserved');}}finally{f.db.close();}});});
test('bounded host cleanup expires private payload even in restore quarantine and preserves opaque reservation fences',t=>{
 const f=fixture();t.after(()=>f.db.close());f.repository.put(f.owner,f.checkpoint,0);f.repository.reservePlanning(f.owner,f.scope,f.reservation);f.quarantine(true);f.clock(f.f.input.nowMs+f.policy.retentionMs+1);f.repository.sweep();assert.equal(f.db.connection.prepare('SELECT payload_json FROM activity_checkpoints').get()!.payload_json,null);assert.equal(f.db.connection.prepare('SELECT state FROM activity_planning_reservations').get()!.state,'reserved');
});
