import assert from 'node:assert/strict';import test from 'node:test';import {randomUUID,createHash} from 'node:crypto';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {Database} from '../src/database.ts';import {ExperienceRepository} from '../src/experience.ts';import {defaultTopics,type ExperienceScope,type ExperiencePolicy,type ReflectionResult,type Source} from '@lifestream/contracts/experience';
const scope=():ExperienceScope=>({assistantId:randomUUID(),principalId:randomUUID(),relationshipId:randomUUID()});
const policy:ExperiencePolicy={allowed:true,revision:1,dimensions:{attentionGardening:{minimum:-1,maximum:1,delta:.05},attentionReading:{minimum:-1,maximum:1,delta:.05}}};
const source=(n:number):Source=>({id:'source-'+n,revision:1,family:'turn:'+n,digest:createHash('sha256').update('experience '+n).digest('hex'),content:'I enjoyed gardening project '+n,occurredAt:'2026-09-01T00:00:00Z'});
async function setup(t:any){const root=await mkdtemp(join(tmpdir(),'experience-store-'));t.after(()=>rm(root,{recursive:true,force:true}));let db=new Database({path:join(root,'db.sqlite')});db.migrate();t.after(()=>db.close());const clock={now:Date.parse('2026-09-01T00:00:00Z')},s=scope();let repo=new ExperienceRepository(db,()=>clock.now);repo.configure(s,0,{enabled:true,frozen:false,retention:'sourceBound',topicPolicies:defaultTopics},policy);return {get repo(){return repo;},s,clock,restart(){db.close();db=new Database({path:join(root,'db.sqlite')});db.migrate();repo=new ExperienceRepository(db,()=>clock.now);repo.recover();}};}
const result=(refs:string[],episodes:string[],delta=.05):ReflectionResult=>({recordType:'reflectionResult',decision:'change',conclusion:'The independently reported project outcomes support a next step.',items:[{id:'garden-project',expectedRevision:0,kind:'project',topic:'gardening',statement:'Compare two garden beds',nextStep:'Plan one soil trial',uncertainty:'medium',sourceRefs:refs,disposition:'open'}],changes:delta?[{dimension:'attentionGardening',delta,episodeRefs:episodes,confidence:.9,reason:'Two separately sourced outcomes'}]:[]});
async function learned(t:any){const ctx=await setup(t),sources=[source(1),source(2)],a=ctx.repo.enqueue(ctx.s,[sources[0]!],'project',policy)!,b=ctx.repo.enqueue(ctx.s,[sources[1]!],'project',policy)!;ctx.clock.now+=60001;assert.equal(ctx.repo.admit(b,'fixture'),true);ctx.repo.called(ctx.s);ctx.repo.publish(b,result(sources.map(s=>s.id),[a.id,b.id]),policy,sources);ctx.repo.finish(b,'published',{inputTokens:100,outputTokens:90,elapsedMs:2});return {...ctx,get repo(){return ctx.repo;},sources,a,b};}
test('closed database restart retains workspace, independent bounded imprint and provenance',async t=>{const c=await learned(t),before=c.repo.read(c.s);c.restart();assert.deepEqual(c.repo.read(c.s),before);assert.equal(before.items[0]?.disposition,'open');assert.equal(before.imprints[0]?.value,.05);assert.equal(c.repo.enqueue(c.s,[source(1)],'project',policy),null);assert.equal(c.repo.read(scope()).imprints[0]?.value,0);assert.equal(c.repo.read(c.s).funnel.calls,1);});
test('missing policy, duplicate sources, delta excess and rollback cannot inflate learning',async t=>{const c=await setup(t);assert.throws(()=>c.repo.configure(c.s,1,{enabled:true,frozen:false,retention:'sourceBound',topicPolicies:defaultTopics},{...policy,allowed:false}),/policy/);const one=source(1),job=c.repo.enqueue(c.s,[one],'interest',policy)!;c.clock.now+=60001;assert.ok(c.repo.admit(job,'fixture'));const before=c.repo.read(c.s);assert.throws(()=>c.repo.publish(job,result([one.id],[job.id,job.id]),policy,[one]),/independent/);assert.throws(()=>c.repo.publish(job,result([one.id],[job.id],.051),policy,[one]),/invalid_Result/);assert.deepEqual(c.repo.read(c.s),before);});
test('forgetting removes dependent content and inverse payload and fences late work after restart',async t=>{const c=await learned(t);const pending=c.repo.enqueue(c.s,[source(3)],'project',policy)!;c.clock.now+=60001;assert.ok(c.repo.admit(pending,'fixture'));c.repo.reconcile(c.s,[],policy);assert.equal(c.repo.current(pending),false);assert.equal(c.repo.read(c.s).imprints[0]?.value,0);assert.equal(c.repo.read(c.s).items[0]?.statement,'');assert.equal(c.repo.read(c.s).items[0]?.disposition,'invalidated');assert.throws(()=>c.repo.publish(pending,result(['source-3'],[pending.id],0),policy,[source(3)]),/stale/);c.restart();assert.equal(c.repo.current(pending),false);assert.doesNotMatch(JSON.stringify(c.repo.read(c.s)),/Compare two garden beds|Plan one soil trial/);});
test('freeze blocks admission; reset and inverse are local and idempotent',async t=>{const c=await learned(t),line=c.repo.lineage(c.s).find(l=>l.operation==='reflection')!;let state=c.repo.reverse(c.s,c.repo.read(c.s).revision,line.id);assert.equal(state.items.length,0);assert.equal(state.imprints[0]?.value,0);assert.deepEqual(c.repo.reverse(c.s,0,line.id),state);state=c.repo.configure(c.s,state.revision,{enabled:true,frozen:true,retention:'sourceBound',topicPolicies:defaultTopics},policy);assert.equal(c.repo.enqueue(c.s,[source(3)],'interest',policy),null);state=c.repo.reset(c.s,state.revision);assert.equal(state.items.length,0);assert.equal(c.repo.read(scope()).revision,0);});
test('capacity and closed-item rules reject the whole proposed update without eviction',async t=>{const c=await setup(t),s=source(1),job=c.repo.enqueue(c.s,[s],'project',policy)!;c.clock.now+=60001;assert.ok(c.repo.admit(job,'fixture'));const proposal=result([s.id],[],0);proposal.items=Array.from({length:16},(_,n)=>({...proposal.items[0]!,id:'item-'+n}));c.repo.publish(job,proposal,policy,[s]);const before=c.repo.read(c.s);const more=result([s.id],[],0);assert.throws(()=>c.repo.publish(job,more,policy,[s]),/capacity/);assert.deepEqual(c.repo.read(c.s),before);const resolve=result([s.id],[],0);resolve.items=[{...proposal.items[0]!,expectedRevision:1,disposition:'resolved'}];c.repo.publish(job,resolve,policy,[s]);resolve.items[0]!.expectedRevision=2;resolve.items[0]!.disposition='open';assert.throws(()=>c.repo.publish(job,resolve,policy,[s]),/closed_item/);});
test('calls and one retry persist across restart and daily rollover',async t=>{const c=await setup(t);for(let n=0;n<4;n++){const j=c.repo.enqueue(c.s,[source(n)],'interest',policy)!;c.clock.now+=60001;assert.ok(c.repo.admit(j,'fixture'));c.repo.called(c.s);c.repo.finish(j,'provider_failed');c.clock.now+=60001;assert.ok(c.repo.admit(j,'fixture'));c.repo.called(c.s);c.repo.finish(j,'provider_failed');assert.equal(c.repo.admit(j,'fixture'),false);}const ninth=c.repo.enqueue(c.s,[source(9)],'interest',policy)!;c.clock.now+=60001;c.restart();assert.equal(c.repo.admit(ninth,'fixture'),false);assert.equal(c.repo.read(c.s).funnel.calls,8);c.clock.now+=86400000;assert.equal(c.repo.admit(ninth,'fixture'),true);});
test('rolling absolute delta budget survives inverse and restart; stricter profile and thirty-day expiry are enforced',async t=>{
 const c=await setup(t);const sources:Source[]=[];const apply=(n:number,delta=.05,p=policy)=>{const pair=[source(n*2+20),source(n*2+21)];sources.push(...pair);const jobs=pair.map(s=>c.repo.enqueue(c.s,[s],'outcome',p)!);c.clock.now+=60001;assert.ok(c.repo.admit(jobs[1]!,'fixture'));const proposal=result(pair.map(s=>s.id),jobs.map(j=>j.id),delta);proposal.items=[];c.repo.publish(jobs[1]!,proposal,p,sources);c.repo.finish(jobs[1]!,'published');c.repo.finish(jobs[0]!,'noChange');return jobs[1]!;};
 for(let n=0;n<4;n++){apply(n);if(n===1)c.restart();}assert.ok(Math.abs(c.repo.read(c.s).imprints[0]!.value-.20)<1e-12);const line=c.repo.lineage(c.s).find(l=>l.operation==='reflection')!;c.repo.reverse(c.s,c.repo.read(c.s).revision,line.id);assert.throws(()=>apply(4),/rolling_delta_limit/);c.restart();c.clock.now+=31*86400000;apply(5);assert.ok(Math.abs(c.repo.read(c.s).imprints[0]!.value-.20)<1e-12);assert.throws(()=>apply(6,.04,{...policy,dimensions:{attentionGardening:{minimum:-1,maximum:1,delta:.03}}}),/delta_not_allowed/);
});
test('forgetting also erases no-change and previously reversed summaries and their inverse payloads',async t=>{
 const c=await learned(t);const line=c.repo.lineage(c.s).find(l=>l.operation==='reflection')!;c.repo.reverse(c.s,c.repo.read(c.s).revision,line.id);assert.equal(c.repo.read(c.s).imprints[0]!.confidence,0);
 const fresh=source(3),job=c.repo.enqueue(c.s,[fresh],'project',policy)!;c.clock.now+=60001;assert.ok(c.repo.admit(job,'fixture'));c.repo.publish(job,{recordType:'reflectionResult',decision:'noChange',conclusion:'PRIVATE_MINIMIZED_SUMMARY',items:[],changes:[]},policy,[fresh]);c.repo.finish(job,'noChange');assert.ok(c.repo.lineage(c.s).some(l=>l.summary==='PRIVATE_MINIMIZED_SUMMARY'));c.repo.reconcile(c.s,[],policy);c.restart();assert.ok(c.repo.lineage(c.s).every(l=>l.summary===''));assert.equal(c.repo.read(c.s).imprints[0]!.confidence,0);
});
test('daily Dreaming reconciles unfinished work through the same persistent budget and never reopens resolved items',async t=>{
 const c=await learned(t);c.repo.finish(c.a,'noChange');assert.equal(c.repo.enqueueConsolidation(c.s,policy),null);c.clock.now+=86400001;const dream=c.repo.enqueueConsolidation(c.s,policy)!;assert.ok(dream);assert.equal(dream.reason,'dreaming_consolidation');assert.equal(c.repo.enqueueConsolidation(c.s,policy),null);c.clock.now+=60001;assert.ok(c.repo.admit(dream,'fixture'));const proposal=result(c.sources.map(s=>s.id),[],0);proposal.items[0]!.expectedRevision=1;proposal.items[0]!.disposition='resolved';c.repo.publish(dream,proposal,policy,c.sources);c.repo.finish(dream,'published');c.restart();c.clock.now+=86400000;assert.equal(c.repo.enqueueConsolidation(c.s,policy),null);assert.equal(c.repo.read(c.s).items[0]!.disposition,'resolved');
});
test('unavailable provider priority is inspectable without spending model calls',async t=>{const c=await setup(t),job=c.repo.enqueue(c.s,[source(1)],'project',policy)!;c.repo.defer(job,'providerPriorityUnverified');assert.equal(c.repo.jobs(c.s)[0]!.reason,'providerPriorityUnverified');assert.equal(c.repo.read(c.s).funnel.calls,0);assert.equal(c.repo.read(c.s).funnel.admitted,0);assert.equal(c.repo.read(c.s).funnel.skips,1);c.repo.defer(job,'providerPriorityUnverified');assert.equal(c.repo.read(c.s).funnel.skips,1);});
