import assert from 'node:assert/strict';import test from 'node:test';import {randomUUID,createHash} from 'node:crypto';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {Database} from '../src/database.ts';import {ExperienceRepository} from '../src/experience.ts';import {defaultTopics,type ExperienceScope,type ExperiencePolicy,type ReflectionResult,type Source} from '@lifestream/contracts/experience';
const scope=():ExperienceScope=>({assistantId:randomUUID(),principalId:randomUUID(),relationshipId:randomUUID()});
const policy:ExperiencePolicy={allowed:true,revision:1,dimensions:{attentionGardening:{minimum:-1,maximum:1,delta:.05},attentionReading:{minimum:-1,maximum:1,delta:.05}}};
const source=(n:number):Source=>({id:'source-'+n,revision:1,family:'turn:'+n,digest:createHash('sha256').update('experience '+n).digest('hex'),content:'I enjoyed gardening project '+n,occurredAt:'2026-09-01T00:00:00Z'});
async function setup(t:any){const root=await mkdtemp(join(tmpdir(),'experience-store-'));t.after(()=>rm(root,{recursive:true,force:true}));let db=new Database({path:join(root,'db.sqlite')});db.migrate();t.after(()=>db.close());const clock={now:Date.parse('2026-09-01T00:00:00Z')},s=scope();let repo=new ExperienceRepository(db,()=>clock.now);repo.configure(s,0,{enabled:true,frozen:false,retention:'sourceBound',topicPolicies:defaultTopics},policy);return {get repo(){return repo;},s,clock,restart(){db.close();db=new Database({path:join(root,'db.sqlite')});db.migrate();repo=new ExperienceRepository(db,()=>clock.now);repo.recover();}};}
const result=(refs:string[],episodes:string[],delta=.05):ReflectionResult=>({recordType:'reflectionResult',decision:'change',conclusion:'The independently reported project outcomes support a next step.',items:[{id:'garden-project',expectedRevision:0,kind:'project',topic:'gardening',statement:'Compare two garden beds',nextStep:'Plan one soil trial',uncertainty:'medium',sourceRefs:refs,disposition:'open'}],changes:delta?[{dimension:'attentionGardening',delta,episodeRefs:episodes,confidence:.9,reason:'Two separately sourced outcomes'}]:[]});
async function learned(t:any){const ctx=await setup(t),sources=[source(1),source(2)],a=ctx.repo.enqueue(ctx.s,[sources[0]!],'project',policy)!,b=ctx.repo.enqueue(ctx.s,[sources[1]!],'project',policy)!;ctx.clock.now+=60001;assert.equal(ctx.repo.admit(b,'fixture'),true);ctx.repo.called(ctx.s);ctx.repo.publish(b,result(sources.map(s=>s.id),[a.id,b.id]),policy,sources);ctx.repo.finish(b,'published',{inputTokens:100,outputTokens:90,elapsedMs:2});return {...ctx,get repo(){return ctx.repo;},sources,a,b};}
test('closed database restart retains workspace, independent bounded imprint and provenance',async t=>{const c=await learned(t),before=c.repo.read(c.s);c.restart();assert.deepEqual(c.repo.read(c.s),before);assert.equal(before.items[0]?.disposition,'open');assert.equal(before.imprints[0]?.value,.05);assert.equal(c.repo.enqueue(c.s,[source(1)],'project',policy),null);assert.equal(c.repo.read(scope()).imprints[0]?.value,0);assert.equal(c.repo.read(c.s).funnel.calls,1);});
test('missing policy, duplicate sources, delta excess and rollback cannot inflate learning',async t=>{const c=await setup(t);assert.throws(()=>c.repo.configure(c.s,1,{enabled:true,frozen:false,retention:'sourceBound',topicPolicies:defaultTopics},{...policy,allowed:false}),/policy/);const one=source(1),job=c.repo.enqueue(c.s,[one],'interest',policy)!;c.clock.now+=60001;assert.ok(c.repo.admit(job,'fixture'));const before=c.repo.read(c.s);assert.throws(()=>c.repo.publish(job,result([one.id],[job.id,job.id]),policy,[one]),/independent|invalid_Result/);assert.throws(()=>c.repo.publish(job,result([one.id],[job.id],.051),policy,[one]),/invalid_Result/);assert.deepEqual(c.repo.read(c.s),before);});
test('forgetting removes dependent content and inverse payload and fences late work after restart',async t=>{const c=await learned(t);const pending=c.repo.enqueue(c.s,[source(3)],'project',policy)!;c.clock.now+=60001;assert.ok(c.repo.admit(pending,'fixture'));c.repo.reconcile(c.s,[],policy);assert.equal(c.repo.current(pending),false);assert.equal(c.repo.read(c.s).imprints[0]?.value,0);assert.equal(c.repo.read(c.s).items[0]?.statement,'');assert.equal(c.repo.read(c.s).items[0]?.disposition,'invalidated');assert.throws(()=>c.repo.publish(pending,result(['source-3'],[pending.id],0),policy,[source(3)]),/stale/);c.restart();assert.equal(c.repo.current(pending),false);assert.doesNotMatch(JSON.stringify(c.repo.read(c.s)),/Compare two garden beds|Plan one soil trial/);});
test('freeze blocks admission; reset and inverse are local and idempotent',async t=>{const c=await learned(t),line=c.repo.lineage(c.s).find(l=>l.operation==='reflection')!;let state=c.repo.reverse(c.s,c.repo.read(c.s).revision,line.id);assert.equal(state.items.length,0);assert.equal(state.imprints[0]?.value,0);assert.deepEqual(c.repo.reverse(c.s,0,line.id),state);state=c.repo.configure(c.s,state.revision,{enabled:true,frozen:true,retention:'sourceBound',topicPolicies:defaultTopics},policy);assert.equal(c.repo.enqueue(c.s,[source(3)],'interest',policy),null);state=c.repo.reset(c.s,state.revision);assert.equal(state.items.length,0);assert.equal(c.repo.read(scope()).revision,0);});
test('capacity and closed-item rules reject the whole proposed update without eviction',async t=>{const c=await setup(t),s=source(1),job=c.repo.enqueue(c.s,[s],'project',policy)!;c.clock.now+=60001;assert.ok(c.repo.admit(job,'fixture'));const proposal=result([s.id],[],0);proposal.items=Array.from({length:16},(_,n)=>({...proposal.items[0]!,id:'item-'+n}));c.repo.publish(job,proposal,policy,[s]);const before=c.repo.read(c.s);const more=result([s.id],[],0);assert.throws(()=>c.repo.publish(job,more,policy,[s]),/capacity/);assert.deepEqual(c.repo.read(c.s),before);const resolve=result([s.id],[],0);resolve.items=[{...proposal.items[0]!,expectedRevision:1,disposition:'resolved'}];c.repo.publish(job,resolve,policy,[s]);resolve.items[0]!.expectedRevision=2;resolve.items[0]!.disposition='open';assert.throws(()=>c.repo.publish(job,resolve,policy,[s]),/closed_item/);});
test('calls and one retry persist across restart and daily rollover',async t=>{const c=await setup(t);for(let n=0;n<4;n++){const j=c.repo.enqueue(c.s,[source(n)],'interest',policy)!;c.clock.now+=60001;assert.ok(c.repo.admit(j,'fixture'));c.repo.called(c.s);c.repo.finish(j,'provider_failed');c.clock.now+=60001;assert.ok(c.repo.admit(j,'fixture'));c.repo.called(c.s);c.repo.finish(j,'provider_failed');assert.equal(c.repo.admit(j,'fixture'),false);}const ninth=c.repo.enqueue(c.s,[source(9)],'interest',policy)!;c.clock.now+=60001;c.restart();assert.equal(c.repo.admit(ninth,'fixture'),false);assert.equal(c.repo.read(c.s).funnel.calls,8);c.clock.now+=86400000;assert.equal(c.repo.admit(ninth,'fixture'),true);});
test('rolling absolute delta budget survives inverse and restart; stricter profile and thirty-day expiry are enforced',async t=>{
 const c=await setup(t);const sources:Source[]=[];const apply=(n:number,delta=.05,p=policy)=>{const pair=[source(n*2+20),source(n*2+21)];sources.push(...pair);const jobs=pair.map(s=>c.repo.enqueue(c.s,[s],'outcome',p)!);c.clock.now+=60001;assert.ok(c.repo.admit(jobs[1]!,'fixture'));const proposal=result(pair.map(s=>s.id),jobs.map(j=>j.id),delta);proposal.items=[];c.repo.publish(jobs[1]!,proposal,p,sources);c.repo.finish(jobs[1]!,'published');c.repo.finish(jobs[0]!,'noChange');return jobs[1]!;};
 for(let n=0;n<4;n++){apply(n);if(n===1)c.restart();}assert.ok(Math.abs(c.repo.read(c.s).imprints[0]!.value-.20)<1e-12);const line=c.repo.lineage(c.s).find(l=>l.operation==='reflection')!;c.repo.reverse(c.s,c.repo.read(c.s).revision,line.id);assert.throws(()=>apply(4),/rolling_delta_limit/);c.restart();c.clock.now+=31*86400000;apply(5);assert.ok(Math.abs(c.repo.read(c.s).imprints[0]!.value-.20)<1e-12);assert.throws(()=>apply(6,.04,{...policy,dimensions:{attentionGardening:{minimum:-1,maximum:1,delta:.03}}}),/delta_not_allowed/);
});
test('forgetting also erases no-change and previously reversed summaries and their inverse payloads',async t=>{
 const c=await learned(t);const line=c.repo.lineage(c.s).find(l=>l.operation==='reflection')!;c.repo.reverse(c.s,c.repo.read(c.s).revision,line.id);assert.equal(c.repo.read(c.s).imprints[0]!.confidence,0);
 const fresh=source(3),job=c.repo.enqueue(c.s,[fresh],'project',policy)!;c.clock.now+=60001;assert.ok(c.repo.admit(job,'fixture'));c.repo.publish(job,{recordType:'reflectionResult',decision:'noChange',conclusion:'PRIVATE_MINIMIZED_SUMMARY',items:[],changes:[]},policy,[fresh]);c.repo.finish(job,'noChange');assert.ok(c.repo.lineage(c.s).some(l=>l.summary==='PRIVATE_MINIMIZED_SUMMARY'));c.repo.reconcile(c.s,[],policy);c.restart();assert.ok(c.repo.lineage(c.s).every(l=>l.summary===''));assert.equal(c.repo.read(c.s).imprints[0]!.confidence,0);
});
test('daily Dreaming reconciles unfinished work through the same persistent budget and never reopens resolved items',async t=>{
 const c=await learned(t);c.repo.finish(c.a,'noChange');assert.equal(c.repo.enqueueConsolidation(c.s,policy),null);c.clock.now+=86400001;const dream=c.repo.enqueueConsolidation(c.s,policy)!;assert.ok(dream);assert.equal(dream.reason,'dreaming_consolidation');assert.equal(c.repo.enqueueConsolidation(c.s,policy),null);c.clock.now+=60001;assert.ok(c.repo.admit(dream,'fixture'));const proposal=result(c.sources.map(s=>s.id),[],0);proposal.items[0]!.expectedRevision=1;proposal.items[0]!.disposition='resolved';c.repo.publish(dream,proposal,policy,c.sources);c.repo.finish(dream,'published');c.restart();c.clock.now+=86400000;assert.equal(c.repo.enqueueConsolidation(c.s,policy),null);assert.equal(c.repo.read(c.s).items[0]!.disposition,'resolved');
});
test('unavailable provider priority is inspectable without spending model calls',async t=>{const c=await setup(t),job=c.repo.enqueue(c.s,[source(1)],'project',policy)!;c.repo.defer(job,'providerPriorityUnverified');assert.equal(c.repo.jobs(c.s)[0]!.reason,'providerPriorityUnverified');assert.equal(c.repo.read(c.s).funnel.calls,0);assert.equal(c.repo.read(c.s).funnel.admitted,0);assert.equal(c.repo.read(c.s).funnel.skips,1);c.repo.defer(job,'providerPriorityUnverified');assert.equal(c.repo.read(c.s).funnel.skips,1);});
test('simulated false source is removed while independently supported or explicitly authored harmless preference survives',async t=>{
 const c=await setup(t),falseSource={...source(30),content:'SIMULATED model-error source: an invented gardening outcome.'},valid=[source(31),source(32)],all=[falseSource,...valid],jobs=all.map(s=>c.repo.enqueue(c.s,[s],'outcome',policy)!);c.clock.now+=60001;assert.ok(c.repo.admit(jobs[2]!,'fixture'));const proposal=result(valid.map(s=>s.id),jobs.slice(1).map(j=>j.id));proposal.items.push({...proposal.items[0]!,id:'false-derived-item',statement:'SIMULATED false conclusion',sourceRefs:[falseSource.id]});c.repo.publish(jobs[2]!,proposal,policy,all);c.repo.finish(jobs[2]!,'published');c.repo.seed(c.s,c.repo.read(c.s).revision,'attentionReading',.1,policy);
 c.repo.reconcile(c.s,valid,policy);const state=c.repo.read(c.s);assert.equal(state.imprints[0]!.value,.05,'separate valid episodes retain their contribution');assert.equal(state.imprints[2]!.value,.1,'explicitly authored seed remains distinct');assert.equal(state.items.find(i=>i.id==='false-derived-item')!.statement,'');assert.equal(state.items.find(i=>i.id==='garden-project')!.disposition,'open');assert.ok(c.repo.lineage(c.s).filter(l=>l.operation==='reflection').every(l=>l.summary===''));
 c.restart();c.repo.reconcile(c.s,[valid[1]!],policy);assert.equal(c.repo.read(c.s).imprints[0]!.value,0,'loss of a required independent source removes its learned contribution');assert.equal(c.repo.read(c.s).imprints[2]!.value,.1);c.repo.reconcile(c.s,[],policy);assert.equal(c.repo.read(c.s).imprints[0]!.value,0,'no double inverse');
});
test('source invalidation and later explicit reversal each undo only their remaining independent contributions',async t=>{
 const c=await setup(t),sources=[source(40),source(41),source(42),source(43)],jobs=sources.map(s=>c.repo.enqueue(c.s,[s],'outcome',policy)!);c.clock.now+=60001;const job=jobs[3]!;assert.ok(c.repo.admit(job,'fixture'));const proposal=result(sources.slice(0,2).map(s=>s.id),jobs.slice(0,2).map(j=>j.id));proposal.changes.push({dimension:'attentionReading',delta:.04,episodeRefs:jobs.slice(2).map(j=>j.id),confidence:.85,reason:'A separate independently supported activity'});c.repo.publish(job,proposal,policy,sources);c.repo.finish(job,'published');
 c.repo.reconcile(c.s,sources.slice(1),policy);const line=c.repo.lineage(c.s).find(l=>l.operation==='reflection')!;assert.equal(line.reversed,false);assert.equal(line.changes[0]!.reversed,true);assert.ok(!line.changes[1]!.reversed);assert.equal(c.repo.read(c.s).imprints[0]!.value,0);assert.equal(c.repo.read(c.s).imprints[2]!.value,.04);c.restart();c.repo.reverse(c.s,c.repo.read(c.s).revision,line.id);assert.equal(c.repo.read(c.s).imprints[0]!.value,0,'invalidated contribution is not reversed twice');assert.equal(c.repo.read(c.s).imprints[2]!.value,0);assert.ok(c.repo.read(c.s).items.every(i=>!i.sourceRefs.includes(sources[0]!.id)));c.repo.reconcile(c.s,[],policy);assert.ok(c.repo.read(c.s).imprints.every(i=>i.value===0));
});
test('partly invalidated workspace-only publication remains explicitly reversible',async t=>{
 const c=await setup(t),sources=[source(50),source(51)],jobs=sources.map(s=>c.repo.enqueue(c.s,[s],'project',policy)!);c.clock.now+=60001;const job=jobs[1]!;assert.ok(c.repo.admit(job,'fixture'));const proposal=result([sources[0]!.id],[],0);proposal.items.push({...proposal.items[0]!,id:'independent-reading',topic:'reading',sourceRefs:[sources[1]!.id]});c.repo.publish(job,proposal,policy,sources);c.repo.finish(job,'published');c.repo.reconcile(c.s,[sources[1]!],policy);const line=c.repo.lineage(c.s).find(l=>l.operation==='reflection')!;assert.equal(line.reversed,false,'remaining workspace update still has a usable inverse');assert.equal(c.repo.read(c.s).items.find(i=>i.id==='independent-reading')!.disposition,'open');c.repo.reverse(c.s,c.repo.read(c.s).revision,line.id);assert.deepEqual(c.repo.read(c.s).items,[]);
});

test('withdrawing processing consent leaves authored seed lineage distinct and reversible',async t=>{const c=await setup(t);c.repo.seed(c.s,c.repo.read(c.s).revision,'attentionReading',.1,policy);const line=c.repo.lineage(c.s).find(l=>l.operation==='seed')!;c.repo.reconcile(c.s,[],{...policy,allowed:false,revision:2});assert.equal(c.repo.read(c.s).imprints[2]!.seed,.1);assert.equal(c.repo.lineage(c.s).find(l=>l.id===line.id)!.reversed,false);c.repo.reverse(c.s,c.repo.read(c.s).revision,line.id);assert.equal(c.repo.read(c.s).imprints[2]!.value,0);});

// Scripted typed source evidence; no camera, selected-model or Human qualification.
import {visualEpisode} from './fixtures/visual-episode.ts';
import {visualExperienceEpisode} from '@lifestream/contracts/experience';
function visualSource(c:Awaited<ReturnType<typeof setup>>,n=0):Source{const {episode}=visualEpisode(c.s,{enabled:true,revision:1,retentionMs:86400000,retentionPolicyRef:'synthetic-retention'},c.clock.now+n);episode.state='retained';const content=JSON.stringify(episode);return {id:'visual-episode:'+episode.episodeId,revision:episode.revision,family:'visual:'+episode.independenceKeys[0],content,digest:createHash('sha256').update(content).digest('hex'),occurredAt:episode.occurredAt};}
test('typed visual reflection preserves original date/family, qualifies existing workspace and is erased on withdrawal',async t=>{
 const c=await setup(t),owner=source(81),first=c.repo.enqueue(c.s,[owner],'project',policy)!;c.clock.now+=60001;assert.ok(c.repo.admit(first,'fixture'));c.repo.publish(first,result([owner.id],[],0),policy,[owner]);c.repo.finish(first,'published');const visual=visualSource(c),job=c.repo.enqueue(c.s,[visual],'question',policy)!;assert.ok(visualExperienceEpisode(visual));assert.equal(c.repo.episodes(c.s).find(e=>e.id===job.id)!.occurredAt,visual.occurredAt);c.clock.now+=60001;assert.ok(c.repo.admit(job,'fixture'));const update=result([owner.id,visual.id],[],0);update.items[0]!.expectedRevision=1;const before=c.repo.read(c.s);assert.throws(()=>c.repo.publish(job,update,policy,[owner,visual]),/visual_item_uncertainty/);assert.deepEqual(c.repo.read(c.s),before);update.items[0]!.uncertainty='high';update.items[0]!.id='invented-visual-project';update.items[0]!.expectedRevision=0;assert.throws(()=>c.repo.publish(job,update,policy,[owner,visual]),/supported_workspace/);update.items[0]!.id='garden-project';update.items[0]!.expectedRevision=1;c.repo.publish(job,update,policy,[owner,visual]);c.repo.finish(job,'published');assert.equal(c.repo.read(c.s).items[0]!.uncertainty,'high');c.restart();c.repo.reconcile(c.s,[owner],policy);assert.equal(c.repo.read(c.s).items[0]!.disposition,'invalidated');assert.ok(c.repo.lineage(c.s).filter(l=>l.operation==='reflection'&&l.sourceRefs.includes(visual.id)).every(l=>l.summary===''));assert.ok(c.repo.lineage(c.s).some(l=>l.operation==='reflection'&&!l.sourceRefs.includes(visual.id)&&l.summary));assert.ok(c.repo.read(c.s).imprints.every(i=>i.value===0));
});
test('visual and mixed episodes cannot support imprints; invalid scope/digest/expiry cannot publish',async t=>{
 const c=await setup(t),visual=visualSource(c),owner=source(82),a=c.repo.enqueue(c.s,[visual,owner],'question',policy)!,other=source(83),b=c.repo.enqueue(c.s,[other],'project',policy)!;c.clock.now+=60001;assert.ok(c.repo.admit(b,'fixture'));const change=result([owner.id], [a.id,b.id]);change.items=[];assert.throws(()=>c.repo.publish(b,change,policy,[visual,owner,other]),/model_observation_not_preference_evidence/);assert.ok(c.repo.read(c.s).imprints.every(i=>i.value===0));assert.equal(c.repo.enqueue({...c.s,principalId:randomUUID()},[visual],'question',policy),null);
});
test('visual source binding rejects tampering and reprojection cannot manufacture independence',async t=>{
 const c=await setup(t),visual=visualSource(c),job=c.repo.enqueue(c.s,[visual],'question',policy)!;assert.equal(c.repo.enqueue(c.s,[visual],'question',policy),null);const revisedEpisode=JSON.parse(visual.content);revisedEpisode.revision++;const revisedContent=JSON.stringify(revisedEpisode),revised={...visual,revision:2,content:revisedContent,digest:createHash('sha256').update(revisedContent).digest('hex')};assert.equal(c.repo.enqueue(c.s,[revised],'question',policy),null);assert.throws(()=>c.repo.enqueue(c.s,[{...visual,digest:'0'.repeat(64)}],'question',policy),/visual_source_binding/);const episode=JSON.parse(visual.content);episode.scope.principalId=randomUUID();episode.sourceDigest=createHash('sha256').update(JSON.stringify({scope:episode.scope,observations:episode.observations})).digest('hex');const content=JSON.stringify(episode);assert.throws(()=>c.repo.enqueue(c.s,[{...visual,content,digest:createHash('sha256').update(content).digest('hex')}],'question',policy),/visual_source_binding/);c.clock.now+=60001;assert.ok(c.repo.admit(job,'fixture'));c.clock.now+=86400000;assert.throws(()=>c.repo.publish(job,{recordType:'reflectionResult',decision:'noChange',conclusion:'Cannot retain expired evidence.',items:[],changes:[]},policy,[visual]),/visual_source_binding/);c.repo.reconcile(c.s,[visual],policy);assert.equal(c.repo.episodes(c.s)[0]!.state,'invalidated');
});

import {fixtureEpisode} from '../../runtime/test/fixtures/game-memory.ts';
import {gameEpisodeFamilyKey} from '@lifestream/contracts/game-memory';
import {gameExperienceEpisode} from '@lifestream/contracts/experience';
function gameSource(c:Awaited<ReturnType<typeof setup>>){const e=fixtureEpisode(c.clock.now);Object.assign(e.scope,c.s);e.expiresAt=new Date(c.clock.now+86400000).toISOString();const content=JSON.stringify(e);return {episode:e,source:{id:'game-episode:'+e.episodeId,revision:e.revision,family:'game:'+gameEpisodeFamilyKey(e),digest:createHash('sha256').update(content).digest('hex'),content,occurredAt:e.occurredFrom}};}
function gameResult(ref:string):ReflectionResult{return {recordType:'reflectionResult',decision:'change',conclusion:'Recorded gate failure supports a bounded game question, not a feeling.',items:[{id:'game-gate',expectedRevision:0,kind:'question',topic:'games',statement:'The recorded gate attempt remained unsuccessful; its hidden reason is unknown.',nextStep:'Ask how the Human approached that visible gate, when conversation permits.',uncertainty:'high',sourceRefs:[ref],disposition:'open'}],changes:[]};}
test('typed game source enters independently enabled reflection without a fake Human turn and invalidates after restart/forget',async t=>{
 const c=await setup(t),g=gameSource(c);assert.ok(gameExperienceEpisode(g.source,c.clock.now));const job=c.repo.enqueue(c.s,[g.source],'outcome',policy)!;assert.ok(job);assert.equal(c.repo.episodes(c.s)[0]!.occurredAt,g.episode.occurredFrom);c.clock.now+=60001;assert.ok(c.repo.admit(job,'scripted-game-reflector'));c.repo.publish(job,gameResult(g.source.id),policy,[g.source]);c.repo.finish(job,'published');assert.equal(c.repo.read(c.s).items[0]!.topic,'games');assert.equal(c.repo.read(c.s).items[0]!.uncertainty,'high');assert.ok(c.repo.read(c.s).imprints.every(i=>i.value===0));c.restart();assert.equal(c.repo.read(c.s).items[0]!.sourceRefs[0],g.source.id);c.repo.reconcile(c.s,[],policy);assert.equal(c.repo.read(c.s).items[0]!.statement,'');assert.equal(c.repo.read(c.s).items[0]!.disposition,'invalidated');assert.ok(c.repo.lineage(c.s).filter(l=>l.operation==='reflection').every(l=>l.summary===''));
});
for(const change of ['lowUncertainty','physicalTopic'])test('game reflection cannot publish '+change,async t=>{const c=await setup(t),g=gameSource(c),job=c.repo.enqueue(c.s,[g.source],'outcome',policy)!;c.clock.now+=60001;assert.ok(c.repo.admit(job,'scripted'));const r=gameResult(g.source.id);if(change==='lowUncertainty')r.items[0]!.uncertainty='low';else r.items[0]!.topic='health';const before=c.repo.read(c.s);assert.throws(()=>c.repo.publish(job,r,policy,[g.source]),/game_item_scope_uncertainty/);assert.deepEqual(c.repo.read(c.s),before);});
test('game dialogue enjoyment or mixed game/Human episodes cannot support a preference imprint',async t=>{const c=await setup(t),a=gameSource(c),b=gameSource(c),owner=source(91);const x=c.repo.enqueue(c.s,[a.source,owner],'outcome',policy)!,y=c.repo.enqueue(c.s,[b.source],'outcome',policy)!;c.clock.now+=60001;assert.ok(c.repo.admit(y,'scripted'));const r=result([owner.id],[x.id,y.id]);r.items=[];assert.throws(()=>c.repo.publish(y,r,policy,[a.source,b.source,owner]),/model_observation_not_preference_evidence/);assert.ok(c.repo.read(c.s).imprints.every(i=>i.value===0));});
test('game family dedup survives timeline/run/summary changes and invalidation',async t=>{const c=await setup(t),g=gameSource(c);assert.ok(c.repo.enqueue(c.s,[g.source],'outcome',policy));const e=structuredClone(g.episode);e.episodeId=randomUUID();e.scope.timelineId=randomUUID();e.scope.runId=randomUUID();e.summary='Same original event after reload, summarized another way.';const content=JSON.stringify(e),revised={...g.source,id:'game-episode:'+e.episodeId,content,digest:createHash('sha256').update(content).digest('hex')};assert.equal(c.repo.enqueue(c.s,[revised],'outcome',policy),null);c.repo.reconcile(c.s,[],policy);assert.equal(c.repo.enqueue(c.s,[revised],'outcome',policy),null);});
for(const change of ['digest','namespace','foreignOwner','expiry','advice'])test('game reflection source binding refuses '+change,async t=>{const c=await setup(t),g=gameSource(c);if(change==='digest')g.source.digest='f'.repeat(64);if(change==='namespace')g.source.family='game:forged';if(change==='foreignOwner'){g.episode.scope.principalId=randomUUID();g.source.content=JSON.stringify(g.episode);g.source.digest=createHash('sha256').update(g.source.content).digest('hex');g.source.family='game:'+gameEpisodeFamilyKey(g.episode);}if(change==='expiry')c.clock.now+=86400000;if(change==='advice'){g.episode.adviceRefs=['unattributed:human-advice'];g.source.content=JSON.stringify(g.episode);g.source.digest=createHash('sha256').update(g.source.content).digest('hex');}assert.throws(()=>c.repo.enqueue(c.s,[g.source],'outcome',policy),/game_source_binding/);});
test('game permission/source existence alone cannot enable reflection processing',async t=>{const c=await setup(t),g=gameSource(c),s=c.repo.read(c.s);c.repo.configure(c.s,s.revision,{enabled:false,frozen:false,retention:'sourceBound',topicPolicies:defaultTopics},policy);assert.equal(c.repo.enqueue(c.s,[g.source],'outcome',policy),null);});
