import assert from 'node:assert/strict';
import test from 'node:test';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Database} from '../src/database.ts';
import {loadMigrations} from '../src/migrations/index.ts';
import {MemoryRepository} from '../src/memory.ts';
import {GameExperienceRepository,quarantineGameExperience,type GameEpisodeSources,type GameEpisodeOptions} from '../src/game-experience.ts';
import {fixtureEpisode,projection,fixtureGameEpisodeSources as sourceRecords} from '../../runtime/test/fixtures/game-memory.ts';
import {AutomaticMemory} from '../../../apps/server/src/runtime/automatic-memory.ts';
function setup(t:import('node:test').TestContext,path=':memory:'){
 let now=Date.now(),current=true,published=true,meaningful=true,quarantined=false;const db=new Database({path});db.migrate();t.after(()=>db.close());const e=fixtureEpisode(now),owner={principalId:e.scope.principalId,assistantId:e.scope.assistantId,relationshipId:e.scope.relationshipId},sources=sourceRecords(e),retention={retentionMs:86400000,retentionPolicyRef:e.retentionPolicyRef,maximumEpisodes:4,maximumBytes:8192};
 db.connection.prepare('INSERT INTO automatic_memory_policies VALUES(?,?,?,?,?,?,?)').run('test-only:owned-memory',owner.principalId,owner.assistantId,owner.relationshipId,1,1,new Date(now).toISOString());
 const options:GameEpisodeOptions={maximumFences:16,scopeCurrent:o=>JSON.stringify(o)===JSON.stringify(owner),quarantined:()=>quarantined,retentionFor:()=>retention,sourceRecordsFor:()=>sources,meaningfulGroundingCurrent:()=>meaningful,publicationCurrent:()=>published,retainedSourceCurrent:()=>current,now:()=>now};
 const repo=new GameExperienceRepository(db,options),memories=new MemoryRepository(db,repo.memorySources(4));return {db,e,owner,sources,retention,options,repo,memories,now:()=>now,advance:(ms:number)=>now+=ms,withdraw:()=>current=false,unpublish:()=>published=false,meaningless:()=>meaningful=false,quarantine:()=>quarantined=true};
}
test('qualified recorded action/result joins a selective durable source and existing canonical memory candidate',t=>{const f=setup(t);assert.equal(f.repo.admit(f.e),true);const stored=f.repo.get(f.owner,f.e.episodeId)!;assert.deepEqual(stored,f.e);const saved=f.memories.saveGameProjection(projection(stored,f.now()));assert.equal(f.memories.get(f.owner.assistantId,saved.id)!.content,f.e.summary);assert.deepEqual(f.memories.contextRecordIds(f.owner.assistantId,f.owner.principalId),[]);const raw=JSON.stringify(f.db.connection.prepare('SELECT payload_json FROM game_experience_episodes').get());assert.ok(!raw.includes(f.sources.observations[0]!.screenshots[0]!.mediaRef));assert.ok(!raw.includes(f.sources.actions[0]!.inputDigest));assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM automatic_memory_work').get()!.n,0);});
for(const mode of ['disabledMemory','missingRetention','quarantine','publication','meaningless','source']as const)test('separate admission denies '+mode,t=>{const f=setup(t);if(mode==='disabledMemory')f.db.exec('UPDATE automatic_memory_policies SET enabled=0');if(mode==='missingRetention')f.options.retentionFor=()=>null;if(mode==='quarantine')f.quarantine();if(mode==='publication')f.unpublish();if(mode==='meaningless')f.meaningless();if(mode==='source')f.withdraw();const repo=new GameExperienceRepository(f.db,f.options);if(['disabledMemory','missingRetention','quarantine'].includes(mode))assert.throws(()=>repo.admit(f.e),/unavailable/);else assert.equal(repo.admit(f.e),false);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_experience_episodes').get()!.n,0);});
for(const [label,change]of [
 ['unstarted receipt',(s:GameEpisodeSources)=>{s.actions[0]!.startedAt=null;s.actions[0]!.disposition='admitted';}],['foreign action',(s:GameEpisodeSources)=>{s.actions[0]!.scope.relationshipId=randomUUID();}],['foreign observation',(s:GameEpisodeSources)=>{s.observations[0]!.scope.timelineId=randomUUID();}],['wrong artifact',(s:GameEpisodeSources)=>{s.observations[0]!.pinsDigest='f'.repeat(64);}],['outside frame',(s:GameEpisodeSources)=>{s.observations[0]!.frameNumber++;}],['no result linkage',(s:GameEpisodeSources)=>{s.actions[0]!.resultingObservationIds=[];s.observations[0]!.previousActionId=null;}],['future result',(s:GameEpisodeSources)=>{s.observations[0]!.receivedAt=new Date(Date.now()+100000).toISOString();}],['unknown hidden field',(s:GameEpisodeSources)=>{(s.observations[0]as any).futurePlotFlag=true;}]
]as const)test('typed source join refuses '+label,t=>{const f=setup(t);change(f.sources);assert.equal(f.repo.admit(f.e),false);});
test('source refusal inside the transaction rolls back both source payload and opaque fences',t=>{const f=setup(t);const repo=new GameExperienceRepository(f.db,{...f.options,publicationCurrent:()=>!f.db.connection.prepare('SELECT 1 FROM game_experience_episodes').get()});assert.throws(()=>repo.admit(f.e),/changed during/);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_experience_episodes').get()!.n,0);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_experience_sources').get()!.n,0);});
test('source mutation in the final publication callback is fenced before commit',t=>{const f=setup(t);const repo=new GameExperienceRepository(f.db,{...f.options,publicationCurrent:()=>{if(f.db.connection.prepare('SELECT 1 FROM game_experience_episodes').get())f.sources.observations[0]!.facts[0]!.description='Changed underlying interpretation';return true;}});assert.throws(()=>repo.admit(f.e),/changed during/);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_experience_episodes').get()!.n,0);});
test('last source lookup cannot withdraw durable consent and still commit a retained episode',t=>{const f=setup(t);const repo=new GameExperienceRepository(f.db,{...f.options,sourceRecordsFor:()=>{if(f.db.connection.prepare('SELECT 1 FROM game_experience_episodes').get())f.db.exec('UPDATE automatic_memory_policies SET enabled=0');return f.sources;}});assert.throws(()=>repo.admit(f.e),/changed during/);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_experience_episodes').get()!.n,0);assert.equal(f.db.connection.prepare('SELECT enabled FROM automatic_memory_policies').get()!.enabled,1);});
for(const mode of ['forgetEpisode','forgetMemory','sourceCorrection','expiry','policyRevision','quarantine']as const)test('source/projection erasure joins '+mode,t=>{const f=setup(t);assert.equal(f.repo.admit(f.e),true);const m=f.memories.saveGameProjection(projection(f.e,f.now()));if(mode==='forgetEpisode')f.repo.forget(f.owner,f.e.episodeId,1);if(mode==='forgetMemory')f.memories.forget(f.owner.assistantId,m.id,f.owner.principalId);if(mode==='sourceCorrection'){f.withdraw();f.repo.get(f.owner,f.e.episodeId);}if(mode==='expiry'){f.advance(60000);f.repo.sweep();}if(mode==='policyRevision'){f.db.exec('UPDATE automatic_memory_policies SET revision=revision+1');f.repo.sweep();}if(mode==='quarantine')assert.equal(quarantineGameExperience(f.db),1);assert.equal(f.repo.get(f.owner,f.e.episodeId),null);assert.equal(f.db.connection.prepare('SELECT payload_json FROM game_experience_episodes').get()!.payload_json,null);assert.equal(f.db.connection.prepare('SELECT content FROM memories WHERE id=?').get(m.id)!.content,'');assert.ok(!JSON.stringify(f.memories.history(f.owner.assistantId,m.id)).includes(f.e.summary));assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_experience_sources').get()!.n,2);});
test('existing automatic-memory withdrawal atomically retires retained game sources and derivatives',async t=>{const f=setup(t),worker=new AutomaticMemory({database:f.db,memories:f.memories,provider:()=>({revision:'unused',provider:{async *generate(){throw Error('no inference');}}}),idle:()=>false,changed:()=>{}});t.after(()=>worker.close());const actualKey=worker.policy(f.owner as any);assert.equal(actualKey.enabled,false);f.db.exec('DELETE FROM automatic_memory_policies');worker.configure(f.owner as any,true,0);assert.equal(f.repo.admit(f.e),true);const m=f.memories.saveGameProjection(projection(f.e,f.now()));worker.configure(f.owner as any,false,1);assert.equal(f.repo.get(f.owner,f.e.episodeId),null);assert.equal(f.db.connection.prepare('SELECT content FROM memories WHERE id=?').get(m.id)!.content,'');assert.equal(f.db.connection.prepare('SELECT payload_json FROM game_experience_episodes').get()!.payload_json,null);await worker.close();});
test('deduplication and scope fences persist through SQLite reopen and cannot be reset by reload or forgetting',t=>{const dir=mkdtempSync(join(tmpdir(),'game-source-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,'sources.sqlite'),f=setup(t,path);assert.equal(f.repo.admit(f.e),true);const replica=new Database({path});replica.migrate();t.after(()=>replica.close());const repo=new GameExperienceRepository(replica,f.options);assert.deepEqual(repo.get(f.owner,f.e.episodeId),f.e);assert.equal(repo.admit(f.e),false);assert.equal(repo.get({...f.owner,principalId:randomUUID()},f.e.episodeId),null);repo.forget(f.owner,f.e.episodeId,1);assert.equal(repo.admit(f.e),false);assert.equal(f.repo.get(f.owner,f.e.episodeId),null);assert.ok(!JSON.stringify(replica.connection.prepare('SELECT * FROM game_experience_sources').all()).includes(f.e.summary));});
test('durable UTC floor and finite source-fence capacity survive erasure',t=>{const f=setup(t),repo=new GameExperienceRepository(f.db,{...f.options,maximumFences:1});assert.equal(repo.admit(f.e),true);repo.forget(f.owner,f.e.episodeId,1);const e=structuredClone(f.e);e.episodeId=randomUUID();e.independenceKey=randomUUID();e.sourceObservationIds=[randomUUID()];e.sourceActionIds=[randomUUID()];e.sourceAdmissionIds=[randomUUID()];const next=new GameExperienceRepository(f.db,{...f.options,maximumFences:1,sourceRecordsFor:()=>sourceRecords(e)});assert.throws(()=>next.admit(e),/capacity/);f.advance(-1);assert.throws(()=>next.get(f.owner,e.episodeId),/clock/);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_experience_episodes').get()!.n,1);});
for(const mode of ['changedSummary','corruptJSON']as const)test('source integrity failure erases unsupported source and derivative '+mode,t=>{const f=setup(t);f.repo.admit(f.e);const m=f.memories.saveGameProjection(projection(f.e,f.now()));const changed=structuredClone(f.e);changed.summary='An unsupported new claim without a source revision';f.db.connection.prepare('UPDATE game_experience_episodes SET payload_json=?').run(mode==='changedSummary'?JSON.stringify(changed):'{');if(mode==='changedSummary')assert.equal(f.repo.get(f.owner,f.e.episodeId),null);else f.repo.sweep();assert.equal(f.db.connection.prepare('SELECT payload_json FROM game_experience_episodes').get()!.payload_json,null);assert.equal(f.db.connection.prepare('SELECT content FROM memories WHERE id=?').get(m.id)!.content,'');});
for(const mode of ['rawArtifact','unboundAdvice']as const)test('unimplemented evidence policy is denied '+mode,t=>{const f=setup(t);if(mode==='rawArtifact')f.e.rawEvidenceAvailability='explicitlyRetainedArtifact';else f.e.adviceRefs=['unbound:human-advice'];assert.equal(f.repo.admit(f.e),false);});
test('migration is additive and leaves earlier schema, clock and memory rows unchanged',t=>{const dir=mkdtempSync(join(tmpdir(),'game-source-upgrade-')),path=join(dir,'state.sqlite');t.after(()=>rmSync(dir,{recursive:true,force:true}));let db=new Database({path,migrations:loadMigrations().filter(m=>m.id<=63)});const before=db.migrate();db.connection.prepare("INSERT INTO memories VALUES('old','assistant','owner data','{}','{}','old')").run();db.connection.prepare('UPDATE activity_metadata_clock SET observed_at=4321').run();db.close();db=new Database({path});t.after(()=>db.close());const after=db.migrate();assert.deepEqual(after.slice(0,before.length),before);assert.deepEqual(after.slice(before.length).map(m=>m.id),[64,65,66,67]);assert.equal(db.connection.prepare("SELECT content FROM memories WHERE id='old'").get()!.content,'owner data');assert.equal(db.connection.prepare('SELECT observed_at FROM activity_metadata_clock').get()!.observed_at,4321);assert.equal(db.connection.prepare('SELECT count(*) AS n FROM game_experience_episodes').get()!.n,0);});
