import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {Database} from '../src/database.ts';
import {loadMigrations} from '../src/migrations/index.ts';
import {GameHelpRepository,type GameHelpOptions} from '../src/game-help.ts';
import {GameExperienceRepository,quarantineGameExperience,type GameEpisodeOptions} from '../src/game-experience.ts';
import {fixtureEpisode,fixtureGameHelpItem,projection,fixtureGameEpisodeSources} from '../../runtime/test/fixtures/game-memory.ts';
import {selectGameHelpSource} from '../../runtime/src/activity/help.ts';
import type {GameHelpItem,GameExperienceEpisode} from '@lifestream/contracts/game-activity';
import {MemoryRepository} from '../src/memory.ts';

function setup(t:import('node:test').TestContext,path=':memory:'){
 let now=Date.now(),revision=1,paused=true,configured=true,grounded=true,attachment=true,quarantined=false,sourceCurrent=true,closed=false;const db=new Database({path});db.migrate();const close=()=>{if(!closed){db.close();closed=true;}};t.after(close);const e=fixtureEpisode(now),owner={principalId:e.scope.principalId,assistantId:e.scope.assistantId,relationshipId:e.scope.relationshipId},sources=new Map([[e.episodeId,fixtureGameEpisodeSources(e)]]);
 db.connection.prepare('INSERT INTO automatic_memory_policies VALUES(?,?,?,?,?,?,?)').run('test-only:owned-memory',owner.principalId,owner.assistantId,owner.relationshipId,1,1,new Date(now).toISOString());
 const episodeOptions:GameEpisodeOptions={maximumFences:16,scopeCurrent:o=>JSON.stringify(o)===JSON.stringify(owner),quarantined:()=>quarantined,retentionFor:()=>({retentionMs:86400000,retentionPolicyRef:e.retentionPolicyRef,maximumEpisodes:8,maximumBytes:8192}),sourceRecordsFor:x=>sources.get(x.episodeId)??null,meaningfulGroundingCurrent:()=>true,publicationCurrent:()=>true,retainedSourceCurrent:()=>sourceCurrent,now:()=>now};
 const episodes=new GameExperienceRepository(db,episodeOptions);assert.equal(episodes.admit(e),true);
 const makeItem=(x:GameExperienceEpisode):GameHelpItem=>fixtureGameHelpItem(x,now);
 const item=makeItem(e),options:GameHelpOptions={maximumFences:8,scopeCurrent:episodeOptions.scopeCurrent,quarantined:()=>quarantined,retentionFor:()=>({revision:1,policyRef:'test-only:independent-pending-help-retention',retentionMs:30000,maximumItems:4,maximumBytes:8192}),episodeFor:(o,id)=>episodes.get(o,id),boundaryRevision:()=>String(revision),situationKeyFor:()=> 'd'.repeat(64),pendingCurrent:(i,x)=>{
  const o=sources.get(x.episodeId)?.observations[0];if(!o)return false;
  return selectGameHelpSource({item:structuredClone(i),episode:structuredClone(x),observation:structuredClone(o),maximumBytes:8192,maximumObservationAgeMs:6000,nowMs:now,freshUntilMs:Math.min(now+5000,Date.parse(o.capturedAt)+6000,Date.parse(x.expiresAt))},{boundaryRevision:()=>String(revision),episodeCurrent:()=>sourceCurrent,observationCurrent:()=>sourceCurrent,pauseCurrent:()=>paused,configuredRecipientCurrent:()=>configured,questionGroundedCurrent:()=>grounded,attachmentCurrent:()=>attachment,now:()=>now}).state==='prepared';},now:()=>now};
 const repo=new GameHelpRepository(db,options),queue=()=>({item,episodeId:e.episodeId,expiresAt:now+30000});
 return {db,e,item,owner,episodes,episodeOptions,repo,options,makeItem,queue,close,seed:(x:GameExperienceEpisode)=>sources.set(x.episodeId,fixtureGameEpisodeSources(x)),now:()=>now,advance:(ms:number)=>now+=ms,change:()=>revision++,pauseLoss:()=>paused=false,configurationLoss:()=>configured=false,groundingLoss:()=>grounded=false,attachmentLoss:()=>attachment=false,quarantine:()=>quarantined=true,withdraw:()=>sourceCurrent=false,add:(x:GameExperienceEpisode)=>{sources.set(x.episodeId,fixtureGameEpisodeSources(x));return episodes.admit(x);}};
}

test('actual retained episode and inert qualification create one finite pending item without contact or resume authority',t=>{
 const f=setup(t);assert.equal(f.repo.queue(f.queue()),true);const v=f.repo.get(f.owner,f.item.helpId)!;assert.equal(v.revision,1);assert.equal(v.item.attemptsSummary,f.e.summary);assert.equal(v.item.status,'queued');assert.equal(v.item.sentAt,null);assert.equal(v.sendAuthority,false);assert.equal(v.resumeAuthority,false);assert.ok(Object.isFrozen(v.item.scope));assert.equal(f.repo.queue(f.queue()),false);
 const changed=f.queue();changed.item=structuredClone(f.item);changed.item.helpId=randomUUID();changed.item.question='A differently worded question';assert.equal(f.repo.queue(changed),false);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_start_claims').get()!.n,0);
});

for(const cause of ['pause','recipient','grounding','quarantine','source']as const)test('pending ledger requires independent '+cause,t=>{const f=setup(t);if(cause==='pause')f.pauseLoss();if(cause==='recipient')f.configurationLoss();if(cause==='grounding')f.groundingLoss();if(cause==='quarantine')f.quarantine();if(cause==='source')f.withdraw();if(cause==='quarantine')assert.throws(()=>f.repo.queue(f.queue()),/unavailable/);else assert.equal(f.repo.queue(f.queue()),false);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_help_items').get()!.n,0);});

for(const [label,change]of [
 ['unretained source',(v:any)=>v.episodeId=randomUUID()],['foreign timeline',(v:any)=>v.item.scope.timelineId=randomUUID()],['invented attempt',(v:any)=>v.item.attemptsSummary='A fabricated victory'],['unstarted action',(v:any)=>v.item.attemptedActionIds=[randomUUID()]],['claimed send',(v:any)=>v.item.messageSentEvidenceRef='forged:send'],['already replied',(v:any)=>v.item.status='replied'],['retention excess',(v:any)=>v.expiresAt+=1],['hidden extra field',(v:any)=>v.item.hiddenPlot=true],['missing item',(v:any)=>v.item=null]
]as const)test('pending ledger rejects '+label,t=>{const f=setup(t),v=f.queue();change(v);assert.equal(f.repo.queue(v),false);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_help_items').get()!.n,0);});

for(const cause of ['memoryPolicy','boundary','forgetDuringRead','expiryDuringRead']as const)test('late '+cause+' cannot commit or reveal pending help',t=>{
 const f=setup(t);let late=false;const repo=new GameHelpRepository(f.db,{...f.options,pendingCurrent:(i,e)=>{const qualified=f.options.pendingCurrent(i,e);if(late){if(cause==='memoryPolicy')f.db.exec('UPDATE automatic_memory_policies SET enabled=0,revision=revision+1');if(cause==='boundary')f.change();if(cause==='forgetDuringRead')repo.forget(f.owner,f.item.helpId,1);if(cause==='expiryDuringRead')f.advance(30000);}return qualified;}});
 if(cause==='forgetDuringRead'||cause==='expiryDuringRead'){assert.equal(repo.queue(f.queue()),true);late=true;assert.equal(repo.get(f.owner,f.item.helpId),null);}else {const other=new GameHelpRepository(f.db,{...f.options,pendingCurrent:(i,e)=>{const qualified=f.options.pendingCurrent(i,e);if(f.db.connection.prepare('SELECT 1 FROM game_help_items').get()){if(cause==='memoryPolicy')f.db.exec('UPDATE automatic_memory_policies SET enabled=0,revision=revision+1');else f.change();}return qualified;}});assert.throws(()=>other.queue(f.queue()),/unavailable/);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_help_items').get()!.n,0);assert.equal(f.db.connection.prepare('SELECT enabled FROM automatic_memory_policies').get()!.enabled,1);}
});

for(const cause of ['forget','sourceForget','quarantine','expiry','corruption']as const)test('pending erasure keeps opaque dedup fence for '+cause,t=>{
 const f=setup(t);assert.equal(f.repo.queue(f.queue()),true);if(cause==='forget'){f.repo.forget(f.owner,f.item.helpId,1);f.repo.forget(f.owner,f.item.helpId,1);}if(cause==='sourceForget')f.episodes.forget(f.owner,f.e.episodeId,1);if(cause==='quarantine')quarantineGameExperience(f.db);if(cause==='expiry')f.advance(30000);if(cause==='corruption')f.db.exec("UPDATE game_help_items SET payload_json='{}'");assert.equal(f.repo.get(f.owner,f.item.helpId),null);const row=f.db.connection.prepare('SELECT * FROM game_help_items').get()!;assert.equal(row.payload_json,null);assert.equal(row.payload_digest,null);assert.doesNotMatch(JSON.stringify(row),/How would you|recorded gate|attemptsSummary/);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_help_items').get()!.n,1);
});

test('caller callback mutation cannot replace captured qualification and owner scope stays isolated',t=>{const f=setup(t);assert.equal(f.repo.queue(f.queue()),true);assert.equal(f.repo.get({...f.owner,principalId:randomUUID()},f.item.helpId),null);assert.throws(()=>f.repo.forget({...f.owner,principalId:randomUUID()},f.item.helpId,1),/unavailable/);f.pauseLoss();f.options.pendingCurrent=()=>true;assert.equal(f.repo.get(f.owner,f.item.helpId),null);});

test('SQLite reopen preserves pending metadata and erased fences across reload and revised policy',t=>{
 const root=mkdtempSync(join(tmpdir(),'game-help-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const path=join(root,'state.sqlite'),f=setup(t,path);assert.equal(f.repo.queue(f.queue()),true);f.close();const db=new Database({path});db.migrate();t.after(()=>db.close());const episodes=new GameExperienceRepository(db,f.episodeOptions),repo=new GameHelpRepository(db,{...f.options,episodeFor:(o,id)=>episodes.get(o,id)});assert.equal(repo.get(f.owner,f.item.helpId)!.revision,1);repo.forget(f.owner,f.item.helpId,1);
 const e=structuredClone(f.e);e.episodeId=randomUUID();e.independenceKey=randomUUID();e.scope.runId=randomUUID();e.scope.timelineId=randomUUID();e.sourceActionIds=[randomUUID()];e.sourceObservationIds=[randomUUID()];e.sourceAdmissionIds=[randomUUID()];f.seed(e);assert.equal(episodes.admit(e),true);const item=f.makeItem(e),revised=new GameHelpRepository(db,{...f.options,episodeFor:(o,id)=>episodes.get(o,id),retentionFor:(o,id)=>({...f.options.retentionFor(o,id)!,revision:2})});assert.equal(revised.queue({item,episodeId:e.episodeId,expiresAt:f.now()+30000}),false,'same observed situation cannot become another help item after reload, policy revision or erasure');
 f.advance(-1);assert.throws(()=>repo.get(f.owner,item.helpId),/clock/);assert.equal(db.connection.prepare('SELECT count(*) AS n FROM game_help_items').get()!.n,1);
});

test('existing source-aware memory forgetting atomically erases pending help payload',t=>{const f=setup(t);assert.equal(f.repo.queue(f.queue()),true);const memories=new MemoryRepository(f.db,f.episodes.memorySources(4)),m=memories.saveGameProjection(projection(f.e,f.now()));memories.forget(f.owner.assistantId,m.id,f.owner.principalId);assert.equal(f.repo.get(f.owner,f.item.helpId),null);assert.equal(f.db.connection.prepare('SELECT payload_json FROM game_help_items').get()!.payload_json,null);assert.equal(f.db.connection.prepare('SELECT payload_json FROM game_experience_episodes').get()!.payload_json,null);});

test('existing automatic-memory disable erases game source and pending help together',async t=>{const f=setup(t),{AutomaticMemory}=await import('../../../apps/server/src/runtime/automatic-memory.ts');const worker=new AutomaticMemory({database:f.db,memories:new MemoryRepository(f.db),provider:()=>({revision:'unused',provider:{async*generate(){throw Error('No inference');}}}),idle:()=>false,changed:()=>{}});t.after(()=>worker.close());f.db.exec('DELETE FROM automatic_memory_policies');worker.configure(f.owner as any,true,0);assert.equal(f.repo.queue(f.queue()),true);worker.configure(f.owner as any,false,1);assert.equal(f.db.connection.prepare('SELECT state FROM game_help_items').get()!.state,'invalidated');assert.equal(f.db.connection.prepare('SELECT payload_json FROM game_help_items').get()!.payload_json,null);assert.equal(f.repo.get(f.owner,f.item.helpId),null);await worker.close();});

test('finite fence capacity is not refunded by erasure',t=>{const f=setup(t),repo=new GameHelpRepository(f.db,{...f.options,maximumFences:1});assert.equal(repo.queue(f.queue()),true);repo.forget(f.owner,f.item.helpId,1);const e=structuredClone(f.e);e.episodeId=randomUUID();e.independenceKey=randomUUID();e.sourceActionIds=[randomUUID()];e.sourceObservationIds=[randomUUID()];e.sourceAdmissionIds=[randomUUID()];assert.equal(f.add(e),true);const item=f.makeItem(e),other=new GameHelpRepository(f.db,{...f.options,maximumFences:1,situationKeyFor:()=> 'e'.repeat(64)});assert.throws(()=>other.queue({item,episodeId:e.episodeId,expiresAt:f.now()+30000}),/capacity/);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_help_items').get()!.n,1);});

test('migration65 adds only help metadata and preserves applied history, source privacy and budget clocks',t=>{
 const root=mkdtempSync(join(tmpdir(),'game-help-upgrade-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const path=join(root,'state.sqlite');let db=new Database({path,migrations:loadMigrations().filter(m=>m.id<=64)});const old=db.migrate();db.exec('UPDATE game_experience_clock SET observed_at=12345');db.exec('UPDATE activity_metadata_clock SET observed_at=54321');db.close();db=new Database({path});t.after(()=>db.close());const updated=db.migrate();assert.deepEqual(updated.slice(0,old.length),old);assert.deepEqual(updated.slice(old.length).map(m=>m.id),[65,66]);assert.equal(db.connection.prepare('SELECT observed_at FROM game_experience_clock').get()!.observed_at,12345);assert.equal(db.connection.prepare('SELECT observed_at FROM activity_metadata_clock').get()!.observed_at,54321);assert.equal(db.connection.prepare('SELECT count(*) AS n FROM game_help_items').get()!.n,0);
});
