import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Database} from '../src/database.ts';
import {loadMigrations} from '../src/migrations/index.ts';
import {MemoryRepository} from '../src/memory.ts';
import {GameExperienceRepository,quarantineGameExperience,type GameEpisodeSources} from '../src/game-experience.ts';
import {GameHelpRepository} from '../src/game-help.ts';
import type {GameEpisodeAdviceSource} from '../src/game-advice-custody.ts';
import {fixtureEpisode,fixtureGameEpisodeSources,fixtureGameHelpItem,projection} from '../../runtime/test/fixtures/game-memory.ts';

function fixture(t:import('node:test').TestContext){
 const dir=mkdtempSync(join(tmpdir(),'game-advice-custody-')),path=join(dir,'test.sqlite');let db=new Database({path});db.migrate();let now=Date.now(),auth=true,scope=true;const start=now,e=fixtureEpisode(now),owner={principalId:e.scope.principalId,assistantId:e.scope.assistantId,relationshipId:e.scope.relationshipId};
 const sourceRecords=new Map<string,GameEpisodeSources>([[e.episodeId,fixtureGameEpisodeSources(e)]]);let hook=()=>{};
 const options={maximumFences:16,scopeCurrent:()=>scope,quarantined:()=>false,retentionFor:()=>({retentionMs:86400000,retentionPolicyRef:e.retentionPolicyRef,maximumEpisodes:8,maximumBytes:8192}),sourceRecordsFor:(episode:typeof e)=>sourceRecords.get(episode.episodeId)??null,meaningfulGroundingCurrent:()=>true,publicationCurrent:()=>true,retainedSourceCurrent:()=>true,adviceSourceCurrent:(_episode:typeof e,s:GameEpisodeAdviceSource)=>{hook();return auth&&s.authenticatedReplyEvidenceRef==='scripted:authenticated-reply';},now:()=>now};
 let repository=new GameExperienceRepository(db,options),memories=new MemoryRepository(db,repository.memorySources(8));
 db.connection.prepare('INSERT INTO automatic_memory_policies VALUES(?,?,?,?,?,?,?)').run('synthetic:explicit-memory',owner.principalId,owner.assistantId,owner.relationshipId,1,1,new Date(now).toISOString());assert.equal(repository.admit(e),true);
 const helpOptions={maximumFences:16,scopeCurrent:()=>scope,quarantined:()=>false,retentionFor:()=>({revision:1,policyRef:'synthetic:separate-help-retention',retentionMs:60000,maximumItems:8,maximumBytes:8192}),episodeFor:(_owner:typeof owner,id:string)=>repository.get(owner,id),boundaryRevision:()=> 'synthetic:help-epoch:1',pendingCurrent:()=>true,situationKeyFor:()=> 'a'.repeat(64),now:()=>now};let help=new GameHelpRepository(db,helpOptions);const item=fixtureGameHelpItem(e,now);assert.equal(help.queue({item,episodeId:e.episodeId,expiresAt:now+60000}),true);
 const sourceTurnRef=randomUUID(),sourceSessionRef=randomUUID(),human=memories.save({id:randomUUID(),assistantId:owner.assistantId,content:'User stated: PRIVATE_EXACT_HUMAN_ADVICE',provenance:{actor:owner.principalId,relationshipId:owner.relationshipId,sourceTurnRef,sourceFamily:`turn:${sourceTurnRef}`,epistemicStatus:'userStatement',transformation:'exact-attributed-quote-v1'},lifecycle:{status:'candidate',revision:1},createdAt:new Date(now).toISOString()});assert.ok(memories.transition(owner.assistantId,human.id,'active',owner.principalId,undefined,1));
 const advice:GameEpisodeAdviceSource={adviceRef:'game-advice:'+randomUUID(),helpId:item.helpId,helpRevision:1,memoryId:human.id,memoryRevision:2,sourceTurnRef,sourceSessionRef,receivedAt:new Date(now).toISOString(),questionDeliveryEvidenceRef:'scripted:question-delivered',authenticatedReplyEvidenceRef:'scripted:authenticated-reply'};
 now+=1000;const derived=fixtureEpisode(now);derived.scope=structuredClone(e.scope);derived.adviceRefs=[advice.adviceRef];derived.summary='PRIVATE_ADVICE_BEARING_EPISODE';derived.expiresAt=new Date(start+50000).toISOString();sourceRecords.set(derived.episodeId,{...fixtureGameEpisodeSources(derived),advice:[advice]});
 t.after(()=>{db.close();rmSync(dir,{recursive:true,force:true});});
 return {e,derived,owner,human,item,advice,options,helpOptions,sourceRecords,get db(){return db;},get repository(){return repository;},get memories(){return memories;},get help(){return help;},now:()=>now,advance:(ms:number)=>now+=ms,unauthenticate:()=>auth=false,deny:()=>scope=false,hook:(f:()=>void)=>hook=f,admit:()=>repository.admit(derived),project:()=>{const m=memories.saveGameProjection(projection(derived,now));assert.ok(memories.activateGameCandidate(owner.assistantId,m.id,owner.principalId,1));return m;},restart:()=>{db.close();db=new Database({path});db.migrate();repository=new GameExperienceRepository(db,options);memories=new MemoryRepository(db,repository.memorySources(8));help=new GameHelpRepository(db,helpOptions);}};
}

test('separate actual Human/help custody permits a source-bound game projection and survives SQLite reopen without control authority',t=>{
 const f=fixture(t);assert.equal(f.admit(),true);const m=f.project();assert.equal(f.memories.get(f.owner.assistantId,m.id)!.lifecycle.factuality,'unverified');assert.equal(f.memories.get(f.owner.assistantId,m.id)!.lifecycle.lastReinforcedAt,null);const raw=f.db.connection.prepare('SELECT source_json FROM game_episode_advice_sources').get()!.source_json as string;assert.doesNotMatch(raw,/PRIVATE_|recipient|quotedAdvice|buttons|save/);f.restart();assert.deepEqual(f.repository.get(f.owner,f.derived.episodeId),f.derived);assert.equal(f.memories.get(f.owner.assistantId,m.id)!.content,f.derived.summary);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_start_claims').get()!.n,0);
});

for(const mode of ['noAuthenticator','wrongAuthenticator','missingSource','foreignHuman','gameHuman','visualHuman','inactiveHuman','missingActivation','wrongTurn','wrongMemoryRevision','wrongHelpRevision','wrongScope','unknownField','wrongPins','changedOriginalPolicy','pastHelpRetention']as const)test('advice episode refuses '+mode,t=>{
 const f=fixture(t),s=f.sourceRecords.get(f.derived.episodeId)!;
 if(mode==='noAuthenticator')f.options.adviceSourceCurrent=undefined as any;if(mode==='wrongAuthenticator')f.unauthenticate();if(mode==='missingSource')delete s.advice;
 if(['foreignHuman','gameHuman','visualHuman','inactiveHuman'].includes(mode)){const m=f.memories.get(f.owner.assistantId,f.human.id)!;if(mode==='foreignHuman')m.provenance.actor=randomUUID();if(mode==='gameHuman')m.provenance.gameEpisodeId=randomUUID();if(mode==='visualHuman')m.provenance.visualEpisodeId=randomUUID();if(mode==='inactiveHuman')m.lifecycle.status='candidate';f.db.connection.prepare('UPDATE memories SET provenance_json=?,lifecycle_json=? WHERE id=?').run(JSON.stringify(m.provenance),JSON.stringify(m.lifecycle),m.id);}
 if(mode==='missingActivation')f.db.connection.prepare("DELETE FROM memory_lifecycle_events WHERE memory_id=? AND event_type='lifecycleChanged'").run(f.human.id);
 if(mode==='wrongTurn')s.advice![0]={...f.advice,sourceTurnRef:randomUUID()};if(mode==='wrongMemoryRevision')s.advice![0]={...f.advice,memoryRevision:1};if(mode==='wrongHelpRevision')s.advice![0]={...f.advice,helpRevision:2};if(mode==='wrongScope'){f.derived.scope.timelineId=randomUUID();for(const record of [...s.actions,...s.observations])record.scope=structuredClone(f.derived.scope);}if(mode==='wrongPins'){f.derived.pinsDigest='f'.repeat(64);for(const observation of s.observations)observation.pinsDigest=f.derived.pinsDigest;}if(mode==='changedOriginalPolicy')f.db.exec("UPDATE game_experience_episodes SET policy_digest='changed'");if(mode==='unknownField')(s.advice![0]as any).playAuthority=true;if(mode==='pastHelpRetention')f.derived.expiresAt=new Date(f.now()+60000).toISOString();const repository=new GameExperienceRepository(f.db,f.options);assert.equal(repository.admit(f.derived),false);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_episode_advice_sources').get()!.n,0);
});

for(const mode of ['forgetHuman','correctHuman','invalidateHuman','forgetHelp','forgetOriginalEpisode','restore']as const)test('atomic '+mode+' removes derived source/projection/custody before reuse and keeps fences after reopen',t=>{
 const f=fixture(t);assert.equal(f.admit(),true);const m=f.project();
 if(mode==='forgetHuman')f.memories.forget(f.owner.assistantId,f.human.id,f.owner.principalId);
 if(mode==='correctHuman'){const proposal=f.memories.proposeCorrection(f.owner.assistantId,f.human.id,'Corrected Human input',f.owner.principalId)!;f.memories.applyCorrection(f.owner.assistantId,f.human.id,proposal.revision,2,f.owner.principalId);}
 if(mode==='invalidateHuman')f.memories.transition(f.owner.assistantId,f.human.id,'invalidated',f.owner.principalId,undefined,2);if(mode==='forgetHelp')f.help.forget(f.owner,f.item.helpId,1);if(mode==='forgetOriginalEpisode')f.repository.forget(f.owner,f.e.episodeId,1);if(mode==='restore')quarantineGameExperience(f.db);
 assert.equal(f.repository.get(f.owner,f.derived.episodeId),null);assert.equal(f.db.connection.prepare('SELECT content FROM memories WHERE id=?').get(m.id)!.content,'');assert.equal(f.db.connection.prepare('SELECT source_json FROM game_episode_advice_sources').get()!.source_json,null);assert.equal(f.db.connection.prepare('SELECT payload_json FROM game_experience_episodes WHERE episode_id=?').get(f.derived.episodeId)!.payload_json,null);f.restart();assert.equal(f.repository.get(f.owner,f.derived.episodeId),null);assert.equal(f.admit(),false);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_episode_advice_sources').get()!.n,1);
});

test('late authenticated-source withdrawal inside admission rolls back episode/projection and reference rows',t=>{
 const f=fixture(t);f.hook(()=>{if(f.db.connection.prepare('SELECT 1 FROM game_episode_advice_sources').get())f.unauthenticate();});assert.throws(()=>f.admit(),/changed during admission/);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_episode_advice_sources').get()!.n,0);assert.equal(f.db.connection.prepare('SELECT 1 FROM game_experience_episodes WHERE episode_id=?').get(f.derived.episodeId),undefined);
});

test('Human forget from a late read predicate cannot return a stale source or leave private projection prose',t=>{
 const f=fixture(t);assert.equal(f.admit(),true);const m=f.project();f.hook(()=>{f.hook(()=>{});f.memories.forget(f.owner.assistantId,f.human.id,f.owner.principalId);});assert.equal(f.repository.get(f.owner,f.derived.episodeId),null);assert.equal(f.db.connection.prepare('SELECT content FROM memories WHERE id=?').get(m.id)!.content,'');
});

test('tampered custody/source references, source policy withdrawal and expiry invalidate before memory reuse',async t=>{
 for(const mode of ['tamper','policy','expiry','auth'])await t.test(mode,t=>{const f=fixture(t);assert.equal(f.admit(),true);const m=f.project();if(mode==='tamper')f.db.exec("UPDATE game_episode_advice_sources SET memory_digest='tampered'");if(mode==='policy')f.db.exec('UPDATE automatic_memory_policies SET enabled=0');if(mode==='expiry')f.advance(60000);if(mode==='auth')f.unauthenticate();assert.equal(f.memories.get(f.owner.assistantId,m.id),undefined);assert.equal(f.repository.get(f.owner,f.derived.episodeId),null);});
});


test('erasing one Human source cascades through a derived help item without erasing an independent second Human input',t=>{
 const f=fixture(t);assert.equal(f.admit(),true);f.project();const secondaryHelp=new GameHelpRepository(f.db,{...f.helpOptions,situationKeyFor:()=> 'b'.repeat(64)}),item=fixtureGameHelpItem(f.derived,f.now()),expiresAt=Date.parse(f.derived.expiresAt);assert.equal(secondaryHelp.queue({item,episodeId:f.derived.episodeId,expiresAt}),true);
 const turn=randomUUID(),second=f.memories.save({id:randomUUID(),assistantId:f.owner.assistantId,content:'User stated: PRIVATE_SECOND_ADVICE',provenance:{actor:f.owner.principalId,relationshipId:f.owner.relationshipId,sourceTurnRef:turn,sourceFamily:`turn:${turn}`,epistemicStatus:'userStatement',transformation:'exact-attributed-quote-v1'},lifecycle:{status:'candidate',revision:1},createdAt:new Date(f.now()).toISOString()});assert.ok(f.memories.transition(f.owner.assistantId,second.id,'active',f.owner.principalId,undefined,1));
 const source={...f.advice,adviceRef:'game-advice:'+randomUUID(),helpId:item.helpId,memoryId:second.id,sourceTurnRef:turn,sourceSessionRef:randomUUID(),receivedAt:new Date(f.now()).toISOString()};f.advance(1000);const episode=fixtureEpisode(f.now());episode.scope=structuredClone(f.e.scope);episode.adviceRefs=[source.adviceRef];episode.expiresAt=new Date(expiresAt).toISOString();episode.summary='PRIVATE_SECOND_DERIVED_EPISODE';f.sourceRecords.set(episode.episodeId,{...fixtureGameEpisodeSources(episode),advice:[source]});assert.equal(f.repository.admit(episode),true);const m=f.memories.saveGameProjection(projection(episode,f.now()));assert.ok(f.memories.activateGameCandidate(f.owner.assistantId,m.id,f.owner.principalId,1));
 f.memories.forget(f.owner.assistantId,f.human.id,f.owner.principalId);assert.equal(f.repository.get(f.owner,episode.episodeId),null);assert.equal(f.db.connection.prepare('SELECT content FROM memories WHERE id=?').get(m.id)!.content,'');assert.equal(f.db.connection.prepare('SELECT payload_json FROM game_help_items WHERE help_id=?').get(item.helpId)!.payload_json,null);assert.equal(f.memories.get(f.owner.assistantId,second.id)!.content,'User stated: PRIVATE_SECOND_ADVICE');assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM game_episode_advice_sources WHERE source_json IS NOT NULL').get()!.n,0);
});


test('migration66 preserves exact applied history, existing memory and monotonic budget/help/source clocks',t=>{
 const dir=mkdtempSync(join(tmpdir(),'game-advice-upgrade-')),path=join(dir,'state.sqlite');let db=new Database({path,migrations:loadMigrations().filter(m=>m.id<=65)});const previous=db.migrate();new MemoryRepository(db).save({id:'old-source',assistantId:'old-assistant',content:'Preserved original source',provenance:{actor:'old-owner'},lifecycle:{status:'candidate',revision:1},createdAt:new Date().toISOString()});db.exec('UPDATE game_experience_clock SET observed_at=12345');db.exec('UPDATE game_help_clock SET observed_at=23456');db.exec('UPDATE activity_metadata_clock SET observed_at=34567');const before=db.connection.prepare('SELECT * FROM memories').all();db.close();db=new Database({path});t.after(()=>db.close());t.after(()=>rmSync(dir,{recursive:true,force:true}));const current=db.migrate();assert.deepEqual(current.slice(0,previous.length),previous);assert.deepEqual(current.slice(previous.length).map(m=>m.id),[66,67,68,69]);assert.deepEqual(db.connection.prepare('SELECT * FROM memories').all(),before);assert.equal(db.connection.prepare('SELECT observed_at FROM game_experience_clock').get()!.observed_at,12345);assert.equal(db.connection.prepare('SELECT observed_at FROM game_help_clock').get()!.observed_at,23456);assert.equal(db.connection.prepare('SELECT observed_at FROM activity_metadata_clock').get()!.observed_at,34567);assert.equal(db.connection.prepare('SELECT count(*) AS n FROM game_episode_advice_sources').get()!.n,0);assert.equal(db.connection.prepare('SELECT count(*) AS n FROM game_start_claims').get()!.n,0);
});
