import assert from 'node:assert/strict';
import test from 'node:test';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Database} from '../src/database.ts';
import {MemoryRepository,type GameMemorySourceOptions} from '../src/memory.ts';
import {fixtureEpisode,projection} from '../../runtime/test/fixtures/game-memory.ts';
function setup(t:import('node:test').TestContext){let now=Date.now(),enabled=true,current=true;const e=fixtureEpisode(now),db=new Database({path:':memory:'});db.migrate();t.after(()=>db.close());const options:GameMemorySourceOptions={maximumCandidates:2,resolveSource:b=>b.episodeId===e.episodeId?structuredClone(e):null,memoryPolicyCurrent:()=>enabled,sourceCurrent:()=>current,now:()=>now};const repo=new MemoryRepository(db,options);return {db,e,repo,options,now:()=>now,advance:(ms:number)=>now+=ms,disable:()=>enabled=false,withdraw:()=>current=false,make:()=>projection(e,now)};}
test('typed candidate uses existing durable memories without a fake Human transcript, recall, reinforcement or learning activation',t=>{const f=setup(t),saved=f.repo.saveGameProjection(f.make());assert.equal(f.repo.get(f.e.scope.assistantId,saved.id)!.content,f.e.summary);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM memories').get()!.n,1);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM automatic_memory_work').get()!.n,0);assert.deepEqual(f.repo.contextRecords(f.e.scope.assistantId,f.e.scope.principalId),[]);assert.throws(()=>f.repo.transition(f.e.scope.assistantId,saved.id,'active',f.e.scope.principalId),/source-aware/);assert.throws(()=>f.repo.proposeCorrection(f.e.scope.assistantId,saved.id,'Pretend it succeeded',f.e.scope.principalId),/source-aware/);assert.throws(()=>f.repo.admitAutomatic([saved],f.e.scope.principalId,false),/typed memory/);});
test('unconfigured source host and unavailable independent memory consent deny game candidate writes',t=>{const f=setup(t);assert.throws(()=>new MemoryRepository(f.db).saveGameProjection(f.make()),/unavailable/);f.disable();assert.throws(()=>f.repo.saveGameProjection(f.make()),/unavailable/);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM memories').get()!.n,0);});
for(const state of ['policy','source','expiry','rollback']as const)test('read and search fence '+state+' without promoting stale game truth',t=>{const f=setup(t),saved=f.repo.saveGameProjection(f.make());if(state==='policy')f.disable();if(state==='source')f.withdraw();if(state==='expiry')f.advance(60000);if(state==='rollback')f.advance(-1);assert.equal(f.repo.get(f.e.scope.assistantId,saved.id),undefined);assert.deepEqual(f.repo.search(f.e.scope.assistantId,'gate'),[]);assert.deepEqual(f.repo.contextRecords(f.e.scope.assistantId,f.e.scope.principalId),[]);});
test('same event cannot be retained twice with a new memory ID; forgetting retains opaque exclusion and erases payload/history',t=>{const f=setup(t),saved=f.repo.saveGameProjection(f.make());assert.throws(()=>f.repo.saveGameProjection(f.make()),/already retained/);assert.ok(f.repo.forget(f.e.scope.assistantId,saved.id,f.e.scope.principalId,'forget',1));const raw=f.db.connection.prepare('SELECT content,provenance_json FROM memories WHERE id=?').get(saved.id)!;assert.equal(raw.content,'');assert.ok(!String(raw.provenance_json).includes(f.e.summary));assert.ok(!String(raw.provenance_json).includes(f.e.episodeId));assert.throws(()=>f.repo.saveGameProjection(f.make()),/already retained/);assert.ok(!JSON.stringify(f.repo.history(f.e.scope.assistantId,saved.id)).includes(f.e.summary));});
test('forget remains available to the original actor after source or consent withdrawal, and cannot erase another actor source',t=>{const f=setup(t),saved=f.repo.saveGameProjection(f.make());assert.throws(()=>f.repo.forget(f.e.scope.assistantId,saved.id,randomUUID()),/owner/);f.disable();f.withdraw();assert.ok(f.repo.forget(f.e.scope.assistantId,saved.id,f.e.scope.principalId));assert.equal(f.db.connection.prepare('SELECT content FROM memories WHERE id=?').get(saved.id)!.content,'');});
test('consent withdrawal during the actual transaction rolls back both memory and lifecycle writes',t=>{const f=setup(t);f.options.memoryPolicyCurrent=()=>true;const host={...f.options,memoryPolicyCurrent:()=>!f.db.connection.prepare('SELECT 1 FROM memories').get()};const repo=new MemoryRepository(f.db,host);assert.throws(()=>repo.saveGameProjection(f.make()),/immutable/);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM memories').get()!.n,0);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM memory_lifecycle_events').get()!.n,0);});
test('raw save and bulk/automatic paths cannot alter canonical source lineage or activate candidates',t=>{const f=setup(t),saved=f.repo.saveGameProjection(f.make());for(const change of [(r:any)=>r.content='Fabricated victory',(r:any)=>r.provenance.relationshipId=randomUUID(),(r:any)=>r.lifecycle.status='active',(r:any)=>r.provenance.gameEpisodeRevision++]){const altered=structuredClone(saved);altered.id=randomUUID();change(altered);assert.throws(()=>f.repo.save(altered));assert.throws(()=>f.repo.saveMany([altered]));}assert.equal(f.repo.list(f.e.scope.assistantId).length,1);});
test('actual SQLite reopen requires the separately current source and memory policy; metadata alone never restores authority',t=>{const dir=mkdtempSync(join(tmpdir(),'game-memory-')),path=join(dir,'memory.sqlite');t.after(()=>rmSync(dir,{recursive:true,force:true}));const now=Date.now(),e=fixtureEpisode(now),options:GameMemorySourceOptions={maximumCandidates:1,resolveSource:()=>structuredClone(e),memoryPolicyCurrent:()=>true,sourceCurrent:()=>true,now:()=>now};let db=new Database({path});db.migrate();const saved=new MemoryRepository(db,options).saveGameProjection(projection(e,now));db.close();db=new Database({path});db.migrate();t.after(()=>db.close());assert.equal(new MemoryRepository(db).get(e.scope.assistantId,saved.id),undefined);assert.equal(new MemoryRepository(db,{...options,sourceCurrent:()=>false}).get(e.scope.assistantId,saved.id),undefined);assert.equal(new MemoryRepository(db,options).get(e.scope.assistantId,saved.id)!.content,e.summary);assert.deepEqual(new MemoryRepository(db,options).contextRecordIds(e.scope.assistantId,e.scope.principalId),[]);});
test('reload and paraphrase cannot turn one source family into independent memories',t=>{const f=setup(t);f.repo.saveGameProjection(f.make());f.e.episodeId=randomUUID();f.e.scope.runId=randomUUID();f.e.scope.timelineId=randomUUID();f.e.summary='The same source event, summarized differently after reload.';assert.throws(()=>f.repo.saveGameProjection(f.make()),/already retained/);});
test('erasure cannot reset the finite opaque source-fence capacity',t=>{const f=setup(t),repo=new MemoryRepository(f.db,{...f.options,maximumCandidates:1}),saved=repo.saveGameProjection(f.make());repo.forget(f.e.scope.assistantId,saved.id,f.e.scope.principalId);f.e.episodeId=randomUUID();f.e.independenceKey=randomUUID();assert.throws(()=>repo.saveGameProjection(f.make()),/capacity/);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM memories').get()!.n,1);});
test('bulk persistence is atomic when a later source is unavailable',t=>{const f=setup(t),saved=f.repo.saveGameProjection(f.make()),good={id:randomUUID(),assistantId:f.e.scope.assistantId,content:'Ordinary independently authored fixture',createdAt:new Date(f.now()).toISOString(),provenance:{actor:f.e.scope.principalId},lifecycle:{status:'candidate',revision:1}},bad=structuredClone(saved);bad.id=randomUUID();bad.provenance.gameEpisodeDigest='f'.repeat(64);assert.throws(()=>f.repo.saveMany([good,bad]));assert.equal(f.repo.get(good.assistantId,good.id),undefined);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM memories').get()!.n,1);});

function enableDurableConsent(f:ReturnType<typeof setup>){f.db.connection.prepare('INSERT INTO automatic_memory_policies VALUES(?,?,?,?,?,?,?)').run('test-only:game-activation',f.e.scope.principalId,f.e.scope.assistantId,f.e.scope.relationshipId,1,1,new Date(f.now()).toISOString());}
test('typed activation requires separate durable consent, exact actor and candidate CAS',t=>{const f=setup(t),m=f.repo.saveGameProjection(f.make());assert.throws(()=>f.repo.activateGameCandidate(m.assistantId,m.id,f.e.scope.principalId,1),/consent/);enableDurableConsent(f);assert.equal(f.repo.activateGameCandidate(m.assistantId,m.id,randomUUID(),1),undefined);assert.equal(f.repo.activateGameCandidate(m.assistantId,m.id,f.e.scope.principalId,2),undefined);const active=f.repo.activateGameCandidate(m.assistantId,m.id,f.e.scope.principalId,1)!;assert.equal(active.lifecycle.status,'active');assert.equal(active.lifecycle.revision,2);assert.equal((active.provenance.canonical as any).status,'active');assert.equal(active.lifecycle.factuality,'unverified');assert.equal(active.lifecycle.lastReinforcedAt,null);assert.deepEqual(f.repo.contextRecordIds(m.assistantId,f.e.scope.principalId),[m.id]);assert.equal(f.repo.activateGameCandidate(m.assistantId,m.id,f.e.scope.principalId,1),undefined);});
test('activation rollback leaves candidate intact when source withdraws after durable active write',t=>{const f=setup(t);enableDurableConsent(f);const host={...f.options,sourceCurrent:()=>!(f.db.connection.prepare("SELECT 1 FROM memories WHERE json_extract(lifecycle_json,'$.status')='active'").get())},repo=new MemoryRepository(f.db,host),m=repo.saveGameProjection(f.make());assert.throws(()=>repo.activateGameCandidate(m.assistantId,m.id,f.e.scope.principalId,1),/changed during/);assert.equal(repo.get(m.assistantId,m.id)!.lifecycle.status,'candidate');assert.equal(repo.history(m.assistantId,m.id).length,1);});
test('activation rollback rechecks durable consent after source callbacks',t=>{const f=setup(t);enableDurableConsent(f);const repo=new MemoryRepository(f.db,{...f.options,sourceCurrent:()=>{if(f.db.connection.prepare("SELECT 1 FROM memories WHERE json_extract(lifecycle_json,'$.status')='active'").get())f.db.exec('UPDATE automatic_memory_policies SET enabled=0');return true;}}),m=repo.saveGameProjection(f.make());assert.throws(()=>repo.activateGameCandidate(m.assistantId,m.id,f.e.scope.principalId,1),/changed during/);assert.equal(repo.get(m.assistantId,m.id)!.lifecycle.status,'candidate');assert.equal(f.db.connection.prepare('SELECT enabled FROM automatic_memory_policies').get()!.enabled,1);});
test('active prepared-memory boundary changes with source withdrawal and expiry before recall',t=>{for(const cause of ['source','expiry']){const f=setup(t);enableDurableConsent(f);const m=f.repo.saveGameProjection(f.make());f.repo.activateGameCandidate(m.assistantId,m.id,f.e.scope.principalId,1);const before=JSON.stringify(f.repo.contextBoundaryRows(m.assistantId,f.e.scope.principalId));if(cause==='source')f.withdraw();else f.advance(60000);assert.notEqual(JSON.stringify(f.repo.contextBoundaryRows(m.assistantId,f.e.scope.principalId)),before);assert.deepEqual(f.repo.contextRecordIds(m.assistantId,f.e.scope.principalId),[]);}});
test('destructive privacy access survives use withdrawal only for exact original actor',t=>{const f=setup(t);enableDurableConsent(f);const m=f.repo.saveGameProjection(f.make());f.repo.activateGameCandidate(m.assistantId,m.id,f.e.scope.principalId,1);f.disable();f.withdraw();assert.equal(f.repo.get(m.assistantId,m.id),undefined);assert.equal(f.repo.getForPrivacy(m.assistantId,m.id,randomUUID()),undefined);assert.equal(f.repo.getForPrivacy(m.assistantId,m.id,f.e.scope.principalId)!.content,f.e.summary);assert.equal(f.repo.transition(m.assistantId,m.id,'invalidated',f.e.scope.principalId,'privacy',2)!.lifecycle.status,'invalidated');assert.equal((f.repo.getForPrivacy(m.assistantId,m.id,f.e.scope.principalId)!.provenance.canonical as any).status,'invalidated');assert.ok(f.repo.forget(m.assistantId,m.id,f.e.scope.principalId,'forget',3));assert.equal(f.db.connection.prepare('SELECT content FROM memories WHERE id=?').get(m.id)!.content,'');});
