import assert from "node:assert/strict"; import { mkdtemp, rm } from "node:fs/promises"; import { tmpdir } from "node:os"; import { join } from "node:path"; import { test } from "node:test"; import { Database } from "../src/database.ts"; import { MemoryRepository } from "../src/memory.ts";
test("memory is assistant scoped and immutable", () => { const repo = new MemoryRepository(); const r = { id: "m1", assistantId: "a1", content: "x", provenance: {}, lifecycle: {}, createdAt: "2026-09-06T00:00:00Z" }; repo.save(r); assert.equal(repo.get("a2", "m1"), undefined); assert.throws(() => repo.save(r), /immutable/); });
test("memory persists through the existing SQLite database and restart", async (t) => { const root = await mkdtemp(join(tmpdir(), "lifestream-memory-")); t.after(() => rm(root, { recursive: true, force: true })); const path = join(root, "state.sqlite"); const first = new Database({ path }); first.migrate(); const record = { id: "m1", assistantId: "a1", content: "Prefers concise answers", provenance: { source: "conversation-1" }, lifecycle: { status: "active", revision: 1 }, createdAt: "2026-09-06T00:00:00Z" }; const repo = new MemoryRepository(first); repo.save(record); assert.deepEqual(repo.get("a1", "m1"), record); assert.equal(first.connection.prepare("SELECT event_type FROM memory_lifecycle_events WHERE memory_id = ? AND revision = 1").get("m1")?.event_type, "created"); first.close(); const second = new Database({ path }); second.migrate(); t.after(() => second.close()); assert.deepEqual(new MemoryRepository(second).list("a1"), [record]); assert.equal(new MemoryRepository(second).get("a2", "m1"), undefined); assert.throws(() => new MemoryRepository(second).save(record), /immutable/); });
test("memory lifecycle transition uses an atomic revision predicate", async (t) => { const root = await mkdtemp(join(tmpdir(), "lifestream-memory-cas-")); t.after(() => rm(root, { recursive: true, force: true })); const database = new Database({ path: join(root, "state.sqlite") }); database.migrate(); const repo = new MemoryRepository(database); repo.save({ id: "m1", assistantId: "a1", content: "x", provenance: {}, lifecycle: { status: "candidate", revision: 1 }, createdAt: "2026-09-06T00:00:00Z" }); assert.equal(repo.transition("a1", "m1", "active", "human", undefined, 1)?.lifecycle.status, "active"); assert.throws(() => repo.transition("a1", "m1", "invalidated", "stale", undefined, 1), /revision conflict/); assert.equal(repo.history("a1", "m1").length, 2); database.close(); });
test("memory correction proposals allocate journal revisions inside the transaction", async (t) => { const root = await mkdtemp(join(tmpdir(), "lifestream-memory-correction-")); t.after(() => rm(root, { recursive: true, force: true })); const database = new Database({ path: join(root, "state.sqlite") }); database.migrate(); const repo = new MemoryRepository(database); repo.save({ id: "m1", assistantId: "a1", content: "x", provenance: {}, lifecycle: { status: "active", revision: 1 }, createdAt: "2026-09-06T00:00:00Z" }); assert.equal(repo.proposeCorrection("a1", "m1", "y", "human")?.revision, 2); assert.equal(repo.proposeCorrection("a1", "m1", "z", "human")?.revision, 3); assert.deepEqual(repo.history("a1", "m1").map((event) => event.revision), [1, 2, 3]); database.close(); });
test("forget removes payload while retaining non-sensitive lifecycle evidence", async (t) => { const root = await mkdtemp(join(tmpdir(), "lifestream-memory-forget-")); t.after(() => rm(root, { recursive: true, force: true })); const database = new Database({ path: join(root, "state.sqlite") }); database.migrate(); const repo = new MemoryRepository(database); repo.save({ id: "m1", assistantId: "a1", content: "private fact", provenance: { sourceId: "source-1" }, lifecycle: { status: "active", revision: 1 }, createdAt: "2026-09-06T00:00:00Z" }); const result = repo.forget("a1", "m1", "human", "source revoked", 1); assert.equal(result?.contentRemoved, true); assert.equal(repo.get("a1", "m1")?.content, ""); assert.equal(repo.get("a1", "m1")?.lifecycle.status, "invalidated"); assert.equal(repo.history("a1", "m1").at(-1)?.eventType, "forgotten"); assert.throws(() => repo.forget("a1", "m1", "stale", "retry", 1), /revision conflict/); database.close(); });

test("reviewed correction supersedes atomically, retains provenance and survives restart", async t => {
  const root = await mkdtemp(join(tmpdir(), "lifestream-reviewed-correction-")); t.after(() => rm(root, { recursive: true, force: true }));
  const path = join(root, "state.sqlite"); const first = new Database({ path }); first.migrate(); const repo = new MemoryRepository(first);
  repo.save({ id: "original", assistantId: "a1", content: "Synthetic old answer", provenance: { source: "synthetic-note" }, lifecycle: { status: "active", revision: 1 }, createdAt: new Date().toISOString() });
  const old = repo.proposeCorrection("a1", "original", "Synthetic stale answer", "human")!;
  const latest = repo.proposeCorrection("a1", "original", "Synthetic revised answer", "human")!;
  assert.throws(() => repo.applyCorrection("a1", "original", old.revision, 1, "human"), /conflict/);
  assert.throws(() => repo.applyCorrection("a2", "original", latest.revision, 1, "human"), /conflict/);
  const corrected = repo.applyCorrection("a1", "original", latest.revision, 1, "human");
  assert.equal(corrected.lifecycle.status, "active"); assert.equal(corrected.provenance.correctionOf, "original"); assert.equal(corrected.provenance.source, "synthetic-note");
  assert.equal(repo.get("a1", "original")?.content, "Synthetic old answer"); assert.equal(repo.get("a1", "original")?.lifecycle.status, "superseded");
  assert.equal(repo.history("a1", "original").at(-1)?.eventType, "correctionApplied");
  assert.throws(() => repo.applyCorrection("a1", "original", latest.revision, 1, "human"), /conflict/); first.close();
  const second = new Database({ path }); second.migrate(); t.after(() => second.close()); const restored = new MemoryRepository(second);
  assert.equal(restored.search("a1", "revised answer")[0]?.id, corrected.id); assert.equal(restored.search("a2", "revised answer").length, 0);
  assert.equal(restored.get("a1", "original")?.lifecycle.supersededBy, corrected.id); assert.equal(restored.history("a1", "original").length, 4);
  restored.save({ id: "candidate", assistantId: "a1", content: "candidate", provenance: {}, lifecycle: { status: "candidate", revision: 1 }, createdAt: new Date().toISOString() });
  const pending = restored.proposeCorrection("a1", "candidate", "corrected candidate", "human")!;
  assert.equal(restored.applyCorrection("a1", "candidate", pending.revision, 1, "human").lifecycle.status, "candidate", "correction does not admit a candidate");
});
