import assert from 'node:assert/strict';
import test from 'node:test';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Database} from '../src/database.ts';
import {VisualMemoryRepository,visualEpisodeSourceDigest} from '../src/visual-memory.ts';
import {visualEpisode,visualOwner} from './fixtures/visual-episode.ts';
import {MemoryRepository} from '../src/memory.ts';
import {validateVisualMemoryProjection,type VisualMemoryProjection,type VisualTransformationConfidence} from '@lifestream/contracts/visual-memory';
import {compareHistoricalAppearance,appearanceComparisonCurrent,type HistoricalAppearanceEpisode} from '../../runtime/src/visual-memory/comparison.ts';
const initial=Date.parse('2026-09-29T12:00:00Z');
function setup(t:import('node:test').TestContext,retentionMs=86400000){let now=initial;t.mock.method(Date,'now',()=>now);const db=new Database({path:':memory:'});db.migrate();t.after(()=>db.close());const repo=new VisualMemoryRepository(db,()=>now),owner=visualOwner();const policy=repo.configure(owner,true,0,retentionMs);return {db,repo,owner,policy,advance:(ms:number)=>now+=ms,now:()=>now,make:(session?:string)=>visualEpisode(owner,policy,now,session)};}
test('typed visual episode retains uncertainty, identity and no raw media or invented owner quote',t=>{
 const f=setup(t),{episode,admission}=f.make();assert.equal(f.repo.admit(f.owner,episode,admission).state,'retained');
 const saved=f.repo.inspect(f.owner,true).episodes[0]!.episode!;assert.equal(saved.state,'retained');assert.equal(saved.observations[0]!.confidence,null);assert.equal(saved.rawMediaRetained,false);assert.equal(saved.memoryRecordId,null);assert.equal(saved.memoryFactuality,'unverified');assert.deepEqual(episode.state,'candidate');
 assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM memories').get()!.n,0);assert.equal(f.db.connection.prepare('SELECT count(*) AS n FROM automatic_memory_work').get()!.n,0);
 assert.equal(f.repo.inspect({...f.owner,principalId:randomUUID()},true).episodes.length,0);assert.equal(f.repo.inspect(f.owner,false).episodes.length,0);
});
test('closed schema and cross-field metadata reject forged evidence and oversized episodes',t=>{
 const f=setup(t);for(const change of [e=>{e.rawMediaRetained=true;},e=>{e.memoryFactuality='verified';},e=>{e.sourceDigest='f'.repeat(64);},e=>{e.sourceObservationIds=[randomUUID()];},e=>{e.observations[0].sourceTurnRef='forged-turn';},e=>{e.memoryRecordId=randomUUID();},e=>{e.summary='é'.repeat(4000);}]){const v=f.make();change(v.episode as any);assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'invalidEpisode');}assert.equal(f.repo.inspect(f.owner,true).episodes.length,0);
});
test('fresh host scope, explicit policy and visual association are independently required',t=>{
 const f=setup(t);let v=f.make();assert.equal(f.repo.admit({...f.owner,principalId:randomUUID()},v.episode,v.admission).state,'policyDenied');
 for(const change of [a=>{a.current=false;},a=>{a.scope.audienceRevision++;},a=>{a.scope.sessionRevision++;},a=>{a.scope.relationshipId=randomUUID();}]){v=f.make();change(v.admission as any);assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'scopeChanged');}
 v=f.make();v.episode.observations[0]!.subject.binding='unidentified';v.episode.sourceDigest=visualEpisodeSourceDigest(v.episode);assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'unattributedSubject');
 v=f.make();v.admission.verifiedSubjectRef='different-visual-subject';assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'unattributedSubject');
 assert.throws(()=>f.repo.configure(visualOwner(),true,0,null),/Invalid/);assert.throws(()=>f.repo.configure(f.owner,true,0,1000),/conflict/);
});
test('source family, observation and frame fences prevent retries, paraphrase and multi-camera reinforcement',t=>{
 const f=setup(t),v=f.make();assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'retained');
 for(const source of ['family','observation','frame']){const w=f.make();if(source==='family'){w.episode.observations[0]!.independenceKey=v.episode.independenceKeys[0]!;w.episode.independenceKeys=[v.episode.independenceKeys[0]!];}if(source==='observation'){w.episode.observations[0]!.observationId=v.episode.sourceObservationIds[0]!;w.episode.sourceObservationIds=[v.episode.sourceObservationIds[0]!];}if(source==='frame')w.episode.observations[0]!.sourceFrameIds=[...v.episode.observations[0]!.sourceFrameIds];w.episode.summary='A differently phrased retry from another camera.';w.episode.sourceDigest=visualEpisodeSourceDigest(w.episode);assert.equal(f.repo.admit(f.owner,w.episode,w.admission).state,'duplicateSource');}
 assert.equal(f.repo.inspect(f.owner,true).episodes.length,1);
});
test('appearance per subject/session and twelve rolling-hour episodes include forgotten evidence in quotas',t=>{
 const f=setup(t),session=randomUUID(),v=f.make(session);assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'retained');assert.equal(f.repo.admit(f.owner,f.make(session).episode,f.make(session).admission).state,'scopeChanged');const same=f.make(session);assert.equal(f.repo.admit(f.owner,same.episode,same.admission).state,'appearanceBound');
 f.repo.forget(f.owner,v.episode.episodeId,1);const forgottenRetry=f.make(session);assert.equal(f.repo.admit(f.owner,forgottenRetry.episode,forgottenRetry.admission).state,'appearanceBound');
 for(let i=1;i<12;i++){const next=f.make(session);next.admission.reason='meaningfulChange';assert.equal(f.repo.admit(f.owner,next.episode,next.admission).state,'retained');}
 let next=f.make(session);next.admission.reason='meaningfulChange';assert.equal(f.repo.admit(f.owner,next.episode,next.admission).state,'sessionBound');
 assert.equal(f.repo.inspect(f.owner,true,2).complete,false);f.advance(3600000);next=f.make(session);next.admission.reason='meaningfulChange';assert.equal(f.repo.admit(f.owner,next.episode,next.admission).state,'retained');
});
test('expiry removes stored payload at the boundary and cannot resurrect after clock rollback',t=>{
 const f=setup(t),v=f.make();v.episode.expiresAt=new Date(f.now()+1000).toISOString();assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'retained');f.advance(1000);const retired=f.repo.inspect(f.owner,true).episodes[0]!;assert.equal(retired.state,'expired');assert.equal(retired.episode,null);f.advance(-500);assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'duplicateSource');assert.equal(f.db.connection.prepare('SELECT payload_json FROM visual_observation_episodes').get()!.payload_json,null);
});
test('stale source, fabricated chronology and excessive retention cannot enter durable memory',t=>{
 const f=setup(t);for(const change of [e=>{e.observations[0].expiresAt=new Date(initial).toISOString();},e=>{e.observations[0].interpretedAt=new Date(initial+1).toISOString();},e=>{e.expiresAt=new Date(initial+86400001).toISOString();},e=>{e.occurredAt=new Date(initial-1).toISOString();}]){const v=f.make();change(v.episode as any);v.episode.sourceDigest=visualEpisodeSourceDigest(v.episode);assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'sourceExpired');}
});

test('memory preserves producer clock-uncertainty intervals while rejecting a future earliest capture or excess uncertainty',t=>{
 const f=setup(t),valid=f.make();valid.episode.observations[0]!.latestCaptureAt=new Date(initial+250).toISOString();valid.episode.sourceDigest=visualEpisodeSourceDigest(valid.episode);assert.equal(f.repo.admit(f.owner,valid.episode,valid.admission).state,'retained');assert.equal(f.repo.inspect(f.owner,true).episodes[0]!.episode!.observations[0]!.latestCaptureAt,new Date(initial+250).toISOString());
 for(const kind of ['earliest','uncertainty']){const v=f.make();v.episode.observations[0]!.latestCaptureAt=new Date(initial+(kind==='earliest'?100:251)).toISOString();if(kind==='earliest'){v.episode.observations[0]!.earliestCaptureAt=new Date(initial+1).toISOString();v.episode.occurredAt=v.episode.observations[0]!.earliestCaptureAt;}v.episode.sourceDigest=visualEpisodeSourceDigest(v.episode);assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'sourceExpired');}
});
test('transaction failure rolls back payload and dedup fences before a successful retry',t=>{
 const f=setup(t),v=f.make();f.db.exec("CREATE TRIGGER fail_visual_sources BEFORE INSERT ON visual_episode_sources BEGIN SELECT RAISE(ABORT,'synthetic failure'); END");assert.throws(()=>f.repo.admit(f.owner,v.episode,v.admission),/synthetic/);assert.equal(f.repo.inspect(f.owner,true).episodes.length,0);f.db.exec('DROP TRIGGER fail_visual_sources');assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'retained');
});
test('forget is scoped, revision guarded and removes content while preserving replay fences',t=>{
 const f=setup(t),v=f.make();assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'retained');assert.throws(()=>f.repo.forget({...f.owner,principalId:randomUUID()},v.episode.episodeId,1),/conflict/);assert.throws(()=>f.repo.forget(f.owner,v.episode.episodeId,2),/conflict/);f.repo.forget(f.owner,v.episode.episodeId,1);assert.equal(f.repo.inspect(f.owner,true).episodes[0]!.state,'forgotten');assert.equal(f.repo.inspect(f.owner,true).episodes[0]!.episode,null);assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'duplicateSource');
});
test('restart preserves typed episodes and fences; policy withdrawal and restore retire payloads and consent',t=>{
 const root=mkdtempSync(join(tmpdir(),'ls-visual-memory-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const path=join(root,'state.sqlite'),owner=visualOwner();let db=new Database({path});db.migrate();let repo=new VisualMemoryRepository(db,()=>initial);let policy=repo.configure(owner,true,0,86400000);const v=visualEpisode(owner,policy,initial);assert.equal(repo.admit(owner,v.episode,v.admission).state,'retained');db.close();db=new Database({path});db.migrate();t.after(()=>db.close());repo=new VisualMemoryRepository(db,()=>initial);assert.equal(repo.inspect(owner,true).episodes[0]!.episode!.sourceDigest,v.episode.sourceDigest);assert.equal(repo.admit(owner,v.episode,v.admission).state,'duplicateSource');policy=repo.configure(owner,false,1,86400000);assert.equal(repo.inspect(owner,true).episodes[0]!.episode,null);assert.equal(repo.admit(owner,v.episode,v.admission).state,'policyDenied');policy=repo.configure(owner,true,2,86400000);const w=visualEpisode(owner,policy,initial);assert.equal(repo.admit(owner,w.episode,w.admission).state,'retained');assert.equal(repo.quarantine(),1);assert.equal(repo.policy(owner).enabled,false);assert.equal(repo.inspect(owner,true).episodes.every(e=>e.episode===null),true);assert.equal(repo.admit(owner,w.episode,w.admission).state,'policyDenied');
});

const transformationEstimate:VisualTransformationConfidence={value:0.8,basis:'Synthetic assessment of source-to-summary fidelity, not appearance truth.',policyRef:'synthetic-projection-policy:1.0.0'};
test('canonical candidate projection needs an attributable transformation estimate and retains unknown perception confidence',t=>{
 const f=setup(t),v=f.make(),memories=new MemoryRepository(f.db);assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'retained');
 assert.equal(f.repo.project(f.owner,v.episode.episodeId,1,null).state,'estimateUnavailable');assert.equal(memories.list(f.owner.assistantId).length,0);
 for(const estimate of [{...transformationEstimate,value:NaN},{...transformationEstimate,value:1.1},{...transformationEstimate,basis:''},{...transformationEstimate,policyRef:''},{...transformationEstimate,unattributed:'extra'}])assert.equal(f.repo.project(f.owner,v.episode.episodeId,1,estimate).state,'invalidEstimate');
 // Durable history can project after its six-second current-camera lifetime.
 f.advance(7000);const result=f.repo.project(f.owner,v.episode.episodeId,1,transformationEstimate);assert.equal(result.state,'projected');assert.ok('memoryId' in result);const record=memories.get(f.owner.assistantId,result.memoryId!)!;
 const episode=f.repo.inspect(f.owner,true).episodes[0]!.episode!,canonical=record.provenance.canonical as VisualMemoryProjection['memoryRecord'];assert.equal(episode.observations[0]!.confidence,null);assert.equal(episode.memoryRecordId,record.id);assert.equal(episode.revision,2);assert.equal(canonical.confidence,0.8);assert.equal(canonical.factuality,'unverified');assert.equal(canonical.provenance.sourceType,'interaction');assert.equal(record.provenance.sourceTurnRef,undefined);assert.equal(canonical.lastReinforcedAt,null);assert.deepEqual(canonical.contradictedBy,[]);assert.equal(canonical.extensions['lifestream.conversationalVision'].transformationConfidence.basis,transformationEstimate.basis);
 const projection:VisualMemoryProjection={schemaVersion:'1.0.0',recordType:'visualMemoryProjection',episode,memoryRecord:canonical};assert.equal(validateVisualMemoryProjection(projection).valid,true);
 for(const change of [(p:VisualMemoryProjection)=>p.memoryRecord.confidence=0.1,(p:VisualMemoryProjection)=>p.memoryRecord.extensions['lifestream.conversationalVision'].episodeRevision++,(p:VisualMemoryProjection)=>p.memoryRecord.provenance.sourceRefs=['fake-turn'],(p:VisualMemoryProjection)=>p.memoryRecord.content='An unrelated summary.']){const copy=structuredClone(projection);change(copy);assert.equal(validateVisualMemoryProjection(copy).valid,false);}
 assert.equal(f.repo.project(f.owner,v.episode.episodeId,2,transformationEstimate).state,'alreadyProjected');assert.equal(memories.list(f.owner.assistantId).length,1);assert.equal(memories.contextRecords(f.owner.assistantId,f.owner.principalId).length,0);
 assert.throws(()=>memories.transition(f.owner.assistantId,record.id,'active',f.owner.principalId),/source-aware/);assert.throws(()=>memories.proposeCorrection(f.owner.assistantId,record.id,'An actual correction must have its own attribution.',f.owner.principalId),/typed source/);
});

test('visual projection lifecycle removes both payloads, preserves fences and never reactivates on rollback',async t=>{
 for(const mode of ['episodeForget','memoryForget','policy','expiry','restore'])await t.test(mode,child=>{
  const f=setup(child),v=f.make(),memories=new MemoryRepository(f.db);assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'retained');const result=f.repo.project(f.owner,v.episode.episodeId,1,transformationEstimate);assert.ok('memoryId' in result);const memoryId=result.memoryId!;
  if(mode==='episodeForget')f.repo.forget(f.owner,v.episode.episodeId,2);if(mode==='memoryForget')memories.forget(f.owner.assistantId,memoryId,f.owner.principalId,'source forgotten',1);if(mode==='policy')f.repo.configure(f.owner,false,1,86400000);if(mode==='expiry')f.advance(86400000);if(mode==='restore')f.repo.quarantine();
  const source=f.repo.inspect(f.owner,true).episodes[0]!;assert.equal(source.episode,null);const record=memories.get(f.owner.assistantId,memoryId)!;assert.equal(record.content,'');assert.equal(record.lifecycle.contentRemoved,true);assert.equal(record.provenance.canonical,undefined);assert.equal(JSON.stringify(memories.history(f.owner.assistantId,memoryId)).includes('blue hat'),false);assert.equal(memories.contextRecords(f.owner.assistantId,f.owner.principalId).length,0);
  f.advance(-1000);assert.equal(f.repo.project(f.owner,v.episode.episodeId,source.revision,transformationEstimate).state,mode==='policy'||mode==='restore'?'policyDenied':'sourceUnavailable');
 });
});

test('projection is owner/revision bound and transaction failure leaves the source unprojected for safe retry',t=>{
 const f=setup(t),v=f.make();assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'retained');assert.equal(f.repo.project({...f.owner,relationshipId:randomUUID()},v.episode.episodeId,1,transformationEstimate).state,'policyDenied');assert.equal(f.repo.project(f.owner,v.episode.episodeId,2,transformationEstimate).state,'sourceUnavailable');
 f.db.exec("CREATE TRIGGER fail_visual_projection BEFORE INSERT ON memory_lifecycle_events BEGIN SELECT RAISE(ABORT,'synthetic projection failure'); END");assert.throws(()=>f.repo.project(f.owner,v.episode.episodeId,1,transformationEstimate),/synthetic projection/);assert.equal(new MemoryRepository(f.db).list(f.owner.assistantId).length,0);assert.equal(f.repo.inspect(f.owner,true).episodes[0]!.episode!.memoryRecordId,null);f.db.exec('DROP TRIGGER fail_visual_projection');assert.equal(f.repo.project(f.owner,v.episode.episodeId,1,transformationEstimate).state,'projected');
});

test('memory inspection/export rejects a lost or corrupted source binding and expired content before scheduled cleanup',t=>{
 const f=setup(t),v=f.make(),memories=new MemoryRepository(f.db);assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'retained');const result=f.repo.project(f.owner,v.episode.episodeId,1,transformationEstimate);assert.ok('memoryId' in result);const memoryId=result.memoryId!;
 const row=f.db.connection.prepare('SELECT provenance_json FROM memories WHERE id=?').get(memoryId)!;const provenance=JSON.parse(String(row.provenance_json));provenance.canonical.extensions['lifestream.conversationalVision'].sourceDigest='f'.repeat(64);f.db.connection.prepare('UPDATE memories SET provenance_json=? WHERE id=?').run(JSON.stringify(provenance),memoryId);assert.equal(memories.get(f.owner.assistantId,memoryId),undefined);assert.equal(memories.list(f.owner.assistantId).length,0);
 f.db.connection.prepare('UPDATE memories SET provenance_json=? WHERE id=?').run(String(row.provenance_json),memoryId);assert.ok(memories.get(f.owner.assistantId,memoryId));t.mock.timers.enable({apis:['Date'],now:initial+86400000});assert.equal(memories.get(f.owner.assistantId,memoryId),undefined);assert.equal(memories.list(f.owner.assistantId).length,0);f.advance(86400000);f.repo.sweep();assert.equal(memories.get(f.owner.assistantId,memoryId)!.content,'');
});

test('exhaustive retained history joins comparison with contrary evidence and fences forgetting without reconstructing erased metadata',t=>{
 const day=86400000,f=setup(t,31*day),contrary=new Set<string>();
 for(let i=0;i<4;i++){const v=f.make();if(i===3){v.episode.observations[0]!.description='Synthetic confirmed participant with positively usable head; no hat visible.';v.episode.summary='Synthetic contrary appearance.';v.episode.sourceDigest=visualEpisodeSourceDigest(v.episode);contrary.add(v.episode.episodeId);}assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'retained');f.advance(day);}
 const now=f.now(),from=now-30*day,window=f.repo.retainedWindow(f.owner,true,from,now);assert.equal(window.complete,true);assert.equal(window.episodes.length,4);assert.ok(window.episodes.every(e=>Date.parse(e.observations[0]!.expiresAt)<now));assert.ok(Object.isFrozen(window.episodes[0]!.observations[0]));assert.equal(f.repo.retainedWindowCurrent(structuredClone(window),true),false);
 const scope={...f.owner,subjectRef:'synthetic-confirmed-subject'};
 // Explicit scripted head/hat assessments qualify only this downstream fixture;
 // the adapter never classifies arbitrary prose or claims real image semantics.
 const episodes:HistoricalAppearanceEpisode[]=window.episodes.map(e=>({scope,sourceFamily:e.independenceKeys[0]!,sessionId:e.scope.sessionId,capturedAtMs:Date.parse(e.occurredAt),attribution:'userConfirmed',headVisibility:'usable',hat:contrary.has(e.episodeId)?'notVisible':'present',limitations:['Scripted assessment; no real image understanding.'],episodeId:e.episodeId,episodeRevision:e.revision,lifecycleRevision:e.revision,lifecycle:'active',retainedUntilMs:Date.parse(e.expiresAt)}));
 const input={scope,nowMs:now,calendarTimeZone:'UTC',relationshipAuthorized:true,visualHistoryAllowed:true,audiencePermits:true,subjectBindingCurrent:true,coverage:{fromMs:from,toMs:now,complete:window.complete,totalEpisodes:episodes.length,boundaryRevision:window.boundaryRevision},current:{scope,sourceFamily:randomUUID(),sessionId:randomUUID(),capturedAtMs:now,attribution:'userConfirmed' as const,headVisibility:'usable' as const,hat:'notVisible' as const,limitations:['Scripted current head assessment.'],observationId:randomUUID(),freshUntilMs:now+6000},episodes};
 const result=compareHistoricalAppearance(input,revision=>revision===window.boundaryRevision&&f.repo.retainedWindowCurrent(window,true));assert.equal(result.status,'qualified');assert.equal(result.numerator,3);assert.equal(result.denominator,4);assert.equal(result.supportingSessions,3);assert.equal(result.supportingDates,3);assert.deepEqual(result.counterexamples,[...contrary]);assert.equal(appearanceComparisonCurrent(result,now),true);
 const id=[...contrary][0]!;f.repo.forget(f.owner,id,1);assert.equal(f.repo.retainedWindowCurrent(window,true),false);assert.equal(appearanceComparisonCurrent(result,now),false);const remaining=f.repo.retainedWindow(f.owner,true,from,now);assert.equal(remaining.complete,false);assert.equal(remaining.reason,'missingSource');assert.equal(remaining.episodes.length,3);assert.equal(compareHistoricalAppearance({...input,coverage:{...input.coverage,complete:false,totalEpisodes:3},episodes:episodes.filter(e=>e.episodeId!==id)},()=>true).reason,'incomplete_coverage');
});

test('history windows reject truncation, unowned scopes, rollback and changed lifecycle boundaries',async t=>{
 for(const mode of ['scope','policy','expiry','rollback','newSource'])await t.test(mode,child=>{
  const f=setup(child),v=f.make();assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'retained');f.advance(10);const now=f.now(),window=f.repo.retainedWindow(f.owner,true,now-86400000,now);assert.equal(window.complete,true);assert.equal(f.repo.retainedWindowCurrent(window,true),true);
  if(mode==='scope')assert.equal(f.repo.retainedWindowCurrent(window,false),false);if(mode==='policy')f.repo.configure(f.owner,false,1,86400000);if(mode==='expiry')f.advance(86400000);if(mode==='rollback')f.advance(-1);if(mode==='newSource'){const next=f.make();assert.equal(f.repo.admit(f.owner,next.episode,next.admission).state,'retained');}
  assert.equal(f.repo.retainedWindowCurrent(window,true),false);if(mode==='scope'||mode==='rollback')assert.equal(f.repo.retainedWindowCurrent(window,true),false);
 });
 const f=setup(t);for(let i=0;i<129;i++){const v=f.make();assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'retained');}f.advance(1);const window=f.repo.retainedWindow(f.owner,true,f.now()-86400000,f.now());assert.equal(window.complete,false);assert.equal(window.reason,'capacityExceeded');assert.equal(window.episodes.length,0);assert.equal(f.repo.retainedWindow({...f.owner,principalId:randomUUID()},true,f.now()-86400000,f.now()).reason,'scopeUnavailable');
});


test('Human visual correction preserves original attribution, appends an entry and retires historical conclusions',t=>{
 const f=setup(t),v=f.make(),memories=new MemoryRepository(f.db);assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'retained');const projected=f.repo.project(f.owner,v.episode.episodeId,1,transformationEstimate);assert.ok('memoryId' in projected);f.advance(1);const boundary=f.repo.retainedWindow(f.owner,true,f.now()-86400000,f.now());
 const correction=f.repo.correct(f.owner,v.episode.episodeId,2,'I was wearing a hood, not a hat.');const row=f.repo.inspect(f.owner,true).episodes[0]!;
 assert.equal(row.episode!.state,'superseded');assert.equal(row.episode!.sourceDigest,v.episode.sourceDigest);assert.deepEqual(row.episode!.observations,v.episode.observations);assert.equal(row.episode!.summary,v.episode.summary);assert.deepEqual(row.episode!.correctionRefs,[correction.correctionId]);assert.equal(row.corrections[0]!.content,'I was wearing a hood, not a hat.');assert.equal(row.corrections[0]!.sourceType,'humanEntry');assert.equal(row.corrections[0]!.actor,f.owner.principalId);assert.equal('sourceTurnRef' in row.corrections[0]!,false);assert.equal('confidence' in row.corrections[0]!,false);
 const record=memories.get(f.owner.assistantId,projected.memoryId!)!;assert.equal(record.content,v.episode.summary);assert.equal(record.lifecycle.status,'contradicted');assert.equal((record.provenance.canonical as VisualMemoryProjection['memoryRecord']).factuality,'unverified');assert.equal(memories.history(f.owner.assistantId,record.id).at(-1)!.eventType,'visualCorrectionApplied');assert.equal(memories.contextRecords(f.owner.assistantId,f.owner.principalId).length,0);assert.equal(f.repo.retainedWindowCurrent(boundary,true),false);assert.equal(f.repo.retainedWindow(f.owner,true,f.now()-86400000,f.now()).complete,false);assert.equal(f.repo.project(f.owner,v.episode.episodeId,3,transformationEstimate).state,'sourceUnavailable');assert.throws(()=>f.repo.correct(f.owner,v.episode.episodeId,2,'Stale correction.'),/conflict/);
});

test('typed correction works without a projection and preserves append-only history through a file restart',t=>{
 const root=mkdtempSync(join(tmpdir(),'ls-visual-correction-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const path=join(root,'state.sqlite'),owner=visualOwner();let db=new Database({path});db.migrate();let repo=new VisualMemoryRepository(db,()=>initial);const policy=repo.configure(owner,true,0,86400000),v=visualEpisode(owner,policy,initial);assert.equal(repo.admit(owner,v.episode,v.admission).state,'retained');repo.correct(owner,v.episode.episodeId,1,'My first explicit correction.');repo.correct(owner,v.episode.episodeId,2,'My second explicit correction.');db.close();db=new Database({path});db.migrate();t.after(()=>db.close());repo=new VisualMemoryRepository(db,()=>initial);assert.deepEqual(repo.inspect(owner,true).episodes[0]!.corrections.map(c=>c.content),['My first explicit correction.','My second explicit correction.']);assert.equal(repo.inspect(owner,true).episodes[0]!.episode!.sourceDigest,v.episode.sourceDigest);assert.equal(new MemoryRepository(db).list(owner.assistantId).length,0);assert.throws(()=>repo.correct({...owner,principalId:randomUUID()},v.episode.episodeId,3,'Wrong scope.'),/unavailable/);
});

test('correction transaction failure preserves original source and permits a revision-bound retry',t=>{
 const f=setup(t),v=f.make();assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'retained');f.repo.project(f.owner,v.episode.episodeId,1,transformationEstimate);f.db.exec("CREATE TRIGGER fail_visual_correction BEFORE INSERT ON memory_lifecycle_events WHEN NEW.event_type='visualUserCorrection' BEGIN SELECT RAISE(ABORT,'synthetic correction failure'); END");assert.throws(()=>f.repo.correct(f.owner,v.episode.episodeId,2,'Real Human entry.'),/synthetic correction/);assert.equal(f.repo.inspect(f.owner,true).episodes[0]!.episode!.state,'retained');assert.equal(f.repo.inspect(f.owner,true).episodes[0]!.corrections.length,0);assert.equal(new MemoryRepository(f.db).list(f.owner.assistantId)[0]!.lifecycle.status,'candidate');f.db.exec('DROP TRIGGER fail_visual_correction');f.repo.correct(f.owner,v.episode.episodeId,2,'Real Human entry.');
});

test('corrected visual payloads and exact Human entries are erased by all source retirement paths',async t=>{
 for(const mode of ['episodeForget','memoryForget','expiry','policy','restore'])await t.test(mode,child=>{
  const f=setup(child),v=f.make(),memories=new MemoryRepository(f.db);assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'retained');const projection=f.repo.project(f.owner,v.episode.episodeId,1,transformationEstimate);assert.ok('memoryId' in projection);f.repo.correct(f.owner,v.episode.episodeId,2,'Exact private Human correction payload.');
  if(mode==='episodeForget')f.repo.forget(f.owner,v.episode.episodeId,3);if(mode==='memoryForget')memories.forget(f.owner.assistantId,projection.memoryId!,f.owner.principalId,'forget',2);if(mode==='expiry')f.advance(86400000);if(mode==='policy')f.repo.configure(f.owner,false,1,86400000);if(mode==='restore')f.repo.quarantine();assert.equal(f.repo.inspect(f.owner,true).episodes[0]!.episode,null);assert.deepEqual(f.repo.inspect(f.owner,true).episodes[0]!.corrections,[]);assert.equal(JSON.stringify(f.db.connection.prepare('SELECT payload_json FROM memory_lifecycle_events').all()).includes('Exact private Human'),false);
 });
});


test('active visual memory requires both consent policies, remains unverified and changes the prepared boundary on retirement',t=>{
 const f=setup(t),v=f.make(),memories=new MemoryRepository(f.db);t.mock.timers.enable({apis:['Date'],now:initial});assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'retained');f.repo.project(f.owner,v.episode.episodeId,1,transformationEstimate);assert.equal(f.repo.activate(f.owner,v.episode.episodeId,2).state,'policyDenied');f.db.connection.prepare('INSERT INTO automatic_memory_policies VALUES (?,?,?,?,?,?,?)').run('synthetic-owned-policy',f.owner.principalId,f.owner.assistantId,f.owner.relationshipId,1,1,new Date(initial).toISOString());
 assert.equal(memories.contextBoundaryRows(f.owner.assistantId,f.owner.principalId).length,0);assert.equal(f.repo.activate(f.owner,v.episode.episodeId,2).state,'active');const active=memories.contextRecords(f.owner.assistantId,f.owner.principalId)[0]!;assert.equal(active.lifecycle.status,'active');assert.equal(active.lifecycle.factuality,'unverified');assert.equal(active.lifecycle.lastReinforcedAt,null);assert.equal(active.provenance.sourceTurnRef,undefined);assert.equal(active.provenance.visualOccurredAt,v.episode.occurredAt);assert.equal(memories.contextBoundaryRows(f.owner.assistantId,f.owner.principalId).length,1);assert.equal(f.repo.activate(f.owner,v.episode.episodeId,2).state,'alreadyActive');
 f.repo.correct(f.owner,v.episode.episodeId,2,'My explicit correction.');assert.equal(memories.contextRecords(f.owner.assistantId,f.owner.principalId).length,0);assert.equal(memories.contextBoundaryRows(f.owner.assistantId,f.owner.principalId).length,0);assert.equal(memories.get(f.owner.assistantId,active.id)!.content,v.episode.summary);
});

test('active visual reads and cache boundaries refuse expiry, rollback, consent loss and corrupt metadata before cleanup',async t=>{
 for(const mode of ['expiryRollback','ordinary','visual','metadata'])await t.test(mode,child=>{
  const f=setup(child),v=f.make(),memories=new MemoryRepository(f.db);child.mock.timers.enable({apis:['Date'],now:initial});f.db.connection.prepare('INSERT INTO automatic_memory_policies VALUES (?,?,?,?,?,?,?)').run('synthetic-owned-policy',f.owner.principalId,f.owner.assistantId,f.owner.relationshipId,1,1,new Date(initial).toISOString());assert.equal(f.repo.admit(f.owner,v.episode,v.admission).state,'retained');const result=f.repo.project(f.owner,v.episode.episodeId,1,transformationEstimate);assert.ok('memoryId' in result);assert.equal(f.repo.activate(f.owner,v.episode.episodeId,2).state,'active');assert.equal(memories.contextRecords(f.owner.assistantId,f.owner.principalId).length,1);
  if(mode==='expiryRollback')child.mock.timers.tick(86400000);if(mode==='ordinary')f.db.exec('UPDATE automatic_memory_policies SET enabled=0');if(mode==='visual')f.db.exec('UPDATE visual_memory_policies SET enabled=0');if(mode==='metadata'){const row=f.db.connection.prepare('SELECT provenance_json FROM memories').get()!;const p=JSON.parse(String(row.provenance_json));p.visualOccurredAt=new Date(initial+1000).toISOString();f.db.connection.prepare('UPDATE memories SET provenance_json=?').run(JSON.stringify(p));}
  assert.equal(memories.contextRecords(f.owner.assistantId,f.owner.principalId).length,0);assert.equal(memories.contextRecordIds(f.owner.assistantId,f.owner.principalId).length,0);if(mode!=='metadata')assert.equal(memories.contextBoundaryRows(f.owner.assistantId,f.owner.principalId).length,0);if(mode==='expiryRollback'){child.mock.timers.setTime(initial);assert.equal(memories.contextRecords(f.owner.assistantId,f.owner.principalId).length,0);assert.equal(memories.contextBoundaryRows(f.owner.assistantId,f.owner.principalId).length,0);}
 });
});
