import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
import {PwceIncidentClient} from '../src/incidents.ts';
import {EXPECTED_PWCE_INCIDENT_BUNDLE as contract} from '../src/incident-bundle.ts';
import {EXPECTED_PWCE_PROFILE,EXPECTED_PWCE_ARTIFACTS,EXPECTED_PWCE_GENERATED_CLIENT_SHA256} from '../src/client.ts';
const operations=['context.getPreparedInputs','context.query','evidence.get','events.subscribe','authority.evaluate','authority.authorizeDispatch','authority.getGrants','capabilities.getSnapshot','capabilities.invoke','capabilities.getInvocation','trace.publish','health.get'];
const profile={...EXPECTED_PWCE_PROFILE,schemaStatus:'published',operationCatalog:operations.map(operation=>({operation}))},core={bundleId:profile.bundleId,bundleVersion:profile.bundleVersion,bundleDigest:profile.schemaDigest,artifacts:EXPECTED_PWCE_ARTIFACTS,generatedClient:{path:'src/gateway/generated-client.js',sha256:EXPECTED_PWCE_GENERATED_CLIENT_SHA256}};
const identity=()=>({assistantRef:'assistant.one',endpointRef:'endpoint.one',participantRefs:['owner'],audienceRef:'solo'});
function fixture(){const bytes=Buffer.from('synthetic media'),now=new Date().toISOString(),state={current:true,drift:false,tamper:false,foreign:false,extra:false,hook:async(_path:string)=>{}};const record={evidenceRef:'pwce:incident:'+randomUUID(),siteRef:'home.one',zoneRef:'zone.demo',eventClass:'door.open',state:'ready',occurredAt:now,lastTriggerAt:now,windowStart:now,windowEnd:now,expiresAt:new Date(Date.now()+86400000).toISOString(),summary:'Synthetic incident.',media:{sha256:createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length,mime:'image/png',actualStart:now,actualEnd:now},limitations:[]},calls:{path:string;body:Record<string,unknown>|null}[]=[];const client=new PwceIncidentClient({baseUrl:'http://fixture',token:'synthetic-incident-token',siteRef:'home.one',worldRef:'world.personal.v1',replay:true,fetchImpl:async(url,init)=>{const path=new URL(String(url)).pathname,body=init?.body?JSON.parse(String(init.body)):null;calls.push({path,body});await state.hook(path);if(path===contract.routes.bundle)return Response.json(state.drift?{...contract,bundleDigest:'wrong'}:contract);if(path==='/gateway/v1/profile')return Response.json(profile);if(path==='/gateway/v1/bundle')return Response.json(core);if(path==='/gateway/v1/authority')return Response.json({authorityContextRef:randomUUID()});if(path===contract.routes.query)return Response.json({profileId:contract.profileId,profileVersion:contract.profileVersion,incidents:[{...record,siteRef:state.foreign?'home.other':record.siteRef,...(state.extra?{rawMedia:'forbidden'}:{})}]});if(path===contract.routes.media)return new Response(state.tamper?Buffer.alloc(bytes.length):bytes,{headers:{'content-type':'image/png','content-length':String(bytes.length),'x-pwce-content-sha256':record.media.sha256}});throw Error('Unexpected route '+path);}});return {client,state,calls,record,current:()=>state.current};}
test('incident reads negotiate exact contracts and keep binary evidence out of the summary',async()=>{const f=fixture(),summary=await f.client.list(identity(),f.current);assert.equal(summary.replay,true);assert.equal(summary.incidents[0]!.evidenceRef,f.record.evidenceRef);assert.equal(f.calls.some(c=>c.path.endsWith('/media')),false);const media=await f.client.media(f.record.evidenceRef,identity(),f.current);assert.equal(media.bytes.toString(),'synthetic media');assert.equal(f.calls.filter(c=>c.path===contract.routes.query).length,3);assert.equal(f.calls.some(c=>/dispatch|capture/.test(c.path)),false);});
test('contract drift, foreign summaries, unexpected raw fields and tampered media are rejected',async()=>{for(const kind of ['drift','foreign','extra'] as const){const f=fixture();f.state[kind]=true;await assert.rejects(f.client.list(identity(),f.current));}const f=fixture();f.state.tamper=true;await assert.rejects(f.client.media(f.record.evidenceRef,identity(),f.current),{code:'incident_media_integrity'});});
test('incident results are fenced by current host scope and caller identity is snapshotted',async()=>{const f=fixture(),id=identity();f.state.hook=async path=>{if(path===contract.routes.bundle)id.participantRefs.push('foreign');};await f.client.list(id,f.current);assert.deepEqual(f.calls.find(c=>c.path===contract.routes.query)!.body!.participantRefs,['owner']);f.state.hook=async path=>{if(path===contract.routes.media)f.state.current=false;};await assert.rejects(f.client.media(f.record.evidenceRef,identity(),f.current),{code:'scope_invalidated'});const blocked=fixture();blocked.state.current=false;await assert.rejects(blocked.client.list(identity(),blocked.current));assert.equal(blocked.calls.length,0);});
test('cancellation prevents a late incident result',async()=>{const f=fixture(),c=new AbortController();f.state.hook=async path=>{if(path===contract.routes.bundle)c.abort();};await assert.rejects(f.client.list(identity(),f.current,c.signal));assert.equal(f.calls.some(call=>call.path===contract.routes.query),false);});
